local _default_val={
    gift_configure={
        seq=0,
        phase=0,
        reward_immortal_coin=150000
    },
    phase_configure={
        reward_buy=150000,
        buy_money=980
    }
}
Config.immortal_coin_fund_auto={
    gift_configure={
        {
            type=0,
            reward_level=35,
            reward_immortal_coin=40000
        },
        {
            type=1,
            seq=1,
            reward_level=40,
            reward_immortal_coin=55000
        },
        {
            type=2,
            seq=2,
            reward_level=45,
            reward_immortal_coin=70000
        },
        {
            type=3,
            seq=3,
            reward_level=50,
            reward_immortal_coin=85000
        },
        {
            type=4,
            seq=4,
            reward_level=55,
            reward_immortal_coin=100000
        },
        {
            type=5,
            phase=1,
            reward_level=58,
            reward_immortal_coin=100000
        },
        {
            type=6,
            seq=1,
            phase=1,
            reward_level=60,
            reward_immortal_coin=120000
        },
        {
            type=7,
            seq=2,
            phase=1,
            reward_level=62,
            reward_immortal_coin=140000
        },
        {
            type=8,
            seq=3,
            phase=1,
            reward_level=64,
            reward_immortal_coin=160000
        },
        {
            type=9,
            seq=4,
            phase=1,
            reward_level=66,
            reward_immortal_coin=180000
        },
        {
            type=10,
            phase=2,
            reward_level=68
        },
        {
            type=11,
            seq=1,
            phase=2,
            reward_level=70,
            reward_immortal_coin=170000
        },
        {
            type=12,
            seq=2,
            phase=2,
            reward_level=72,
            reward_immortal_coin=190000
        },
        {
            type=13,
            seq=3,
            phase=2,
            reward_level=74,
            reward_immortal_coin=210000
        },
        {
            type=14,
            seq=4,
            phase=2,
            reward_level=76,
            reward_immortal_coin=230000
        },
        {
            type=15,
            phase=3,
            reward_level=78
        },
        {
            type=16,
            seq=1,
            phase=3,
            reward_level=80,
            reward_immortal_coin=180000
        },
        {
            type=17,
            seq=2,
            phase=3,
            reward_level=82,
            reward_immortal_coin=210000
        },
        {
            type=18,
            seq=3,
            phase=3,
            reward_level=84,
            reward_immortal_coin=230000
        },
        {
            type=19,
            seq=4,
            phase=3,
            reward_level=86,
            reward_immortal_coin=250000
        },
        {
            type=20,
            phase=4,
            reward_level=88
        },
        {
            type=21,
            seq=1,
            phase=4,
            reward_level=90,
            reward_immortal_coin=180000
        },
        {
            type=22,
            seq=2,
            phase=4,
            reward_level=92,
            reward_immortal_coin=225000
        },
        {
            type=23,
            seq=3,
            phase=4,
            reward_level=94,
            reward_immortal_coin=280000
        },
        {
            type=24,
            seq=4,
            phase=4,
            reward_level=96,
            reward_immortal_coin=300000
        },
        {
            type=25,
            phase=5,
            reward_level=98
        },
        {
            type=26,
            seq=1,
            phase=5,
            reward_level=100,
            reward_immortal_coin=200000
        },
        {
            type=27,
            seq=2,
            phase=5,
            reward_level=102,
            reward_immortal_coin=250000
        },
        {
            type=28,
            seq=3,
            phase=5,
            reward_level=104,
            reward_immortal_coin=320000
        },
        {
            type=29,
            seq=4,
            phase=5,
            reward_level=106,
            reward_immortal_coin=350000
        },
        {
            type=30,
            phase=6,
            reward_level=108
        },
        {
            type=31,
            seq=1,
            phase=6,
            reward_level=110,
            reward_immortal_coin=180000
        },
        {
            type=32,
            seq=2,
            phase=6,
            reward_level=112,
            reward_immortal_coin=300000
        },
        {
            type=33,
            seq=3,
            phase=6,
            reward_level=114,
            reward_immortal_coin=370000
        },
        {
            type=34,
            seq=4,
            phase=6,
            reward_level=116,
            reward_immortal_coin=400000
        }
    },
    phase_configure={
        {
            phase=0,
            reward_buy=55000,
            reward_multiple=810,
            buy_money=300,
            acc_total=405000,
            show_level=32,
            multiple=8.1
        },
        {
            phase=1,
            reward_buy=110000,
            reward_multiple=827,
            buy_money=500,
            acc_total=810000,
            show_level=57,
            multiple=8.199999999999999
        },
        {
            phase=2,
            reward_multiple=859,
            acc_total=1100000,
            show_level=67,
            multiple=8.5
        },
        {
            phase=3,
            reward_multiple=914,
            acc_total=1170000,
            show_level=77,
            multiple=9.1
        },
        {
            phase=4,
            reward_multiple=1004,
            acc_total=1285000,
            show_level=87,
            multiple=10
        },
        {
            phase=5,
            reward_multiple=1109,
            acc_total=1420000,
            show_level=97,
            multiple=11
        },
        {
            phase=6,
            reward_multiple=1211,
            acc_total=1550000,
            show_level=107,
            multiple=12
        }
    },
    other={
        {
            phase=7,
            cfg_ver=3
        }
    }
}
SetConfigDefaultVal(Config.immortal_coin_fund_auto,_default_val,nil,nil,nil)