return {
	
	"protocol/msgadapter",
	"protocol/baseprotocolstruct",

	"protocol/user/protocol_common",

	--logic server
	"protocol/user/protocol_007",
	"protocol/user/protocol_010",
	"protocol/user/protocol_011",
	"protocol/user/protocol_012",
	"protocol/user/protocol_013",
	"protocol/user/protocol_014",
	"protocol/user/protocol_015",
	"protocol/user/protocol_016",
	"protocol/user/protocol_017",
	"protocol/user/protocol_018",
	"protocol/user/protocol_019",
	"protocol/user/protocol_020",
	"protocol/user/protocol_021",
	"protocol/user/protocol_022",
	"protocol/user/protocol_023",
	"protocol/user/protocol_024",
	"protocol/user/protocol_025",
	"protocol/user/protocol_026",
	"protocol/user/protocol_027",
	"protocol/user/protocol_028",
	"protocol/user/protocol_029",
	"protocol/user/protocol_030",
	"protocol/user/protocol_031",
	"protocol/user/protocol_032",
	"protocol/user/protocol_033",
	"protocol/user/protocol_034",
	"protocol/user/protocol_035",
	"protocol/user/protocol_036",
	"protocol/user/protocol_038",
	"protocol/user/protocol_039",
	"protocol/user/protocol_040",
	"protocol/user/protocol_041",
	"protocol/user/protocol_042",
	"protocol/user/protocol_043",
	"protocol/user/protocol_044",
	"protocol/user/protocol_046",
	"protocol/user/protocol_047",
	"protocol/user/protocol_048",
	"protocol/user/protocol_049",
	"protocol/user/protocol_050",
	"protocol/user/protocol_051",
	"protocol/user/protocol_052",
	"protocol/user/protocol_053",
	"protocol/user/protocol_054",
	"protocol/user/protocol_055",
	"protocol/user/protocol_056",
	"protocol/user/protocol_057",
	--login server
	"protocol/user/protocol_070",
	"protocol/user/protocol_071",
	"protocol/user/protocol_081",

	"protocol/user/protocol_090",
	"protocol/user/protocol_091",
	"protocol/user/protocol_092",
	"protocol/user/protocol_095",
	"protocol/user/protocol_098",
	
	"protocol/user/protocol_100",

	"protocol/user/protocol_110",
}