Config.activity_load_auto={
    require_list={
        {
            file_name="wealth_cornucopia"
        },
        {
            file_name="pet_exchange_activity"
        },
        {
            file_name="chongwuledou"
        },
        {
            file_name="pet_loot"
        },
        {
            file_name="looks_new"
        },
        {
            file_name="treasure_activity"
        },
        {
            file_name="exchange_jade"
        },
        {
            file_name="seal_promote"
        },
        {
            file_name="fortune_bag"
        },
        {
            file_name="ustomized_box"
        },
        {
            file_name="extra_bonus"
        },
        {
            file_name="drop_double"
        },
        {
            file_name="assign_horcrux"
        },
        {
            file_name="fengshenzhanling"
        },
        {
            file_name="national_day"
        },
        {
            file_name="gift_rotation"
        },
        {
            file_name="back_reward"
        },
        {
            file_name="joy_seeks_favors"
        },
        {
            file_name="ambassador_activity"
        },
        {
            file_name="trade_discount"
        },
        {
            file_name="word_gift_activity"
        },
        {
            file_name="jiandanqinxin"
        },
        {
            file_name="partner_activity"
        },
        {
            file_name="exp_purchase"
        },
        {
            file_name="activity_main"
        },
        {
            file_name="sign_in_continuity"
        },
        {
            file_name="cow_lucky_exchange"
        },
        {
            file_name="dragon_boat_racing"
        },
        {
            file_name="acc_recharge"
        },
        {
            file_name="immortal_coin_fund"
        },
        {
            file_name="linkage_gift"
        },
        {
            file_name="customs_gift"
        },
        {
            file_name="cow_exchange"
        },
        {
            file_name="monopoly_gift"
        },
        {
            file_name="lingpai_divine"
        },
        {
            file_name="cow_store"
        },
        {
            file_name="spring_festival_store"
        },
        {
            file_name="colorful_illustrations"
        },
        {
            file_name="repel_the_monster"
        },
        {
            file_name="pai_mai_hang"
        },
        {
            file_name="adventure_gift_activity"
        },
        {
            file_name="qm_discount"
        },
        {
            file_name="cool_summer"
        },
        {
            file_name="tujian_treasure"
        },
        {
            file_name="tax_discount"
        },
        {
            file_name="sale_shop_activity"
        },
        {
            file_name="burning_summer"
        },
        {
            file_name="pet_befall"
        },
        {
            file_name="pet_search"
        },
        {
            file_name="divination_activity"
        },
        {
            file_name="animal_race"
        },
        {
            file_name="tianjianghaoli"
        },
        {
            file_name="happy_up_activity"
        },
        {
            file_name="lucky_discount"
        },
        {
            file_name="element_cards"
        },
        {
            file_name="gift_box"
        },
        {
            file_name="month_card"
        },
        {
            file_name="chain_box"
        },
        {
            file_name="lucky_maze"
        },
        {
            file_name="xinfawuliang"
        },
        {
            file_name="buy_one_gold"
        },
        {
            file_name="may_day_activity"
        },
        {
            file_name="little_year_gift"
        },
        {
            file_name="lucky_turntable"
        },
        {
            file_name="give_secret_key"
        },
        {
            file_name="exclusive_gift"
        },
        {
            file_name="discount_carnival"
        },
        {
            file_name="buy_item_validation"
        },
        {
            file_name="gift_randitem"
        },
        {
            file_name="treasure_hunt"
        },
        {
            file_name="rand_activity"
        },
        {
            file_name="day_reward"
        },
        {
            file_name="randactivityopencfg_1"
        },
        {
            file_name="randactivityconfig_1"
        },
        {
            file_name="gift"
        },
        {
            file_name="expense"
        },
        {
            file_name="other"
        }
    }
}