Config.activity_list_auto={
    configure={
        {
            seq=0,
            name="牛气冲天",
            activity_type=3000,
            mod_key=46002,
            reward_item={
                [0]={
                    item_id=28058,
                    num=1,
                    is_bind=1
                },
                [1]={
                    item_id=28059,
                    num=1,
                    is_bind=1
                }
            },
            desc="新年到，程吉祥，参与活动即可获得移动点数，可触发宝箱等奖励"
        },
        {
            seq=1,
            name="小年送礼",
            activity_type=3001,
            mod_key=46003,
            reward_item={
                [0]={
                    item_id=28058,
                    num=1,
                    is_bind=1
                },
                [1]={
                    item_id=28059,
                    num=1,
                    is_bind=1
                }
            },
            desc="小年到，迎新年，根据线索找到对应NPC即可小年登录礼"
        },
        {
            seq=2,
            name="年货节",
            activity_type=3002,
            mod_key=46004,
            reward_item={
                [0]={
                    item_id=28058,
                    num=1,
                    is_bind=1
                },
                [1]={
                    item_id=28059,
                    num=1,
                    is_bind=1
                }
            },
            desc="风风火火年货节，你想要的这里都有！"
        },
        {
            seq=3,
            name="牛运商城",
            activity_type=3003,
            mod_key=46005,
            reward_item={
                [0]={
                    item_id=28058,
                    num=1,
                    is_bind=1
                },
                [1]={
                    item_id=28059,
                    num=1,
                    is_bind=1
                }
            },
            desc="牛运当头送好运，积分兑换送好礼！"
        },
        {
            seq=4,
            name="牛运无边",
            activity_type=3004,
            mod_key=46006,
            reward_item={
                [0]={
                    item_id=28058,
                    num=1,
                    is_bind=1
                },
                [1]={
                    item_id=28059,
                    num=1,
                    is_bind=1
                }
            },
            desc="无边好运送给你，稀有宠物等你拿"
        }
    }
}