local _default_val={
    active={
        type=2,
        act_type=10009,
        need_count=10,
        integral_active=40,
        is_every_time=0,
        is_remind=0,
        is_off=0,
        level_min=1,
        level_max=120,
        exp=0,
        coin=10000,
        strength=0,
        sort=3,
        desc="完成今日<color=#B84300>门派任务</color>",
        recom_order=-1,
        need_goto=0,
        open_day=0,
        is_special=0
    },
    active_reward={
        seq=1,
        level_min=1,
        level_max=39,
        integral_active=50,
        coin=0,
        gold=0,
        power=0,
        exp=0
    },
    linkage_act={
        seq=5,
        act_type=2168
    },
    week_activity={
        need_count=1,
        show_type=1,
        integral_active=20
    },
    week_activity_reward={
        seq=1,
        integral_active=50,
        level_min=1,
        level_max=49
    },
    turntable_task={
        seq=0,
        task_type=1,
        turntable_num=2
    },
    turntable_reward_group={
        reward_group=1,
        index=1
    },
    one_click_list={
        cost_gold=10
    }
}
local _itemlist={
    i_31322_2_1={
        item_id=31322,
        num=2,
        is_bind=1
    },
    i_27850_1_1={
        item_id=27850,
        num=1,
        is_bind=1
    },
    i_27303_1_1={
        item_id=27303,
        num=1,
        is_bind=1
    },
    i_27397_3_1={
        item_id=27397,
        num=3,
        is_bind=1
    },
    i_24557_1_1={
        item_id=24557,
        num=1,
        is_bind=1
    },
    i_24518_1_1={
        item_id=24518,
        num=1,
        is_bind=1
    },
    i_24557_3_1={
        item_id=24557,
        num=3,
        is_bind=1
    },
    i_28820_1_1={
        item_id=28820,
        num=1,
        is_bind=1
    },
    i_24326_1_1={
        item_id=24326,
        num=1,
        is_bind=1
    },
    i_28828_1_1={
        item_id=28828,
        num=1,
        is_bind=1
    },
    i_27855_1_1={
        item_id=27855,
        num=1,
        is_bind=1
    },
    i_27855_2_1={
        item_id=27855,
        num=2,
        is_bind=1
    },
    i_29125_5_1={
        item_id=29125,
        num=5,
        is_bind=1
    },
    i_29125_10_1={
        item_id=29125,
        num=10,
        is_bind=1
    },
    i_29125_15_1={
        item_id=29125,
        num=15,
        is_bind=1
    },
    i_26364_1_1={
        item_id=26364,
        num=1,
        is_bind=1
    },
    i_26692_1_1={
        item_id=26692,
        num=1,
        is_bind=1
    },
    i_26703_1_1={
        item_id=26703,
        num=1,
        is_bind=1
    },
    i_28522_1_1={
        item_id=28522,
        num=1,
        is_bind=1
    },
    i_22050_2_1={
        item_id=22050,
        num=2,
        is_bind=1
    },
    i_25517_3_1={
        item_id=25517,
        num=3,
        is_bind=1
    },
    i_22051_2_1={
        item_id=22051,
        num=2,
        is_bind=1
    },
    i_27821_2_1={
        item_id=27821,
        num=2,
        is_bind=1
    },
    i_26502_1_1={
        item_id=26502,
        num=1,
        is_bind=1
    },
    i_22051_1_1={
        item_id=22051,
        num=1,
        is_bind=1
    },
    i_27821_1_1={
        item_id=27821,
        num=1,
        is_bind=1
    },
    i_22050_1_1={
        item_id=22050,
        num=1,
        is_bind=1
    },
    i_24326_2_1={
        item_id=24326,
        num=2,
        is_bind=1
    },
    i_24326_3_1={
        item_id=24326,
        num=3,
        is_bind=1
    },
    i_24326_4_1={
        item_id=24326,
        num=4,
        is_bind=1
    }
}
Config.activedegree_auto={
    active={
        {
            type=0,
            act_type=10044,
            need_count=0,
            integral_active=0,
            level_min=34,
            coin=0,
            sort=1,
            desc="<color=#B84300>万灵大事件</color> 限时开启！"
        },
        {
            type=8,
            act_type=10020,
            is_remind=1,
            level_max=39,
            exp=90000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            sort=2
        },
        {
            type=8,
            act_type=10020,
            is_remind=1,
            level_min=40,
            level_max=44,
            exp=215000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            sort=2
        },
        {
            type=8,
            act_type=10020,
            is_remind=1,
            level_min=45,
            level_max=49,
            exp=230000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            sort=2
        },
        {
            type=8,
            act_type=10020,
            is_remind=1,
            level_min=50,
            level_max=54,
            exp=235000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            sort=2
        },
        {
            type=8,
            act_type=10020,
            is_remind=1,
            level_min=55,
            level_max=59,
            exp=245000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            sort=2
        },
        {
            type=8,
            act_type=10020,
            is_remind=1,
            level_min=60,
            level_max=64,
            exp=257000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            sort=2
        },
        {
            type=8,
            act_type=10020,
            is_remind=1,
            level_min=65,
            level_max=69,
            exp=270000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            sort=2
        },
        {
            type=8,
            act_type=10020,
            is_remind=1,
            level_min=70,
            level_max=74,
            exp=277000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            sort=2
        },
        {
            type=8,
            act_type=10020,
            is_remind=1,
            level_min=75,
            level_max=79,
            exp=289000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            sort=2
        },
        {
            type=8,
            act_type=10020,
            is_remind=1,
            level_min=80,
            level_max=84,
            exp=297000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            sort=2
        },
        {
            type=8,
            act_type=10020,
            is_remind=1,
            level_min=85,
            level_max=89,
            exp=309000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            sort=2
        },
        {
            type=8,
            act_type=10020,
            is_remind=1,
            level_min=90,
            level_max=94,
            exp=317000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            sort=2
        },
        {
            type=8,
            act_type=10020,
            is_remind=1,
            level_min=95,
            level_max=99,
            exp=329000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            sort=2
        },
        {
            type=8,
            act_type=10020,
            is_remind=1,
            level_min=100,
            level_max=104,
            exp=337000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            sort=2
        },
        {
            type=8,
            act_type=10020,
            is_remind=1,
            level_min=105,
            level_max=109,
            exp=349000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            sort=2
        },
        {
            type=8,
            act_type=10020,
            is_remind=1,
            level_min=110,
            level_max=114,
            exp=356000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            sort=2
        },
        {
            type=8,
            act_type=10020,
            is_remind=1,
            level_min=115,
            exp=364000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            sort=2
        },
        {
            type=23,
            act_type=10041,
            need_count=1,
            level_max=39,
            exp=65000,
            sort=4,
            desc="组队挑战<color=#B84300>万灵话本</color>"
        },
        {
            type=23,
            act_type=10041,
            need_count=1,
            level_min=40,
            level_max=44,
            exp=160000,
            sort=4,
            desc="组队挑战<color=#B84300>万灵话本</color>"
        },
        {
            type=23,
            act_type=10041,
            need_count=1,
            level_min=45,
            level_max=49,
            exp=167500,
            sort=4,
            desc="组队挑战<color=#B84300>万灵话本</color>"
        },
        {
            type=23,
            act_type=10041,
            need_count=1,
            level_min=50,
            level_max=54,
            exp=169000,
            sort=4,
            desc="组队挑战<color=#B84300>万灵话本</color>"
        },
        {
            type=23,
            act_type=10041,
            need_count=1,
            level_min=55,
            level_max=59,
            exp=188000,
            sort=4,
            desc="组队挑战<color=#B84300>万灵话本</color>"
        },
        {
            type=23,
            act_type=10041,
            need_count=1,
            level_min=60,
            level_max=64,
            exp=197000,
            sort=4,
            desc="组队挑战<color=#B84300>万灵话本</color>"
        },
        {
            type=23,
            act_type=10041,
            need_count=1,
            level_min=65,
            level_max=69,
            exp=210000,
            sort=4,
            desc="组队挑战<color=#B84300>万灵话本</color>"
        },
        {
            type=23,
            act_type=10041,
            need_count=1,
            level_min=70,
            level_max=74,
            exp=217000,
            sort=4,
            desc="组队挑战<color=#B84300>万灵话本</color>"
        },
        {
            type=23,
            act_type=10041,
            need_count=1,
            level_min=75,
            level_max=79,
            exp=229000,
            sort=4,
            desc="组队挑战<color=#B84300>万灵话本</color>"
        },
        {
            type=23,
            act_type=10041,
            need_count=1,
            level_min=80,
            level_max=84,
            exp=237000,
            sort=4,
            desc="组队挑战<color=#B84300>万灵话本</color>"
        },
        {
            type=23,
            act_type=10041,
            need_count=1,
            level_min=85,
            level_max=89,
            exp=249000,
            sort=4,
            desc="组队挑战<color=#B84300>万灵话本</color>"
        },
        {
            type=23,
            act_type=10041,
            need_count=1,
            level_min=90,
            level_max=94,
            exp=257000,
            sort=4,
            desc="组队挑战<color=#B84300>万灵话本</color>"
        },
        {
            type=23,
            act_type=10041,
            need_count=1,
            level_min=95,
            level_max=99,
            exp=269000,
            sort=4,
            desc="组队挑战<color=#B84300>万灵话本</color>"
        },
        {
            type=23,
            act_type=10041,
            need_count=1,
            level_min=100,
            level_max=104,
            exp=277000,
            sort=4,
            desc="组队挑战<color=#B84300>万灵话本</color>"
        },
        {
            type=23,
            act_type=10041,
            need_count=1,
            level_min=105,
            level_max=109,
            exp=289000,
            sort=4,
            desc="组队挑战<color=#B84300>万灵话本</color>"
        },
        {
            type=23,
            act_type=10041,
            need_count=1,
            level_min=110,
            level_max=114,
            exp=296000,
            sort=4,
            desc="组队挑战<color=#B84300>万灵话本</color>"
        },
        {
            type=23,
            act_type=10041,
            need_count=1,
            level_min=115,
            exp=304000,
            sort=4,
            desc="组队挑战<color=#B84300>万灵话本</color>"
        },
        {
            need_count=20,
            is_remind=1,
            level_max=30,
            exp=90000,
            coin=20000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            desc="完成今日<color=#B84300>三界除魔</color>"
        },
        {
            need_count=20,
            is_remind=1,
            level_min=31,
            level_max=39,
            exp=90000,
            coin=20000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            desc="完成今日<color=#B84301>三界除魔</color>"
        },
        {
            need_count=20,
            is_remind=1,
            level_min=40,
            level_max=44,
            exp=215000,
            coin=20000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            desc="完成今日<color=#B84302>三界除魔</color>"
        },
        {
            need_count=20,
            is_remind=1,
            level_min=45,
            level_max=49,
            exp=230000,
            coin=20000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            desc="完成今日<color=#B84303>三界除魔</color>"
        },
        {
            need_count=20,
            is_remind=1,
            level_min=50,
            level_max=54,
            exp=235000,
            coin=20000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            desc="完成今日<color=#B84304>三界除魔</color>"
        },
        {
            need_count=20,
            is_remind=1,
            level_min=55,
            level_max=59,
            exp=245000,
            coin=20000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            desc="完成今日<color=#B84305>三界除魔</color>"
        },
        {
            need_count=20,
            is_remind=1,
            level_min=60,
            level_max=64,
            exp=257000,
            coin=20000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            desc="完成今日<color=#B84306>三界除魔</color>"
        },
        {
            need_count=20,
            is_remind=1,
            level_min=65,
            level_max=69,
            exp=270000,
            coin=20000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            desc="完成今日<color=#B84307>三界除魔</color>"
        },
        {
            need_count=20,
            is_remind=1,
            level_min=70,
            level_max=74,
            exp=277000,
            coin=20000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            desc="完成今日<color=#B84308>三界除魔</color>"
        },
        {
            need_count=20,
            is_remind=1,
            level_min=75,
            level_max=79,
            exp=289000,
            coin=20000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            desc="完成今日<color=#B84309>三界除魔</color>"
        },
        {
            need_count=20,
            is_remind=1,
            level_min=80,
            level_max=84,
            exp=297000,
            coin=20000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            desc="完成今日<color=#B84310>三界除魔</color>"
        },
        {
            need_count=20,
            is_remind=1,
            level_min=85,
            level_max=89,
            exp=309000,
            coin=20000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            desc="完成今日<color=#B84311>三界除魔</color>"
        },
        {
            need_count=20,
            is_remind=1,
            level_min=90,
            level_max=94,
            exp=317000,
            coin=20000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            desc="完成今日<color=#B84312>三界除魔</color>"
        },
        {
            need_count=20,
            is_remind=1,
            level_min=95,
            level_max=99,
            exp=329000,
            coin=20000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            desc="完成今日<color=#B84313>三界除魔</color>"
        },
        {
            need_count=20,
            is_remind=1,
            level_min=100,
            level_max=104,
            exp=337000,
            coin=20000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            desc="完成今日<color=#B84314>三界除魔</color>"
        },
        {
            need_count=20,
            is_remind=1,
            level_min=105,
            level_max=109,
            exp=349000,
            coin=20000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            desc="完成今日<color=#B84315>三界除魔</color>"
        },
        {
            need_count=20,
            is_remind=1,
            level_min=110,
            level_max=114,
            exp=356000,
            coin=20000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            desc="完成今日<color=#B84316>三界除魔</color>"
        },
        {
            need_count=20,
            is_remind=1,
            level_min=115,
            exp=364000,
            coin=20000,
            reward_item={
                [0]=_itemlist.i_31322_2_1
            },
            desc="完成今日<color=#B84300>三界除魔</color>"
        },
        {
            type=25,
            act_type=10043,
            integral_active=20,
            coin=20000,
            reward_item={
                [0]=_itemlist.i_27850_1_1
            },
            sort=5,
            desc="完成今日<color=#B84300>寻仙问道</color>"
        },
        {
            type=21,
            act_type=10039,
            need_count=5,
            integral_active=30,
            level_min=31,
            coin=20000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=6,
            desc="完成今日<color=#B84300>声望任务</color>",
            open_day=3
        },
        {
            type=3,
            act_type=10001,
            need_count=3,
            integral_active=20,
            is_off=1,
            coin=0,
            sort=7,
            desc="缉捕盗贼"
        },
        {
            type=4,
            act_type=10005,
            integral_active=20,
            is_off=1,
            level_max=39,
            exp=80000,
            sort=8,
            desc="完成今日<color=#B84300>神算子的考验</color>"
        },
        {
            type=4,
            act_type=10005,
            integral_active=20,
            is_off=1,
            level_min=40,
            level_max=44,
            exp=80000,
            sort=8,
            desc="完成今日<color=#B84300>神算子的考验</color>"
        },
        {
            type=4,
            act_type=10005,
            integral_active=20,
            is_off=1,
            level_min=45,
            level_max=49,
            exp=87500,
            sort=8,
            desc="完成今日<color=#B84300>神算子的考验</color>"
        },
        {
            type=4,
            act_type=10005,
            integral_active=20,
            is_off=1,
            level_min=50,
            level_max=54,
            exp=99000,
            sort=8,
            desc="完成今日<color=#B84300>神算子的考验</color>"
        },
        {
            type=4,
            act_type=10005,
            integral_active=20,
            is_off=1,
            level_min=55,
            level_max=59,
            exp=118000,
            sort=8,
            desc="完成今日<color=#B84300>神算子的考验</color>"
        },
        {
            type=4,
            act_type=10005,
            integral_active=20,
            is_off=1,
            level_min=60,
            level_max=64,
            exp=127000,
            sort=8,
            desc="完成今日<color=#B84300>神算子的考验</color>"
        },
        {
            type=4,
            act_type=10005,
            integral_active=20,
            is_off=1,
            level_min=65,
            level_max=69,
            exp=140000,
            sort=8,
            desc="完成今日<color=#B84300>神算子的考验</color>"
        },
        {
            type=4,
            act_type=10005,
            integral_active=20,
            is_off=1,
            level_min=70,
            level_max=74,
            exp=147000,
            sort=8,
            desc="完成今日<color=#B84300>神算子的考验</color>"
        },
        {
            type=4,
            act_type=10005,
            integral_active=20,
            is_off=1,
            level_min=75,
            level_max=79,
            exp=159000,
            sort=8,
            desc="完成今日<color=#B84300>神算子的考验</color>"
        },
        {
            type=4,
            act_type=10005,
            integral_active=20,
            is_off=1,
            level_min=80,
            level_max=84,
            exp=167000,
            sort=8,
            desc="完成今日<color=#B84300>神算子的考验</color>"
        },
        {
            type=4,
            act_type=10005,
            integral_active=20,
            is_off=1,
            level_min=85,
            level_max=89,
            exp=179000,
            sort=8,
            desc="完成今日<color=#B84300>神算子的考验</color>"
        },
        {
            type=4,
            act_type=10005,
            integral_active=20,
            is_off=1,
            level_min=90,
            level_max=94,
            exp=187000,
            sort=8,
            desc="完成今日<color=#B84300>神算子的考验</color>"
        },
        {
            type=4,
            act_type=10005,
            integral_active=20,
            is_off=1,
            level_min=95,
            level_max=99,
            exp=199000,
            sort=8,
            desc="完成今日<color=#B84300>神算子的考验</color>"
        },
        {
            type=4,
            act_type=10005,
            integral_active=20,
            is_off=1,
            level_min=100,
            level_max=104,
            exp=207000,
            sort=8,
            desc="完成今日<color=#B84300>神算子的考验</color>"
        },
        {
            type=4,
            act_type=10005,
            integral_active=20,
            is_off=1,
            level_min=105,
            level_max=109,
            exp=219000,
            sort=8,
            desc="完成今日<color=#B84300>神算子的考验</color>"
        },
        {
            type=4,
            act_type=10005,
            integral_active=20,
            is_off=1,
            level_min=110,
            level_max=114,
            exp=226000,
            sort=8,
            desc="完成今日<color=#B84300>神算子的考验</color>"
        },
        {
            type=4,
            act_type=10005,
            integral_active=20,
            is_off=1,
            level_min=115,
            exp=234000,
            sort=8,
            desc="完成今日<color=#B84300>神算子的考验</color>"
        },
        {
            type=24,
            act_type=10042,
            integral_active=30,
            coin=0,
            reward_item={
                [0]=_itemlist.i_27303_1_1,
                [1]=_itemlist.i_27397_3_1
            },
            sort=10,
            desc="完成十次<color=#B84300>九州秘宝</color>探索"
        },
        {
            type=19,
            act_type=10035,
            need_count=2,
            level_max=39,
            exp=75000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=9,
            desc="战胜2次<color=#B84300>精英试炼</color>首领"
        },
        {
            type=19,
            act_type=10035,
            need_count=2,
            level_min=40,
            level_max=44,
            exp=187500,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=9,
            desc="战胜2次<color=#B84300>精英试炼</color>首领"
        },
        {
            type=19,
            act_type=10035,
            need_count=2,
            level_min=45,
            level_max=49,
            exp=198700,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=9,
            desc="战胜2次<color=#B84300>精英试炼</color>首领"
        },
        {
            type=19,
            act_type=10035,
            need_count=2,
            level_min=50,
            level_max=54,
            exp=202000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=9,
            desc="战胜2次<color=#B84300>精英试炼</color>首领"
        },
        {
            type=19,
            act_type=10035,
            need_count=2,
            level_min=55,
            level_max=59,
            exp=216500,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=9,
            desc="战胜2次<color=#B84300>精英试炼</color>首领"
        },
        {
            type=19,
            act_type=10035,
            need_count=2,
            level_min=60,
            level_max=64,
            exp=227000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=9,
            desc="战胜2次<color=#B84300>精英试炼</color>首领"
        },
        {
            type=19,
            act_type=10035,
            need_count=2,
            level_min=65,
            level_max=69,
            exp=240000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=9,
            desc="战胜2次<color=#B84300>精英试炼</color>首领"
        },
        {
            type=19,
            act_type=10035,
            need_count=2,
            level_min=70,
            level_max=74,
            exp=247000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=9,
            desc="战胜2次<color=#B84300>精英试炼</color>首领"
        },
        {
            type=19,
            act_type=10035,
            need_count=2,
            level_min=75,
            level_max=79,
            exp=259000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=9,
            desc="战胜2次<color=#B84300>精英试炼</color>首领"
        },
        {
            type=19,
            act_type=10035,
            need_count=2,
            level_min=80,
            level_max=84,
            exp=267000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=9,
            desc="战胜2次<color=#B84300>精英试炼</color>首领"
        },
        {
            type=19,
            act_type=10035,
            need_count=2,
            level_min=85,
            level_max=89,
            exp=279000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=9,
            desc="战胜2次<color=#B84300>精英试炼</color>首领"
        },
        {
            type=19,
            act_type=10035,
            need_count=2,
            level_min=90,
            level_max=94,
            exp=287000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=9,
            desc="战胜2次<color=#B84300>精英试炼</color>首领"
        },
        {
            type=19,
            act_type=10035,
            need_count=2,
            level_min=95,
            level_max=99,
            exp=299000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=9,
            desc="战胜2次<color=#B84300>精英试炼</color>首领"
        },
        {
            type=19,
            act_type=10035,
            need_count=2,
            level_min=100,
            level_max=104,
            exp=307000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=9,
            desc="战胜2次<color=#B84300>精英试炼</color>首领"
        },
        {
            type=19,
            act_type=10035,
            need_count=2,
            level_min=105,
            level_max=109,
            exp=319000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=9,
            desc="战胜2次<color=#B84300>精英试炼</color>首领"
        },
        {
            type=19,
            act_type=10035,
            need_count=2,
            level_min=110,
            level_max=114,
            exp=326000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=9,
            desc="战胜2次<color=#B84300>精英试炼</color>首领"
        },
        {
            type=19,
            act_type=10035,
            need_count=2,
            level_min=115,
            exp=334000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=9,
            desc="战胜2次<color=#B84300>精英试炼</color>首领"
        },
        {
            type=14,
            act_type=10031,
            need_count=100,
            integral_active=30,
            is_remind=1,
            is_off=1,
            coin=0,
            strength=40,
            reward_item={
                [0]=_itemlist.i_24557_1_1
            },
            sort=11,
            desc="消耗100点<color=#B84300>体力</color>"
        },
        {
            type=17,
            act_type=10030,
            need_count=5,
            integral_active=20,
            is_off=1,
            sort=12,
            desc="通关/扫荡5次<color=#B84300>梦渊笔录</color>"
        },
        {
            type=5,
            act_type=10006,
            need_count=3,
            integral_active=15,
            is_off=1,
            coin=0,
            sort=13,
            desc="许愿池"
        },
        {
            type=11,
            act_type=10025,
            need_count=3,
            integral_active=20,
            is_off=1,
            strength=30,
            sort=15,
            desc="进行3次<color=#B84300>竞技场</color>挑战"
        },
        {
            type=10,
            act_type=10022,
            need_count=4,
            integral_active=30,
            is_off=1,
            coin=0,
            sort=17,
            desc="四象幻境"
        },
        {
            type=12,
            act_type=10007,
            need_count=1,
            integral_active=20,
            is_off=1,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=18,
            desc="挑战1次<color=#B84300>锢魔之塔</color>"
        },
        {
            type=15,
            act_type=10034,
            need_count=5,
            integral_active=20,
            level_max=39,
            exp=60000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=20,
            desc="进行5次<color=#B84300>穹顶之争</color>挑战"
        },
        {
            type=15,
            act_type=10034,
            need_count=5,
            integral_active=20,
            level_min=40,
            level_max=44,
            exp=160000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=20,
            desc="进行5次<color=#B84300>穹顶之争</color>挑战"
        },
        {
            type=15,
            act_type=10034,
            need_count=5,
            integral_active=20,
            level_min=45,
            level_max=49,
            exp=167500,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=20,
            desc="进行5次<color=#B84300>穹顶之争</color>挑战"
        },
        {
            type=15,
            act_type=10034,
            need_count=5,
            integral_active=20,
            level_min=50,
            level_max=54,
            exp=169000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=20,
            desc="进行5次<color=#B84300>穹顶之争</color>挑战"
        },
        {
            type=15,
            act_type=10034,
            need_count=5,
            integral_active=20,
            level_min=55,
            level_max=59,
            exp=188000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=20,
            desc="进行5次<color=#B84300>穹顶之争</color>挑战"
        },
        {
            type=15,
            act_type=10034,
            need_count=5,
            integral_active=20,
            level_min=60,
            level_max=64,
            exp=197000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=20,
            desc="进行5次<color=#B84300>穹顶之争</color>挑战"
        },
        {
            type=15,
            act_type=10034,
            need_count=5,
            integral_active=20,
            level_min=65,
            level_max=69,
            exp=210000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=20,
            desc="进行5次<color=#B84300>穹顶之争</color>挑战"
        },
        {
            type=15,
            act_type=10034,
            need_count=5,
            integral_active=20,
            level_min=70,
            level_max=74,
            exp=217000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=20,
            desc="进行5次<color=#B84300>穹顶之争</color>挑战"
        },
        {
            type=15,
            act_type=10034,
            need_count=5,
            integral_active=20,
            level_min=75,
            level_max=79,
            exp=229000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=20,
            desc="进行5次<color=#B84300>穹顶之争</color>挑战"
        },
        {
            type=15,
            act_type=10034,
            need_count=5,
            integral_active=20,
            level_min=80,
            level_max=84,
            exp=237000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=20,
            desc="进行5次<color=#B84300>穹顶之争</color>挑战"
        },
        {
            type=15,
            act_type=10034,
            need_count=5,
            integral_active=20,
            level_min=85,
            level_max=89,
            exp=249000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=20,
            desc="进行5次<color=#B84300>穹顶之争</color>挑战"
        },
        {
            type=15,
            act_type=10034,
            need_count=5,
            integral_active=20,
            level_min=90,
            level_max=94,
            exp=257000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=20,
            desc="进行5次<color=#B84300>穹顶之争</color>挑战"
        },
        {
            type=15,
            act_type=10034,
            need_count=5,
            integral_active=20,
            level_min=95,
            level_max=99,
            exp=269000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=20,
            desc="进行5次<color=#B84300>穹顶之争</color>挑战"
        },
        {
            type=15,
            act_type=10034,
            need_count=5,
            integral_active=20,
            level_min=100,
            level_max=104,
            exp=277000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=20,
            desc="进行5次<color=#B84300>穹顶之争</color>挑战"
        },
        {
            type=15,
            act_type=10034,
            need_count=5,
            integral_active=20,
            level_min=105,
            level_max=109,
            exp=289000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=20,
            desc="进行5次<color=#B84300>穹顶之争</color>挑战"
        },
        {
            type=15,
            act_type=10034,
            need_count=5,
            integral_active=20,
            level_min=110,
            level_max=114,
            exp=296000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=20,
            desc="进行5次<color=#B84300>穹顶之争</color>挑战"
        },
        {
            type=15,
            act_type=10034,
            need_count=5,
            integral_active=20,
            level_min=115,
            exp=304000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=20,
            desc="进行5次<color=#B84300>穹顶之争</color>挑战"
        },
        {
            type=16,
            act_type=10033,
            need_count=1,
            integral_active=20,
            is_off=1,
            coin=20000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=21,
            desc="挑战1次<color=#B84300>轮回忘川</color>"
        },
        {
            type=22,
            act_type=10040,
            need_count=1,
            integral_active=30,
            coin=20000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=22,
            desc="组队挑战<color=#B84300>北斗七星</color>"
        },
        {
            type=18,
            act_type=10037,
            need_count=2,
            integral_active=30,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=23,
            desc="战胜2次<color=#B84300>山海降妖</color>首领"
        },
        {
            type=0,
            act_type=19,
            need_count=0,
            integral_active=0,
            coin=0,
            sort=24,
            desc="挑战<color=#B84300>心灵之境</color>"
        },
        {
            type=0,
            act_type=10011,
            need_count=0,
            integral_active=0,
            coin=0,
            sort=25,
            desc="完成本周<color=#B84300>商人的烦恼</color>"
        },
        {
            type=1,
            act_type=10027,
            need_count=25,
            integral_active=0,
            level_min=30,
            coin=30000,
            reward_item={
                [0]=_itemlist.i_24518_1_1,
                [1]=_itemlist.i_24557_3_1
            },
            sort=26,
            desc="组队击败<color=#B84300>野外首领</color>",
            is_special=1
        },
        {
            type=1,
            act_type=10002,
            need_count=5,
            integral_active=20,
            is_off=1,
            level_min=70,
            coin=0,
            sort=27,
            desc="门派任务"
        },
        {
            type=0,
            act_type=10046,
            need_count=0,
            integral_active=0,
            level_min=70,
            coin=0,
            sort=28,
            desc="组队挑战<color=#B84300>殒神之地</color>"
        },
        {
            type=0,
            act_type=10050,
            need_count=0,
            integral_active=0,
            level_min=90,
            coin=0,
            sort=29,
            desc="组队挑战<color=#B84300>鸿蒙天界</color>"
        },
        {
            type=6,
            act_type=10004,
            need_count=1,
            integral_active=30,
            coin=20000,
            reward_item={
                [0]=_itemlist.i_27303_1_1
            },
            sort=12,
            desc="组队进行1次<color=#B84300>万妖谷</color>挑战"
        }
    },
    active_reward={
        {
            reward_item={
                [0]=_itemlist.i_28820_1_1
            },
            reward_id={
                [0]=_itemlist.i_28820_1_1
            }
        },
        {
            seq=2,
            integral_active=75,
            exp=90000
        },
        {
            seq=3,
            integral_active=100,
            reward_item={
                [0]=_itemlist.i_24326_1_1
            },
            reward_id={
                [0]=_itemlist.i_24326_1_1
            }
        },
        {
            seq=4,
            integral_active=120,
            exp=135000
        },
        {
            seq=5,
            integral_active=150,
            reward_item={
                [0]=_itemlist.i_28828_1_1
            },
            reward_id={
                [0]=_itemlist.i_28828_1_1
            }
        },
        {
            level_min=40,
            level_max=44,
            reward_item={
                [0]=_itemlist.i_28820_1_1
            },
            reward_id={
                [0]=_itemlist.i_28820_1_1
            }
        },
        {
            seq=2,
            level_min=40,
            level_max=44,
            integral_active=75,
            exp=210000
        },
        {
            seq=3,
            level_min=40,
            level_max=44,
            integral_active=100,
            reward_item={
                [0]=_itemlist.i_24326_1_1
            },
            reward_id={
                [0]=_itemlist.i_24326_1_1
            }
        },
        {
            seq=4,
            level_min=40,
            level_max=44,
            integral_active=120,
            exp=260000
        },
        {
            seq=5,
            level_min=40,
            level_max=44,
            integral_active=150,
            reward_item={
                [0]=_itemlist.i_28828_1_1
            },
            reward_id={
                [0]=_itemlist.i_28828_1_1
            }
        },
        {
            level_min=45,
            level_max=49,
            reward_item={
                [0]=_itemlist.i_28820_1_1
            },
            reward_id={
                [0]=_itemlist.i_28820_1_1
            }
        },
        {
            seq=2,
            level_min=45,
            level_max=49,
            integral_active=75,
            exp=225000
        },
        {
            seq=3,
            level_min=45,
            level_max=49,
            integral_active=100,
            reward_item={
                [0]=_itemlist.i_24326_1_1
            },
            reward_id={
                [0]=_itemlist.i_24326_1_1
            }
        },
        {
            seq=4,
            level_min=45,
            level_max=49,
            integral_active=120,
            exp=280000
        },
        {
            seq=5,
            level_min=45,
            level_max=49,
            integral_active=150,
            reward_item={
                [0]=_itemlist.i_28828_1_1
            },
            reward_id={
                [0]=_itemlist.i_28828_1_1
            }
        },
        {
            level_min=50,
            level_max=54,
            reward_item={
                [0]=_itemlist.i_28820_1_1
            },
            reward_id={
                [0]=_itemlist.i_28820_1_1
            }
        },
        {
            seq=2,
            level_min=50,
            level_max=54,
            integral_active=75,
            exp=235000
        },
        {
            seq=3,
            level_min=50,
            level_max=54,
            integral_active=100,
            reward_item={
                [0]=_itemlist.i_24326_1_1
            },
            reward_id={
                [0]=_itemlist.i_24326_1_1
            }
        },
        {
            seq=4,
            level_min=50,
            level_max=54,
            integral_active=120,
            exp=305000
        },
        {
            seq=5,
            level_min=50,
            level_max=54,
            integral_active=150,
            reward_item={
                [0]=_itemlist.i_28828_1_1
            },
            reward_id={
                [0]=_itemlist.i_28828_1_1
            }
        },
        {
            level_min=55,
            level_max=59,
            reward_item={
                [0]=_itemlist.i_28820_1_1
            },
            reward_id={
                [0]=_itemlist.i_28820_1_1
            }
        },
        {
            seq=2,
            level_min=55,
            level_max=59,
            integral_active=75,
            exp=255000
        },
        {
            seq=3,
            level_min=55,
            level_max=59,
            integral_active=100,
            reward_item={
                [0]=_itemlist.i_24326_1_1
            },
            reward_id={
                [0]=_itemlist.i_24326_1_1
            }
        },
        {
            seq=4,
            level_min=55,
            level_max=59,
            integral_active=120,
            exp=315000
        },
        {
            seq=5,
            level_min=55,
            level_max=59,
            integral_active=150,
            reward_item={
                [0]=_itemlist.i_28828_1_1
            },
            reward_id={
                [0]=_itemlist.i_28828_1_1
            }
        },
        {
            level_min=60,
            level_max=64,
            reward_item={
                [0]=_itemlist.i_28820_1_1
            },
            reward_id={
                [0]=_itemlist.i_28820_1_1
            }
        },
        {
            seq=2,
            level_min=60,
            level_max=64,
            integral_active=75,
            exp=268000
        },
        {
            seq=3,
            level_min=60,
            level_max=64,
            integral_active=100,
            reward_item={
                [0]=_itemlist.i_24326_1_1
            },
            reward_id={
                [0]=_itemlist.i_24326_1_1
            }
        },
        {
            seq=4,
            level_min=60,
            level_max=64,
            integral_active=120,
            exp=352000
        },
        {
            seq=5,
            level_min=60,
            level_max=64,
            integral_active=150,
            reward_item={
                [0]=_itemlist.i_28828_1_1
            },
            reward_id={
                [0]=_itemlist.i_28828_1_1
            }
        },
        {
            level_min=65,
            level_max=69,
            reward_item={
                [0]=_itemlist.i_28820_1_1
            },
            reward_id={
                [0]=_itemlist.i_28820_1_1
            }
        },
        {
            seq=2,
            level_min=65,
            level_max=69,
            integral_active=75,
            exp=284000
        },
        {
            seq=3,
            level_min=65,
            level_max=69,
            integral_active=100,
            reward_item={
                [0]=_itemlist.i_24326_1_1
            },
            reward_id={
                [0]=_itemlist.i_24326_1_1
            }
        },
        {
            seq=4,
            level_min=65,
            level_max=69,
            integral_active=120,
            exp=376000
        },
        {
            seq=5,
            level_min=65,
            level_max=69,
            integral_active=150,
            reward_item={
                [0]=_itemlist.i_28828_1_1
            },
            reward_id={
                [0]=_itemlist.i_28828_1_1
            }
        },
        {
            level_min=70,
            level_max=72,
            reward_item={
                [0]=_itemlist.i_28820_1_1
            },
            reward_id={
                [0]=_itemlist.i_28820_1_1
            }
        },
        {
            seq=2,
            level_min=70,
            level_max=72,
            integral_active=75,
            exp=292000
        },
        {
            seq=3,
            level_min=70,
            level_max=72,
            integral_active=100,
            reward_item={
                [0]=_itemlist.i_24326_1_1
            },
            reward_id={
                [0]=_itemlist.i_24326_1_1
            }
        },
        {
            seq=4,
            level_min=70,
            level_max=72,
            integral_active=120,
            exp=388000
        },
        {
            seq=5,
            level_min=70,
            level_max=72,
            integral_active=150,
            reward_item={
                [0]=_itemlist.i_28828_1_1
            },
            reward_id={
                [0]=_itemlist.i_28828_1_1
            }
        },
        {
            level_min=73,
            level_max=74,
            reward_item={
                [0]=_itemlist.i_28820_1_1
            },
            reward_id={
                [0]=_itemlist.i_28820_1_1
            }
        },
        {
            seq=2,
            level_min=73,
            level_max=74,
            integral_active=75,
            exp=302000
        },
        {
            seq=3,
            level_min=73,
            level_max=74,
            integral_active=100,
            reward_item={
                [0]=_itemlist.i_24326_1_1
            },
            reward_id={
                [0]=_itemlist.i_24326_1_1
            }
        },
        {
            seq=4,
            level_min=73,
            level_max=74,
            integral_active=120,
            exp=400000
        },
        {
            seq=5,
            level_min=73,
            level_max=74,
            integral_active=150,
            reward_item={
                [0]=_itemlist.i_28828_1_1
            },
            reward_id={
                [0]=_itemlist.i_28828_1_1
            }
        },
        {
            level_min=75,
            level_max=79,
            reward_item={
                [0]=_itemlist.i_28820_1_1
            },
            reward_id={
                [0]=_itemlist.i_28820_1_1
            }
        },
        {
            seq=2,
            level_min=75,
            level_max=79,
            integral_active=75,
            exp=312000
        },
        {
            seq=3,
            level_min=75,
            level_max=79,
            integral_active=100,
            reward_item={
                [0]=_itemlist.i_24326_1_1
            },
            reward_id={
                [0]=_itemlist.i_24326_1_1
            }
        },
        {
            seq=4,
            level_min=75,
            level_max=79,
            integral_active=120,
            exp=418000
        },
        {
            seq=5,
            level_min=75,
            level_max=79,
            integral_active=150,
            reward_item={
                [0]=_itemlist.i_28828_1_1
            },
            reward_id={
                [0]=_itemlist.i_28828_1_1
            }
        },
        {
            level_min=80,
            level_max=84,
            reward_item={
                [0]=_itemlist.i_28820_1_1
            },
            reward_id={
                [0]=_itemlist.i_28820_1_1
            }
        },
        {
            seq=2,
            level_min=80,
            level_max=84,
            integral_active=75,
            exp=324000
        },
        {
            seq=3,
            level_min=80,
            level_max=84,
            integral_active=100,
            reward_item={
                [0]=_itemlist.i_24326_1_1
            },
            reward_id={
                [0]=_itemlist.i_24326_1_1
            }
        },
        {
            seq=4,
            level_min=80,
            level_max=84,
            integral_active=120,
            exp=436000
        },
        {
            seq=5,
            level_min=80,
            level_max=84,
            integral_active=150,
            reward_item={
                [0]=_itemlist.i_28828_1_1
            },
            reward_id={
                [0]=_itemlist.i_28828_1_1
            }
        },
        {
            level_min=85,
            level_max=89,
            reward_item={
                [0]=_itemlist.i_28820_1_1
            },
            reward_id={
                [0]=_itemlist.i_28820_1_1
            }
        },
        {
            seq=2,
            level_min=85,
            level_max=89,
            integral_active=75,
            exp=340000
        },
        {
            seq=3,
            level_min=85,
            level_max=89,
            integral_active=100,
            reward_item={
                [0]=_itemlist.i_24326_1_1
            },
            reward_id={
                [0]=_itemlist.i_24326_1_1
            }
        },
        {
            seq=4,
            level_min=85,
            level_max=89,
            integral_active=120,
            exp=460000
        },
        {
            seq=5,
            level_min=85,
            level_max=89,
            integral_active=150,
            reward_item={
                [0]=_itemlist.i_28828_1_1
            },
            reward_id={
                [0]=_itemlist.i_28828_1_1
            }
        },
        {
            level_min=90,
            level_max=94,
            reward_item={
                [0]=_itemlist.i_28820_1_1
            },
            reward_id={
                [0]=_itemlist.i_28820_1_1
            }
        },
        {
            seq=2,
            level_min=90,
            level_max=94,
            integral_active=75,
            exp=352000
        },
        {
            seq=3,
            level_min=90,
            level_max=94,
            integral_active=100,
            reward_item={
                [0]=_itemlist.i_24326_1_1
            },
            reward_id={
                [0]=_itemlist.i_24326_1_1
            }
        },
        {
            seq=4,
            level_min=90,
            level_max=94,
            integral_active=120,
            exp=478000
        },
        {
            seq=5,
            level_min=90,
            level_max=94,
            integral_active=150,
            reward_item={
                [0]=_itemlist.i_28828_1_1
            },
            reward_id={
                [0]=_itemlist.i_28828_1_1
            }
        },
        {
            level_min=95,
            level_max=99,
            reward_item={
                [0]=_itemlist.i_28820_1_1
            },
            reward_id={
                [0]=_itemlist.i_28820_1_1
            }
        },
        {
            seq=2,
            level_min=95,
            level_max=99,
            integral_active=75,
            exp=364000
        },
        {
            seq=3,
            level_min=95,
            level_max=99,
            integral_active=100,
            reward_item={
                [0]=_itemlist.i_24326_1_1
            },
            reward_id={
                [0]=_itemlist.i_24326_1_1
            }
        },
        {
            seq=4,
            level_min=95,
            level_max=99,
            integral_active=120,
            exp=496000
        },
        {
            seq=5,
            level_min=95,
            level_max=99,
            integral_active=150,
            reward_item={
                [0]=_itemlist.i_28828_1_1
            },
            reward_id={
                [0]=_itemlist.i_28828_1_1
            }
        },
        {
            level_min=100,
            level_max=104,
            reward_item={
                [0]=_itemlist.i_28820_1_1
            },
            reward_id={
                [0]=_itemlist.i_28820_1_1
            }
        },
        {
            seq=2,
            level_min=100,
            level_max=104,
            integral_active=75,
            exp=376000
        },
        {
            seq=3,
            level_min=100,
            level_max=104,
            integral_active=100,
            reward_item={
                [0]=_itemlist.i_24326_1_1
            },
            reward_id={
                [0]=_itemlist.i_24326_1_1
            }
        },
        {
            seq=4,
            level_min=100,
            level_max=104,
            integral_active=120,
            exp=514000
        },
        {
            seq=5,
            level_min=100,
            level_max=104,
            integral_active=150,
            reward_item={
                [0]=_itemlist.i_28828_1_1
            },
            reward_id={
                [0]=_itemlist.i_28828_1_1
            }
        },
        {
            level_min=105,
            level_max=109,
            reward_item={
                [0]=_itemlist.i_28820_1_1
            },
            reward_id={
                [0]=_itemlist.i_28820_1_1
            }
        },
        {
            seq=2,
            level_min=105,
            level_max=109,
            integral_active=75,
            exp=392000
        },
        {
            seq=3,
            level_min=105,
            level_max=109,
            integral_active=100,
            reward_item={
                [0]=_itemlist.i_24326_1_1
            },
            reward_id={
                [0]=_itemlist.i_24326_1_1
            }
        },
        {
            seq=4,
            level_min=105,
            level_max=109,
            integral_active=120,
            exp=538000
        },
        {
            seq=5,
            level_min=105,
            level_max=109,
            integral_active=150,
            reward_item={
                [0]=_itemlist.i_28828_1_1
            },
            reward_id={
                [0]=_itemlist.i_28828_1_1
            }
        },
        {
            level_min=110,
            level_max=114,
            reward_item={
                [0]=_itemlist.i_28820_1_1
            },
            reward_id={
                [0]=_itemlist.i_28820_1_1
            }
        },
        {
            seq=2,
            level_min=110,
            level_max=114,
            integral_active=75,
            exp=404000
        },
        {
            seq=3,
            level_min=110,
            level_max=114,
            integral_active=100,
            reward_item={
                [0]=_itemlist.i_24326_1_1
            },
            reward_id={
                [0]=_itemlist.i_24326_1_1
            }
        },
        {
            seq=4,
            level_min=110,
            level_max=114,
            integral_active=120,
            exp=556000
        },
        {
            seq=5,
            level_min=110,
            level_max=114,
            integral_active=150,
            reward_item={
                [0]=_itemlist.i_28828_1_1
            },
            reward_id={
                [0]=_itemlist.i_28828_1_1
            }
        },
        {
            level_min=115,
            level_max=120,
            reward_item={
                [0]=_itemlist.i_28820_1_1
            },
            reward_id={
                [0]=_itemlist.i_28820_1_1
            }
        },
        {
            seq=2,
            level_min=115,
            level_max=120,
            integral_active=75,
            exp=416000
        },
        {
            seq=3,
            level_min=115,
            level_max=120,
            integral_active=100,
            reward_item={
                [0]=_itemlist.i_24326_1_1
            },
            reward_id={
                [0]=_itemlist.i_24326_1_1
            }
        },
        {
            seq=4,
            level_min=115,
            level_max=120,
            integral_active=120,
            exp=574000
        },
        {
            seq=5,
            level_min=115,
            level_max=120,
            integral_active=150,
            reward_item={
                [0]=_itemlist.i_28828_1_1
            },
            reward_id={
                [0]=_itemlist.i_28828_1_1
            }
        }
    },
    linkage_act={
        {
            seq=1,
            reward_item={
                [0]=_itemlist.i_27855_1_1
            }
        },
        {
            seq=2,
            reward_item={
                [0]=_itemlist.i_27855_1_1
            }
        },
        {
            seq=3,
            reward_item={
                [0]=_itemlist.i_27855_1_1
            }
        },
        {
            seq=4,
            reward_item={
                [0]=_itemlist.i_27855_1_1
            }
        },
        {
            reward_item={
                [0]=_itemlist.i_27855_2_1
            }
        },
        {
            seq=1,
            act_type=2122,
            reward_item={
                [0]=_itemlist.i_29125_5_1
            }
        },
        {
            seq=2,
            act_type=2122,
            reward_item={
                [0]=_itemlist.i_29125_5_1
            }
        },
        {
            seq=3,
            act_type=2122,
            reward_item={
                [0]=_itemlist.i_29125_10_1
            }
        },
        {
            seq=4,
            act_type=2122,
            reward_item={
                [0]=_itemlist.i_29125_10_1
            }
        },
        {
            act_type=2122,
            reward_item={
                [0]=_itemlist.i_29125_15_1
            }
        },
        {
            seq=1,
            act_type=2195,
            reward_item={
                [0]=_itemlist.i_26364_1_1
            }
        },
        {
            seq=3,
            act_type=2195,
            reward_item={
                [0]=_itemlist.i_26364_1_1
            }
        },
        {
            act_type=2195,
            reward_item={
                [0]=_itemlist.i_26364_1_1
            }
        },
        {
            act_type=2203,
            reward_item={
                [0]=_itemlist.i_26692_1_1
            }
        },
        {
            seq=1,
            act_type=2200,
            reward_item={
                [0]=_itemlist.i_26703_1_1
            }
        },
        {
            seq=3,
            act_type=2200,
            reward_item={
                [0]=_itemlist.i_26703_1_1
            }
        },
        {
            seq=4,
            act_type=2200,
            reward_item={
                [0]=_itemlist.i_26703_1_1
            }
        }
    },
    week_activity={
        {
            type=0,
            act_type=10009,
            name_text="三界除魔",
            need_count=10,
            show_type=0,
            seq=1,
            integral_active=10
        },
        {
            type=2,
            act_type=10031,
            name_text="消耗100体力",
            need_count=100,
            show_type=0,
            seq=2,
            integral_active=10
        },
        {
            type=3,
            act_type=1,
            name_text="魔将入侵",
            seq=3
        },
        {
            type=4,
            act_type=10,
            name_text="巨龙来袭",
            seq=4
        },
        {
            type=5,
            act_type=9,
            name_text="家族答题",
            seq=5
        },
        {
            type=8,
            act_type=3,
            name_text="迷宫竞速",
            seq=6
        },
        {
            type=6,
            act_type=5,
            name_text="家族大乱斗",
            seq=7
        },
        {
            type=7,
            act_type=2,
            name_text="竞技对抗赛",
            seq=8
        },
        {
            type=9,
            act_type=11,
            name_text="以一敌百",
            seq=9
        },
        {
            type=12,
            act_type=14,
            name_text="百鬼夜行",
            seq=10
        },
        {
            type=10,
            act_type=8,
            name_text="家族荣誉战",
            show_type=2,
            seq=11,
            integral_active=60
        },
        {
            type=11,
            act_type=6,
            name_text="首席竞选",
            show_type=2,
            seq=12,
            integral_active=50
        },
        {
            type=13,
            act_type=4,
            name_text="勇闯地宫",
            seq=13,
            integral_active=30
        },
        {
            type=14,
            act_type=15,
            name_text="丝绸之路",
            seq=14
        },
        {
            type=15,
            act_type=13,
            name_text="遗迹夺宝",
            seq=15
        }
    },
    week_activity_reward={
        {
            reward_item={
                [0]=_itemlist.i_28522_1_1
            },
            reward_id={
                [0]=_itemlist.i_28522_1_1
            }
        },
        {
            seq=2,
            integral_active=100,
            reward_item={
                [0]=_itemlist.i_22050_2_1
            },
            reward_id={
                [0]=_itemlist.i_22050_2_1
            }
        },
        {
            seq=3,
            integral_active=150,
            reward_item={
                [0]=_itemlist.i_25517_3_1
            },
            reward_id={
                [0]=_itemlist.i_25517_3_1
            }
        },
        {
            seq=4,
            integral_active=200,
            reward_item={
                [0]=_itemlist.i_22051_2_1
            },
            reward_id={
                [0]=_itemlist.i_22051_2_1
            }
        },
        {
            seq=5,
            integral_active=300,
            reward_item={
                [0]=_itemlist.i_24518_1_1
            },
            reward_id={
                [0]=_itemlist.i_24518_1_1
            }
        },
        {
            seq=6,
            integral_active=400,
            reward_item={
                [0]=_itemlist.i_27821_2_1
            },
            reward_id={
                [0]=_itemlist.i_27821_2_1
            }
        },
        {
            seq=7,
            integral_active=500,
            reward_item={
                [0]=_itemlist.i_26502_1_1
            },
            reward_id={
                [0]=_itemlist.i_26502_1_1
            }
        },
        {
            level_min=50,
            level_max=120,
            reward_item={
                [0]=_itemlist.i_28522_1_1
            },
            reward_id={
                [0]=_itemlist.i_28522_1_1
            }
        },
        {
            seq=2,
            integral_active=100,
            level_min=50,
            level_max=120,
            reward_item={
                [0]=_itemlist.i_22050_2_1
            },
            reward_id={
                [0]=_itemlist.i_22050_2_1
            }
        },
        {
            seq=3,
            integral_active=150,
            level_min=50,
            level_max=120,
            reward_item={
                [0]=_itemlist.i_25517_3_1
            },
            reward_id={
                [0]=_itemlist.i_25517_3_1
            }
        },
        {
            seq=4,
            integral_active=200,
            level_min=50,
            level_max=120,
            reward_item={
                [0]=_itemlist.i_22051_2_1
            },
            reward_id={
                [0]=_itemlist.i_22051_2_1
            }
        },
        {
            seq=5,
            integral_active=300,
            level_min=50,
            level_max=120,
            reward_item={
                [0]=_itemlist.i_24518_1_1
            },
            reward_id={
                [0]=_itemlist.i_24518_1_1
            }
        },
        {
            seq=6,
            integral_active=400,
            level_min=50,
            level_max=120,
            reward_item={
                [0]=_itemlist.i_27821_2_1
            },
            reward_id={
                [0]=_itemlist.i_27821_2_1
            }
        },
        {
            seq=7,
            integral_active=500,
            level_min=50,
            level_max=120,
            reward_item={
                [0]=_itemlist.i_26502_1_1
            },
            reward_id={
                [0]=_itemlist.i_26502_1_1
            }
        }
    },
    other={
        {
            remind_level=45,
            NPCid=40001,
            start_time=600,
            one_click_level=30,
            one_click_open_time=7
        }
    },
    turntable_task={
        {
            index=1,
            type_param=9
        },
        {
            seq=1,
            index=2,
            type_param=2
        },
        {
            seq=2,
            index=3,
            type_param=3
        },
        {
            seq=3,
            index=4,
            type_param=5
        },
        {
            seq=4,
            index=5,
            type_param=11
        },
        {
            seq=5,
            index=6,
            type_param=8,
            turntable_num=3
        },
        {
            seq=6,
            index=7,
            type_param=6,
            turntable_num=3
        },
        {
            task_type=2,
            index=8,
            type_param=400
        },
        {
            seq=1,
            task_type=2,
            index=9,
            type_param=500
        }
    },
    active_turntable={
        {
            min_level_turn=1,
            max_level_turn=29,
            reward_group=1
        },
        {
            min_level_turn=30,
            max_level_turn=39,
            reward_group=2
        },
        {
            min_level_turn=40,
            max_level_turn=49,
            reward_group=3
        },
        {
            min_level_turn=50,
            max_level_turn=59,
            reward_group=4
        },
        {
            min_level_turn=60,
            max_level_turn=69,
            reward_group=5
        },
        {
            min_level_turn=70,
            max_level_turn=79,
            reward_group=6
        },
        {
            min_level_turn=80,
            max_level_turn=89,
            reward_group=7
        },
        {
            min_level_turn=90,
            max_level_turn=99,
            reward_group=8
        },
        {
            min_level_turn=100,
            max_level_turn=109,
            reward_group=9
        },
        {
            min_level_turn=110,
            max_level_turn=119,
            reward_group=10
        },
        {
            min_level_turn=120,
            max_level_turn=120,
            reward_group=11
        }
    },
    turntable_reward_group={
        {
            seq=0,
            reward=_itemlist.i_22051_1_1
        },
        {
            seq=1,
            index=2,
            reward=_itemlist.i_24326_1_1
        },
        {
            seq=2,
            index=3,
            reward=_itemlist.i_27821_1_1
        },
        {
            seq=3,
            index=4,
            reward=_itemlist.i_24326_1_1
        },
        {
            seq=4,
            index=5,
            reward=_itemlist.i_22051_1_1
        },
        {
            seq=5,
            index=6,
            reward=_itemlist.i_22050_1_1
        },
        {
            seq=6,
            index=7,
            reward=_itemlist.i_24326_1_1
        },
        {
            seq=7,
            index=8,
            reward=_itemlist.i_27821_1_1
        },
        {
            seq=8,
            index=9,
            reward=_itemlist.i_24326_1_1
        },
        {
            seq=9,
            index=10,
            reward=_itemlist.i_22050_1_1
        },
        {
            reward_group=2,
            seq=10,
            reward=_itemlist.i_22051_1_1
        },
        {
            reward_group=2,
            seq=11,
            index=2,
            reward=_itemlist.i_24326_2_1
        },
        {
            reward_group=2,
            seq=12,
            index=3,
            reward=_itemlist.i_27821_1_1
        },
        {
            reward_group=2,
            seq=13,
            index=4,
            reward=_itemlist.i_24326_2_1
        },
        {
            reward_group=2,
            seq=14,
            index=5,
            reward=_itemlist.i_22051_1_1
        },
        {
            reward_group=2,
            seq=15,
            index=6,
            reward=_itemlist.i_22050_1_1
        },
        {
            reward_group=2,
            seq=16,
            index=7,
            reward=_itemlist.i_24326_2_1
        },
        {
            reward_group=2,
            seq=17,
            index=8,
            reward=_itemlist.i_27821_1_1
        },
        {
            reward_group=2,
            seq=18,
            index=9,
            reward=_itemlist.i_24326_2_1
        },
        {
            reward_group=2,
            seq=19,
            index=10,
            reward=_itemlist.i_22050_1_1
        },
        {
            reward_group=3,
            seq=20,
            reward=_itemlist.i_22051_1_1
        },
        {
            reward_group=3,
            seq=21,
            index=2,
            reward=_itemlist.i_24326_2_1
        },
        {
            reward_group=3,
            seq=22,
            index=3,
            reward=_itemlist.i_27821_1_1
        },
        {
            reward_group=3,
            seq=23,
            index=4,
            reward=_itemlist.i_24326_2_1
        },
        {
            reward_group=3,
            seq=24,
            index=5,
            reward=_itemlist.i_22051_1_1
        },
        {
            reward_group=3,
            seq=25,
            index=6,
            reward=_itemlist.i_22050_1_1
        },
        {
            reward_group=3,
            seq=26,
            index=7,
            reward=_itemlist.i_24326_2_1
        },
        {
            reward_group=3,
            seq=27,
            index=8,
            reward=_itemlist.i_27821_1_1
        },
        {
            reward_group=3,
            seq=28,
            index=9,
            reward=_itemlist.i_24326_2_1
        },
        {
            reward_group=3,
            seq=29,
            index=10,
            reward=_itemlist.i_22050_1_1
        },
        {
            reward_group=4,
            seq=30,
            reward=_itemlist.i_22051_1_1
        },
        {
            reward_group=4,
            seq=31,
            index=2,
            reward=_itemlist.i_24326_2_1
        },
        {
            reward_group=4,
            seq=32,
            index=3,
            reward=_itemlist.i_27821_1_1
        },
        {
            reward_group=4,
            seq=33,
            index=4,
            reward=_itemlist.i_24326_2_1
        },
        {
            reward_group=4,
            seq=34,
            index=5,
            reward=_itemlist.i_22051_1_1
        },
        {
            reward_group=4,
            seq=35,
            index=6,
            reward=_itemlist.i_22050_1_1
        },
        {
            reward_group=4,
            seq=36,
            index=7,
            reward=_itemlist.i_24326_2_1
        },
        {
            reward_group=4,
            seq=37,
            index=8,
            reward=_itemlist.i_27821_1_1
        },
        {
            reward_group=4,
            seq=38,
            index=9,
            reward=_itemlist.i_24326_2_1
        },
        {
            reward_group=4,
            seq=39,
            index=10,
            reward=_itemlist.i_22050_1_1
        },
        {
            reward_group=5,
            seq=40,
            reward=_itemlist.i_22051_1_1
        },
        {
            reward_group=5,
            seq=41,
            index=2,
            reward=_itemlist.i_24326_3_1
        },
        {
            reward_group=5,
            seq=42,
            index=3,
            reward=_itemlist.i_27821_1_1
        },
        {
            reward_group=5,
            seq=43,
            index=4,
            reward=_itemlist.i_24326_3_1
        },
        {
            reward_group=5,
            seq=44,
            index=5,
            reward=_itemlist.i_22051_1_1
        },
        {
            reward_group=5,
            seq=45,
            index=6,
            reward=_itemlist.i_22050_1_1
        },
        {
            reward_group=5,
            seq=46,
            index=7,
            reward=_itemlist.i_24326_3_1
        },
        {
            reward_group=5,
            seq=47,
            index=8,
            reward=_itemlist.i_27821_1_1
        },
        {
            reward_group=5,
            seq=48,
            index=9,
            reward=_itemlist.i_24326_3_1
        },
        {
            reward_group=5,
            seq=49,
            index=10,
            reward=_itemlist.i_22050_1_1
        },
        {
            reward_group=6,
            seq=50,
            reward=_itemlist.i_22051_1_1
        },
        {
            reward_group=6,
            seq=51,
            index=2,
            reward=_itemlist.i_24326_3_1
        },
        {
            reward_group=6,
            seq=52,
            index=3,
            reward=_itemlist.i_27821_1_1
        },
        {
            reward_group=6,
            seq=53,
            index=4,
            reward=_itemlist.i_24326_3_1
        },
        {
            reward_group=6,
            seq=54,
            index=5,
            reward=_itemlist.i_22051_1_1
        },
        {
            reward_group=6,
            seq=55,
            index=6,
            reward=_itemlist.i_22050_1_1
        },
        {
            reward_group=6,
            seq=56,
            index=7,
            reward=_itemlist.i_24326_3_1
        },
        {
            reward_group=6,
            seq=57,
            index=8,
            reward=_itemlist.i_27821_1_1
        },
        {
            reward_group=6,
            seq=58,
            index=9,
            reward=_itemlist.i_24326_3_1
        },
        {
            reward_group=6,
            seq=59,
            index=10,
            reward=_itemlist.i_22050_1_1
        },
        {
            reward_group=7,
            seq=60,
            reward=_itemlist.i_22051_1_1
        },
        {
            reward_group=7,
            seq=61,
            index=2,
            reward=_itemlist.i_24326_3_1
        },
        {
            reward_group=7,
            seq=62,
            index=3,
            reward=_itemlist.i_27821_1_1
        },
        {
            reward_group=7,
            seq=63,
            index=4,
            reward=_itemlist.i_24326_3_1
        },
        {
            reward_group=7,
            seq=64,
            index=5,
            reward=_itemlist.i_22051_1_1
        },
        {
            reward_group=7,
            seq=65,
            index=6,
            reward=_itemlist.i_22050_1_1
        },
        {
            reward_group=7,
            seq=66,
            index=7,
            reward=_itemlist.i_24326_3_1
        },
        {
            reward_group=7,
            seq=67,
            index=8,
            reward=_itemlist.i_27821_1_1
        },
        {
            reward_group=7,
            seq=68,
            index=9,
            reward=_itemlist.i_24326_3_1
        },
        {
            reward_group=7,
            seq=69,
            index=10,
            reward=_itemlist.i_22050_1_1
        },
        {
            reward_group=8,
            seq=70,
            reward=_itemlist.i_22051_1_1
        },
        {
            reward_group=8,
            seq=71,
            index=2,
            reward=_itemlist.i_24326_4_1
        },
        {
            reward_group=8,
            seq=72,
            index=3,
            reward=_itemlist.i_27821_1_1
        },
        {
            reward_group=8,
            seq=73,
            index=4,
            reward=_itemlist.i_24326_4_1
        },
        {
            reward_group=8,
            seq=74,
            index=5,
            reward=_itemlist.i_22051_1_1
        },
        {
            reward_group=8,
            seq=75,
            index=6,
            reward=_itemlist.i_22050_1_1
        },
        {
            reward_group=8,
            seq=76,
            index=7,
            reward=_itemlist.i_24326_4_1
        },
        {
            reward_group=8,
            seq=77,
            index=8,
            reward=_itemlist.i_27821_1_1
        },
        {
            reward_group=8,
            seq=78,
            index=9,
            reward=_itemlist.i_24326_4_1
        },
        {
            reward_group=8,
            seq=79,
            index=10,
            reward=_itemlist.i_22050_1_1
        },
        {
            reward_group=9,
            seq=80,
            reward=_itemlist.i_22051_1_1
        },
        {
            reward_group=9,
            seq=81,
            index=2,
            reward=_itemlist.i_24326_4_1
        },
        {
            reward_group=9,
            seq=82,
            index=3,
            reward=_itemlist.i_27821_1_1
        },
        {
            reward_group=9,
            seq=83,
            index=4,
            reward=_itemlist.i_24326_4_1
        },
        {
            reward_group=9,
            seq=84,
            index=5,
            reward=_itemlist.i_22051_1_1
        },
        {
            reward_group=9,
            seq=85,
            index=6,
            reward=_itemlist.i_22050_1_1
        },
        {
            reward_group=9,
            seq=86,
            index=7,
            reward=_itemlist.i_24326_4_1
        },
        {
            reward_group=9,
            seq=87,
            index=8,
            reward=_itemlist.i_27821_1_1
        },
        {
            reward_group=9,
            seq=88,
            index=9,
            reward=_itemlist.i_24326_4_1
        },
        {
            reward_group=9,
            seq=89,
            index=10,
            reward=_itemlist.i_22050_1_1
        },
        {
            reward_group=10,
            seq=90,
            reward=_itemlist.i_22051_1_1
        },
        {
            reward_group=10,
            seq=91,
            index=2,
            reward=_itemlist.i_24326_4_1
        },
        {
            reward_group=10,
            seq=92,
            index=3,
            reward=_itemlist.i_27821_1_1
        },
        {
            reward_group=10,
            seq=93,
            index=4,
            reward=_itemlist.i_24326_4_1
        },
        {
            reward_group=10,
            seq=94,
            index=5,
            reward=_itemlist.i_22051_1_1
        },
        {
            reward_group=10,
            seq=95,
            index=6,
            reward=_itemlist.i_22050_1_1
        },
        {
            reward_group=10,
            seq=96,
            index=7,
            reward=_itemlist.i_24326_4_1
        },
        {
            reward_group=10,
            seq=97,
            index=8,
            reward=_itemlist.i_27821_1_1
        },
        {
            reward_group=10,
            seq=98,
            index=9,
            reward=_itemlist.i_24326_4_1
        },
        {
            reward_group=10,
            seq=99,
            index=10,
            reward=_itemlist.i_22050_1_1
        },
        {
            reward_group=11,
            seq=100,
            reward=_itemlist.i_22051_1_1
        },
        {
            reward_group=11,
            seq=101,
            index=2,
            reward=_itemlist.i_24326_4_1
        },
        {
            reward_group=11,
            seq=102,
            index=3,
            reward=_itemlist.i_27821_1_1
        },
        {
            reward_group=11,
            seq=103,
            index=4,
            reward=_itemlist.i_24326_4_1
        },
        {
            reward_group=11,
            seq=104,
            index=5,
            reward=_itemlist.i_22051_1_1
        },
        {
            reward_group=11,
            seq=105,
            index=6,
            reward=_itemlist.i_22050_1_1
        },
        {
            reward_group=11,
            seq=106,
            index=7,
            reward=_itemlist.i_24326_4_1
        },
        {
            reward_group=11,
            seq=107,
            index=8,
            reward=_itemlist.i_27821_1_1
        },
        {
            reward_group=11,
            seq=108,
            index=9,
            reward=_itemlist.i_24326_4_1
        },
        {
            reward_group=11,
            seq=109,
            index=10,
            reward=_itemlist.i_22050_1_1
        }
    },
    one_click_list={
        {
            seq=0,
            act_type=10020
        },
        {
            seq=1,
            act_type=10009
        },
        {
            seq=2,
            act_type=10039
        },
        {
            seq=3,
            act_type=10043
        },
        {
            seq=4,
            act_type=10042
        },
        {
            seq=5,
            act_type=10041
        }
    }
}
SetConfigDefaultVal(Config.activedegree_auto,_default_val,nil,nil,nil)