local _default_val={
    reward_list={
        seq=7,
        is_show=1,
        type=3
    },
    open_sever_cfg={
        act_type="",
        is_show=1
    },
    rand={
        text="",
        sprite="",
        view_name="",
        mod_key=56026,
        act_type=0,
        position=2,
        new_sign=0,
        effect=0,
        sub_name=""
    },
    btn_list={
        text="大厅特权",
        sprite="",
        view_name="SpecialPower360View",
        effect=0,
        new_sign=0,
        sub_name="",
        is_open=1,
        effect_type=0,
        interface=0
    },
    burning_may_day={
        view_name="",
        mod_key=""
    },
    summer_first={
        view_name="",
        act_type=2106,
        mod_key="",
        desc="夏日的居民们好似遇到了什么难题，还望侠士们能去帮助居民们解决问题。"
    },
    national_day={
        act_tag="趣味惊喜"
    },
    yuanqiqingdian={
        picture="XiongMao",
        plan_type=3,
        show=0
    },
    duanwu_festival={
        start_time=1,
        end_time=8,
        location=4,
        text="端阳宝盒",
        view_name="GiftBoxView",
        mod_key=56031,
        act_type=2088,
        is_close=0
    },
    battle_show={
        act_type=0,
        mod_key=56047
    },
    moon_mid_autumn={
        seq=1,
        start_time=1,
        end_time=5,
        is_close=1,
        is_hidden=1
    }
}
local _itemlist={
    i_26813_1_1={
        item_id=26813,
        num=1,
        is_bind=1
    },
    i_24326_1_1={
        item_id=24326,
        num=1,
        is_bind=1
    },
    i_24607_1_1={
        item_id=24607,
        num=1,
        is_bind=1
    },
    i_25952_1_1={
        item_id=25952,
        num=1,
        is_bind=1
    },
    i_27187_1_1={
        item_id=27187,
        num=1,
        is_bind=1
    },
    i_27541_1_1={
        item_id=27541,
        num=1,
        is_bind=1
    },
    i_27575_1_1={
        item_id=27575,
        num=1,
        is_bind=1
    },
    i_27398_1_1={
        item_id=27398,
        num=1,
        is_bind=1
    },
    i_25951_1_1={
        item_id=25951,
        num=1,
        is_bind=1
    },
    i_25950_1_1={
        item_id=25950,
        num=1,
        is_bind=1
    },
    i_25089_1_1={
        item_id=25089,
        num=1,
        is_bind=1
    },
    i_29032_1_1={
        item_id=29032,
        num=1,
        is_bind=1
    },
    i_29038_1_1={
        item_id=29038,
        num=1,
        is_bind=1
    }
}
Config.activity_main_auto={
    require_list={
        {
            file_name="treasure_activity"
        },
        {
            file_name="joy_seeks_favors"
        },
        {
            file_name="dragon_boat_racing"
        },
        {
            file_name="colorful_illustrations"
        },
        {
            file_name="animal_race"
        },
        {
            file_name="sale_shop_activity"
        },
        {
            file_name="happy_up_activity"
        },
        {
            file_name="repel_the_monster"
        },
        {
            file_name="fortune_bag"
        },
        {
            file_name="drop_double"
        },
        {
            file_name="tax_discount"
        },
        {
            file_name="tianjianghaoli"
        },
        {
            file_name="seal_promote"
        },
        {
            file_name="jiandanqinxin"
        },
        {
            file_name="linkage_gift"
        },
        {
            file_name="pet_exchange_activity"
        },
        {
            file_name="partner_activity"
        },
        {
            file_name="word_gift_activity"
        },
        {
            file_name="adventure_gift_activity"
        },
        {
            file_name="discount_carnival"
        },
        {
            file_name="qm_discount"
        },
        {
            file_name="lucky_turntable"
        },
        {
            file_name="divination_activity"
        },
        {
            file_name="lucky_discount"
        },
        {
            file_name="tujian_treasure"
        },
        {
            file_name="gift_box"
        },
        {
            file_name="ustomized_box"
        },
        {
            file_name="chain_box"
        },
        {
            file_name="wealth_cornucopia"
        },
        {
            file_name="exp_purchase"
        },
        {
            file_name="extra_bonus"
        },
        {
            file_name="exclusive_gift"
        },
        {
            file_name="pet_search"
        },
        {
            file_name="sign_in_continuity"
        },
        {
            file_name="fengshenzhanling"
        },
        {
            file_name="element_cards"
        },
        {
            file_name="cow_lucky_exchange"
        },
        {
            file_name="spring_festival_store"
        },
        {
            file_name="cow_store"
        },
        {
            file_name="little_year_gift"
        },
        {
            file_name="monopoly_gift"
        },
        {
            file_name="cow_exchange"
        },
        {
            file_name="looks_new"
        },
        {
            file_name="customs_gift"
        },
        {
            file_name="give_secret_key"
        },
        {
            file_name="acc_recharge"
        },
        {
            file_name="pet_loot"
        },
        {
            file_name="pet_befall"
        },
        {
            file_name="trade_discount"
        },
        {
            file_name="may_day_activity"
        },
        {
            file_name="gift_rotation"
        },
        {
            file_name="ambassador_activity"
        },
        {
            file_name="lucky_maze"
        },
        {
            file_name="buy_one_gold"
        },
        {
            file_name="immortal_coin_fund"
        },
        {
            file_name="month_card"
        },
        {
            file_name="xinfawuliang"
        },
        {
            file_name="national_day"
        },
        {
            file_name="pai_mai_hang"
        },
        {
            file_name="assign_horcrux"
        },
        {
            file_name="back_reward"
        },
        {
            file_name="exchange_jade"
        },
        {
            file_name="server_competition"
        },
        {
            file_name="buy_item_validation"
        },
        {
            file_name="lingpai_divine"
        },
        {
            file_name="burning_summer"
        },
        {
            file_name="cool_summer"
        },
        {
            file_name="wanlinggongying"
        },
        {
            file_name="taoyuanyisanshi"
        },
        {
            file_name="horcrux_tiancheng"
        },
        {
            file_name="integral_point_choujiang"
        },
        {
            file_name="secret_area"
        },
        {
            file_name="time_limit_answer"
        },
        {
            file_name="shanhai_origin"
        },
        {
            file_name="shanhaixiangfeng"
        },
        {
            file_name="sign_happy"
        },
        {
            file_name="happy_look"
        },
        {
            file_name="recall_shanhai_summary"
        },
        {
            file_name="wanlingyinxiang"
        },
        {
            file_name="shanhaijubao"
        },
        {
            file_name="shanhaichuyu"
        },
        {
            file_name="zhaocaijinbao"
        },
        {
            file_name="jinglingdazhuabu"
        },
        {
            file_name="yunzeqiyuan"
        },
        {
            file_name="xianshileichong"
        },
        {
            file_name="yunzehaoli"
        },
        {
            file_name="mengchongjiadao"
        },
        {
            file_name="yunzehuajing"
        },
        {
            file_name="mozuzainali"
        },
        {
            file_name="chaozhifenxiang"
        },
        {
            file_name="zaizhanyunze"
        },
        {
            file_name="yunzemengce"
        },
        {
            file_name="yunzeersanshi"
        },
        {
            file_name="fenxiangtonghuali"
        },
        {
            file_name="shanhai_box"
        },
        {
            file_name="shanhai_chain_box"
        },
        {
            file_name="shanhai_ustomized_box"
        },
        {
            file_name="shanhaihuadeng"
        },
        {
            file_name="shanhaimibao"
        },
        {
            file_name="shanhaizhengfeng"
        },
        {
            file_name="fenxiangjiabei"
        },
        {
            file_name="yunzefanhualu"
        },
        {
            file_name="yunzebaoxiang"
        },
        {
            file_name="yunzebaohe"
        },
        {
            file_name="yunzebaodai"
        },
        {
            file_name="jixinggaozhao"
        },
        {
            file_name="chaozhixianli"
        },
        {
            file_name="ruixuefengnian"
        },
        {
            file_name="yinhuwenshi"
        },
        {
            file_name="yinhubaisui"
        },
        {
            file_name="huxingdayun"
        },
        {
            file_name="niannianyouyu"
        },
        {
            file_name="yinhutanchun"
        },
        {
            file_name="huyingxinchun"
        },
        {
            file_name="yinhudouxinchun"
        },
        {
            file_name="ciniuyingxinhu"
        },
        {
            file_name="yinhuyasui"
        },
        {
            file_name="qingyuanleichong"
        },
        {
            file_name="qingyuanshizhuang"
        },
        {
            file_name="jingjiyueka"
        },
        {
            file_name="ronglianyouli"
        },
        {
            file_name="period_activity"
        },
        {
            file_name="where_is_the_fairy"
        },
        {
            file_name="lovers_market"
        },
        {
            file_name="rabbit_run"
        },
        {
            file_name="concentric_knot"
        },
        {
            file_name="lovers_match"
        },
        {
            file_name="lantern_riddle"
        },
        {
            file_name="lasso"
        },
        {
            file_name="sanxian"
        },
        {
            file_name="tiangongxunbao"
        },
        {
            file_name="qiyuankongmingdeng"
        },
        {
            file_name="yuanqiqingdian"
        },
        {
            file_name="bozhongyouli"
        },
        {
            file_name="miaobishenghua"
        },
        {
            file_name="yuanqizhuren"
        },
        {
            file_name="xunmenghudie"
        },
        {
            file_name="yuanqifanpai"
        },
        {
            file_name="wanlingzhuli"
        },
        {
            file_name="baozilaile"
        },
        {
            file_name="yuanqiyanhuoxiu"
        },
        {
            file_name="jinyitianxiang"
        },
        {
            file_name="yuanqijingsu"
        },
        {
            file_name="chengfengpolang"
        },
        {
            file_name="yuanqijishibu"
        },
        {
            file_name="yishoulinshi"
        },
        {
            file_name="zongxiangmancheng"
        },
        {
            file_name="xingyunmanghe"
        },
        {
            file_name="duanyangzixuanli"
        },
        {
            file_name="tianxianzhizheng"
        },
        {
            file_name="canglongcifu"
        },
        {
            file_name="sanbaichoupifu"
        },
        {
            file_name="duanyangxiangnang"
        },
        {
            file_name="lantangchumu"
        },
        {
            file_name="duanyangfuli"
        },
        {
            file_name="jinlongjubao"
        },
        {
            file_name="shenshouenze"
        },
        {
            file_name="chongjifanli"
        },
        {
            file_name="xinfuqianghua"
        },
        {
            file_name="keju_examination"
        },
        {
            file_name="sheep_catch"
        },
        {
            file_name="qiqiaotehui"
        },
        {
            file_name="meiliqixi"
        },
        {
            file_name="sijibaohe"
        },
        {
            file_name="sijibaoxiang"
        },
        {
            file_name="sijihuapai"
        },
        {
            file_name="xinfulingchong"
        },
        {
            file_name="kuafuyingxionglu"
        },
        {
            file_name="shencihuafu"
        },
        {
            file_name="tianyiyaoshi"
        },
        {
            file_name="hunqifanli"
        },
        {
            file_name="yuexidengmi"
        },
        {
            file_name="yuexileichong"
        },
        {
            file_name="danbifanli"
        },
        {
            file_name="zhuiyueshangcheng"
        },
        {
            file_name="wanshengqifu"
        },
        {
            file_name="wanshengshangcheng"
        },
        {
            file_name="xingyunshuzi"
        },
        {
            file_name="wanshengleichong"
        },
        {
            file_name="dawanka"
        },
        {
            file_name="txtequan"
        },
        {
            file_name="shengdanmiling"
        },
        {
            file_name="zhoumolianchongli"
        },
        {
            file_name="fuyunshangcheng"
        },
        {
            file_name="yingchunnafu"
        },
        {
            file_name="xingxingdiandeng"
        },
        {
            file_name="dazhanhongtu"
        }
    },
    reward_list={
        {
            id=8,
            seq=8,
            name="消费转盘",
            view_name="roller",
            act_type=2055,
            open=23008,
            type=2
        },
        {
            id=9,
            name="祈福礼袋",
            view_name="fortune_bag",
            act_type=2062,
            open=23009
        },
        {
            id=10,
            seq=6,
            name="灵玉基金",
            view_name="immortal_fund",
            act_type=2115,
            open=23011
        },
        {
            id=11,
            name="道具回收",
            view_name="fund_exchange",
            act_type=2131,
            open=23010,
            type=4
        },
        {
            id=12,
            seq=5,
            name="神兽恩泽",
            view_name="god_beast_grace",
            act_type=2210,
            open=23020
        },
        {
            id=14,
            seq=13,
            name="宠技返利",
            view_name="chongjifanli",
            act_type=2209,
            open=23021,
            type=2
        },
        {
            id=15,
            seq=15,
            name="魂器返利",
            view_name="pet_weapon_fanli",
            act_type=2220,
            open=23022,
            type=2
        }
    },
    open_sever_cfg={
        {
            seq=1,
            name="福牛报喜",
            view_name="act_lucky_cow",
            mod_key=34008
        },
        {
            seq=2,
            name="寅虎纳福",
            view_name="act_lucky_tiger",
            mod_key=34009
        },
        {
            seq=3,
            act_type=2051,
            name="开服转盘",
            view_name="act_open_roller",
            mod_key=0,
            is_show=0
        },
        {
            seq=4,
            act_type=2113,
            name="时装商店",
            view_name="act_fashion_shop",
            mod_key=34006
        },
        {
            seq=5,
            act_type=2068,
            name="集字好礼",
            view_name="act_word_gift",
            mod_key=34003
        },
        {
            seq=6,
            act_type=2076,
            name="幸运转盘",
            view_name="act_luck_roller",
            mod_key=34002
        },
        {
            seq=7,
            act_type=2079,
            name="新服竞技",
            view_name="act_athletics",
            mod_key=34004,
            is_show=0
        },
        {
            seq=8,
            act_type=2133,
            name="新服比拼",
            view_name="competition_rank_view",
            mod_key=34007,
            is_show=0
        },
        {
            seq=9,
            act_type=2183,
            name="缘分天定",
            view_name="act_love_fashion",
            mod_key=34010
        },
        {
            seq=10,
            act_type=2211,
            name="强化有礼",
            view_name="act_pet_str",
            mod_key=34011
        },
        {
            seq=11,
            act_type=2217,
            name="飞鸢神捕",
            view_name="act_new_server_pet",
            mod_key=34012
        }
    },
    rand={
        {
            seq=1,
            text="众神之首|巴蛇问世",
            sprite="LianDongSongLi|BaSheZaiShi",
            view_name="SevenDayView",
            mod_key=56001
        },
        {
            seq=2,
            text="首充专属",
            sprite="ShouChongZhuanShu",
            view_name="FirstChargeExclusiveView",
            mod_key=56041
        },
        {
            seq=3,
            text="赠100抽",
            sprite="Zeng100Chou",
            view_name="GiveHundredView",
            mod_key=56065,
            act_type=2225
        },
        {
            seq=4,
            text="封印提升",
            sprite="FengTiSheng",
            view_name="SealPromoteView",
            mod_key=56010,
            act_type=2065,
            position=1,
            new_sign=1
        },
        {
            seq=5,
            text="秘境双倍",
            sprite="DiaoLuoShuanBei",
            view_name="DropDoubleView",
            mod_key=56011,
            act_type=2066,
            position=1,
            new_sign=1
        },
        {
            seq=6,
            text="税率优惠",
            sprite="SuiLvYouHui",
            view_name="TaxDiscountView",
            mod_key=56013,
            act_type=2063,
            position=1,
            new_sign=1
        },
        {
            seq=7,
            text="春分有礼",
            sprite="HuoBanDuiHuan",
            view_name="ActPartnetExchangeView",
            mod_key=56014,
            act_type=2070,
            position=1,
            new_sign=1
        },
        {
            seq=8,
            text="联动(次日)",
            sprite="LianDongSongLi",
            view_name="LinkageGiftView",
            mod_key=56015,
            act_type=2075
        },
        {
            seq=9,
            text="奇遇礼包",
            sprite="QiYuLiBao",
            view_name="AdventureGiftView",
            mod_key=56016,
            act_type=2074
        },
        {
            seq=10,
            text="幻境奇遇",
            sprite="JianDanQinXin",
            view_name="SwordZitherView",
            mod_key=56020,
            act_type=2073
        },
        {
            seq=11,
            text="欢乐挖蛋",
            sprite="HuanLeXunChong",
            view_name="JoySeeksFavorsView",
            mod_key=56009,
            act_type=2067,
            position=1,
            new_sign=1
        },
        {
            seq=12,
            text="图鉴夺宝",
            sprite="TuJianDuoBao",
            view_name="IllustrateTreasureView",
            mod_key=56024,
            act_type=2080,
            new_sign=1
        },
        {
            seq=13,
            text="桃李福利",
            sprite="ElementCards",
            view_name="ElementCardsView",
            act_type=2082,
            position=1,
            new_sign=1
        },
        {
            seq=14,
            text="赠30连抽",
            sprite="ZengXunChongLianChou",
            view_name="ActPetSearchView",
            mod_key=56028,
            act_type=2090
        },
        {
            seq=15,
            text="经验飙升",
            sprite="JingYanBiaoSheng",
            view_name="ExpPurchaseView",
            mod_key=56030,
            act_type=2087,
            position=1,
            new_sign=1
        },
        {
            seq=16,
            text="金宠助力",
            sprite="ZengXunBaoYaoSi",
            view_name="GiveSecretKeyView",
            mod_key=56034,
            act_type=2099,
            sub_name="give_secret_sub"
        },
        {
            seq=17,
            text="神装惊世",
            sprite="LeiJiChongZhi",
            view_name="AccRechargeView",
            mod_key=56035,
            act_type=2100,
            new_sign=1
        },
        {
            seq=18,
            text="交易狂欢日",
            sprite="JiaoYiKuangHuanRi",
            view_name="DealDiscountView",
            mod_key=64004,
            act_type=2102,
            position=1
        },
        {
            seq=19,
            text="桂月好礼",
            sprite="HaoLiZhuanDong",
            view_name="GiftRotationView",
            mod_key=56037,
            act_type=2104,
            position=1,
            new_sign=1
        },
        {
            seq=20,
            text="令牌天赐",
            sprite="LingPaiTianCi",
            view_name="HeavenSentView",
            mod_key=56039,
            act_type=2112,
            new_sign=1
        },
        {
            seq=21,
            text="心法无量",
            sprite="XinFaWuLiang",
            view_name="RandHeartSkillView",
            mod_key=56042,
            act_type=2116,
            new_sign=1
        },
        {
            seq=22,
            text="拍卖行",
            sprite="PaiMaiHang",
            view_name="PaiMaiHangView",
            mod_key=56043,
            act_type=2129
        },
        {
            seq=23,
            text="赋世魂器",
            sprite="FuShiHunQi",
            view_name="WorldSoulView",
            mod_key=56044,
            act_type=2130,
            new_sign=1
        },
        {
            seq=24,
            text="回归豪礼",
            sprite="HuiGuiHaoLi",
            view_name="RegressRewardView",
            mod_key=56045,
            act_type=2132
        },
        {
            seq=25,
            text="万灵奇闻",
            sprite="WanLingQiWen",
            view_name="SoulsAnecdoteView",
            mod_key=56048,
            act_type=2138,
            position=1
        },
        {
            seq=26,
            text="神宠兑换",
            sprite="ChongWuDuiHuan",
            view_name="ActPetExchangeView",
            mod_key=56017,
            act_type=2072,
            new_sign=1
        },
        {
            seq=27,
            text="宠物夺宝",
            sprite="ChongWuDuoBao",
            view_name="PetLootView",
            mod_key=56036,
            act_type=2101,
            new_sign=1
        },
        {
            seq=28,
            text="财神聚宝",
            sprite="WealthCornucopia",
            view_name="WealthCornucopiaView",
            mod_key=64003,
            act_type=2084,
            new_sign=1
        },
        {
            seq=29,
            text="灵宠祈愿",
            sprite="ZhaoCaiJinBao",
            view_name="ActZhaoCaiJinBaoView",
            mod_key=56049,
            act_type=2146,
            new_sign=1
        },
        {
            seq=30,
            text="吉星高照",
            sprite="JiXingGaoZhao",
            view_name="ActJiXingGaoZhaoView",
            mod_key=56054,
            act_type=2164,
            new_sign=1
        },
        {
            seq=31,
            text="周末累充礼",
            sprite="LimitRecharge",
            view_name="LimitRechargeView",
            mod_key=56056,
            act_type=2169,
            new_sign=1
        },
        {
            seq=32,
            text="魂器天成",
            sprite="HunQiTianCheng",
            view_name="HorcruxTianchengView",
            mod_key=56047,
            act_type=2139,
            new_sign=1
        },
        {
            seq=33,
            text="超值献礼",
            sprite="ChaoZhiXianLi",
            view_name="ChaoZhiGiftView",
            mod_key=56057,
            act_type=2171,
            new_sign=1,
            effect=3165054
        },
        {
            seq=34,
            text="神宠降临",
            sprite="ShenShouJiangLin",
            view_name="PetBefallView",
            mod_key=64005,
            act_type=2103,
            new_sign=1,
            effect=""
        },
        {
            seq=35,
            text="情缘累充",
            mod_key=23018,
            act_type=2184,
            position=0,
            effect=""
        },
        {
            seq=36,
            text="锦衣天香",
            sprite="JinYiTianXiang",
            view_name="ClothAromaView",
            mod_key=56060,
            act_type=2194,
            new_sign=1,
            effect=""
        },
        {
            seq=37,
            text="异兽临世",
            sprite="YiShouLinShi",
            view_name="AnimalWorldView",
            mod_key=141001,
            act_type=2185,
            effect=""
        },
        {
            seq=38,
            text="熔炼有礼",
            sprite="RongLianYouLi",
            view_name="ActEquipSmeltView",
            mod_key=56058,
            act_type=2172,
            position=1,
            effect=""
        },
        {
            seq=39,
            text="幸运盲盒",
            sprite="XingYunMangHe",
            view_name="ActLuckDrawBoxView",
            mod_key=56061,
            act_type=2204,
            effect=""
        },
        {
            seq=40,
            text="300抽皮肤",
            sprite="SanBaiChou",
            view_name="ThreeHundredSkin",
            mod_key=150001,
            act_type=2206,
            effect=""
        },
        {
            seq=41,
            text="齐天大圣|天水灵龙|天舞金龙",
            sprite="JinLongJuBao|ShuiLingLong|JinLong",
            view_name="GoldRMinecView",
            mod_key=151001,
            act_type=2208,
            effect=""
        },
        {
            seq=42,
            text="周末限时礼",
            sprite="ZhenPingHangPu",
            view_name="PreciousStoreView",
            mod_key=113007,
            act_type=2128,
            effect=""
        },
        {
            seq=43,
            text="跨服英雄录",
            sprite="KuaFuYingXiongLu",
            view_name="KFHeroRecordView",
            mod_key=152001,
            effect=""
        },
        {
            seq=44,
            text="天衣曜世",
            sprite="TianYiYaoShi",
            view_name="TianYiYaoShiView",
            mod_key=56062,
            act_type=2219,
            effect=6165243
        },
        {
            seq=45,
            text="神赐华服",
            sprite="ShenCiHuaFu",
            view_name="GodClothesView",
            mod_key=56063,
            act_type=2218,
            effect=6165277
        },
        {
            seq=46,
            text="双十二狂欢",
            sprite="DanBiFanLi",
            view_name="SingleRebateView",
            mod_key=56064,
            act_type=2223,
            effect=""
        },
        {
            seq=47,
            text="华诞登录礼",
            sprite="ElementCards",
            view_name="ElementCardsView",
            act_type=2082,
            new_sign=1
        },
        {
            seq=48,
            text="登录连好礼",
            sprite="DengLuLianHaoLi",
            view_name="SignHappyView",
            mod_key=56047,
            act_type=2135,
            position=1
        },
        {
            seq=49,
            text="周年好礼",
            sprite="ZhouNianQing",
            view_name="SignInContinuityView",
            mod_key=56027,
            act_type=2083
        },
        {
            seq=50,
            text="周年狂欢",
            sprite="ZhouNianKuangHuanRuKouTuBiao",
            view_name="DiscountCarnivalView",
            mod_key=56019,
            act_type=2069
        },
        {
            seq=51,
            text="周末连充礼",
            sprite="ZhouMoLianChongLi",
            view_name="WeekendOverChargeView",
            mod_key=56067,
            act_type=2233,
            effect=7164034
        },
        {
            seq=52,
            text="大展宏兔",
            sprite="DaZhanHongTu",
            view_name="DaZhanHongTuView",
            mod_key=56068,
            act_type=2237,
            effect=""
        },
        {
            seq=53,
            text="好友邀请",
            sprite="YaoQingHaoYou",
            view_name="InviteFriendView",
            mod_key=56066,
            act_type=2232
        },
        {
            seq=54,
            view_name="LevelGiftNotice",
            mod_key=102001,
            sub_name="level_gift_notice_sub"
        },
        {
            seq=55,
            mod_key=8001,
            position=0,
            sub_name="cloud_arena_sub"
        },
        {
            seq=56,
            mod_key=104001,
            position=0,
            sub_name="chief_election_sub"
        },
        {
            seq=57,
            mod_key=104002,
            position=0,
            sub_name="guild_melee_sub"
        },
        {
            seq=58,
            mod_key=104003,
            position=0,
            sub_name="guild_embattle_sub"
        },
        {
            seq=59,
            mod_key=104004,
            sub_name="arena_match_sub"
        },
        {
            seq=60,
            text="论剑九州",
            sprite="LunJianJiuZhou",
            view_name="LunJianSignupView",
            mod_key=128002
        },
        {
            seq=61,
            text="英雄会武",
            sprite="YingXiongHuiWu",
            view_name="HeroVanBattleGloryView",
            mod_key=131004,
            sub_name="hero_van_battle_sub"
        },
        {
            seq=62,
            text="英雄会武",
            sprite="YingXiongHuiWu",
            view_name="HeroVanBattleView",
            mod_key=131001,
            sub_name="hero_van_battle_sub"
        },
        {
            seq=63,
            text="天下第一",
            sprite="TianXiaDiYi",
            view_name="UniverseTeamArenaMain",
            mod_key=132001,
            sub_name="uta_icon_sub"
        },
        {
            seq=64,
            text="神域",
            sprite="ShenYu",
            view_name="LandsBetweenMainView",
            mod_key=161001,
            sub_name="lands_between_sub"
        }
    },
    btn_list={
        {
            seq=1,
            text="",
            view_name="FirstChargeView",
            mod=56002,
            mod_key=56002,
            sub_name="recharge_sub"
        },
        {
            seq=2,
            text="福利",
            sprite="JiangLi",
            view_name="RewardView",
            mod="Reward",
            effect=10010334,
            mod_key=45001
        },
        {
            seq=3,
            text="新服活动",
            sprite="XinFuHuoDong",
            view_name="ServerActivityView",
            mod="ServerActivity",
            effect=10010312,
            mod_key=34001
        },
        {
            seq=4,
            text="新服比拼",
            sprite="XinFuBiPin",
            view_name="CompetitionRankView",
            mod=56059,
            mod_key=56059,
            sub_name="competition_rank_sub"
        },
        {
            seq=5,
            text="桂月时分",
            sprite="JingCaiHuoDong",
            view_name="",
            mod="Splendid",
            effect=10010312,
            new_sign=1,
            mod_key=64001,
            sub_name="splendid_sub",
            is_open=0
        },
        {
            seq=6,
            text="圣诞狂欢",
            sprite="ShengDanJie",
            view_name="ActHalloweenView",
            mod="Act_Halloween",
            effect=7164005,
            mod_key=166001,
            is_open=0,
            interface=2
        },
        {
            seq=7,
            text="燃情五一",
            sprite="RanQingWuYi",
            view_name="LabourDayView",
            mod="LabourDay",
            effect=30000867,
            mod_key=47001,
            is_open=0
        },
        {
            seq=8,
            text="天地道痕",
            sprite="TianDiDaoHen",
            view_name="GodLandTracesView",
            mod="GodLandTraces",
            mod_key=108001
        },
        {
            seq=9,
            text="暑期活动",
            sprite="ShuQiHuoDong",
            view_name="SummerFirstView",
            mod="SummerFirst",
            mod_key=120001,
            is_open=0
        },
        {
            seq=10,
            text="山海绘卷",
            sprite="GuoQingHuoDong",
            view_name="NationalDayView",
            mod="NationalDay",
            effect=5161017,
            new_sign=1,
            mod_key=113001,
            is_open=0
        },
        {
            seq=11,
            text="万灵印象",
            sprite="PaiQiHuoDong",
            view_name="PlanActivityView",
            mod="PlanActivity",
            effect=10010312,
            new_sign=1,
            mod_key=75001,
            sub_name="plan_activity_sub"
        },
        {
            seq=12,
            text="山海回想",
            sprite="ShanHanHuiXiang",
            view_name="MountainSeaTotalView",
            mod="MountainSea",
            effect=5167004,
            new_sign=1,
            mod_key=118001,
            sub_name="mountain_sea_sub",
            is_open=0
        },
        {
            seq=13,
            text="大梦云泽",
            sprite="YunZeIcon",
            view_name="YunZeView",
            mod="YunZe",
            effect=10010312,
            new_sign=1,
            mod_key=121001,
            is_open=0
        },
        {
            seq=14,
            text="前兔似锦",
            sprite="TuNianXinChun",
            view_name="RabbitYearView",
            mod="RabbitYear",
            effect=6167017,
            mod_key=171001,
            sub_name=0,
            is_open=0,
            interface=""
        },
        {
            seq=15,
            text="",
            view_name="LoginRewardView",
            mod=56003,
            effect=2165041,
            mod_key=56003,
            sub_name="login_reward_sub"
        },
        {
            seq=16,
            text="缘牵万灵|山海明月",
            sprite="ZhouQiHuoDong",
            view_name="PeriodActivityView",
            mod="PeriodActivity",
            effect=7165070,
            mod_key=49000,
            effect_type=1
        },
        {
            seq=17,
            text="百神之师",
            sprite="JiangZiYa",
            view_name="HundredGodBoss",
            mod="HundredGodBoss",
            effect=10010334,
            mod_key=138001
        },
        {
            seq=18,
            text="元气庆典",
            sprite="YuanQiQingDian",
            view_name="MayDayView",
            mod="MayDay",
            effect=6165154,
            new_sign=1,
            mod_key=139001,
            is_open=0
        },
        {
            seq=19,
            text="飘香端阳",
            sprite="DuanWu2",
            view_name="ActDragonBoatMainView",
            mod="DragonBoat",
            effect=6165164,
            mod_key=148001,
            is_open=0
        },
        {
            seq=20,
            text="魅力情人节",
            sprite="MeiLiQiXi",
            view_name="QixiFestivalView",
            mod="QixiFestival",
            mod_key=149001
        },
        {
            seq=21,
            text="元宵狂欢",
            sprite="GanEnJie",
            view_name="YmzqView",
            mod="MidAutumnFestival",
            effect=7164030,
            mod_key=157001,
            is_open=0
        },
        {
            seq=22,
            text="大玩咖",
            sprite="QQBigPlayer",
            view_name="QQBigPlayerView",
            mod="QQBigPlayer",
            mod_key=168001
        },
        {
            seq=23,
            sprite="SpecialPowerQQ",
            view_name="SpecialPowerQQView",
            mod=34014,
            mod_key=34014
        },
        {
            seq=24,
            sprite="SpecialPower360",
            mod=34013,
            mod_key=34013
        },
        {
            seq=25,
            text="双端互通",
            sprite="DoublePlat360",
            view_name="DoublePlat360View",
            mod=34015,
            mod_key=34015
        },
        {
            seq=26,
            sprite="SpecialPowerShunWang",
            mod=34016,
            mod_key=34016
        },
        {
            seq=27,
            text="双端互通",
            sprite="DoublePlat360",
            view_name="DoublePlat360View",
            mod=34017,
            mod_key=34017
        }
    },
    spring_festival={
        {
            seq=0,
            text="圣诞商城",
            view_name="HalloweenShopView",
            act_type=2229,
            mod_key=166003,
            desc="珍稀好礼，购买即得"
        },
        {
            seq=1,
            text="圣诞祈福",
            view_name="HalloweenPrayView",
            act_type=2226,
            mod_key=166004,
            desc="绝世珍品，幸运祈愿"
        },
        {
            seq=2,
            text="艾香满城",
            view_name="CowGoingLuckView",
            act_type=2092,
            mod_key=46003,
            desc="专属好礼，累充即得"
        },
        {
            seq=3,
            text="圣诞密令",
            view_name="ShengDanMiLingView",
            act_type=2231,
            mod_key=166006,
            desc="节日祝贺，好运无限"
        }
    },
    burning_may_day={
        {
            seq=1,
            text="春日登峰",
            view_name="SpringClimbView",
            act_type=2108,
            mod_key=47002,
            reward_item={
                [0]=_itemlist.i_26813_1_1,
                [1]=_itemlist.i_24326_1_1
            },
            desc="7层宝塔藏秘宝，琉璃佩中藏玄机，探索寻踪得秘宝！"
        },
        {
            seq=2,
            text="劳动好礼",
            view_name="LabourGiftView",
            act_type=2110,
            mod_key=47003,
            reward_item={
                [0]=_itemlist.i_24607_1_1,
                [1]=_itemlist.i_25952_1_1,
                [2]=_itemlist.i_27187_1_1
            },
            desc="劳动好礼从天降，每晚20:00静待好礼。"
        },
        {
            seq=3,
            text="特惠秘宝",
            view_name="SpSecretTreasureView",
            act_type=2105,
            mod_key=56030,
            reward_item={
                [0]=_itemlist.i_27541_1_1,
                [1]=_itemlist.i_27575_1_1,
                [2]=_itemlist.i_27398_1_1
            },
            desc="特惠秘宝再登场，五一特惠不容错过！"
        },
        {
            seq=4,
            text="秘境奇闻",
            act_type=2109,
            reward_item={
                [0]=_itemlist.i_25951_1_1,
                [1]=_itemlist.i_25950_1_1,
                [2]=_itemlist.i_27187_1_1
            },
            desc="五一惊现特殊秘境，在秘境内又将发生何种奇遇，静待各位少侠前往探查！"
        },
        {
            seq=5,
            text="义胆助人",
            act_type=2106,
            reward_item={
                [0]=_itemlist.i_25089_1_1,
                [1]=_itemlist.i_29032_1_1,
                [2]=_itemlist.i_29038_1_1
            },
            desc="忠肝义胆助人为乐，每日助人拿好礼。请少侠们速速前往帮助需要帮助的人。"
        },
        {
            seq=6,
            text="组合贺礼",
            view_name="CombineGiftView",
            act_type=2111,
            mod_key=47004,
            reward_item={
                [0]=_itemlist.i_29038_1_1,
                [1]=_itemlist.i_24326_1_1
            },
            desc="绝世好礼两两组合，专属折扣乐享优惠，欢迎大家前来选购哦！"
        }
    },
    summer_first={
        {
            seq=1,
            text="山海争锋",
            view_name="SummerExperienceView",
            act_type=2124,
            mod_key=120002,
            reward_item={
                [0]=_itemlist.i_26813_1_1,
                [1]=_itemlist.i_24326_1_1
            },
            desc="夏日炎炎妖魔横行，望各位侠义之士历练之时前往消灭妖魔，击败所有首领妖魔即可获得“谁与争锋”称号哦！"
        },
        {
            seq=2,
            text="多彩花灯",
            view_name="FlowerLampView",
            act_type=2125,
            mod_key=120003,
            reward_item={
                [0]=_itemlist.i_26813_1_1,
                [1]=_itemlist.i_24326_1_1
            },
            desc="花灯朵朵水中开，夏日清凉河里游。钓花灯得积分，任务满满拿奖励！"
        },
        {
            seq=3,
            text="夏日商城",
            view_name="SummerFirstShopView",
            act_type=2127,
            mod_key=120004,
            reward_item={
                [0]=_itemlist.i_26813_1_1,
                [1]=_itemlist.i_24326_1_1
            },
            desc="夏日烈阳高空挂，商城内里藏乾坤。多重秘宝，珍稀道具，等你挑选！"
        },
        {
            seq=4,
            text="好运花签",
            view_name="LuckySignView",
            act_type=2117,
            mod_key=120005,
            reward_item={
                [0]=_itemlist.i_26813_1_1,
                [1]=_itemlist.i_24326_1_1
            },
            desc="每日一签求好运，签签缘来千千结！每日可求取一只花签哦~"
        },
        {
            seq=5,
            text="琼楼玉宴",
            view_name="BanquetView",
            act_type=2118,
            mod_key=120007,
            reward_item={
                [0]=_itemlist.i_26813_1_1,
                [1]=_itemlist.i_24326_1_1
            },
            desc="炎炎夏日，宴会必不可少。全服少侠通过[助人一夏]收集食材，筹备宴会，筹备成功即可品尝满桌珍馐哦！"
        },
        {
            seq=6,
            text="助人一夏",
            reward_item={
                [0]=_itemlist.i_26813_1_1,
                [1]=_itemlist.i_24326_1_1
            }
        },
        {
            seq=7,
            text="元气翻牌",
            view_name="CoolCardView",
            act_type=2120,
            mod_key=120010,
            reward_item={
                [0]=_itemlist.i_26813_1_1,
                [1]=_itemlist.i_24326_1_1
            },
            desc="每日签到祈福运，事事如意万事顺！每日可抽取一次签文哦~"
        },
        {
            seq=8,
            text="莲香助人",
            reward_item={
                [0]=_itemlist.i_26813_1_1,
                [1]=_itemlist.i_24326_1_1
            }
        },
        {
            seq=9,
            text="折扣商城",
            view_name="SummerDiscountShopView",
            act_type=2119,
            mod_key=120006,
            reward_item={
                [0]=_itemlist.i_26813_1_1,
                [1]=_itemlist.i_24326_1_1
            },
            desc="夏日烈阳高空挂，商城内里藏乾坤。多重秘宝，珍稀道具，等你挑选！"
        },
        {
            seq=10,
            text="荷香觅宝",
            view_name="LotusTreasureView",
            act_type=2122,
            mod_key=120009,
            reward_item={
                [0]=_itemlist.i_26813_1_1,
                [1]=_itemlist.i_24326_1_1
            },
            desc="莲花重重藏宝藏，荷香阵阵飘满城。寻找印鉴碎片，点亮印鉴，即可获得道具奖励！"
        },
        {
            seq=11,
            text="夏日迷宫",
            view_name="SummerMazeView",
            act_type=2123,
            mod_key=120008,
            reward_item={
                [0]=_itemlist.i_26813_1_1,
                [1]=_itemlist.i_24326_1_1
            },
            desc="夏日深，迷宫现，重重迷雾，静待少侠前往探索！"
        },
        {
            seq=12,
            text="凉风送爽",
            view_name="CoolBreezeView",
            act_type=2121,
            mod_key=120011,
            reward_item={
                [0]=_itemlist.i_26813_1_1,
                [1]=_itemlist.i_24326_1_1
            },
            desc="夏日微风醉人心，好事多磨待君解。完成任务，拿绝世好礼！"
        }
    },
    national_day={
        {
            seq=1,
            text="露月争锋",
            view_name="SummerExperienceView",
            act_type=2124,
            mod_key=113002,
            reward_item={
                [0]=_itemlist.i_26813_1_1,
                [1]=_itemlist.i_24326_1_1
            },
            desc="妖魔横行，致民众生活在水深火热之中，望各位侠义之士历练之时前往消灭妖魔，击败所有首领妖魔即可获得“首领终结者”称号哦！",
            act_tag="威震首领"
        },
        {
            seq=2,
            text="好运花签",
            view_name="LuckySignView",
            act_type=2117,
            mod_key=113004,
            reward_item={
                [0]=_itemlist.i_26813_1_1,
                [1]=_itemlist.i_24326_1_1
            },
            desc="每日一签求好运，签签缘来千千结！每日可求取一只花签哦~",
            act_tag="签到赠礼"
        },
        {
            seq=3,
            text="多彩河灯",
            view_name="FlowerLampView",
            act_type=2125,
            mod_key=113003,
            reward_item={
                [0]=_itemlist.i_26813_1_1,
                [1]=_itemlist.i_24326_1_1
            },
            desc="花灯朵朵水中开，思念满满河里游。钓花灯得积分，任务满满拿奖励！"
        },
        {
            seq=4,
            text="桂香觅宝",
            view_name="LotusTreasureView",
            act_type=2122,
            mod_key=113005,
            reward_item={
                [0]=_itemlist.i_26813_1_1,
                [1]=_itemlist.i_24326_1_1
            },
            desc="桂香满城藏宝藏，清香阵阵飘满城。寻找印鉴碎片，点亮印鉴，即可获得道具奖励！"
        }
    },
    plan_activity={
        {
            seq=1,
            text="万灵共盈",
            view_name="AllSoulsFullView",
            mod_key=75002,
            act_type=2136
        },
        {
            seq=2,
            text="万灵筑礼",
            view_name="AllSoulCastView",
            mod_key=139008,
            act_type=2193
        },
        {
            seq=3,
            text="万灵有礼",
            view_name="ThrivingShopView",
            mod_key=56005,
            act_type=2060
        },
        {
            seq=4,
            text="万灵图鉴",
            view_name="ColorfulIllustrateView",
            mod_key=56007,
            act_type=2058
        },
        {
            seq=5,
            text="万灵秘宝",
            view_name="CowOriginView",
            mod_key=46005,
            act_type=2094
        },
        {
            seq=6,
            text="万灵迷宫",
            view_name="LuckyMazeView",
            mod_key=56038,
            act_type=2107
        },
        {
            seq=7,
            text="万灵画卷",
            view_name="HeritageTreasureView",
            mod_key=64002,
            act_type=2057
        },
        {
            seq=8,
            text="桃源好礼",
            view_name="HeavenGiftView",
            mod_key=56012,
            act_type=2064
        },
        {
            seq=9,
            text="桃源妖兽",
            view_name="LustrateNianView",
            mod_key=56004,
            act_type=2056
        },
        {
            seq=10,
            text="万灵宝箱",
            view_name="CustomizedTreasureView",
            mod_key=56032,
            act_type=2085
        },
        {
            seq=11,
            text="桃源一三事",
            view_name="HelpOthersView",
            mod_key=75003,
            act_type=2137
        },
        {
            seq=12,
            text="桃源特卖",
            view_name="SaleShopView",
            mod_key=56006,
            act_type=2059
        },
        {
            seq=13,
            text="桃源团购",
            view_name="QmDiscountView",
            mod_key=56018,
            act_type=2078
        },
        {
            seq=14,
            text="桃源秒杀",
            view_name="LuckyDiscountView",
            mod_key=56023,
            act_type=2071
        },
        {
            seq=15,
            text="万灵花礼",
            view_name="FourSeasonCardView",
            mod_key=76001,
            act_type=2214
        },
        {
            seq=16,
            text="万灵宝盒",
            view_name="FourSeasonBoxView",
            mod_key=76002,
            act_type=2215
        }
    },
    recall_summary={
        {
            seq=1,
            text="山海聚宝",
            view_name="MountainSeaMineCView",
            mod_key=118010,
            act_type=2143
        },
        {
            seq=2,
            text="连连乐翻天",
            view_name="HappyLinkupView",
            mod_key=56046,
            act_type=2134
        },
        {
            seq=3,
            text="山海花灯",
            view_name="MSFlowerLampView",
            mod_key=118005,
            act_type=2160
        },
        {
            seq=4,
            text="山海争锋",
            view_name="SummerExperienceTwoView",
            mod_key=118004,
            act_type=2155
        },
        {
            seq=5,
            text="山海觅宝",
            view_name="MSLotusTreasureView",
            mod_key=118006,
            act_type=2156
        },
        {
            seq=6,
            text="山海问答",
            view_name="MountainSeaQuestionView",
            mod_key=118002,
            act_type=2142
        },
        {
            seq=7,
            text="山海缘起",
            view_name="MountainSeaTask",
            mod_key=118008,
            act_type=2145
        },
        {
            seq=8,
            text="山海风月",
            view_name="MountainSeaWindMoonView",
            mod_key=118003,
            act_type=2140
        },
        {
            seq=9,
            text="山海初遇",
            view_name="MountainSeaFirstMeetView",
            mod_key=118007,
            act_type=2141
        },
        {
            seq=10,
            text="山海相逢",
            view_name="MountainSeaMeetView",
            mod_key=118009,
            act_type=2144
        },
        {
            seq=11,
            text="山海宝箱",
            view_name="SeaCustomizedBoxView",
            mod_key=118013,
            act_type=2157
        }
    },
    yunzemengce={
        {
            seq=1,
            text="大梦云泽",
            view_name="CloudSwampView",
            mod_key=56050,
            act_type=2150
        },
        {
            seq=2,
            text="魔族在哪里",
            view_name="MoZuZaiNaLiView",
            mod_key=56051,
            act_type=2151
        },
        {
            seq=3,
            text="云泽画境",
            view_name="YunZeTerritoryView",
            mod_key=121002,
            act_type=2147
        },
        {
            seq=4,
            text="云泽二三事",
            view_name="YunZeErSanShiView",
            mod_key=56052,
            act_type=2153
        },
        {
            seq=5,
            text="云泽繁花录",
            view_name="ActFlowerTouchView",
            mod_key=56053,
            act_type=2148
        },
        {
            seq=6,
            text="纷享同花礼",
            view_name="ActSameFlowerView",
            mod_key=121004,
            act_type=2149
        },
        {
            seq=7,
            text="超值纷享",
            view_name="SuperValueEnjoyView",
            mod_key=121003,
            act_type=2152
        },
        {
            seq=8,
            text="纷享加倍",
            view_name="EnjoyRedoubleView",
            mod_key=121008,
            act_type=2154
        },
        {
            seq=9,
            text="精灵大抓捕",
            view_name="ElvesCatchView",
            mod_key=121009,
            act_type=2168
        },
        {
            seq=10,
            text="云泽好礼",
            view_name="YunZeNiceGiftView",
            mod_key=121011,
            act_type=2166
        },
        {
            seq=11,
            text="云泽祈愿",
            view_name="YZWishView",
            mod_key=121010,
            act_type=2165
        },
        {
            seq=12,
            text="萌宠驾到",
            view_name="MengChongJiaDaoView",
            mod_key=121012,
            act_type=2167
        },
        {
            seq=13,
            text="云泽宝箱",
            view_name="YunZeCustomizedBoxView",
            mod_key=121007,
            act_type=2161
        }
    },
    other={
        {
            phase=0
        }
    },
    tiger_spring_festival={
        {
            seq=1,
            text="迎春纳福",
            view_name="YingChunView",
            mod_key=172004,
            act_type=2236,
            desc="稀世道具，抽出好运"
        },
        {
            seq=2,
            text="福运商城",
            view_name="RabbitYearShopView",
            mod_key=172003,
            act_type=2234,
            desc="珍稀好礼，任君挑选"
        },
        {
            seq=3,
            text="鸿运累充",
            view_name="RabbitYearChargeView",
            mod_key=172005,
            act_type=2227,
            desc="累充豪礼，尽情放送"
        },
        {
            seq=4,
            text="星星点灯",
            view_name="XingXingDianDengView",
            mod_key=172002,
            act_type=2235,
            desc="星星点灯，照亮前路"
        }
    },
    yuanqiqingdian={
        {
            seq=1,
            text="元气翻牌",
            view_name="VitalityFlop",
            mod_key=139005,
            act_type=2191,
            picture=0,
            plan_type=5
        },
        {
            seq=2,
            text="元气助人",
            view_name="VitalityHelpOthersView",
            mod_key=139002,
            act_type=2188,
            picture="Gou"
        },
        {
            seq=3,
            text="祈愿天灯",
            view_name="SkyLanternView",
            mod_key=139003,
            act_type=2186,
            picture="Tu"
        },
        {
            seq=4,
            text="包子来了",
            view_name="BunComeView",
            mod_key=139009,
            act_type=2192
        },
        {
            seq=5,
            text="乘风破浪",
            view_name="BravingView",
            mod_key=139011,
            act_type=2198,
            picture="HuoYueHuoDong"
        },
        {
            seq=6,
            text="播种有礼",
            view_name="SowRewardView",
            mod_key=139006,
            act_type=2190
        },
        {
            seq=7,
            text="元气竞速",
            view_name="YuanQiSpeedView",
            mod_key=139012,
            act_type=2187,
            picture="Tu"
        },
        {
            seq=8,
            text="妙笔生花",
            view_name="ArticulatelyView",
            mod_key=139007,
            act_type=2195,
            picture="HuoYueHuoDong"
        },
        {
            seq=9,
            text="寻梦蝴蝶",
            view_name="CatchButterflies",
            mod_key=139004,
            act_type=2189,
            picture="Gou"
        },
        {
            seq=10,
            text="元气烟火秀",
            view_name="VitalityFireworkView",
            mod_key=139010,
            act_type=2196,
            picture="ZhiGouShangDian",
            plan_type=4,
            show=1
        },
        {
            seq=11,
            text="元气记事簿",
            view_name="VitalityNoteView",
            mod_key=139013,
            act_type=2197,
            picture="ZhiGouShangDian",
            plan_type=4,
            show=1
        }
    },
    duanwu_festival={
        {
            seq=0,
            location=0,
            text="苍龙赐福",
            view_name="ActDragonCollectView",
            mod_key=148006,
            act_type=2203
        },
        {
            seq=1,
            end_time=2,
            location=1,
            text="甜咸之争",
            view_name="SweetSaltyWarView",
            mod_key=148003,
            act_type=2200
        },
        {
            seq=2,
            start_time=3,
            end_time=4,
            location=2,
            text="兰汤初沐",
            view_name="SoupBathView",
            mod_key=148004,
            act_type=2205
        },
        {
            seq=3,
            start_time=5,
            end_time=6,
            location=3,
            text="粽香满城",
            view_name="ReedIncenseCityView",
            mod_key=148002,
            act_type=2199,
            is_close=1
        },
        {
            seq=4,
            start_time=7,
            location=1,
            text="端阳香囊",
            view_name="NoonSachetView",
            mod_key=148007,
            act_type=2201
        },
        {
            seq=5,
            end_time=2
        },
        {
            seq=6,
            start_time=3,
            end_time=4,
            text="端阳宝箱",
            view_name="CustomizedTreasureView",
            mod_key=56032,
            act_type=2085
        },
        {
            seq=7,
            start_time=5,
            end_time=6,
            text="端阳宝袋",
            view_name="ChainBoxView",
            mod_key=56033,
            act_type=2089
        },
        {
            seq=8,
            start_time=7
        },
        {
            seq=9,
            end_time=4,
            location=5,
            text="端阳福礼",
            view_name="ActDuanYangFuLiView",
            mod_key=148008,
            act_type=2207
        },
        {
            seq=10,
            start_time=5,
            location=5,
            text="端阳自选",
            view_name="ActDuanYangZiXuanLiView",
            mod_key=148005,
            act_type=2202
        }
    },
    charm_tanabata={
        {
            seq=1,
            text="魅力情人节",
            view_name="ActMeiLiQiXiView",
            mod_key=149003,
            act_type=2213
        },
        {
            seq=2,
            text="钟情特惠",
            view_name="SevenDayView",
            mod_key=149002,
            act_type=2212
        }
    },
    battle_show={
        {
            name="华诞庆典",
            act_type=2223,
            sprite="DanBiFanLi",
            mod_key=56064,
            weight=1
        },
        {
            name="华诞登录礼",
            act_type=2082,
            sprite="ElementCards",
            mod_key=56026,
            weight=2
        },
        {
            name="登录连好礼",
            act_type=2135,
            sprite="DengLuLianHaoLi",
            weight=3
        },
        {
            name="周年连好礼",
            act_type=2083,
            sprite="SignInContinuity",
            mod_key=56027,
            weight=4
        },
        {
            name="周年狂欢",
            act_type=2069,
            sprite="ZheKouKuangHuan",
            mod_key=56019,
            weight=5
        },
        {
            name="神宠兑换",
            act_type=2072,
            sprite="ChongWuDuiHuan",
            mod_key=56017,
            weight=6
        },
        {
            name="宠物夺宝",
            act_type=2101,
            sprite="ChongWuDuoBao",
            mod_key=56036,
            weight=7
        },
        {
            name="财神聚宝",
            act_type=2084,
            sprite="WealthCornucopia",
            mod_key=64003,
            weight=8
        },
        {
            name="众神之首|巴蛇问世",
            sprite="LianDongSongLi|BaSheZaiShi",
            mod_key=56001,
            weight=9
        },
        {
            name="首充专属",
            sprite="ShouChongZhuanShu",
            mod_key=56041,
            weight=10
        },
        {
            name="神装惊世",
            act_type=2100,
            sprite="LeiJiChongZhi",
            mod_key=56035,
            weight=11
        },
        {
            name="令牌天赐",
            act_type=2112,
            sprite="LingPaiTianCi",
            mod_key=56039,
            weight=12
        },
        {
            name="赋世魂器",
            act_type=2130,
            sprite="FuShiHunQi",
            mod_key=56044,
            weight=13
        },
        {
            name="周末累充礼",
            act_type=2169,
            sprite="LimitRecharge",
            mod_key=56056,
            weight=14
        },
        {
            name="幸运盲盒",
            act_type=2204,
            sprite="XingYunMangHe",
            mod_key=56061,
            weight=15
        },
        {
            name="300抽皮肤",
            act_type=2206,
            sprite="SanBaiChou",
            mod_key=150001,
            weight=16
        },
        {
            name="齐天大圣|天水灵龙|天舞金龙",
            act_type=2208,
            sprite="JinLongJuBao|ShuiLingLong|JinLong",
            mod_key=151001,
            weight=17
        },
        {
            name="周末限时礼",
            act_type=2128,
            sprite="ZhenPingHangPu",
            mod_key=113007,
            weight=18
        },
        {
            name="跨服英雄录",
            sprite="KuaFuYingXiongLu",
            mod_key=152001,
            weight=19
        },
        {
            name="天衣曜世",
            act_type=2219,
            sprite="TianYiYaoShi",
            mod_key=56062,
            weight=20
        },
        {
            name="神赐华服",
            act_type=2218,
            sprite="ShenCiHuaFu",
            mod_key=56063,
            weight=21
        },
        {
            name="灵宠祈愿",
            act_type=2146,
            sprite="ZhaoCaiJinBao",
            mod_key=56049,
            weight=22
        },
        {
            name="吉星高照",
            act_type=2164,
            sprite="JiXingGaoZhao",
            mod_key=56054,
            weight=23
        },
        {
            name="周末连充礼",
            act_type=2233,
            sprite="ZhouMoLianChongLi",
            mod_key=56067,
            weight=24
        },
        {
            name="魂器天成",
            act_type=2139,
            sprite="HunQiTianCheng",
            weight=25
        },
        {
            name="超值献礼",
            act_type=2171,
            sprite="ChaoZhiXianLi",
            mod_key=56057,
            weight=26
        },
        {
            name="神宠降临",
            act_type=2103,
            sprite="ShenShouJiangLin",
            mod_key=64005,
            weight=27
        },
        {
            name="锦衣天香",
            act_type=2194,
            sprite="JinYiTianXiang",
            mod_key=56060,
            weight=28
        },
        {
            name="福利",
            sprite="JiangLi",
            mod_key=45001,
            weight=29
        },
        {
            name="新服活动",
            sprite="XinFuHuoDong",
            mod_key=34001,
            weight=30
        },
        {
            name="新服比拼",
            act_type=2133,
            sprite="XinFuBiPin",
            mod_key=56059,
            weight=31
        },
        {
            name="万灵印象",
            sprite="PaiQiHuoDong",
            mod_key=75001,
            weight=32
        },
        {
            name="山海回想",
            sprite="ShanHanHuiXiang",
            mod_key=118001,
            weight=33
        },
        {
            name="大梦云泽",
            sprite="YunZeIcon",
            mod_key=121001,
            weight=34
        }
    },
    moon_mid_autumn={
        {
            seq=0,
            location=1,
            text="元宵累充",
            view_name="ActYxlcView",
            mod_key=157003,
            act_type=2222,
            desc="元宵馈赠,累充赠礼"
        },
        {
            location=2,
            text="元宵商城",
            view_name="ActZyscView",
            mod_key=157004,
            act_type=2224,
            desc="元宵狂欢,心愿得偿"
        },
        {
            location=3,
            text="元宵问答",
            view_name="YxdmView",
            mod_key=157002,
            act_type=2221,
            is_close=0,
            desc="趣味谜题,与谜同行"
        }
    }
}
SetConfigDefaultVal(Config.activity_main_auto,_default_val,nil,nil,nil)