local _default_val={
    arena={
        seq=0,
        bind_coin=0
    },
    robot_cfg={
        level_show=42
    },
    arena_achievement={
        ach_group=1,
        achieve_type=0,
        ach_param1=10,
        progress_way=1,
        price_type=0,
        price_num=0
    },
    battle_reward={
        integral=50,
        bind_coin=10000,
        rate=2000
    }
}
local _itemlist={
    i_27398_1_1={
        item_id=27398,
        num=1,
        is_bind=1
    },
    i_27398_2_1={
        item_id=27398,
        num=2,
        is_bind=1
    },
    i_27398_3_1={
        item_id=27398,
        num=3,
        is_bind=1
    },
    i_27398_4_1={
        item_id=27398,
        num=4,
        is_bind=1
    },
    i_27398_5_1={
        item_id=27398,
        num=5,
        is_bind=1
    },
    i_27398_6_1={
        item_id=27398,
        num=6,
        is_bind=1
    },
    i_27398_7_1={
        item_id=27398,
        num=7,
        is_bind=1
    },
    i_27398_8_1={
        item_id=27398,
        num=8,
        is_bind=1
    },
    i_27398_9_1={
        item_id=27398,
        num=9,
        is_bind=1
    },
    i_27398_10_1={
        item_id=27398,
        num=10,
        is_bind=1
    },
    i_27398_11_1={
        item_id=27398,
        num=11,
        is_bind=1
    },
    i_27398_12_1={
        item_id=27398,
        num=12,
        is_bind=1
    },
    i_27398_13_1={
        item_id=27398,
        num=13,
        is_bind=1
    },
    i_27398_15_1={
        item_id=27398,
        num=15,
        is_bind=1
    },
    i_56318_2_1={
        item_id=56318,
        num=2,
        is_bind=1
    }
}
Config.arena_cfg_auto={
    arena={
        {
            min_level=0,
            max_level=9,
            exp=2000
        },
        {
            min_level=10,
            max_level=19,
            exp=3000
        },
        {
            min_level=20,
            max_level=29,
            exp=4000
        },
        {
            min_level=30,
            max_level=39,
            exp=5000
        },
        {
            min_level=40,
            max_level=49,
            exp=7000
        },
        {
            min_level=50,
            max_level=59,
            exp=8250
        },
        {
            min_level=60,
            max_level=69,
            exp=9750
        },
        {
            min_level=70,
            max_level=79,
            exp=11250
        },
        {
            min_level=80,
            max_level=89,
            exp=12500
        },
        {
            min_level=90,
            max_level=99,
            exp=14250
        },
        {
            min_level=100,
            max_level=109,
            exp=15750
        },
        {
            min_level=110,
            max_level=120,
            exp=18000
        }
    },
    other={
        {
            challenge_times=10,
            win_price=50,
            lose_price=20,
            reward_pool=1000000,
            min_num=10,
            min_coin=100000,
            integral_pool=100000,
            integral_coin=10000,
            open_time="1:00:00:00",
            end_time="7:23:59:59",
            refresh_time=5,
            end_round=15,
            top_one_title=109,
            top_ten_title=110,
            refresh_intervar=60,
            battle_reward=50,
            skip_open_level=1,
            raiding_battle=60,
            open_level=34
        }
    },
    reward={
        {
            seq=0,
            min_rank=1,
            max_rank=3,
            bind_coin=15000,
            rank_price=2700
        },
        {
            seq=1,
            min_rank=4,
            max_rank=10,
            bind_coin=12000,
            rank_price=2400
        },
        {
            seq=2,
            min_rank=11,
            max_rank=20,
            bind_coin=9000,
            rank_price=2100
        },
        {
            seq=3,
            min_rank=21,
            max_rank=50,
            bind_coin=7000,
            rank_price=1800
        },
        {
            seq=4,
            min_rank=51,
            max_rank=100,
            bind_coin=5000,
            rank_price=1500
        },
        {
            seq=5,
            min_rank=101,
            max_rank=200,
            bind_coin=3000,
            rank_price=1200
        },
        {
            seq=6,
            min_rank=201,
            max_rank=500,
            bind_coin=1500,
            rank_price=900
        },
        {
            seq=7,
            min_rank=501,
            max_rank=1000,
            bind_coin=800,
            rank_price=500
        },
        {
            seq=8,
            min_rank=1001,
            max_rank=9999,
            bind_coin=300,
            rank_price=250
        }
    },
    robot_cfg={
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=36
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=35
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=34
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=33
        },
        {
            level_show=32
        },
        {
            level_show=31
        },
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=36
        },
        {
            level_show=32
        },
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=36
        },
        {
            level_show=32
        },
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {},
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=41
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=40
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=38
        },
        {
            level_show=36
        },
        {
            level_show=32
        }
    },
    attr_adjust_group={},
    buff_group={
        {
            buff_id=444
        },
        {
            buff_id=445
        },
        {
            buff_id=446
        },
        {
            buff_id=447
        },
        {
            buff_id=448
        },
        {
            buff_id=449
        },
        {
            buff_id=450
        }
    },
    rank_section={},
    arena_achievement={
        {
            sn=1,
            ach_name="天梯·壹",
            ach_dsc="竞技场排名前<color=#0278C2>1000</color>名",
            ach_param1=1000,
            progress_way=2,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=2,
            ach_name="天梯·贰",
            ach_dsc="竞技场排名前<color=#0278C2>800</color>名",
            ach_param1=800,
            progress_way=2,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=3,
            ach_name="天梯·叁",
            ach_dsc="竞技场排名前<color=#0278C2>500</color>名",
            ach_param1=500,
            progress_way=2,
            item_list={
                [0]=_itemlist.i_27398_3_1
            }
        },
        {
            sn=4,
            ach_name="天梯·肆",
            ach_dsc="竞技场排名前<color=#0278C2>300</color>名",
            ach_param1=300,
            progress_way=2,
            item_list={
                [0]=_itemlist.i_27398_4_1
            }
        },
        {
            sn=5,
            ach_name="天梯·伍",
            ach_dsc="竞技场排名前<color=#0278C2>200</color>名",
            ach_param1=200,
            progress_way=2,
            item_list={
                [0]=_itemlist.i_27398_5_1
            }
        },
        {
            sn=6,
            ach_name="天梯·陆",
            ach_dsc="竞技场排名前<color=#0278C2>100</color>名",
            ach_param1=100,
            progress_way=2,
            item_list={
                [0]=_itemlist.i_27398_6_1
            }
        },
        {
            sn=7,
            ach_name="天梯·柒",
            ach_dsc="竞技场排名前<color=#0278C2>50</color>名",
            ach_param1=50,
            progress_way=2,
            item_list={
                [0]=_itemlist.i_27398_7_1
            }
        },
        {
            sn=8,
            ach_name="天梯·捌",
            ach_dsc="竞技场排名前<color=#0278C2>30</color>名",
            ach_param1=30,
            progress_way=2,
            item_list={
                [0]=_itemlist.i_27398_8_1
            }
        },
        {
            sn=9,
            ach_name="天梯·玖",
            ach_dsc="竞技场排名前<color=#0278C2>20</color>名",
            ach_param1=20,
            progress_way=2,
            item_list={
                [0]=_itemlist.i_27398_9_1
            }
        },
        {
            sn=10,
            ach_name="天梯·拾",
            ach_dsc="竞技场排名前<color=#0278C2>10</color>名",
            progress_way=2,
            item_list={
                [0]=_itemlist.i_27398_10_1
            }
        },
        {
            sn=11,
            ach_name="天梯·拾壹",
            ach_dsc="竞技场排名前<color=#0278C2>5</color>名",
            ach_param1=5,
            progress_way=2,
            item_list={
                [0]=_itemlist.i_27398_11_1
            }
        },
        {
            sn=12,
            ach_name="天梯·拾贰",
            ach_dsc="竞技场排名第<color=#0278C2>3</color>名",
            ach_param1=3,
            progress_way=2,
            item_list={
                [0]=_itemlist.i_27398_12_1
            }
        },
        {
            sn=13,
            ach_name="天梯·拾叁",
            ach_dsc="竞技场排名第<color=#0278C2>2</color>名",
            ach_param1=2,
            progress_way=2,
            item_list={
                [0]=_itemlist.i_27398_13_1
            }
        },
        {
            sn=14,
            ach_name="天梯·拾肆",
            ach_dsc="竞技场排名第<color=#0278C2>1</color>名",
            ach_param1=1,
            progress_way=2,
            item_list={
                [0]=_itemlist.i_27398_15_1
            }
        },
        {
            sn=15,
            ach_group=2,
            ach_name="善战·壹",
            ach_dsc="累计挑战竞技场<color=#0278C2>10</color>次",
            achieve_type=1,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=16,
            ach_group=2,
            ach_name="善战·贰",
            ach_dsc="累计挑战竞技场<color=#0278C2>20</color>次",
            achieve_type=1,
            ach_param1=20,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=17,
            ach_group=2,
            ach_name="善战·叁",
            ach_dsc="累计挑战竞技场<color=#0278C2>50</color>次",
            achieve_type=1,
            ach_param1=50,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=18,
            ach_group=2,
            ach_name="善战·肆",
            ach_dsc="累计挑战竞技场<color=#0278C2>80</color>次",
            achieve_type=1,
            ach_param1=80,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=19,
            ach_group=2,
            ach_name="善战·伍",
            ach_dsc="累计挑战竞技场<color=#0278C2>100</color>次",
            achieve_type=1,
            ach_param1=100,
            item_list={
                [0]=_itemlist.i_27398_3_1
            }
        },
        {
            sn=20,
            ach_group=3,
            ach_name="无双·壹",
            ach_dsc="累计获得<color=#0278C2>1</color>次战斗胜利",
            achieve_type=2,
            ach_param1=1,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=21,
            ach_group=3,
            ach_name="无双·贰",
            ach_dsc="累计获得<color=#0278C2>2</color>次战斗胜利",
            achieve_type=2,
            ach_param1=2,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=22,
            ach_group=3,
            ach_name="无双·叁",
            ach_dsc="累计获得<color=#0278C2>5</color>次战斗胜利",
            achieve_type=2,
            ach_param1=5,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=23,
            ach_group=3,
            ach_name="无双·肆",
            ach_dsc="累计获得<color=#0278C2>10</color>次战斗胜利",
            achieve_type=2,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=24,
            ach_group=3,
            ach_name="无双·伍",
            ach_dsc="累计获得<color=#0278C2>20</color>次战斗胜利",
            achieve_type=2,
            ach_param1=20,
            item_list={
                [0]=_itemlist.i_27398_3_1
            }
        },
        {
            sn=25,
            ach_group=3,
            ach_name="无双·陆",
            ach_dsc="累计获得<color=#0278C2>50</color>次战斗胜利",
            achieve_type=2,
            ach_param1=50,
            item_list={
                [0]=_itemlist.i_27398_5_1
            }
        },
        {
            sn=26,
            ach_group=3,
            ach_name="无双·柒",
            ach_dsc="累计获得<color=#0278C2>80</color>次战斗胜利",
            achieve_type=2,
            ach_param1=80,
            item_list={
                [0]=_itemlist.i_27398_8_1
            }
        },
        {
            sn=27,
            ach_group=3,
            ach_name="无双·捌",
            ach_dsc="累计获得<color=#0278C2>100</color>次战斗胜利",
            achieve_type=2,
            ach_param1=100,
            item_list={
                [0]=_itemlist.i_27398_10_1
            }
        },
        {
            sn=28,
            ach_group=4,
            ach_name="坚守·壹",
            ach_dsc="玩家被挑战获胜<color=#0278C2>5</color>场",
            achieve_type=3,
            ach_param1=5,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=29,
            ach_group=4,
            ach_name="坚守·贰",
            ach_dsc="玩家被挑战获胜<color=#0278C2>10</color>场",
            achieve_type=3,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=30,
            ach_group=4,
            ach_name="坚守·叁",
            ach_dsc="玩家被挑战获胜<color=#0278C2>20</color>场",
            achieve_type=3,
            ach_param1=20,
            item_list={
                [0]=_itemlist.i_27398_3_1
            }
        },
        {
            sn=31,
            ach_group=4,
            ach_name="坚守·肆",
            ach_dsc="玩家被挑战获胜<color=#0278C2>50</color>场",
            achieve_type=3,
            ach_param1=50,
            item_list={
                [0]=_itemlist.i_27398_5_1
            }
        },
        {
            sn=32,
            ach_group=5,
            ach_name="连捷·壹",
            ach_dsc="玩家连续获胜<color=#0278C2>2</color>场",
            achieve_type=5,
            ach_param1=2,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=33,
            ach_group=5,
            ach_name="连捷·贰",
            ach_dsc="玩家连续获胜<color=#0278C2>3</color>场",
            achieve_type=5,
            ach_param1=3,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=34,
            ach_group=5,
            ach_name="连捷·叁",
            ach_dsc="玩家连续获胜<color=#0278C2>5</color>场",
            achieve_type=5,
            ach_param1=5,
            item_list={
                [0]=_itemlist.i_27398_3_1
            }
        },
        {
            sn=35,
            ach_group=5,
            ach_name="连捷·肆",
            ach_dsc="玩家连续获胜<color=#0278C2>10</color>场",
            achieve_type=5,
            item_list={
                [0]=_itemlist.i_27398_5_1
            }
        },
        {
            sn=36,
            ach_group=5,
            ach_name="连捷·伍",
            ach_dsc="玩家连续获胜<color=#0278C2>20</color>场",
            achieve_type=5,
            ach_param1=20,
            item_list={
                [0]=_itemlist.i_27398_10_1
            }
        },
        {
            sn=37,
            ach_group=5,
            ach_name="连捷·陆",
            ach_dsc="玩家连续获胜<color=#0278C2>30</color>场",
            achieve_type=5,
            ach_param1=50,
            item_list={
                [0]=_itemlist.i_27398_12_1
            }
        },
        {
            sn=38,
            ach_group=6,
            ach_name="暴力·壹",
            ach_dsc="单场战斗累计造成<color=#0278C2>5000</color>点伤害",
            achieve_type=6,
            ach_param1=5000,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=39,
            ach_group=6,
            ach_name="暴力·贰",
            ach_dsc="单场战斗累计造成<color=#0278C2>8000</color>点伤害",
            achieve_type=6,
            ach_param1=8000,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=40,
            ach_group=6,
            ach_name="暴力·叁",
            ach_dsc="单场战斗累计造成<color=#0278C2>10000</color>点伤害",
            achieve_type=6,
            ach_param1=10000,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=41,
            ach_group=6,
            ach_name="暴力·肆",
            ach_dsc="单场战斗累计造成<color=#0278C2>20000</color>点伤害",
            achieve_type=6,
            ach_param1=20000,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=42,
            ach_group=7,
            ach_name="强势·壹",
            ach_dsc="战胜比自己综合评分高的玩家<color=#0278C2>5</color>次",
            achieve_type=7,
            ach_param1=5,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=43,
            ach_group=7,
            ach_name="强势·贰",
            ach_dsc="战胜比自己综合评分高的玩家<color=#0278C2>10</color>次",
            achieve_type=7,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=44,
            ach_group=7,
            ach_name="强势·叁",
            ach_dsc="战胜比自己综合评分高的玩家<color=#0278C2>15</color>次",
            achieve_type=7,
            ach_param1=15,
            item_list={
                [0]=_itemlist.i_27398_3_1
            }
        },
        {
            sn=45,
            ach_group=7,
            ach_name="强势·肆",
            ach_dsc="战胜比自己综合评分高的玩家<color=#0278C2>20</color>次",
            achieve_type=7,
            ach_param1=20,
            item_list={
                [0]=_itemlist.i_27398_4_1
            }
        },
        {
            sn=46,
            ach_group=7,
            ach_name="强势·伍",
            ach_dsc="战胜比自己综合评分高的玩家<color=#0278C2>30</color>次",
            achieve_type=7,
            ach_param1=30,
            item_list={
                [0]=_itemlist.i_27398_5_1
            }
        },
        {
            sn=47,
            ach_group=7,
            ach_name="强势·陆",
            ach_dsc="战胜比自己综合评分高的玩家<color=#0278C2>50</color>次",
            achieve_type=7,
            ach_param1=50,
            item_list={
                [0]=_itemlist.i_27398_8_1
            }
        },
        {
            sn=48,
            ach_group=8,
            ach_name="愈勇·壹",
            ach_dsc="累计战败<color=#0278C2>5</color>次",
            achieve_type=8,
            ach_param1=5,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=49,
            ach_group=8,
            ach_name="愈勇·贰",
            ach_dsc="累计战败<color=#0278C2>10</color>次",
            achieve_type=8,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=50,
            ach_group=8,
            ach_name="愈勇·叁",
            ach_dsc="累计战败<color=#0278C2>20</color>次",
            achieve_type=8,
            ach_param1=20,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=51,
            ach_group=8,
            ach_name="愈勇·肆",
            ach_dsc="累计战败<color=#0278C2>50</color>次",
            achieve_type=8,
            ach_param1=50,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=52,
            ach_group=9,
            ach_name="涅槃·壹",
            ach_dsc="累计复活<color=#0278C2>5</color>次",
            achieve_type=9,
            ach_param1=5,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=53,
            ach_group=9,
            ach_name="涅槃·贰",
            ach_dsc="累计复活<color=#0278C2>10</color>次",
            achieve_type=9,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=54,
            ach_group=9,
            ach_name="涅槃·叁",
            ach_dsc="累计复活<color=#0278C2>20</color>次",
            achieve_type=9,
            ach_param1=20,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=55,
            ach_group=9,
            ach_name="涅槃·肆",
            ach_dsc="累计复活<color=#0278C2>50</color>次",
            achieve_type=9,
            ach_param1=50,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=56,
            ach_group=10,
            ach_name="药罐·壹",
            ach_dsc="累计使用药品<color=#0278C2>10</color>次",
            achieve_type=10,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=57,
            ach_group=10,
            ach_name="药罐·贰",
            ach_dsc="累计使用药品<color=#0278C2>20</color>次",
            achieve_type=10,
            ach_param1=20,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=58,
            ach_group=10,
            ach_name="药罐·叁",
            ach_dsc="累计使用药品<color=#0278C2>50</color>次",
            achieve_type=10,
            ach_param1=50,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=59,
            ach_group=10,
            ach_name="药罐·肆",
            ach_dsc="累计使用药品<color=#0278C2>100</color>次",
            achieve_type=10,
            ach_param1=100,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=60,
            ach_group=11,
            ach_name="持久·壹",
            ach_dsc="战斗达到8回合并最终获胜<color=#0278C2>5</color>场",
            achieve_type=11,
            ach_param1=5,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=61,
            ach_group=11,
            ach_name="持久·贰",
            ach_dsc="战斗达到8回合并最终获胜<color=#0278C2>10</color>场",
            achieve_type=11,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=62,
            ach_group=11,
            ach_name="持久·叁",
            ach_dsc="战斗达到8回合并最终获胜<color=#0278C2>20</color>场",
            achieve_type=11,
            ach_param1=20,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=63,
            ach_group=11,
            ach_name="持久·肆",
            ach_dsc="战斗达到8回合并最终获胜<color=#0278C2>30</color>场",
            achieve_type=11,
            ach_param1=30,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=64,
            ach_group=12,
            ach_name="巾帼·壹",
            ach_dsc="不带女性伙伴胜利<color=#0278C2>3</color>场",
            achieve_type=12,
            ach_param1=3,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=65,
            ach_group=12,
            ach_name="巾帼·贰",
            ach_dsc="不带女性伙伴胜利<color=#0278C2>5</color>场",
            achieve_type=12,
            ach_param1=5,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=66,
            ach_group=12,
            ach_name="巾帼·叁",
            ach_dsc="不带女性伙伴胜利<color=#0278C2>10</color>场",
            achieve_type=12,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=67,
            ach_group=12,
            ach_name="巾帼·肆",
            ach_dsc="不带女性伙伴胜利<color=#0278C2>20</color>场",
            achieve_type=12,
            ach_param1=20,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=68,
            ach_group=13,
            ach_name="悍勇·壹",
            ach_dsc="不带男性伙伴胜利<color=#0278C2>3</color>场",
            achieve_type=13,
            ach_param1=3,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=69,
            ach_group=13,
            ach_name="悍勇·贰",
            ach_dsc="不带男性伙伴胜利<color=#0278C2>5</color>场",
            achieve_type=13,
            ach_param1=5,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=70,
            ach_group=13,
            ach_name="悍勇·叁",
            ach_dsc="不带男性伙伴胜利<color=#0278C2>10</color>场",
            achieve_type=13,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=71,
            ach_group=13,
            ach_name="悍勇·肆",
            ach_dsc="不带男性伙伴胜利<color=#0278C2>20</color>场",
            achieve_type=13,
            ach_param1=20,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=72,
            ach_group=14,
            ach_name="剑攻·壹",
            ach_dsc="玩家携带剑客伙伴获胜<color=#0278C2>5</color>场",
            achieve_type=14,
            ach_param1=5,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=73,
            ach_group=14,
            ach_name="剑攻·贰",
            ach_dsc="玩家携带剑客伙伴获胜<color=#0278C2>10</color>场",
            achieve_type=14,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=74,
            ach_group=14,
            ach_name="剑攻·叁",
            ach_dsc="玩家携带剑客伙伴获胜<color=#0278C2>20</color>场",
            achieve_type=14,
            ach_param1=20,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=75,
            ach_group=14,
            ach_name="剑攻·肆",
            ach_dsc="玩家携带剑客伙伴获胜<color=#0278C2>50</color>场",
            achieve_type=14,
            ach_param1=50,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=76,
            ach_group=15,
            ach_name="术法·壹",
            ach_dsc="玩家携带星术师伙伴获胜<color=#0278C2>5</color>场",
            achieve_type=15,
            ach_param1=5,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=77,
            ach_group=15,
            ach_name="术法·贰",
            ach_dsc="玩家携带星术师伙伴获胜<color=#0278C2>10</color>场",
            achieve_type=15,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=78,
            ach_group=15,
            ach_name="术法·叁",
            ach_dsc="玩家携带星术师伙伴获胜<color=#0278C2>20</color>场",
            achieve_type=15,
            ach_param1=20,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=79,
            ach_group=15,
            ach_name="术法·肆",
            ach_dsc="玩家携带星术师伙伴获胜<color=#0278C2>50</color>场",
            achieve_type=15,
            ach_param1=50,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=80,
            ach_group=16,
            ach_name="巫蛊·壹",
            ach_dsc="玩家携带巫师伙伴获胜<color=#0278C2>5</color>场",
            achieve_type=16,
            ach_param1=5,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=81,
            ach_group=16,
            ach_name="巫蛊·贰",
            ach_dsc="玩家携带巫师伙伴获胜<color=#0278C2>10</color>场",
            achieve_type=16,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=82,
            ach_group=16,
            ach_name="巫蛊·叁",
            ach_dsc="玩家携带巫师伙伴获胜<color=#0278C2>20</color>场",
            achieve_type=16,
            ach_param1=20,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=83,
            ach_group=16,
            ach_name="巫蛊·肆",
            ach_dsc="玩家携带巫师伙伴获胜<color=#0278C2>50</color>场",
            achieve_type=16,
            ach_param1=50,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=84,
            ach_group=17,
            ach_name="狂蛮·壹",
            ach_dsc="玩家携带狂战士伙伴获胜<color=#0278C2>5</color>场",
            achieve_type=17,
            ach_param1=5,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=85,
            ach_group=17,
            ach_name="狂蛮·贰",
            ach_dsc="玩家携带狂战士伙伴获胜<color=#0278C2>10</color>场",
            achieve_type=17,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=86,
            ach_group=17,
            ach_name="狂蛮·叁",
            ach_dsc="玩家携带狂战士伙伴获胜<color=#0278C2>20</color>场",
            achieve_type=17,
            ach_param1=20,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=87,
            ach_group=17,
            ach_name="狂蛮·肆",
            ach_dsc="玩家携带狂战士伙伴获胜<color=#0278C2>50</color>场",
            achieve_type=17,
            ach_param1=50,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=88,
            ach_group=18,
            ach_name="穿杨·壹",
            ach_dsc="玩家携带神射手伙伴获胜<color=#0278C2>5</color>场",
            achieve_type=18,
            ach_param1=5,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=89,
            ach_group=18,
            ach_name="穿杨·贰",
            ach_dsc="玩家携带神射手伙伴获胜<color=#0278C2>10</color>场",
            achieve_type=18,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=90,
            ach_group=18,
            ach_name="穿杨·叁",
            ach_dsc="玩家携带神射手伙伴获胜<color=#0278C2>20</color>场",
            achieve_type=18,
            ach_param1=20,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=91,
            ach_group=18,
            ach_name="穿杨·肆",
            ach_dsc="玩家携带神射手伙伴获胜<color=#0278C2>50</color>场",
            achieve_type=18,
            ach_param1=50,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=92,
            ach_group=19,
            ach_name="济世·壹",
            ach_dsc="玩家携带医师伙伴获胜<color=#0278C2>5</color>场",
            achieve_type=19,
            ach_param1=5,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=93,
            ach_group=19,
            ach_name="济世·贰",
            ach_dsc="玩家携带医师伙伴获胜<color=#0278C2>10</color>场",
            achieve_type=19,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=94,
            ach_group=19,
            ach_name="济世·叁",
            ach_dsc="玩家携带医师伙伴获胜<color=#0278C2>20</color>场",
            achieve_type=19,
            ach_param1=20,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=95,
            ach_group=19,
            ach_name="济世·肆",
            ach_dsc="玩家携带医师伙伴获胜<color=#0278C2>50</color>场",
            achieve_type=19,
            ach_param1=50,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=96,
            ach_group=20,
            ach_name="守卫·壹",
            ach_dsc="玩家携带铁卫伙伴获胜<color=#0278C2>5</color>场",
            achieve_type=20,
            ach_param1=5,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=97,
            ach_group=20,
            ach_name="守卫·贰",
            ach_dsc="玩家携带铁卫伙伴获胜<color=#0278C2>10</color>场",
            achieve_type=20,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=98,
            ach_group=20,
            ach_name="守卫·叁",
            ach_dsc="玩家携带铁卫伙伴获胜<color=#0278C2>20</color>场",
            achieve_type=20,
            ach_param1=20,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=99,
            ach_group=20,
            ach_name="守卫·肆",
            ach_dsc="玩家携带铁卫伙伴获胜<color=#0278C2>50</color>场",
            achieve_type=20,
            ach_param1=50,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=100,
            ach_group=21,
            ach_name="崩击·壹",
            ach_dsc="玩家携带拳师伙伴获胜<color=#0278C2>5</color>场",
            achieve_type=21,
            ach_param1=5,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=101,
            ach_group=21,
            ach_name="崩击·贰",
            ach_dsc="玩家携带拳师伙伴获胜<color=#0278C2>10</color>场",
            achieve_type=21,
            item_list={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            sn=102,
            ach_group=21,
            ach_name="崩击·叁",
            ach_dsc="玩家携带拳师伙伴获胜<color=#0278C2>20</color>场",
            achieve_type=21,
            ach_param1=20,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            sn=103,
            ach_group=21,
            ach_name="崩击·肆",
            ach_dsc="玩家携带拳师伙伴获胜<color=#0278C2>50</color>场",
            achieve_type=21,
            ach_param1=50,
            item_list={
                [0]=_itemlist.i_27398_2_1
            }
        }
    },
    history_rank_reward={
        {
            sn=1,
            rank_low=10,
            rank_high=1,
            reward=50
        },
        {
            sn=2,
            rank_low=20,
            rank_high=11,
            reward=20
        },
        {
            sn=3,
            rank_low=100,
            rank_high=21,
            reward=10
        },
        {
            sn=4,
            rank_low=500,
            rank_high=101,
            reward=5
        },
        {
            sn=5,
            rank_low=1000,
            rank_high=501,
            reward=2
        },
        {
            sn=6,
            rank_low=2000,
            rank_high=1001,
            reward=1
        }
    },
    battle_reward={
        {
            battle_price=1,
            rate=1000
        },
        {
            battle_price=2,
            bind_coin=5000
        },
        {
            battle_price=3,
            bind_coin=1000,
            rate=3000
        },
        {
            battle_price=4,
            item_list={
                [0]=_itemlist.i_56318_2_1
            },
            rate=500
        },
        {
            battle_price=5,
            item_list={
                [0]=_itemlist.i_56318_2_1
            },
            bind_coin=5000,
            rate=1500
        },
        {
            battle_price=6,
            item_list={
                [0]=_itemlist.i_56318_2_1
            },
            bind_coin=1000
        }
    }
}
SetConfigDefaultVal(Config.arena_cfg_auto,_default_val,nil,nil,nil)