local _default_val={
    operate_list={
        sp_name="",
        is_drag=0,
        is_pet_can=1,
        open=0
    }
}
Config.battle_operate_auto={
    operate_list={
        {
            index=1,
            name="物品",
            sprite_name="WuPin",
            move_type=4
        },
        {
            index=2,
            name="宠物",
            sprite_name="ChongWu",
            move_type=7
        },
        {
            index=3,
            name="法宝",
            sprite_name="FaBao",
            move_type=102,
            is_pet_can=0,
            open=24001
        },
        {
            index=4,
            name="心法",
            sprite_name="XinFa",
            move_type=12,
            is_pet_can=0,
            open=1005
        },
        {
            index=5,
            name="绝招",
            sprite_name="JueZhao",
            move_type=1,
            is_pet_can=0,
            open=1006
        },
        {
            index=6,
            name="逃跑",
            sprite_name="TaoPao",
            move_type=5,
            sp_name=51
        },
        {
            index=7,
            name="封印",
            sprite_name="FengYin",
            move_type=101
        },
        {
            index=8,
            name="换位",
            sprite_name="HuanWei",
            move_type=6,
            sp_name=41
        }
    },
    other={
        {
            open_level=1
        }
    }
}
SetConfigDefaultVal(Config.battle_operate_auto,_default_val,nil,nil,nil)