local _default_val={
    role_clue={
        suspicion=20,
        identity=2,
        directed="2|3|4|5|6|7|8",
        add_suspicion=10
    },
    item_clue={
        x=200,
        directed=3,
        add_suspicion=5
    }
}
Config.brothel_murder_auto={
    role_clue={
        {
            seq=0,
            npc_id=59010,
            name="阿香",
            stage_1_seq=59010,
            stage_1=0,
            stage_2_seq=59010,
            stage_2=72093,
            stage_3_seq=59010,
            stage_3=72093,
            suspicion=0,
            identity=0,
            desc="死者",
            note="死者嘴唇青黑，双眼充血，明显是<color=#B20202>中了致命剧毒</color>。可为何身体又遍布伤痕，这似乎是……虐尸泄愤？看起来更像是<color=#B20202>报复性谋杀</color>。"
        },
        {
            seq=1,
            npc_id=59011,
            name="品如",
            stage_1_seq=59011,
            stage_1=72084,
            stage_2_seq=59037,
            stage_2=72094,
            stage_3_seq=59037,
            stage_3=0,
            suspicion=0,
            identity=1,
            desc="温香楼的老板，风韵犹存，性格开朗大方，对姑娘们照顾有加",
            note="品如姑娘讲述了阿香的可怜身世，并且听起来阿香姑娘似乎因为性格的原因，<color=#B20202>曾经得罪过一些人</color>。"
        },
        {
            seq=2,
            npc_id=59012,
            name="妙雪姑娘",
            stage_1_seq=59012,
            stage_1=72085,
            stage_2_seq=59012,
            stage_2=72097,
            stage_3_seq=59012,
            stage_3=72106,
            directed="2|3|4|5",
            add_suspicion=5,
            desc="温香楼的红牌，美艳动人，似乎非常在意客人们对她的评价",
            note="在和妙雪姑娘的对话中，她对她和阿香的关系有所避讳。她在刻意隐瞒什么吗？"
        },
        {
            seq=3,
            npc_id=59013,
            name="巧月姑娘",
            stage_1_seq=59013,
            stage_1=72087,
            stage_2_seq=59013,
            stage_2=72098,
            stage_3_seq=59013,
            stage_3=72107,
            directed="2|3|6",
            desc="温香楼的红牌，性情温柔，对医卜之术似乎颇为擅长",
            note="巧月姑娘仔细观察了尸体的表现，并得出了<color=#B20202>不是寻常剧毒</color>的结论。这似乎并非是寻常风月之地的女子的见识。"
        },
        {
            seq=4,
            npc_id=59014,
            name="欧阳婆婆",
            stage_1_seq=59014,
            stage_1=72089,
            stage_2_seq=59014,
            stage_2=72095,
            stage_3_seq=59014,
            stage_3=72102,
            identity=3,
            directed=4,
            desc="平日负责调教温香楼的姑娘们，来历似乎颇为神秘",
            note="在和欧阳婆婆的谈话中得知，婆婆在<color=#B20202>负责温香楼的安全保卫</color>工作。并且因为阿香姑娘性格高傲，言谈令婆婆很看不惯。"
        },
        {
            seq=5,
            npc_id=59015,
            name="小秀儿",
            stage_1_seq=59015,
            stage_1=72090,
            stage_2_seq=59015,
            stage_2=72101,
            stage_3_seq=59015,
            stage_3=72108,
            directed=5,
            desc="年仅五岁，有些胆小怕生，自幼和欧阳婆婆相依为命",
            note="小秀儿表现出了对阿香的恐惧，<color=#B20202>阿香生前似乎不喜欢小秀儿</color>。她们之间曾经发生了什么？"
        },
        {
            seq=6,
            npc_id=59016,
            name="任公子",
            stage_1_seq=59016,
            stage_1=72236,
            stage_2_seq=59016,
            stage_2=72099,
            stage_3_seq=59016,
            stage_3=72109,
            directed=6,
            desc="风流倜傥的少年公子，和温香楼中人都很熟悉，似乎身份非同凡响",
            note="任公子似乎更中意巧月姑娘，并且在对话中并未暴露什么有嫌疑的信息。"
        },
        {
            seq=7,
            npc_id=59017,
            name="余少爷",
            stage_1_seq=59017,
            stage_1=72088,
            stage_2_seq=59017,
            stage_2=72100,
            stage_3_seq=59017,
            stage_3=72110,
            directed="7|8",
            desc="都城余家的长子，是温香楼的常客，平日里打赏姑娘出手甚是阔绰",
            note="余公子目前是已知在<color=#B20202>阿香死前接触的最后一个人</color>，看似二者感情颇深，但总觉得余少爷的情绪表现过分激烈。"
        },
        {
            seq=8,
            npc_id=59018,
            name="茗儿",
            stage_1_seq=59018,
            stage_1=72086,
            stage_2_seq=59044,
            stage_2=72096,
            stage_3_seq=59044,
            stage_3=72111,
            directed="2|3|7|8",
            desc="伺候姑娘和客人们的婢子，对温香楼大事小情都甚是清楚",
            note="茗儿对姑娘们的关系甚是了解，并且在对话中谈到，<color=#B20202>妙雪姑娘似乎对阿香颇为不喜</color>。"
        }
    },
    item_clue={
        {
            seq=1,
            item_name="一包香粉",
            icon=65542,
            x=146,
            y=156,
            directed=2,
            desc="发现了妙雪姑娘的香囊，似乎破了一个洞，香气四溢。里面是山奈、白芷、菖蒲、薄荷和藿香研磨而成的黄色粉末",
            note="发现了妙雪姑娘的香囊，里面的<color=#B20202>黄色粉末</color>，似乎在什么地方见过。"
        },
        {
            seq=2,
            item_name="客逢参",
            icon=65543,
            x=92,
            y=74,
            desc="发现了巧月姑娘的草药。《玄都本纪》记载：客逢，根参磨粉，以温酒送服有驻颜益血之效。然果实有剧毒，服之血逆而猝",
            note="发现了巧月姑娘的草药，“客逢参”虽有养颜驻容之效，<color=#B20202>但若服用不慎，足以令人丧命</color>。"
        },
        {
            seq=3,
            item_name="一枚银针",
            icon=65544,
            x=38,
            y=54,
            desc="发现了巧月姑娘的一枚银针，不过针尖似乎已经发黑",
            note="发现了巧月姑娘的一枚银针，不过<color=#B20202>针尖已经发黑</color>。"
        },
        {
            seq=4,
            item_name="沁血聆玉镯",
            icon=65545,
            y=172,
            directed="2|7",
            desc="发现了妙雪姑娘的沁血聆玉镯 ，丹琼沁血，价值不菲",
            note="意外发现了几日前<color=#B20202>余公子送给阿香的手镯</color>，为什么会出现在妙雪这里？这是不是说明，她可能比我们<color=#B20202>更早出现在案发现场</color>？"
        },
        {
            seq=5,
            item_name="一盒胭脂",
            icon=65546,
            y=196,
            directed=2,
            desc="发现了妙雪姑娘的胭脂，色彩鲜艳，极其精美，出自采蝶轩。不过似乎并没有什么香气",
            note="发现了妙雪姑娘的胭脂，色彩鲜艳，极其精美，出自采蝶轩。不过似乎并没有什么香气。"
        },
        {
            seq=6,
            item_name="一柄木剑",
            icon=65547,
            x=158,
            y=280,
            directed=5,
            add_suspicion=10,
            desc="发现了一把木剑，似乎是小孩子的玩具。剑身依稀散发出了一种奇异的香气",
            note="发现了一把木剑，似乎是小孩子的玩具。剑身的材料特殊，依稀散发出了一种奇异的香气。"
        },
        {
            seq=7,
            item_name="半壶醉仙酿",
            icon=65548,
            x=242,
            y=180,
            directed="7|8",
            add_suspicion=10,
            desc="发现了余少爷和阿香在案发前饮用的醉仙酿。这壶酒的酒香与寻常的醉仙酿相比，似乎格外浓烈",
            note="发现了余少爷和阿香在<color=#B20202>案发前饮用的醉仙酿</color>。这壶酒的酒香与寻常的醉仙酿相比，似乎格外浓烈 。"
        },
        {
            seq=8,
            item_name="不知名的古籍",
            icon=65549,
            x=381,
            y=152,
            directed=4,
            add_suspicion=20,
            desc="发现了欧阳婆婆的一本古籍。看起来年代久远，字迹已经有些模糊。依稀可以辨认出一些诡异的符文，似乎记载了神秘的咒术",
            note="发现了欧阳婆婆的一本古籍。看起来年代久远，字迹已经有些模糊。依稀可以辨认出一些诡异的符文，似乎记载了<color=#B20202>神秘的咒术 </color>。"
        }
    },
    event_cfg={
        {
            stage=1,
            x=226,
            y=212,
            talk_id=0
        },
        {
            stage=2,
            x=342,
            y=214,
            talk_id=72037
        }
    },
    other={
        {
            min_suspicion=60,
            prove_error=72037,
            prove_correct=72103,
            radius=30,
            item_radius=10,
            battle_1=27050,
            battle_2=27051,
            scene_id=1610,
            task_id=65081,
            fail_talk=72082,
            restart_talk=72081,
            end_talk=72104,
            npc_id=59020,
            bubble_id=115,
            talk_1=72083,
            talk_2=72092
        }
    }
}
SetConfigDefaultVal(Config.brothel_murder_auto,_default_val,nil,nil,nil)