local _default_val={
    colorful_lantern={
        section_start=1,
        section_end=0,
        task_type=2,
        task_param=3,
        param_2=0
    },
    lantern_configuration={
        score=0,
        speed_multiple=0,
        speed_time=0,
        scope_expand=0,
        scope_expand_time=0,
        rate=200
    },
    summer_lilian={
        section_start=1,
        section_end=0
    },
    leader_configuration={
        monster_group=1,
        level_down=32,
        level_up=50
    },
    reward_group={
        exp=0,
        coin=0,
        rate=100
    },
    summer_store={
        section_start=1,
        section_end=7,
        index=0,
        start_time=11,
        end_time=15,
        phase=3,
        seq=0,
        limit_type=2,
        buy_times=0,
        today_times=1,
        price_type=0,
        price=300,
        value=1200
    },
    qionglou_banquet={
        section_start=1,
        section_end=7,
        seq=0,
        prep_down=0,
        prep_up=449,
        banquet_type=0,
        reward_group=1,
        sp_reward_group=0
    },
    banquet_group={
        reward_group=1,
        rate=100
    },
    lucky_sign={
        section_start=1,
        section_end=7,
        seq=0,
        sign_group_id=1
    },
    huaqian_group={
        rate=250
    },
    sign_group_id={
        sign_group_id=1,
        luck="大吉"
    }
}
local _itemlist={
    i_27402_1_1={
        item_id=27402,
        num=1,
        is_bind=1
    },
    i_29018_1_1={
        item_id=29018,
        num=1,
        is_bind=1
    },
    i_26327_1_1={
        item_id=26327,
        num=1,
        is_bind=1
    },
    i_26327_2_1={
        item_id=26327,
        num=2,
        is_bind=1
    },
    i_28708_1_1={
        item_id=28708,
        num=1,
        is_bind=1
    },
    i_28709_1_1={
        item_id=28709,
        num=1,
        is_bind=1
    },
    i_28705_1_1={
        item_id=28705,
        num=1,
        is_bind=1
    },
    i_28706_1_1={
        item_id=28706,
        num=1,
        is_bind=1
    },
    i_28707_1_1={
        item_id=28707,
        num=1,
        is_bind=1
    },
    i_28716_1_1={
        item_id=28716,
        num=1,
        is_bind=1
    },
    i_28717_1_1={
        item_id=28717,
        num=1,
        is_bind=1
    },
    i_28713_1_1={
        item_id=28713,
        num=1,
        is_bind=1
    },
    i_28714_1_1={
        item_id=28714,
        num=1,
        is_bind=1
    },
    i_28715_1_1={
        item_id=28715,
        num=1,
        is_bind=1
    },
    i_25017_1_1={
        item_id=25017,
        num=1,
        is_bind=1
    },
    i_25951_1_1={
        item_id=25951,
        num=1,
        is_bind=1
    },
    i_25505_1_1={
        item_id=25505,
        num=1,
        is_bind=1
    },
    i_26813_8_1={
        item_id=26813,
        num=8,
        is_bind=1
    },
    i_25505_20_1={
        item_id=25505,
        num=20,
        is_bind=1
    },
    i_27541_8_1={
        item_id=27541,
        num=8,
        is_bind=1
    },
    i_25506_3_1={
        item_id=25506,
        num=3,
        is_bind=1
    },
    i_29021_150_1={
        item_id=29021,
        num=150,
        is_bind=1
    },
    i_27187_40_1={
        item_id=27187,
        num=40,
        is_bind=1
    },
    i_28067_1_1={
        item_id=28067,
        num=1,
        is_bind=1
    },
    i_25506_1_1={
        item_id=25506,
        num=1,
        is_bind=1
    },
    i_28070_1_1={
        item_id=28070,
        num=1,
        is_bind=1
    },
    i_28078_1_1={
        item_id=28078,
        num=1,
        is_bind=1
    },
    i_25950_1_1={
        item_id=25950,
        num=1,
        is_bind=1
    },
    i_29032_1_1={
        item_id=29032,
        num=1,
        is_bind=1
    },
    i_27398_1_1={
        item_id=27398,
        num=1,
        is_bind=1
    },
    i_26812_1_1={
        item_id=26812,
        num=1,
        is_bind=1
    },
    i_29021_180_1={
        item_id=29021,
        num=180,
        is_bind=1
    },
    i_22007_100_1={
        item_id=22007,
        num=100,
        is_bind=1
    },
    i_27575_10_1={
        item_id=27575,
        num=10,
        is_bind=1
    },
    i_29038_5_1={
        item_id=29038,
        num=5,
        is_bind=1
    },
    i_26393_1_1={
        item_id=26393,
        num=1,
        is_bind=1
    },
    i_27188_1_1={
        item_id=27188,
        num=1,
        is_bind=1
    },
    i_27398_2_1={
        item_id=27398,
        num=2,
        is_bind=1
    },
    i_27478_5_1={
        item_id=27478,
        num=5,
        is_bind=1
    },
    i_24326_2_1={
        item_id=24326,
        num=2,
        is_bind=1
    },
    i_27187_1_1={
        item_id=27187,
        num=1,
        is_bind=1
    },
    i_26812_3_1={
        item_id=26812,
        num=3,
        is_bind=1
    },
    i_27478_8_1={
        item_id=27478,
        num=8,
        is_bind=1
    },
    i_22006_3_1={
        item_id=22006,
        num=3,
        is_bind=1
    },
    i_22006_2_1={
        item_id=22006,
        num=2,
        is_bind=1
    },
    i_22006_1_1={
        item_id=22006,
        num=1,
        is_bind=1
    },
    i_26813_1_1={
        item_id=26813,
        num=1,
        is_bind=1
    },
    i_24326_3_1={
        item_id=24326,
        num=3,
        is_bind=1
    },
    i_27398_3_1={
        item_id=27398,
        num=3,
        is_bind=1
    },
    i_24326_1_1={
        item_id=24326,
        num=1,
        is_bind=1
    },
    i_29017_1_1={
        item_id=29017,
        num=1,
        is_bind=1
    },
    i_28555_1_1={
        item_id=28555,
        num=1,
        is_bind=1
    },
    i_27655_1_1={
        item_id=27655,
        num=1,
        is_bind=1
    },
    i_28522_1_1={
        item_id=28522,
        num=1,
        is_bind=1
    },
    i_29076_1_1={
        item_id=29076,
        num=1,
        is_bind=1
    }
}
Config.burning_summer_auto={
    other={
        {
            consume_item=26327,
            num=1,
            all_pass_reward_group=11,
            phase=3,
            cfg_ver=2,
            refresh_time=3,
            refresh_num_down=2,
            refresh_num_up=4,
            game_time=60,
            day_times=3,
            item_id_1=26324,
            item_id_2=26325,
            item_id_3=26326,
            prep_num=5,
            reward_group_2=6,
            banquet_num=5,
            banquet_times=1200,
            phase_times=5,
            start_time=1859,
            prepare_times=60,
            refresh=15
        }
    },
    colorful_lantern={
        {
            type=0,
            task_id=1,
            task_type=1,
            task_param=1,
            param_1=50,
            task_desc="单次获得50分",
            reward_item=_itemlist.i_27402_1_1
        },
        {
            type=1,
            task_id=2,
            task_type=1,
            task_param=1,
            param_1=100,
            task_desc="单次获得100分",
            reward_item=_itemlist.i_29018_1_1
        },
        {
            type=2,
            task_id=3,
            task_type=1,
            param_1=2,
            task_desc="参与2次多彩花灯",
            reward_item=_itemlist.i_26327_1_1
        },
        {
            type=3,
            task_id=4,
            task_param=2,
            param_1=300,
            task_desc="累计获得300分",
            reward_item=_itemlist.i_26327_1_1
        },
        {
            type=4,
            task_id=5,
            task_param=2,
            param_1=600,
            task_desc="累计获得600分",
            reward_item=_itemlist.i_26327_2_1
        },
        {
            type=5,
            task_id=6,
            param_1=5,
            task_desc="累计参与5次多彩花灯",
            reward_item=_itemlist.i_26327_1_1
        },
        {
            type=6,
            task_id=7,
            param_1=9,
            task_desc="累计参与9次多彩花灯",
            reward_item=_itemlist.i_26327_2_1
        }
    },
    lantern_configuration={
        {
            type=0,
            score=1
        },
        {
            type=1,
            score=2
        },
        {
            type=2,
            score=3
        },
        {
            type=3,
            score=5
        },
        {
            type=4,
            speed_multiple=2,
            speed_time=8,
            rate=100
        },
        {
            type=5,
            scope_expand=1.5,
            scope_expand_time=8,
            rate=100
        }
    },
    summer_lilian={
        {
            type=0,
            activity_time=1,
            monster_group=1,
            first_reward_group=1,
            random_reward_group=6,
            show_monster_id=53132,
            desc="赤角牛头，身披铠甲，狂暴起来威力无人能敌。"
        },
        {
            type=1,
            activity_time=2,
            monster_group=2,
            first_reward_group=2,
            random_reward_group=7,
            show_monster_id=53139,
            desc="赤首巨蛇可吞象，身体两分，暴躁异常。"
        },
        {
            type=2,
            activity_time=3,
            monster_group=3,
            first_reward_group=3,
            random_reward_group=8,
            show_monster_id=53146,
            desc="半人兽，手持利刃，威武非常。"
        },
        {
            type=3,
            activity_time=4,
            monster_group=4,
            first_reward_group=4,
            random_reward_group=9,
            show_monster_id=53153,
            desc="器械座驾，外壳坚硬不催且内里凶悍。"
        },
        {
            type=4,
            activity_time=5,
            monster_group=5,
            first_reward_group=5,
            random_reward_group=10,
            show_monster_id=53160,
            desc="随身携鼓，赤红毛发，凶猛异常。"
        }
    },
    leader_configuration={
        {
            monster_id_1=40310,
            monster_id_2=40310,
            monster_id_3=40310,
            monster_id_4=40310,
            monster_id_5=40310
        },
        {
            level_down=51,
            level_up=60,
            monster_id_1=40311,
            monster_id_2=40311,
            monster_id_3=40311,
            monster_id_4=40311,
            monster_id_5=40311
        },
        {
            level_down=61,
            level_up=70,
            monster_id_1=40312,
            monster_id_2=40312,
            monster_id_3=40312,
            monster_id_4=40312,
            monster_id_5=40312
        },
        {
            level_down=71,
            level_up=80,
            monster_id_1=40313,
            monster_id_2=40313,
            monster_id_3=40313,
            monster_id_4=40313,
            monster_id_5=40313
        },
        {
            level_down=81,
            level_up=90,
            monster_id_1=40314,
            monster_id_2=40314,
            monster_id_3=40314,
            monster_id_4=40314,
            monster_id_5=40314
        },
        {
            level_down=91,
            level_up=100,
            monster_id_1=40315,
            monster_id_2=40315,
            monster_id_3=40315,
            monster_id_4=40315,
            monster_id_5=40315
        },
        {
            level_down=101,
            level_up=120,
            monster_id_1=40316,
            monster_id_2=40316,
            monster_id_3=40316,
            monster_id_4=40316,
            monster_id_5=40316
        },
        {
            monster_group=2,
            monster_id_1=40317,
            monster_id_2=40317,
            monster_id_3=40317,
            monster_id_4=40317,
            monster_id_5=40317
        },
        {
            monster_group=2,
            level_down=51,
            level_up=60,
            monster_id_1=40318,
            monster_id_2=40318,
            monster_id_3=40318,
            monster_id_4=40318,
            monster_id_5=40318
        },
        {
            monster_group=2,
            level_down=61,
            level_up=70,
            monster_id_1=40319,
            monster_id_2=40319,
            monster_id_3=40319,
            monster_id_4=40319,
            monster_id_5=40319
        },
        {
            monster_group=2,
            level_down=71,
            level_up=80,
            monster_id_1=40320,
            monster_id_2=40320,
            monster_id_3=40320,
            monster_id_4=40320,
            monster_id_5=40320
        },
        {
            monster_group=2,
            level_down=81,
            level_up=90,
            monster_id_1=40321,
            monster_id_2=40321,
            monster_id_3=40321,
            monster_id_4=40321,
            monster_id_5=40321
        },
        {
            monster_group=2,
            level_down=91,
            level_up=100,
            monster_id_1=40322,
            monster_id_2=40322,
            monster_id_3=40322,
            monster_id_4=40322,
            monster_id_5=40322
        },
        {
            monster_group=2,
            level_down=101,
            level_up=120,
            monster_id_1=40323,
            monster_id_2=40323,
            monster_id_3=40323,
            monster_id_4=40323,
            monster_id_5=40323
        },
        {
            monster_group=3,
            monster_id_1=40324,
            monster_id_2=40324,
            monster_id_3=40324,
            monster_id_4=40324,
            monster_id_5=40324
        },
        {
            monster_group=3,
            level_down=51,
            level_up=60,
            monster_id_1=40325,
            monster_id_2=40325,
            monster_id_3=40325,
            monster_id_4=40325,
            monster_id_5=40325
        },
        {
            monster_group=3,
            level_down=61,
            level_up=70,
            monster_id_1=40326,
            monster_id_2=40326,
            monster_id_3=40326,
            monster_id_4=40326,
            monster_id_5=40326
        },
        {
            monster_group=3,
            level_down=71,
            level_up=80,
            monster_id_1=40327,
            monster_id_2=40327,
            monster_id_3=40327,
            monster_id_4=40327,
            monster_id_5=40327
        },
        {
            monster_group=3,
            level_down=81,
            level_up=90,
            monster_id_1=40328,
            monster_id_2=40328,
            monster_id_3=40328,
            monster_id_4=40328,
            monster_id_5=40328
        },
        {
            monster_group=3,
            level_down=91,
            level_up=100,
            monster_id_1=40329,
            monster_id_2=40329,
            monster_id_3=40329,
            monster_id_4=40329,
            monster_id_5=40329
        },
        {
            monster_group=3,
            level_down=101,
            level_up=120,
            monster_id_1=40330,
            monster_id_2=40330,
            monster_id_3=40330,
            monster_id_4=40330,
            monster_id_5=40330
        },
        {
            monster_group=4,
            monster_id_1=40331,
            monster_id_2=40331,
            monster_id_3=40331,
            monster_id_4=40331,
            monster_id_5=40331
        },
        {
            monster_group=4,
            level_down=51,
            level_up=60,
            monster_id_1=40332,
            monster_id_2=40332,
            monster_id_3=40332,
            monster_id_4=40332,
            monster_id_5=40332
        },
        {
            monster_group=4,
            level_down=61,
            level_up=70,
            monster_id_1=40333,
            monster_id_2=40333,
            monster_id_3=40333,
            monster_id_4=40333,
            monster_id_5=40333
        },
        {
            monster_group=4,
            level_down=71,
            level_up=80,
            monster_id_1=40334,
            monster_id_2=40334,
            monster_id_3=40334,
            monster_id_4=40334,
            monster_id_5=40334
        },
        {
            monster_group=4,
            level_down=81,
            level_up=90,
            monster_id_1=40335,
            monster_id_2=40335,
            monster_id_3=40335,
            monster_id_4=40335,
            monster_id_5=40335
        },
        {
            monster_group=4,
            level_down=91,
            level_up=100,
            monster_id_1=40336,
            monster_id_2=40336,
            monster_id_3=40336,
            monster_id_4=40336,
            monster_id_5=40336
        },
        {
            monster_group=4,
            level_down=101,
            level_up=120,
            monster_id_1=40337,
            monster_id_2=40337,
            monster_id_3=40337,
            monster_id_4=40337,
            monster_id_5=40337
        },
        {
            monster_group=5,
            monster_id_1=40338,
            monster_id_2=40338,
            monster_id_3=40338,
            monster_id_4=40338,
            monster_id_5=40338
        },
        {
            monster_group=5,
            level_down=51,
            level_up=60,
            monster_id_1=40339,
            monster_id_2=40339,
            monster_id_3=40339,
            monster_id_4=40339,
            monster_id_5=40339
        },
        {
            monster_group=5,
            level_down=61,
            level_up=70,
            monster_id_1=40340,
            monster_id_2=40340,
            monster_id_3=40340,
            monster_id_4=40340,
            monster_id_5=40340
        },
        {
            monster_group=5,
            level_down=71,
            level_up=80,
            monster_id_1=40341,
            monster_id_2=40341,
            monster_id_3=40341,
            monster_id_4=40341,
            monster_id_5=40341
        },
        {
            monster_group=5,
            level_down=81,
            level_up=90,
            monster_id_1=40342,
            monster_id_2=40342,
            monster_id_3=40342,
            monster_id_4=40342,
            monster_id_5=40342
        },
        {
            monster_group=5,
            level_down=91,
            level_up=100,
            monster_id_1=40343,
            monster_id_2=40343,
            monster_id_3=40343,
            monster_id_4=40343,
            monster_id_5=40343
        },
        {
            monster_group=5,
            level_down=101,
            level_up=120,
            monster_id_1=40344,
            monster_id_2=40344,
            monster_id_3=40344,
            monster_id_4=40344,
            monster_id_5=40344
        },
        {
            monster_group=6,
            monster_id_1=40345,
            monster_id_2=40345,
            monster_id_3=40345,
            monster_id_4=40345,
            monster_id_5=40345
        },
        {
            monster_group=6,
            level_down=51,
            level_up=60,
            monster_id_1=40346,
            monster_id_2=40346,
            monster_id_3=40346,
            monster_id_4=40346,
            monster_id_5=40346
        },
        {
            monster_group=6,
            level_down=61,
            level_up=70,
            monster_id_1=40347,
            monster_id_2=40347,
            monster_id_3=40347,
            monster_id_4=40347,
            monster_id_5=40347
        },
        {
            monster_group=6,
            level_down=71,
            level_up=80,
            monster_id_1=40348,
            monster_id_2=40348,
            monster_id_3=40348,
            monster_id_4=40348,
            monster_id_5=40348
        },
        {
            monster_group=6,
            level_down=81,
            level_up=90,
            monster_id_1=40349,
            monster_id_2=40349,
            monster_id_3=40349,
            monster_id_4=40349,
            monster_id_5=40349
        },
        {
            monster_group=6,
            level_down=91,
            level_up=100,
            monster_id_1=40350,
            monster_id_2=40350,
            monster_id_3=40350,
            monster_id_4=40350,
            monster_id_5=40350
        },
        {
            monster_group=6,
            level_down=101,
            level_up=120,
            monster_id_1=40351,
            monster_id_2=40351,
            monster_id_3=40351,
            monster_id_4=40351,
            monster_id_5=40351
        },
        {
            monster_group=7,
            monster_id_1=40352,
            monster_id_2=40352,
            monster_id_3=40352,
            monster_id_4=40352,
            monster_id_5=40352
        },
        {
            monster_group=7,
            level_down=51,
            level_up=60,
            monster_id_1=40353,
            monster_id_2=40353,
            monster_id_3=40353,
            monster_id_4=40353,
            monster_id_5=40353
        },
        {
            monster_group=7,
            level_down=61,
            level_up=70,
            monster_id_1=40354,
            monster_id_2=40354,
            monster_id_3=40354,
            monster_id_4=40354,
            monster_id_5=40354
        },
        {
            monster_group=7,
            level_down=71,
            level_up=80,
            monster_id_1=40355,
            monster_id_2=40355,
            monster_id_3=40355,
            monster_id_4=40355,
            monster_id_5=40355
        },
        {
            monster_group=7,
            level_down=81,
            level_up=90,
            monster_id_1=40356,
            monster_id_2=40356,
            monster_id_3=40356,
            monster_id_4=40356,
            monster_id_5=40356
        },
        {
            monster_group=7,
            level_down=91,
            level_up=100,
            monster_id_1=40357,
            monster_id_2=40357,
            monster_id_3=40357,
            monster_id_4=40357,
            monster_id_5=40357
        },
        {
            monster_group=7,
            level_down=101,
            level_up=120,
            monster_id_1=40358,
            monster_id_2=40358,
            monster_id_3=40358,
            monster_id_4=40358,
            monster_id_5=40358
        },
        {
            monster_group=8,
            monster_id_1=40359,
            monster_id_2=40359,
            monster_id_3=40359,
            monster_id_4=40359,
            monster_id_5=40359
        },
        {
            monster_group=8,
            level_down=51,
            level_up=60,
            monster_id_1=40360,
            monster_id_2=40360,
            monster_id_3=40360,
            monster_id_4=40360,
            monster_id_5=40360
        },
        {
            monster_group=8,
            level_down=61,
            level_up=70,
            monster_id_1=40361,
            monster_id_2=40361,
            monster_id_3=40361,
            monster_id_4=40361,
            monster_id_5=40361
        },
        {
            monster_group=8,
            level_down=71,
            level_up=80,
            monster_id_1=40362,
            monster_id_2=40362,
            monster_id_3=40362,
            monster_id_4=40362,
            monster_id_5=40362
        },
        {
            monster_group=8,
            level_down=81,
            level_up=90,
            monster_id_1=40363,
            monster_id_2=40363,
            monster_id_3=40363,
            monster_id_4=40363,
            monster_id_5=40363
        },
        {
            monster_group=8,
            level_down=91,
            level_up=100,
            monster_id_1=40364,
            monster_id_2=40364,
            monster_id_3=40364,
            monster_id_4=40364,
            monster_id_5=40364
        },
        {
            monster_group=8,
            level_down=101,
            level_up=120,
            monster_id_1=40365,
            monster_id_2=40365,
            monster_id_3=40365,
            monster_id_4=40365,
            monster_id_5=40365
        },
        {
            monster_group=9,
            monster_id_1=40366,
            monster_id_2=40366,
            monster_id_3=40366,
            monster_id_4=40366,
            monster_id_5=40366
        },
        {
            monster_group=9,
            level_down=51,
            level_up=60,
            monster_id_1=40367,
            monster_id_2=40367,
            monster_id_3=40367,
            monster_id_4=40367,
            monster_id_5=40367
        },
        {
            monster_group=9,
            level_down=61,
            level_up=70,
            monster_id_1=40368,
            monster_id_2=40368,
            monster_id_3=40368,
            monster_id_4=40368,
            monster_id_5=40368
        },
        {
            monster_group=9,
            level_down=71,
            level_up=80,
            monster_id_1=40369,
            monster_id_2=40369,
            monster_id_3=40369,
            monster_id_4=40369,
            monster_id_5=40369
        },
        {
            monster_group=9,
            level_down=81,
            level_up=90,
            monster_id_1=40370,
            monster_id_2=40370,
            monster_id_3=40370,
            monster_id_4=40370,
            monster_id_5=40370
        },
        {
            monster_group=9,
            level_down=91,
            level_up=100,
            monster_id_1=40371,
            monster_id_2=40371,
            monster_id_3=40371,
            monster_id_4=40371,
            monster_id_5=40371
        },
        {
            monster_group=9,
            level_down=101,
            level_up=120,
            monster_id_1=40372,
            monster_id_2=40372,
            monster_id_3=40372,
            monster_id_4=40372,
            monster_id_5=40372
        },
        {
            monster_group=10,
            monster_id_1=40373,
            monster_id_2=40373,
            monster_id_3=40373,
            monster_id_4=40373,
            monster_id_5=40373
        },
        {
            monster_group=10,
            level_down=51,
            level_up=60,
            monster_id_1=40374,
            monster_id_2=40374,
            monster_id_3=40374,
            monster_id_4=40374,
            monster_id_5=40374
        },
        {
            monster_group=10,
            level_down=61,
            level_up=70,
            monster_id_1=40375,
            monster_id_2=40375,
            monster_id_3=40375,
            monster_id_4=40375,
            monster_id_5=40375
        },
        {
            monster_group=10,
            level_down=71,
            level_up=80,
            monster_id_1=40376,
            monster_id_2=40376,
            monster_id_3=40376,
            monster_id_4=40376,
            monster_id_5=40376
        },
        {
            monster_group=10,
            level_down=81,
            level_up=90,
            monster_id_1=40377,
            monster_id_2=40377,
            monster_id_3=40377,
            monster_id_4=40377,
            monster_id_5=40377
        },
        {
            monster_group=10,
            level_down=91,
            level_up=100,
            monster_id_1=40378,
            monster_id_2=40378,
            monster_id_3=40378,
            monster_id_4=40378,
            monster_id_5=40378
        },
        {
            monster_group=10,
            level_down=101,
            level_up=120,
            monster_id_1=40379,
            monster_id_2=40379,
            monster_id_3=40379,
            monster_id_4=40379,
            monster_id_5=40379
        }
    },
    reward_group={
        {
            reward_group=1,
            reward_item={
                [0]=_itemlist.i_28708_1_1
            }
        },
        {
            reward_group=2,
            reward_item={
                [0]=_itemlist.i_28709_1_1
            }
        },
        {
            reward_group=3,
            reward_item={
                [0]=_itemlist.i_28705_1_1
            }
        },
        {
            reward_group=4,
            reward_item={
                [0]=_itemlist.i_28706_1_1
            }
        },
        {
            reward_group=5,
            reward_item={
                [0]=_itemlist.i_28707_1_1
            }
        },
        {
            reward_group=6,
            reward_item={
                [0]=_itemlist.i_28716_1_1
            }
        },
        {
            reward_group=7,
            reward_item={
                [0]=_itemlist.i_28717_1_1
            }
        },
        {
            reward_group=8,
            reward_item={
                [0]=_itemlist.i_28713_1_1
            }
        },
        {
            reward_group=9,
            reward_item={
                [0]=_itemlist.i_28714_1_1
            }
        },
        {
            reward_group=10,
            reward_item={
                [0]=_itemlist.i_28715_1_1
            }
        },
        {
            reward_group=11,
            reward_item={
                [0]=_itemlist.i_25017_1_1
            }
        }
    },
    summer_store={
        {
            type=0,
            start_time=1,
            end_time=5,
            phase=1,
            reward_item=_itemlist.i_25951_1_1,
            limit_type=1,
            buy_times=1,
            today_times=0,
            price_type=3,
            value=98
        },
        {
            type=1,
            index=1,
            start_time=1,
            end_time=5,
            phase=1,
            seq=1,
            reward_item=_itemlist.i_25505_1_1,
            price_type=3,
            price=60,
            value=18
        },
        {
            type=2,
            index=2,
            start_time=1,
            end_time=5,
            phase=1,
            seq=2,
            reward_item=_itemlist.i_26813_8_1,
            today_times=2,
            price_type=3,
            value=320
        },
        {
            type=3,
            index=3,
            start_time=1,
            end_time=5,
            phase=1,
            seq=3,
            reward_item=_itemlist.i_25505_20_1,
            today_times=10,
            price_type=3,
            price=500,
            value=160
        },
        {
            type=4,
            index=4,
            start_time=1,
            end_time=5,
            phase=1,
            seq=4,
            reward_item=_itemlist.i_27541_8_1,
            today_times=5,
            price_type=3,
            price=980,
            value=480
        },
        {
            type=5,
            index=5,
            start_time=1,
            end_time=5,
            phase=1,
            seq=5,
            reward_item=_itemlist.i_25506_3_1,
            today_times=3,
            price=1280,
            value=308
        },
        {
            type=6,
            index=6,
            start_time=1,
            end_time=5,
            phase=1,
            seq=6,
            reward_item=_itemlist.i_29021_150_1,
            limit_type=1,
            buy_times=1,
            today_times=0,
            price=3280,
            value=750
        },
        {
            type=7,
            index=7,
            start_time=1,
            end_time=5,
            phase=1,
            seq=7,
            reward_item=_itemlist.i_27187_40_1,
            price=6480
        },
        {
            type=8,
            index=8,
            start_time=1,
            end_time=5,
            phase=1,
            seq=8,
            reward_item=_itemlist.i_28067_1_1,
            today_times=5,
            price=375
        },
        {
            type=9,
            index=9,
            start_time=1,
            end_time=5,
            phase=1,
            seq=9,
            reward_item=_itemlist.i_25506_1_1,
            today_times=5,
            price_type=2,
            price=8000,
            value=15000
        },
        {
            type=10,
            index=10,
            start_time=1,
            end_time=5,
            phase=1,
            seq=10,
            reward_item=_itemlist.i_28070_1_1,
            today_times=5,
            price_type=2,
            price=30000,
            value=80000
        },
        {
            type=11,
            index=11,
            start_time=6,
            end_time=10,
            phase=2,
            reward_item=_itemlist.i_28078_1_1,
            price=3088,
            value=5888
        },
        {
            type=12,
            index=12,
            start_time=6,
            end_time=10,
            phase=2,
            seq=1,
            reward_item=_itemlist.i_25951_1_1,
            limit_type=1,
            buy_times=1,
            today_times=0,
            price_type=3,
            value=98
        },
        {
            type=13,
            index=13,
            start_time=6,
            end_time=10,
            phase=2,
            seq=2,
            reward_item=_itemlist.i_25950_1_1,
            limit_type=1,
            buy_times=1,
            today_times=0,
            price_type=3,
            price=1280,
            value=328
        },
        {
            type=14,
            index=14,
            start_time=6,
            end_time=10,
            phase=2,
            seq=3,
            reward_item=_itemlist.i_25505_1_1,
            price_type=3,
            price=60,
            value=18
        },
        {
            type=15,
            index=15,
            start_time=6,
            end_time=10,
            phase=2,
            seq=4,
            reward_item=_itemlist.i_29032_1_1,
            limit_type=1,
            buy_times=1,
            today_times=0,
            price_type=3,
            price=60,
            value=98
        },
        {
            type=16,
            index=16,
            start_time=6,
            end_time=10,
            phase=2,
            seq=5,
            reward_item=_itemlist.i_26813_8_1,
            today_times=2,
            price_type=3,
            value=320
        },
        {
            type=17,
            index=17,
            start_time=6,
            end_time=10,
            phase=2,
            seq=6,
            reward_item=_itemlist.i_25505_20_1,
            today_times=10,
            price=500,
            value=160
        },
        {
            type=18,
            index=18,
            start_time=6,
            end_time=10,
            phase=2,
            seq=7,
            reward_item=_itemlist.i_27541_8_1,
            today_times=5,
            price=980,
            value=480
        },
        {
            type=19,
            index=19,
            start_time=6,
            end_time=10,
            phase=2,
            seq=8,
            reward_item=_itemlist.i_25506_3_1,
            today_times=3,
            price=1280,
            value=308
        },
        {
            type=20,
            index=20,
            start_time=6,
            end_time=10,
            phase=2,
            seq=9,
            reward_item=_itemlist.i_27398_1_1,
            today_times=5,
            price_type=2,
            price=3000,
            value=10000
        },
        {
            type=21,
            index=21,
            start_time=6,
            end_time=10,
            phase=2,
            seq=10,
            reward_item=_itemlist.i_26812_1_1,
            today_times=3,
            price_type=2,
            price=15000,
            value=80000
        },
        {
            type=22,
            index=22,
            reward_item=_itemlist.i_29021_150_1,
            price_type=3,
            price=3280,
            value=750
        },
        {
            type=23,
            index=23,
            seq=1,
            reward_item=_itemlist.i_29021_180_1,
            limit_type=1,
            buy_times=1,
            today_times=0,
            price_type=3,
            price=3280,
            value=900
        },
        {
            type=24,
            index=24,
            seq=2,
            reward_item=_itemlist.i_27187_40_1,
            price_type=3,
            price=6480
        },
        {
            type=25,
            index=25,
            seq=3,
            reward_item=_itemlist.i_22007_100_1,
            today_times=30,
            price=3888,
            value=5888
        },
        {
            type=26,
            index=26,
            seq=4,
            reward_item=_itemlist.i_27575_10_1,
            today_times=30,
            price=198,
            value=388
        },
        {
            type=27,
            index=27,
            seq=5,
            reward_item=_itemlist.i_28067_1_1,
            today_times=10,
            price=375
        },
        {
            type=28,
            index=28,
            seq=6,
            reward_item=_itemlist.i_29038_5_1,
            today_times=30,
            price=388,
            value=500
        },
        {
            type=29,
            index=29,
            seq=7,
            reward_item=_itemlist.i_25506_1_1,
            today_times=30,
            price=880,
            value=1500
        },
        {
            type=30,
            index=30,
            seq=8,
            reward_item=_itemlist.i_28070_1_1,
            today_times=10,
            price=1150,
            value=2760
        },
        {
            type=31,
            index=31,
            seq=9,
            reward_item=_itemlist.i_28078_1_1,
            price=3088,
            value=5888
        },
        {
            type=32,
            index=32,
            seq=10,
            reward_item=_itemlist.i_27398_1_1,
            today_times=5,
            price_type=2,
            price=3000,
            value=10000
        },
        {
            type=33,
            index=33,
            seq=11,
            reward_item=_itemlist.i_26812_1_1,
            today_times=3,
            price_type=2,
            price=15000,
            value=80000
        },
        {
            type=34,
            section_start=8,
            section_end=14,
            start_time=1,
            end_time=5,
            phase=1,
            reward_item=_itemlist.i_25951_1_1,
            limit_type=1,
            buy_times=1,
            today_times=0,
            price_type=3,
            value=98
        },
        {
            type=35,
            section_start=8,
            section_end=14,
            index=1,
            start_time=1,
            end_time=5,
            phase=1,
            seq=1,
            reward_item=_itemlist.i_25505_1_1,
            price_type=3,
            price=60,
            value=18
        },
        {
            type=36,
            section_start=8,
            section_end=14,
            index=2,
            start_time=1,
            end_time=5,
            phase=1,
            seq=2,
            reward_item=_itemlist.i_26813_8_1,
            today_times=2,
            price_type=3,
            value=320
        },
        {
            type=37,
            section_start=8,
            section_end=14,
            index=3,
            start_time=1,
            end_time=5,
            phase=1,
            seq=3,
            reward_item=_itemlist.i_25505_20_1,
            today_times=10,
            price_type=3,
            price=500,
            value=160
        },
        {
            type=38,
            section_start=8,
            section_end=14,
            index=4,
            start_time=1,
            end_time=5,
            phase=1,
            seq=4,
            reward_item=_itemlist.i_27541_8_1,
            today_times=5,
            price_type=3,
            price=980,
            value=480
        },
        {
            type=39,
            section_start=8,
            section_end=14,
            index=5,
            start_time=1,
            end_time=5,
            phase=1,
            seq=5,
            reward_item=_itemlist.i_25506_3_1,
            today_times=3,
            price=1280,
            value=308
        },
        {
            type=40,
            section_start=8,
            section_end=14,
            index=6,
            start_time=1,
            end_time=5,
            phase=1,
            seq=6,
            reward_item=_itemlist.i_29021_150_1,
            limit_type=1,
            buy_times=1,
            today_times=0,
            price=3280,
            value=750
        },
        {
            type=41,
            section_start=8,
            section_end=14,
            index=7,
            start_time=1,
            end_time=5,
            phase=1,
            seq=7,
            reward_item=_itemlist.i_27187_40_1,
            price=6480
        },
        {
            type=42,
            section_start=8,
            section_end=14,
            index=8,
            start_time=1,
            end_time=5,
            phase=1,
            seq=8,
            reward_item=_itemlist.i_28067_1_1,
            today_times=5,
            price=375
        },
        {
            type=43,
            section_start=8,
            section_end=14,
            index=9,
            start_time=1,
            end_time=5,
            phase=1,
            seq=9,
            reward_item=_itemlist.i_25506_1_1,
            today_times=5,
            price_type=2,
            price=8000,
            value=15000
        },
        {
            type=44,
            section_start=8,
            section_end=14,
            index=10,
            start_time=1,
            end_time=5,
            phase=1,
            seq=10,
            reward_item=_itemlist.i_28070_1_1,
            today_times=5,
            price_type=2,
            price=30000,
            value=80000
        },
        {
            type=45,
            section_start=8,
            section_end=14,
            index=11,
            start_time=6,
            end_time=10,
            phase=2,
            reward_item=_itemlist.i_28078_1_1,
            price=3088,
            value=5888
        },
        {
            type=46,
            section_start=8,
            section_end=14,
            index=12,
            start_time=6,
            end_time=10,
            phase=2,
            seq=1,
            reward_item=_itemlist.i_25951_1_1,
            limit_type=1,
            buy_times=1,
            today_times=0,
            price_type=3,
            value=98
        },
        {
            type=47,
            section_start=8,
            section_end=14,
            index=13,
            start_time=6,
            end_time=10,
            phase=2,
            seq=2,
            reward_item=_itemlist.i_25950_1_1,
            limit_type=1,
            buy_times=1,
            today_times=0,
            price_type=3,
            price=1280,
            value=328
        },
        {
            type=48,
            section_start=8,
            section_end=14,
            index=14,
            start_time=6,
            end_time=10,
            phase=2,
            seq=3,
            reward_item=_itemlist.i_25505_1_1,
            price_type=3,
            price=60,
            value=18
        },
        {
            type=49,
            section_start=8,
            section_end=14,
            index=15,
            start_time=6,
            end_time=10,
            phase=2,
            seq=4,
            reward_item=_itemlist.i_29032_1_1,
            limit_type=1,
            buy_times=1,
            today_times=0,
            price_type=3,
            price=60,
            value=98
        },
        {
            type=50,
            section_start=8,
            section_end=14,
            index=16,
            start_time=6,
            end_time=10,
            phase=2,
            seq=5,
            reward_item=_itemlist.i_26813_8_1,
            today_times=2,
            price_type=3,
            value=320
        },
        {
            type=51,
            section_start=8,
            section_end=14,
            index=17,
            start_time=6,
            end_time=10,
            phase=2,
            seq=6,
            reward_item=_itemlist.i_25505_20_1,
            today_times=10,
            price=500,
            value=160
        },
        {
            type=52,
            section_start=8,
            section_end=14,
            index=18,
            start_time=6,
            end_time=10,
            phase=2,
            seq=7,
            reward_item=_itemlist.i_27541_8_1,
            today_times=5,
            price=980,
            value=480
        },
        {
            type=53,
            section_start=8,
            section_end=14,
            index=19,
            start_time=6,
            end_time=10,
            phase=2,
            seq=8,
            reward_item=_itemlist.i_25506_3_1,
            today_times=3,
            price=1280,
            value=308
        },
        {
            type=54,
            section_start=8,
            section_end=14,
            index=20,
            start_time=6,
            end_time=10,
            phase=2,
            seq=9,
            reward_item=_itemlist.i_27398_1_1,
            today_times=5,
            price_type=2,
            price=3000,
            value=10000
        },
        {
            type=55,
            section_start=8,
            section_end=14,
            index=21,
            start_time=6,
            end_time=10,
            phase=2,
            seq=10,
            reward_item=_itemlist.i_26812_1_1,
            today_times=3,
            price_type=2,
            price=15000,
            value=80000
        },
        {
            type=56,
            section_start=8,
            section_end=14,
            index=22,
            reward_item=_itemlist.i_29021_150_1,
            price_type=3,
            price=3280,
            value=750
        },
        {
            type=57,
            section_start=8,
            section_end=14,
            index=23,
            seq=1,
            reward_item=_itemlist.i_29021_180_1,
            limit_type=1,
            buy_times=1,
            today_times=0,
            price_type=3,
            price=3280,
            value=900
        },
        {
            type=58,
            section_start=8,
            section_end=14,
            index=24,
            seq=2,
            reward_item=_itemlist.i_27187_40_1,
            price_type=3,
            price=6480
        },
        {
            type=59,
            section_start=8,
            section_end=14,
            index=25,
            seq=3,
            reward_item=_itemlist.i_22007_100_1,
            today_times=30,
            price=3888,
            value=5888
        },
        {
            type=60,
            section_start=8,
            section_end=14,
            index=26,
            seq=4,
            reward_item=_itemlist.i_27575_10_1,
            today_times=30,
            price=198,
            value=388
        },
        {
            type=61,
            section_start=8,
            section_end=14,
            index=27,
            seq=5,
            reward_item=_itemlist.i_28067_1_1,
            today_times=10,
            price=375
        },
        {
            type=62,
            section_start=8,
            section_end=14,
            index=28,
            seq=6,
            reward_item=_itemlist.i_29038_5_1,
            today_times=30,
            price=388,
            value=500
        },
        {
            type=63,
            section_start=8,
            section_end=14,
            index=29,
            seq=7,
            reward_item=_itemlist.i_25506_1_1,
            today_times=30,
            price=880,
            value=1500
        },
        {
            type=64,
            section_start=8,
            section_end=14,
            index=30,
            seq=8,
            reward_item=_itemlist.i_28070_1_1,
            today_times=10,
            price=1150,
            value=2760
        },
        {
            type=65,
            section_start=8,
            section_end=14,
            index=31,
            seq=9,
            reward_item=_itemlist.i_28078_1_1,
            price=3088,
            value=5888
        },
        {
            type=66,
            section_start=8,
            section_end=14,
            index=32,
            seq=10,
            reward_item=_itemlist.i_27398_1_1,
            today_times=5,
            price_type=2,
            price=3000,
            value=10000
        },
        {
            type=67,
            section_start=8,
            section_end=14,
            index=33,
            seq=11,
            reward_item=_itemlist.i_26812_1_1,
            today_times=3,
            price_type=2,
            price=15000,
            value=80000
        },
        {
            type=68,
            section_start=15,
            section_end=0,
            start_time=1,
            end_time=5,
            phase=1,
            reward_item=_itemlist.i_25951_1_1,
            limit_type=1,
            buy_times=1,
            today_times=0,
            price_type=3,
            value=98
        },
        {
            type=69,
            section_start=15,
            section_end=0,
            index=1,
            start_time=1,
            end_time=5,
            phase=1,
            seq=1,
            reward_item=_itemlist.i_25505_1_1,
            price_type=3,
            price=60,
            value=18
        },
        {
            type=70,
            section_start=15,
            section_end=0,
            index=2,
            start_time=1,
            end_time=5,
            phase=1,
            seq=2,
            reward_item=_itemlist.i_26813_8_1,
            today_times=2,
            price_type=3,
            value=320
        },
        {
            type=71,
            section_start=15,
            section_end=0,
            index=3,
            start_time=1,
            end_time=5,
            phase=1,
            seq=3,
            reward_item=_itemlist.i_25505_20_1,
            today_times=10,
            price_type=3,
            price=500,
            value=160
        },
        {
            type=72,
            section_start=15,
            section_end=0,
            index=4,
            start_time=1,
            end_time=5,
            phase=1,
            seq=4,
            reward_item=_itemlist.i_27541_8_1,
            today_times=5,
            price_type=3,
            price=980,
            value=480
        },
        {
            type=73,
            section_start=15,
            section_end=0,
            index=5,
            start_time=1,
            end_time=5,
            phase=1,
            seq=5,
            reward_item=_itemlist.i_25506_3_1,
            today_times=3,
            price=1280,
            value=308
        },
        {
            type=74,
            section_start=15,
            section_end=0,
            index=6,
            start_time=1,
            end_time=5,
            phase=1,
            seq=6,
            reward_item=_itemlist.i_29021_150_1,
            limit_type=1,
            buy_times=1,
            today_times=0,
            price=3280,
            value=750
        },
        {
            type=75,
            section_start=15,
            section_end=0,
            index=7,
            start_time=1,
            end_time=5,
            phase=1,
            seq=7,
            reward_item=_itemlist.i_27187_40_1,
            price=6480
        },
        {
            type=76,
            section_start=15,
            section_end=0,
            index=8,
            start_time=1,
            end_time=5,
            phase=1,
            seq=8,
            reward_item=_itemlist.i_28067_1_1,
            today_times=5,
            price=375
        },
        {
            type=77,
            section_start=15,
            section_end=0,
            index=9,
            start_time=1,
            end_time=5,
            phase=1,
            seq=9,
            reward_item=_itemlist.i_25506_1_1,
            today_times=5,
            price_type=2,
            price=8000,
            value=15000
        },
        {
            type=78,
            section_start=15,
            section_end=0,
            index=10,
            start_time=1,
            end_time=5,
            phase=1,
            seq=10,
            reward_item=_itemlist.i_28070_1_1,
            today_times=5,
            price_type=2,
            price=30000,
            value=80000
        },
        {
            type=79,
            section_start=15,
            section_end=0,
            index=11,
            start_time=6,
            end_time=10,
            phase=2,
            reward_item=_itemlist.i_28078_1_1,
            price=3088,
            value=5888
        },
        {
            type=80,
            section_start=15,
            section_end=0,
            index=12,
            start_time=6,
            end_time=10,
            phase=2,
            seq=1,
            reward_item=_itemlist.i_25951_1_1,
            limit_type=1,
            buy_times=1,
            today_times=0,
            price_type=3,
            value=98
        },
        {
            type=81,
            section_start=15,
            section_end=0,
            index=13,
            start_time=6,
            end_time=10,
            phase=2,
            seq=2,
            reward_item=_itemlist.i_25950_1_1,
            limit_type=1,
            buy_times=1,
            today_times=0,
            price_type=3,
            price=1280,
            value=328
        },
        {
            type=82,
            section_start=15,
            section_end=0,
            index=14,
            start_time=6,
            end_time=10,
            phase=2,
            seq=3,
            reward_item=_itemlist.i_25505_1_1,
            price_type=3,
            price=60,
            value=18
        },
        {
            type=83,
            section_start=15,
            section_end=0,
            index=15,
            start_time=6,
            end_time=10,
            phase=2,
            seq=4,
            reward_item=_itemlist.i_29032_1_1,
            limit_type=1,
            buy_times=1,
            today_times=0,
            price_type=3,
            price=60,
            value=98
        },
        {
            type=84,
            section_start=15,
            section_end=0,
            index=16,
            start_time=6,
            end_time=10,
            phase=2,
            seq=5,
            reward_item=_itemlist.i_26813_8_1,
            today_times=2,
            price_type=3,
            value=320
        },
        {
            type=85,
            section_start=15,
            section_end=0,
            index=17,
            start_time=6,
            end_time=10,
            phase=2,
            seq=6,
            reward_item=_itemlist.i_25505_20_1,
            today_times=10,
            price=500,
            value=160
        },
        {
            type=86,
            section_start=15,
            section_end=0,
            index=18,
            start_time=6,
            end_time=10,
            phase=2,
            seq=7,
            reward_item=_itemlist.i_27541_8_1,
            today_times=5,
            price=980,
            value=480
        },
        {
            type=87,
            section_start=15,
            section_end=0,
            index=19,
            start_time=6,
            end_time=10,
            phase=2,
            seq=8,
            reward_item=_itemlist.i_25506_3_1,
            today_times=3,
            price=1280,
            value=308
        },
        {
            type=88,
            section_start=15,
            section_end=0,
            index=20,
            start_time=6,
            end_time=10,
            phase=2,
            seq=9,
            reward_item=_itemlist.i_27398_1_1,
            today_times=5,
            price_type=2,
            price=3000,
            value=10000
        },
        {
            type=89,
            section_start=15,
            section_end=0,
            index=21,
            start_time=6,
            end_time=10,
            phase=2,
            seq=10,
            reward_item=_itemlist.i_26812_1_1,
            today_times=3,
            price_type=2,
            price=15000,
            value=80000
        },
        {
            type=90,
            section_start=15,
            section_end=0,
            index=22,
            reward_item=_itemlist.i_29021_150_1,
            price_type=3,
            price=3280,
            value=750
        },
        {
            type=91,
            section_start=15,
            section_end=0,
            index=23,
            seq=1,
            reward_item=_itemlist.i_29021_180_1,
            limit_type=1,
            buy_times=1,
            today_times=0,
            price_type=3,
            price=3280,
            value=900
        },
        {
            type=92,
            section_start=15,
            section_end=0,
            index=24,
            seq=2,
            reward_item=_itemlist.i_27187_40_1,
            price_type=3,
            price=6480
        },
        {
            type=93,
            section_start=15,
            section_end=0,
            index=25,
            seq=3,
            reward_item=_itemlist.i_22007_100_1,
            today_times=30,
            price=3888,
            value=5888
        },
        {
            type=94,
            section_start=15,
            section_end=0,
            index=26,
            seq=4,
            reward_item=_itemlist.i_27575_10_1,
            today_times=30,
            price=198,
            value=388
        },
        {
            type=95,
            section_start=15,
            section_end=0,
            index=27,
            seq=5,
            reward_item=_itemlist.i_28067_1_1,
            today_times=10,
            price=375
        },
        {
            type=96,
            section_start=15,
            section_end=0,
            index=28,
            seq=6,
            reward_item=_itemlist.i_29038_5_1,
            today_times=30,
            price=388,
            value=500
        },
        {
            type=97,
            section_start=15,
            section_end=0,
            index=29,
            seq=7,
            reward_item=_itemlist.i_25506_1_1,
            today_times=30,
            price=880,
            value=1500
        },
        {
            type=98,
            section_start=15,
            section_end=0,
            index=30,
            seq=8,
            reward_item=_itemlist.i_28070_1_1,
            today_times=10,
            price=1150,
            value=2760
        },
        {
            type=99,
            section_start=15,
            section_end=0,
            index=31,
            seq=9,
            reward_item=_itemlist.i_28078_1_1,
            price=3088,
            value=5888
        },
        {
            type=100,
            section_start=15,
            section_end=0,
            index=32,
            seq=10,
            reward_item=_itemlist.i_27398_1_1,
            today_times=5,
            price_type=2,
            price=3000,
            value=10000
        },
        {
            type=101,
            section_start=15,
            section_end=0,
            index=33,
            seq=11,
            reward_item=_itemlist.i_26812_1_1,
            today_times=3,
            price_type=2,
            price=15000,
            value=80000
        }
    },
    store_name={
        {
            index=1,
            store_name="烈阳商城",
            store_icon_name="store_1"
        },
        {
            index=2,
            store_name="沁凉商城",
            store_icon_name="store_2"
        },
        {
            index=3,
            store_name="清甜商城",
            store_icon_name="store_3"
        }
    },
    qionglou_banquet={
        {
            type=0
        },
        {
            type=1,
            seq=1,
            prep_down=450,
            prep_up=899,
            banquet_type=1,
            reward_group=2
        },
        {
            type=2,
            seq=2,
            prep_down=900,
            prep_up=1799,
            banquet_type=2,
            reward_group=3
        },
        {
            type=3,
            seq=3,
            prep_down=1800,
            prep_up=0,
            banquet_type=3,
            reward_group=4,
            sp_reward_group=5
        },
        {
            type=4,
            section_start=8,
            section_end=14
        },
        {
            type=5,
            section_start=8,
            section_end=14,
            seq=1,
            prep_down=450,
            prep_up=899,
            banquet_type=1,
            reward_group=2
        },
        {
            type=6,
            section_start=8,
            section_end=14,
            seq=2,
            prep_down=900,
            prep_up=1799,
            banquet_type=2,
            reward_group=3
        },
        {
            type=7,
            section_start=8,
            section_end=14,
            seq=3,
            prep_down=1800,
            prep_up=0,
            banquet_type=3,
            reward_group=4,
            sp_reward_group=5
        },
        {
            type=8,
            section_start=15,
            section_end=0
        },
        {
            type=9,
            section_start=15,
            section_end=0,
            seq=1,
            prep_down=450,
            prep_up=899,
            banquet_type=1,
            reward_group=2
        },
        {
            type=10,
            section_start=15,
            section_end=0,
            seq=2,
            prep_down=900,
            prep_up=1799,
            banquet_type=2,
            reward_group=3
        },
        {
            type=11,
            section_start=15,
            section_end=0,
            seq=3,
            prep_down=1800,
            prep_up=0,
            banquet_type=3,
            reward_group=4,
            sp_reward_group=5
        }
    },
    banquet_group={
        {
            reward_item={
                [0]=_itemlist.i_26812_1_1
            }
        },
        {
            reward_item={
                [0]=_itemlist.i_26393_1_1
            }
        },
        {
            reward_item={
                [0]=_itemlist.i_27188_1_1
            }
        },
        {
            reward_group=2,
            reward_item={
                [0]=_itemlist.i_27398_2_1
            }
        },
        {
            reward_group=2,
            reward_item={
                [0]=_itemlist.i_27478_5_1
            }
        },
        {
            reward_group=2,
            reward_item={
                [0]=_itemlist.i_24326_2_1
            }
        },
        {
            reward_group=3,
            reward_item={
                [0]=_itemlist.i_27187_1_1
            }
        },
        {
            reward_group=3,
            reward_item={
                [0]=_itemlist.i_26812_3_1
            }
        },
        {
            reward_group=3,
            reward_item={
                [0]=_itemlist.i_27478_8_1
            }
        },
        {
            reward_group=4,
            reward_item={
                [0]=_itemlist.i_22006_3_1
            }
        },
        {
            reward_group=4,
            reward_item={
                [0]=_itemlist.i_22006_2_1
            }
        },
        {
            reward_group=4,
            reward_item={
                [0]=_itemlist.i_22006_1_1
            }
        },
        {
            reward_group=5,
            reward_item={
                [0]=_itemlist.i_26813_1_1
            }
        },
        {
            reward_group=5,
            reward_item={
                [0]=_itemlist.i_24326_3_1
            }
        },
        {
            reward_group=5,
            reward_item={
                [0]=_itemlist.i_27398_3_1
            }
        },
        {
            reward_group=6,
            reward_item={
                [0]=_itemlist.i_26812_1_1
            }
        },
        {
            reward_group=6,
            reward_item={
                [0]=_itemlist.i_24326_1_1
            }
        },
        {
            reward_group=6,
            reward_item={
                [0]=_itemlist.i_22006_1_1
            }
        }
    },
    lucky_sign={
        {
            type=0,
            reward_group_id=1
        },
        {
            type=1,
            seq=1,
            sign_group_id=2,
            reward_group_id=2
        },
        {
            type=2,
            seq=2,
            sign_group_id=3,
            reward_group_id=3
        },
        {
            type=3,
            section_start=8,
            section_end=21,
            reward_group_id=4
        },
        {
            type=4,
            section_start=8,
            section_end=21,
            seq=1,
            sign_group_id=2,
            reward_group_id=5
        },
        {
            type=5,
            section_start=8,
            section_end=21,
            seq=2,
            sign_group_id=3,
            reward_group_id=6
        },
        {
            type=6,
            section_start=22,
            section_end=0,
            reward_group_id=7
        },
        {
            type=7,
            section_start=22,
            section_end=0,
            seq=1,
            sign_group_id=2,
            reward_group_id=8
        },
        {
            type=8,
            section_start=22,
            section_end=0,
            seq=2,
            sign_group_id=3,
            reward_group_id=9
        }
    },
    huaqian_group={
        [0]={
            type=0,
            reward_group_id=1,
            reward_item={
                [0]=_itemlist.i_26327_1_1,
                [1]=_itemlist.i_29017_1_1
            }
        },
        [1]={
            type=1,
            reward_group_id=2,
            reward_item={
                [0]=_itemlist.i_26327_1_1,
                [1]=_itemlist.i_26812_1_1
            }
        },
        [2]={
            type=2,
            reward_group_id=3,
            reward_item={
                [0]=_itemlist.i_26327_1_1,
                [1]=_itemlist.i_28555_1_1
            }
        },
        [3]={
            type=3,
            reward_group_id=4,
            reward_item={
                [0]=_itemlist.i_26327_1_1,
                [1]=_itemlist.i_29017_1_1
            }
        },
        [4]={
            type=4,
            reward_group_id=5,
            reward_item={
                [0]=_itemlist.i_26327_1_1,
                [1]=_itemlist.i_27655_1_1
            }
        },
        [5]={
            type=5,
            reward_group_id=6,
            reward_item={
                [0]=_itemlist.i_26327_1_1,
                [1]=_itemlist.i_28522_1_1
            }
        },
        [6]={
            type=6,
            reward_group_id=7,
            reward_item={
                [0]=_itemlist.i_26327_1_1,
                [1]=_itemlist.i_29017_1_1
            }
        },
        [7]={
            type=7,
            reward_group_id=8,
            reward_item={
                [0]=_itemlist.i_26327_1_1,
                [1]=_itemlist.i_27655_1_1
            }
        },
        [8]={
            type=8,
            reward_group_id=9,
            reward_item={
                [0]=_itemlist.i_26327_1_1,
                [1]=_itemlist.i_29076_1_1
            }
        }
    },
    sign_group_id={
        [1]={
            sign_id=1,
            sign="开天辟地作良缘，吉日良时万物全。若得此签非小可，人行忠正帝王宣。",
            sign_solution="此卦盘古初开天地之象，诸事皆吉也。\n急速兆速，年未值时，观音降笔，先报君知。"
        },
        [2]={
            sign_id=2,
            sign="千年古镜复重圆，女再求夫男再婚。自此门庭重改换，更添福禄在儿孙。",
            sign_solution="此卦串镜重圆之象，凡事劳心有贵也。\n淘沙成金，骑龙踏虎，虽是劳心，于中有补。"
        },
        [3]={
            sign_id=3,
            sign="茂林松柏正兴旺，雨雪风霜总莫为。异日忽然成大用，功名成就栋梁材。",
            sign_solution="此卦此卦松柏茂林之象，凡事有贵气也。\n路上亨通。终身有功。田蚕丰熟。家道兴隆。"
        },
        [4]={
            sign_id=4,
            sign="烦君勿作私心事，此意偏宜说问公。一片明心光皎洁，宛如皎月正天中。",
            sign_solution="此卦皎月当空之象，凡事光明通气也。\n心中正直，理顺法宽，圣无私语，终有分明。"
        },
        [5]={
            sign_id=5,
            sign="欲求胜事可非常，争奈亲姻日暂忙。到头竟必成中箭，贵人指引贵人乡。",
            sign_solution="此卦因祸得福之象，凡事营谋吉利也。\n有意兴变，到底安然，若问用事，只近贵人。"
        },
        [6]={
            sign_id=6,
            sign="否去泰来咫尺间，暂交君子出于山。若逢虎兔佳音信，立志忙中事即闲。",
            sign_solution="此卦祸中有福之象，凡事先凶后吉也。\n换麻得丝，击人双足，要见分明，因灾得福。"
        },
        [7]={
            sign_id=7,
            sign="金乌西坠兔东升，日夜循环至古今。僧道得知无不利，士农工商各从心。",
            sign_solution="此卦阴阳消长之象，凡事遂意之兆也。\n心中无事，所作有功，如弓上箭，一发当空。"
        },
        [8]={
            sign_id=8,
            sign="阴阳道合总由天，女嫁男婚喜偎然。但见龙蛇相会合，熊罴入梦乐团圆。",
            sign_solution="此卦阴阳道合之象，凡事和大吉也。\n谋望从心，婚姻孕男，资财进益，更利田蚕。"
        },
        [9]={
            sign_id=9,
            sign="行藏出入礼义恭，言必忠良信必从。心不了然且静澈，光明红日正当中。",
            sign_solution="此卦红日当空正照之象，凡事遂意也。\n心中无事，秋水澄清，不须疑惑，事自然成。"
        },
        [10]={
            sign_id=10,
            sign="君皇圣后终为恩，复待祈禳无损增。一切有情皆受用，人间天上得期亨。",
            sign_solution="此卦天垂恩泽之象，凡事成就大吉也。\n天皇降恩，始终莫忘，晨昏礼念，可宜烧香。"
        },
        [11]={
            sign_id=11,
            sign="天地变通万物全，自营自养自安然。生罗万象皆精彩，事事如心谢圣贤。",
            sign_solution="此卦大地交泰之象，凡事大吉无危也。\n天生万物，谋望皆通，福德相助，瑞气匆匆。"
        },
        [12]={
            sign_id=12,
            sign="温柔自古胜刚强，积善之门大吉昌。若是有人占此卦，宛如正渴遇瑶浆。",
            sign_solution="此卦积善温柔之象，凡事贵人和合也。\n天地有感，应验非常，佛神护佑，得之莫忘。"
        },
        [13]={
            sign_id=13,
            sign="锦上添花色愈鲜，运来禄马喜双全。时人莫恨功名晚，一举登科四海传。",
            sign_solution="此卦锦上添花之象，凡事大吉大利也。\n守旧变新，运至材成，遂平生志，尽皆是命。"
        },
        [14]={
            sign_id=14,
            sign="夏日炎天日最长，人人愁热闷非常。天地也解知人意，薰风拂拂自然凉。",
            sign_solution="此卦人人愁热之象，凡事随心从意也。\n进退莫疑，自有佳期，营谋用么，不须妄为。"
        },
        [15]={
            sign_id=15,
            sign="父贤传子子传孙，衣食丰隆只靠天。堂上椿萱人快乐，饥饭渴饮困时眠。",
            sign_solution="此卦接竹引泉之象，凡事谋望大吉也。\n接竹引泉，流传不绝，君子谋望，无不欣悦。"
        },
        [16]={
            sign_id=16,
            sign="一条金线秤君心，无减无增无重轻。为人平生心正直，文章全贝艺光明。",
            sign_solution="此卦心平正直之象，凡事平稳无凶也。\n心平正直，到底清平，只依本份，天下太平。"
        },
        [17]={
            sign_id=17,
            sign="门廷吉庆喜非常，积善之门大吉昌。婚姻田蚕诸事遂，病逢妙药即安康。",
            sign_solution="此卦春梦百花之象，凡事遇贵人大吉也。\n春深日暖，百花自开，事莫迟疑，从人显达。"
        },
        [18]={
            sign_id=18,
            sign="春来雷震百虫鸣，番身一转离泥中。始知出入还来往，一朝变化便成龙。",
            sign_solution="此卦雷发百虫之象，凡事遇贵人吉兆也。\n雷发时转，出入两存，一朝变化，直到天门。"
        },
        [19]={
            sign_id=19,
            sign="冷水未烧白沸汤，不寒不热有温凉。要行天下无他事，为有身中百艺强。",
            sign_solution="此卦平善用事之象，凡事平稳大吉也。\n囚人逢赦，病遇良医，求财谋望，贵人指示。"
        },
        [20]={
            sign_id=20,
            sign="直上仙岩要学仙，此知一旦帝王宣。青天日月常明照，心正声名四海传。",
            sign_solution="此卦贵人接引之象，凡事和合大吉也。\n有始有终，莫向西东，心中用事，贵人重重。"
        },
        [21]={
            sign_id=21,
            sign_group_id=2,
            sign="鲸鱼未变守江河，不可升腾更望高。异日峥嵘身变化，许君一跃跳龙门。",
            sign_solution="此卦鲸鱼未变之象，凡事忍耐待时也。\n得忍且忍，得耐且耐，须待时至，功名还在。",
            luck="中吉"
        },
        [22]={
            sign_id=22,
            sign_group_id=2,
            sign="一锥草地要求泉，努力求之得最难。无意俄然遇知己，相逢携手上青天。",
            sign_solution="此卦锥地求泉之象，凡事先难后易也。\n欲望心事，西方可求，不如莫动，立地可谋。",
            luck="中吉"
        },
        [23]={
            sign_id=23,
            sign_group_id=2,
            sign="投身岩下雕鸟居，须是还他大丈夫。及早营谋谁可得，通行天地此人无。",
            sign_solution="此卦投岩铜鸟之象，凡事宜顺吉之兆。\n食用无鱼，身清喜贫，待时利乐，权与概人。",
            luck="中吉"
        },
        [24]={
            sign_id=24,
            sign_group_id=2,
            sign="石藏无价玉和珍，只管他乡外客寻。宛如持灯更觅火，不如收拾枉劳心。",
            sign_solution="此卦持灯觅火之象，凡事待时成就也。\n姻缘会遇，何事不成，须无限意，眼前是真。",
            luck="中吉"
        },
        [25]={
            sign_id=25,
            sign_group_id=2,
            sign="自小生在富贵家，眼前万物总奢华。蒙君赐紫金腰带，四海声名定可夸。",
            sign_solution="此卦龙门得通之象，凡事有变大吉也。\n囚人逢赦，病即安然，龙门得遇，名遍名都。",
            luck="中吉"
        },
        [26]={
            sign_id=26,
            sign_group_id=2,
            sign="宛如仙鹤出凡笼，脱得凡笼路路通。南北东西无阻隔，任君直上九霄宫。",
            sign_solution="此卦仙鹤离笼之象，凡事先凶后吉也。\n任意无虞，路有亨通，随心自在，逍遥如人(神)。",
            luck="中吉"
        },
        [27]={
            sign_id=27,
            sign_group_id=2,
            sign="行人绊曰气难吞，忽有灾事勿近前。巢破林鸟无所宿，可寻深处稳安身。",
            sign_solution="此卦鸟鹊巢(离)林之象，凡事到底应心也。\n若人得怨。何时可伸，好言不信，守旧待时。",
            luck="中吉"
        },
        [28]={
            sign_id=28,
            sign_group_id=2,
            sign="愁眉思虑暂时开，启出云霄喜自来。宛如粪土中藏玉，良工荐举出尘埃。",
            sign_solution="此卦阴阳和合之象，凡所谋皆吉也。\n得处无失，损中有益，小人逢凶，君子顺吉。",
            luck="中吉"
        },
        [29]={
            sign_id=29,
            sign_group_id=2,
            sign="急水滩头放船归，风波作波欲何为。若要安然求稳静，等待浪静过此危。",
            sign_solution="此卦船行急滩之象，凡事守旧待时也。\n急水下船，险处待时，若问营谋，尽(不)可施为。",
            luck="中吉"
        },
        [30]={
            sign_id=30,
            sign_group_id=2,
            sign="当春久雨喜开晴，玉兔金乌渐渐明。旧事消散新事遂，看看一跳遇龙门。",
            sign_solution="此卦久雨初明之象，凡事遂意也。\n神佛护持，有灾无危，途生平安，到底荣归。",
            luck="中吉"
        },
        [31]={
            sign_id=31,
            sign_group_id=2,
            sign="旱时田里皆枯槁，谢天甘雨落淋淋。花果草木皆润泽，始知一雨值千金。",
            sign_solution="此卦旱逢甘雨之象，凡事难中有救也。\n田蚕倍熟，命运渐来，病遇良药，行人不便。",
            luck="中吉"
        },
        [32]={
            sign_id=32,
            sign_group_id=2,
            sign="欲扳仙桂入蟾宫，普开天门不任君。忽遇一般音信好，人人皆笑岭顶花。",
            sign_solution="此卦手扳仙桂之象，凡事必有贵人也。\n商贾利益，行戴有(无)危，病安讼遂，尽可施为。",
            luck="中吉"
        },
        [33]={
            sign_id=33,
            sign_group_id=2,
            sign="过了忧危事几重，从今再立永无空。宽心自有宽心计，得遇高人立大功。",
            sign_solution="此卦古井逢泉之象，凡事贵人成就也。\n讼终有理，病得安全，出入求谋，古井逢泉。",
            luck="中吉"
        },
        [34]={
            sign_id=34,
            sign_group_id=2,
            sign="一谋一用一番书，虑后思前不敢为。时到贵人相助力，如山墙立可安居。",
            sign_solution="此卦屋好墙壁之象，凡事稳当无险也。\n改旧成新，寒花遇春，从前阻滞，今得称心。",
            luck="中吉"
        },
        [35]={
            sign_id=35,
            sign_group_id=2,
            sign="东边月上正蝉娟，顷刻云遮亦暗存。或有圆时还有缺，更言非者亦闲言。",
            sign_solution="此卦月被云遮之象，凡事昏迷未定也。\n浮云遮月，不须疑惑，等待云收，便见明白。",
            luck="中吉"
        },
        [36]={
            sign_id=36,
            sign_group_id=2,
            sign="宝剑出匣耀光明，在匣全然不惹尘。今得贵人携出现，有威有势众人钦。",
            sign_solution="此卦宝剑出匣之象，凡事有威有势也。\n宝剑出匣，光辉万里，贵人指引，无不观美。",
            luck="中吉"
        },
        [37]={
            sign_id=37,
            sign_group_id=2,
            sign="劝君切莫向他求，似鹤飞来暗箭投。若去采薪蛇在草，恐遭毒口也忧愁。",
            sign_solution="此卦安份守己之象，凡事小心谨防也。\n闭口含齿，他事莫理，若有亏心，到头害己。",
            luck="中吉"
        },
        [38]={
            sign_id=38,
            sign_group_id=2,
            sign="清闲无忧静处侩，饱后吃茶时坐卧。汝下身心不用忙，必定不招冤与祸。",
            sign_solution="此卦守旧安然之象，凡事时待时则吉也。\n守旧安然，叩问神仙，直待时来，事亦偶然。",
            luck="中吉"
        },
        [39]={
            sign_id=39,
            sign_group_id=2,
            sign="归程杳杳定无疑，石中藏玉有谁知。一朝良匠分明剖，始觉安然碧玉期。",
            sign_solution="此卦剖石见玉之象，凡事着力成功也。\n宝在石中，异人少知，直待分明，尽可施为。",
            luck="中吉"
        },
        [40]={
            sign_id=40,
            sign_group_id=2,
            sign="内藏无价宝和珍，得玉何须外界寻。不如等待高人识，宽心犹且更宽心。",
            sign_solution="此卦藏玉外寻之象，凡事待时可也。\n内藏金玉，不识外寻，遇贵指引，不须劳心。",
            luck="中吉"
        },
        [41]={
            sign_id=41,
            sign_group_id=3,
            sign="临风冒雨去还乡，正是其身似燕儿。衔得坭来欲作垒，到头垒坏复须坭。",
            sign_solution="此卦燕子衔坭之象，凡事劳心费力也。\n千般用计，晨昏不停，谁知此事，到底劳心。",
            luck="小吉"
        },
        [42]={
            sign_id=42,
            sign_group_id=3,
            sign="奔波阻隔重重险，带水拖坭去度山。更望他乡求用事，千乡万里未回还。",
            sign_solution="此卦拖坭带水之象，凡事守旧则吉也。\n退身可得，进步为难，只宜守旧，莫望高扳。",
            luck="小吉"
        },
        [43]={
            sign_id=43,
            sign_group_id=3,
            sign="莫听闲言说是非，晨昏只好念阿弥。若将狂话为真实，书饼如何止得饥。",
            sign_solution="此卦书饼充饥之象，诸事多虚少实也。\n心中不定，枉看经文，恰似书饼，食也难吞。",
            luck="小吉"
        },
        [44]={
            sign_id=44,
            sign_group_id=3,
            sign="不成理论不成家，水性痴人似落花。若问君恩须得力，到头方见事如麻。",
            sign_solution="此卦痴人道塞之象，凡事守旧待时也。\n是非莫说，必须仔细，心正理直，方免灾危。",
            luck="小吉"
        },
        [45]={
            sign_id=45,
            sign_group_id=3,
            sign="上下传来事转虚，天边接得一封书。书中许我功名遂，直到终时亦是虚。",
            sign_solution="此卦虚名之象，凡事虚多少实宜守旧也。\n上下心烦，求闲不闲，欲望功名，守旧身安。",
            luck="小吉"
        },
        [46]={
            sign_id=46,
            sign_group_id=3,
            sign="月照天宅静处期，忽遭云雾又昏迷。宽心祈信云霞散，此时更改好施为。",
            sign_solution="此卦云雾遮月之象，凡事未遂守旧也。\n家道忧凶，人口有灾，祈福保庆，犹恐破财。",
            luck="小吉"
        },
        [47]={
            sign_id=47,
            sign_group_id=3,
            sign="天边消息实难思，切莫多心望强求。若把石头磨作镜，曾知枉费己功夫。",
            sign_solution="此卦守常安静之象，凡事守己则吉也。\n千般用计，枉费功夫，不如守旧，着甚来由。",
            luck="小吉"
        },
        [48]={
            sign_id=48,
            sign_group_id=3,
            sign="水中捉月费功夫，费尽功夫却又无。莫说闲言并乱语，枉劳心力强身枯。",
            sign_solution="此卦贪求费力之象，凡事劳心费力也。\n言诺难思，费力劳心，宅中忧虑，等遇贵人。",
            luck="小吉"
        },
        [49]={
            sign_id=49,
            sign_group_id=3,
            sign="梦中得宝醒来无，自谓南山只是锄。若问婚姻并问病，别寻来路为相扶。",
            sign_solution="此卦梦中得宝之象，凡事枉费心力也。\n物在水中，形影长短，皆有分定，不用商量。",
            luck="小吉"
        },
        [50]={
            sign_id=50,
            sign_group_id=3,
            sign="直上重楼去藏身，四围荆棘绕为林。天高君命长和短，得一番成失二人。",
            sign_solution="此卦守旧随时之象，凡事待时则吉。\n如醉饮酒，只宜守旧，直待时来，无灾无咎。",
            luck="小吉"
        },
        [51]={
            sign_id=51,
            sign_group_id=3,
            sign="抱薪救火大皆燃，烧遍三千亦复然。若问荣华并出入，不如收拾枉劳心。",
            sign_solution="此卦抱薪救火之象，凡事亦自谨防也。\n有千般计，一旦相惹，不如莫动，恐惹祸身。",
            luck="小吉"
        },
        [52]={
            sign_id=52,
            sign_group_id=3,
            sign="游鱼却在碧波池，撞遭罗网四边围。思量无计番身出，事到头来惹事非。",
            sign_solution="此卦鱼遭罗网之象，凡事亦宜提防也。\n屋下安身，祸从天降，早觉先防，免遭灾殃。",
            luck="小吉"
        },
        [53]={
            sign_id=53,
            sign_group_id=3,
            sign="眼前欢喜未为欢，亦不危时亦不安。割肉补疮为甚事，不如守旧待时光。",
            sign_solution="此卦割肉成疮之象，凡事只宜守旧待时。\n知止则止，知宽自宽，割自身肉，疾痛一般。",
            luck="小吉"
        },
        [54]={
            sign_id=54,
            sign_group_id=3,
            sign="路险马嬴人行急，失群军卒困相当。滩高风浪船桌破，日暮花残天降霜。",
            sign_solution="此卦船破下滩之象，凡事险阻提防也。\n守旧守旧，安静无咎，不用求谋，自在优游。",
            luck="小吉"
        },
        [55]={
            sign_id=55,
            sign_group_id=3,
            sign="朝朝恰似采花蜂，飞出西南又走东。春尽花残无觅处，此心不变旧行踪。",
            sign_solution="此卦蜜蜂采花之象，凡事劳心费力也。\n无觅春色，久雨不晴，求谋动用，不如安静。",
            luck="小吉"
        },
        [56]={
            sign_id=56,
            sign_group_id=3,
            sign="似鹄飞来自入笼，欲得番身却不通。南北东西都难出，此卦诚恐恨无穹。",
            sign_solution="此卦似鹄投水(笼)之象，凡事多虚少实也。\n进身可(不)得，退步为(不)能，低头直去，悉在其中。",
            luck="小吉"
        },
        [57]={
            sign_id=57,
            sign_group_id=3,
            sign="因名丧德如何事，切恐吉中变化凶。酒醉不知何处去，青松影里梦朦胧。",
            sign_solution="此卦寒鱼离水之象，凡事不可移动也。\n寒鱼离水，美中不足，若问营谋，不如莫起。",
            luck="小吉"
        },
        [58]={
            sign_id=58,
            sign_group_id=3,
            sign="君子莫体小人为，事若差池惹是非。琴鸣须用知音听，守常安静得依稀。",
            sign_solution="此卦要逢知己之象，凡事守常则吉也。\n知音方许，闲事莫理，待得贵人，无不欢喜。",
            luck="小吉"
        },
        [59]={
            sign_id=59,
            sign_group_id=3,
            sign="出入求谋事宜迟，急恐忧愁惹是非。如鸟飞入罗网内，脱困能有几多时。",
            sign_solution="此卦守旧随缘之象，凡事不如意主凶也。\n守旧随时，待贵人至，若问诸般，主事定迟。",
            luck="小吉"
        },
        [60]={
            sign_id=60,
            sign_group_id=3,
            sign="勒马持鞭直过来，半有忧危半有灾。恰似遭火焚烧屋，天降时雨荡成灰。",
            sign_solution="此卦半忧半喜之象，凡事只宜行善也。\n终身劳力，莫管是非，枷锁临时，怨尤自至。",
            luck="小吉"
        }
    }
}
SetConfigDefaultVal(Config.burning_summer_auto,_default_val,nil,nil,nil)