local _default_val={
    basis_configuration={
        section_start=1,
        section_end=21,
        seq=0,
        light_group=1
    },
    reward_configuration={
        seq=0,
        group=1
    }
}
local _itemlist={
    i_26692_1_1={
        item_id=26692,
        num=1,
        is_bind=1
    },
    i_23908_1_1={
        item_id=23908,
        num=1,
        is_bind=1
    },
    i_24811_1_1={
        item_id=24811,
        num=1,
        is_bind=1
    },
    i_25994_1_1={
        item_id=25994,
        num=1,
        is_bind=1
    },
    i_28915_1_1={
        item_id=28915,
        num=1,
        is_bind=1
    },
    i_25542_1_1={
        item_id=25542,
        num=1,
        is_bind=1
    },
    i_27838_1_1={
        item_id=27838,
        num=1,
        is_bind=1
    },
    i_29017_1_1={
        item_id=29017,
        num=1,
        is_bind=1
    },
    i_22013_1_1={
        item_id=22013,
        num=1,
        is_bind=1
    },
    i_28667_1_1={
        item_id=28667,
        num=1,
        is_bind=1
    },
    i_29017_2_1={
        item_id=29017,
        num=2,
        is_bind=1
    },
    i_31373_1_1={
        item_id=31373,
        num=1,
        is_bind=1
    },
    i_26692__={
        item_id=26692,
        num=null,
        is_bind=null
    }
}
Config.canglongcifu_auto={
    basis_configuration={
        {
            type=0,
            light_item=_itemlist.i_26692_1_1
        },
        {
            type=1,
            seq=1,
            light_item=_itemlist.i_26692_1_1
        },
        {
            type=2,
            seq=2,
            light_item=_itemlist.i_26692_1_1
        },
        {
            type=3,
            seq=3,
            light_item=_itemlist.i_26692_1_1
        },
        {
            type=4,
            seq=4,
            light_item=_itemlist.i_26692_1_1
        },
        {
            type=5,
            seq=5,
            light_item=_itemlist.i_26692_1_1
        },
        {
            type=6,
            seq=6,
            light_item=_itemlist.i_26692_1_1
        },
        {
            type=7,
            seq=7,
            light_item=_itemlist.i_26692_1_1
        },
        {
            type=8,
            seq=8,
            light_item=_itemlist.i_26692_1_1
        },
        {
            type=9,
            seq=9,
            light_item=_itemlist.i_26692_1_1
        },
        {
            type=10,
            seq=10,
            light_item=_itemlist.i_26692_1_1
        },
        {
            type=11,
            seq=11,
            light_item=_itemlist.i_26692_1_1
        },
        {
            type=12,
            seq=12,
            light_item=_itemlist.i_26692_1_1
        },
        {
            type=13,
            seq=13,
            light_item=_itemlist.i_26692_1_1
        },
        {
            type=14,
            seq=14,
            light_item=_itemlist.i_26692_1_1
        },
        {
            type=15,
            seq=15,
            light_item=_itemlist.i_26692_1_1
        },
        {
            type=16,
            seq=16,
            light_item=_itemlist.i_26692_1_1
        },
        {
            type=17,
            seq=17,
            light_item=_itemlist.i_26692_1_1
        },
        {
            type=18,
            seq=18,
            light_item=_itemlist.i_26692_1_1
        },
        {
            type=19,
            seq=19,
            light_item=_itemlist.i_26692_1_1
        },
        {
            type=20,
            section_start=22,
            section_end=0,
            light_item=_itemlist.i_26692_1_1,
            light_group=2
        },
        {
            type=21,
            section_start=22,
            section_end=0,
            seq=1,
            light_item=_itemlist.i_26692_1_1,
            light_group=2
        },
        {
            type=22,
            section_start=22,
            section_end=0,
            seq=2,
            light_item=_itemlist.i_26692_1_1,
            light_group=2
        },
        {
            type=23,
            section_start=22,
            section_end=0,
            seq=3,
            light_item=_itemlist.i_26692_1_1,
            light_group=2
        },
        {
            type=24,
            section_start=22,
            section_end=0,
            seq=4,
            light_item=_itemlist.i_26692_1_1,
            light_group=2
        },
        {
            type=25,
            section_start=22,
            section_end=0,
            seq=5,
            light_item=_itemlist.i_26692_1_1,
            light_group=2
        },
        {
            type=26,
            section_start=22,
            section_end=0,
            seq=6,
            light_item=_itemlist.i_26692_1_1,
            light_group=2
        },
        {
            type=27,
            section_start=22,
            section_end=0,
            seq=7,
            light_item=_itemlist.i_26692_1_1,
            light_group=2
        },
        {
            type=28,
            section_start=22,
            section_end=0,
            seq=8,
            light_item=_itemlist.i_26692_1_1,
            light_group=2
        },
        {
            type=29,
            section_start=22,
            section_end=0,
            seq=9,
            light_item=_itemlist.i_26692_1_1,
            light_group=2
        },
        {
            type=30,
            section_start=22,
            section_end=0,
            seq=10,
            light_item=_itemlist.i_26692_1_1,
            light_group=2
        },
        {
            type=31,
            section_start=22,
            section_end=0,
            seq=11,
            light_item=_itemlist.i_26692_1_1,
            light_group=2
        },
        {
            type=32,
            section_start=22,
            section_end=0,
            seq=12,
            light_item=_itemlist.i_26692_1_1,
            light_group=2
        },
        {
            type=33,
            section_start=22,
            section_end=0,
            seq=13,
            light_item=_itemlist.i_26692_1_1,
            light_group=2
        },
        {
            type=34,
            section_start=22,
            section_end=0,
            seq=14,
            light_item=_itemlist.i_26692_1_1,
            light_group=2
        },
        {
            type=35,
            section_start=22,
            section_end=0,
            seq=15,
            light_item=_itemlist.i_26692_1_1,
            light_group=2
        },
        {
            type=36,
            section_start=22,
            section_end=0,
            seq=16,
            light_item=_itemlist.i_26692_1_1,
            light_group=2
        },
        {
            type=37,
            section_start=22,
            section_end=0,
            seq=17,
            light_item=_itemlist.i_26692_1_1,
            light_group=2
        },
        {
            type=38,
            section_start=22,
            section_end=0,
            seq=18,
            light_item=_itemlist.i_26692_1_1,
            light_group=2
        },
        {
            type=39,
            section_start=22,
            section_end=0,
            seq=19,
            light_item=_itemlist.i_26692_1_1,
            light_group=2
        }
    },
    reward_configuration={
        {
            reward_item={
                [0]=_itemlist.i_23908_1_1
            }
        },
        {
            seq=1,
            reward_item={
                [0]=_itemlist.i_24811_1_1
            }
        },
        {
            seq=2,
            reward_item={
                [0]=_itemlist.i_25994_1_1
            }
        },
        {
            seq=3,
            reward_item={
                [0]=_itemlist.i_28915_1_1
            }
        },
        {
            seq=4,
            reward_item={
                [0]=_itemlist.i_25542_1_1
            }
        },
        {
            seq=5,
            reward_item={
                [0]=_itemlist.i_27838_1_1
            }
        },
        {
            seq=6,
            reward_item={
                [0]=_itemlist.i_29017_1_1
            }
        },
        {
            seq=7,
            reward_item={
                [0]=_itemlist.i_22013_1_1
            }
        },
        {
            group=2,
            reward_item={
                [0]=_itemlist.i_28667_1_1
            }
        },
        {
            seq=1,
            group=2,
            reward_item={
                [0]=_itemlist.i_24811_1_1
            }
        },
        {
            seq=2,
            group=2,
            reward_item={
                [0]=_itemlist.i_25994_1_1
            }
        },
        {
            seq=3,
            group=2,
            reward_item={
                [0]=_itemlist.i_28915_1_1
            }
        },
        {
            seq=4,
            group=2,
            reward_item={
                [0]=_itemlist.i_25542_1_1
            }
        },
        {
            seq=5,
            group=2,
            reward_item={
                [0]=_itemlist.i_27838_1_1
            }
        },
        {
            seq=6,
            group=2,
            reward_item={
                [0]=_itemlist.i_29017_2_1
            }
        },
        {
            seq=7,
            group=2,
            reward_item={
                [0]=_itemlist.i_22013_1_1
            }
        }
    },
    show_reward={
        {
            type=0,
            section_start=1,
            section_end=21,
            show_reward_item={
                [0]=_itemlist.i_23908_1_1,
                [1]=_itemlist.i_24811_1_1,
                [2]=_itemlist.i_25994_1_1,
                [3]=_itemlist.i_28915_1_1,
                [4]=_itemlist.i_25542_1_1,
                [5]=_itemlist.i_27838_1_1,
                [6]=_itemlist.i_29017_1_1,
                [7]=_itemlist.i_22013_1_1
            }
        },
        {
            type=1,
            section_start=22,
            section_end=0,
            show_reward_item={
                [0]=_itemlist.i_28667_1_1,
                [1]=_itemlist.i_24811_1_1,
                [2]=_itemlist.i_25994_1_1,
                [3]=_itemlist.i_28915_1_1,
                [4]=_itemlist.i_25542_1_1,
                [5]=_itemlist.i_27838_1_1,
                [6]=_itemlist.i_29017_2_1,
                [7]=_itemlist.i_22013_1_1
            }
        }
    },
    other={
        {
            all_light_item=_itemlist.i_31373_1_1,
            light_item=_itemlist.i_26692__
        }
    },
    activity_jump={
        {
            start_time=1,
            end_time=2,
            jump_mod=148003
        },
        {
            start_time=3,
            end_time=4,
            jump_mod=148004
        },
        {
            start_time=5,
            end_time=6,
            jump_mod=148002
        },
        {
            start_time=7,
            end_time=8,
            jump_mod=148007
        }
    }
}
SetConfigDefaultVal(Config.canglongcifu_auto,_default_val,nil,nil,nil)