local _default_val={
    level_monster_group={
        npc_id=59035
    }
}
Config.catch_fox_auto={
    find_fox={
        {
            level=1,
            scene_id=1702,
            pos_x1=163,
            pos_y1=64,
            is_map=0,
            layer=1,
            txt="目标：根据罗盘的指向，找到<color=#F7CF6F>隐形的狐妖</color>，并将它带到僧人身边\n<color=#fe1d1d>中途离开，任务将失败</color>"
        }
    },
    patrol={
        [1]={
            npc_index=1,
            name="聂小狐",
            npc_id=59025,
            res_id=109,
            change_res_id=669,
            scene_id=1702,
            birth_xyz="222|190",
            xyz1="194|314",
            xyz2="262|326",
            xyz3="290|274",
            xyz4="260|184",
            xyz5=0,
            xyz6=0,
            xyz7=0,
            xyz8=0,
            xyz9=0,
            xyz10=0,
            destination_xyz="222|190",
            dir_y=90,
            move_speed=2.5
        }
    },
    level_monster_group={
        {
            min_level=1,
            max_level=10,
            monster_group_id=27027
        },
        {
            min_level=11,
            max_level=20,
            monster_group_id=27028
        },
        {
            min_level=21,
            max_level=30,
            monster_group_id=27029
        },
        {
            min_level=31,
            max_level=40,
            monster_group_id=27030
        },
        {
            min_level=41,
            max_level=50,
            monster_group_id=27031
        },
        {
            min_level=51,
            max_level=60,
            monster_group_id=27032
        },
        {
            min_level=61,
            max_level=70,
            monster_group_id=27033
        },
        {
            min_level=71,
            max_level=80,
            monster_group_id=27034
        },
        {
            min_level=81,
            max_level=90,
            monster_group_id=27035
        },
        {
            min_level=91,
            max_level=100,
            monster_group_id=27036
        },
        {
            min_level=101,
            max_level=110,
            monster_group_id=27037
        },
        {
            min_level=111,
            max_level=120,
            monster_group_id=27038
        }
    },
    other={
        {
            task_id=65110,
            last_task_id=65113,
            npc_id=59022,
            level=1,
            special_bubble=119,
            special_talk=72121,
            fail_talk=72126,
            restart_talk=72127,
            max_player=1,
            skill_time=6,
            skill_range=80
        }
    }
}
SetConfigDefaultVal(Config.catch_fox_auto,_default_val,nil,nil,nil)