Config.chain_tasklist_auto={
    task_list={
        [20000]={
            task_id=20000,
            task_name="青云之乱",
            task_scene_name="玄都",
            min_level=34,
            task_scene_id=108,
            task_type=0,
            ver=0,
            time_day=1,
            max_level=120,
            pretaskid1="",
            camp_left_value=-1,
            camp_right_value=-1,
            is_add_robot=0,
            group_limited=0,
            group_limited_1=1,
            is_giveup="0|0|0|0",
            is_share=0,
            time_limit_second=0,
            condition=1,
            c_param1=696,
            c_param2=0,
            c_param3=0,
            reward_type=0,
            accept_npc=0,
            commit_npc=696,
            is_show_npc="",
            is_show_task_button=1,
            accept_btn_txt=0,
            accept_dialog_beh=0,
            dialog_btn_txt="与村长交谈",
            tasks_dialog_beh=0,
            commit_btn_txt="与村长交谈",
            commit_dialog_beh=1,
            accept_desc=0,
            progress_desc="接取环任务",
            obj_desc="接取环任务",
            obj_desc_1="接取环任务",
            show_other_npcseq="",
            is_shield_npc="",
            fly_to="0|0|0",
            follow_npc_seq="",
            auto_task=1,
            is_skip=0,
            skip_cost_type=0,
            skip_cost_num=0,
            section=1,
            schedule=""
        }
    },
    task_award={
        [20000]={
            task_id=20000,
            seq_beizhu=1,
            levels=1,
            left_value=100,
            right_value=199,
            coin_bind=5000,
            exp=69,
            pet_exp=0,
            immortal=0,
            gold=0,
            item_list={
                [0]={
                    item_id=2101,
                    num=1,
                    is_bind=1
                },
                [1]={
                    item_id=3101,
                    num=1,
                    is_bind=1
                }
            },
            power=0,
            reputation_city=1,
            reputation_num=0
        }
    },
    chapter_award={
        {
            section_seq=1,
            chapter_seq=1,
            chapter_award={
                [0]={
                    item_id=26719,
                    num=3,
                    is_bind=1
                }
            },
            chapter_seq_show="章壹",
            chapter_name="青云之乱",
            chapter_describe="境外历练#竟遇沫璃被抓"
        },
        {
            section_seq=1,
            chapter_seq=2,
            chapter_award={
                [0]={
                    item_id=26722,
                    num=3,
                    is_bind=1
                }
            },
            chapter_seq_show="章贰",
            chapter_name="游方药师",
            chapter_describe="刑天初现#玄都附近的阴谋"
        },
        {
            section_seq=1,
            chapter_seq=3,
            chapter_award={
                [0]={
                    item_id=26722,
                    num=3,
                    is_bind=1
                },
                [1]={
                    item_id=26812,
                    num=1,
                    is_bind=1
                }
            },
            chapter_seq_show="章叁",
            chapter_name="有情之人",
            chapter_describe="身负重伤#追踪刑天下落"
        },
        {
            section_seq=1,
            chapter_seq=4,
            chapter_award={
                [0]={
                    item_id=26719,
                    num=3,
                    is_bind=1
                },
                [1]={
                    item_id=26812,
                    num=1,
                    is_bind=1
                }
            },
            chapter_seq_show="章肆",
            chapter_name="还没写好",
            chapter_describe="阴山墓谷#关押散修的险地"
        },
        {
            section_seq=1,
            chapter_seq=5,
            chapter_award={
                [0]={
                    item_id=26725,
                    num=3,
                    is_bind=1
                },
                [1]={
                    item_id=26812,
                    num=1,
                    is_bind=1
                }
            },
            chapter_seq_show="章伍",
            chapter_name="继续摆烂",
            chapter_describe="奇异村庄#心智被迷供奉恶神"
        }
    },
    item_group={
        [20000]={
            group=20000,
            item_id=22005
        }
    },
    drop_group={},
    task_types={
        {
            sep=1,
            name="主线",
            color1="fef3d3",
            color2="",
            color3=""
        },
        {
            sep=2,
            name="支线",
            color1="e9a588",
            color2="",
            color3=""
        },
        {
            sep=3,
            name="挑战",
            color1="b5db64",
            color2="",
            color3=""
        },
        {
            sep=4,
            name="日常",
            color1="e9a588",
            color2="",
            color3=""
        },
        {
            sep=5,
            name="周常",
            color1="e9a588",
            color2="",
            color3=""
        },
        {
            sep=6,
            name="引导",
            color1="e9a588",
            color2="",
            color3=""
        },
        {
            sep=7,
            name="进阶",
            color1="b5db64",
            color2="",
            color3=""
        },
        {
            sep=8,
            name="声望",
            color1="5de4e2",
            color2="",
            color3=""
        },
        {
            sep=9,
            name="奇遇",
            color1="f09eff",
            color2="",
            color3=""
        },
        {
            sep=10,
            name="家族",
            color1="e9a588",
            color2="",
            color3=""
        },
        {
            sep=11,
            name="勋章",
            color1="b5db64",
            color2="",
            color3=""
        }
    },
    other={
        {
            pretask_id=1464
        }
    }
}