Config.children_question_auto={
    question={
        {
            question_id=1,
            order=1,
            answer_id=3,
            question="“妈妈的妹妹的女儿该怎么准确的称呼呢？”",
            anwser_1="堂哥",
            anwser_2="堂姐",
            anwser_3="姨表姐",
            anwser_4="表姐"
        },
        {
            question_id=2,
            order=2,
            answer_id=2,
            question="“奶奶的弟弟该怎么准确的称呼呢？”",
            anwser_1="爷爷",
            anwser_2="舅公",
            anwser_3="外公",
            anwser_4="叔公"
        },
        {
            question_id=3,
            order=3,
            answer_id=4,
            question="“爸爸的妈妈的姐姐该怎么准确的称呼呢？”",
            anwser_1="姑奶奶",
            anwser_2="外婆",
            anwser_3="叔公",
            anwser_4="姨奶奶"
        }
    },
    other={
        {
            question_num=3,
            success=5008,
            fail=5007
        }
    }
}