local _default_val={
    basis_configure={
        section_start=1,
        section_end=0,
        awaken_reward_group=1
    },
    gift_configure={
        section_start=1,
        section_end=0,
        seq=0,
        module_type=0,
        parameter=20,
        target_desc="虎气生生"
    },
    gift_group={
        reward_group=1,
        is_show=1,
        show_rate=0.15,
        hearsay=1
    }
}
local _itemlist={
    i_22013_5_1={
        item_id=22013,
        num=5,
        is_bind=1
    },
    i_29017_3_1={
        item_id=29017,
        num=3,
        is_bind=1
    },
    i_27838_1_1={
        item_id=27838,
        num=1,
        is_bind=1
    },
    i_29017_4_1={
        item_id=29017,
        num=4,
        is_bind=1
    },
    i_27838_2_1={
        item_id=27838,
        num=2,
        is_bind=1
    },
    i_29017_5_1={
        item_id=29017,
        num=5,
        is_bind=1
    },
    i_27838_3_1={
        item_id=27838,
        num=3,
        is_bind=1
    },
    i_28283_1_1={
        item_id=28283,
        num=1,
        is_bind=1
    },
    i_24800_1_1={
        item_id=24800,
        num=1,
        is_bind=1
    },
    i_25005_1_1={
        item_id=25005,
        num=1,
        is_bind=1
    },
    i_25542_1_1={
        item_id=25542,
        num=1,
        is_bind=1
    },
    i_25993_1_1={
        item_id=25993,
        num=1,
        is_bind=1
    },
    i_25834_1_1={
        item_id=25834,
        num=1,
        is_bind=1
    }
}
Config.ciniuyingxinhu_auto={
    basis_configure={
        {
            type=0,
            seq=0,
            activity_days=1,
            module_name="长寿"
        },
        {
            type=1,
            seq=1,
            activity_days=3,
            module_name="富贵"
        },
        {
            type=2,
            seq=2,
            activity_days=5,
            module_name="康宁"
        },
        {
            type=3,
            seq=3,
            activity_days=8,
            module_name="慈孝"
        },
        {
            type=4,
            seq=4,
            activity_days=10,
            module_name="好德"
        }
    },
    gift_configure={
        {
            type=0,
            reward_item={
                [0]=_itemlist.i_22013_5_1,
                [1]=_itemlist.i_29017_3_1,
                [2]=_itemlist.i_27838_1_1
            }
        },
        {
            type=1,
            seq=1,
            parameter=40,
            reward_item={
                [0]=_itemlist.i_22013_5_1,
                [1]=_itemlist.i_29017_4_1,
                [2]=_itemlist.i_27838_2_1
            },
            target_desc="虎气生威"
        },
        {
            type=2,
            seq=2,
            parameter=60,
            reward_item={
                [0]=_itemlist.i_22013_5_1,
                [1]=_itemlist.i_29017_5_1,
                [2]=_itemlist.i_27838_3_1
            },
            target_desc="虎气冲天"
        },
        {
            type=3,
            module_type=1,
            reward_item={
                [0]=_itemlist.i_22013_5_1,
                [1]=_itemlist.i_29017_3_1,
                [2]=_itemlist.i_27838_1_1
            }
        },
        {
            type=4,
            seq=1,
            module_type=1,
            parameter=40,
            reward_item={
                [0]=_itemlist.i_22013_5_1,
                [1]=_itemlist.i_29017_4_1,
                [2]=_itemlist.i_27838_2_1
            },
            target_desc="虎气生威"
        },
        {
            type=5,
            seq=2,
            module_type=1,
            parameter=60,
            reward_item={
                [0]=_itemlist.i_22013_5_1,
                [1]=_itemlist.i_29017_5_1,
                [2]=_itemlist.i_27838_3_1
            },
            target_desc="虎气冲天"
        },
        {
            type=6,
            module_type=2,
            reward_item={
                [0]=_itemlist.i_22013_5_1,
                [1]=_itemlist.i_29017_3_1,
                [2]=_itemlist.i_27838_1_1
            }
        },
        {
            type=7,
            seq=1,
            module_type=2,
            parameter=40,
            reward_item={
                [0]=_itemlist.i_22013_5_1,
                [1]=_itemlist.i_29017_4_1,
                [2]=_itemlist.i_27838_2_1
            },
            target_desc="虎气生威"
        },
        {
            type=8,
            seq=2,
            module_type=2,
            parameter=60,
            reward_item={
                [0]=_itemlist.i_22013_5_1,
                [1]=_itemlist.i_29017_5_1,
                [2]=_itemlist.i_27838_3_1
            },
            target_desc="虎气冲天"
        },
        {
            type=9,
            module_type=3,
            reward_item={
                [0]=_itemlist.i_22013_5_1,
                [1]=_itemlist.i_29017_3_1,
                [2]=_itemlist.i_27838_1_1
            }
        },
        {
            type=10,
            seq=1,
            module_type=3,
            parameter=40,
            reward_item={
                [0]=_itemlist.i_22013_5_1,
                [1]=_itemlist.i_29017_4_1,
                [2]=_itemlist.i_27838_2_1
            },
            target_desc="虎气生威"
        },
        {
            type=11,
            seq=2,
            module_type=3,
            parameter=60,
            reward_item={
                [0]=_itemlist.i_22013_5_1,
                [1]=_itemlist.i_29017_5_1,
                [2]=_itemlist.i_27838_3_1
            },
            target_desc="虎气冲天"
        },
        {
            type=12,
            module_type=4,
            reward_item={
                [0]=_itemlist.i_22013_5_1,
                [1]=_itemlist.i_29017_3_1,
                [2]=_itemlist.i_27838_1_1
            }
        },
        {
            type=13,
            seq=1,
            module_type=4,
            parameter=40,
            reward_item={
                [0]=_itemlist.i_22013_5_1,
                [1]=_itemlist.i_29017_4_1,
                [2]=_itemlist.i_27838_2_1
            },
            target_desc="虎气生威"
        },
        {
            type=14,
            seq=2,
            module_type=4,
            parameter=60,
            reward_item={
                [0]=_itemlist.i_22013_5_1,
                [1]=_itemlist.i_29017_5_1,
                [2]=_itemlist.i_27838_3_1
            },
            target_desc="虎气冲天"
        }
    },
    gift_group={
        {
            type=0,
            seq=0,
            reward_item=_itemlist.i_28283_1_1
        },
        {
            type=1,
            seq=1,
            reward_item=_itemlist.i_24800_1_1
        },
        {
            type=2,
            seq=2,
            reward_item=_itemlist.i_25005_1_1
        },
        {
            type=3,
            seq=3,
            reward_item=_itemlist.i_25542_1_1,
            is_show=0
        },
        {
            type=4,
            seq=4,
            reward_item=_itemlist.i_25993_1_1,
            is_show=0,
            show_rate=0.2
        },
        {
            type=5,
            seq=5,
            reward_item=_itemlist.i_25834_1_1,
            is_show=0,
            show_rate=0.2
        }
    },
    other={
        {
            submit_item=26356,
            item_num=1,
            add_tiger_air=1
        }
    }
}
SetConfigDefaultVal(Config.ciniuyingxinhu_auto,_default_val,nil,nil,nil)