local _default_val={
    seven_color_picture_award={
        seq=0,
        section_start=1,
        section_end=7,
        grade_start=1,
        grade_end=0
    },
    color_list={
        seq=0,
        quality=0
    }
}
local _itemlist={
    i_26344_20_1={
        item_id=26344,
        num=20,
        is_bind=1
    },
    i_26344_1_1={
        item_id=26344,
        num=1,
        is_bind=1
    },
    i_29018_1_1={
        item_id=29018,
        num=1,
        is_bind=1
    },
    i_28664_1_1={
        item_id=28664,
        num=1,
        is_bind=1
    },
    i_27620_1_1={
        item_id=27620,
        num=1,
        is_bind=1
    }
}
Config.colorful_illustrations_auto={
    other={
        {
            section_start=1,
            section_end=0,
            seven_color_collection_reward=_itemlist.i_26344_20_1,
            time=1,
            coin_num=4000,
            gold_num=2,
            is_complement=0
        }
    },
    seven_color_picture_pigment={
        {
            seq=0,
            quality=0,
            is_special=12
        },
        {
            seq=1,
            quality=1,
            is_special=7
        },
        {
            seq=2,
            quality=2,
            is_special=3
        }
    },
    seven_color_picture_award={
        {
            reward_show=_itemlist.i_26344_1_1
        },
        {
            seq=1,
            reward_show=_itemlist.i_29018_1_1
        },
        {
            section_start=8,
            section_end=21,
            reward_show=_itemlist.i_26344_1_1
        },
        {
            seq=1,
            section_start=8,
            section_end=21,
            reward_show=_itemlist.i_28664_1_1
        },
        {
            section_start=22,
            section_end=36,
            reward_show=_itemlist.i_26344_1_1
        },
        {
            seq=1,
            section_start=22,
            section_end=36,
            reward_show=_itemlist.i_27620_1_1
        },
        {
            section_start=37,
            section_end=0,
            reward_show=_itemlist.i_26344_1_1
        },
        {
            seq=1,
            section_start=37,
            section_end=0,
            reward_show=_itemlist.i_27620_1_1
        }
    },
    color_list={
        {
            sort=1
        },
        {
            sort=2,
            quality=1
        },
        {
            sort=3,
            quality=2
        },
        {
            seq=1,
            sort=4
        },
        {
            seq=1,
            sort=5,
            quality=1
        },
        {
            seq=1,
            sort=6,
            quality=2
        },
        {
            seq=2,
            sort=7
        },
        {
            seq=2,
            sort=8,
            quality=1
        },
        {
            seq=2,
            sort=9,
            quality=2
        },
        {
            seq=3,
            sort=10
        },
        {
            seq=3,
            sort=11,
            quality=1
        },
        {
            seq=3,
            sort=12,
            quality=2
        },
        {
            seq=4,
            sort=13
        },
        {
            seq=4,
            sort=14,
            quality=1
        },
        {
            seq=4,
            sort=15,
            quality=2
        },
        {
            seq=5,
            sort=16
        },
        {
            seq=5,
            sort=17,
            quality=1
        },
        {
            seq=5,
            sort=18,
            quality=2
        },
        {
            seq=6,
            sort=19
        },
        {
            seq=6,
            sort=20,
            quality=1
        },
        {
            seq=6,
            sort=21,
            quality=2
        }
    }
}
SetConfigDefaultVal(Config.colorful_illustrations_auto,_default_val,nil,nil,nil)