local _default_val={
    cards_group={
        left_1=2,
        left_2=5,
        left_3=9,
        left_4=7,
        left_5=5,
        left_6=3,
        left_7=6,
        left_8=4,
        left_9=9,
        right_1=4,
        right_2=5,
        right_3=8,
        right_4=2,
        right_5=6,
        right_6=7,
        right_7=8,
        right_8=3,
        right_9=6
    },
    moqi_num={
        dec_second="你们的默契打败了<color=#00e240>100%</color>的玩家"
    }
}
local _itemlist={
    i_26863_1_1={
        item_id=26863,
        num=1,
        is_bind=1
    },
    i_26864_1_1={
        item_id=26864,
        num=1,
        is_bind=1
    },
    i_26865_1_1={
        item_id=26865,
        num=1,
        is_bind=1
    },
    i_31319_1_1={
        item_id=31319,
        num=1,
        is_bind=1
    },
    i_26230_30_1={
        item_id=26230,
        num=30,
        is_bind=1
    },
    i_26230_1_1={
        item_id=26230,
        num=1,
        is_bind=1
    }
}
Config.concentric_knot_auto={
    cards_group={
        {
            cards_groud=1,
            left_1=1,
            left_2=4,
            left_3=7,
            left_4=5,
            left_5=3,
            left_6=8,
            left_7=2,
            left_8=9,
            left_9=6,
            right_2=8,
            right_3=5,
            right_5=1,
            right_6=9,
            right_7=7
        },
        {
            cards_groud=2,
            left_1=7,
            left_3=1,
            left_4=4,
            left_5=2,
            left_8=8,
            right_1=9,
            right_2=4,
            right_4=3,
            right_7=2,
            right_8=1,
            right_9=5
        },
        {
            cards_groud=3,
            left_2=7,
            left_4=1,
            left_5=4,
            left_6=5,
            left_7=3,
            left_8=6,
            left_9=8,
            right_1=2,
            right_2=6,
            right_3=7,
            right_4=9,
            right_5=4,
            right_6=5,
            right_9=1
        },
        {
            cards_groud=4,
            left_1=3,
            left_2=6,
            left_3=8,
            left_5=9,
            left_6=2,
            left_7=5,
            left_9=1,
            right_7=1,
            right_9=9
        },
        {
            cards_groud=5,
            left_1=6,
            left_2=8,
            left_6=1,
            left_7=4,
            left_8=2,
            left_9=3,
            right_1=7,
            right_2=2,
            right_3=1,
            right_4=5,
            right_5=9,
            right_6=4
        },
        {
            cards_groud=6,
            left_2=9,
            left_3=6,
            left_4=8,
            left_7=1,
            left_9=7,
            right_1=7,
            right_2=3,
            right_3=6,
            right_4=4,
            right_5=8,
            right_6=5,
            right_7=2,
            right_8=1,
            right_9=9
        },
        {
            cards_groud=7,
            left_1=4,
            left_3=8,
            left_4=3,
            left_5=1,
            left_6=2,
            left_8=7,
            right_3=3,
            right_4=6,
            right_5=8,
            right_6=2,
            right_7=7,
            right_8=9,
            right_9=1
        }
    },
    other={
        {
            item_list_first={
                [0]=_itemlist.i_26863_1_1,
                [1]=_itemlist.i_26864_1_1,
                [2]=_itemlist.i_26865_1_1
            },
            play_time=65,
            reward_1={
                [0]=_itemlist.i_31319_1_1,
                [1]=_itemlist.i_26230_30_1
            },
            reward_show={
                [0]=_itemlist.i_31319_1_1,
                [1]=_itemlist.i_26230_1_1
            },
            npc_seq=73712,
            talk_fail_id=14009,
            talk_win_id=14010,
            talk_rule=14030,
            talk_win_id2=11064
        }
    },
    activedegree={
        {
            activedegree=50
        },
        {
            activedegree=75
        },
        {
            activedegree=100
        },
        {
            activedegree=120
        },
        {
            activedegree=150
        }
    },
    moqi_num={
        {
            expends_time=1,
            dec_first="<color=#FFB934>太棒了！用时1秒</color>"
        },
        {
            expends_time=2,
            dec_first="<color=#FFB934>太棒了！用时2秒</color>"
        },
        {
            expends_time=3,
            dec_first="<color=#FFB934>太棒了！用时3秒</color>"
        },
        {
            expends_time=4,
            dec_first="<color=#FFB934>太棒了！用时4秒</color>"
        },
        {
            expends_time=5,
            dec_first="<color=#FFB934>太棒了！用时5秒</color>"
        },
        {
            expends_time=6,
            dec_first="<color=#FFB934>太棒了！用时6秒</color>"
        },
        {
            expends_time=7,
            dec_first="<color=#FFB934>太棒了！用时7秒</color>"
        },
        {
            expends_time=8,
            dec_first="<color=#FFB934>太棒了！用时8秒</color>"
        },
        {
            expends_time=9,
            dec_first="<color=#FFB934>太棒了！用时9秒</color>",
            dec_second="你们的默契打败了<color=#00e240>99%</color>的玩家"
        },
        {
            expends_time=10,
            dec_first="<color=#FFB934>太棒了！用时10秒</color>",
            dec_second="你们的默契打败了<color=#00e240>99%</color>的玩家"
        },
        {
            expends_time=11,
            dec_first="<color=#FFB934>太棒了！用时11秒</color>",
            dec_second="你们的默契打败了<color=#00e240>99%</color>的玩家"
        },
        {
            expends_time=12,
            dec_first="<color=#FFB934>太棒了！用时12秒</color>",
            dec_second="你们的默契打败了<color=#00e240>98%</color>的玩家"
        },
        {
            expends_time=13,
            dec_first="<color=#FFB934>太棒了！用时13秒</color>",
            dec_second="你们的默契打败了<color=#00e240>98%</color>的玩家"
        },
        {
            expends_time=14,
            dec_first="<color=#FFB934>太棒了！用时14秒</color>",
            dec_second="你们的默契打败了<color=#00e240>98%</color>的玩家"
        },
        {
            expends_time=15,
            dec_first="<color=#FFB934>太棒了！用时15秒</color>",
            dec_second="你们的默契打败了<color=#00e240>97%</color>的玩家"
        },
        {
            expends_time=16,
            dec_first="<color=#FFB934>太棒了！用时16秒</color>",
            dec_second="你们的默契打败了<color=#00e240>97%</color>的玩家"
        },
        {
            expends_time=17,
            dec_first="<color=#FFB934>太棒了！用时17秒</color>",
            dec_second="你们的默契打败了<color=#00e240>96%</color>的玩家"
        },
        {
            expends_time=18,
            dec_first="<color=#FFB934>太棒了！用时18秒</color>",
            dec_second="你们的默契打败了<color=#00e240>96%</color>的玩家"
        },
        {
            expends_time=19,
            dec_first="<color=#FFB934>太棒了！用时19秒</color>",
            dec_second="你们的默契打败了<color=#00e240>95%</color>的玩家"
        },
        {
            expends_time=20,
            dec_first="<color=#FFB934>太棒了！用时20秒</color>",
            dec_second="你们的默契打败了<color=#00e240>95%</color>的玩家"
        },
        {
            expends_time=21,
            dec_first="<color=#FFB934>太棒了！用时21秒</color>",
            dec_second="你们的默契打败了<color=#00e240>94%</color>的玩家"
        },
        {
            expends_time=22,
            dec_first="<color=#FFB934>太棒了！用时22秒</color>",
            dec_second="你们的默契打败了<color=#00e240>94%</color>的玩家"
        },
        {
            expends_time=23,
            dec_first="<color=#FFB934>太棒了！用时23秒</color>",
            dec_second="你们的默契打败了<color=#00e240>93%</color>的玩家"
        },
        {
            expends_time=24,
            dec_first="<color=#FFB934>太棒了！用时24秒</color>",
            dec_second="你们的默契打败了<color=#00e240>93%</color>的玩家"
        },
        {
            expends_time=25,
            dec_first="<color=#FFB934>太棒了！用时25秒</color>",
            dec_second="你们的默契打败了<color=#00e240>92%</color>的玩家"
        },
        {
            expends_time=26,
            dec_first="<color=#FFB934>太棒了！用时26秒</color>",
            dec_second="你们的默契打败了<color=#00e240>92%</color>的玩家"
        },
        {
            expends_time=27,
            dec_first="<color=#FFB934>太棒了！用时27秒</color>",
            dec_second="你们的默契打败了<color=#00e240>91%</color>的玩家"
        },
        {
            expends_time=28,
            dec_first="<color=#FFB934>太棒了！用时28秒</color>",
            dec_second="你们的默契打败了<color=#00e240>91%</color>的玩家"
        },
        {
            expends_time=29,
            dec_first="<color=#FFB934>太棒了！用时29秒</color>",
            dec_second="你们的默契打败了<color=#00e240>90%</color>的玩家"
        },
        {
            expends_time=30,
            dec_first="<color=#FFB934>太棒了！用时30秒</color>",
            dec_second="你们的默契打败了<color=#00e240>90%</color>的玩家"
        },
        {
            expends_time=31,
            dec_first="<color=#FFB934>太棒了！用时31秒</color>",
            dec_second="你们的默契打败了<color=#00e240>89%</color>的玩家"
        },
        {
            expends_time=32,
            dec_first="<color=#FFB934>太棒了！用时32秒</color>",
            dec_second="你们的默契打败了<color=#00e240>89%</color>的玩家"
        },
        {
            expends_time=33,
            dec_first="<color=#FFB934>太棒了！用时33秒</color>",
            dec_second="你们的默契打败了<color=#00e240>88%</color>的玩家"
        },
        {
            expends_time=34,
            dec_first="<color=#FFB934>太棒了！用时34秒</color>",
            dec_second="你们的默契打败了<color=#00e240>88%</color>的玩家"
        },
        {
            expends_time=35,
            dec_first="<color=#FFB934>太棒了！用时35秒</color>",
            dec_second="你们的默契打败了<color=#00e240>87%</color>的玩家"
        },
        {
            expends_time=36,
            dec_first="<color=#FFB934>太棒了！用时36秒</color>",
            dec_second="你们的默契打败了<color=#00e240>86%</color>的玩家"
        },
        {
            expends_time=37,
            dec_first="<color=#FFB934>太棒了！用时37秒</color>",
            dec_second="你们的默契打败了<color=#00e240>85%</color>的玩家"
        },
        {
            expends_time=38,
            dec_first="<color=#FFB934>太棒了！用时38秒</color>",
            dec_second="你们的默契打败了<color=#00e240>84%</color>的玩家"
        },
        {
            expends_time=39,
            dec_first="<color=#FFB934>太棒了！用时39秒</color>",
            dec_second="你们的默契打败了<color=#00e240>83%</color>的玩家"
        },
        {
            expends_time=40,
            dec_first="<color=#FFB934>太棒了！用时40秒</color>",
            dec_second="你们的默契打败了<color=#00e240>82%</color>的玩家"
        },
        {
            expends_time=41,
            dec_first="<color=#FFB934>本场用时41秒</color>",
            dec_second="你们的默契打败了<color=#00e240>78%</color>的玩家"
        },
        {
            expends_time=42,
            dec_first="<color=#FFB934>本场用时42秒</color>",
            dec_second="你们的默契打败了<color=#00e240>73%</color>的玩家"
        },
        {
            expends_time=43,
            dec_first="<color=#FFB934>本场用时43秒</color>",
            dec_second="你们的默契打败了<color=#00e240>70%</color>的玩家"
        },
        {
            expends_time=44,
            dec_first="<color=#FFB934>本场用时44秒</color>",
            dec_second="你们的默契打败了<color=#00e240>65%</color>的玩家"
        },
        {
            expends_time=45,
            dec_first="<color=#FFB934>本场用时45秒</color>",
            dec_second="你们的默契打败了<color=#00e240>59%</color>的玩家"
        },
        {
            expends_time=46,
            dec_first="<color=#FFB934>本场用时46秒</color>",
            dec_second="你们的默契打败了<color=#00e240>54%</color>的玩家"
        },
        {
            expends_time=47,
            dec_first="<color=#FFB934>本场用时47秒</color>",
            dec_second="你们的默契打败了<color=#00e240>50%</color>的玩家"
        },
        {
            expends_time=48,
            dec_first="<color=#FFB934>本场用时48秒</color>",
            dec_second="你们的默契打败了<color=#00e240>47%</color>的玩家"
        },
        {
            expends_time=49,
            dec_first="<color=#FFB934>本场用时49秒</color>",
            dec_second="你们的默契打败了<color=#00e240>40%</color>的玩家"
        },
        {
            expends_time=50,
            dec_first="<color=#FFB934>本场用时50秒</color>",
            dec_second="你们的默契打败了<color=#00e240>35%</color>的玩家"
        },
        {
            expends_time=51,
            dec_first="<color=#FFB934>本场用时51秒</color>",
            dec_second="你们的默契打败了<color=#00e240>33%</color>的玩家"
        },
        {
            expends_time=52,
            dec_first="<color=#FFB934>本场用时52秒</color>",
            dec_second="你们的默契打败了<color=#00e240>31%</color>的玩家"
        },
        {
            expends_time=53,
            dec_first="<color=#FFB934>本场用时53秒</color>",
            dec_second="你们的默契打败了<color=#00e240>30%</color>的玩家"
        },
        {
            expends_time=54,
            dec_first="<color=#FFB934>本场用时54秒</color>",
            dec_second="你们的默契打败了<color=#00e240>27%</color>的玩家"
        },
        {
            expends_time=55,
            dec_first="<color=#FFB934>本场用时55秒</color>",
            dec_second="你们的默契打败了<color=#00e240>26%</color>的玩家"
        },
        {
            expends_time=56,
            dec_first="<color=#FFB934>本场用时56秒</color>",
            dec_second="你们的默契打败了<color=#00e240>24%</color>的玩家"
        },
        {
            expends_time=57,
            dec_first="<color=#FFB934>本场用时57秒</color>",
            dec_second="你们的默契打败了<color=#00e240>20%</color>的玩家"
        },
        {
            expends_time=58,
            dec_first="<color=#FFB934>本场用时58秒</color>",
            dec_second="你们的默契打败了<color=#00e240>18%</color>的玩家"
        },
        {
            expends_time=59,
            dec_first="<color=#FFB934>本场用时59秒</color>",
            dec_second="你们的默契打败了<color=#00e240>15%</color>的玩家"
        },
        {
            expends_time=60,
            dec_first="<color=#FFB934>本场用时60秒</color>",
            dec_second="你们的默契打败了<color=#00e240>12%</color>的玩家"
        },
        {
            expends_time=61,
            dec_first="<color=#FFB934>本场用时61秒</color>",
            dec_second="你们的默契打败了<color=#00e240>9%</color>的玩家"
        },
        {
            expends_time=62,
            dec_first="<color=#FFB934>本场用时62秒</color>",
            dec_second="你们的默契打败了<color=#00e240>7%</color>的玩家"
        },
        {
            expends_time=63,
            dec_first="<color=#FFB934>本场用时63秒</color>",
            dec_second="你们的默契打败了<color=#00e240>5%</color>的玩家"
        },
        {
            expends_time=64,
            dec_first="<color=#FFB934>本场用时64秒</color>",
            dec_second="你们的默契打败了<color=#00e240>3%</color>的玩家"
        },
        {
            expends_time=65,
            dec_first="<color=#FFB934>本场用时65秒</color>",
            dec_second="你们的默契打败了<color=#00e240>0%</color>的玩家"
        }
    }
}
SetConfigDefaultVal(Config.concentric_knot_auto,_default_val,nil,nil,nil)