local _default_val={
    gift_configure={
        section_start=1,
        section_end=7,
        seq=0,
        unlock_integral=0,
        limit_type=2,
        buy_times=0,
        today_times=1,
        price_type=1,
        price=2500
    }
}
local _itemlist={
    i_25979_1_1={
        item_id=25979,
        num=1,
        is_bind=1
    },
    i_25977_1_1={
        item_id=25977,
        num=1,
        is_bind=1
    },
    i_29032_1_1={
        item_id=29032,
        num=1,
        is_bind=1
    },
    i_26812_1_1={
        item_id=26812,
        num=1,
        is_bind=1
    },
    i_25505_1_1={
        item_id=25505,
        num=1,
        is_bind=1
    },
    i_29038_1_1={
        item_id=29038,
        num=1,
        is_bind=1
    },
    i_27575_1_1={
        item_id=27575,
        num=1,
        is_bind=1
    },
    i_22007_10_1={
        item_id=22007,
        num=10,
        is_bind=1
    },
    i_24326_1_1={
        item_id=24326,
        num=1,
        is_bind=1
    }
}
Config.cow_exchange_auto={
    gift_configure={
        {
            type=0,
            reward_item=_itemlist.i_25979_1_1,
            limit_type=1,
            buy_times=1,
            today_times=0
        },
        {
            type=1,
            seq=1,
            reward_item=_itemlist.i_25977_1_1,
            limit_type=1,
            buy_times=1,
            today_times=0
        },
        {
            type=2,
            seq=2,
            reward_item=_itemlist.i_29032_1_1,
            price=8000
        },
        {
            type=3,
            seq=3,
            reward_item=_itemlist.i_26812_1_1,
            today_times=3,
            price=800
        },
        {
            type=4,
            seq=4,
            reward_item=_itemlist.i_25505_1_1,
            price=2000
        },
        {
            type=5,
            seq=5,
            reward_item=_itemlist.i_29038_1_1
        },
        {
            type=6,
            seq=6,
            reward_item=_itemlist.i_27575_1_1,
            today_times=5,
            price=500
        },
        {
            type=7,
            seq=7,
            reward_item=_itemlist.i_22007_10_1,
            today_times=5,
            price=250
        },
        {
            type=8,
            seq=8,
            reward_item=_itemlist.i_24326_1_1,
            today_times=5,
            price=250
        },
        {
            type=9,
            section_start=8,
            section_end=14,
            reward_item=_itemlist.i_25979_1_1,
            limit_type=1,
            buy_times=1,
            today_times=0
        },
        {
            type=10,
            section_start=8,
            section_end=14,
            seq=1,
            reward_item=_itemlist.i_25977_1_1,
            limit_type=1,
            buy_times=1,
            today_times=0
        },
        {
            type=11,
            section_start=8,
            section_end=14,
            seq=2,
            reward_item=_itemlist.i_29032_1_1,
            price=8000
        },
        {
            type=12,
            section_start=8,
            section_end=14,
            seq=3,
            reward_item=_itemlist.i_26812_1_1,
            today_times=3,
            price=800
        },
        {
            type=13,
            section_start=8,
            section_end=14,
            seq=4,
            reward_item=_itemlist.i_25505_1_1,
            price=2000
        },
        {
            type=14,
            section_start=8,
            section_end=14,
            seq=5,
            reward_item=_itemlist.i_29038_1_1
        },
        {
            type=15,
            section_start=8,
            section_end=14,
            seq=6,
            reward_item=_itemlist.i_27575_1_1,
            today_times=5,
            price=500
        },
        {
            type=16,
            section_start=8,
            section_end=14,
            seq=7,
            reward_item=_itemlist.i_22007_10_1,
            today_times=5,
            price=250
        },
        {
            type=17,
            section_start=8,
            section_end=14,
            seq=8,
            reward_item=_itemlist.i_24326_1_1,
            today_times=5,
            price=250
        },
        {
            type=18,
            section_start=15,
            section_end=0,
            reward_item=_itemlist.i_25979_1_1,
            limit_type=1,
            buy_times=1,
            today_times=0
        },
        {
            type=19,
            section_start=15,
            section_end=0,
            seq=1,
            reward_item=_itemlist.i_25977_1_1,
            limit_type=1,
            buy_times=1,
            today_times=0
        },
        {
            type=20,
            section_start=15,
            section_end=0,
            seq=2,
            reward_item=_itemlist.i_29032_1_1,
            price=8000
        },
        {
            type=21,
            section_start=15,
            section_end=0,
            seq=3,
            reward_item=_itemlist.i_26812_1_1,
            today_times=3,
            price=800
        },
        {
            type=22,
            section_start=15,
            section_end=0,
            seq=4,
            reward_item=_itemlist.i_25505_1_1,
            price=2000
        },
        {
            type=23,
            section_start=15,
            section_end=0,
            seq=5,
            reward_item=_itemlist.i_29038_1_1
        },
        {
            type=24,
            section_start=15,
            section_end=0,
            seq=6,
            reward_item=_itemlist.i_27575_1_1,
            today_times=5,
            price=500
        },
        {
            type=25,
            section_start=15,
            section_end=0,
            seq=7,
            reward_item=_itemlist.i_22007_10_1,
            today_times=5,
            price=250
        },
        {
            type=26,
            section_start=15,
            section_end=0,
            seq=8,
            reward_item=_itemlist.i_24326_1_1,
            today_times=5,
            price=250
        }
    },
    other={
        {
            cfg_ver=1
        }
    }
}
SetConfigDefaultVal(Config.cow_exchange_auto,_default_val,nil,nil,nil)