local _default_val={
    daily={
        act_seq=14,
        is_show=1,
        icon_id="a1013",
        name_text="竞技场",
        fun_name=0,
        title=4,
        activity_group=1,
        position=0,
        recommend_text="无",
        level_restrict=30,
        number_min=1,
        number_max=1,
        is_team=0,
        time_text="全天可参与",
        open_day="1:2:3:4:5:6:7",
        begin_time="00:00",
        end_time="24:00",
        content_text="神域神域神域",
        is_push_show=0,
        red_shape=0,
        btn_name="前往",
        btn_type=1,
        content_tip=0,
        cross_service=0
    },
    activity_label_show={
        label_color=1
    },
    week_time={
        week_6="",
        act_id_6="",
        week_7="",
        act_id_7=""
    },
    effect_show={
        effect_id=3161079
    },
    sign_up={
        open=1
    },
    reward_show={
        act_type=1,
        min_level=1,
        max_level=120,
        activity_type="1,2,7",
        label_show="3,4",
        reward_id="65549:65770:65771:65772:65532"
    },
    activity_show={
        activity_show=191,
        is_popup=1,
        reward_id="22050:24518:24557"
    },
    join_reward={
        seq=3,
        activity_id=5,
        min_level=1,
        max_level=120,
        exp=0,
        coin=30000
    },
    match_notice={
        seq=0,
        type=1,
        name="奖励规则"
    }
}
local _itemlist={
    i_27398_1_1={
        item_id=27398,
        num=1,
        is_bind=1
    },
    i_28518_1_1={
        item_id=28518,
        num=1,
        is_bind=1
    },
    i_24518_1_1={
        item_id=24518,
        num=1,
        is_bind=1
    }
}
Config.daily_activity_auto={
    daily={
        [10044]={
            act_type=10044,
            act_seq=1,
            icon_id="a1049",
            name_text="万灵大事件",
            title=5,
            position=2,
            content_text="云泽大陆上每天都上演着诸多奇闻轶事，期待你的参与！",
            btn_name="查看"
        },
        [10035]={
            act_type=10035,
            act_seq=10,
            icon_id="a1040",
            name_text="精英试炼",
            fun_name=31010,
            level_restrict=34,
            number_max=5,
            is_team=1,
            content_text="组队进入幻境中，协力击败幻境中的首领，通关可获得丰厚奖励",
            red_shape=1
        },
        [10009]={
            act_type=10009,
            act_seq=3,
            icon_id="a1008",
            name_text="三界除魔",
            fun_name=5010,
            title=3,
            position=9,
            recommend_text="皇城",
            level_restrict=31,
            content_text="需击败潜藏在各地的妖灵，以守护人们的安危，完成即可获得大量奖励",
            red_shape=1,
            btn_type=2
        },
        [10022]={
            act_type=10022,
            act_seq=4,
            is_show=0,
            icon_id="a1027",
            name_text="四象幻境",
            fun_name=5063,
            recommend_text="皇城",
            level_restrict=31,
            number_min=3,
            number_max=5,
            is_team=1,
            content_text="组队进入幻境中，内含地水火风四个幻境，通关者可获得丰厚奖励"
        },
        [10004]={
            act_type=10004,
            act_seq=5,
            icon_id="a1066",
            name_text="万妖谷",
            fun_name=825,
            position=4,
            level_restrict=60,
            number_min=3,
            number_max=5,
            is_team=1,
            content_text="组队任务，抵御妖兽的连续入侵，每成功抵御一波进攻即可获得丰厚的奖赏",
            btn_type=2
        },
        [10030]={
            act_type=10030,
            act_seq=6,
            is_show=0,
            icon_id="a1037",
            name_text="梦渊笔录",
            title=3,
            level_restrict=13,
            content_text="进入书卷之中挑战BOSS，提升自己和伙伴实力，赢取丰厚奖励",
            red_shape=1
        },
        [10020]={
            act_type=10020,
            act_seq=8,
            icon_id="a1001",
            name_text="门派任务",
            title=3,
            position=2,
            content_text="灵活运用智慧与战力，完成每日的门派任务，获得丰厚奖励！"
        },
        [10001]={
            act_type=10001,
            act_seq=9,
            is_show=0,
            icon_id="a1000",
            name_text="缉捕盗贼",
            fun_name=5012,
            title=3,
            position=1,
            recommend_text="皇城",
            level_restrict=25,
            content_text="抓捕各地的盗贼，为民除害"
        },
        [10042]={
            act_type=10042,
            act_seq=2,
            icon_id="a10042",
            name_text="九州秘宝",
            title=1,
            position=2,
            level_restrict=31,
            open_day=7,
            content_text="在场景中探索隐藏在各处的珍珑秘宝匣，获得九州秘宝"
        },
        [10025]={
            act_type=10025,
            act_seq=12,
            icon_id="a1018",
            title=3,
            level_restrict=31,
            content_text="参加活动，对战赢取奖励"
        },
        [10007]={
            act_type=10007,
            act_seq=13,
            icon_id="a1033",
            name_text="锢魔之塔",
            fun_name=93,
            title=3,
            position=7,
            level_restrict=45,
            content_text="单人任务，进入百层妖塔，降服塔内驻扎的妖兽，层数越高妖兽越强，奖励随之越丰厚",
            red_shape=1,
            btn_type=2
        },
        [1]={
            act_type=1,
            icon_id="a1002",
            name_text="魔将入侵",
            activity_group=2,
            position=3,
            recommend_text="世界地图查看位置",
            number_min=3,
            number_max=5,
            is_team=1,
            time_text="周一至周五12:00-12:20",
            open_day="1:2:3:4:5",
            begin_time="12:00",
            end_time="12:20",
            content_text="组队抵抗随机入侵到各地的强力妖兽，参与讨伐者可获得丰厚的奖励",
            is_push_show=1,
            content_tip=97
        },
        [10011]={
            act_type=10011,
            icon_id="a1010",
            name_text="商人的烦恼",
            fun_name=4,
            title=2,
            position=11,
            recommend_text="皇城",
            level_restrict=45,
            time_text="45级每周50环；50级每周100环；60级每周150环",
            content_text="单人多环任务，可获得大量经验",
            red_shape=1,
            btn_type=2
        },
        [10010]={
            act_type=10010,
            act_seq=15,
            icon_id="a1035",
            name_text="远征魔冢（组队）",
            fun_name=111,
            title=2,
            position=10,
            recommend_text="皇城",
            level_restrict=47,
            number_max=5,
            is_team=1,
            content_text="完成远征任务，解锁被封印的魔之禁地。赢得象征荣耀的令牌，谱写史诗篇章",
            red_shape=1
        },
        [10]={
            act_type=10,
            act_seq=16,
            icon_id="a1025",
            name_text="巨龙来袭",
            activity_group=2,
            number_max=5,
            is_team=1,
            time_text="周六、周日12:00-12:20",
            open_day="6:7",
            begin_time="12:00",
            end_time="12:20",
            content_text="组队抵抗突破封印的上古魔龙，参与讨伐者可获得丰厚的奖励",
            is_push_show=1,
            content_tip=98
        },
        [10028]={
            act_type=10028,
            act_seq=16,
            is_show=0,
            name_text="勇闯地宫（限时）",
            fun_name=90,
            title=0,
            activity_group=2,
            recommend_text="皇城",
            number_max=5,
            is_team=1,
            time_text="周日14:00~24:00",
            open_day=7,
            begin_time="14:00",
            content_text="本次活动所到达的层数越高，排名越靠前，相应的奖励越丰厚",
            content_tip=320
        },
        [4]={
            act_type=4,
            act_seq=17,
            name_text="勇闯地宫",
            fun_name=90,
            activity_group=2,
            recommend_text="皇城",
            number_max=5,
            is_team=1,
            time_text="周日14:00~21:00",
            open_day=7,
            begin_time="14:00",
            end_time="21:00",
            content_text="本次活动所到达的层数越高，排名越靠前，相应的奖励越丰厚",
            is_push_show=1,
            red_shape=1,
            content_tip=320
        },
        [9]={
            act_type=9,
            act_seq=17,
            icon_id="a1024",
            name_text="家族答题",
            activity_group=2,
            number_max=5,
            time_text="周一、三、五19:30",
            open_day="1:3:5",
            begin_time="19:30",
            end_time="19:40",
            content_text="是时候展示真正的技术了！学识渊博的你快去解答各种谜题，赢取奖励吧！",
            is_push_show=1,
            content_tip=96
        },
        [19]={
            act_type=19,
            act_seq=18,
            icon_id="a1059",
            name_text="挑战心灵之境",
            title=3,
            level_restrict=32,
            content_text="修行之路，坎坷重重，击败内心的魔障，方能臻至巅峰！",
            cross_service=1
        },
        [3]={
            act_type=3,
            act_seq=19,
            icon_id="a1014",
            name_text="迷宫竞速",
            fun_name=4,
            activity_group=2,
            position=14,
            recommend_text="皇城",
            number_min=3,
            number_max=5,
            is_team=1,
            time_text="周二、四19:30",
            open_day="2:4",
            begin_time="19:30",
            end_time="20:15",
            content_text="组队进入错综复杂的迷宫之中，用谋略争取以最快时间通关。通关时间越短，排名越靠前",
            is_push_show=1,
            content_tip=11
        },
        [10027]={
            act_type=10027,
            act_seq=19,
            icon_id="a1028",
            name_text="野外首领（组队）",
            fun_name=111,
            title=2,
            position=10,
            recommend_text="野外",
            number_min=3,
            number_max=5,
            is_team=1,
            content_text="结伴同行，训练默契，共御魔兽。利用完美配合，保卫人族领地！",
            red_shape=1
        },
        [8]={
            act_type=8,
            act_seq=20,
            icon_id="a1021",
            name_text="家族荣誉战",
            fun_name=8,
            activity_group=2,
            number_max=5,
            time_text="周六21:00",
            open_day=6,
            begin_time="21:00",
            end_time="21:45",
            content_text="为了你的家族荣誉而战吧！",
            is_push_show=1,
            red_shape=1,
            content_tip=95
        },
        [6]={
            act_type=6,
            act_seq=21,
            icon_id="a1012",
            name_text="首席竞选",
            fun_name=4,
            title=3,
            activity_group=2,
            position=13,
            recommend_text="皇城",
            time_text="周日21:00",
            open_day=7,
            begin_time="21:00",
            end_time="22:00",
            content_text="限时活动，从各职业报名玩家中选出战斗力名列前茅者参与首席竞选，参与者皆可获得丰厚的奖励",
            is_push_show=1,
            content_tip=88
        },
        [7]={
            act_type=7,
            act_seq=22,
            is_show=0,
            icon_id="a1011",
            name_text="首席巅峰战",
            fun_name=4,
            title=3,
            activity_group=2,
            recommend_text="皇城",
            time_text="周日21:00",
            open_day=7,
            begin_time="21:00",
            end_time="21:45",
            content_text="限时活动，各路强者们通过首席比拼争夺全服最强首席",
            btn_type=0
        },
        [11]={
            act_type=11,
            act_seq=23,
            icon_id="a1031",
            name_text="以一敌百",
            fun_name=5,
            title=3,
            activity_group=2,
            time_text="周五21:00",
            open_day=5,
            begin_time="21:00",
            end_time="21:45",
            content_text="百人竞技，谁会是最后的王者",
            is_push_show=1,
            red_shape=1,
            content_tip=50
        },
        [5]={
            act_type=5,
            act_seq=24,
            icon_id="a1018",
            name_text="家族大乱斗",
            fun_name=5,
            activity_group=2,
            recommend_text="家族驻地",
            number_max=5,
            is_team=1,
            time_text="周二、四21:00-21:45",
            open_day="2:4",
            begin_time="21:00",
            end_time="21:45",
            content_text="家族活动，与各家族玩家一起角逐最强家族称号",
            is_push_show=1,
            red_shape=1,
            content_tip=14
        },
        [2]={
            act_type=2,
            act_seq=25,
            icon_id="a1015",
            name_text="竞技对抗赛",
            fun_name=100,
            activity_group=2,
            position=15,
            recommend_text="皇城",
            number_max=3,
            is_team=1,
            time_text="周一21:00-21:30",
            open_day=1,
            begin_time="21:00",
            end_time="21:30",
            content_text="合理搭配不同职业的队友，利用毕生所学与未知的对手斗智斗勇，胜者奖励丰厚",
            is_push_show=1,
            content_tip=94,
            cross_service=1
        },
        [10016]={
            act_type=10016,
            act_seq=26,
            icon_id="a1019",
            title=0,
            activity_group=3,
            level_restrict=31,
            content_text="参加活动，对战赢取奖励"
        },
        [10032]={
            act_type=10032,
            act_seq=27,
            icon_id="a1039",
            name_text="穹顶之争",
            title=0,
            activity_group=3,
            level_restrict=45,
            content_text="各服高手齐聚于此，谁能登顶斗战殿堂",
            red_shape=1
        },
        [10034]={
            act_type=10034,
            act_seq=27,
            icon_id="a1039",
            name_text="穹顶之争",
            title=0,
            level_restrict=45,
            content_text="各服高手齐聚于此，谁能登顶斗战殿堂",
            red_shape=1
        },
        [10018]={
            act_type=10018,
            act_seq=28,
            icon_id="a1026",
            name_text="五方擂台",
            title=0,
            activity_group=3,
            level_restrict=65,
            content_text=""
        },
        [12]={
            act_type=12,
            act_seq=29,
            icon_id="a1032",
            name_text="幻界战场",
            title=3,
            activity_group=2,
            level_restrict=70,
            time_text="周二、四22:00~22:45",
            open_day="2:4",
            begin_time="22：00",
            end_time="22：45",
            content_text="睥睨三界凭天怒，纵横风云我一人。这是三界有史以来最大的武学盛典，全服高手汇聚一堂，争夺至高荣耀！",
            is_push_show=1,
            content_tip=65
        },
        [10026]={
            act_type=10026,
            act_seq=29,
            icon_id="a1032",
            name_text="幻界战场",
            title=0,
            activity_group=3,
            level_restrict=70,
            number_max=3,
            time_text="周二、四22:00~22:45",
            open_day="2:4",
            begin_time="22：00",
            end_time="22：45",
            content_text="睥睨三界凭天怒，纵横风云我一人。这是三界有史以来最大的武学盛典，全服高手汇聚一堂，争夺至高荣耀！",
            content_tip=65
        },
        [10024]={
            act_type=10024,
            act_seq=30,
            is_show=0,
            icon_id="a1023",
            name_text="家族试炼",
            title=3,
            level_restrict=35,
            content_text="与家族成员一同挑战试炼boss，每日3次，击败boss可获得丰厚奖励",
            cross_service=1
        },
        [10002]={
            act_type=10002,
            act_seq=31,
            is_show=0,
            icon_id="a1001",
            name_text="门派任务",
            fun_name=4,
            position=2,
            recommend_text="职业门派",
            number_max=5,
            is_team=1,
            content_text="此为门派发布给门派各学徒的每日修行任务，完成可以获得门派派发的奖励"
        },
        [10006]={
            act_type=10006,
            act_seq=32,
            is_show=0,
            icon_id="a1005",
            name_text="许愿池",
            fun_name=71,
            title=3,
            position=6,
            recommend_text="皇城",
            level_restrict=24,
            content_text="以虔诚之心祈愿，以沐虔诚之魂",
            red_shape=1,
            btn_type=2
        },
        [10014]={
            act_type=10014,
            act_seq=33,
            is_show=0,
            icon_id="a1016",
            name_text="挑战秘境",
            fun_name=5040,
            title=0,
            activity_group=3,
            level_restrict=50,
            number_min=3,
            number_max=5,
            is_team=1,
            time_text="每周一次",
            content_text="击败秘境关卡中的BOSS，有机会得到BOSS身上掉落的奇珍异宝"
        },
        [10015]={
            act_type=10015,
            act_seq=34,
            is_show=0,
            icon_id="a1017",
            name_text="挑战任务",
            fun_name=5045,
            title=0,
            activity_group=3,
            level_restrict=38,
            number_max=5,
            is_team=1,
            content_text="内含数个难度较高的挑战任务，有铜币以及元宝等诱人的丰厚奖励",
            cross_service=1
        },
        [10017]={
            act_type=10017,
            act_seq=35,
            is_show=0,
            icon_id="a1020",
            name_text="情缘任务",
            fun_name=4,
            level_restrict=35,
            number_max=2,
            is_team=1,
            content_text="专属于夫妻二人的任务，需要两人携手共同完成"
        },
        [10019]={
            act_type=10019,
            act_seq=36,
            is_show=0,
            icon_id="a1022",
            name_text="家族任务",
            title=3,
            level_restrict=22,
            time_text="周一至周五",
            open_day="1:2:3:4:5",
            content_text="每天与家族成员一起完成任务目标，每周完成的次数越多，周六结算奖励越多，加油！"
        },
        [10023]={
            act_type=10023,
            act_seq=37,
            is_show=0,
            icon_id="a1028",
            name_text="巡逻",
            fun_name=5064,
            title=3,
            level_restrict=1,
            number_max=5,
            content_text="找到隐藏于各地的怪物，消灭它们获得战斗经验"
        },
        [10037]={
            act_type=10037,
            act_seq=38,
            icon_id="a1016",
            name_text="山海降妖（组队）",
            fun_name=31009,
            position=12,
            recommend_text="野外",
            level_restrict=51,
            number_min=3,
            number_max=5,
            is_team=1,
            time_text="每天08:00-次日02:00",
            content_text="山海精怪，上古魔神，携手挑战最强BOSS，赢取奇珍异宝"
        },
        [10031]={
            act_type=10031,
            act_seq=40,
            icon_id="a1036",
            name_text="消耗100点体力",
            title=3,
            content_text="挑战上古秘境，赢取丰厚奖励",
            red_shape=1
        },
        [10033]={
            act_type=10033,
            act_seq=41,
            icon_id="a1009",
            name_text="轮回忘川",
            title=0,
            level_restrict=53,
            content_text="轮回有道，忘川有灵，完成忘川的试炼，可的获得忘川的馈赠。",
            red_shape=1
        },
        [10036]={
            act_type=10036,
            act_seq=42,
            icon_id="a1041",
            name_text="幽冥炼狱",
            fun_name=31011,
            title=2,
            level_restrict=73,
            content_text="与宠物、伙伴协同作战，挑战幽冥炼狱中的魔将，赢取丰厚奖励",
            red_shape=1
        },
        [14]={
            act_type=14,
            act_seq=43,
            icon_id="a1045",
            name_text="百鬼夜行",
            activity_group=2,
            time_text="周一、三、五 22:00",
            open_day="1:3:5",
            begin_time="22:00",
            end_time="22:30",
            content_text="夜幕已至，冥府洞开，百鬼降临玄都。组队击败入侵玄都的妖鬼邪祟，高概率获得神兽之魂！",
            is_push_show=1,
            red_shape=1,
            content_tip=152
        },
        [10039]={
            act_type=10039,
            act_seq=43,
            icon_id="a1004",
            name_text="声望任务",
            fun_name=31012,
            title=3,
            level_restrict=31,
            content_text="仁义之心，日月可鉴。协助伍长完成诸多事宜，即可获得大量声望。",
            red_shape=1,
            cross_service=1
        },
        [10040]={
            act_type=10040,
            act_seq=44,
            icon_id="a1017",
            name_text="北斗七星",
            fun_name=31014,
            title=1,
            level_restrict=53,
            number_min=3,
            number_max=5,
            is_team=1,
            time_text="星君每天开启一位，帝君周五开启",
            content_text="七星耀世，帝镇北斗。挑战北斗七星，获取强大宠物魂器",
            red_shape=1
        },
        [10041]={
            act_type=10041,
            act_seq=45,
            icon_id="a10041",
            name_text="万灵话本",
            fun_name=31038,
            number_min=3,
            number_max=5,
            is_team=1,
            time_text="每天可参加1次",
            content_text="组队任务，观看人物外传，完成副本后可获得大量装备，更有机会获得神装材料"
        },
        [15]={
            act_type=15,
            act_seq=46,
            icon_id="a10041",
            name_text="丝绸之路",
            fun_name=124001,
            title=2,
            activity_group=2,
            time_text="周五、六14:00-16:00",
            open_day="5:6",
            begin_time="14:00",
            end_time="16:00",
            content_text="丝绸之路，贸易通南北。",
            is_push_show=1,
            red_shape=1,
            content_tip=191
        },
        [10043]={
            act_type=10043,
            act_seq=47,
            icon_id="a10043",
            name_text="寻仙问道",
            title=1,
            position=2,
            level_restrict=90,
            content_text="单人多环任务，每环可获得物品奖励",
            cross_service=1
        },
        [10045]={
            act_type=10045,
            act_seq=48,
            icon_id="a10044",
            name_text="论剑九州",
            title=0,
            activity_group=3,
            position=2,
            level_restrict=80,
            content_text="吾辈侠客，忠肝义胆，三尺青峰，论剑九州！",
            is_push_show=1,
            content_tip=257
        },
        [10046]={
            act_type=10046,
            act_seq=49,
            icon_id="a10046",
            name_text="殒神之地",
            title=2,
            level_restrict=75,
            number_min=3,
            number_max=5,
            is_team=1,
            open_day="5:6:7",
            content_text="神体有终，魂存万世。接受神之魂灵的试炼，即可获得丰厚的奖励！",
            red_shape=1,
            cross_service=1
        },
        [13]={
            act_type=13,
            act_seq=50,
            icon_id="a1038",
            name_text="遗迹夺宝",
            fun_name=31006,
            activity_group=2,
            position=16,
            level_restrict=32,
            number_max=3,
            is_team=1,
            time_text="周三21:00",
            open_day=3,
            begin_time="21:00",
            end_time="21:45",
            content_text="上古遗迹，重现于世，用全新的身份获取胜利，即可获得丰厚的奖励！",
            is_push_show=1,
            red_shape=1,
            content_tip=129,
            cross_service=1
        },
        [16]={
            act_type=16,
            act_seq=51,
            icon_id="a8888",
            name_text="英雄会武",
            title=6,
            activity_group=2,
            position=2,
            level_restrict=85,
            number_max=5,
            content_text="各位修炼者可组成战队报名参与“英雄会武”，与全服战队一较高下！并且可获得竞争“天下第一”之名的资格",
            is_push_show=1,
            content_tip=310,
            cross_service=1
        },
        [10047]={
            act_type=10047,
            act_seq=53,
            icon_id="a9999",
            name_text="天下第一比武大会",
            title=0,
            activity_group=3,
            position=2,
            level_restrict=85,
            number_max=5,
            content_text="“天下第一比武大会”每月开启一次，所有服务器共同角逐冠军。今日，我们便要了这“天下第一”的虚名！每个跨服战区“英雄会武”最终排名前十的战队，拥有“天下第一比武大会”的参赛资格",
            is_push_show=1,
            content_tip=205,
            cross_service=""
        },
        [10048]={
            act_type=10048,
            act_seq=52,
            icon_id="a8888",
            name_text="英雄会武",
            title=0,
            activity_group=3,
            position=2,
            level_restrict=85,
            number_max=5,
            content_text="各位修炼者可组成战队报名参与“英雄会武”，与全服战队一较高下！并且可获得竞争“天下第一”之名的资格",
            is_push_show=1,
            content_tip=310,
            cross_service=""
        },
        [10049]={
            act_type=10049,
            act_seq=54,
            icon_id="a9999",
            name_text="天下第一比武大会",
            title=6,
            activity_group=2,
            position=2,
            level_restrict=85,
            number_max=5,
            content_text="“天下第一比武大会”每月开启一次，所有服务器共同角逐冠军。今日，我们便要了这“天下第一”的虚名！每个跨服战区“英雄会武”最终排名前十的战队，拥有“天下第一比武大会”的参赛资格",
            is_push_show=1,
            content_tip=205,
            cross_service=1
        },
        [10050]={
            act_type=10050,
            act_seq=55,
            icon_id="a1060",
            name_text="鸿蒙天界",
            level_restrict=90,
            number_min=3,
            number_max=5,
            content_text="鸿蒙天界乃初始之地，一切都笼罩在混沌无序之中，击败鸿蒙天界的生灵，获得全新的装备！",
            is_push_show=1,
            cross_service=1
        },
        [18]={
            act_type=18,
            icon_id="a1062",
            name_text="星官降临",
            activity_group=2,
            position=3,
            recommend_text="世界地图查看位置",
            level_restrict=77,
            number_min=3,
            number_max=5,
            is_team=1,
            time_text="周一至周日19:00-19:20",
            begin_time="19:00",
            end_time="19:20",
            content_text="组队挑战随机降临到各地的星官，参与挑战可获得丰厚的奖励",
            is_push_show=1,
            content_tip=351
        },
        [10051]={
            act_type=10051,
            act_seq=56,
            icon_id="a10051",
            name_text="神域",
            fun_name=161001,
            title=0,
            activity_group=2,
            level_restrict=85,
            is_push_show=1,
            cross_service=1
        },
        [10052]={
            act_type=10052,
            act_seq=57,
            icon_id="a10052",
            name_text="归墟之境",
            title=0,
            activity_group=2,
            level_restrict=85,
            is_push_show=1,
            cross_service=1
        },
        [10053]={
            act_type=10053,
            act_seq=58,
            icon_id="a10053",
            name_text="阵营神兽",
            title=0,
            activity_group=2,
            level_restrict=85,
            is_push_show=1,
            cross_service=1
        },
        [10054]={
            act_type=10054,
            act_seq=59,
            icon_id="YunDingTianGong",
            name_text="云顶天宫",
            title=0,
            activity_group=2,
            level_restrict=85,
            is_push_show=1,
            cross_service=1
        }
    },
    activity_label_show={
        {
            label_seq=1,
            label_name="高收益"
        },
        {
            label_seq=2,
            label_name="经验",
            label_color=2
        },
        {
            label_seq=3,
            label_name="铜币",
            label_color=3
        },
        {
            label_seq=4,
            label_name="道具"
        },
        {
            label_seq=5,
            label_name="贡献",
            label_color=2
        },
        {
            label_seq=6,
            label_name="封印卡",
            label_color=3
        },
        {
            label_seq=7,
            label_name="料理"
        },
        {
            label_seq=8,
            label_name="属性",
            label_color=2
        },
        {
            label_seq=9,
            label_name="称号",
            label_color=3
        },
        {
            label_seq=10,
            label_name="声望"
        },
        {
            label_seq=11,
            label_name="宝石"
        },
        {
            label_seq=12,
            label_name="魔币",
            label_color=3
        },
        {
            label_seq=13,
            label_name="高经验",
            label_color=2
        },
        {
            label_seq=14,
            label_name="伙伴",
            label_color=2
        },
        {
            label_seq=15,
            label_name="状态",
            label_color=2
        },
        {
            label_seq=16,
            label_name="灵饰"
        },
        {
            label_seq=17,
            label_name="封印石",
            label_color=4
        },
        {
            label_seq=18,
            label_name="材料"
        },
        {
            label_seq=19,
            label_name="藏宝图"
        },
        {
            label_seq=20,
            label_name="图鉴卡",
            label_color=5
        },
        {
            label_seq=21,
            label_name="命格卡"
        },
        {
            label_seq=22,
            label_name="五珍"
        },
        {
            label_seq=23,
            label_name="资金"
        },
        {
            label_seq=24,
            label_name="宝箱",
            label_color=5
        },
        {
            label_seq=25,
            label_name="祈福币"
        },
        {
            label_seq=26,
            label_name="令牌"
        },
        {
            label_seq=27,
            label_name="灵骑"
        },
        {
            label_seq=28,
            label_name="装备"
        },
        {
            label_seq=29,
            label_name="铸灵"
        },
        {
            label_seq=30,
            label_name="灵玉",
            label_color=2
        },
        {
            label_seq=31,
            label_name="魂器"
        }
    },
    activity_type_cfg={
        {
            activity_seq=1,
            activity_type_name="全部"
        },
        {
            activity_seq=2,
            activity_type_name="高收益"
        },
        {
            activity_seq=3,
            activity_type_name="经验"
        },
        {
            activity_seq=4,
            activity_type_name="铜币"
        },
        {
            activity_seq=5,
            activity_type_name="材料"
        },
        {
            activity_seq=6,
            activity_type_name="道具"
        },
        {
            activity_seq=7,
            activity_type_name="其他"
        }
    },
    week_time={
        [1]={
            time_seq=1,
            act_show_time="12:00",
            week_1="魔将入侵",
            act_id_1=1,
            week_2="魔将入侵",
            act_id_2=1,
            week_3="魔将入侵",
            act_id_3=1,
            week_4="魔将入侵",
            act_id_4=1,
            week_5="魔将入侵",
            act_id_5=1,
            week_6="巨龙来袭",
            act_id_6=10,
            week_7="巨龙来袭",
            act_id_7=10
        },
        [2]={
            time_seq=2,
            act_show_time="14:00",
            week_1="",
            act_id_1="",
            week_2="",
            act_id_2="",
            week_3="",
            act_id_3="",
            week_4="",
            act_id_4="",
            week_5="丝绸之路",
            act_id_5=15,
            week_6="丝绸之路",
            act_id_6=15,
            week_7="勇闯地宫",
            act_id_7=4
        },
        [3]={
            time_seq=3,
            act_show_time="19:00",
            week_1="星官降临",
            act_id_1=18,
            week_2="星官降临",
            act_id_2=18,
            week_3="星官降临",
            act_id_3=18,
            week_4="星官降临",
            act_id_4=18,
            week_5="星官降临",
            act_id_5=18,
            week_6="星官降临",
            act_id_6=18,
            week_7="星官降临",
            act_id_7=18
        },
        [4]={
            time_seq=4,
            act_show_time="19:30",
            week_1="家族答题",
            act_id_1=9,
            week_2="迷宫竞速",
            act_id_2=5,
            week_3="家族答题",
            act_id_3=9,
            week_4="迷宫竞速",
            act_id_4=5,
            week_5="家族答题",
            act_id_5=9
        },
        [5]={
            time_seq=5,
            act_show_time="21:00",
            week_1="竞技对抗赛",
            act_id_1=2,
            week_2="家族大乱斗",
            act_id_2=13,
            week_3="遗迹夺宝",
            act_id_3=2,
            week_4="家族大乱斗",
            act_id_4=3,
            week_5="以一敌百",
            act_id_5=11,
            week_6="家族荣誉战",
            act_id_6=8,
            week_7="首席竞选",
            act_id_7=6
        },
        [6]={
            time_seq=6,
            act_show_time="22:00",
            week_1="百鬼夜行",
            act_id_1=14,
            week_2="幻界战场",
            act_id_2=12,
            week_3="百鬼夜行",
            act_id_3=14,
            week_4="幻界战场",
            act_id_4=12,
            week_5="百鬼夜行",
            act_id_5=14
        }
    },
    effect_show={
        [10007]={
            act_type=10007,
            effect_id=10010316
        },
        [10016]={
            act_type=10016,
            effect_id=10010317
        },
        [10015]={
            act_type=10015,
            effect_id=10010318
        },
        [10010]={
            act_type=10010,
            effect_id=10010319
        },
        [10014]={
            act_type=10014,
            effect_id=0
        },
        [10018]={
            act_type=10018,
            effect_id=10010320
        },
        [10026]={
            act_type=10026,
            effect_id=10010852
        },
        [10032]={
            act_type=10032,
            effect_id=2166004
        },
        [16]={
            act_type=16
        },
        [10047]={
            act_type=10047,
            effect_id=3165097
        },
        [10048]={
            act_type=10048
        },
        [10049]={
            act_type=10049,
            effect_id=3165097
        }
    },
    sign_up={
        {
            seq=0,
            activity_id=1,
            reward_item={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            seq=1,
            activity_id=2,
            reward_item={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            seq=2,
            activity_id=3,
            reward_item={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            seq=3,
            activity_id=5,
            reward_item={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            seq=4,
            activity_id=8,
            reward_item={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            seq=5,
            activity_id=9,
            reward_item={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            seq=6,
            activity_id=10,
            reward_item={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            seq=7,
            activity_id=11,
            reward_item={
                [0]=_itemlist.i_27398_1_1
            }
        }
    },
    reward_show={
        {
            max_level=44,
            activity_type="1,2,4,6",
            label_show="4,3",
            reward_id="65532:27494:28507:65545:65539"
        },
        {
            min_level=45,
            activity_type="1,2,4,6",
            label_show="4,3",
            reward_id="65532:27494:28507:65545:65555"
        },
        {
            act_type=2,
            activity_type="1,2,3,4",
            label_show="2,3,22",
            reward_id="65535:65532:65595"
        },
        {
            act_type=3,
            max_level=49,
            activity_type="1,2",
            label_show="1,11"
        },
        {
            act_type=3,
            min_level=50,
            activity_type="1,2",
            label_show="1,17"
        },
        {
            act_type=4,
            activity_type="1,2",
            label_show="1,10",
            reward_id="24518:23941:29005:28516:24557:65532"
        },
        {
            act_type=5,
            label_show="23,5,9",
            reward_id="65535:65532:65536:65605:65549:65551"
        },
        {
            act_type=6,
            activity_type="1,2",
            label_show="4,9",
            reward_id="65551:65591"
        },
        {
            act_type=7,
            activity_type="1,2",
            label_show="1,4,9",
            reward_id="65532:65551:65591"
        },
        {
            act_type=8,
            label_show="23,5,9",
            reward_id="65532:65536:65605:65546:65551"
        },
        {
            act_type=9,
            label_show="23,5,17",
            reward_id="65535:65532:65536:65605:31249::65550:65549"
        },
        {
            act_type=10,
            max_level=44,
            label_show="3,18",
            reward_id="65532:27494:65545:65549:65595"
        },
        {
            act_type=10,
            min_level=45,
            label_show="3,18,20",
            reward_id="65532:27494:65545:65549:65595:65555"
        },
        {
            act_type=11,
            max_level=49,
            label_show="2,3,9",
            reward_id="65535:65532:65551"
        },
        {
            act_type=11,
            min_level=50,
            label_show="2,3,9",
            reward_id="65535:65532:65551:65555"
        },
        {
            act_type=12,
            activity_type="1,3,4",
            reward_id="23907:23908:25700:27399"
        },
        {
            act_type=18,
            min_level=77,
            activity_type="1,2,4,6",
            label_show="1,4",
            reward_id="56334:56365:56369"
        },
        {
            act_type=10037,
            activity_type="1,2,4,6",
            label_show="21,27",
            reward_id="65683:26404:26411:26403:26402:26401:65532"
        },
        {
            act_type=10024,
            label_show="23,5,3",
            reward_id="65532:65536:65605:65552"
        },
        {
            act_type=10001,
            max_level=39,
            activity_type="1,2,3,4",
            label_show="2,3",
            reward_id="65535:65532"
        },
        {
            act_type=10001,
            min_level=40,
            activity_type="1,2,3,4",
            label_show="2,3,19",
            reward_id="65535:65532:65590"
        },
        {
            act_type=10002,
            activity_type="1,2,3,4",
            label_show="2,10",
            reward_id="65535:65532:65550"
        },
        {
            act_type=10004,
            activity_type="1,2,4,6",
            label_show="10,17",
            reward_id="65532:56605:56606:56626"
        },
        {
            act_type=10006,
            activity_type="1,2,3,4,",
            label_show="2,3,15",
            reward_id="65532:65535:65557:65552"
        },
        {
            act_type=10007,
            activity_type="1,2,4,6",
            reward_id="65532:65552:65550:65543"
        },
        {
            act_type=10008,
            activity_type="1,2,4,",
            label_show=3,
            reward_id="65532:65593"
        },
        {
            act_type=10009,
            activity_type="1,2,3,6",
            label_show=13,
            reward_id="65535:65552:65543:56318"
        },
        {
            act_type=10010,
            activity_type="1,2,3,4,6",
            label_show="26,2,3",
            reward_id="65596:65545:65535:65532:65544"
        },
        {
            act_type=10011,
            max_level=49,
            activity_type="1,6",
            label_show="4,20",
            reward_id="56318:24518:22053:22099:65535:24557:26813:65561:65563"
        },
        {
            act_type=10011,
            min_level=50,
            activity_type="1,6",
            label_show="4,20",
            reward_id="56318:24518:22053:22099:65535:24557:26813:65561:65563:65555"
        },
        {
            act_type=10014,
            activity_type="1,2",
            label_show="2,3,4",
            reward_id="65532:65545:65555"
        },
        {
            act_type=10015,
            activity_type="1,2",
            label_show="2,3,4",
            reward_id="65549:65539:65550:65551"
        },
        {
            act_type=10016,
            activity_type="1,4",
            reward_id="65532:65567:56318"
        },
        {
            act_type=10017,
            activity_type="1,4,7",
            reward_id=65532
        },
        {
            act_type=10018,
            label_show="4,5",
            reward_id="27974:27576:65568"
        },
        {
            act_type=10019,
            label_show="4,5,23",
            reward_id="65536:65544"
        },
        {
            act_type=10020,
            activity_type="1,2,3,4",
            label_show="2,4",
            reward_id="65535:65532:56318:65950"
        },
        {
            act_type=10022,
            activity_type="1,2,3,4",
            label_show="2,3,18",
            reward_id="65535:65532:65545:65549"
        },
        {
            act_type=10023,
            activity_type="1,2",
            label_show="2,10",
            reward_id=65535
        },
        {
            act_type=10025,
            activity_type="1,4",
            reward_id="65532:65567"
        },
        {
            act_type=10026,
            activity_type="1,3,4",
            reward_id="65604:26404:26403:26411:26402"
        },
        {
            act_type=10027,
            activity_type="1,2,4,6",
            label_show="28,20",
            reward_id="65532:26226:26229:26224:65767:65769:65555:65546:56318"
        },
        {
            act_type=10028,
            activity_type="1,2",
            label_show="1,17",
            reward_id="65535:65532:65550:65543"
        },
        {
            act_type=10030,
            activity_type="1,2,6",
            label_show="1,4,14",
            reward_id="65548:65607:65620:27575"
        },
        {
            act_type=10031,
            activity_type="1,2,4",
            label_show="1,2,4",
            reward_id="65543:65555:65547"
        },
        {
            act_type=10032,
            activity_type="1,4",
            reward_id="65682:25862:28516:25542"
        },
        {
            act_type=10033,
            activity_type="1,4,5,6",
            label_show="3,4,18",
            reward_id="26412:26413:26414:26415:26420"
        },
        {
            act_type=10034,
            activity_type="1,4",
            reward_id="65682:25862:28516:25542"
        },
        {
            act_type=10035,
            activity_type="1,5,6",
            label_show="18,28,20",
            reward_id="65697:65545:65555"
        },
        {
            act_type=10036,
            activity_type="1,2,6",
            label_show=29,
            reward_id="65716:65717"
        },
        {
            act_type=14,
            activity_type="1,2,4,6",
            label_show="2,4,6",
            reward_id="65548:65607:65620:27575"
        },
        {
            act_type=10039,
            activity_type="1,2,4",
            label_show="1,10",
            reward_id="65561:65532"
        },
        {
            act_type=10040,
            activity_type="1,2,6",
            label_show="1,31",
            reward_id="27723:27724"
        },
        {
            act_type=10041,
            activity_type="1,3,4,5",
            label_show="1,28,2",
            reward_id="26229:65697:65535:65532:56318"
        },
        {
            act_type=15,
            activity_type="1,2,4",
            label_show="1,3",
            reward_id="22050:65532"
        },
        {
            act_type=10042,
            activity_type="1,2",
            label_show="1,11,25",
            reward_id="65808:65809:27399"
        },
        {
            act_type=10043,
            activity_type="5,6",
            label_show="1,4",
            reward_id="27850:22014"
        },
        {
            act_type=10044,
            activity_type="2,6",
            label_show="4,30",
            reward_id="28522:25842:27403"
        },
        {
            act_type=10045,
            activity_type="1,2,6",
            label_show="4,30",
            reward_id="27974:25542:24518"
        },
        {
            act_type=10046,
            activity_type="1,2,6",
            label_show="1,31",
            reward_id="27723:27724:31245"
        },
        {
            act_type=13,
            activity_type="1,2,4,6",
            label_show="4,6",
            reward_id="24518:28516:65532"
        },
        {
            act_type=16,
            activity_type="2,6",
            label_show="1,4",
            reward_id="28677:25542:28676"
        },
        {
            act_type=10047,
            activity_type="1,2,6",
            label_show="1,4",
            reward_id="50240:28916:40050:25542"
        },
        {
            act_type=10048,
            activity_type="1,2,6",
            label_show="1,4",
            reward_id="28677:25542:28676"
        },
        {
            act_type=10049,
            activity_type="1,2,6",
            label_show="1,4",
            reward_id="50240:28916:40050:25542"
        },
        {
            act_type=19,
            activity_type="3,6",
            label_show="1,2,4",
            reward_id="65535:26812:26393"
        },
        {
            act_type=10050,
            activity_type="1,28,18",
            label_show="28,18",
            reward_id="65898:65897:26773:26687"
        }
    },
    activity_show={
        {
            act_type=1,
            activity_show=97,
            reward_id="22051:28516:24572",
            reward_desc="参与讨伐魔将入侵，有机会获得<color=#BA6908>伙伴属性丹、稀世五珍、魔将图鉴卡</color>等珍贵奖励！少侠不去试试吗？"
        },
        {
            act_type=2,
            activity_show=94,
            reward_desc="参与竞技对抗赛，有机会获得<color=#BA6908>宠物属性丹、高级技能书、高级藏宝图</color>等珍贵奖励！少侠不去试试吗？"
        },
        {
            act_type=3,
            activity_show=11,
            reward_id="22051:28700",
            reward_desc="参与迷宫竞速，有机会获得<color=#BA6908>伙伴属性丹、高级装备材料</color>等珍贵奖励！少侠不去试试吗？"
        },
        {
            act_type=5,
            activity_show=14,
            reward_desc="参与家族大乱斗，有机会获得<color=#BA6908>宠物属性丹、高级技能书、高级藏宝图</color>等珍贵奖励！少侠不去试试吗？"
        },
        {
            act_type=6,
            activity_show=88,
            reward_id="27821:24518:24557",
            reward_desc="参与首席竞选，有机会获得<color=#BA6908>角色属性丹、高级技能书、高级藏宝图</color>等珍贵奖励！少侠不去试试吗？"
        },
        {
            act_type=8,
            activity_show=95,
            reward_id="27821:25864:24518:24557",
            reward_desc="参与家族荣誉战，有机会获得<color=#BA6908>角色属性丹、荣耀礼盒、高级技能书、高级藏宝图</color>等珍贵奖励！少侠不去试试吗？"
        },
        {
            act_type=9,
            activity_show=96,
            reward_id="22051:28516:65536",
            reward_desc="参与家族答题，有机会获得<color=#BA6908>伙伴属性丹、稀世五珍</color>等珍贵奖励，以及大量家族贡献！少侠不去试试吗？"
        },
        {
            act_type=10,
            activity_show=98,
            reward_id="22051:28516:24405",
            reward_desc="参与对抗巨龙来袭，有机会获得<color=#BA6908>伙伴属性丹、稀世五珍、巨龙图鉴卡</color>等珍贵奖励！少侠不去试试吗？"
        },
        {
            act_type=11,
            activity_show=50,
            reward_desc="参与以一敌百，有机会获得<color=#BA6908>宠物属性丹、高级技能书、高级藏宝图</color>等珍贵奖励！少侠不去试试吗？"
        },
        {
            act_type=14,
            activity_show=152,
            reward_id="27187:29021:24518",
            reward_desc="参与对抗百鬼夜行，有机会获得<color=#BA6908>神兽之魂、稀有宠物碎片、高级技能书</color>等珍贵奖励！少侠不去试试吗？"
        },
        {
            act_type=15,
            reward_id="22050:27620:27303",
            reward_desc="参与丝绸之路，有机会获得<color=#BA6908>宠物属性丹、稀有宠物玉玦、金宠灵魂玉玦</color>等珍贵奖励！少侠不去试试吗？"
        },
        {
            act_type=10044,
            reward_id="22050:27620:27303",
            reward_desc="参与万灵大事件，有机会获得<color=#BA6908>宠物属性丹、稀有宠物玉玦、金宠灵魂玉玦</color>等珍贵奖励！少侠不去试试吗？"
        },
        {
            act_type=12,
            activity_show=65,
            reward_id="23907:25542:26403",
            reward_desc="参与幻界战场，有机会获得<color=#BA6908>稀有宠物蛋、超级技能书、灵骑突破丹</color>等珍贵奖励！少侠不去试试吗？"
        },
        {
            act_type=10045,
            reward_id="22050:27620:27303",
            reward_desc="参与论剑九州，有机会获得<color=#BA6908>超级宠物技能书、限定稀有宠物、五级宝石礼袋</color>等珍贵奖励！少侠不去试试吗？"
        },
        {
            act_type=13,
            activity_show=119,
            reward_desc="参与遗迹夺宝，有机会获得<color=#BA6908>高级技能书礼盒、五级宝石礼袋</color>等珍贵奖励！少侠不去试试吗？"
        },
        {
            act_type=4,
            activity_show=85,
            reward_id="65535:65532:65550:65543",
            reward_desc="参与勇闯地宫，有机会获得<color=#BA6908>声望卡自选礼盒、高级技能书、高级藏宝图</color>等珍贵奖励！少侠不去试试吗？"
        },
        {
            act_type=16,
            activity_show=310,
            is_popup=0,
            reward_id="",
            reward_desc=""
        },
        {
            act_type=18,
            activity_show=351,
            reward_id="56334:56335:56339",
            reward_desc="参与星官降临，有机会获得<color=#BA6908>星辰碎片、星辉石、超型星</color>等珍贵奖励！少侠不去试试吗？"
        }
    },
    join_reward={
        {
            seq=0,
            activity_id=1,
            max_level=39,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=20000
        },
        {
            seq=0,
            activity_id=1,
            min_level=40,
            max_level=49,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=20000
        },
        {
            seq=0,
            activity_id=1,
            min_level=50,
            max_level=59,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=0,
            activity_id=1,
            min_level=60,
            max_level=69,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=0,
            activity_id=1,
            min_level=70,
            max_level=79,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=0,
            activity_id=1,
            min_level=80,
            max_level=89,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=40000
        },
        {
            seq=0,
            activity_id=1,
            min_level=90,
            max_level=99,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=40000
        },
        {
            seq=0,
            activity_id=1,
            min_level=100,
            max_level=109,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=40000
        },
        {
            seq=0,
            activity_id=1,
            min_level=110,
            max_level=119,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=50000
        },
        {
            seq=0,
            activity_id=1,
            min_level=120,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=50000
        },
        {
            seq=1,
            activity_id=2,
            max_level=34,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=175000,
            coin=20000
        },
        {
            seq=1,
            activity_id=2,
            min_level=35,
            max_level=39,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=196000,
            coin=20000
        },
        {
            seq=1,
            activity_id=2,
            min_level=40,
            max_level=44,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=217000,
            coin=20000
        },
        {
            seq=1,
            activity_id=2,
            min_level=45,
            max_level=49,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=238000,
            coin=20000
        },
        {
            seq=1,
            activity_id=2,
            min_level=50,
            max_level=54,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=266000
        },
        {
            seq=1,
            activity_id=2,
            min_level=55,
            max_level=59,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=294000
        },
        {
            seq=1,
            activity_id=2,
            min_level=60,
            max_level=64,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=315000
        },
        {
            seq=1,
            activity_id=2,
            min_level=65,
            max_level=69,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=343000
        },
        {
            seq=1,
            activity_id=2,
            min_level=70,
            max_level=74,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=364000
        },
        {
            seq=1,
            activity_id=2,
            min_level=75,
            max_level=79,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=385000
        },
        {
            seq=1,
            activity_id=2,
            min_level=80,
            max_level=84,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=413000,
            coin=40000
        },
        {
            seq=1,
            activity_id=2,
            min_level=85,
            max_level=89,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=434000,
            coin=40000
        },
        {
            seq=1,
            activity_id=2,
            min_level=90,
            max_level=94,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=462000,
            coin=40000
        },
        {
            seq=1,
            activity_id=2,
            min_level=95,
            max_level=99,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=483000,
            coin=40000
        },
        {
            seq=1,
            activity_id=2,
            min_level=100,
            max_level=104,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=504000,
            coin=40000
        },
        {
            seq=1,
            activity_id=2,
            min_level=105,
            max_level=109,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=532000,
            coin=40000
        },
        {
            seq=1,
            activity_id=2,
            min_level=110,
            max_level=114,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=553000,
            coin=50000
        },
        {
            seq=1,
            activity_id=2,
            min_level=115,
            max_level=119,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=581000,
            coin=50000
        },
        {
            seq=1,
            activity_id=2,
            min_level=120,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=602000,
            coin=50000
        },
        {
            seq=2,
            activity_id=3,
            max_level=39,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=20000
        },
        {
            seq=2,
            activity_id=3,
            min_level=40,
            max_level=49,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=20000
        },
        {
            seq=2,
            activity_id=3,
            min_level=50,
            max_level=59,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=2,
            activity_id=3,
            min_level=60,
            max_level=69,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=2,
            activity_id=3,
            min_level=70,
            max_level=79,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=2,
            activity_id=3,
            min_level=80,
            max_level=89,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=40000
        },
        {
            seq=2,
            activity_id=3,
            min_level=90,
            max_level=99,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=40000
        },
        {
            seq=2,
            activity_id=3,
            min_level=100,
            max_level=109,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=40000
        },
        {
            seq=2,
            activity_id=3,
            min_level=110,
            max_level=119,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=50000
        },
        {
            seq=2,
            activity_id=3,
            min_level=120,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=50000
        },
        {
            max_level=29,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=204900,
            coin=20000
        },
        {
            min_level=30,
            max_level=34,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=252900,
            coin=20000
        },
        {
            min_level=35,
            max_level=39,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=300900,
            coin=20000
        },
        {
            min_level=40,
            max_level=44,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=348900,
            coin=20000
        },
        {
            min_level=45,
            max_level=49,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=396900,
            coin=20000
        },
        {
            min_level=50,
            max_level=54,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=444900
        },
        {
            min_level=55,
            max_level=59,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=650400
        },
        {
            min_level=60,
            max_level=64,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=698400
        },
        {
            min_level=65,
            max_level=69,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=746400
        },
        {
            min_level=70,
            max_level=74,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=794400
        },
        {
            min_level=75,
            max_level=79,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=842400
        },
        {
            min_level=80,
            max_level=84,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=890400,
            coin=40000
        },
        {
            min_level=85,
            max_level=89,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=938400,
            coin=40000
        },
        {
            min_level=90,
            max_level=94,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=986400,
            coin=40000
        },
        {
            min_level=95,
            max_level=99,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=1034400,
            coin=40000
        },
        {
            min_level=100,
            max_level=104,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=1082400,
            coin=40000
        },
        {
            min_level=105,
            max_level=109,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=1130400,
            coin=40000
        },
        {
            min_level=110,
            max_level=114,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=1178400,
            coin=50000
        },
        {
            min_level=115,
            max_level=119,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=1226400,
            coin=50000
        },
        {
            min_level=120,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=1274400,
            coin=50000
        },
        {
            seq=4,
            activity_id=8,
            max_level=39,
            reward_item={
                [0]=_itemlist.i_28518_1_1,
                [1]=_itemlist.i_24518_1_1
            },
            coin=20000
        },
        {
            seq=4,
            activity_id=8,
            min_level=40,
            max_level=49,
            reward_item={
                [0]=_itemlist.i_28518_1_1,
                [1]=_itemlist.i_24518_1_1
            },
            coin=20000
        },
        {
            seq=4,
            activity_id=8,
            min_level=50,
            max_level=59,
            reward_item={
                [0]=_itemlist.i_28518_1_1,
                [1]=_itemlist.i_24518_1_1
            }
        },
        {
            seq=4,
            activity_id=8,
            min_level=60,
            max_level=69,
            reward_item={
                [0]=_itemlist.i_28518_1_1,
                [1]=_itemlist.i_24518_1_1
            }
        },
        {
            seq=4,
            activity_id=8,
            min_level=70,
            max_level=79,
            reward_item={
                [0]=_itemlist.i_28518_1_1,
                [1]=_itemlist.i_24518_1_1
            }
        },
        {
            seq=4,
            activity_id=8,
            min_level=80,
            max_level=89,
            reward_item={
                [0]=_itemlist.i_28518_1_1,
                [1]=_itemlist.i_24518_1_1
            },
            coin=40000
        },
        {
            seq=4,
            activity_id=8,
            min_level=90,
            max_level=99,
            reward_item={
                [0]=_itemlist.i_28518_1_1,
                [1]=_itemlist.i_24518_1_1
            },
            coin=40000
        },
        {
            seq=4,
            activity_id=8,
            min_level=100,
            max_level=109,
            reward_item={
                [0]=_itemlist.i_28518_1_1,
                [1]=_itemlist.i_24518_1_1
            },
            coin=40000
        },
        {
            seq=4,
            activity_id=8,
            min_level=110,
            max_level=119,
            reward_item={
                [0]=_itemlist.i_28518_1_1,
                [1]=_itemlist.i_24518_1_1
            },
            coin=50000
        },
        {
            seq=4,
            activity_id=8,
            min_level=120,
            reward_item={
                [0]=_itemlist.i_28518_1_1,
                [1]=_itemlist.i_24518_1_1
            },
            coin=50000
        },
        {
            seq=5,
            activity_id=9,
            max_level=39,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=20000
        },
        {
            seq=5,
            activity_id=9,
            min_level=40,
            max_level=49,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=20000
        },
        {
            seq=5,
            activity_id=9,
            min_level=50,
            max_level=59,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=5,
            activity_id=9,
            min_level=60,
            max_level=69,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=5,
            activity_id=9,
            min_level=70,
            max_level=79,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=5,
            activity_id=9,
            min_level=80,
            max_level=89,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=40000
        },
        {
            seq=5,
            activity_id=9,
            min_level=90,
            max_level=99,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=40000
        },
        {
            seq=5,
            activity_id=9,
            min_level=100,
            max_level=109,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=40000
        },
        {
            seq=5,
            activity_id=9,
            min_level=110,
            max_level=119,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=50000
        },
        {
            seq=5,
            activity_id=9,
            min_level=120,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=50000
        },
        {
            seq=6,
            activity_id=10,
            max_level=39,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=20000
        },
        {
            seq=6,
            activity_id=10,
            min_level=40,
            max_level=49,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=20000
        },
        {
            seq=6,
            activity_id=10,
            min_level=50,
            max_level=59,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=6,
            activity_id=10,
            min_level=60,
            max_level=69,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=6,
            activity_id=10,
            min_level=70,
            max_level=79,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=6,
            activity_id=10,
            min_level=80,
            max_level=89,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=40000
        },
        {
            seq=6,
            activity_id=10,
            min_level=90,
            max_level=99,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=40000
        },
        {
            seq=6,
            activity_id=10,
            min_level=100,
            max_level=109,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=40000
        },
        {
            seq=6,
            activity_id=10,
            min_level=110,
            max_level=119,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=50000
        },
        {
            seq=6,
            activity_id=10,
            min_level=120,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=50000
        },
        {
            seq=7,
            activity_id=11,
            max_level=29,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=141400,
            coin=20000
        },
        {
            seq=7,
            activity_id=11,
            min_level=30,
            max_level=34,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=169400,
            coin=20000
        },
        {
            seq=7,
            activity_id=11,
            min_level=35,
            max_level=39,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=197400,
            coin=20000
        },
        {
            seq=7,
            activity_id=11,
            min_level=40,
            max_level=44,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=225400,
            coin=20000
        },
        {
            seq=7,
            activity_id=11,
            min_level=45,
            max_level=49,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=253400,
            coin=20000
        },
        {
            seq=7,
            activity_id=11,
            min_level=50,
            max_level=54,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=281400
        },
        {
            seq=7,
            activity_id=11,
            min_level=55,
            max_level=59,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=309400
        },
        {
            seq=7,
            activity_id=11,
            min_level=60,
            max_level=64,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=407400
        },
        {
            seq=7,
            activity_id=11,
            min_level=65,
            max_level=69,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=435400
        },
        {
            seq=7,
            activity_id=11,
            min_level=70,
            max_level=74,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=463400
        },
        {
            seq=7,
            activity_id=11,
            min_level=75,
            max_level=79,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=491400
        },
        {
            seq=7,
            activity_id=11,
            min_level=80,
            max_level=84,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=519400,
            coin=40000
        },
        {
            seq=7,
            activity_id=11,
            min_level=85,
            max_level=89,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=547400,
            coin=40000
        },
        {
            seq=7,
            activity_id=11,
            min_level=90,
            max_level=94,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=575400,
            coin=40000
        },
        {
            seq=7,
            activity_id=11,
            min_level=95,
            max_level=99,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=603400,
            coin=40000
        },
        {
            seq=7,
            activity_id=11,
            min_level=100,
            max_level=104,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=631400,
            coin=40000
        },
        {
            seq=7,
            activity_id=11,
            min_level=105,
            max_level=109,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=659400,
            coin=40000
        },
        {
            seq=7,
            activity_id=11,
            min_level=110,
            max_level=114,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=687400,
            coin=50000
        },
        {
            seq=7,
            activity_id=11,
            min_level=115,
            max_level=119,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=715400,
            coin=50000
        },
        {
            seq=7,
            activity_id=11,
            min_level=120,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=743400,
            coin=50000
        },
        {
            seq=8,
            activity_id=6,
            max_level=29,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=30200,
            coin=20000
        },
        {
            seq=8,
            activity_id=6,
            min_level=30,
            max_level=34,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=34200,
            coin=20000
        },
        {
            seq=8,
            activity_id=6,
            min_level=35,
            max_level=39,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=38200,
            coin=20000
        },
        {
            seq=8,
            activity_id=6,
            min_level=40,
            max_level=44,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=42200,
            coin=20000
        },
        {
            seq=8,
            activity_id=6,
            min_level=45,
            max_level=49,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=46200,
            coin=20000
        },
        {
            seq=8,
            activity_id=6,
            min_level=50,
            max_level=54,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=50200
        },
        {
            seq=8,
            activity_id=6,
            min_level=55,
            max_level=59,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=54200
        },
        {
            seq=8,
            activity_id=6,
            min_level=60,
            max_level=64,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=58200
        },
        {
            seq=8,
            activity_id=6,
            min_level=65,
            max_level=69,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=62200
        },
        {
            seq=8,
            activity_id=6,
            min_level=70,
            max_level=74,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=66200
        },
        {
            seq=8,
            activity_id=6,
            min_level=75,
            max_level=79,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=70200
        },
        {
            seq=8,
            activity_id=6,
            min_level=80,
            max_level=84,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=74200,
            coin=40000
        },
        {
            seq=8,
            activity_id=6,
            min_level=85,
            max_level=89,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=78200,
            coin=40000
        },
        {
            seq=8,
            activity_id=6,
            min_level=90,
            max_level=94,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=82200,
            coin=40000
        },
        {
            seq=8,
            activity_id=6,
            min_level=95,
            max_level=99,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=86200,
            coin=40000
        },
        {
            seq=8,
            activity_id=6,
            min_level=100,
            max_level=104,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=90200,
            coin=40000
        },
        {
            seq=8,
            activity_id=6,
            min_level=105,
            max_level=109,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=94200,
            coin=40000
        },
        {
            seq=8,
            activity_id=6,
            min_level=110,
            max_level=114,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=98200,
            coin=50000
        },
        {
            seq=8,
            activity_id=6,
            min_level=115,
            max_level=119,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=102200,
            coin=50000
        },
        {
            seq=8,
            activity_id=6,
            min_level=120,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            exp=106200,
            coin=50000
        },
        {
            seq=9,
            activity_id=12,
            max_level=39,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=20000
        },
        {
            seq=9,
            activity_id=12,
            min_level=40,
            max_level=49,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=20000
        },
        {
            seq=9,
            activity_id=12,
            min_level=50,
            max_level=59,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=9,
            activity_id=12,
            min_level=60,
            max_level=69,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=9,
            activity_id=12,
            min_level=70,
            max_level=79,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=9,
            activity_id=12,
            min_level=80,
            max_level=89,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=40000
        },
        {
            seq=9,
            activity_id=12,
            min_level=90,
            max_level=99,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=40000
        },
        {
            seq=9,
            activity_id=12,
            min_level=100,
            max_level=109,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=40000
        },
        {
            seq=9,
            activity_id=12,
            min_level=110,
            max_level=119,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=50000
        },
        {
            seq=9,
            activity_id=12,
            min_level=120,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=50000
        },
        {
            seq=10,
            activity_id=14,
            max_level=39,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=20000
        },
        {
            seq=10,
            activity_id=14,
            min_level=40,
            max_level=49,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=20000
        },
        {
            seq=10,
            activity_id=14,
            min_level=50,
            max_level=59,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=10,
            activity_id=14,
            min_level=60,
            max_level=69,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=10,
            activity_id=14,
            min_level=70,
            max_level=79,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=10,
            activity_id=14,
            min_level=80,
            max_level=89,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=40000
        },
        {
            seq=10,
            activity_id=14,
            min_level=90,
            max_level=99,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=40000
        },
        {
            seq=10,
            activity_id=14,
            min_level=100,
            max_level=109,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=40000
        },
        {
            seq=10,
            activity_id=14,
            min_level=110,
            max_level=119,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=50000
        },
        {
            seq=10,
            activity_id=14,
            min_level=120,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=50000
        },
        {
            seq=11,
            activity_id=15,
            max_level=39,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=20000
        },
        {
            seq=11,
            activity_id=15,
            min_level=40,
            max_level=49,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=20000
        },
        {
            seq=11,
            activity_id=15,
            min_level=50,
            max_level=59,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=20000
        },
        {
            seq=11,
            activity_id=15,
            min_level=60,
            max_level=69,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            },
            coin=20000
        },
        {
            seq=11,
            activity_id=15,
            min_level=70,
            max_level=79,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=11,
            activity_id=15,
            min_level=80,
            max_level=89,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=11,
            activity_id=15,
            min_level=90,
            max_level=99,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=11,
            activity_id=15,
            min_level=100,
            max_level=109,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=11,
            activity_id=15,
            min_level=110,
            max_level=119,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=11,
            activity_id=15,
            min_level=120,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        },
        {
            seq=12,
            activity_id=18,
            reward_item={
                [0]=_itemlist.i_28518_1_1
            }
        }
    },
    match_notice={
        {
            name="报名规则",
            language_seq=200
        },
        {
            name="比赛规则",
            language_seq=201
        },
        {
            type=2,
            language_seq=202
        },
        {
            seq=1,
            name="资格淘汰赛阶段规则",
            language_seq=205
        },
        {
            seq=1,
            name="晋级赛阶段规则",
            language_seq=206
        },
        {
            seq=1,
            type=2,
            language_seq=207
        }
    }
}
SetConfigDefaultVal(Config.daily_activity_auto,_default_val,nil,nil,nil)