local _default_val={
    friendship_skill={
        icon_id="s6101",
        skill_sort=1,
        skill_level=1
    }
}
Config.deep_friendship_auto={
    friendship_skill={
        {
            friendship_level=1,
            level_name="布衣之交",
            friendship_intimacy=0,
            friendship_time=1,
            sp_id=6101,
            skill_name="齐心协力I",
            description="当队伍中存在2名以上结义成员时，结义成员防御提升等级*3+10，法抗提升等级*0.5+5（仅PVE生效）"
        },
        {
            friendship_level=2,
            level_name="君子之交",
            friendship_intimacy=1000,
            friendship_time=10,
            sp_id=6102,
            skill_level=2,
            skill_name="齐心协力II",
            description="当队伍中存在2名以上结义成员时，结义成员防御提升等级*7+30，法抗提升等级*1+10（仅PVE生效）"
        },
        {
            friendship_level=3,
            level_name="管鲍之交",
            friendship_intimacy=2000,
            friendship_time=20,
            sp_id=6103,
            skill_level=3,
            skill_name="齐心协力III",
            description="当队伍中存在2名以上结义成员时，结义成员防御提升等级*12+50，法抗提升等级*1.5+15（仅PVE生效）"
        },
        {
            friendship_level=4,
            level_name="杵臼之交",
            friendship_intimacy=3000,
            friendship_time=30,
            sp_id=6104,
            icon_id="s6104",
            skill_sort=2,
            skill_name="如虎添翼I",
            description="当队伍中存在2名以上结义成员时，所有结义成员的异常抗性提升3%（仅PVE生效）"
        },
        {
            friendship_level=5,
            level_name="莫逆之交",
            friendship_intimacy=4000,
            friendship_time=40,
            sp_id=6105,
            icon_id="s6104",
            skill_sort=2,
            skill_level=2,
            skill_name="如虎添翼II",
            description="当队伍中存在2名以上结义成员时，所有结义成员的异常抗性提升5%（仅PVE生效）"
        },
        {
            friendship_level=6,
            level_name="忘形之交",
            friendship_intimacy=5000,
            friendship_time=50,
            sp_id=6106,
            icon_id="s6104",
            skill_sort=2,
            skill_level=3,
            skill_name="如虎添翼III",
            description="当队伍中存在2名以上结义成员时，所有结义成员的异常抗性提升7%（仅PVE生效）"
        },
        {
            friendship_level=7,
            level_name="羊左之交",
            friendship_intimacy=6000,
            friendship_time=60,
            sp_id=6107,
            icon_id="s6107",
            skill_sort=3,
            skill_name="肝胆相照I",
            description="受到来自结义成员的药品或恢复、复活类技能，治疗效果额外提升7%（仅PVE生效）"
        },
        {
            friendship_level=8,
            level_name="生死之交",
            friendship_intimacy=7000,
            friendship_time=70,
            sp_id=6108,
            icon_id="s6107",
            skill_sort=3,
            skill_level=2,
            skill_name="肝胆相照II",
            description="受到来自结义成员的药品或恢复、复活类技能，治疗效果额外提升9%（仅PVE生效）"
        },
        {
            friendship_level=9,
            level_name="金兰之交",
            friendship_intimacy=8000,
            friendship_time=80,
            sp_id=6109,
            icon_id="s6107",
            skill_sort=3,
            skill_level=3,
            skill_name="肝胆相照III",
            description="受到来自结义成员的药品或恢复、复活类技能，治疗效果额外提升11%（仅PVE生效）"
        },
        {
            friendship_level=10,
            level_name="八拜之交",
            friendship_intimacy=10000,
            friendship_time=100,
            sp_id=6110,
            icon_id="s6108",
            skill_sort=4,
            skill_name="其利断金",
            description="当队伍中存在2名以上结义成员时，所有结义成员伤害提升13%（仅PVE生效）"
        }
    },
    other={
        {
            intimacy_request=500,
            title_revise_consume=27846,
            consume_num1=1,
            name_revise_consume=27846,
            consume_num2=1,
            cooling_period_time=86400,
            member_max=5,
            member_min=2,
            friendship_npc=71052,
            for_test=0,
            tan_he_not_online_time=259200,
            tan_he_impeach_time=43200,
            tan_he_vote_time=43200,
            tan_he_poll=1
        }
    }
}
SetConfigDefaultVal(Config.deep_friendship_auto,_default_val,nil,nil,nil)