local _default_val={
    player_side={
        critical_dec_value=1,
        anti_poison=0,
        anti_sleep=0,
        anti_petrify=0,
        anti_forget=0,
        anti_chaos=0,
        anti_drunk=0,
        race=0,
        water=0,
        earth=0,
        skill_id_2=0,
        skill_id_3=0,
        skill_id_4=0,
        skill_id_5=0,
        skill_id_6=0,
        skill_id_7=0,
        skill_id_8=0,
        skill_id_9=0,
        skill_level_0=1,
        skill_level_2=0,
        skill_level_3=0,
        skill_level_4=0,
        skill_level_5=0,
        skill_level_6=0,
        skill_level_7=0,
        skill_level_8=0,
        skill_level_9=0,
        weapon_effect=0,
        effect_3=0,
        effect_4=0,
        effect_5=0,
        effect_6=0,
        effect_7=0,
        effect_8=0,
        effect_9=0,
        effect_10=0
    }
}
Config.demo_auto={
    player_side={
        {
            attack=2000,
            defense=1500,
            agility=1000,
            mental=0,
            recovery=344,
            critical=500,
            dodge=-100,
            hit=37,
            counter_attack=9,
            magic_defense=0,
            magic_attack=70,
            critical_inc_value=0,
            fire=10,
            wind=0,
            skill_id_0=1124,
            skill_id_1=401,
            skill_level_1=1,
            effect_1=342,
            effect_2=338
        },
        {
            attack=1292,
            defense=763,
            agility=299,
            mental=124,
            recovery=275,
            critical=1,
            dodge=19,
            hit=29,
            counter_attack=7,
            magic_defense=102,
            magic_attack=56,
            critical_inc_value=1,
            fire=0,
            wind=10,
            skill_id_0=1,
            skill_id_1=502,
            skill_level_1=8,
            effect_1=0,
            effect_2=0
        }
    },
    other={
        {
            monster_group_id=50000
        }
    }
}
SetConfigDefaultVal(Config.demo_auto,_default_val,nil,nil,nil)