local _default_val={
    main_screen_button={
        place=1,
        mod="",
        pos="",
        out_show=""
    },
    daily={
        divine_realm_stage=2,
        is_show=1,
        act_icon_click="",
        act_model_show="",
        act_go_click="",
        activity_time=2,
        open_day=1,
        begin_time="21:30",
        position_1="",
        position_2="",
        position_3="",
        position_4="",
        quantity=1,
        ui_show_sp_sub="",
        ui_model_decals_1="",
        ui_model_decals_2="",
        ui_model_decals_3="",
        ui_model_decals_4="",
        map_position_1="",
        map_position_2="",
        map_position_3="",
        map_position_4=""
    },
    position={
        position_x=3,
        position_y=3,
        position_core="2|2"
    },
    map_location={
        position_x=0,
        position_y=0,
        width=0,
        height=0
    }
}
Config.divine_domain_function_auto={
    main_screen_button={
        {
            view="LandsBetweenSeasonView",
            text="赛季",
            sprite="SaiJi",
            open=161010,
            out_show=1
        },
        {
            view="ShenYuRankView",
            text="排行",
            sprite="PaiHangBang",
            open=162004,
            out_show=1
        },
        {
            view="GodPosView",
            text="神位",
            sprite="ShenWei",
            open=162001,
            out_show=1
        },
        {
            view="FairyDragonView",
            text="神龙",
            sprite="ShenLong",
            open=160001,
            out_show=1
        },
        {
            view="LingBaoView",
            text="灵宝",
            sprite="LingBao",
            open=159001,
            out_show=1
        },
        {
            view="LBShopView",
            text="商店",
            sprite="ShenYuShangDian",
            open=162005
        },
        {
            view="GodAreasActs",
            text="活动",
            sprite="HuoDong",
            open=163001
        },
        {
            view="PalacesWorship",
            text="殿堂",
            sprite="DianTang",
            open=163005
        },
        {
            view="LBHandBookView",
            text="神域指南",
            sprite="ZhiNan",
            open=162003
        },
        {
            view="ShenYuProbeView",
            text="神域探索",
            sprite="ShenYuTanSuo2",
            open=164001
        },
        {
            view="LBFestivalView",
            text="神域狂欢",
            sprite="ShenYuKuangHuan",
            mod="LBFestival",
            open=165001
        }
    },
    daily={
        [10052]={
            act_type=10052,
            divine_realm_stage=1,
            act_seq=1,
            icon_id="a10052",
            mod_key=163001,
            name_text="归墟之境",
            act_icon_click="ruins_act_icon_click",
            act_model_show="ruins_model_show",
            act_go_click="ruins_act_go_click",
            end_time="21:45",
            position_1=1,
            ui_model_decals_1="LingDi",
            map_position_1=1
        },
        [10053]={
            act_type=10053,
            act_seq=2,
            icon_id="ZhenYingShenShou",
            mod_key=163003,
            name_text="阵营神兽",
            act_model_show="animals_model_show",
            activity_time=1,
            open_day=6,
            begin_time="9:46",
            end_time="21:30",
            position_1=2,
            position_2=3,
            position_3=4,
            position_4=5,
            quantity=4,
            ui_show_sp_sub="zhen_yin_shen_shou_sub",
            ui_model_decals_1="BaiHu",
            ui_model_decals_2="QingLong",
            ui_model_decals_3="XuanWu",
            ui_model_decals_4="ZhuQue",
            map_position_1=2,
            map_position_2=3,
            map_position_3=4,
            map_position_4=5
        },
        [10054]={
            act_type=10054,
            act_seq=3,
            icon_id="YunDingTianGong",
            mod_key=163002,
            name_text="云顶天宫",
            act_icon_click="palaces_act_icon_click",
            act_model_show="palaces_model_show",
            act_go_click="palaces_act_go_click",
            activity_time=6,
            end_time="22:00",
            position_1=6,
            ui_model_decals_1="JiTan",
            map_position_1=6
        },
        [10055]={
            act_type=10055,
            act_seq=4,
            icon_id="LongMai",
            mod_key=162002,
            name_text="龙脉",
            open_day=5,
            begin_time="8:00",
            end_time="20:00",
            quantity=0
        },
        [10056]={
            act_type=10056,
            act_seq=5,
            icon_id="ShenYuTanSuo1",
            mod_key=164001,
            name_text="神域探索",
            activity_time=6,
            begin_time="9:46",
            end_time="24:00",
            quantity=0
        }
    },
    position={
        {
            position_id=1,
            position_generate="54|102",
            position_x=4,
            position_y=4
        },
        {
            position_id=2,
            position_generate="73|69|0"
        },
        {
            position_id=3,
            position_generate="69|73|1"
        },
        {
            position_id=4,
            position_generate="73|77|2"
        },
        {
            position_id=5,
            position_generate="77|73|3"
        },
        {
            position_id=6,
            position_generate="72|72",
            position_x=5,
            position_y=5,
            position_core="3|3"
        }
    },
    map_location={
        {
            position_id=1,
            position_x=3084.4,
            position_y=-642.6,
            width=163.8808,
            height=112.129
        },
        {
            position_id=2
        },
        {
            position_id=3
        },
        {
            position_id=4
        },
        {
            position_id=5
        },
        {
            position_id=6,
            position_x=2045.1,
            position_y=-1102.2,
            width=132.7538,
            height=75.11069999999999
        }
    }
}
SetConfigDefaultVal(Config.divine_domain_function_auto,_default_val,nil,nil,nil)