local _default_val={
    dragon_Boat={
        grade_start=1,
        grade_end=30,
        seq1=0,
        difference_time=50,
        time_slot="50及以上"
    }
}
local _itemlist={
    i_26680_1_1={
        item_id=26680,
        num=1,
        is_bind=1
    },
    i_23941_1_1={
        item_id=23941,
        num=1,
        is_bind=1
    },
    i_27188_1_1={
        item_id=27188,
        num=1,
        is_bind=1
    },
    i_24383_1_1={
        item_id=24383,
        num=1,
        is_bind=1
    },
    i_28517_1_1={
        item_id=28517,
        num=1,
        is_bind=1
    },
    i_28522_1_1={
        item_id=28522,
        num=1,
        is_bind=1
    }
}
Config.dragon_boat_racing_auto={
    other={
        {
            dragon_Boat_failure={
                [0]=_itemlist.i_26680_1_1
            }
        }
    },
    dragon_Boat={
        {
            seq=0,
            reward_item=_itemlist.i_23941_1_1
        },
        {
            seq=1,
            seq1=1,
            difference_time=40,
            time_slot="40-49",
            reward_item=_itemlist.i_27188_1_1
        },
        {
            seq=2,
            seq1=2,
            difference_time=30,
            time_slot="30-39",
            reward_item=_itemlist.i_24383_1_1
        },
        {
            seq=3,
            seq1=3,
            difference_time=20,
            time_slot="20-29",
            reward_item=_itemlist.i_28517_1_1
        },
        {
            seq=4,
            seq1=4,
            difference_time=0,
            time_slot="0-19",
            reward_item=_itemlist.i_28522_1_1
        },
        {
            seq=5,
            grade_start=31,
            grade_end=50,
            reward_item=_itemlist.i_23941_1_1
        },
        {
            seq=6,
            grade_start=31,
            grade_end=50,
            seq1=1,
            difference_time=40,
            time_slot="40-49",
            reward_item=_itemlist.i_27188_1_1
        },
        {
            seq=7,
            grade_start=31,
            grade_end=50,
            seq1=2,
            difference_time=30,
            time_slot="30-39",
            reward_item=_itemlist.i_24383_1_1
        },
        {
            seq=8,
            grade_start=31,
            grade_end=50,
            seq1=3,
            difference_time=20,
            time_slot="20-29",
            reward_item=_itemlist.i_28517_1_1
        },
        {
            seq=9,
            grade_start=31,
            grade_end=50,
            seq1=4,
            difference_time=0,
            time_slot="0-19",
            reward_item=_itemlist.i_28522_1_1
        },
        {
            seq=10,
            grade_start=51,
            grade_end=0,
            reward_item=_itemlist.i_23941_1_1
        },
        {
            seq=11,
            grade_start=51,
            grade_end=0,
            seq1=1,
            difference_time=40,
            time_slot="40-49",
            reward_item=_itemlist.i_27188_1_1
        },
        {
            seq=12,
            grade_start=51,
            grade_end=0,
            seq1=2,
            difference_time=30,
            time_slot="30-39",
            reward_item=_itemlist.i_24383_1_1
        },
        {
            seq=13,
            grade_start=51,
            grade_end=0,
            seq1=3,
            difference_time=20,
            time_slot="20-29",
            reward_item=_itemlist.i_28517_1_1
        },
        {
            seq=14,
            grade_start=51,
            grade_end=0,
            seq1=4,
            difference_time=0,
            time_slot="0-19",
            reward_item=_itemlist.i_28522_1_1
        }
    },
    pattern={
        {
            seq=0,
            speed_mode=0,
            point=2
        },
        {
            seq=1,
            speed_mode=1,
            point=3
        }
    }
}
SetConfigDefaultVal(Config.dragon_boat_racing_auto,_default_val,nil,nil,nil)