local _default_val={
    experience_view={
        label_type=0,
        is_guide=0,
        skip=4
    },
    challenge_navi={
        label_type=0,
        is_team=1,
        is_guide=0,
        effect=7161026
    }
}
Config.experience_auto={
    experience_view={
        {
            sort=1,
            id=1,
            name="校场演武",
            mod=30005,
            reward_sign="珍宝",
            is_guide=1,
            effect=7165063,
            type=54
        },
        {
            sort=2,
            id=2,
            name="挑战任务",
            mod=30001,
            reward_sign="珍宝|声望",
            effect=7165062,
            type=0
        },
        {
            sort=3,
            id=3,
            name="锢魔之塔",
            mod=30002,
            reward_sign="修炼",
            is_guide=1,
            effect=7165064,
            type=9
        },
        {
            sort=4,
            id=4,
            name="妖行试炼",
            mod=137001,
            reward_sign="宠物|天赋",
            effect=7165048,
            type=85
        },
        {
            sort=5,
            id=5,
            name="轮回忘川",
            mod=30006,
            reward_sign="法宝",
            is_guide=1,
            effect=7165065,
            type=59
        },
        {
            sort=6,
            id=6,
            name="幽冥炼狱",
            mod=105001,
            label_type=2,
            reward_sign="铸灵",
            is_guide=1,
            effect=7165066,
            type=62
        },
        {
            sort=7,
            id=7,
            name="无尽之塔",
            mod=30011,
            reward_sign="神印",
            effect=7165067,
            type=73
        },
        {
            sort=8,
            id=8,
            name="天辰蜃境",
            mod=30012,
            label_type=1,
            reward_sign="伙伴|专武",
            effect=7165068,
            type=78
        },
        {
            sort=9,
            id=9,
            name="弑神之塔",
            mod=30020,
            reward_sign="星图",
            effect=6165336,
            type=95
        }
    },
    challenge_navi={
        {
            sort=1,
            id=1,
            name="精英试炼",
            mod=30007,
            effect=2161047
        },
        {
            sort=2,
            id=2,
            name="远征魔冢",
            mod=72001,
            label_type=2,
            effect=10010370
        },
        {
            sort=3,
            id=3,
            name="北斗七星",
            mod=30008,
            label_type=2,
            effect=4161004
        },
        {
            sort=4,
            id=4,
            name="陨神之地",
            mod=30013,
            label_type=2,
            effect=7161022
        },
        {
            sort=5,
            id=5,
            name="上古遗迹",
            mod=30010,
            effect=4165101
        },
        {
            sort=6,
            id=6,
            name="九重天劫",
            mod=30009,
            effect=4161029
        },
        {
            sort=7,
            id=7,
            name="塔楼冒险",
            mod=30014,
            is_team=0,
            is_guide=1
        },
        {
            sort=8,
            id=8,
            name="丹师试炼",
            mod=30015,
            is_team=0,
            is_guide=1
        },
        {
            sort=9,
            id=9,
            name="鸿蒙天界",
            mod=143001,
            label_type=2,
            effect=3161115
        }
    },
    other={
        {
            advance_level=5,
            default_num=5,
            explain=311
        }
    }
}
SetConfigDefaultVal(Config.experience_auto,_default_val,nil,nil,nil)