local _default_val={
    reward={
        section_start=1,
        section_end=2,
        item_id=1,
        seq=0,
        item_pool=1,
        show3=0
    }
}
local _itemlist={
    i_1__={
        item_id=1,
        num=null,
        is_bind=null
    },
    i_2__={
        item_id=2,
        num=null,
        is_bind=null
    },
    i_3__={
        item_id=3,
        num=null,
        is_bind=null
    },
    i_4__={
        item_id=4,
        num=null,
        is_bind=null
    },
    i_5__={
        item_id=5,
        num=null,
        is_bind=null
    },
    i_6__={
        item_id=6,
        num=null,
        is_bind=null
    },
    i_7__={
        item_id=7,
        num=null,
        is_bind=null
    },
    i_8__={
        item_id=8,
        num=null,
        is_bind=null
    },
    i_9__={
        item_id=9,
        num=null,
        is_bind=null
    },
    i_10__={
        item_id=10,
        num=null,
        is_bind=null
    },
    i_25614_1_1={
        item_id=25614,
        num=1,
        is_bind=1
    },
    i_29100_1_1={
        item_id=29100,
        num=1,
        is_bind=1
    },
    i_24800_1_1={
        item_id=24800,
        num=1,
        is_bind=1
    },
    i_22007_500_1={
        item_id=22007,
        num=500,
        is_bind=1
    },
    i_27541_1_1={
        item_id=27541,
        num=1,
        is_bind=1
    },
    i_28555_10_1={
        item_id=28555,
        num=10,
        is_bind=1
    },
    i_27839_1_1={
        item_id=27839,
        num=1,
        is_bind=1
    },
    i_27403_1_1={
        item_id=27403,
        num=1,
        is_bind=1
    },
    i_26813_1_1={
        item_id=26813,
        num=1,
        is_bind=1
    },
    i_27839_2_1={
        item_id=27839,
        num=2,
        is_bind=1
    },
    i_27403_2_1={
        item_id=27403,
        num=2,
        is_bind=1
    },
    i_26813_2_1={
        item_id=26813,
        num=2,
        is_bind=1
    },
    i_27839_3_1={
        item_id=27839,
        num=3,
        is_bind=1
    },
    i_27403_3_1={
        item_id=27403,
        num=3,
        is_bind=1
    },
    i_26813_3_1={
        item_id=26813,
        num=3,
        is_bind=1
    },
    i_27848_3_1={
        item_id=27848,
        num=3,
        is_bind=1
    }
}
Config.fenxiangtonghuali_auto={
    basics={
        {
            item_id=1,
            quantity=3,
            reward1_item=_itemlist.i_1__,
            reward2_item=_itemlist.i_2__,
            reward3_item=_itemlist.i_3__
        },
        {
            item_id=2,
            quantity=2,
            reward1_item=_itemlist.i_4__,
            reward2_item=_itemlist.i_5__,
            reward3_item=_itemlist.i_6__
        },
        {
            item_id=3,
            quantity=1,
            reward1_item=_itemlist.i_7__,
            reward2_item=_itemlist.i_8__,
            reward3_item=_itemlist.i_9__
        },
        {
            item_id=4,
            quantity=0,
            reward1_item=_itemlist.i_10__
        }
    },
    reward={
        {
            type=0,
            reward_item=_itemlist.i_25614_1_1,
            show3=1
        },
        {
            type=1,
            item_id=2,
            seq=1,
            reward_item=_itemlist.i_29100_1_1,
            show3=1
        },
        {
            type=2,
            item_id=3,
            seq=2,
            reward_item=_itemlist.i_24800_1_1,
            show3=1
        },
        {
            type=3,
            item_id=4,
            seq=3,
            item_pool=2,
            reward_item=_itemlist.i_22007_500_1
        },
        {
            type=4,
            item_id=5,
            seq=4,
            item_pool=2,
            reward_item=_itemlist.i_27541_1_1
        },
        {
            type=5,
            item_id=6,
            seq=5,
            item_pool=2,
            reward_item=_itemlist.i_28555_10_1
        },
        {
            type=6,
            item_id=7,
            seq=6,
            item_pool=3,
            reward_item=_itemlist.i_27839_1_1
        },
        {
            type=7,
            item_id=8,
            seq=7,
            item_pool=3,
            reward_item=_itemlist.i_27403_1_1
        },
        {
            type=8,
            item_id=9,
            seq=8,
            item_pool=3,
            reward_item=_itemlist.i_26813_1_1
        },
        {
            type=9,
            item_id=10,
            seq=9,
            item_pool=4,
            reward_item=_itemlist.i_27541_1_1
        },
        {
            type=10,
            section_start=3,
            section_end=5,
            reward_item=_itemlist.i_25614_1_1,
            show3=1
        },
        {
            type=11,
            section_start=3,
            section_end=5,
            item_id=2,
            seq=1,
            reward_item=_itemlist.i_29100_1_1,
            show3=1
        },
        {
            type=12,
            section_start=3,
            section_end=5,
            item_id=3,
            seq=2,
            reward_item=_itemlist.i_24800_1_1,
            show3=1
        },
        {
            type=13,
            section_start=3,
            section_end=5,
            item_id=4,
            seq=3,
            item_pool=2,
            reward_item=_itemlist.i_22007_500_1
        },
        {
            type=14,
            section_start=3,
            section_end=5,
            item_id=5,
            seq=4,
            item_pool=2,
            reward_item=_itemlist.i_27541_1_1
        },
        {
            type=15,
            section_start=3,
            section_end=5,
            item_id=6,
            seq=5,
            item_pool=2,
            reward_item=_itemlist.i_28555_10_1
        },
        {
            type=16,
            section_start=3,
            section_end=5,
            item_id=7,
            seq=6,
            item_pool=3,
            reward_item=_itemlist.i_27839_2_1
        },
        {
            type=17,
            section_start=3,
            section_end=5,
            item_id=8,
            seq=7,
            item_pool=3,
            reward_item=_itemlist.i_27403_2_1
        },
        {
            type=18,
            section_start=3,
            section_end=5,
            item_id=9,
            seq=8,
            item_pool=3,
            reward_item=_itemlist.i_26813_2_1
        },
        {
            type=19,
            section_start=3,
            section_end=5,
            item_id=10,
            seq=9,
            item_pool=4,
            reward_item=_itemlist.i_27541_1_1
        },
        {
            type=20,
            section_start=6,
            section_end=0,
            reward_item=_itemlist.i_25614_1_1,
            show3=1
        },
        {
            type=21,
            section_start=6,
            section_end=0,
            item_id=2,
            seq=1,
            reward_item=_itemlist.i_29100_1_1,
            show3=1
        },
        {
            type=22,
            section_start=6,
            section_end=0,
            item_id=3,
            seq=2,
            reward_item=_itemlist.i_24800_1_1,
            show3=1
        },
        {
            type=23,
            section_start=6,
            section_end=0,
            item_id=4,
            seq=3,
            item_pool=2,
            reward_item=_itemlist.i_22007_500_1
        },
        {
            type=24,
            section_start=6,
            section_end=0,
            item_id=5,
            seq=4,
            item_pool=2,
            reward_item=_itemlist.i_27541_1_1
        },
        {
            type=25,
            section_start=6,
            section_end=0,
            item_id=6,
            seq=5,
            item_pool=2,
            reward_item=_itemlist.i_28555_10_1
        },
        {
            type=26,
            section_start=6,
            section_end=0,
            item_id=7,
            seq=6,
            item_pool=3,
            reward_item=_itemlist.i_27839_3_1
        },
        {
            type=27,
            section_start=6,
            section_end=0,
            item_id=8,
            seq=7,
            item_pool=3,
            reward_item=_itemlist.i_27403_3_1
        },
        {
            type=28,
            section_start=6,
            section_end=0,
            item_id=9,
            seq=8,
            item_pool=3,
            reward_item=_itemlist.i_26813_3_1
        },
        {
            type=29,
            section_start=6,
            section_end=0,
            item_id=10,
            seq=9,
            item_pool=4,
            reward_item=_itemlist.i_27541_1_1
        }
    },
    other={
        {
            price_type=1,
            price=98,
            cfg_ver=2,
            reward_item={
                [0]=_itemlist.i_27848_3_1
            },
            item_num=3,
            limit_type=2,
            buy_times=0,
            today_times=10,
            desc="1.抽取花色中：\n含有自选幸运花色3个，可获得所有奖池所选；\n含有自选幸运花色2个，可获得精品+好运奖池所选；\n含有自选幸运花色1个，可获得好运奖池所选。\n\n2.不含有自选幸运花色时，可获得以下参与奖励：\nXXXXXXXX*1"
        }
    }
}
SetConfigDefaultVal(Config.fenxiangtonghuali_auto,_default_val,nil,nil,nil)