Config.fill_poetry_auto={
    lattice={
        {
            seq=1,
            type=0,
            group=1,
            word_0="黄",
            word_1="河",
            word_2="远",
            word_3="上",
            word_4=10,
            word_5=5,
            word_6="间",
            word_7="，",
            word_8="一",
            word_9="片",
            word_10=2,
            word_11=16,
            word_12="万",
            word_13="仞",
            word_14="山"
        },
        {
            seq=2,
            type=1,
            group=1,
            word_0="羌",
            word_1="笛",
            word_2=7,
            word_3=15,
            word_4="怨",
            word_5="杨",
            word_6="柳",
            word_7="，",
            word_8="春",
            word_9="风",
            word_10="不",
            word_11="度",
            word_12=17,
            word_13=9,
            word_14=12
        },
        {
            seq=3,
            type=0,
            group=2,
            word_0=15,
            word_1=5,
            word_2=8,
            word_3=7,
            word_4="老",
            word_5="大",
            word_6="回",
            word_7="，",
            word_8=3,
            word_9=1,
            word_10="无",
            word_11="改",
            word_12="鬓",
            word_13="毛",
            word_14="衰"
        },
        {
            seq=4,
            type=1,
            group=2,
            word_0="儿",
            word_1="童",
            word_2="相",
            word_3="见",
            word_4="不",
            word_5="相",
            word_6="识",
            word_7="，",
            word_8="笑",
            word_9="问",
            word_10=12,
            word_11="从",
            word_12=17,
            word_13=4,
            word_14="来"
        },
        {
            seq=5,
            type=0,
            group=3,
            word_0="横",
            word_1="看",
            word_2="成",
            word_3="岭",
            word_4=4,
            word_5=11,
            word_6=1,
            word_7="，",
            word_8="高",
            word_9="低",
            word_10=8,
            word_11=3,
            word_12="各",
            word_13="不",
            word_14="同"
        },
        {
            seq=6,
            type=1,
            group=3,
            word_0="不",
            word_1="识",
            word_2=14,
            word_3=10,
            word_4="真",
            word_5="面",
            word_6="目",
            word_7="，",
            word_8=7,
            word_9="缘",
            word_10="身",
            word_11="在",
            word_12=17,
            word_13=12,
            word_14=2
        }
    },
    word_group={
        {
            group=1,
            seq=1,
            word="思"
        },
        {
            group=1,
            seq=2,
            word="孤"
        },
        {
            group=1,
            seq=3,
            word="玉"
        },
        {
            group=1,
            seq=4,
            word="及"
        },
        {
            group=1,
            seq=5,
            word="云"
        },
        {
            group=1,
            seq=6,
            word="他"
        },
        {
            group=1,
            seq=7,
            word="何"
        },
        {
            group=1,
            seq=8,
            word="真"
        },
        {
            group=1,
            seq=9,
            word="门"
        },
        {
            group=1,
            seq=10,
            word="白"
        },
        {
            group=1,
            seq=11,
            word="之"
        },
        {
            group=1,
            seq=12,
            word="关"
        },
        {
            group=1,
            seq=13,
            word="万"
        },
        {
            group=1,
            seq=14,
            word="是"
        },
        {
            group=1,
            seq=15,
            word="须"
        },
        {
            group=1,
            seq=16,
            word="城"
        },
        {
            group=1,
            seq=17,
            word="需"
        },
        {
            group=1,
            seq=18,
            word="也"
        },
        {
            group=2,
            seq=1,
            word="音"
        },
        {
            group=2,
            seq=2,
            word="容"
        },
        {
            group=2,
            seq=3,
            word="乡"
        },
        {
            group=2,
            seq=4,
            word="处"
        },
        {
            group=2,
            seq=5,
            word="小"
        },
        {
            group=2,
            seq=6,
            word="少"
        },
        {
            group=2,
            seq=7,
            word="家"
        },
        {
            group=2,
            seq=8,
            word="离"
        },
        {
            group=2,
            seq=9,
            word="爹"
        },
        {
            group=2,
            seq=10,
            word="雷"
        },
        {
            group=2,
            seq=11,
            word="颜"
        },
        {
            group=2,
            seq=12,
            word="客"
        },
        {
            group=2,
            seq=13,
            word="知"
        },
        {
            group=2,
            seq=14,
            word="天"
        },
        {
            group=2,
            seq=15,
            word="少"
        },
        {
            group=2,
            seq=16,
            word="时"
        },
        {
            group=2,
            seq=17,
            word="何"
        },
        {
            group=2,
            seq=18,
            word="下"
        },
        {
            group=3,
            seq=1,
            word="峰"
        },
        {
            group=3,
            seq=2,
            word="层"
        },
        {
            group=3,
            seq=3,
            word="近"
        },
        {
            group=3,
            seq=4,
            word="侧"
        },
        {
            group=3,
            seq=5,
            word="此"
        },
        {
            group=3,
            seq=6,
            word="山"
        },
        {
            group=3,
            seq=7,
            word="只"
        },
        {
            group=3,
            seq=8,
            word="远"
        },
        {
            group=3,
            seq=9,
            word="黄"
        },
        {
            group=3,
            seq=10,
            word="山"
        },
        {
            group=3,
            seq=11,
            word="成"
        },
        {
            group=3,
            seq=12,
            word="高"
        },
        {
            group=3,
            seq=13,
            word="自"
        },
        {
            group=3,
            seq=14,
            word="庐"
        },
        {
            group=3,
            seq=15,
            word="大"
        },
        {
            group=3,
            seq=16,
            word="黄"
        },
        {
            group=3,
            seq=17,
            word="最"
        },
        {
            group=3,
            seq=18,
            word="中"
        }
    },
    other={
        {
            special_task_id=65230,
            last_task_id=65232,
            subject_talk_2=72318,
            subject_talk_3=72319,
            restart_talk=72317,
            fail_talk=72321,
            npc_id=589,
            special_bubble=130
        }
    }
}