local _default_val={
    music={
        combo_type=1,
        combo_score=110,
        music_name=""
    },
    button_pos={
        music_id=5,
        seq=1,
        time=5300,
        type=1,
        pos_x=0,
        pos_y=-94.5,
        link=0
    },
    button_type={
        disappear_time=120,
        perfect1=60,
        perfect2=110
    }
}
Config.gsls_story_auto={
    music={
        {
            music_id=1,
            audio=2000,
            time=6300,
            max_score=21978
        },
        {
            music_id=2,
            audio=2001,
            time=9600,
            max_score=30525
        },
        {
            music_id=3,
            audio=2002,
            time=9900,
            max_score=34188
        },
        {
            music_id=4,
            audio=2003,
            time=9300,
            max_score=31339
        },
        {
            music_id=5,
            audio=2004,
            time=9800,
            max_score=39072
        }
    },
    button_pos={
        {
            music_id=1,
            time=50,
            pos_x=-360,
            pos_y=-115
        },
        {
            music_id=1,
            seq=2,
            time=200,
            pos_x=302
        },
        {
            music_id=1,
            seq=3,
            time=400,
            pos_x=-339,
            pos_y=-371
        },
        {
            music_id=1,
            seq=4,
            time=600,
            pos_x=351,
            pos_y=-392
        },
        {
            music_id=1,
            seq=5,
            time=750,
            pos_x=-212,
            pos_y=-250
        },
        {
            music_id=1,
            seq=6,
            time=850,
            pos_x=229,
            pos_y=-250
        },
        {
            music_id=1,
            seq=7,
            time=1000,
            type=2,
            pos_x=135,
            pos_y=-190
        },
        {
            music_id=1,
            seq=8,
            time=1200,
            pos_x=-374,
            pos_y=-80
        },
        {
            music_id=1,
            seq=9,
            time=1300,
            pos_x=-190,
            pos_y=-216
        },
        {
            music_id=1,
            seq=10,
            time=1400,
            pos_y=-386
        },
        {
            music_id=1,
            seq=11,
            time=1500,
            pos_x=199,
            pos_y=-250
        },
        {
            music_id=1,
            seq=12,
            time=1600,
            pos_x=365
        },
        {
            music_id=1,
            seq=13,
            time=1750,
            type=3,
            pos_x=-122,
            pos_y=-95
        },
        {
            music_id=1,
            seq=14,
            time=1900,
            pos_x=-224,
            pos_y=-278
        },
        {
            music_id=1,
            seq=15,
            time=2000,
            pos_x=306
        },
        {
            music_id=1,
            seq=16,
            time=2100,
            pos_x=124
        },
        {
            music_id=1,
            seq=17,
            time=2200,
            pos_x=110
        },
        {
            music_id=1,
            seq=18,
            time=2300,
            pos_x=306
        },
        {
            music_id=1,
            seq=19,
            time=2500,
            type=2,
            pos_x=-99,
            pos_y=-360
        },
        {
            music_id=1,
            seq=20,
            time=2650,
            pos_x=-360
        },
        {
            music_id=1,
            seq=21,
            time=2800,
            pos_x=346,
            pos_y=-405.5
        },
        {
            music_id=1,
            seq=22,
            time=2900,
            pos_y=-231
        },
        {
            music_id=1,
            seq=23,
            time=3050,
            pos_x=-390,
            pos_y=-355
        },
        {
            music_id=1,
            seq=24,
            time=3200,
            pos_y=-105
        },
        {
            music_id=1,
            seq=25,
            time=3400,
            pos_x=266,
            pos_y=-250
        },
        {
            music_id=1,
            seq=26,
            time=3500,
            pos_x=378
        },
        {
            music_id=1,
            seq=27,
            time=3600,
            pos_x=382,
            pos_y=-250
        },
        {
            music_id=1,
            seq=28,
            time=3700,
            pos_x=384,
            pos_y=-405.5
        },
        {
            music_id=1,
            seq=29,
            time=3800,
            pos_x=-268,
            pos_y=-123
        },
        {
            music_id=1,
            seq=30,
            time=3900,
            pos_x=-250,
            pos_y=-250
        },
        {
            music_id=1,
            seq=31,
            time=4000,
            pos_x=-306,
            pos_y=-405.5
        },
        {
            music_id=1,
            seq=32,
            time=4140,
            type=4,
            pos_x=345,
            pos_y=-398
        },
        {
            music_id=1,
            seq=33,
            time=4360,
            pos_x=-343,
            pos_y=-228
        },
        {
            music_id=1,
            seq=34,
            time=4500,
            pos_x=-230,
            pos_y=-338
        },
        {
            music_id=1,
            seq=35,
            time=4600,
            pos_x=227,
            pos_y=-129
        },
        {
            music_id=1,
            seq=36,
            time=4700,
            pos_x=459,
            pos_y=-236
        },
        {
            music_id=1,
            seq=37,
            time=4800,
            pos_x=-339,
            pos_y=-128
        },
        {
            music_id=1,
            seq=38,
            time=4900,
            type=2,
            pos_y=-357
        },
        {
            music_id=1,
            seq=39,
            time=5080,
            pos_x=413,
            pos_y=-170
        },
        {
            music_id=1,
            seq=40,
            time=5200,
            pos_x=-252,
            pos_y=-154
        },
        {
            music_id=1,
            seq=41,
            time=5400,
            type=4,
            pos_y=-415
        },
        {
            music_id=1,
            seq=42,
            time=5500,
            pos_x=295,
            pos_y=-129
        },
        {
            music_id=1,
            seq=43,
            time=5620,
            pos_x=410,
            pos_y=-210
        },
        {
            music_id=1,
            seq=44,
            time=5800,
            type=3,
            pos_x=-152,
            pos_y=-238
        },
        {
            music_id=1,
            seq=45,
            time=5900,
            pos_x=-196
        },
        {
            music_id=1,
            seq=46,
            time=6000,
            pos_x=203
        },
        {
            music_id=2,
            time=50,
            pos_x=-357
        },
        {
            music_id=2,
            seq=2,
            time=200,
            pos_x=320
        },
        {
            music_id=2,
            seq=3,
            time=370,
            pos_x=-168,
            pos_y=-240
        },
        {
            music_id=2,
            seq=4,
            time=510,
            pos_x=162,
            pos_y=-250
        },
        {
            music_id=2,
            seq=5,
            time=670,
            type=2,
            pos_x=159,
            pos_y=-343
        },
        {
            music_id=2,
            seq=6,
            time=820,
            pos_x=-231,
            pos_y=-135
        },
        {
            music_id=2,
            seq=7,
            time=970,
            pos_x=271,
            pos_y=-359
        },
        {
            music_id=2,
            seq=8,
            time=1170,
            pos_x=-404,
            pos_y=-177
        },
        {
            music_id=2,
            seq=9,
            time=1350,
            type=3,
            pos_x=-405,
            pos_y=-138
        },
        {
            music_id=2,
            seq=10,
            time=1500,
            pos_x=-189,
            pos_y=-278
        },
        {
            music_id=2,
            seq=11,
            time=1630,
            pos_x=330,
            pos_y=-144
        },
        {
            music_id=2,
            seq=12,
            time=1790,
            pos_x=-212,
            pos_y=-343
        },
        {
            music_id=2,
            seq=13,
            time=1950,
            pos_x=-462,
            pos_y=-115
        },
        {
            music_id=2,
            seq=14,
            time=2100,
            pos_x=-129,
            pos_y=-154
        },
        {
            music_id=2,
            seq=15,
            time=2230,
            pos_x=-217,
            pos_y=-136
        },
        {
            music_id=2,
            seq=16,
            time=2330,
            pos_x=207,
            pos_y=-317
        },
        {
            music_id=2,
            seq=17,
            time=2410,
            type=4,
            pos_x=-251,
            pos_y=-396
        },
        {
            music_id=2,
            seq=18,
            time=2510,
            pos_x=365,
            pos_y=-154
        },
        {
            music_id=2,
            seq=19,
            time=2660,
            pos_y=-250
        },
        {
            music_id=2,
            seq=20,
            time=2790,
            pos_x=-495,
            pos_y=-381
        },
        {
            music_id=2,
            seq=21,
            time=2900,
            pos_x=342,
            pos_y=-107
        },
        {
            music_id=2,
            seq=22,
            time=3010,
            pos_x=345,
            pos_y=-333
        },
        {
            music_id=2,
            seq=23,
            time=3200,
            pos_x=-403,
            pos_y=-103
        },
        {
            music_id=2,
            seq=24,
            time=3300,
            pos_x=-232,
            pos_y=-316
        },
        {
            music_id=2,
            seq=25,
            time=3430,
            type=5,
            pos_x=390,
            pos_y=-102
        },
        {
            music_id=2,
            seq=26,
            time=3500,
            pos_x=-357
        },
        {
            music_id=2,
            seq=27,
            time=3600,
            pos_x=320
        },
        {
            music_id=2,
            seq=28,
            time=3700,
            pos_x=-168,
            pos_y=-240
        },
        {
            music_id=2,
            seq=29,
            time=3800,
            pos_x=162,
            pos_y=-250
        },
        {
            music_id=2,
            seq=30,
            time=3900,
            type=2,
            pos_x=159,
            pos_y=-343
        },
        {
            music_id=2,
            seq=31,
            time=4100,
            pos_x=-231,
            pos_y=-135
        },
        {
            music_id=2,
            seq=32,
            time=4280,
            pos_x=271,
            pos_y=-359
        },
        {
            music_id=2,
            seq=33,
            time=4390,
            pos_x=-404,
            pos_y=-177
        },
        {
            music_id=2,
            seq=34,
            time=4500,
            type=3,
            pos_x=-405,
            pos_y=-138
        },
        {
            music_id=2,
            seq=35,
            time=4680,
            pos_x=-189,
            pos_y=-278
        },
        {
            music_id=2,
            seq=36,
            time=4900,
            pos_x=330,
            pos_y=-144
        },
        {
            music_id=2,
            seq=37,
            time=5150,
            pos_x=-212,
            pos_y=-343
        },
        {
            music_id=2,
            seq=38,
            pos_x=-462,
            pos_y=-115
        },
        {
            music_id=2,
            seq=39,
            time=5450,
            pos_x=-129,
            pos_y=-154
        },
        {
            music_id=2,
            seq=40,
            time=5650,
            pos_x=-217,
            pos_y=-136
        },
        {
            music_id=2,
            seq=41,
            time=5790,
            pos_x=207,
            pos_y=-317
        },
        {
            music_id=2,
            seq=42,
            time=5900,
            type=4,
            pos_x=-251,
            pos_y=-396
        },
        {
            music_id=2,
            seq=43,
            time=6100,
            pos_x=365,
            pos_y=-154
        },
        {
            music_id=2,
            seq=44,
            time=6200,
            pos_y=-250
        },
        {
            music_id=2,
            seq=45,
            time=6300,
            pos_x=-495,
            pos_y=-381
        },
        {
            music_id=2,
            seq=46,
            time=6450,
            pos_x=342,
            pos_y=-107
        },
        {
            music_id=2,
            seq=47,
            time=6580,
            pos_x=345,
            pos_y=-333
        },
        {
            music_id=2,
            seq=48,
            time=6680,
            pos_x=-403,
            pos_y=-103
        },
        {
            music_id=2,
            seq=49,
            time=6780,
            pos_x=-232,
            pos_y=-316
        },
        {
            music_id=2,
            seq=50,
            time=6900,
            type=5,
            pos_x=390,
            pos_y=-102
        },
        {
            music_id=2,
            seq=51,
            time=7100,
            pos_x=-357
        },
        {
            music_id=2,
            seq=52,
            time=7300,
            pos_x=320
        },
        {
            music_id=2,
            seq=53,
            time=7400,
            pos_x=-168,
            pos_y=-240
        },
        {
            music_id=2,
            seq=54,
            time=7550,
            pos_x=162,
            pos_y=-250
        },
        {
            music_id=2,
            seq=55,
            time=7700,
            type=2,
            pos_x=159,
            pos_y=-343
        },
        {
            music_id=2,
            seq=56,
            time=7850,
            pos_x=-231,
            pos_y=-135
        },
        {
            music_id=2,
            seq=57,
            time=8000,
            pos_x=271,
            pos_y=-359
        },
        {
            music_id=2,
            seq=58,
            time=8150,
            pos_x=-404,
            pos_y=-177
        },
        {
            music_id=2,
            seq=59,
            time=8300,
            type=3,
            pos_x=-405,
            pos_y=-138
        },
        {
            music_id=2,
            seq=60,
            time=8450,
            pos_x=-189,
            pos_y=-278
        },
        {
            music_id=2,
            seq=61,
            time=8580,
            pos_x=330,
            pos_y=-144
        },
        {
            music_id=2,
            seq=62,
            time=8660,
            pos_x=-212,
            pos_y=-343
        },
        {
            music_id=2,
            seq=63,
            time=8770,
            pos_x=-462,
            pos_y=-115
        },
        {
            music_id=2,
            seq=64,
            time=8900,
            pos_x=-129,
            pos_y=-154
        },
        {
            music_id=2,
            seq=65,
            time=9000,
            pos_x=-217,
            pos_y=-136
        },
        {
            music_id=2,
            seq=66,
            time=9100,
            pos_x=207,
            pos_y=-317
        },
        {
            music_id=2,
            seq=67,
            time=9200,
            type=4,
            pos_x=-251,
            pos_y=-396
        },
        {
            music_id=2,
            seq=68,
            time=9300,
            pos_x=365,
            pos_y=-154
        },
        {
            music_id=2,
            seq=69,
            time=9400,
            pos_y=-250
        },
        {
            music_id=2,
            seq=70,
            time=9500,
            type=3,
            pos_x=-405,
            pos_y=-138
        },
        {
            music_id=3,
            time=40,
            pos_x=-120,
            pos_y=-199
        },
        {
            music_id=3,
            seq=2,
            time=160,
            pos_x=268,
            pos_y=-142
        },
        {
            music_id=3,
            seq=3,
            time=230,
            type=2,
            pos_y=-232
        },
        {
            music_id=3,
            seq=4,
            time=440,
            pos_x=194,
            pos_y=-170
        },
        {
            music_id=3,
            seq=5,
            time=590,
            pos_x=-343,
            pos_y=-295
        },
        {
            music_id=3,
            seq=6,
            time=730,
            pos_x=374,
            pos_y=-330
        },
        {
            music_id=3,
            seq=7,
            time=880,
            pos_x=-284,
            pos_y=-131
        },
        {
            music_id=3,
            seq=8,
            time=970,
            pos_x=-173,
            pos_y=-360
        },
        {
            music_id=3,
            seq=9,
            time=1080,
            type=4,
            pos_x=456,
            pos_y=-396
        },
        {
            music_id=3,
            seq=10,
            time=1200,
            pos_x=-474,
            pos_y=-254
        },
        {
            music_id=3,
            seq=11,
            time=1340,
            type=2,
            pos_x=104,
            pos_y=-392
        },
        {
            music_id=3,
            seq=12,
            time=1470,
            pos_x=337,
            pos_y=-131
        },
        {
            music_id=3,
            seq=13,
            time=1610,
            pos_x=-328,
            pos_y=-107
        },
        {
            music_id=3,
            seq=14,
            time=1760,
            pos_x=397,
            pos_y=-115
        },
        {
            music_id=3,
            seq=15,
            time=1910,
            pos_x=95,
            pos_y=-362
        },
        {
            music_id=3,
            seq=16,
            time=2050,
            pos_x=-253,
            pos_y=-256
        },
        {
            music_id=3,
            seq=17,
            time=2170,
            pos_x=370,
            pos_y=-133
        },
        {
            music_id=3,
            seq=18,
            time=2280,
            pos_x=375,
            pos_y=-318
        },
        {
            music_id=3,
            seq=19,
            time=2430,
            pos_x=-357,
            pos_y=-138
        },
        {
            music_id=3,
            seq=20,
            time=2530,
            pos_x=-109,
            pos_y=-139
        },
        {
            music_id=3,
            seq=21,
            time=2620,
            pos_x=115,
            pos_y=-142
        },
        {
            music_id=3,
            seq=22,
            time=2760,
            type=2,
            pos_x=464,
            pos_y=-368
        },
        {
            music_id=3,
            seq=23,
            time=2890,
            pos_x=289,
            pos_y=-102
        },
        {
            music_id=3,
            seq=24,
            time=3140,
            pos_x=-491,
            pos_y=-362
        },
        {
            music_id=3,
            seq=25,
            time=3280,
            pos_x=-210,
            pos_y=-184
        },
        {
            music_id=3,
            seq=26,
            time=3410,
            pos_x=-57,
            pos_y=-389
        },
        {
            music_id=3,
            seq=27,
            time=3550,
            pos_x=205,
            pos_y=-129
        },
        {
            music_id=3,
            seq=28,
            time=3690,
            pos_x=383,
            pos_y=-369
        },
        {
            music_id=3,
            seq=29,
            time=3820,
            pos_x=-333,
            pos_y=-129
        },
        {
            music_id=3,
            seq=30,
            time=3930,
            pos_x=-195,
            pos_y=-285
        },
        {
            music_id=3,
            seq=31,
            time=4020,
            pos_y=-405
        },
        {
            music_id=3,
            seq=32,
            time=4120,
            pos_x=167,
            pos_y=-275
        },
        {
            music_id=3,
            seq=33,
            time=4230,
            pos_x=312,
            pos_y=-118
        },
        {
            music_id=3,
            seq=34,
            time=4370,
            type=4,
            pos_x=-376,
            pos_y=-403
        },
        {
            music_id=3,
            seq=35,
            time=4510,
            type=2,
            pos_x=157,
            pos_y=-250
        },
        {
            music_id=3,
            seq=36,
            time=4670,
            type=5,
            pos_x=377,
            pos_y=-97
        },
        {
            music_id=3,
            seq=37,
            time=4740,
            pos_x=-120,
            pos_y=-199
        },
        {
            music_id=3,
            seq=38,
            time=4840,
            pos_x=268,
            pos_y=-142
        },
        {
            music_id=3,
            seq=39,
            time=5000,
            type=2,
            pos_y=-232
        },
        {
            music_id=3,
            seq=40,
            time=5100,
            pos_x=194,
            pos_y=-170
        },
        {
            music_id=3,
            seq=41,
            time=5200,
            pos_x=-343,
            pos_y=-295
        },
        {
            music_id=3,
            seq=42,
            pos_x=374,
            pos_y=-330
        },
        {
            music_id=3,
            seq=43,
            time=5500,
            pos_x=-284,
            pos_y=-131
        },
        {
            music_id=3,
            seq=44,
            time=5600,
            pos_x=-173,
            pos_y=-360
        },
        {
            music_id=3,
            seq=45,
            time=5800,
            type=4,
            pos_x=456,
            pos_y=-396
        },
        {
            music_id=3,
            seq=46,
            time=5900,
            pos_x=-474,
            pos_y=-254
        },
        {
            music_id=3,
            seq=47,
            time=6100,
            type=2,
            pos_x=104,
            pos_y=-392
        },
        {
            music_id=3,
            seq=48,
            time=6300,
            pos_x=337,
            pos_y=-131
        },
        {
            music_id=3,
            seq=49,
            time=6400,
            pos_x=-328,
            pos_y=-107
        },
        {
            music_id=3,
            seq=50,
            time=6500,
            pos_x=397,
            pos_y=-115
        },
        {
            music_id=3,
            seq=51,
            time=6600,
            pos_x=95,
            pos_y=-362
        },
        {
            music_id=3,
            seq=52,
            time=6700,
            pos_x=-253,
            pos_y=-256
        },
        {
            music_id=3,
            seq=53,
            time=6800,
            pos_x=370,
            pos_y=-133
        },
        {
            music_id=3,
            seq=54,
            time=7000,
            pos_x=375,
            pos_y=-318
        },
        {
            music_id=3,
            seq=55,
            time=7100,
            pos_x=-357,
            pos_y=-138
        },
        {
            music_id=3,
            seq=56,
            time=7300,
            pos_x=-109,
            pos_y=-139
        },
        {
            music_id=3,
            seq=57,
            time=7450,
            pos_x=115,
            pos_y=-142
        },
        {
            music_id=3,
            seq=58,
            time=7600,
            type=2,
            pos_x=464,
            pos_y=-368
        },
        {
            music_id=3,
            seq=59,
            time=7700,
            pos_x=289,
            pos_y=-102
        },
        {
            music_id=3,
            seq=60,
            time=7900,
            pos_x=-491,
            pos_y=-362
        },
        {
            music_id=3,
            seq=61,
            time=8000,
            pos_x=-210,
            pos_y=-184
        },
        {
            music_id=3,
            seq=62,
            time=8100,
            pos_x=-57,
            pos_y=-389
        },
        {
            music_id=3,
            seq=63,
            time=8200,
            pos_x=205,
            pos_y=-129
        },
        {
            music_id=3,
            seq=64,
            time=8300,
            pos_x=383,
            pos_y=-369
        },
        {
            music_id=3,
            seq=65,
            time=8400,
            pos_x=-333,
            pos_y=-129
        },
        {
            music_id=3,
            seq=66,
            time=8600,
            pos_x=-195,
            pos_y=-285
        },
        {
            music_id=3,
            seq=67,
            time=8750,
            pos_y=-405
        },
        {
            music_id=3,
            seq=68,
            time=8850,
            pos_x=167,
            pos_y=-275
        },
        {
            music_id=3,
            seq=69,
            time=9000,
            pos_x=312,
            pos_y=-118
        },
        {
            music_id=3,
            seq=70,
            time=9200,
            type=4,
            pos_x=-376,
            pos_y=-403
        },
        {
            music_id=3,
            seq=71,
            time=9300,
            type=2,
            pos_x=157,
            pos_y=-250
        },
        {
            music_id=3,
            seq=72,
            time=9400,
            type=5,
            pos_x=377,
            pos_y=-97
        },
        {
            music_id=4,
            time=80,
            pos_x=-404,
            pos_y=-189
        },
        {
            music_id=4,
            seq=2,
            time=210,
            pos_x=-165,
            pos_y=-353
        },
        {
            music_id=4,
            seq=3,
            time=390,
            pos_x=183,
            pos_y=-352
        },
        {
            music_id=4,
            seq=4,
            time=580,
            pos_x=434,
            pos_y=-161
        },
        {
            music_id=4,
            seq=5,
            time=870,
            pos_x=188,
            pos_y=-134
        },
        {
            music_id=4,
            seq=6,
            time=1070,
            pos_x=-219,
            pos_y=-145
        },
        {
            music_id=4,
            seq=7,
            time=1270,
            pos_x=-237,
            pos_y=-350
        },
        {
            music_id=4,
            seq=8,
            time=1450,
            pos_x=234,
            pos_y=-348
        },
        {
            music_id=4,
            seq=9,
            time=1680,
            pos_x=-361,
            pos_y=-159
        },
        {
            music_id=4,
            seq=10,
            time=1820,
            pos_x=-131,
            pos_y=-158
        },
        {
            music_id=4,
            seq=11,
            time=1980,
            type=2,
            pos_x=155,
            pos_y=-367
        },
        {
            music_id=4,
            seq=12,
            time=2110,
            pos_x=425,
            pos_y=-157
        },
        {
            music_id=4,
            seq=13,
            time=2270,
            pos_x=199,
            pos_y=-157
        },
        {
            music_id=4,
            seq=14,
            time=2490,
            type=3,
            pos_x=-156,
            pos_y=-371
        },
        {
            music_id=4,
            seq=15,
            time=2770,
            pos_x=-443,
            pos_y=-366
        },
        {
            music_id=4,
            seq=16,
            time=2870,
            pos_x=-439,
            pos_y=-133
        },
        {
            music_id=4,
            seq=17,
            time=3070,
            type=4,
            pos_x=-180,
            pos_y=-408
        },
        {
            music_id=4,
            seq=18,
            time=3360,
            pos_x=162,
            pos_y=-138
        },
        {
            music_id=4,
            seq=19,
            time=3400,
            pos_x=438,
            pos_y=-133
        },
        {
            music_id=4,
            seq=20,
            time=3450,
            pos_x=439,
            pos_y=-387
        },
        {
            music_id=4,
            seq=21,
            time=3480,
            pos_x=163,
            pos_y=-385
        },
        {
            music_id=4,
            seq=22,
            time=3640,
            pos_x=-173,
            pos_y=-373
        },
        {
            music_id=4,
            seq=23,
            time=3700,
            pos_x=-439,
            pos_y=-374
        },
        {
            music_id=4,
            seq=24,
            time=3930,
            pos_x=-378,
            pos_y=-150
        },
        {
            music_id=4,
            seq=25,
            time=4060,
            pos_x=-146,
            pos_y=-366
        },
        {
            music_id=4,
            seq=26,
            time=4230,
            pos_x=174,
            pos_y=-145
        },
        {
            music_id=4,
            seq=27,
            time=4350,
            pos_y=-250
        },
        {
            music_id=4,
            seq=28,
            time=4550,
            pos_x=-404,
            pos_y=-189
        },
        {
            music_id=4,
            seq=29,
            time=4650,
            pos_x=-165,
            pos_y=-353
        },
        {
            music_id=4,
            seq=30,
            time=4750,
            pos_x=183,
            pos_y=-352
        },
        {
            music_id=4,
            seq=31,
            time=4900,
            pos_x=434,
            pos_y=-161
        },
        {
            music_id=4,
            seq=32,
            time=5050,
            pos_x=188,
            pos_y=-134
        },
        {
            music_id=4,
            seq=33,
            time=5190,
            pos_x=-219,
            pos_y=-145
        },
        {
            music_id=4,
            seq=34,
            pos_x=-237,
            pos_y=-350
        },
        {
            music_id=4,
            seq=35,
            time=5420,
            pos_x=234,
            pos_y=-348
        },
        {
            music_id=4,
            seq=36,
            time=5580,
            pos_x=-361,
            pos_y=-159
        },
        {
            music_id=4,
            seq=37,
            time=5700,
            pos_x=-131,
            pos_y=-158
        },
        {
            music_id=4,
            seq=38,
            time=5810,
            type=2,
            pos_x=155,
            pos_y=-367
        },
        {
            music_id=4,
            seq=39,
            time=5950,
            pos_x=425,
            pos_y=-157
        },
        {
            music_id=4,
            seq=40,
            time=6100,
            pos_x=199,
            pos_y=-157
        },
        {
            music_id=4,
            seq=41,
            time=6250,
            type=3,
            pos_x=-156,
            pos_y=-371
        },
        {
            music_id=4,
            seq=42,
            time=6320,
            pos_x=-443,
            pos_y=-366
        },
        {
            music_id=4,
            seq=43,
            time=6420,
            pos_x=-439,
            pos_y=-133
        },
        {
            music_id=4,
            seq=44,
            time=6580,
            type=4,
            pos_x=-180,
            pos_y=-408
        },
        {
            music_id=4,
            seq=45,
            time=6700,
            pos_x=162,
            pos_y=-138
        },
        {
            music_id=4,
            seq=46,
            time=6800,
            pos_x=438,
            pos_y=-133
        },
        {
            music_id=4,
            seq=47,
            time=6900,
            pos_x=439,
            pos_y=-387
        },
        {
            music_id=4,
            seq=48,
            time=7000,
            pos_x=163,
            pos_y=-385
        },
        {
            music_id=4,
            seq=49,
            time=7100,
            pos_x=-173,
            pos_y=-373
        },
        {
            music_id=4,
            seq=50,
            time=7200,
            pos_x=-439,
            pos_y=-374
        },
        {
            music_id=4,
            seq=51,
            time=7300,
            pos_x=-378,
            pos_y=-150
        },
        {
            music_id=4,
            seq=52,
            time=7400,
            pos_x=-146,
            pos_y=-366
        },
        {
            music_id=4,
            seq=53,
            time=7500,
            pos_x=174,
            pos_y=-145
        },
        {
            music_id=4,
            seq=54,
            time=7600,
            pos_y=-250
        },
        {
            music_id=4,
            seq=55,
            time=7800,
            type=3,
            pos_x=-156,
            pos_y=-371
        },
        {
            music_id=4,
            seq=56,
            time=7950,
            pos_x=-443,
            pos_y=-366
        },
        {
            music_id=4,
            seq=57,
            time=8080,
            pos_x=-439,
            pos_y=-133
        },
        {
            music_id=4,
            seq=58,
            time=8200,
            type=4,
            pos_x=-180,
            pos_y=-408
        },
        {
            music_id=4,
            seq=59,
            time=8300,
            pos_x=162,
            pos_y=-138
        },
        {
            music_id=4,
            seq=60,
            time=8400,
            pos_x=438,
            pos_y=-133
        },
        {
            music_id=4,
            seq=61,
            time=8500,
            pos_x=439,
            pos_y=-387
        },
        {
            music_id=4,
            seq=62,
            time=8600,
            pos_x=163,
            pos_y=-385
        },
        {
            music_id=4,
            seq=63,
            time=8700,
            pos_x=-173,
            pos_y=-373
        },
        {
            music_id=4,
            seq=64,
            time=8800,
            pos_x=-439,
            pos_y=-374
        },
        {
            music_id=4,
            seq=65,
            time=8950,
            type=2,
            pos_x=155,
            pos_y=-367
        },
        {
            music_id=4,
            seq=66,
            time=9050,
            pos_x=199,
            pos_y=-157
        },
        {
            music_id=4,
            seq=67,
            time=9190,
            type=4,
            pos_x=-180,
            pos_y=-408
        },
        {
            time=70,
            pos_x=414,
            pos_y=-112
        },
        {
            seq=2,
            time=170,
            pos_x=192,
            pos_y=-342
        },
        {
            seq=3,
            time=280,
            pos_x=190,
            pos_y=-111
        },
        {
            seq=4,
            time=380,
            pos_x=418,
            pos_y=-343
        },
        {
            seq=5,
            time=570,
            pos_x=-411,
            pos_y=-111
        },
        {
            seq=6,
            time=680,
            pos_x=-184,
            pos_y=-343
        },
        {
            seq=7,
            time=770,
            pos_x=-190,
            pos_y=-109
        },
        {
            seq=8,
            time=850,
            pos_x=-407,
            pos_y=-342
        },
        {
            seq=9,
            time=990,
            type=2,
            pos_x=-124,
            pos_y=-131
        },
        {
            seq=10,
            time=1200,
            type=2,
            pos_x=156,
            pos_y=-371
        },
        {
            seq=11,
            time=1400,
            pos_x=202,
            pos_y=-119
        },
        {
            seq=12,
            time=1450,
            pos_x=466,
            pos_y=-118
        },
        {
            seq=13,
            time=1540,
            type=3,
            pos_x=174,
            pos_y=-364
        },
        {
            seq=14,
            time=1730,
            type=3,
            pos_x=-155,
            pos_y=-115
        },
        {
            seq=15,
            time=1940,
            pos_x=-187,
            pos_y=-355
        },
        {
            seq=16,
            time=1980,
            pos_x=-438,
            pos_y=-355
        },
        {
            seq=17,
            time=2190,
            pos_x=-335,
            pos_y=-143
        },
        {
            seq=18,
            time=2240,
            pos_x=-146,
            pos_y=-349
        },
        {
            seq=19,
            time=2280,
            pos_x=-190,
            pos_y=-381
        },
        {
            seq=20,
            time=2350,
            type=5,
            pos_x=421,
            pos_y=-85
        },
        {
            seq=21,
            time=2520,
            pos_x=434,
            pos_y=-111
        },
        {
            seq=22,
            time=2580,
            pos_x=193,
            pos_y=-325
        },
        {
            seq=23,
            time=2630,
            pos_x=-187,
            pos_y=-388
        },
        {
            seq=24,
            time=2710,
            type=5,
            pos_x=-445,
            pos_y=-95
        },
        {
            seq=25,
            time=3090,
            pos_x=-176,
            pos_y=-117
        },
        {
            seq=26,
            time=3180,
            pos_y=-371
        },
        {
            seq=27,
            time=3280,
            pos_x=170,
            pos_y=-113
        },
        {
            seq=28,
            time=3370,
            pos_x=396,
            pos_y=-366
        },
        {
            seq=29,
            time=3460,
            pos_x=393,
            pos_y=-116
        },
        {
            seq=30,
            time=3650,
            type=4,
            pos_x=224,
            pos_y=-405
        },
        {
            seq=31,
            time=3870,
            type=3,
            pos_x=-312,
            pos_y=-415
        },
        {
            seq=32,
            time=4060,
            pos_x=205,
            pos_y=-121
        },
        {
            seq=33,
            time=4160,
            pos_y=-389
        },
        {
            seq=34,
            time=4290,
            pos_x=-204,
            pos_y=-119
        },
        {
            seq=35,
            time=4390,
            pos_x=-473,
            pos_y=-392
        },
        {
            seq=36,
            time=4480,
            pos_x=-471,
            pos_y=-119
        },
        {
            seq=37,
            time=4660,
            type=4,
            pos_x=-212,
            pos_y=-415
        },
        {
            seq=38,
            time=4850,
            type=2,
            pos_x=321,
            pos_y=-415
        },
        {
            seq=39,
            time=4950,
            pos_x=414,
            pos_y=-112
        },
        {
            seq=40,
            time=5100,
            pos_x=192,
            pos_y=-342
        },
        {
            seq=41,
            time=5200,
            pos_x=190,
            pos_y=-111
        },
        {
            seq=42,
            pos_x=418,
            pos_y=-343
        },
        {
            seq=43,
            time=5400,
            pos_x=-411,
            pos_y=-111
        },
        {
            seq=44,
            time=5500,
            pos_x=-184,
            pos_y=-343
        },
        {
            seq=45,
            time=5600,
            pos_x=-190,
            pos_y=-109
        },
        {
            seq=46,
            time=5700,
            pos_x=-407,
            pos_y=-342
        },
        {
            seq=47,
            time=5900,
            type=2,
            pos_x=-124,
            pos_y=-131
        },
        {
            seq=48,
            time=6150,
            type=2,
            pos_x=156,
            pos_y=-371
        },
        {
            seq=49,
            time=6300,
            pos_x=202,
            pos_y=-119
        },
        {
            seq=50,
            time=6400,
            pos_x=466,
            pos_y=-118
        },
        {
            seq=51,
            time=6550,
            type=3,
            pos_x=174,
            pos_y=-364
        },
        {
            seq=52,
            time=6700,
            type=3,
            pos_x=-155,
            pos_y=-115
        },
        {
            seq=53,
            time=6800,
            pos_x=-187,
            pos_y=-355
        },
        {
            seq=54,
            time=6900,
            pos_x=-438,
            pos_y=-355
        },
        {
            seq=55,
            time=7000,
            pos_x=-335,
            pos_y=-143
        },
        {
            seq=56,
            time=7150,
            pos_x=-146,
            pos_y=-349
        },
        {
            seq=57,
            time=7250,
            pos_x=-190,
            pos_y=-381
        },
        {
            seq=58,
            time=7400,
            type=5,
            pos_x=421,
            pos_y=-85
        },
        {
            seq=59,
            time=7500,
            pos_x=434,
            pos_y=-111
        },
        {
            seq=60,
            time=7600,
            pos_x=193,
            pos_y=-325
        },
        {
            seq=61,
            time=7700,
            pos_x=-187,
            pos_y=-388
        },
        {
            seq=62,
            time=7850,
            type=5,
            pos_x=-445,
            pos_y=-95
        },
        {
            seq=63,
            time=8000,
            pos_x=-176,
            pos_y=-117
        },
        {
            seq=64,
            time=8100,
            pos_y=-371
        },
        {
            seq=65,
            time=8200,
            pos_x=170,
            pos_y=-113
        },
        {
            seq=66,
            time=8300,
            pos_x=396,
            pos_y=-366
        },
        {
            seq=67,
            time=8400,
            pos_x=393,
            pos_y=-116
        },
        {
            seq=68,
            time=8550,
            type=4,
            pos_x=224,
            pos_y=-405
        },
        {
            seq=69,
            time=8700,
            type=3,
            pos_x=-312,
            pos_y=-415
        },
        {
            seq=70,
            time=8800,
            pos_x=205,
            pos_y=-121
        },
        {
            seq=71,
            time=8900,
            pos_y=-389
        },
        {
            seq=72,
            time=9000,
            pos_x=-204,
            pos_y=-119
        },
        {
            seq=73,
            time=9100,
            pos_x=-473,
            pos_y=-392
        },
        {
            seq=74,
            time=9200,
            pos_x=-471,
            pos_y=-119
        },
        {
            seq=75,
            time=9400,
            type=4,
            pos_x=-212,
            pos_y=-415
        },
        {
            seq=76,
            time=9600,
            type=2,
            pos_x=321,
            pos_y=-415
        }
    },
    button_type={
        {
            type=1,
            perfect2=0
        },
        {
            type=2
        },
        {
            type=3
        },
        {
            type=4
        },
        {
            type=5
        },
        {
            type=6
        }
    },
    score_determine={
        {
            type=0,
            name="失误",
            score=0,
            before=70,
            after=60
        },
        {
            type=1,
            name="一般",
            score=200,
            before=50,
            after=40
        },
        {
            type=2,
            name="漂亮",
            score=300,
            before=40,
            after=30
        },
        {
            type=3,
            name="完美",
            score=370,
            before=20,
            after=20
        }
    },
    other={
        {
            hp=100,
            an_error=10
        }
    }
}
SetConfigDefaultVal(Config.gsls_story_auto,_default_val,nil,nil,nil)