local _default_val={
    skill_cfg={
        sign=101,
        skill_level=3,
        skill_name="落叶萧萧",
        target_type=2,
        target_num=5,
        asset_id_1="",
        asset_id_2="LuoYeXiaoXiao",
        asset_id_3=""
    },
    hallow_id={
        hallow_id=10,
        skill_id=431
    }
}
Config.hallow_skill_auto={
    skill_cfg={
        {
            skill_id=101,
            skill_level=1,
            target_type=1,
            target_num=2
        },
        {
            skill_id=102,
            skill_level=2,
            target_type=1
        },
        {
            skill_id=103,
            target_type=1,
            target_num=7
        },
        {
            skill_id=111,
            sign=102,
            skill_level=1,
            skill_name="灵魂震荡",
            target_type=1,
            target_num=2,
            asset_id_2="LingHunZhenDang"
        },
        {
            skill_id=112,
            sign=102,
            skill_level=2,
            skill_name="灵魂震荡",
            target_type=1,
            asset_id_2="LingHunZhenDang"
        },
        {
            skill_id=113,
            sign=102,
            skill_name="灵魂震荡",
            target_type=1,
            target_num=7,
            asset_id_2="LingHunZhenDang"
        },
        {
            skill_id=121,
            sign=103,
            skill_level=1,
            skill_name="魔能冲击",
            target_type=1,
            target_num=2,
            asset_id_2="MoNengChongJi"
        },
        {
            skill_id=122,
            sign=103,
            skill_level=2,
            skill_name="魔能冲击",
            target_type=1,
            asset_id_2="MoNengChongJi"
        },
        {
            skill_id=123,
            sign=103,
            skill_name="魔能冲击",
            target_type=1,
            target_num=7,
            asset_id_2="MoNengChongJi"
        },
        {
            skill_id=131,
            sign=104,
            skill_level=1,
            skill_name="魔能激发",
            target_type=1,
            target_num=2,
            asset_id_2="MoNengJiFa"
        },
        {
            skill_id=132,
            sign=104,
            skill_level=2,
            skill_name="魔能激发",
            target_type=1,
            asset_id_2="MoNengJiFa"
        },
        {
            skill_id=133,
            sign=104,
            skill_name="魔能激发",
            target_type=1,
            target_num=7,
            asset_id_2="MoNengJiFa"
        },
        {
            skill_id=141,
            sign=105,
            skill_level=1,
            skill_name="催魂夺命",
            target_type=1,
            target_num=2,
            asset_id_2="CuiHunDuoMing"
        },
        {
            skill_id=142,
            sign=105,
            skill_level=2,
            skill_name="催魂夺命",
            target_type=1,
            asset_id_2="CuiHunDuoMing"
        },
        {
            skill_id=143,
            sign=105,
            skill_name="催魂夺命",
            target_type=1,
            target_num=7,
            asset_id_2="CuiHunDuoMing"
        },
        {
            skill_id=151,
            sign=106,
            skill_level=1,
            skill_name="催魂夺魄",
            target_type=1,
            target_num=2,
            asset_id_2="CuiHunDuoPo"
        },
        {
            skill_id=152,
            sign=106,
            skill_level=2,
            skill_name="催魂夺魄",
            target_type=1,
            asset_id_2="CuiHunDuoPo"
        },
        {
            skill_id=153,
            sign=106,
            skill_name="催魂夺魄",
            target_type=1,
            target_num=7,
            asset_id_2="CuiHunDuoPo"
        },
        {
            skill_id=161,
            sign=107,
            skill_level=1,
            skill_name="破碎无双",
            target_type=1,
            target_num=1,
            asset_id_2="PoSuiWuShuang"
        },
        {
            skill_id=162,
            sign=107,
            skill_level=2,
            skill_name="破碎无双",
            target_type=1,
            target_num=3,
            asset_id_2="PoSuiWuShuang"
        },
        {
            skill_id=163,
            sign=107,
            skill_name="破碎无双",
            target_type=1,
            asset_id_2="PoSuiWuShuang"
        },
        {
            skill_id=171,
            sign=108,
            skill_level=1,
            skill_name="灵魂冲击",
            target_type=1,
            target_num=1,
            asset_id_2="LingHunChongJi"
        },
        {
            skill_id=172,
            sign=108,
            skill_level=2,
            skill_name="灵魂冲击",
            target_type=1,
            target_num=3,
            asset_id_2="LingHunChongJi"
        },
        {
            skill_id=173,
            sign=108,
            skill_name="灵魂冲击",
            target_type=1,
            asset_id_2="LingHunChongJi"
        },
        {
            skill_id=181,
            sign=109,
            skill_level=1,
            skill_name="诅咒之伤",
            target_type=1,
            target_num=1,
            asset_id_2="ZuZhouZhiShang"
        },
        {
            skill_id=182,
            sign=109,
            skill_level=2,
            skill_name="诅咒之伤",
            target_type=1,
            target_num=3,
            asset_id_2="ZuZhouZhiShang"
        },
        {
            skill_id=183,
            sign=109,
            skill_name="诅咒之伤",
            target_type=1,
            asset_id_2="ZuZhouZhiShang"
        },
        {
            skill_id=191,
            sign=110,
            skill_level=1,
            skill_name="淬毒汲取",
            target_type=1,
            target_num=2,
            asset_id_2="CuiDuJiQu"
        },
        {
            skill_id=192,
            sign=110,
            skill_level=2,
            skill_name="淬毒汲取",
            target_type=1,
            asset_id_2="CuiDuJiQu"
        },
        {
            skill_id=193,
            sign=110,
            skill_name="淬毒汲取",
            target_type=1,
            target_num=7,
            asset_id_2="CuiDuJiQu"
        },
        {
            skill_id=201,
            sign=111,
            skill_level=1,
            skill_name="急杀令",
            target_type=6,
            target_num=10,
            asset_id_2="JiShaLing"
        },
        {
            skill_id=202,
            sign=111,
            skill_level=2,
            skill_name="急杀令",
            target_type=6,
            target_num=10,
            asset_id_2="JiShaLing"
        },
        {
            skill_id=203,
            sign=111,
            skill_name="急杀令",
            target_type=6,
            target_num=10,
            asset_id_2="JiShaLing"
        },
        {
            skill_id=211,
            sign=112,
            skill_level=1,
            skill_name="断后斩",
            target_type=7,
            target_num=10,
            asset_id_2="DuanHouZhan"
        },
        {
            skill_id=212,
            sign=112,
            skill_level=2,
            skill_name="断后斩",
            target_type=7,
            target_num=10,
            asset_id_2="DuanHouZhan"
        },
        {
            skill_id=213,
            sign=112,
            skill_name="断后斩",
            target_type=7,
            target_num=10,
            asset_id_2="DuanHouZhan"
        },
        {
            skill_id=221,
            sign=113,
            skill_level=1,
            skill_name="回春咒",
            target_num=2,
            asset_id_2="HuiChunZhou"
        },
        {
            skill_id=222,
            sign=113,
            skill_level=2,
            skill_name="回春咒",
            asset_id_2="HuiChunZhou"
        },
        {
            skill_id=223,
            sign=113,
            skill_name="回春咒",
            target_num=7,
            asset_id_2="HuiChunZhou"
        },
        {
            skill_id=231,
            sign=114,
            skill_level=1,
            skill_name="广陵散",
            target_num=2,
            asset_id_2="GuangLingSan"
        },
        {
            skill_id=232,
            sign=114,
            skill_level=2,
            skill_name="广陵散",
            asset_id_2="GuangLingSan"
        },
        {
            skill_id=233,
            sign=114,
            skill_name="广陵散",
            target_num=7,
            asset_id_2="GuangLingSan"
        },
        {
            skill_id=241,
            sign=115,
            skill_level=1,
            skill_name="冰心咒",
            target_num=2,
            asset_id_2="BingXinZhou"
        },
        {
            skill_id=242,
            sign=115,
            skill_level=2,
            skill_name="冰心咒",
            asset_id_2="BingXinZhou"
        },
        {
            skill_id=243,
            sign=115,
            skill_name="冰心咒",
            target_num=7,
            asset_id_2="BingXinZhou"
        },
        {
            skill_id=251,
            sign=116,
            skill_level=1,
            skill_name="元阳•风水",
            target_num=2,
            asset_id_2="YuanYangFengShuiXuLi"
        },
        {
            skill_id=252,
            sign=116,
            skill_level=2,
            skill_name="元阳•风水",
            asset_id_2="YuanYangFengShuiXuLi"
        },
        {
            skill_id=253,
            sign=116,
            skill_name="元阳•风水",
            target_num=7,
            asset_id_2="YuanYangFengShuiXuLi"
        },
        {
            skill_id=261,
            sign=117,
            skill_level=1,
            skill_name="元阳•地火",
            target_num=2,
            asset_id_2="YuanYangDiHuoXuLi"
        },
        {
            skill_id=262,
            sign=117,
            skill_level=2,
            skill_name="元阳•地火",
            asset_id_2="YuanYangDiHuoXuLi"
        },
        {
            skill_id=263,
            sign=117,
            skill_name="元阳•地火",
            target_num=7,
            asset_id_2="YuanYangDiHuoXuLi"
        },
        {
            skill_id=271,
            sign=118,
            skill_level=1,
            skill_name="元阳•火风",
            target_num=2,
            asset_id_2="YuanYangHuoFengXuLi"
        },
        {
            skill_id=272,
            sign=118,
            skill_level=2,
            skill_name="元阳•火风",
            asset_id_2="YuanYangHuoFengXuLi"
        },
        {
            skill_id=273,
            sign=118,
            skill_name="元阳•火风",
            target_num=7,
            asset_id_2="YuanYangHuoFengXuLi"
        },
        {
            skill_id=281,
            sign=119,
            skill_level=1,
            skill_name="元阳•水地",
            target_num=2,
            asset_id_2="YuanYangShuiDiXuLi"
        },
        {
            skill_id=282,
            sign=119,
            skill_level=2,
            skill_name="元阳•水地",
            asset_id_2="YuanYangShuiDiXuLi"
        },
        {
            skill_id=283,
            sign=119,
            skill_name="元阳•水地",
            target_num=7,
            asset_id_2="YuanYangShuiDiXuLi"
        },
        {
            skill_id=291,
            sign=120,
            skill_level=1,
            skill_name="玉净散",
            target_num=2,
            asset_id_2="YuJingSanXuLi"
        },
        {
            skill_id=292,
            sign=120,
            skill_level=2,
            skill_name="玉净散",
            asset_id_2="YuJingSanXuLi"
        },
        {
            skill_id=293,
            sign=120,
            skill_name="玉净散",
            target_num=7,
            asset_id_2="YuJingSanXuLi"
        },
        {
            skill_id=301,
            sign=121,
            skill_level=1,
            skill_name="清心散",
            target_num=2,
            asset_id_2="QingXinSan"
        },
        {
            skill_id=302,
            sign=121,
            skill_level=2,
            skill_name="清心散",
            asset_id_2="QingXinSan"
        },
        {
            skill_id=303,
            sign=121,
            skill_name="清心散",
            target_num=7,
            asset_id_2="QingXinSan"
        },
        {
            skill_id=311,
            sign=122,
            skill_level=1,
            skill_name="心如水",
            target_num=1,
            asset_id_2="XinRuiShui"
        },
        {
            skill_id=312,
            sign=122,
            skill_level=2,
            skill_name="心如水",
            target_num=3,
            asset_id_2="XinRuiShui"
        },
        {
            skill_id=313,
            sign=122,
            skill_name="心如水",
            asset_id_2="XinRuiShui"
        },
        {
            skill_id=321,
            sign=123,
            skill_level=1,
            skill_name="回魂咒",
            target_num=1,
            asset_id_2="HuiHunZhou"
        },
        {
            skill_id=322,
            sign=123,
            skill_level=2,
            skill_name="回魂咒",
            target_num=3,
            asset_id_2="HuiHunZhou"
        },
        {
            skill_id=323,
            sign=123,
            skill_name="回魂咒",
            asset_id_2="HuiHunZhou"
        },
        {
            skill_id=331,
            sign=124,
            skill_level=1,
            skill_name="归墟骨幡",
            target_num=1,
            asset_id_2="GuiXuGuFanSkill"
        },
        {
            skill_id=332,
            sign=124,
            skill_level=2,
            skill_name="归墟骨幡",
            target_num=3,
            asset_id_2="GuiXuGuFanSkill"
        },
        {
            skill_id=333,
            sign=124,
            skill_name="归墟骨幡",
            asset_id_2="GuiXuGuFanSkill"
        },
        {
            skill_id=341,
            sign=125,
            skill_level=1,
            skill_name="波澜不惊",
            target_num=1,
            asset_id_2="BoLanBuJingSkill"
        },
        {
            skill_id=342,
            sign=125,
            skill_level=2,
            skill_name="波澜不惊",
            target_num=2,
            asset_id_2="BoLanBuJingSkill"
        },
        {
            skill_id=343,
            sign=125,
            skill_name="波澜不惊",
            target_num=4,
            asset_id_2="BoLanBuJingSkill"
        },
        {
            skill_id=351,
            sign=126,
            skill_level=1,
            skill_name="精神集中",
            target_num=1,
            asset_id_2="JingShenJiZhong"
        },
        {
            skill_id=352,
            sign=126,
            skill_level=2,
            skill_name="精神集中",
            target_num=3,
            asset_id_2="JingShenJiZhong"
        },
        {
            skill_id=353,
            sign=126,
            skill_name="精神集中",
            asset_id_2="JingShenJiZhong"
        },
        {
            skill_id=361,
            sign=127,
            skill_level=1,
            skill_name="禁疗术",
            target_type=1,
            target_num=1,
            asset_id_2="JinLiaoShu"
        },
        {
            skill_id=362,
            sign=127,
            skill_level=2,
            skill_name="禁疗术",
            target_type=1,
            target_num=3,
            asset_id_2="JinLiaoShu"
        },
        {
            skill_id=363,
            sign=127,
            skill_name="禁疗术",
            target_type=1,
            asset_id_2="JinLiaoShu"
        },
        {
            skill_id=371,
            sign=128,
            skill_level=1,
            skill_name="石猴附身",
            target_type=1,
            target_num=1,
            asset_id_2="ShiHouFuShen"
        },
        {
            skill_id=372,
            sign=128,
            skill_level=2,
            skill_name="石猴附身",
            target_type=1,
            target_num=3,
            asset_id_2="ShiHouFuShen"
        },
        {
            skill_id=373,
            sign=128,
            skill_name="石猴附身",
            target_type=1,
            asset_id_2="ShiHouFuShen"
        },
        {
            skill_id=381,
            sign=129,
            skill_level=1,
            skill_name="乾坤遮天",
            target_type=11,
            asset_id_2="QianKunZheTian"
        },
        {
            skill_id=391,
            sign=130,
            skill_level=1,
            skill_name="乾坤破阵",
            target_type=1,
            target_num=2,
            asset_id_2="QianKunPoZhen"
        },
        {
            skill_id=392,
            sign=130,
            skill_level=2,
            skill_name="乾坤破阵",
            target_type=1,
            asset_id_2="QianKunPoZhen"
        },
        {
            skill_id=393,
            sign=130,
            skill_name="乾坤破阵",
            target_type=1,
            target_num=7,
            asset_id_2="QianKunPoZhen"
        },
        {
            skill_id=401,
            sign=131,
            skill_level=1,
            skill_name="乾坤伏魔",
            target_type=8,
            target_num=1,
            asset_id_2="QianKunFuMo"
        },
        {
            skill_id=402,
            sign=131,
            skill_level=2,
            skill_name="乾坤伏魔",
            target_type=8,
            target_num=2,
            asset_id_2="QianKunFuMo"
        },
        {
            skill_id=403,
            sign=131,
            skill_name="乾坤伏魔",
            target_type=8,
            target_num=4,
            asset_id_2="QianKunFuMo"
        },
        {
            skill_id=413,
            sign=132,
            skill_name="遁入虚空",
            target_type=11,
            target_num=3,
            asset_id_2="DunRuXuKong"
        },
        {
            skill_id=423,
            sign=133,
            skill_name="晶清诀",
            target_num=10,
            asset_id_2="JingQingJue"
        },
        {
            skill_id=431,
            sign=134,
            skill_level=1,
            skill_name="落宝神针",
            target_type=3,
            target_num=1,
            asset_id_2="LuoBaoShenZhen"
        },
        {
            skill_id=432,
            sign=134,
            skill_level=2,
            skill_name="落宝神针",
            target_type=3,
            target_num=2,
            asset_id_2="LuoBaoShenZhen"
        },
        {
            skill_id=433,
            sign=134,
            skill_name="落宝神针",
            target_type=3,
            target_num=4,
            asset_id_2="LuoBaoShenZhen"
        }
    },
    fit_in_effec={},
    hallow_id={
        {
            hallow_id=0,
            skill_id=101
        },
        {
            hallow_id=0,
            skill_id=102
        },
        {
            hallow_id=0,
            skill_id=103
        },
        {
            hallow_id=1,
            skill_id=111
        },
        {
            hallow_id=1,
            skill_id=112
        },
        {
            hallow_id=1,
            skill_id=113
        },
        {
            hallow_id=2,
            skill_id=121
        },
        {
            hallow_id=2,
            skill_id=122
        },
        {
            hallow_id=2,
            skill_id=123
        },
        {
            hallow_id=3,
            skill_id=131
        },
        {
            hallow_id=3,
            skill_id=132
        },
        {
            hallow_id=3,
            skill_id=133
        },
        {
            hallow_id=4,
            skill_id=141
        },
        {
            hallow_id=4,
            skill_id=142
        },
        {
            hallow_id=4,
            skill_id=143
        },
        {
            hallow_id=5,
            skill_id=101
        },
        {
            hallow_id=5,
            skill_id=102
        },
        {
            hallow_id=5,
            skill_id=103
        },
        {
            hallow_id=5,
            skill_id=151
        },
        {
            hallow_id=5,
            skill_id=152
        },
        {
            hallow_id=5,
            skill_id=153
        },
        {
            hallow_id=6,
            skill_id=111
        },
        {
            hallow_id=6,
            skill_id=112
        },
        {
            hallow_id=6,
            skill_id=113
        },
        {
            hallow_id=6,
            skill_id=161
        },
        {
            hallow_id=6,
            skill_id=162
        },
        {
            hallow_id=6,
            skill_id=163
        },
        {
            hallow_id=7,
            skill_id=121
        },
        {
            hallow_id=7,
            skill_id=122
        },
        {
            hallow_id=7,
            skill_id=123
        },
        {
            hallow_id=7,
            skill_id=171
        },
        {
            hallow_id=7,
            skill_id=172
        },
        {
            hallow_id=7,
            skill_id=173
        },
        {
            hallow_id=8,
            skill_id=131
        },
        {
            hallow_id=8,
            skill_id=132
        },
        {
            hallow_id=8,
            skill_id=133
        },
        {
            hallow_id=8,
            skill_id=201
        },
        {
            hallow_id=8,
            skill_id=202
        },
        {
            hallow_id=8,
            skill_id=203
        },
        {
            hallow_id=9,
            skill_id=141
        },
        {
            hallow_id=9,
            skill_id=142
        },
        {
            hallow_id=9,
            skill_id=143
        },
        {
            hallow_id=9,
            skill_id=211
        },
        {
            hallow_id=9,
            skill_id=212
        },
        {
            hallow_id=9,
            skill_id=213
        },
        {
            skill_id=151
        },
        {
            skill_id=152
        },
        {
            skill_id=153
        },
        {
            skill_id=161
        },
        {
            skill_id=162
        },
        {
            skill_id=163
        },
        {
            skill_id=181
        },
        {
            skill_id=182
        },
        {
            skill_id=183
        },
        {},
        {
            skill_id=432
        },
        {
            skill_id=433
        },
        {
            hallow_id=11,
            skill_id=161
        },
        {
            hallow_id=11,
            skill_id=162
        },
        {
            hallow_id=11,
            skill_id=163
        },
        {
            hallow_id=11,
            skill_id=171
        },
        {
            hallow_id=11,
            skill_id=172
        },
        {
            hallow_id=11,
            skill_id=173
        },
        {
            hallow_id=11,
            skill_id=191
        },
        {
            hallow_id=11,
            skill_id=192
        },
        {
            hallow_id=11,
            skill_id=193
        },
        {
            hallow_id=11
        },
        {
            hallow_id=11,
            skill_id=432
        },
        {
            hallow_id=11,
            skill_id=433
        },
        {
            hallow_id=12,
            skill_id=171
        },
        {
            hallow_id=12,
            skill_id=172
        },
        {
            hallow_id=12,
            skill_id=173
        },
        {
            hallow_id=12,
            skill_id=181
        },
        {
            hallow_id=12,
            skill_id=182
        },
        {
            hallow_id=12,
            skill_id=183
        },
        {
            hallow_id=12,
            skill_id=201
        },
        {
            hallow_id=12,
            skill_id=202
        },
        {
            hallow_id=12,
            skill_id=203
        },
        {
            hallow_id=12
        },
        {
            hallow_id=12,
            skill_id=432
        },
        {
            hallow_id=12,
            skill_id=433
        },
        {
            hallow_id=13,
            skill_id=181
        },
        {
            hallow_id=13,
            skill_id=182
        },
        {
            hallow_id=13,
            skill_id=183
        },
        {
            hallow_id=13,
            skill_id=191
        },
        {
            hallow_id=13,
            skill_id=192
        },
        {
            hallow_id=13,
            skill_id=193
        },
        {
            hallow_id=13,
            skill_id=211
        },
        {
            hallow_id=13,
            skill_id=212
        },
        {
            hallow_id=13,
            skill_id=213
        },
        {
            hallow_id=13
        },
        {
            hallow_id=13,
            skill_id=432
        },
        {
            hallow_id=13,
            skill_id=433
        },
        {
            hallow_id=14,
            skill_id=191
        },
        {
            hallow_id=14,
            skill_id=192
        },
        {
            hallow_id=14,
            skill_id=193
        },
        {
            hallow_id=14,
            skill_id=201
        },
        {
            hallow_id=14,
            skill_id=202
        },
        {
            hallow_id=14,
            skill_id=203
        },
        {
            hallow_id=14,
            skill_id=211
        },
        {
            hallow_id=14,
            skill_id=212
        },
        {
            hallow_id=14,
            skill_id=213
        },
        {
            hallow_id=14
        },
        {
            hallow_id=14,
            skill_id=432
        },
        {
            hallow_id=14,
            skill_id=433
        },
        {
            hallow_id=15,
            skill_id=251
        },
        {
            hallow_id=15,
            skill_id=252
        },
        {
            hallow_id=15,
            skill_id=253
        },
        {
            hallow_id=16,
            skill_id=261
        },
        {
            hallow_id=16,
            skill_id=262
        },
        {
            hallow_id=16,
            skill_id=263
        },
        {
            hallow_id=17,
            skill_id=271
        },
        {
            hallow_id=17,
            skill_id=272
        },
        {
            hallow_id=17,
            skill_id=273
        },
        {
            hallow_id=18,
            skill_id=281
        },
        {
            hallow_id=18,
            skill_id=282
        },
        {
            hallow_id=18,
            skill_id=283
        },
        {
            hallow_id=19,
            skill_id=221
        },
        {
            hallow_id=19,
            skill_id=222
        },
        {
            hallow_id=19,
            skill_id=223
        },
        {
            hallow_id=20,
            skill_id=231
        },
        {
            hallow_id=20,
            skill_id=232
        },
        {
            hallow_id=20,
            skill_id=233
        },
        {
            hallow_id=20,
            skill_id=361
        },
        {
            hallow_id=20,
            skill_id=362
        },
        {
            hallow_id=20,
            skill_id=363
        },
        {
            hallow_id=21,
            skill_id=241
        },
        {
            hallow_id=21,
            skill_id=242
        },
        {
            hallow_id=21,
            skill_id=243
        },
        {
            hallow_id=21,
            skill_id=351
        },
        {
            hallow_id=21,
            skill_id=352
        },
        {
            hallow_id=21,
            skill_id=353
        },
        {
            hallow_id=22,
            skill_id=291
        },
        {
            hallow_id=22,
            skill_id=292
        },
        {
            hallow_id=22,
            skill_id=293
        },
        {
            hallow_id=22,
            skill_id=341
        },
        {
            hallow_id=22,
            skill_id=342
        },
        {
            hallow_id=22,
            skill_id=343
        },
        {
            hallow_id=23,
            skill_id=301
        },
        {
            hallow_id=23,
            skill_id=302
        },
        {
            hallow_id=23,
            skill_id=303
        },
        {
            hallow_id=23,
            skill_id=331
        },
        {
            hallow_id=23,
            skill_id=332
        },
        {
            hallow_id=23,
            skill_id=333
        },
        {
            hallow_id=24,
            skill_id=311
        },
        {
            hallow_id=24,
            skill_id=312
        },
        {
            hallow_id=24,
            skill_id=313
        },
        {
            hallow_id=24,
            skill_id=321
        },
        {
            hallow_id=24,
            skill_id=322
        },
        {
            hallow_id=24,
            skill_id=323
        },
        {
            hallow_id=25,
            skill_id=371
        },
        {
            hallow_id=25,
            skill_id=372
        },
        {
            hallow_id=25,
            skill_id=373
        },
        {
            hallow_id=25,
            skill_id=381
        },
        {
            hallow_id=25,
            skill_id=391
        },
        {
            hallow_id=25,
            skill_id=392
        },
        {
            hallow_id=25,
            skill_id=393
        },
        {
            hallow_id=25
        },
        {
            hallow_id=25,
            skill_id=432
        },
        {
            hallow_id=25,
            skill_id=433
        },
        {
            hallow_id=26,
            skill_id=361
        },
        {
            hallow_id=26,
            skill_id=362
        },
        {
            hallow_id=26,
            skill_id=363
        },
        {
            hallow_id=26,
            skill_id=391
        },
        {
            hallow_id=26,
            skill_id=392
        },
        {
            hallow_id=26,
            skill_id=393
        },
        {
            hallow_id=26,
            skill_id=401
        },
        {
            hallow_id=26,
            skill_id=402
        },
        {
            hallow_id=26,
            skill_id=403
        },
        {
            hallow_id=26
        },
        {
            hallow_id=26,
            skill_id=432
        },
        {
            hallow_id=26,
            skill_id=433
        },
        {
            hallow_id=27,
            skill_id=351
        },
        {
            hallow_id=27,
            skill_id=352
        },
        {
            hallow_id=27,
            skill_id=353
        },
        {
            hallow_id=27,
            skill_id=401
        },
        {
            hallow_id=27,
            skill_id=402
        },
        {
            hallow_id=27,
            skill_id=403
        },
        {
            hallow_id=27,
            skill_id=413
        },
        {
            hallow_id=27
        },
        {
            hallow_id=27,
            skill_id=432
        },
        {
            hallow_id=27,
            skill_id=433
        },
        {
            hallow_id=28,
            skill_id=341
        },
        {
            hallow_id=28,
            skill_id=342
        },
        {
            hallow_id=28,
            skill_id=343
        },
        {
            hallow_id=28,
            skill_id=413
        },
        {
            hallow_id=28,
            skill_id=423
        },
        {
            hallow_id=28
        },
        {
            hallow_id=28,
            skill_id=432
        },
        {
            hallow_id=28,
            skill_id=433
        },
        {
            hallow_id=29,
            skill_id=331
        },
        {
            hallow_id=29,
            skill_id=332
        },
        {
            hallow_id=29,
            skill_id=333
        },
        {
            hallow_id=29,
            skill_id=371
        },
        {
            hallow_id=29,
            skill_id=372
        },
        {
            hallow_id=29,
            skill_id=373
        },
        {
            hallow_id=29,
            skill_id=423
        },
        {
            hallow_id=29
        },
        {
            hallow_id=29,
            skill_id=432
        },
        {
            hallow_id=29,
            skill_id=433
        }
    },
    assist_effect={}
}
SetConfigDefaultVal(Config.hallow_skill_auto,_default_val,nil,nil,nil)