local _default_val={
    reward={
        section_start=1,
        section_end=21,
        seq1=0,
        time=30,
        quantity=40,
        name="30秒·终极挑战",
        picture=1
    }
}
local _itemlist={
    i_26349_1_1={
        item_id=26349,
        num=1,
        is_bind=1
    },
    i_28522_1_1={
        item_id=28522,
        num=1,
        is_bind=1
    },
    i_26812_1_1={
        item_id=26812,
        num=1,
        is_bind=1
    },
    i_28555_1_1={
        item_id=28555,
        num=1,
        is_bind=1
    },
    i_29077_1_1={
        item_id=29077,
        num=1,
        is_bind=1
    },
    i_27540_1_1={
        item_id=27540,
        num=1,
        is_bind=1
    },
    i_29076_1_1={
        item_id=29076,
        num=1,
        is_bind=1
    }
}
Config.happy_look_auto={
    other={
        {
            frequency=3,
            reward_item={
                [0]=_itemlist.i_26349_1_1
            },
            preview={
                [0]=_itemlist.i_26349_1_1
            },
            desc="规则说明：\n1.选择一对相同的花牌连线，将相同的两张牌用三根以内的直线连在一起消除即可。\n2.每一局里玩家需要在规定的时间内消除所有的花牌，游戏中可重置花牌顺序。\n3.挑战失败将无法获得挑战宝盒，获得参与宝袋。"
        }
    },
    reward={
        {
            type=0,
            reward_item={
                [0]=_itemlist.i_26349_1_1,
                [1]=_itemlist.i_28522_1_1,
                [2]=_itemlist.i_26812_1_1
            }
        },
        {
            type=1,
            seq1=1,
            time=60,
            quantity=50,
            reward_item={
                [0]=_itemlist.i_26349_1_1,
                [1]=_itemlist.i_28522_1_1
            },
            name="60秒·超级挑战",
            picture=2
        },
        {
            type=2,
            seq1=2,
            time=120,
            quantity=60,
            reward_item={
                [0]=_itemlist.i_26349_1_1,
                [1]=_itemlist.i_28555_1_1
            },
            name="120秒·高级挑战",
            picture=3
        },
        {
            type=3,
            section_start=22,
            section_end=0,
            reward_item={
                [0]=_itemlist.i_26349_1_1,
                [1]=_itemlist.i_29077_1_1,
                [2]=_itemlist.i_27540_1_1
            }
        },
        {
            type=4,
            section_start=22,
            section_end=0,
            seq1=1,
            time=60,
            quantity=50,
            reward_item={
                [0]=_itemlist.i_26349_1_1,
                [1]=_itemlist.i_29077_1_1
            },
            name="60秒·超级挑战",
            picture=2
        },
        {
            type=5,
            section_start=22,
            section_end=0,
            seq1=2,
            time=120,
            quantity=60,
            reward_item={
                [0]=_itemlist.i_26349_1_1,
                [1]=_itemlist.i_29076_1_1
            },
            name="120秒·高级挑战",
            picture=3
        }
    }
}
SetConfigDefaultVal(Config.happy_look_auto,_default_val,nil,nil,nil)