local _default_val={
    target={
        cond_type=1
    }
}
local _itemlist={
    i_22014_1_1={
        item_id=22014,
        num=1,
        is_bind=1
    },
    i_27398_3_1={
        item_id=27398,
        num=3,
        is_bind=1
    },
    i_28516_1_1={
        item_id=28516,
        num=1,
        is_bind=1
    },
    i_27402_1_1={
        item_id=27402,
        num=1,
        is_bind=1
    }
}
Config.hundred_god_boss_auto={
    target={
        {
            id=1,
            finish_reward=_itemlist.i_22014_1_1,
            target="目标1",
            task_dec="<color=#FF6E00>【目标1】</color>等级达到21级",
            param=21,
            task_show="等级达到21级"
        },
        {
            id=2,
            finish_reward=_itemlist.i_27398_3_1,
            target="目标2",
            task_dec="<color=#FF6E00>【目标2】</color>通关主线：刑天的踪迹",
            cond_type=2,
            param=440,
            task_show="完成刑天主线"
        },
        {
            id=3,
            finish_reward=_itemlist.i_28516_1_1,
            target="目标3",
            task_dec="<color=#FF6E00>【目标3】</color>完成今日门派任务",
            cond_type=3,
            param=1,
            task_show="完成门派任务"
        },
        {
            id=4,
            finish_reward=_itemlist.i_27402_1_1,
            target="目标4",
            task_dec="<color=#FF6E00>【目标4】</color>等级达到35级",
            param=35,
            task_show="等级达到35级"
        }
    },
    other={
        {
            prepose_task=363,
            during_time=48,
            partner_id=21,
            show_id=25541,
            guide_id=124
        }
    }
}
SetConfigDefaultVal(Config.hundred_god_boss_auto,_default_val,nil,nil,nil)