local _default_val={
    image_chan={
        image_name="月照君",
        avartar_type=1,
        color_1="skin0",
        color_2="skin1",
        color_3="skin2",
        color_4="skin3",
        camp_level=1,
        icon_id="head1"
    },
    create_role={
        role_id=1,
        model_id=1,
        advancement_level=1,
        color_id=1
    },
    role={
        sex=0,
        role_desc_1="",
        role_desc_2="",
        role_desc_3=""
    },
    image_job={
        avartar_type=1,
        camp_level=1
    },
    head_job={
        avartar_type=1,
        type=2,
        advancement_level=0,
        surface_id=0
    }
}
Config.image_change_auto={
    image_chan={
        {
            image_id=10001,
            image_show_id=1,
            color_list="1,6,4,9"
        },
        {
            image_id=10002,
            camp_level=2,
            image_show_id=2,
            color_list="7,6,5,2"
        },
        {
            image_id=10003,
            camp_level=3,
            image_show_id=3,
            color_list="1,8,3,10"
        },
        {
            image_id=10004,
            camp_level=4,
            image_show_id=4,
            color_list="2,5,13,10"
        },
        {
            image_id=10005,
            camp_level=5,
            image_show_id=5,
            color_list="9,4,13,10"
        },
        {
            image_id=10006,
            camp_level=6,
            image_show_id=6,
            color_list="7,5,6,11"
        },
        {
            image_id=20001,
            image_name="花偶",
            avartar_type=2,
            icon_id="head2",
            image_show_id=7,
            color_list="1,2,9,4"
        },
        {
            image_id=20002,
            image_name="花偶",
            avartar_type=2,
            camp_level=2,
            icon_id="head2",
            image_show_id=8,
            color_list="12,3,2,7"
        },
        {
            image_id=20003,
            image_name="花偶",
            avartar_type=2,
            camp_level=3,
            icon_id="head2",
            image_show_id=9,
            color_list="1,5,3,7"
        },
        {
            image_id=20004,
            image_name="花偶",
            avartar_type=2,
            camp_level=4,
            icon_id="head2",
            image_show_id=10,
            color_list="2,5,7,10"
        },
        {
            image_id=20005,
            image_name="花偶",
            avartar_type=2,
            camp_level=5,
            icon_id="head2",
            image_show_id=11,
            color_list="9,2,4,3"
        },
        {
            image_id=20006,
            image_name="花偶",
            avartar_type=2,
            camp_level=6,
            icon_id="head2",
            image_show_id=12,
            color_list="7,1,2,3"
        },
        {
            image_id=30001,
            image_name="猫耳娘",
            avartar_type=3,
            icon_id="head3",
            image_show_id=13,
            color_list="1,5,2,3"
        },
        {
            image_id=30002,
            image_name="猫耳娘",
            avartar_type=3,
            camp_level=2,
            icon_id="head3",
            image_show_id=14,
            color_list="7,12,2,3"
        },
        {
            image_id=30003,
            image_name="猫耳娘",
            avartar_type=3,
            camp_level=3,
            icon_id="head3",
            image_show_id=15,
            color_list="3,10,13,8"
        },
        {
            image_id=30004,
            image_name="猫耳娘",
            avartar_type=3,
            camp_level=4,
            icon_id="head3",
            image_show_id=16,
            color_list="2,10,5,3"
        },
        {
            image_id=30005,
            image_name="猫耳娘",
            avartar_type=3,
            camp_level=5,
            icon_id="head3",
            image_show_id=17,
            color_list="9,13,10,4"
        },
        {
            image_id=30006,
            image_name="猫耳娘",
            avartar_type=3,
            camp_level=6,
            icon_id="head3",
            image_show_id=18,
            color_list="7,3,2,13"
        },
        {
            image_id=40001,
            image_name="涂魂",
            avartar_type=4,
            icon_id="head4",
            image_show_id=19,
            color_list="4,5,2,1"
        },
        {
            image_id=40002,
            image_name="涂魂",
            avartar_type=4,
            camp_level=2,
            icon_id="head4",
            image_show_id=20,
            color_list="7,2,3,10"
        },
        {
            image_id=40003,
            image_name="涂魂",
            avartar_type=4,
            camp_level=3,
            icon_id="head4",
            image_show_id=21,
            color_list="3,9,2,8"
        },
        {
            image_id=40004,
            image_name="涂魂",
            avartar_type=4,
            camp_level=4,
            icon_id="head4",
            image_show_id=22,
            color_list="2,5,3,10"
        },
        {
            image_id=40005,
            image_name="涂魂",
            avartar_type=4,
            camp_level=5,
            icon_id="head4",
            image_show_id=23,
            color_list="9,7,12,10"
        },
        {
            image_id=40006,
            image_name="涂魂",
            avartar_type=4,
            camp_level=6,
            icon_id="head4",
            image_show_id=24,
            color_list="7,4,9,2"
        },
        {
            image_id=50001,
            image_name="半月",
            avartar_type=5,
            icon_id="head5",
            image_show_id=25,
            color_list="1,2,5,3"
        },
        {
            image_id=50002,
            image_name="半月",
            avartar_type=5,
            camp_level=2,
            icon_id="head5",
            image_show_id=26,
            color_list="7,3,2,1"
        },
        {
            image_id=50003,
            image_name="半月",
            avartar_type=5,
            camp_level=3,
            icon_id="head5",
            image_show_id=27,
            color_list="3,5,7,2"
        },
        {
            image_id=50004,
            image_name="半月",
            avartar_type=5,
            camp_level=4,
            icon_id="head5",
            image_show_id=28,
            color_list="2,5,6,7"
        },
        {
            image_id=50005,
            image_name="半月",
            avartar_type=5,
            camp_level=5,
            icon_id="head5",
            image_show_id=29,
            color_list="9,2,7,5"
        },
        {
            image_id=50006,
            image_name="半月",
            avartar_type=5,
            camp_level=6,
            icon_id="head5",
            image_show_id=30,
            color_list="7,10,13,2"
        },
        {
            image_id=60001,
            image_name="角男",
            avartar_type=6,
            icon_id="head6",
            image_show_id=31,
            color_list="1,2,3,4"
        },
        {
            image_id=60002,
            image_name="角男",
            avartar_type=6,
            camp_level=2,
            icon_id="head6",
            image_show_id=32,
            color_list="4,2,1,3"
        },
        {
            image_id=60003,
            image_name="角男",
            avartar_type=6,
            camp_level=3,
            icon_id="head6",
            image_show_id=33,
            color_list="2,13,7,3"
        },
        {
            image_id=60004,
            image_name="角男",
            avartar_type=6,
            camp_level=4,
            icon_id="head6",
            image_show_id=34,
            color_list="2,5,3,4"
        },
        {
            image_id=60005,
            image_name="角男",
            avartar_type=6,
            camp_level=5,
            icon_id="head6",
            image_show_id=35,
            color_list="6,11,9,4"
        },
        {
            image_id=60006,
            image_name="角男",
            avartar_type=6,
            camp_level=6,
            icon_id="head6",
            image_show_id=36,
            color_list="2,13,6,7"
        }
    },
    create_role={
        {
            pic_id=1
        },
        {
            pic_id=2,
            color_id=2
        },
        {
            pic_id=3,
            color_id=3
        },
        {
            pic_id=4,
            color_id=4
        },
        {
            pic_id=5,
            model_id=2,
            advancement_level=2
        },
        {
            pic_id=6,
            model_id=2,
            advancement_level=2,
            color_id=2
        },
        {
            pic_id=7,
            model_id=2,
            advancement_level=2,
            color_id=3
        },
        {
            pic_id=8,
            model_id=2,
            advancement_level=2,
            color_id=4
        },
        {
            pic_id=9,
            model_id=3,
            advancement_level=3
        },
        {
            pic_id=10,
            model_id=3,
            advancement_level=3,
            color_id=2
        },
        {
            pic_id=11,
            model_id=3,
            advancement_level=3,
            color_id=3
        },
        {
            pic_id=12,
            model_id=3,
            advancement_level=3,
            color_id=4
        },
        {
            pic_id=13,
            model_id=4,
            advancement_level=4
        },
        {
            pic_id=14,
            model_id=4,
            advancement_level=4,
            color_id=2
        },
        {
            pic_id=15,
            model_id=4,
            advancement_level=4,
            color_id=3
        },
        {
            pic_id=16,
            model_id=4,
            advancement_level=4,
            color_id=4
        },
        {
            role_id=2,
            pic_id=17,
            model_id=5
        },
        {
            role_id=2,
            pic_id=18,
            model_id=5,
            color_id=2
        },
        {
            role_id=2,
            pic_id=19,
            model_id=5,
            color_id=3
        },
        {
            role_id=2,
            pic_id=20,
            model_id=5,
            color_id=4
        },
        {
            role_id=2,
            pic_id=21,
            model_id=6,
            advancement_level=2
        },
        {
            role_id=2,
            pic_id=22,
            model_id=6,
            advancement_level=2,
            color_id=2
        },
        {
            role_id=2,
            pic_id=23,
            model_id=6,
            advancement_level=2,
            color_id=3
        },
        {
            role_id=2,
            pic_id=24,
            model_id=6,
            advancement_level=2,
            color_id=4
        },
        {
            role_id=2,
            pic_id=25,
            model_id=7,
            advancement_level=3
        },
        {
            role_id=2,
            pic_id=26,
            model_id=7,
            advancement_level=3,
            color_id=2
        },
        {
            role_id=2,
            pic_id=27,
            model_id=7,
            advancement_level=3,
            color_id=3
        },
        {
            role_id=2,
            pic_id=28,
            model_id=7,
            advancement_level=3,
            color_id=4
        },
        {
            role_id=2,
            pic_id=29,
            model_id=8,
            advancement_level=4
        },
        {
            role_id=2,
            pic_id=30,
            model_id=8,
            advancement_level=4,
            color_id=2
        },
        {
            role_id=2,
            pic_id=31,
            model_id=8,
            advancement_level=4,
            color_id=3
        },
        {
            role_id=2,
            pic_id=32,
            model_id=8,
            advancement_level=4,
            color_id=4
        },
        {
            role_id=3,
            pic_id=33,
            model_id=9
        },
        {
            role_id=3,
            pic_id=34,
            model_id=9,
            color_id=2
        },
        {
            role_id=3,
            pic_id=35,
            model_id=9,
            color_id=3
        },
        {
            role_id=3,
            pic_id=36,
            model_id=9,
            color_id=4
        },
        {
            role_id=3,
            pic_id=37,
            model_id=10,
            advancement_level=2
        },
        {
            role_id=3,
            pic_id=38,
            model_id=10,
            advancement_level=2,
            color_id=2
        },
        {
            role_id=3,
            pic_id=39,
            model_id=0,
            advancement_level=2,
            color_id=3
        },
        {
            role_id=3,
            pic_id=40,
            model_id=10,
            advancement_level=2,
            color_id=4
        },
        {
            role_id=3,
            pic_id=41,
            model_id=11,
            advancement_level=3
        },
        {
            role_id=3,
            pic_id=42,
            model_id=11,
            advancement_level=3,
            color_id=2
        },
        {
            role_id=3,
            pic_id=43,
            model_id=11,
            advancement_level=3,
            color_id=3
        },
        {
            role_id=3,
            pic_id=44,
            model_id=11,
            advancement_level=3,
            color_id=4
        },
        {
            role_id=3,
            pic_id=45,
            model_id=12,
            advancement_level=4
        },
        {
            role_id=3,
            pic_id=46,
            model_id=12,
            advancement_level=4,
            color_id=2
        },
        {
            role_id=3,
            pic_id=47,
            model_id=12,
            advancement_level=4,
            color_id=3
        },
        {
            role_id=3,
            pic_id=48,
            model_id=12,
            advancement_level=4,
            color_id=4
        },
        {
            role_id=4,
            pic_id=49,
            model_id=13
        },
        {
            role_id=4,
            pic_id=50,
            model_id=13,
            color_id=2
        },
        {
            role_id=4,
            pic_id=51,
            model_id=13,
            color_id=3
        },
        {
            role_id=4,
            pic_id=52,
            model_id=13,
            color_id=4
        },
        {
            role_id=4,
            pic_id=53,
            model_id=14,
            advancement_level=2
        },
        {
            role_id=4,
            pic_id=54,
            model_id=14,
            advancement_level=2,
            color_id=2
        },
        {
            role_id=4,
            pic_id=55,
            model_id=14,
            advancement_level=2,
            color_id=3
        },
        {
            role_id=4,
            pic_id=56,
            model_id=14,
            advancement_level=2,
            color_id=4
        },
        {
            role_id=4,
            pic_id=57,
            model_id=15,
            advancement_level=3
        },
        {
            role_id=4,
            pic_id=58,
            model_id=15,
            advancement_level=3,
            color_id=2
        },
        {
            role_id=4,
            pic_id=59,
            model_id=15,
            advancement_level=3,
            color_id=3
        },
        {
            role_id=4,
            pic_id=60,
            model_id=15,
            advancement_level=3,
            color_id=4
        },
        {
            role_id=4,
            pic_id=61,
            model_id=16,
            advancement_level=4
        },
        {
            role_id=4,
            pic_id=62,
            model_id=16,
            advancement_level=4,
            color_id=2
        },
        {
            role_id=4,
            pic_id=63,
            model_id=16,
            advancement_level=4,
            color_id=3
        },
        {
            role_id=4,
            pic_id=64,
            model_id=16,
            advancement_level=4,
            color_id=4
        },
        {
            role_id=5,
            pic_id=65,
            model_id=17
        },
        {
            role_id=5,
            pic_id=66,
            model_id=17,
            color_id=2
        },
        {
            role_id=5,
            pic_id=67,
            model_id=17,
            color_id=3
        },
        {
            role_id=5,
            pic_id=68,
            model_id=17,
            color_id=4
        },
        {
            role_id=5,
            pic_id=69,
            model_id=18,
            advancement_level=2
        },
        {
            role_id=5,
            pic_id=70,
            model_id=18,
            advancement_level=2,
            color_id=2
        },
        {
            role_id=5,
            pic_id=71,
            model_id=18,
            advancement_level=2,
            color_id=3
        },
        {
            role_id=5,
            pic_id=72,
            model_id=18,
            advancement_level=2,
            color_id=4
        },
        {
            role_id=5,
            pic_id=73,
            model_id=19,
            advancement_level=3
        },
        {
            role_id=5,
            pic_id=74,
            model_id=19,
            advancement_level=3,
            color_id=2
        },
        {
            role_id=5,
            pic_id=75,
            model_id=19,
            advancement_level=3,
            color_id=3
        },
        {
            role_id=5,
            pic_id=76,
            model_id=19,
            advancement_level=3,
            color_id=4
        },
        {
            role_id=5,
            pic_id=77,
            model_id=20,
            advancement_level=4
        },
        {
            role_id=5,
            pic_id=78,
            model_id=20,
            advancement_level=4,
            color_id=2
        },
        {
            role_id=5,
            pic_id=79,
            model_id=20,
            advancement_level=4,
            color_id=3
        },
        {
            role_id=5,
            pic_id=80,
            model_id=20,
            advancement_level=4,
            color_id=4
        },
        {
            role_id=6,
            pic_id=81,
            model_id=21
        },
        {
            role_id=6,
            pic_id=82,
            model_id=21,
            color_id=2
        },
        {
            role_id=6,
            pic_id=83,
            model_id=21,
            color_id=3
        },
        {
            role_id=6,
            pic_id=84,
            model_id=21,
            color_id=4
        },
        {
            role_id=6,
            pic_id=85,
            model_id=22,
            advancement_level=2
        },
        {
            role_id=6,
            pic_id=86,
            model_id=22,
            advancement_level=2,
            color_id=2
        },
        {
            role_id=6,
            pic_id=87,
            model_id=22,
            advancement_level=2,
            color_id=3
        },
        {
            role_id=6,
            pic_id=88,
            model_id=22,
            advancement_level=2,
            color_id=4
        },
        {
            role_id=6,
            pic_id=89,
            model_id=23,
            advancement_level=3
        },
        {
            role_id=6,
            pic_id=90,
            model_id=23,
            advancement_level=3,
            color_id=2
        },
        {
            role_id=6,
            pic_id=91,
            model_id=23,
            advancement_level=3,
            color_id=3
        },
        {
            role_id=6,
            pic_id=92,
            model_id=23,
            advancement_level=3,
            color_id=4
        },
        {
            role_id=6,
            pic_id=93,
            model_id=24,
            advancement_level=4
        },
        {
            role_id=6,
            pic_id=94,
            model_id=24,
            advancement_level=4,
            color_id=2
        },
        {
            role_id=6,
            pic_id=95,
            model_id=24,
            advancement_level=4,
            color_id=3
        },
        {
            role_id=6,
            pic_id=96,
            model_id=24,
            advancement_level=4,
            color_id=4
        }
    },
    role={
        {
            seq=1,
            role_id=1,
            role_name="月照君",
            role_desc_3="无言独上西楼月如钩"
        },
        {
            seq=3,
            role_id=2,
            role_name="花偶",
            role_desc_1="不与花为偶",
            role_desc_2="终遣与谁言"
        },
        {
            seq=5,
            role_id=3,
            role_name="猫耳娘",
            role_desc_3="雪猫戏扑风花影"
        },
        {
            seq=2,
            role_id=4,
            role_name="涂魂",
            sex=1,
            role_desc_1="诗界千年靡靡风",
            role_desc_2="兵魂销尽国魂空"
        },
        {
            seq=4,
            role_id=5,
            role_name="半月",
            sex=1,
            role_desc_1="海上升明月",
            role_desc_2="天涯共此时"
        },
        {
            seq=6,
            role_id=6,
            role_name="角男",
            sex=1,
            role_desc_1="身既死兮神以灵",
            role_desc_2="子魂魄兮为鬼雄"
        }
    },
    image_job={
        {
            image_show_id=1,
            job_id="501|601|701|801"
        },
        {
            image_show_id=2,
            camp_level=2,
            job_id="502|602|702|802"
        },
        {
            image_show_id=3,
            camp_level=3,
            job_id="503|603|703|803"
        },
        {
            image_show_id=4,
            camp_level=4,
            job_id="504|604|704|804"
        },
        {
            image_show_id=5,
            camp_level=5,
            job_id="505|605|705|805"
        },
        {
            image_show_id=6,
            camp_level=6,
            job_id="506|606|706|806"
        },
        {
            image_show_id=7,
            avartar_type=2,
            job_id="701|801|601|301"
        },
        {
            image_show_id=8,
            avartar_type=2,
            camp_level=2,
            job_id="702|802|602|302"
        },
        {
            image_show_id=9,
            avartar_type=2,
            camp_level=3,
            job_id="703|803|603|303"
        },
        {
            image_show_id=10,
            avartar_type=2,
            camp_level=4,
            job_id="704|804|604|304"
        },
        {
            image_show_id=11,
            avartar_type=2,
            camp_level=5,
            job_id="705|805|605|305"
        },
        {
            image_show_id=12,
            avartar_type=2,
            camp_level=6,
            job_id="706|806|606|306"
        },
        {
            image_show_id=13,
            avartar_type=3,
            job_id="201|401|501|701"
        },
        {
            image_show_id=14,
            avartar_type=3,
            camp_level=2,
            job_id="202|402|502|702"
        },
        {
            image_show_id=15,
            avartar_type=3,
            camp_level=3,
            job_id="203|403|503|703"
        },
        {
            image_show_id=16,
            avartar_type=3,
            camp_level=4,
            job_id="204|404|504|704"
        },
        {
            image_show_id=17,
            avartar_type=3,
            camp_level=5,
            job_id="205|405|505|705"
        },
        {
            image_show_id=18,
            avartar_type=3,
            camp_level=6,
            job_id="206|406|506|706"
        },
        {
            image_show_id=19,
            avartar_type=4,
            job_id="301|101|401"
        },
        {
            image_show_id=20,
            avartar_type=4,
            camp_level=2,
            job_id="302|102|402"
        },
        {
            image_show_id=21,
            avartar_type=4,
            camp_level=3,
            job_id="303|103|403"
        },
        {
            image_show_id=22,
            avartar_type=4,
            camp_level=4,
            job_id="304|104|404"
        },
        {
            image_show_id=23,
            avartar_type=4,
            camp_level=5,
            job_id="305|105|405"
        },
        {
            image_show_id=24,
            avartar_type=4,
            camp_level=6,
            job_id="306|106|406"
        },
        {
            image_show_id=25,
            avartar_type=5,
            job_id="801|301|101"
        },
        {
            image_show_id=26,
            avartar_type=5,
            camp_level=2,
            job_id="802|302|102"
        },
        {
            image_show_id=27,
            avartar_type=5,
            camp_level=3,
            job_id="803|303|103"
        },
        {
            image_show_id=28,
            avartar_type=5,
            camp_level=4,
            job_id="804|304|104"
        },
        {
            image_show_id=29,
            avartar_type=5,
            camp_level=5,
            job_id="805|305|105"
        },
        {
            image_show_id=30,
            avartar_type=5,
            camp_level=6,
            job_id="806|306|106"
        },
        {
            image_show_id=31,
            avartar_type=6,
            job_id="501|201|601|101"
        },
        {
            image_show_id=32,
            avartar_type=6,
            camp_level=2,
            job_id="502|202|602|102"
        },
        {
            image_show_id=33,
            avartar_type=6,
            camp_level=3,
            job_id="503|203|603|103"
        },
        {
            image_show_id=34,
            avartar_type=6,
            camp_level=4,
            job_id="504|204|604|104"
        },
        {
            image_show_id=35,
            avartar_type=6,
            camp_level=5,
            job_id="505|205|605|105"
        },
        {
            image_show_id=36,
            avartar_type=6,
            camp_level=6,
            job_id="506|206|606|106"
        }
    },
    head_job={
        [1001]={
            avatar_id=1001,
            type=1,
            advancement_level=1
        },
        [1002]={
            avatar_id=1002,
            type=1,
            advancement_level=2
        },
        [1003]={
            avatar_id=1003,
            type=1,
            advancement_level=3
        },
        [1004]={
            avatar_id=1004,
            type=1,
            advancement_level=4
        },
        [1005]={
            avatar_id=1005,
            type=1,
            advancement_level=5
        },
        [1006]={
            avatar_id=1006,
            type=1,
            advancement_level=6
        },
        [1101]={
            avatar_id=1101,
            surface_id=1
        },
        [1102]={
            avatar_id=1102,
            surface_id=2
        },
        [1103]={
            avatar_id=1103,
            surface_id=3
        },
        [1104]={
            avatar_id=1104,
            surface_id=4
        },
        [1105]={
            avatar_id=1105,
            surface_id=5
        },
        [1106]={
            avatar_id=1106,
            surface_id=6
        },
        [1107]={
            avatar_id=1107,
            surface_id=7
        },
        [1108]={
            avatar_id=1108,
            surface_id=8
        },
        [1109]={
            avatar_id=1109,
            surface_id=9
        },
        [1110]={
            avatar_id=1110,
            surface_id=10
        },
        [1111]={
            avatar_id=1111,
            surface_id=11
        },
        [1112]={
            avatar_id=1112,
            surface_id=12
        },
        [1113]={
            avatar_id=1113,
            surface_id=13
        },
        [1114]={
            avatar_id=1114,
            surface_id=14
        },
        [1115]={
            avatar_id=1115,
            surface_id=15
        },
        [1116]={
            avatar_id=1116,
            surface_id=16
        },
        [1117]={
            avatar_id=1117,
            surface_id=17
        },
        [1118]={
            avatar_id=1118,
            surface_id=18
        },
        [1119]={
            avatar_id=1119,
            surface_id=19
        },
        [1120]={
            avatar_id=1120,
            surface_id=20
        },
        [1122]={
            avatar_id=1122,
            surface_id=22
        },
        [2001]={
            avatar_id=2001,
            avartar_type=2,
            type=1,
            advancement_level=1
        },
        [2002]={
            avatar_id=2002,
            avartar_type=2,
            type=1,
            advancement_level=2
        },
        [2003]={
            avatar_id=2003,
            avartar_type=2,
            type=1,
            advancement_level=3
        },
        [2004]={
            avatar_id=2004,
            avartar_type=2,
            type=1,
            advancement_level=4
        },
        [2005]={
            avatar_id=2005,
            avartar_type=2,
            type=1,
            advancement_level=5
        },
        [2006]={
            avatar_id=2006,
            avartar_type=2,
            type=1,
            advancement_level=6
        },
        [2101]={
            avatar_id=2101,
            avartar_type=2,
            surface_id=1
        },
        [2102]={
            avatar_id=2102,
            avartar_type=2,
            surface_id=2
        },
        [2103]={
            avatar_id=2103,
            avartar_type=2,
            surface_id=3
        },
        [2104]={
            avatar_id=2104,
            avartar_type=2,
            surface_id=4
        },
        [2105]={
            avatar_id=2105,
            avartar_type=2,
            surface_id=5
        },
        [2106]={
            avatar_id=2106,
            avartar_type=2,
            surface_id=6
        },
        [2107]={
            avatar_id=2107,
            avartar_type=2,
            surface_id=7
        },
        [2108]={
            avatar_id=2108,
            avartar_type=2,
            surface_id=8
        },
        [2109]={
            avatar_id=2109,
            avartar_type=2,
            surface_id=9
        },
        [2110]={
            avatar_id=2110,
            avartar_type=2,
            surface_id=10
        },
        [2111]={
            avatar_id=2111,
            avartar_type=2,
            surface_id=11
        },
        [2112]={
            avatar_id=2112,
            avartar_type=2,
            surface_id=12
        },
        [2113]={
            avatar_id=2113,
            avartar_type=2,
            surface_id=13
        },
        [2114]={
            avatar_id=2114,
            avartar_type=2,
            surface_id=14
        },
        [2115]={
            avatar_id=2115,
            avartar_type=2,
            surface_id=15
        },
        [2116]={
            avatar_id=2116,
            avartar_type=2,
            surface_id=16
        },
        [2117]={
            avatar_id=2117,
            avartar_type=2,
            surface_id=17
        },
        [2118]={
            avatar_id=2118,
            avartar_type=2,
            surface_id=18
        },
        [2119]={
            avatar_id=2119,
            avartar_type=2,
            surface_id=19
        },
        [2120]={
            avatar_id=2120,
            avartar_type=2,
            surface_id=20
        },
        [2122]={
            avatar_id=2122,
            avartar_type=2,
            surface_id=22
        },
        [3001]={
            avatar_id=3001,
            avartar_type=3,
            type=1,
            advancement_level=1
        },
        [3002]={
            avatar_id=3002,
            avartar_type=3,
            type=1,
            advancement_level=2
        },
        [3003]={
            avatar_id=3003,
            avartar_type=3,
            type=1,
            advancement_level=3
        },
        [3004]={
            avatar_id=3004,
            avartar_type=3,
            type=1,
            advancement_level=4
        },
        [3005]={
            avatar_id=3005,
            avartar_type=3,
            type=1,
            advancement_level=5
        },
        [3006]={
            avatar_id=3006,
            avartar_type=3,
            type=1,
            advancement_level=6
        },
        [3101]={
            avatar_id=3101,
            avartar_type=3,
            surface_id=1
        },
        [3102]={
            avatar_id=3102,
            avartar_type=3,
            surface_id=2
        },
        [3103]={
            avatar_id=3103,
            avartar_type=3,
            surface_id=3
        },
        [3104]={
            avatar_id=3104,
            avartar_type=3,
            surface_id=4
        },
        [3105]={
            avatar_id=3105,
            avartar_type=3,
            surface_id=5
        },
        [3106]={
            avatar_id=3106,
            avartar_type=3,
            surface_id=6
        },
        [3107]={
            avatar_id=3107,
            avartar_type=3,
            surface_id=7
        },
        [3108]={
            avatar_id=3108,
            avartar_type=3,
            surface_id=8
        },
        [3109]={
            avatar_id=3109,
            avartar_type=3,
            surface_id=9
        },
        [3110]={
            avatar_id=3110,
            avartar_type=3,
            surface_id=10
        },
        [3111]={
            avatar_id=3111,
            avartar_type=3,
            surface_id=11
        },
        [3112]={
            avatar_id=3112,
            avartar_type=3,
            surface_id=12
        },
        [3113]={
            avatar_id=3113,
            avartar_type=3,
            surface_id=13
        },
        [3114]={
            avatar_id=3114,
            avartar_type=3,
            surface_id=14
        },
        [3115]={
            avatar_id=3115,
            avartar_type=3,
            surface_id=15
        },
        [3116]={
            avatar_id=3116,
            avartar_type=3,
            surface_id=16
        },
        [3117]={
            avatar_id=3117,
            avartar_type=3,
            surface_id=17
        },
        [3118]={
            avatar_id=3118,
            avartar_type=3,
            surface_id=18
        },
        [3119]={
            avatar_id=3119,
            avartar_type=3,
            surface_id=19
        },
        [3120]={
            avatar_id=3120,
            avartar_type=3,
            surface_id=20
        },
        [3122]={
            avatar_id=3122,
            avartar_type=3,
            surface_id=22
        },
        [4001]={
            avatar_id=4001,
            avartar_type=4,
            type=1,
            advancement_level=1
        },
        [4002]={
            avatar_id=4002,
            avartar_type=4,
            type=1,
            advancement_level=2
        },
        [4003]={
            avatar_id=4003,
            avartar_type=4,
            type=1,
            advancement_level=3
        },
        [4004]={
            avatar_id=4004,
            avartar_type=4,
            type=1,
            advancement_level=4
        },
        [4005]={
            avatar_id=4005,
            avartar_type=4,
            type=1,
            advancement_level=5
        },
        [4006]={
            avatar_id=4006,
            avartar_type=4,
            type=1,
            advancement_level=6
        },
        [4101]={
            avatar_id=4101,
            avartar_type=4,
            surface_id=1
        },
        [4102]={
            avatar_id=4102,
            avartar_type=4,
            surface_id=2
        },
        [4103]={
            avatar_id=4103,
            avartar_type=4,
            surface_id=3
        },
        [4104]={
            avatar_id=4104,
            avartar_type=4,
            surface_id=4
        },
        [4105]={
            avatar_id=4105,
            avartar_type=4,
            surface_id=5
        },
        [4106]={
            avatar_id=4106,
            avartar_type=4,
            surface_id=6
        },
        [4107]={
            avatar_id=4107,
            avartar_type=4,
            surface_id=7
        },
        [4108]={
            avatar_id=4108,
            avartar_type=4,
            surface_id=8
        },
        [4109]={
            avatar_id=4109,
            avartar_type=4,
            surface_id=9
        },
        [4110]={
            avatar_id=4110,
            avartar_type=4,
            surface_id=10
        },
        [4111]={
            avatar_id=4111,
            avartar_type=4,
            surface_id=11
        },
        [4112]={
            avatar_id=4112,
            avartar_type=4,
            surface_id=12
        },
        [4113]={
            avatar_id=4113,
            avartar_type=4,
            surface_id=13
        },
        [4114]={
            avatar_id=4114,
            avartar_type=4,
            surface_id=14
        },
        [4115]={
            avatar_id=4115,
            avartar_type=4,
            surface_id=15
        },
        [4116]={
            avatar_id=4116,
            avartar_type=4,
            surface_id=16
        },
        [4117]={
            avatar_id=4117,
            avartar_type=4,
            surface_id=17
        },
        [4118]={
            avatar_id=4118,
            avartar_type=4,
            surface_id=18
        },
        [4119]={
            avatar_id=4119,
            avartar_type=4,
            surface_id=19
        },
        [4120]={
            avatar_id=4120,
            avartar_type=4,
            surface_id=20
        },
        [4122]={
            avatar_id=4122,
            avartar_type=4,
            surface_id=22
        },
        [5001]={
            avatar_id=5001,
            avartar_type=5,
            type=1,
            advancement_level=1
        },
        [5002]={
            avatar_id=5002,
            avartar_type=5,
            type=1,
            advancement_level=2
        },
        [5003]={
            avatar_id=5003,
            avartar_type=5,
            type=1,
            advancement_level=3
        },
        [5004]={
            avatar_id=5004,
            avartar_type=5,
            type=1,
            advancement_level=4
        },
        [5005]={
            avatar_id=5005,
            avartar_type=5,
            type=1,
            advancement_level=5
        },
        [5006]={
            avatar_id=5006,
            avartar_type=5,
            type=1,
            advancement_level=6
        },
        [5101]={
            avatar_id=5101,
            avartar_type=5,
            surface_id=1
        },
        [5102]={
            avatar_id=5102,
            avartar_type=5,
            surface_id=2
        },
        [5103]={
            avatar_id=5103,
            avartar_type=5,
            surface_id=3
        },
        [5104]={
            avatar_id=5104,
            avartar_type=5,
            surface_id=4
        },
        [5105]={
            avatar_id=5105,
            avartar_type=5,
            surface_id=5
        },
        [5106]={
            avatar_id=5106,
            avartar_type=5,
            surface_id=6
        },
        [5107]={
            avatar_id=5107,
            avartar_type=5,
            surface_id=7
        },
        [5108]={
            avatar_id=5108,
            avartar_type=5,
            surface_id=8
        },
        [5109]={
            avatar_id=5109,
            avartar_type=5,
            surface_id=9
        },
        [5110]={
            avatar_id=5110,
            avartar_type=5,
            surface_id=10
        },
        [5111]={
            avatar_id=5111,
            avartar_type=5,
            surface_id=11
        },
        [5112]={
            avatar_id=5112,
            avartar_type=5,
            surface_id=12
        },
        [5113]={
            avatar_id=5113,
            avartar_type=5,
            surface_id=13
        },
        [5114]={
            avatar_id=5114,
            avartar_type=5,
            surface_id=14
        },
        [5115]={
            avatar_id=5115,
            avartar_type=5,
            surface_id=15
        },
        [5116]={
            avatar_id=5116,
            avartar_type=5,
            surface_id=16
        },
        [5117]={
            avatar_id=5117,
            avartar_type=5,
            surface_id=17
        },
        [5118]={
            avatar_id=5118,
            avartar_type=5,
            surface_id=18
        },
        [5119]={
            avatar_id=5119,
            avartar_type=5,
            surface_id=19
        },
        [5120]={
            avatar_id=5120,
            avartar_type=5,
            surface_id=20
        },
        [5122]={
            avatar_id=5122,
            avartar_type=5,
            surface_id=22
        },
        [6001]={
            avatar_id=6001,
            avartar_type=6,
            type=1,
            advancement_level=1
        },
        [6002]={
            avatar_id=6002,
            avartar_type=6,
            type=1,
            advancement_level=2
        },
        [6003]={
            avatar_id=6003,
            avartar_type=6,
            type=1,
            advancement_level=3
        },
        [6004]={
            avatar_id=6004,
            avartar_type=6,
            type=1,
            advancement_level=4
        },
        [6005]={
            avatar_id=6005,
            avartar_type=6,
            type=1,
            advancement_level=5
        },
        [6006]={
            avatar_id=6006,
            avartar_type=6,
            type=1,
            advancement_level=6
        },
        [6101]={
            avatar_id=6101,
            avartar_type=6,
            surface_id=1
        },
        [6102]={
            avatar_id=6102,
            avartar_type=6,
            surface_id=2
        },
        [6103]={
            avatar_id=6103,
            avartar_type=6,
            surface_id=3
        },
        [6104]={
            avatar_id=6104,
            avartar_type=6,
            surface_id=4
        },
        [6105]={
            avatar_id=6105,
            avartar_type=6,
            surface_id=5
        },
        [6106]={
            avatar_id=6106,
            avartar_type=6,
            surface_id=6
        },
        [6107]={
            avatar_id=6107,
            avartar_type=6,
            surface_id=7
        },
        [6108]={
            avatar_id=6108,
            avartar_type=6,
            surface_id=8
        },
        [6109]={
            avatar_id=6109,
            avartar_type=6,
            surface_id=9
        },
        [6110]={
            avatar_id=6110,
            avartar_type=6,
            surface_id=10
        },
        [6111]={
            avatar_id=6111,
            avartar_type=6,
            surface_id=11
        },
        [6112]={
            avatar_id=6112,
            avartar_type=6,
            surface_id=12
        },
        [6113]={
            avatar_id=6113,
            avartar_type=6,
            surface_id=13
        },
        [6114]={
            avatar_id=6114,
            avartar_type=6,
            surface_id=14
        },
        [6115]={
            avatar_id=6115,
            avartar_type=6,
            surface_id=15
        },
        [6116]={
            avatar_id=6116,
            avartar_type=6,
            surface_id=16
        },
        [6117]={
            avatar_id=6117,
            avartar_type=6,
            surface_id=17
        },
        [6118]={
            avatar_id=6118,
            avartar_type=6,
            surface_id=18
        },
        [6119]={
            avatar_id=6119,
            avartar_type=6,
            surface_id=19
        },
        [6120]={
            avatar_id=6120,
            avartar_type=6,
            surface_id=20
        },
        [6122]={
            avatar_id=6122,
            avartar_type=6,
            surface_id=22
        }
    }
}
SetConfigDefaultVal(Config.image_change_auto,_default_val,nil,nil,nil)