local _default_val={
    copy_copyreward={
        section_start=1,
        section_end=7,
        checkpoint_layer=1,
        type=0,
        monster_group_id=40000,
        characteristic="一群沉迷诗词的蛙怪，无法容忍不精通诗词的对手，将对其造成毁灭打击！",
        battle_icon="s221",
        strategy="建议根据诗词顺序击败怪物和蛙怪。",
        seq1=0
    }
}
local _itemlist={
    i_26812_2_1={
        item_id=26812,
        num=2,
        is_bind=1
    },
    i_26073_100_1={
        item_id=26073,
        num=100,
        is_bind=1
    },
    i_27402_3_1={
        item_id=27402,
        num=3,
        is_bind=1
    },
    i_26073_200_1={
        item_id=26073,
        num=200,
        is_bind=1
    },
    i_26073_300_1={
        item_id=26073,
        num=300,
        is_bind=1
    },
    i_26812_3_1={
        item_id=26812,
        num=3,
        is_bind=1
    },
    i_26412_2_1={
        item_id=26412,
        num=2,
        is_bind=1
    },
    i_24557_1_1={
        item_id=24557,
        num=1,
        is_bind=1
    },
    i_26412_3_1={
        item_id=26412,
        num=3,
        is_bind=1
    },
    i_26413_2_1={
        item_id=26413,
        num=2,
        is_bind=1
    }
}
Config.jiandanqinxin_auto={
    organize={
        {
            no_less_than=3,
            target_id=164
        }
    },
    copy_copyreward={
        {
            seq=0,
            reward_item={
                [0]=_itemlist.i_26812_2_1,
                [1]=_itemlist.i_26073_100_1
            }
        },
        {
            seq=1,
            checkpoint_layer=2,
            monster_group_id=40002,
            reward_item={
                [0]=_itemlist.i_27402_3_1,
                [1]=_itemlist.i_26073_200_1
            },
            characteristic="来自深海的仙灵使者，因为环境污染想教训我们一番，为了保护陆地，只好迎战击退！",
            battle_icon="s222",
            strategy="建议优先击败召唤怪物的上古仙灵。",
            seq1=1
        },
        {
            seq=2,
            checkpoint_layer=3,
            monster_group_id=40004,
            reward_item={
                [0]=_itemlist.i_26812_2_1,
                [1]=_itemlist.i_26073_100_1
            },
            characteristic="狂妄的火焰怪物最近迷上了答题，要是答不出来村庄就会被他们烧毁！",
            battle_icon="s224",
            strategy="建议根据答题顺序击败怪物和火焰魔影。",
            seq1=2
        },
        {
            seq=3,
            checkpoint_layer=4,
            monster_group_id=40006,
            reward_item={
                [0]=_itemlist.i_27402_3_1,
                [1]=_itemlist.i_26073_100_1
            },
            characteristic="巫师听说玄都出现夜明珠可召唤万物，不击败怪物，整座城会被怪物催眠！",
            strategy="建议优先击败释放石化的巫术之灵，10回合内击败所有怪物。",
            seq1=3
        },
        {
            seq=4,
            checkpoint_layer=5,
            monster_group_id=40008,
            reward_item={
                [0]=_itemlist.i_26812_2_1,
                [1]=_itemlist.i_26073_200_1
            },
            characteristic="玄清观被释放出一批魔盒，只有解答出封印密码才能让作乱的怪物回到盒子里！",
            battle_icon="s222",
            strategy="建议根据答题顺序击败怪物和苍眼魔盔。",
            seq1=4
        },
        {
            seq=5,
            checkpoint_layer=6,
            monster_group_id=40010,
            reward_item={
                [0]=_itemlist.i_27402_3_1,
                [1]=_itemlist.i_26073_100_1
            },
            characteristic="变异的风灵芝出现在封魔林，误伤了不少村民，请务必迅速击败！",
            battle_icon="s224",
            strategy="建议优先击败高治愈的风灵芝精，5回合内击败所有怪物。",
            seq1=5
        },
        {
            seq=6,
            checkpoint_layer=7,
            monster_group_id=40012,
            reward_item={
                [0]=_itemlist.i_26812_2_1,
                [1]=_itemlist.i_26073_300_1
            },
            characteristic="地狱妖兽抢夺坊间幼童祭天，如果不迅速击败，必将形成不可挽回的局面！",
            strategy="建议优先击败高法力的狱史兽，10回合内击败所有怪物。",
            seq1=6
        },
        {
            seq=7,
            type=1,
            monster_group_id=40001,
            reward_item={
                [0]=_itemlist.i_26812_3_1,
                [1]=_itemlist.i_26412_2_1
            },
            characteristic="精通诗词的蛙仙闻声而来，不敢相信自己的同伙已经被击败，誓要再决一死战！",
            strategy="建议组队参与，击败诗词顺序怪物和蛙仙。",
            seq1=7
        },
        {
            seq=8,
            checkpoint_layer=2,
            type=1,
            monster_group_id=40003,
            reward_item={
                [0]=_itemlist.i_24557_1_1,
                [1]=_itemlist.i_26412_3_1
            },
            characteristic="深海特派太古仙灵前来调解，希望两陆友好协作，不料途中被妖兽迷惑，只好迎战击退！",
            battle_icon="s222",
            strategy="建议组队参与，优先击败召唤怪物的太古仙灵。",
            seq1=8
        },
        {
            seq=9,
            checkpoint_layer=3,
            type=1,
            monster_group_id=40005,
            reward_item={
                [0]=_itemlist.i_26812_3_1,
                [1]=_itemlist.i_26412_2_1
            },
            characteristic="村庄弥漫的烟火久久未散，深入调查才发现还存在另一批火焰怪物聚集在角落答题，村庄烧毁前必须全部击败怪物！",
            battle_icon="s224",
            strategy="建议组队参与，根据答题顺序击败怪物和南宫守护。",
            seq1=9
        },
        {
            seq=10,
            checkpoint_layer=4,
            type=1,
            monster_group_id=40007,
            reward_item={
                [0]=_itemlist.i_24557_1_1,
                [1]=_itemlist.i_26412_3_1
            },
            characteristic="深海之首听说玄都夜明珠可以净化海洋，派出怪物厮杀村民抢夺，必须要阻止这场腥风血雨的发生！",
            strategy="建议组队参与，优先击败释放石化的海洋之灵，10回合内击败所有怪物。",
            seq1=10
        },
        {
            seq=11,
            checkpoint_layer=5,
            type=1,
            monster_group_id=40009,
            reward_item={
                [0]=_itemlist.i_26812_3_1,
                [1]=_itemlist.i_26412_2_1
            },
            characteristic="封印魔盒的朱雀梵钟被魔盒所控制，只有解开魔盒的答案才能解救被迷惑的朱雀梵钟，重新封印怪物！",
            battle_icon="s222",
            strategy="建议组队参与，根据答题顺序击败怪物和朱雀梵钟。",
            seq1=11
        },
        {
            seq=12,
            checkpoint_layer=6,
            type=1,
            monster_group_id=40011,
            reward_item={
                [0]=_itemlist.i_24557_1_1,
                [1]=_itemlist.i_26412_3_1
            },
            characteristic="被误伤的村民需要土灵芝身上的粉尘方可治愈，需要速速取回，不久将会中毒身亡！",
            battle_icon="s224",
            strategy="建议组队参与，优先击败高治愈的土灵芝精，5回合内击败所有怪物。",
            seq1=12
        },
        {
            seq=13,
            checkpoint_layer=7,
            type=1,
            monster_group_id=40013,
            reward_item={
                [0]=_itemlist.i_26812_3_1,
                [1]=_itemlist.i_26413_2_1
            },
            characteristic="地狱妖狐追踪幼童气息中途杀出来，为脱离危险之境，只好迅速击败怪物！",
            strategy="建议组队参与，优先击败高法力的炎狱妖狐以及高治愈的炎狱史，10回合内击败所有怪物。",
            seq1=13
        },
        {
            seq=14,
            section_start=8,
            section_end=14,
            reward_item={
                [0]=_itemlist.i_26812_2_1,
                [1]=_itemlist.i_26073_100_1
            }
        },
        {
            seq=15,
            section_start=8,
            section_end=14,
            checkpoint_layer=2,
            monster_group_id=40002,
            reward_item={
                [0]=_itemlist.i_27402_3_1,
                [1]=_itemlist.i_26073_200_1
            },
            characteristic="来自深海的仙灵使者，因为环境污染想教训我们一番，为了保护陆地，只好迎战击退！",
            battle_icon="s222",
            strategy="建议优先击败召唤怪物的上古仙灵。",
            seq1=1
        },
        {
            seq=16,
            section_start=8,
            section_end=14,
            checkpoint_layer=3,
            monster_group_id=40004,
            reward_item={
                [0]=_itemlist.i_26812_2_1,
                [1]=_itemlist.i_26073_100_1
            },
            characteristic="狂妄的火焰怪物最近迷上了答题，要是答不出来村庄就会被他们烧毁！",
            battle_icon="s224",
            strategy="建议根据答题顺序击败怪物和火焰魔影。",
            seq1=2
        },
        {
            seq=17,
            section_start=8,
            section_end=14,
            checkpoint_layer=4,
            monster_group_id=40006,
            reward_item={
                [0]=_itemlist.i_27402_3_1,
                [1]=_itemlist.i_26073_100_1
            },
            characteristic="巫师听说玄都出现夜明珠可召唤万物，不击败怪物，整座城会被怪物催眠！",
            strategy="建议优先击败释放石化的巫术之灵，10回合内击败所有怪物。",
            seq1=3
        },
        {
            seq=18,
            section_start=8,
            section_end=14,
            checkpoint_layer=5,
            monster_group_id=40008,
            reward_item={
                [0]=_itemlist.i_26812_2_1,
                [1]=_itemlist.i_26073_200_1
            },
            characteristic="玄清观被释放出一批魔盒，只有解答出封印密码才能让作乱的怪物回到盒子里！",
            battle_icon="s222",
            strategy="建议根据答题顺序击败怪物和苍眼魔盔。",
            seq1=4
        },
        {
            seq=19,
            section_start=8,
            section_end=14,
            checkpoint_layer=6,
            monster_group_id=40010,
            reward_item={
                [0]=_itemlist.i_27402_3_1,
                [1]=_itemlist.i_26073_100_1
            },
            characteristic="变异的风灵芝出现在封魔林，误伤了不少村民，请务必迅速击败！",
            battle_icon="s224",
            strategy="建议优先击败高治愈的风灵芝精，5回合内击败所有怪物。",
            seq1=5
        },
        {
            seq=20,
            section_start=8,
            section_end=14,
            checkpoint_layer=7,
            monster_group_id=40012,
            reward_item={
                [0]=_itemlist.i_26812_2_1,
                [1]=_itemlist.i_26073_300_1
            },
            characteristic="地狱妖兽抢夺坊间幼童祭天，如果不迅速击败，必将形成不可挽回的局面！",
            strategy="建议优先击败高法力的狱史兽，10回合内击败所有怪物。",
            seq1=6
        },
        {
            seq=21,
            section_start=8,
            section_end=14,
            type=1,
            monster_group_id=40001,
            reward_item={
                [0]=_itemlist.i_26812_3_1,
                [1]=_itemlist.i_26412_2_1
            },
            characteristic="精通诗词的蛙仙闻声而来，不敢相信自己的同伙已经被击败，誓要再决一死战！",
            strategy="建议组队参与，击败诗词顺序怪物和蛙仙。",
            seq1=7
        },
        {
            seq=22,
            section_start=8,
            section_end=14,
            checkpoint_layer=2,
            type=1,
            monster_group_id=40003,
            reward_item={
                [0]=_itemlist.i_24557_1_1,
                [1]=_itemlist.i_26412_3_1
            },
            characteristic="深海特派太古仙灵前来调解，希望两陆友好协作，不料途中被妖兽迷惑，只好迎战击退！",
            battle_icon="s222",
            strategy="建议组队参与，优先击败召唤怪物的太古仙灵。",
            seq1=8
        },
        {
            seq=23,
            section_start=8,
            section_end=14,
            checkpoint_layer=3,
            type=1,
            monster_group_id=40005,
            reward_item={
                [0]=_itemlist.i_26812_3_1,
                [1]=_itemlist.i_26412_2_1
            },
            characteristic="村庄弥漫的烟火久久未散，深入调查才发现还存在另一批火焰怪物聚集在角落答题，村庄烧毁前必须全部击败怪物！",
            battle_icon="s224",
            strategy="建议组队参与，根据答题顺序击败怪物和南宫守护。",
            seq1=9
        },
        {
            seq=24,
            section_start=8,
            section_end=14,
            checkpoint_layer=4,
            type=1,
            monster_group_id=40007,
            reward_item={
                [0]=_itemlist.i_24557_1_1,
                [1]=_itemlist.i_26412_3_1
            },
            characteristic="深海之首听说玄都夜明珠可以净化海洋，派出怪物厮杀村民抢夺，必须要阻止这场腥风血雨的发生！",
            strategy="建议组队参与，优先击败释放石化的海洋之灵，10回合内击败所有怪物。",
            seq1=10
        },
        {
            seq=25,
            section_start=8,
            section_end=14,
            checkpoint_layer=5,
            type=1,
            monster_group_id=40009,
            reward_item={
                [0]=_itemlist.i_26812_3_1,
                [1]=_itemlist.i_26412_2_1
            },
            characteristic="封印魔盒的朱雀梵钟被魔盒所控制，只有解开魔盒的答案才能解救被迷惑的朱雀梵钟，重新封印怪物！",
            battle_icon="s222",
            strategy="建议组队参与，根据答题顺序击败怪物和朱雀梵钟。",
            seq1=11
        },
        {
            seq=26,
            section_start=8,
            section_end=14,
            checkpoint_layer=6,
            type=1,
            monster_group_id=40011,
            reward_item={
                [0]=_itemlist.i_24557_1_1,
                [1]=_itemlist.i_26412_3_1
            },
            characteristic="被误伤的村民需要土灵芝身上的粉尘方可治愈，需要速速取回，不久将会中毒身亡！",
            battle_icon="s224",
            strategy="建议组队参与，优先击败高治愈的土灵芝精，5回合内击败所有怪物。",
            seq1=12
        },
        {
            seq=27,
            section_start=8,
            section_end=14,
            checkpoint_layer=7,
            type=1,
            monster_group_id=40013,
            reward_item={
                [0]=_itemlist.i_26812_3_1,
                [1]=_itemlist.i_26413_2_1
            },
            characteristic="地狱妖狐追踪幼童气息中途杀出来，为脱离危险之境，只好迅速击败怪物！",
            strategy="建议组队参与，优先击败高法力的炎狱妖狐以及高治愈的炎狱史，10回合内击败所有怪物。",
            seq1=13
        },
        {
            seq=28,
            section_start=15,
            section_end=0,
            reward_item={
                [0]=_itemlist.i_26812_2_1,
                [1]=_itemlist.i_26073_100_1
            }
        },
        {
            seq=29,
            section_start=15,
            section_end=0,
            checkpoint_layer=2,
            monster_group_id=40002,
            reward_item={
                [0]=_itemlist.i_27402_3_1,
                [1]=_itemlist.i_26073_200_1
            },
            characteristic="来自深海的仙灵使者，因为环境污染想教训我们一番，为了保护陆地，只好迎战击退！",
            battle_icon="s222",
            strategy="建议优先击败召唤怪物的上古仙灵。",
            seq1=1
        },
        {
            seq=30,
            section_start=15,
            section_end=0,
            checkpoint_layer=3,
            monster_group_id=40004,
            reward_item={
                [0]=_itemlist.i_26812_2_1,
                [1]=_itemlist.i_26073_100_1
            },
            characteristic="狂妄的火焰怪物最近迷上了答题，要是答不出来村庄就会被他们烧毁！",
            battle_icon="s224",
            strategy="建议根据答题顺序击败怪物和火焰魔影。",
            seq1=2
        },
        {
            seq=31,
            section_start=15,
            section_end=0,
            checkpoint_layer=4,
            monster_group_id=40006,
            reward_item={
                [0]=_itemlist.i_27402_3_1,
                [1]=_itemlist.i_26073_100_1
            },
            characteristic="巫师听说玄都出现夜明珠可召唤万物，不击败怪物，整座城会被怪物催眠！",
            strategy="建议优先击败释放石化的巫术之灵，10回合内击败所有怪物。",
            seq1=3
        },
        {
            seq=32,
            section_start=15,
            section_end=0,
            checkpoint_layer=5,
            monster_group_id=40008,
            reward_item={
                [0]=_itemlist.i_26812_2_1,
                [1]=_itemlist.i_26073_200_1
            },
            characteristic="玄清观被释放出一批魔盒，只有解答出封印密码才能让作乱的怪物回到盒子里！",
            battle_icon="s222",
            strategy="建议根据答题顺序击败怪物和苍眼魔盔。",
            seq1=4
        },
        {
            seq=33,
            section_start=15,
            section_end=0,
            checkpoint_layer=6,
            monster_group_id=40010,
            reward_item={
                [0]=_itemlist.i_27402_3_1,
                [1]=_itemlist.i_26073_100_1
            },
            characteristic="变异的风灵芝出现在封魔林，误伤了不少村民，请务必迅速击败！",
            battle_icon="s224",
            strategy="建议优先击败高治愈的风灵芝精，5回合内击败所有怪物。",
            seq1=5
        },
        {
            seq=34,
            section_start=15,
            section_end=0,
            checkpoint_layer=7,
            monster_group_id=40012,
            reward_item={
                [0]=_itemlist.i_26812_2_1,
                [1]=_itemlist.i_26073_300_1
            },
            characteristic="地狱妖兽抢夺坊间幼童祭天，如果不迅速击败，必将形成不可挽回的局面！",
            strategy="建议优先击败高法力的狱史兽，10回合内击败所有怪物。",
            seq1=6
        },
        {
            seq=35,
            section_start=15,
            section_end=0,
            type=1,
            monster_group_id=40001,
            reward_item={
                [0]=_itemlist.i_26812_3_1,
                [1]=_itemlist.i_26412_2_1
            },
            characteristic="精通诗词的蛙仙闻声而来，不敢相信自己的同伙已经被击败，誓要再决一死战！",
            strategy="建议组队参与，击败诗词顺序怪物和蛙仙。",
            seq1=7
        },
        {
            seq=36,
            section_start=15,
            section_end=0,
            checkpoint_layer=2,
            type=1,
            monster_group_id=40003,
            reward_item={
                [0]=_itemlist.i_24557_1_1,
                [1]=_itemlist.i_26412_3_1
            },
            characteristic="深海特派太古仙灵前来调解，希望两陆友好协作，不料途中被妖兽迷惑，只好迎战击退！",
            battle_icon="s222",
            strategy="建议组队参与，优先击败召唤怪物的太古仙灵。",
            seq1=8
        },
        {
            seq=37,
            section_start=15,
            section_end=0,
            checkpoint_layer=3,
            type=1,
            monster_group_id=40005,
            reward_item={
                [0]=_itemlist.i_26812_3_1,
                [1]=_itemlist.i_26412_2_1
            },
            characteristic="村庄弥漫的烟火久久未散，深入调查才发现还存在另一批火焰怪物聚集在角落答题，村庄烧毁前必须全部击败怪物！",
            battle_icon="s224",
            strategy="建议组队参与，根据答题顺序击败怪物和南宫守护。",
            seq1=9
        },
        {
            seq=38,
            section_start=15,
            section_end=0,
            checkpoint_layer=4,
            type=1,
            monster_group_id=40007,
            reward_item={
                [0]=_itemlist.i_24557_1_1,
                [1]=_itemlist.i_26412_3_1
            },
            characteristic="深海之首听说玄都夜明珠可以净化海洋，派出怪物厮杀村民抢夺，必须要阻止这场腥风血雨的发生！",
            strategy="建议组队参与，优先击败释放石化的海洋之灵，10回合内击败所有怪物。",
            seq1=10
        },
        {
            seq=39,
            section_start=15,
            section_end=0,
            checkpoint_layer=5,
            type=1,
            monster_group_id=40009,
            reward_item={
                [0]=_itemlist.i_26812_3_1,
                [1]=_itemlist.i_26412_2_1
            },
            characteristic="封印魔盒的朱雀梵钟被魔盒所控制，只有解开魔盒的答案才能解救被迷惑的朱雀梵钟，重新封印怪物！",
            battle_icon="s222",
            strategy="建议组队参与，根据答题顺序击败怪物和朱雀梵钟。",
            seq1=11
        },
        {
            seq=40,
            section_start=15,
            section_end=0,
            checkpoint_layer=6,
            type=1,
            monster_group_id=40011,
            reward_item={
                [0]=_itemlist.i_24557_1_1,
                [1]=_itemlist.i_26412_3_1
            },
            characteristic="被误伤的村民需要土灵芝身上的粉尘方可治愈，需要速速取回，不久将会中毒身亡！",
            battle_icon="s224",
            strategy="建议组队参与，优先击败高治愈的土灵芝精，5回合内击败所有怪物。",
            seq1=12
        },
        {
            seq=41,
            section_start=15,
            section_end=0,
            checkpoint_layer=7,
            type=1,
            monster_group_id=40013,
            reward_item={
                [0]=_itemlist.i_26812_3_1,
                [1]=_itemlist.i_26413_2_1
            },
            characteristic="地狱妖狐追踪幼童气息中途杀出来，为脱离危险之境，只好迅速击败怪物！",
            strategy="建议组队参与，优先击败高法力的炎狱妖狐以及高治愈的炎狱史，10回合内击败所有怪物。",
            seq1=13
        }
    },
    is_open={
        {
            seq=0,
            section_start=8,
            section_end=14,
            is_open=2
        },
        {
            seq=1,
            section_start=15,
            section_end=0,
            is_open=1
        }
    }
}
SetConfigDefaultVal(Config.jiandanqinxin_auto,_default_val,nil,nil,nil)