local _default_val={
    basis_configuration={
        level_down=50,
        level_up=70,
        seq=0,
        level_card=0,
        upgrade_exp=100,
        is_reward_item=1
    },
    task_configuration={
        task_group=1,
        task_id=0,
        task_type=8,
        parameter=1,
        task_exp=10,
        jump_interface=0
    },
    task_num={
        season_task_num=5,
        week_task_num=10,
        day_task_num=10
    }
}
local _itemlist={
    i_22007_20_1={
        item_id=22007,
        num=20,
        is_bind=1
    },
    i_22007_15_1={
        item_id=22007,
        num=15,
        is_bind=1
    },
    i_26812_1_1={
        item_id=26812,
        num=1,
        is_bind=1
    },
    i_26393_3_1={
        item_id=26393,
        num=3,
        is_bind=1
    },
    i_27398_3_1={
        item_id=27398,
        num=3,
        is_bind=1
    },
    i_26393_1_1={
        item_id=26393,
        num=1,
        is_bind=1
    },
    i_24326_3_1={
        item_id=24326,
        num=3,
        is_bind=1
    },
    i_27398_1_1={
        item_id=27398,
        num=1,
        is_bind=1
    },
    i_27399_2_1={
        item_id=27399,
        num=2,
        is_bind=1
    },
    i_27575_1_1={
        item_id=27575,
        num=1,
        is_bind=1
    },
    i_27478_2_1={
        item_id=27478,
        num=2,
        is_bind=1
    },
    i_27479_1_1={
        item_id=27479,
        num=1,
        is_bind=1
    },
    i_26393_5_1={
        item_id=26393,
        num=5,
        is_bind=1
    },
    i_27478_20_1={
        item_id=27478,
        num=20,
        is_bind=1
    },
    i_24326_5_1={
        item_id=24326,
        num=5,
        is_bind=1
    },
    i_27478_30_1={
        item_id=27478,
        num=30,
        is_bind=1
    },
    i_26812_3_1={
        item_id=26812,
        num=3,
        is_bind=1
    },
    i_22007_30_1={
        item_id=22007,
        num=30,
        is_bind=1
    },
    i_26812_2_1={
        item_id=26812,
        num=2,
        is_bind=1
    },
    i_27398_5_1={
        item_id=27398,
        num=5,
        is_bind=1
    },
    i_26393_2_1={
        item_id=26393,
        num=2,
        is_bind=1
    },
    i_27398_2_1={
        item_id=27398,
        num=2,
        is_bind=1
    },
    i_27399_3_1={
        item_id=27399,
        num=3,
        is_bind=1
    },
    i_27575_2_1={
        item_id=27575,
        num=2,
        is_bind=1
    },
    i_27478_3_1={
        item_id=27478,
        num=3,
        is_bind=1
    },
    i_27479_2_1={
        item_id=27479,
        num=2,
        is_bind=1
    },
    i_26393_8_1={
        item_id=26393,
        num=8,
        is_bind=1
    },
    i_24326_8_1={
        item_id=24326,
        num=8,
        is_bind=1
    },
    i_27479_3_1={
        item_id=27479,
        num=3,
        is_bind=1
    },
    i_27478_50_1={
        item_id=27478,
        num=50,
        is_bind=1
    },
    i_22007_50_1={
        item_id=22007,
        num=50,
        is_bind=1
    },
    i_27398_8_1={
        item_id=27398,
        num=8,
        is_bind=1
    },
    i_27399_5_1={
        item_id=27399,
        num=5,
        is_bind=1
    },
    i_27575_5_1={
        item_id=27575,
        num=5,
        is_bind=1
    },
    i_27478_5_1={
        item_id=27478,
        num=5,
        is_bind=1
    },
    i_26393_10_1={
        item_id=26393,
        num=10,
        is_bind=1
    },
    i_24326_10_1={
        item_id=24326,
        num=10,
        is_bind=1
    },
    i_27479_5_1={
        item_id=27479,
        num=5,
        is_bind=1
    },
    i_27478_80_1={
        item_id=27478,
        num=80,
        is_bind=1
    },
    i_26812_5_1={
        item_id=26812,
        num=5,
        is_bind=1
    },
    i_28821_1_1={
        item_id=28821,
        num=1,
        is_bind=1
    }
}
Config.jingjiyueka_auto={
    basis_configuration={
        {
            type=0,
            upgrade_exp=20,
            is_reward_item=0
        },
        {
            type=1,
            seq=1,
            level_card=1,
            upgrade_exp=20,
            con_reward_item=_itemlist.i_22007_20_1,
            add_reward_item={
                [0]=_itemlist.i_22007_15_1
            }
        },
        {
            type=2,
            seq=2,
            level_card=2,
            upgrade_exp=50,
            con_reward_item=_itemlist.i_26812_1_1,
            add_reward_item={
                [0]=_itemlist.i_26393_3_1
            }
        },
        {
            type=3,
            seq=3,
            level_card=3,
            upgrade_exp=50,
            add_reward_item={
                [0]=_itemlist.i_27398_3_1
            },
            is_reward_item=0
        },
        {
            type=4,
            seq=4,
            level_card=4,
            upgrade_exp=50,
            con_reward_item=_itemlist.i_26393_1_1,
            add_reward_item={
                [0]=_itemlist.i_24326_3_1
            }
        },
        {
            type=5,
            seq=5,
            level_card=5,
            upgrade_exp=50,
            con_reward_item=_itemlist.i_27398_1_1,
            add_reward_item={
                [0]=_itemlist.i_27399_2_1,
                [1]=_itemlist.i_27575_1_1
            }
        },
        {
            type=6,
            seq=6,
            level_card=6,
            add_reward_item={
                [0]=_itemlist.i_27478_2_1
            },
            is_reward_item=0
        },
        {
            type=7,
            seq=7,
            level_card=7,
            con_reward_item=_itemlist.i_27479_1_1,
            add_reward_item={
                [0]=_itemlist.i_26393_5_1
            }
        },
        {
            type=8,
            seq=8,
            level_card=8,
            con_reward_item=_itemlist.i_27478_20_1,
            add_reward_item={
                [0]=_itemlist.i_24326_5_1
            }
        },
        {
            type=9,
            seq=9,
            level_card=9,
            add_reward_item={
                [0]=_itemlist.i_27479_1_1
            },
            is_reward_item=0
        },
        {
            type=10,
            seq=10,
            level_card=10,
            con_reward_item=_itemlist.i_24326_3_1,
            add_reward_item={
                [0]=_itemlist.i_27478_30_1,
                [1]=_itemlist.i_26812_3_1
            }
        },
        {
            type=11,
            seq=11,
            level_card=11,
            upgrade_exp=150,
            con_reward_item=_itemlist.i_22007_30_1,
            add_reward_item={
                [0]=_itemlist.i_22007_30_1
            }
        },
        {
            type=12,
            seq=12,
            level_card=12,
            upgrade_exp=150,
            con_reward_item=_itemlist.i_26812_2_1,
            add_reward_item={
                [0]=_itemlist.i_26393_5_1
            }
        },
        {
            type=13,
            seq=13,
            level_card=13,
            upgrade_exp=150,
            add_reward_item={
                [0]=_itemlist.i_27398_5_1
            },
            is_reward_item=0
        },
        {
            type=14,
            seq=14,
            level_card=14,
            upgrade_exp=150,
            con_reward_item=_itemlist.i_26393_2_1,
            add_reward_item={
                [0]=_itemlist.i_24326_5_1
            }
        },
        {
            type=15,
            seq=15,
            level_card=15,
            upgrade_exp=150,
            con_reward_item=_itemlist.i_27398_2_1,
            add_reward_item={
                [0]=_itemlist.i_27399_3_1,
                [1]=_itemlist.i_27575_2_1
            }
        },
        {
            type=16,
            seq=16,
            level_card=16,
            upgrade_exp=200,
            add_reward_item={
                [0]=_itemlist.i_27478_3_1
            },
            is_reward_item=0
        },
        {
            type=17,
            seq=17,
            level_card=17,
            upgrade_exp=200,
            con_reward_item=_itemlist.i_27479_2_1,
            add_reward_item={
                [0]=_itemlist.i_26393_8_1
            }
        },
        {
            type=18,
            seq=18,
            level_card=18,
            upgrade_exp=200,
            con_reward_item=_itemlist.i_27478_30_1,
            add_reward_item={
                [0]=_itemlist.i_24326_8_1
            }
        },
        {
            type=19,
            seq=19,
            level_card=19,
            upgrade_exp=200,
            add_reward_item={
                [0]=_itemlist.i_27479_3_1
            },
            is_reward_item=0
        },
        {
            type=20,
            seq=20,
            level_card=20,
            upgrade_exp=200,
            con_reward_item=_itemlist.i_24326_5_1,
            add_reward_item={
                [0]=_itemlist.i_27478_50_1,
                [1]=_itemlist.i_26812_3_1
            }
        },
        {
            type=21,
            seq=21,
            level_card=21,
            upgrade_exp=300,
            con_reward_item=_itemlist.i_22007_50_1,
            add_reward_item={
                [0]=_itemlist.i_22007_50_1
            }
        },
        {
            type=22,
            seq=22,
            level_card=22,
            upgrade_exp=300,
            con_reward_item=_itemlist.i_26812_3_1,
            add_reward_item={
                [0]=_itemlist.i_26393_8_1
            }
        },
        {
            type=23,
            seq=23,
            level_card=23,
            upgrade_exp=300,
            add_reward_item={
                [0]=_itemlist.i_27398_8_1
            },
            is_reward_item=0
        },
        {
            type=24,
            seq=24,
            level_card=24,
            upgrade_exp=300,
            con_reward_item=_itemlist.i_26393_3_1,
            add_reward_item={
                [0]=_itemlist.i_24326_8_1
            }
        },
        {
            type=25,
            seq=25,
            level_card=25,
            upgrade_exp=300,
            con_reward_item=_itemlist.i_27398_3_1,
            add_reward_item={
                [0]=_itemlist.i_27399_5_1,
                [1]=_itemlist.i_27575_5_1
            }
        },
        {
            type=26,
            seq=26,
            level_card=26,
            upgrade_exp=400,
            add_reward_item={
                [0]=_itemlist.i_27478_5_1
            },
            is_reward_item=0
        },
        {
            type=27,
            seq=27,
            level_card=27,
            upgrade_exp=400,
            con_reward_item=_itemlist.i_27479_3_1,
            add_reward_item={
                [0]=_itemlist.i_26393_10_1
            }
        },
        {
            type=28,
            seq=28,
            level_card=28,
            upgrade_exp=400,
            con_reward_item=_itemlist.i_27478_50_1,
            add_reward_item={
                [0]=_itemlist.i_24326_10_1
            }
        },
        {
            type=29,
            seq=29,
            level_card=29,
            upgrade_exp=400,
            add_reward_item={
                [0]=_itemlist.i_27479_5_1
            },
            is_reward_item=0
        },
        {
            type=30,
            seq=30,
            level_card=30,
            upgrade_exp=0,
            con_reward_item=_itemlist.i_24326_8_1,
            add_reward_item={
                [0]=_itemlist.i_27478_80_1,
                [1]=_itemlist.i_26812_5_1
            }
        },
        {
            type=31,
            level_down=71,
            level_up=0,
            upgrade_exp=20,
            is_reward_item=0
        },
        {
            type=32,
            level_down=71,
            level_up=0,
            seq=1,
            level_card=1,
            upgrade_exp=20,
            con_reward_item=_itemlist.i_22007_20_1,
            add_reward_item={
                [0]=_itemlist.i_22007_15_1
            }
        },
        {
            type=33,
            level_down=71,
            level_up=0,
            seq=2,
            level_card=2,
            upgrade_exp=50,
            con_reward_item=_itemlist.i_26812_1_1,
            add_reward_item={
                [0]=_itemlist.i_26393_3_1
            }
        },
        {
            type=34,
            level_down=71,
            level_up=0,
            seq=3,
            level_card=3,
            upgrade_exp=50,
            add_reward_item={
                [0]=_itemlist.i_27398_3_1
            },
            is_reward_item=0
        },
        {
            type=35,
            level_down=71,
            level_up=0,
            seq=4,
            level_card=4,
            upgrade_exp=50,
            con_reward_item=_itemlist.i_26393_1_1,
            add_reward_item={
                [0]=_itemlist.i_24326_3_1
            }
        },
        {
            type=36,
            level_down=71,
            level_up=0,
            seq=5,
            level_card=5,
            upgrade_exp=50,
            con_reward_item=_itemlist.i_27398_1_1,
            add_reward_item={
                [0]=_itemlist.i_27399_2_1,
                [1]=_itemlist.i_27575_1_1
            }
        },
        {
            type=37,
            level_down=71,
            level_up=0,
            seq=6,
            level_card=6,
            add_reward_item={
                [0]=_itemlist.i_27478_2_1
            },
            is_reward_item=0
        },
        {
            type=38,
            level_down=71,
            level_up=0,
            seq=7,
            level_card=7,
            con_reward_item=_itemlist.i_27479_1_1,
            add_reward_item={
                [0]=_itemlist.i_26393_5_1
            }
        },
        {
            type=39,
            level_down=71,
            level_up=0,
            seq=8,
            level_card=8,
            con_reward_item=_itemlist.i_27478_20_1,
            add_reward_item={
                [0]=_itemlist.i_24326_5_1
            }
        },
        {
            type=40,
            level_down=71,
            level_up=0,
            seq=9,
            level_card=9,
            add_reward_item={
                [0]=_itemlist.i_27479_1_1
            },
            is_reward_item=0
        },
        {
            type=41,
            level_down=71,
            level_up=0,
            seq=10,
            level_card=10,
            con_reward_item=_itemlist.i_24326_3_1,
            add_reward_item={
                [0]=_itemlist.i_27478_30_1,
                [1]=_itemlist.i_26812_3_1
            }
        },
        {
            type=42,
            level_down=71,
            level_up=0,
            seq=11,
            level_card=11,
            upgrade_exp=150,
            con_reward_item=_itemlist.i_22007_30_1,
            add_reward_item={
                [0]=_itemlist.i_22007_30_1
            }
        },
        {
            type=43,
            level_down=71,
            level_up=0,
            seq=12,
            level_card=12,
            upgrade_exp=150,
            con_reward_item=_itemlist.i_26812_2_1,
            add_reward_item={
                [0]=_itemlist.i_26393_5_1
            }
        },
        {
            type=44,
            level_down=71,
            level_up=0,
            seq=13,
            level_card=13,
            upgrade_exp=150,
            add_reward_item={
                [0]=_itemlist.i_27398_5_1
            },
            is_reward_item=0
        },
        {
            type=45,
            level_down=71,
            level_up=0,
            seq=14,
            level_card=14,
            upgrade_exp=150,
            con_reward_item=_itemlist.i_26393_2_1,
            add_reward_item={
                [0]=_itemlist.i_24326_5_1
            }
        },
        {
            type=46,
            level_down=71,
            level_up=0,
            seq=15,
            level_card=15,
            upgrade_exp=150,
            con_reward_item=_itemlist.i_27398_2_1,
            add_reward_item={
                [0]=_itemlist.i_27399_3_1,
                [1]=_itemlist.i_27575_2_1
            }
        },
        {
            type=47,
            level_down=71,
            level_up=0,
            seq=16,
            level_card=16,
            upgrade_exp=200,
            add_reward_item={
                [0]=_itemlist.i_27478_3_1
            },
            is_reward_item=0
        },
        {
            type=48,
            level_down=71,
            level_up=0,
            seq=17,
            level_card=17,
            upgrade_exp=200,
            con_reward_item=_itemlist.i_27479_2_1,
            add_reward_item={
                [0]=_itemlist.i_26393_8_1
            }
        },
        {
            type=49,
            level_down=71,
            level_up=0,
            seq=18,
            level_card=18,
            upgrade_exp=200,
            con_reward_item=_itemlist.i_27478_30_1,
            add_reward_item={
                [0]=_itemlist.i_24326_8_1
            }
        },
        {
            type=50,
            level_down=71,
            level_up=0,
            seq=19,
            level_card=19,
            upgrade_exp=200,
            add_reward_item={
                [0]=_itemlist.i_27479_3_1
            },
            is_reward_item=0
        },
        {
            type=51,
            level_down=71,
            level_up=0,
            seq=20,
            level_card=20,
            upgrade_exp=200,
            con_reward_item=_itemlist.i_24326_5_1,
            add_reward_item={
                [0]=_itemlist.i_27478_50_1,
                [1]=_itemlist.i_26812_3_1
            }
        },
        {
            type=52,
            level_down=71,
            level_up=0,
            seq=21,
            level_card=21,
            upgrade_exp=300,
            con_reward_item=_itemlist.i_22007_50_1,
            add_reward_item={
                [0]=_itemlist.i_22007_50_1
            }
        },
        {
            type=53,
            level_down=71,
            level_up=0,
            seq=22,
            level_card=22,
            upgrade_exp=300,
            con_reward_item=_itemlist.i_26812_3_1,
            add_reward_item={
                [0]=_itemlist.i_26393_8_1
            }
        },
        {
            type=54,
            level_down=71,
            level_up=0,
            seq=23,
            level_card=23,
            upgrade_exp=300,
            add_reward_item={
                [0]=_itemlist.i_27398_8_1
            },
            is_reward_item=0
        },
        {
            type=55,
            level_down=71,
            level_up=0,
            seq=24,
            level_card=24,
            upgrade_exp=300,
            con_reward_item=_itemlist.i_26393_3_1,
            add_reward_item={
                [0]=_itemlist.i_24326_8_1
            }
        },
        {
            type=56,
            level_down=71,
            level_up=0,
            seq=25,
            level_card=25,
            upgrade_exp=300,
            con_reward_item=_itemlist.i_27398_3_1,
            add_reward_item={
                [0]=_itemlist.i_27399_5_1,
                [1]=_itemlist.i_27575_5_1
            }
        },
        {
            type=57,
            level_down=71,
            level_up=0,
            seq=26,
            level_card=26,
            upgrade_exp=400,
            add_reward_item={
                [0]=_itemlist.i_27478_5_1
            },
            is_reward_item=0
        },
        {
            type=58,
            level_down=71,
            level_up=0,
            seq=27,
            level_card=27,
            upgrade_exp=400,
            con_reward_item=_itemlist.i_27479_3_1,
            add_reward_item={
                [0]=_itemlist.i_26393_10_1
            }
        },
        {
            type=59,
            level_down=71,
            level_up=0,
            seq=28,
            level_card=28,
            upgrade_exp=400,
            con_reward_item=_itemlist.i_27478_50_1,
            add_reward_item={
                [0]=_itemlist.i_24326_10_1
            }
        },
        {
            type=60,
            level_down=71,
            level_up=0,
            seq=29,
            level_card=29,
            upgrade_exp=400,
            add_reward_item={
                [0]=_itemlist.i_27479_5_1
            },
            is_reward_item=0
        },
        {
            type=61,
            level_down=71,
            level_up=0,
            seq=30,
            level_card=30,
            upgrade_exp=0,
            con_reward_item=_itemlist.i_24326_8_1,
            add_reward_item={
                [0]=_itemlist.i_27478_80_1,
                [1]=_itemlist.i_26812_5_1
            }
        }
    },
    task_configuration={
        {
            type=0,
            task_group=0,
            task_type=0,
            desc="参与1次穹顶之战",
            jump_interface=8001
        },
        {
            type=1,
            task_group=0,
            task_id=1,
            task_type=2,
            desc="参与1次五方擂台",
            jump_interface=67001
        },
        {
            type=2,
            task_group=0,
            task_id=2,
            task_type=4,
            desc="参与1次幻界战场",
            jump_interface=70001
        },
        {
            type=3,
            task_group=0,
            task_id=3,
            task_type=1,
            task_exp=15,
            desc="穹顶之战获胜1次",
            jump_interface=8001
        },
        {
            type=4,
            task_group=0,
            task_id=4,
            task_type=3,
            task_exp=15,
            desc="五方擂台获胜1次",
            jump_interface=67001
        },
        {
            type=5,
            task_group=0,
            task_id=5,
            task_type=5,
            task_exp=15,
            desc="幻界战场获胜1次",
            jump_interface=70001
        },
        {
            type=6,
            desc="通关1次梦渊谷",
            jump_interface=110005
        },
        {
            type=7,
            task_id=1,
            task_type=9,
            desc="通关1次玉虚境",
            jump_interface=110001
        },
        {
            type=8,
            task_id=2,
            task_type=10,
            desc="通关1次神印地",
            jump_interface=110004
        },
        {
            type=9,
            task_id=3,
            task_type=11,
            desc="通关1次秘宝阁",
            jump_interface=110002
        },
        {
            type=10,
            task_id=4,
            task_type=12,
            desc="完成每日登录"
        },
        {
            type=11,
            task_id=5,
            task_type=13,
            parameter=100,
            desc="消耗100体力",
            jump_interface=110005
        },
        {
            type=12,
            task_id=6,
            task_type=14,
            desc="通关1次北斗七星",
            jump_interface=30008
        },
        {
            type=13,
            task_id=7,
            task_type=15,
            parameter=5,
            desc="通关5次轮回忘川",
            jump_interface=30006
        },
        {
            type=14,
            task_id=8,
            task_type=16,
            parameter=2,
            desc="任意宠物学习2本技能书",
            jump_interface=2007
        },
        {
            type=15,
            task_id=9,
            task_type=17,
            parameter=800,
            desc="竞技场排名达到800",
            jump_interface=38001
        },
        {
            type=16,
            task_id=10,
            task_type=18,
            parameter=20,
            desc="锢魔之塔获得20星",
            jump_interface=30002
        },
        {
            type=17,
            task_id=11,
            task_type=19,
            parameter=2700,
            desc="累计在线45分钟"
        },
        {
            type=18,
            task_id=12,
            task_type=21,
            parameter=3,
            desc="累计击败3个野外首领",
            jump_interface=66001
        },
        {
            type=19,
            task_id=13,
            task_type=24,
            parameter=150,
            desc="活跃值达到150",
            jump_interface=21001
        },
        {
            type=20,
            task_id=14,
            task_type=25,
            parameter=80000,
            desc="累计消耗8万铜币"
        },
        {
            type=21,
            task_id=15,
            task_type=26,
            parameter=2000,
            desc="累计消耗2000元宝",
            jump_interface=33002
        },
        {
            type=22,
            task_id=16,
            task_type=27,
            parameter=100000,
            desc="累计消耗10万灵玉",
            jump_interface=18003
        },
        {
            type=23,
            task_group=2,
            parameter=5,
            desc="通关5次梦渊谷",
            jump_interface=110005
        },
        {
            type=24,
            task_group=2,
            task_id=1,
            task_type=9,
            parameter=3,
            desc="通关3次玉虚境",
            jump_interface=110001
        },
        {
            type=25,
            task_group=2,
            task_id=2,
            task_type=10,
            parameter=5,
            desc="通关5次神印地",
            jump_interface=110004
        },
        {
            type=26,
            task_group=2,
            task_id=3,
            task_type=11,
            parameter=5,
            desc="通关5次秘宝阁",
            jump_interface=110002
        },
        {
            type=27,
            task_group=2,
            task_id=4,
            task_type=12,
            parameter=5,
            desc="累计登录5次"
        },
        {
            type=28,
            task_group=2,
            task_id=5,
            task_type=13,
            parameter=500,
            desc="消耗500体力",
            jump_interface=110005
        },
        {
            type=29,
            task_group=2,
            task_id=6,
            task_type=20,
            parameter=5,
            desc="任意宠物强化5次",
            jump_interface=2005
        },
        {
            type=30,
            task_group=2,
            task_id=7,
            task_type=24,
            parameter=750,
            desc="累计获得750活跃值",
            jump_interface=21001
        },
        {
            type=31,
            task_group=2,
            task_id=8,
            task_type=16,
            parameter=6,
            desc="任意宠物学习6本技能书",
            jump_interface=30002
        },
        {
            type=32,
            task_group=2,
            task_id=9,
            task_type=7,
            parameter=5,
            desc="竞技场胜利5次",
            jump_interface=38001
        },
        {
            type=33,
            task_group=2,
            task_id=10,
            task_type=6,
            parameter=5,
            desc="参与5次竞技场",
            jump_interface=38001
        },
        {
            type=34,
            task_group=2,
            task_id=11,
            task_type=14,
            parameter=5,
            desc="通关5次北斗七星",
            jump_interface=30008
        },
        {
            type=35,
            task_group=2,
            task_id=12,
            task_type=22,
            parameter=3,
            desc="累计3天完成门派任务"
        },
        {
            type=36,
            task_group=2,
            task_id=13,
            task_type=25,
            parameter=200000,
            desc="累计消耗20万铜币"
        },
        {
            type=37,
            task_group=2,
            task_id=14,
            task_type=26,
            parameter=8000,
            desc="累计消耗8000元宝",
            jump_interface=33002
        },
        {
            type=38,
            task_group=2,
            task_id=15,
            task_type=27,
            parameter=300000,
            desc="累计消耗30万灵玉",
            jump_interface=18003
        },
        {
            type=39,
            task_group=2,
            task_id=16,
            task_type=23,
            parameter=3,
            desc="勇闯地宫通关3层",
            jump_interface=82001
        }
    },
    task_num={
        {
            level_down=50,
            level_up=70,
            activity_title="初入天下"
        },
        {
            level_down=71,
            level_up=0,
            activity_title="逐鹿八荒"
        }
    },
    other={
        {
            show_item=_itemlist.i_28821_1_1,
            buy_gold=20,
            task_gold=10,
            is_open=1,
            open_day=25,
            buy_price=500,
            cfg_ver=1,
            task_exp=65841,
            open_level=50
        }
    }
}
SetConfigDefaultVal(Config.jingjiyueka_auto,_default_val,nil,nil,nil)