local _default_val={
    basis_configuration={
        section_start=1,
        section_end=0,
        parameter=1
    },
    herbs_configuration={
        submit_num=1
    },
    reward_configuration={
        section_start=1,
        section_end=21,
        reward_group=1,
        seq=0
    }
}
local _itemlist={
    i_26699_1_1={
        item_id=26699,
        num=1,
        is_bind=1
    },
    i_26692_2_1={
        item_id=26692,
        num=2,
        is_bind=1
    },
    i_26700_1_1={
        item_id=26700,
        num=1,
        is_bind=1
    },
    i_28516_1_1={
        item_id=28516,
        num=1,
        is_bind=1
    },
    i_26701_1_1={
        item_id=26701,
        num=1,
        is_bind=1
    },
    i_29060_1_1={
        item_id=29060,
        num=1,
        is_bind=1
    },
    i_26702_1_1={
        item_id=26702,
        num=1,
        is_bind=1
    },
    i_27838_1_1={
        item_id=27838,
        num=1,
        is_bind=1
    },
    i_22013_3_1={
        item_id=22013,
        num=3,
        is_bind=1
    },
    i_29060_2_1={
        item_id=29060,
        num=2,
        is_bind=1
    },
    i_26441_3_1={
        item_id=26441,
        num=3,
        is_bind=1
    },
    i_29060_3_1={
        item_id=29060,
        num=3,
        is_bind=1
    },
    i_26442_2_1={
        item_id=26442,
        num=2,
        is_bind=1
    }
}
Config.lantangchumu_auto={
    basis_configuration={
        {
            type=0,
            seq=0,
            task_type=9,
            parameter=10,
            task_desc="在线10分钟",
            reward_item={
                [0]=_itemlist.i_26699_1_1,
                [1]=_itemlist.i_26692_2_1
            },
            jump_interface=""
        },
        {
            type=1,
            seq=1,
            task_type=4,
            parameter=50,
            task_desc="使用50点体力",
            reward_item={
                [0]=_itemlist.i_26700_1_1,
                [1]=_itemlist.i_28516_1_1
            },
            jump_interface=110005
        },
        {
            type=2,
            seq=2,
            task_type=0,
            task_desc="参与1次竞技场",
            reward_item={
                [0]=_itemlist.i_26701_1_1,
                [1]=_itemlist.i_29060_1_1
            },
            jump_interface=38001
        },
        {
            type=3,
            seq=3,
            task_type=10,
            task_desc="参与1次万灵话本",
            reward_item={
                [0]=_itemlist.i_26702_1_1,
                [1]=_itemlist.i_27838_1_1
            },
            jump_interface=122001
        }
    },
    herbs_configuration={
        {
            seq=0,
            submit_item_id=26699
        },
        {
            seq=1,
            submit_item_id=26700
        },
        {
            seq=2,
            submit_item_id=26701
        },
        {
            seq=3,
            submit_item_id=26702
        }
    },
    reward_configuration={
        {
            type=0,
            bath_reward_item={
                [0]=_itemlist.i_22013_3_1
            }
        },
        {
            type=1,
            seq=1,
            bath_reward_item={
                [0]=_itemlist.i_29060_2_1
            }
        },
        {
            type=2,
            seq=2,
            bath_reward_item={
                [0]=_itemlist.i_26441_3_1
            }
        },
        {
            type=3,
            section_start=22,
            section_end=0,
            reward_group=2,
            bath_reward_item={
                [0]=_itemlist.i_22013_3_1
            }
        },
        {
            type=4,
            section_start=22,
            section_end=0,
            reward_group=2,
            seq=1,
            bath_reward_item={
                [0]=_itemlist.i_29060_3_1
            }
        },
        {
            type=5,
            section_start=22,
            section_end=0,
            reward_group=2,
            seq=2,
            bath_reward_item={
                [0]=_itemlist.i_26442_2_1
            }
        }
    },
    show_reward={
        {
            type=0,
            section_start=1,
            section_end=21,
            show_reward_item={
                [0]=_itemlist.i_22013_3_1,
                [1]=_itemlist.i_29060_2_1,
                [2]=_itemlist.i_26441_3_1
            }
        },
        {
            type=1,
            section_start=22,
            section_end=0,
            show_reward_item={
                [0]=_itemlist.i_22013_3_1,
                [1]=_itemlist.i_29060_3_1,
                [2]=_itemlist.i_26442_2_1
            }
        }
    }
}
SetConfigDefaultVal(Config.lantangchumu_auto,_default_val,nil,nil,nil)