local _default_val={
    item={
        item_type=1,
        sp_type=0,
        word=""
    },
    item_group={
        group=1,
        item_id=1,
        item_num=0
    },
    battle={
        score=100,
        num=10
    }
}
local _itemlist={
    i_31323_1_1={
        item_id=31323,
        num=1,
        is_bind=1
    },
    i_26232_40_1={
        item_id=26232,
        num=40,
        is_bind=1
    },
    i_31324_1_1={
        item_id=31324,
        num=1,
        is_bind=1
    },
    i_31325_1_1={
        item_id=31325,
        num=1,
        is_bind=1
    }
}
Config.lasso_game_auto={
    item={
        {
            item_id=1,
            score=10
        },
        {
            item_id=2,
            score=15,
            word="恭喜套中月华祝福的烟花，相同摆件全部消除"
        },
        {
            item_id=3,
            item_type=2,
            score=20
        },
        {
            item_id=4,
            item_type=2,
            score=25,
            word="恭喜套中月华祝福的花灯，相同摆件全部消除"
        },
        {
            item_id=5,
            item_type=3,
            score=30
        },
        {
            item_id=6,
            item_type=3,
            score=35,
            word="恭喜套中月华祝福的兔子，相同摆件全部消除"
        },
        {
            item_id=7,
            item_type=4,
            score=50,
            word="恭喜套中欢乐兔，九宫格内摆件全部消除"
        }
    },
    item_group={
        {
            item_num=27
        },
        {
            item_id=2,
            item_num=3
        },
        {
            item_id=3
        },
        {
            item_id=4
        },
        {
            item_id=5
        },
        {
            item_id=6
        },
        {
            item_id=7
        },
        {
            group=2,
            item_num=20
        },
        {
            group=2,
            item_id=2,
            item_num=7
        },
        {
            group=2,
            item_id=3,
            item_num=3
        },
        {
            group=2,
            item_id=4
        },
        {
            group=2,
            item_id=5
        },
        {
            group=2,
            item_id=6
        },
        {
            group=2,
            item_id=7
        },
        {
            group=3,
            item_num=17
        },
        {
            group=3,
            item_id=2,
            item_num=9
        },
        {
            group=3,
            item_id=3,
            item_num=2
        },
        {
            group=3,
            item_id=4,
            item_num=2
        },
        {
            group=3,
            item_id=5
        },
        {
            group=3,
            item_id=6
        },
        {
            group=3,
            item_id=7
        },
        {
            group=4,
            item_num=15
        },
        {
            group=4,
            item_id=2,
            item_num=7
        },
        {
            group=4,
            item_id=3,
            item_num=6
        },
        {
            group=4,
            item_id=4,
            item_num=2
        },
        {
            group=4,
            item_id=5
        },
        {
            group=4,
            item_id=6
        },
        {
            group=4,
            item_id=7
        },
        {
            group=5,
            item_num=13
        },
        {
            group=5,
            item_id=2,
            item_num=5
        },
        {
            group=5,
            item_id=3,
            item_num=5
        },
        {
            group=5,
            item_id=4,
            item_num=4
        },
        {
            group=5,
            item_id=5,
            item_num=3
        },
        {
            group=5,
            item_id=6
        },
        {
            group=5,
            item_id=7
        },
        {
            group=6,
            item_num=10
        },
        {
            group=6,
            item_id=2,
            item_num=3
        },
        {
            group=6,
            item_id=3,
            item_num=5
        },
        {
            group=6,
            item_id=4,
            item_num=4
        },
        {
            group=6,
            item_id=5,
            item_num=5
        },
        {
            group=6,
            item_id=6,
            item_num=3
        },
        {
            group=6,
            item_id=7
        },
        {
            group=7,
            item_num=7
        },
        {
            group=7,
            item_id=2,
            item_num=5
        },
        {
            group=7,
            item_id=3,
            item_num=6
        },
        {
            group=7,
            item_id=4,
            item_num=5
        },
        {
            group=7,
            item_id=5,
            item_num=4
        },
        {
            group=7,
            item_id=6,
            item_num=3
        },
        {
            group=7,
            item_id=7
        },
        {
            group=8,
            item_num=5
        },
        {
            group=8,
            item_id=2,
            item_num=6
        },
        {
            group=8,
            item_id=3,
            item_num=3
        },
        {
            group=8,
            item_id=4,
            item_num=6
        },
        {
            group=8,
            item_id=5,
            item_num=3
        },
        {
            group=8,
            item_id=6,
            item_num=6
        },
        {
            group=8,
            item_id=7,
            item_num=1
        },
        {
            group=9,
            item_num=3
        },
        {
            group=9,
            item_id=2,
            item_num=6
        },
        {
            group=9,
            item_id=3,
            item_num=3
        },
        {
            group=9,
            item_id=4,
            item_num=6
        },
        {
            group=9,
            item_id=5,
            item_num=3
        },
        {
            group=9,
            item_id=6,
            item_num=6
        },
        {
            group=9,
            item_id=7,
            item_num=3
        },
        {
            group=10,
            item_num=3
        },
        {
            group=10,
            item_id=2,
            item_num=2
        },
        {
            group=10,
            item_id=3,
            item_num=3
        },
        {
            group=10,
            item_id=4,
            item_num=5
        },
        {
            group=10,
            item_id=5,
            item_num=5
        },
        {
            group=10,
            item_id=6,
            item_num=7
        },
        {
            group=10,
            item_id=7,
            item_num=5
        }
    },
    reward={
        {
            score=0,
            score_desc="距离第一阶段奖励只差%s分了",
            show_reward=0
        },
        {
            score=60,
            final_reward={
                [0]=_itemlist.i_31323_1_1,
                [1]=_itemlist.i_26232_40_1
            },
            score_desc="当前已获得五宝莲台灯",
            show_reward=31323
        },
        {
            score=120,
            final_reward={
                [0]=_itemlist.i_31324_1_1,
                [1]=_itemlist.i_26232_40_1
            },
            score_desc="当前已获得七星水晶灯",
            show_reward=31324
        },
        {
            score=200,
            final_reward={
                [0]=_itemlist.i_31325_1_1,
                [1]=_itemlist.i_26232_40_1
            },
            score_desc="当前已获得九转琉璃灯",
            show_reward=31325
        }
    },
    other={
        {
            circle_num=10,
            column_num=6,
            row_num=5,
            reward_show="31325:26232",
            desc1=299,
            desc2=300,
            npc_id=73700,
            scene_id=328,
            reward_time=2,
            title_item_id=28928,
            title_id=190,
            title_score=1000
        }
    },
    battle={
        {
            group=1,
            score=50,
            num=15
        },
        {
            group=2,
            score=80,
            num=15
        },
        {
            group=3,
            num=15
        },
        {
            group=4,
            score=80
        },
        {
            group=5
        },
        {
            group=6,
            score=130
        },
        {
            group=7,
            score=150
        },
        {
            group=8,
            num=8
        },
        {
            group=9,
            score=150,
            num=8
        },
        {
            group=10,
            score=180,
            num=8
        }
    }
}
SetConfigDefaultVal(Config.lasso_game_auto,_default_val,nil,nil,nil)