local _default_val={
    discount={
        weight=1
    },
    reward={
        seq=0,
        type=0,
        original_price=1500,
        frequency=10,
        limit_type=2,
        section_start=29,
        section_end=35
    },
    activity_interface={
        is_show=0
    }
}
local _itemlist={
    i_25505_1_1={
        item_id=25505,
        num=1,
        is_bind=1
    },
    i_28067_1_1={
        item_id=28067,
        num=1,
        is_bind=1
    },
    i_25614_1_1={
        item_id=25614,
        num=1,
        is_bind=1
    },
    i_28186_1_1={
        item_id=28186,
        num=1,
        is_bind=1
    },
    i_25520_1_1={
        item_id=25520,
        num=1,
        is_bind=1
    },
    i_28070_1_1={
        item_id=28070,
        num=1,
        is_bind=1
    },
    i_28076_1_1={
        item_id=28076,
        num=1,
        is_bind=1
    },
    i_28556_1_1={
        item_id=28556,
        num=1,
        is_bind=1
    },
    i_29160_1_1={
        item_id=29160,
        num=1,
        is_bind=1
    },
    i_29159_1_1={
        item_id=29159,
        num=1,
        is_bind=1
    },
    i_28336_1_1={
        item_id=28336,
        num=1,
        is_bind=1
    },
    i_26410_1_1={
        item_id=26410,
        num=1,
        is_bind=1
    },
    i_28771_1_1={
        item_id=28771,
        num=1,
        is_bind=1
    },
    i_28187_1_1={
        item_id=28187,
        num=1,
        is_bind=1
    },
    i_56333_1_1={
        item_id=56333,
        num=1,
        is_bind=1
    },
    i_25678_1_1={
        item_id=25678,
        num=1,
        is_bind=1
    },
    i_25677_1_1={
        item_id=25677,
        num=1,
        is_bind=1
    },
    i_29018_1_1={
        item_id=29018,
        num=1,
        is_bind=1
    },
    i_29152_1_1={
        item_id=29152,
        num=1,
        is_bind=1
    },
    i_29107_1_1={
        item_id=29107,
        num=1,
        is_bind=1
    },
    i_29040_1_1={
        item_id=29040,
        num=1,
        is_bind=1
    },
    i_28157_1_1={
        item_id=28157,
        num=1,
        is_bind=1
    },
    i_29345_1_1={
        item_id=29345,
        num=1,
        is_bind=1
    },
    i_56453_1_1={
        item_id=56453,
        num=1,
        is_bind=1
    },
    i_56452_1_1={
        item_id=56452,
        num=1,
        is_bind=1
    },
    i_31468_1_1={
        item_id=31468,
        num=1,
        is_bind=1
    },
    i_25688_1_1={
        item_id=25688,
        num=1,
        is_bind=1
    },
    i_28156_1_1={
        item_id=28156,
        num=1,
        is_bind=1
    },
    i_56369_1_1={
        item_id=56369,
        num=1,
        is_bind=1
    },
    i_29378_10_1={
        item_id=29378,
        num=10,
        is_bind=1
    },
    i_56368_1_1={
        item_id=56368,
        num=1,
        is_bind=1
    },
    i_29077_1_1={
        item_id=29077,
        num=1,
        is_bind=1
    },
    i_29155_1_1={
        item_id=29155,
        num=1,
        is_bind=1
    },
    i_31398_1_1={
        item_id=31398,
        num=1,
        is_bind=1
    },
    i_26764_1_1={
        item_id=26764,
        num=1,
        is_bind=1
    },
    i_25853_1_1={
        item_id=25853,
        num=1,
        is_bind=1
    },
    i_28760_1_1={
        item_id=28760,
        num=1,
        is_bind=1
    },
    i_29319_1_1={
        item_id=29319,
        num=1,
        is_bind=1
    },
    i_29165_1_1={
        item_id=29165,
        num=1,
        is_bind=1
    },
    i_29444_1_1={
        item_id=29444,
        num=1,
        is_bind=1
    },
    i_56540_1_1={
        item_id=56540,
        num=1,
        is_bind=1
    },
    i_29445_1_1={
        item_id=29445,
        num=1,
        is_bind=1
    },
    i_31357_1_1={
        item_id=31357,
        num=1,
        is_bind=1
    },
    i_31358_1_1={
        item_id=31358,
        num=1,
        is_bind=1
    },
    i_31359_1_1={
        item_id=31359,
        num=1,
        is_bind=1
    },
    i_61506_1_1={
        item_id=61506,
        num=1,
        is_bind=1
    },
    i_61500_1_1={
        item_id=61500,
        num=1,
        is_bind=1
    },
    i_28310_1_1={
        item_id=28310,
        num=1,
        is_bind=1
    },
    i_28857_1_1={
        item_id=28857,
        num=1,
        is_bind=1
    }
}
Config.lucky_discount_auto={
    discount={
        {
            seq=0,
            proportion=7
        },
        {
            seq=1,
            proportion=6,
            weight=1000
        },
        {
            seq=2,
            proportion=5,
            weight=9000
        },
        {
            seq=3,
            proportion=8
        },
        {
            seq=4,
            proportion=9
        }
    },
    reward={
        {
            reward_item=_itemlist.i_25505_1_1,
            original_price=150,
            frequency=20,
            section_start=1,
            section_end=2
        },
        {
            seq=1,
            reward_item=_itemlist.i_28067_1_1,
            original_price=960,
            frequency=20,
            section_start=1,
            section_end=2
        },
        {
            seq=2,
            reward_item=_itemlist.i_25614_1_1,
            original_price=1176,
            frequency=2,
            section_start=1,
            section_end=2
        },
        {
            seq=3,
            reward_item=_itemlist.i_28186_1_1,
            original_price=450,
            frequency=5,
            section_start=1,
            section_end=2
        },
        {
            seq=4,
            reward_item=_itemlist.i_25520_1_1,
            original_price=900,
            frequency=5,
            section_start=1,
            section_end=2
        },
        {
            seq=5,
            reward_item=_itemlist.i_28070_1_1,
            original_price=2760,
            frequency=20,
            section_start=1,
            section_end=2
        },
        {
            seq=6,
            reward_item=_itemlist.i_28076_1_1,
            original_price=450,
            section_start=1,
            section_end=2
        },
        {
            seq=7,
            reward_item=_itemlist.i_28556_1_1,
            original_price=60,
            frequency=5,
            section_start=1,
            section_end=2
        },
        {
            reward_item=_itemlist.i_29160_1_1,
            original_price=2500,
            frequency=20,
            section_start=3,
            section_end=7
        },
        {
            seq=1,
            reward_item=_itemlist.i_29159_1_1,
            original_price=1000,
            frequency=20,
            section_start=3,
            section_end=7
        },
        {
            seq=2,
            reward_item=_itemlist.i_28336_1_1,
            frequency=6,
            section_start=3,
            section_end=7
        },
        {
            seq=3,
            reward_item=_itemlist.i_26410_1_1,
            original_price=6480,
            frequency=1,
            limit_type=1,
            section_start=3,
            section_end=7
        },
        {
            seq=4,
            reward_item=_itemlist.i_28771_1_1,
            original_price=776,
            frequency=20,
            section_start=3,
            section_end=7
        },
        {
            seq=5,
            reward_item=_itemlist.i_28070_1_1,
            original_price=2760,
            frequency=20,
            section_start=3,
            section_end=7
        },
        {
            seq=6,
            reward_item=_itemlist.i_28187_1_1,
            original_price=2750,
            frequency=20,
            section_start=3,
            section_end=7
        },
        {
            seq=7,
            reward_item=_itemlist.i_28186_1_1,
            original_price=450,
            frequency=5,
            section_start=3,
            section_end=7
        },
        {
            seq=8,
            reward_item=_itemlist.i_56333_1_1,
            original_price=500,
            frequency=99,
            section_start=3,
            section_end=7
        },
        {
            seq=9,
            reward_item=_itemlist.i_25614_1_1,
            original_price=976,
            frequency=3,
            section_start=3,
            section_end=7
        },
        {
            seq=10,
            reward_item=_itemlist.i_28076_1_1,
            original_price=450,
            section_start=3,
            section_end=7
        },
        {
            seq=11,
            reward_item=_itemlist.i_25678_1_1,
            original_price=1716,
            frequency=1,
            section_start=3,
            section_end=7
        },
        {
            seq=12,
            reward_item=_itemlist.i_25677_1_1,
            original_price=760,
            frequency=1,
            section_start=3,
            section_end=7
        },
        {
            seq=13,
            reward_item=_itemlist.i_29018_1_1,
            original_price=40,
            section_start=3,
            section_end=7
        },
        {
            seq=14,
            reward_item=_itemlist.i_29152_1_1,
            frequency=2,
            section_start=3,
            section_end=7
        },
        {
            reward_item=_itemlist.i_28336_1_1,
            frequency=6,
            section_start=8,
            section_end=14
        },
        {
            seq=1,
            reward_item=_itemlist.i_28070_1_1,
            original_price=2160,
            frequency=20,
            section_start=8,
            section_end=14
        },
        {
            seq=2,
            reward_item=_itemlist.i_28187_1_1,
            original_price=2750,
            frequency=20,
            section_start=8,
            section_end=14
        },
        {
            seq=3,
            reward_item=_itemlist.i_29107_1_1,
            original_price=360,
            section_start=8,
            section_end=14
        },
        {
            seq=4,
            reward_item=_itemlist.i_29040_1_1,
            frequency=30,
            section_start=8,
            section_end=14
        },
        {
            seq=5,
            reward_item=_itemlist.i_28157_1_1,
            original_price=1120,
            section_start=8,
            section_end=14
        },
        {
            seq=6,
            reward_item=_itemlist.i_56333_1_1,
            original_price=500,
            frequency=99,
            section_start=8,
            section_end=14
        },
        {
            seq=7,
            reward_item=_itemlist.i_25678_1_1,
            original_price=1716,
            frequency=1,
            section_start=8,
            section_end=14
        },
        {
            seq=8,
            reward_item=_itemlist.i_25677_1_1,
            original_price=760,
            frequency=1,
            section_start=8,
            section_end=14
        },
        {
            seq=9,
            reward_item=_itemlist.i_25614_1_1,
            original_price=976,
            frequency=3,
            section_start=8,
            section_end=14
        },
        {
            seq=10,
            reward_item=_itemlist.i_28076_1_1,
            original_price=450,
            section_start=8,
            section_end=14
        },
        {
            seq=11,
            reward_item=_itemlist.i_29345_1_1,
            original_price=100,
            section_start=8,
            section_end=14
        },
        {
            seq=12,
            reward_item=_itemlist.i_29152_1_1,
            frequency=2,
            section_start=8,
            section_end=14
        },
        {
            seq=13,
            reward_item=_itemlist.i_29160_1_1,
            original_price=2500,
            frequency=20,
            section_start=8,
            section_end=14
        },
        {
            seq=14,
            reward_item=_itemlist.i_29159_1_1,
            original_price=1000,
            frequency=20,
            section_start=8,
            section_end=14
        },
        {
            reward_item=_itemlist.i_56453_1_1,
            original_price=3280,
            frequency=3,
            section_start=15,
            section_end=21
        },
        {
            seq=1,
            reward_item=_itemlist.i_56452_1_1,
            original_price=980,
            frequency=3,
            section_start=15,
            section_end=21
        },
        {
            seq=2,
            reward_item=_itemlist.i_31468_1_1,
            original_price=2010,
            frequency=3,
            section_start=15,
            section_end=21
        },
        {
            seq=3,
            reward_item=_itemlist.i_25688_1_1,
            original_price=600,
            section_start=15,
            section_end=21
        },
        {
            seq=4,
            reward_item=_itemlist.i_28156_1_1,
            original_price=360,
            section_start=15,
            section_end=21
        },
        {
            seq=5,
            reward_item=_itemlist.i_28336_1_1,
            frequency=6,
            section_start=15,
            section_end=21
        },
        {
            seq=6,
            reward_item=_itemlist.i_56333_1_1,
            original_price=500,
            frequency=99,
            section_start=15,
            section_end=21
        },
        {
            seq=7,
            reward_item=_itemlist.i_29107_1_1,
            original_price=360,
            section_start=15,
            section_end=21
        },
        {
            seq=8,
            reward_item=_itemlist.i_29040_1_1,
            frequency=30,
            section_start=15,
            section_end=21
        },
        {
            seq=9,
            reward_item=_itemlist.i_25678_1_1,
            original_price=1716,
            frequency=1,
            section_start=15,
            section_end=21
        },
        {
            seq=10,
            reward_item=_itemlist.i_25677_1_1,
            original_price=760,
            frequency=1,
            section_start=15,
            section_end=21
        },
        {
            seq=11,
            reward_item=_itemlist.i_25614_1_1,
            original_price=976,
            frequency=3,
            section_start=15,
            section_end=21
        },
        {
            seq=12,
            reward_item=_itemlist.i_28076_1_1,
            original_price=450,
            section_start=15,
            section_end=21
        },
        {
            seq=13,
            reward_item=_itemlist.i_29345_1_1,
            original_price=100,
            frequency=20,
            section_start=15,
            section_end=21
        },
        {
            seq=14,
            reward_item=_itemlist.i_29152_1_1,
            frequency=2,
            section_start=15,
            section_end=21
        },
        {
            seq=15,
            reward_item=_itemlist.i_29160_1_1,
            original_price=2500,
            frequency=20,
            section_start=15,
            section_end=21
        },
        {
            seq=16,
            reward_item=_itemlist.i_29159_1_1,
            original_price=1000,
            frequency=20,
            section_start=15,
            section_end=21
        },
        {
            seq=17,
            reward_item=_itemlist.i_28070_1_1,
            original_price=2160,
            frequency=20,
            section_start=15,
            section_end=21
        },
        {
            seq=18,
            reward_item=_itemlist.i_28187_1_1,
            original_price=2750,
            frequency=20,
            section_start=15,
            section_end=21
        },
        {
            seq=19,
            reward_item=_itemlist.i_28157_1_1,
            original_price=1120,
            section_start=15,
            section_end=21
        },
        {
            reward_item=_itemlist.i_56369_1_1,
            original_price=700,
            frequency=100,
            section_start=22,
            section_end=28
        },
        {
            seq=1,
            reward_item=_itemlist.i_29378_10_1,
            original_price=4000,
            frequency=99,
            section_start=22,
            section_end=28
        },
        {
            seq=2,
            reward_item=_itemlist.i_56368_1_1,
            original_price=1400,
            section_start=22,
            section_end=28
        },
        {
            seq=3,
            reward_item=_itemlist.i_56453_1_1,
            original_price=3280,
            frequency=3,
            section_start=22,
            section_end=28
        },
        {
            seq=4,
            reward_item=_itemlist.i_56452_1_1,
            original_price=980,
            frequency=3,
            section_start=22,
            section_end=28
        },
        {
            seq=5,
            reward_item=_itemlist.i_31468_1_1,
            original_price=2010,
            frequency=3,
            section_start=22,
            section_end=28
        },
        {
            seq=6,
            reward_item=_itemlist.i_28336_1_1,
            frequency=6,
            section_start=22,
            section_end=28
        },
        {
            seq=7,
            reward_item=_itemlist.i_29107_1_1,
            original_price=360,
            section_start=22,
            section_end=28
        },
        {
            seq=8,
            reward_item=_itemlist.i_29077_1_1,
            original_price=180,
            section_start=22,
            section_end=28
        },
        {
            seq=9,
            reward_item=_itemlist.i_29040_1_1,
            frequency=30,
            section_start=22,
            section_end=28
        },
        {
            seq=10,
            reward_item=_itemlist.i_56333_1_1,
            original_price=500,
            frequency=99,
            section_start=22,
            section_end=28
        },
        {
            seq=11,
            reward_item=_itemlist.i_25688_1_1,
            original_price=600,
            section_start=22,
            section_end=28
        },
        {
            seq=12,
            reward_item=_itemlist.i_28156_1_1,
            original_price=360,
            section_start=22,
            section_end=28
        },
        {
            seq=13,
            reward_item=_itemlist.i_25614_1_1,
            original_price=976,
            frequency=3,
            section_start=22,
            section_end=28
        },
        {
            seq=14,
            reward_item=_itemlist.i_28076_1_1,
            original_price=450,
            section_start=22,
            section_end=28
        },
        {
            seq=15,
            reward_item=_itemlist.i_29345_1_1,
            original_price=90,
            frequency=30,
            section_start=22,
            section_end=28
        },
        {
            seq=16,
            reward_item=_itemlist.i_29152_1_1,
            frequency=2,
            section_start=22,
            section_end=28
        },
        {
            seq=17,
            reward_item=_itemlist.i_29160_1_1,
            original_price=2500,
            frequency=20,
            section_start=22,
            section_end=28
        },
        {
            seq=18,
            reward_item=_itemlist.i_29159_1_1,
            original_price=1000,
            frequency=20,
            section_start=22,
            section_end=28
        },
        {
            seq=19,
            reward_item=_itemlist.i_28070_1_1,
            original_price=1960,
            frequency=20,
            section_start=22,
            section_end=28
        },
        {
            seq=20,
            reward_item=_itemlist.i_28187_1_1,
            original_price=2350,
            frequency=20,
            section_start=22,
            section_end=28
        },
        {
            seq=21,
            reward_item=_itemlist.i_28157_1_1,
            original_price=1120,
            section_start=22,
            section_end=28
        },
        {
            reward_item=_itemlist.i_56369_1_1,
            original_price=700,
            frequency=100
        },
        {
            seq=1,
            reward_item=_itemlist.i_29378_10_1,
            original_price=4000,
            frequency=99
        },
        {
            seq=2,
            reward_item=_itemlist.i_56368_1_1,
            original_price=1400
        },
        {
            seq=3,
            reward_item=_itemlist.i_29155_1_1,
            original_price=3500,
            frequency=1
        },
        {
            seq=4,
            reward_item=_itemlist.i_31398_1_1,
            original_price=3800,
            frequency=5
        },
        {
            seq=5,
            reward_item=_itemlist.i_56453_1_1,
            original_price=3280,
            frequency=3
        },
        {
            seq=6,
            reward_item=_itemlist.i_56452_1_1,
            original_price=980,
            frequency=3
        },
        {
            seq=7,
            reward_item=_itemlist.i_31468_1_1,
            original_price=2010,
            frequency=3
        },
        {
            seq=8,
            reward_item=_itemlist.i_26764_1_1,
            original_price=150,
            frequency=50
        },
        {
            seq=9,
            reward_item=_itemlist.i_29107_1_1,
            original_price=300
        },
        {
            seq=10,
            reward_item=_itemlist.i_29040_1_1,
            frequency=30
        },
        {
            seq=11,
            reward_item=_itemlist.i_29077_1_1,
            original_price=180
        },
        {
            seq=12,
            reward_item=_itemlist.i_56333_1_1,
            original_price=500,
            frequency=99
        },
        {
            seq=13,
            reward_item=_itemlist.i_25688_1_1,
            original_price=600
        },
        {
            seq=14,
            reward_item=_itemlist.i_28156_1_1,
            original_price=360
        },
        {
            seq=15,
            reward_item=_itemlist.i_25614_1_1,
            original_price=976,
            frequency=3
        },
        {
            seq=16,
            reward_item=_itemlist.i_28076_1_1,
            original_price=450
        },
        {
            seq=17,
            reward_item=_itemlist.i_29345_1_1,
            original_price=90,
            frequency=40
        },
        {
            seq=18,
            reward_item=_itemlist.i_29152_1_1,
            frequency=2
        },
        {
            seq=19,
            reward_item=_itemlist.i_29160_1_1,
            original_price=2500,
            frequency=20
        },
        {
            seq=20,
            reward_item=_itemlist.i_29159_1_1,
            original_price=1000,
            frequency=20
        },
        {
            seq=21,
            reward_item=_itemlist.i_28336_1_1,
            frequency=6
        },
        {
            seq=22,
            reward_item=_itemlist.i_28187_1_1,
            original_price=2350,
            frequency=20
        },
        {
            seq=23,
            reward_item=_itemlist.i_28157_1_1,
            original_price=1120
        },
        {
            reward_item=_itemlist.i_25853_1_1,
            original_price=3300,
            frequency=5,
            section_start=36,
            section_end=44
        },
        {
            seq=1,
            reward_item=_itemlist.i_29155_1_1,
            original_price=3500,
            frequency=1,
            section_start=36,
            section_end=44
        },
        {
            seq=2,
            reward_item=_itemlist.i_31398_1_1,
            original_price=3800,
            frequency=5,
            section_start=36,
            section_end=44
        },
        {
            seq=3,
            reward_item=_itemlist.i_26764_1_1,
            original_price=150,
            frequency=50,
            section_start=36,
            section_end=44
        },
        {
            seq=4,
            reward_item=_itemlist.i_56453_1_1,
            original_price=3280,
            frequency=3,
            section_start=36,
            section_end=44
        },
        {
            seq=5,
            reward_item=_itemlist.i_56452_1_1,
            original_price=980,
            frequency=3,
            section_start=36,
            section_end=44
        },
        {
            seq=6,
            reward_item=_itemlist.i_31468_1_1,
            original_price=2010,
            frequency=3,
            section_start=36,
            section_end=44
        },
        {
            seq=7,
            reward_item=_itemlist.i_28760_1_1,
            original_price=1800,
            frequency=20,
            section_start=36,
            section_end=44
        },
        {
            seq=8,
            reward_item=_itemlist.i_29040_1_1,
            frequency=30,
            section_start=36,
            section_end=44
        },
        {
            seq=9,
            reward_item=_itemlist.i_29107_1_1,
            original_price=300,
            section_start=36,
            section_end=44
        },
        {
            seq=10,
            reward_item=_itemlist.i_56333_1_1,
            original_price=500,
            frequency=99,
            section_start=36,
            section_end=44
        },
        {
            seq=11,
            reward_item=_itemlist.i_25688_1_1,
            original_price=600,
            section_start=36,
            section_end=44
        },
        {
            seq=12,
            reward_item=_itemlist.i_28156_1_1,
            original_price=360,
            section_start=36,
            section_end=44
        },
        {
            seq=13,
            reward_item=_itemlist.i_25614_1_1,
            original_price=976,
            frequency=3,
            section_start=36,
            section_end=44
        },
        {
            seq=14,
            reward_item=_itemlist.i_28076_1_1,
            original_price=450,
            section_start=36,
            section_end=44
        },
        {
            seq=15,
            reward_item=_itemlist.i_29345_1_1,
            original_price=80,
            frequency=40,
            section_start=36,
            section_end=44
        },
        {
            seq=16,
            reward_item=_itemlist.i_29152_1_1,
            frequency=2,
            section_start=36,
            section_end=44
        },
        {
            seq=17,
            reward_item=_itemlist.i_29160_1_1,
            original_price=2500,
            frequency=20,
            section_start=36,
            section_end=44
        },
        {
            seq=18,
            reward_item=_itemlist.i_29159_1_1,
            original_price=1000,
            frequency=20,
            section_start=36,
            section_end=44
        },
        {
            seq=19,
            reward_item=_itemlist.i_56369_1_1,
            original_price=700,
            frequency=100,
            section_start=36,
            section_end=44
        },
        {
            seq=20,
            reward_item=_itemlist.i_29378_10_1,
            original_price=4000,
            frequency=99,
            section_start=36,
            section_end=44
        },
        {
            seq=21,
            reward_item=_itemlist.i_56368_1_1,
            original_price=1400,
            section_start=36,
            section_end=44
        },
        {
            seq=22,
            reward_item=_itemlist.i_28187_1_1,
            original_price=2150,
            frequency=20,
            section_start=36,
            section_end=44
        },
        {
            seq=23,
            reward_item=_itemlist.i_28157_1_1,
            original_price=1120,
            section_start=36,
            section_end=44
        },
        {
            reward_item=_itemlist.i_25853_1_1,
            original_price=3300,
            frequency=5,
            section_start=45,
            section_end=57
        },
        {
            seq=1,
            reward_item=_itemlist.i_29155_1_1,
            original_price=3500,
            frequency=1,
            section_start=45,
            section_end=57
        },
        {
            seq=2,
            reward_item=_itemlist.i_31398_1_1,
            original_price=3800,
            frequency=5,
            section_start=45,
            section_end=57
        },
        {
            seq=3,
            reward_item=_itemlist.i_29319_1_1,
            original_price=1200,
            frequency=50,
            section_start=45,
            section_end=57
        },
        {
            seq=4,
            reward_item=_itemlist.i_56453_1_1,
            original_price=3280,
            frequency=3,
            section_start=45,
            section_end=57
        },
        {
            seq=5,
            reward_item=_itemlist.i_56452_1_1,
            original_price=980,
            frequency=3,
            section_start=45,
            section_end=57
        },
        {
            seq=6,
            reward_item=_itemlist.i_31468_1_1,
            original_price=2010,
            frequency=3,
            section_start=45,
            section_end=57
        },
        {
            seq=7,
            reward_item=_itemlist.i_29165_1_1,
            original_price=2750,
            frequency=3,
            limit_type=1,
            section_start=45,
            section_end=57
        },
        {
            seq=8,
            reward_item=_itemlist.i_29444_1_1,
            original_price=960,
            section_start=45,
            section_end=57
        },
        {
            seq=9,
            reward_item=_itemlist.i_56540_1_1,
            original_price=500,
            frequency=30,
            section_start=45,
            section_end=57
        },
        {
            seq=10,
            reward_item=_itemlist.i_29445_1_1,
            original_price=2175,
            section_start=45,
            section_end=57
        },
        {
            seq=11,
            reward_item=_itemlist.i_31357_1_1,
            original_price=1400,
            frequency=2,
            limit_type=1,
            section_start=45,
            section_end=57
        },
        {
            seq=12,
            reward_item=_itemlist.i_29040_1_1,
            frequency=30,
            section_start=45,
            section_end=57
        },
        {
            seq=13,
            reward_item=_itemlist.i_29107_1_1,
            original_price=300,
            section_start=45,
            section_end=57
        },
        {
            seq=14,
            reward_item=_itemlist.i_56333_1_1,
            original_price=500,
            frequency=99,
            section_start=45,
            section_end=57
        },
        {
            seq=15,
            reward_item=_itemlist.i_28156_1_1,
            original_price=360,
            section_start=45,
            section_end=57
        },
        {
            seq=16,
            reward_item=_itemlist.i_28076_1_1,
            original_price=450,
            section_start=45,
            section_end=57
        },
        {
            seq=17,
            reward_item=_itemlist.i_29345_1_1,
            original_price=80,
            frequency=40,
            section_start=45,
            section_end=57
        },
        {
            seq=18,
            reward_item=_itemlist.i_29152_1_1,
            frequency=2,
            section_start=45,
            section_end=57
        },
        {
            seq=19,
            reward_item=_itemlist.i_29160_1_1,
            original_price=2500,
            frequency=20,
            section_start=45,
            section_end=57
        },
        {
            seq=20,
            reward_item=_itemlist.i_56369_1_1,
            original_price=700,
            frequency=100,
            section_start=45,
            section_end=57
        },
        {
            seq=21,
            reward_item=_itemlist.i_29378_10_1,
            original_price=4000,
            frequency=99,
            section_start=45,
            section_end=57
        },
        {
            seq=22,
            reward_item=_itemlist.i_56368_1_1,
            original_price=1400,
            section_start=45,
            section_end=57
        },
        {
            seq=23,
            reward_item=_itemlist.i_28187_1_1,
            original_price=2150,
            frequency=20,
            section_start=45,
            section_end=57
        },
        {
            reward_item=_itemlist.i_25853_1_1,
            original_price=3300,
            frequency=5,
            section_start=58,
            section_end=64
        },
        {
            seq=1,
            reward_item=_itemlist.i_29155_1_1,
            original_price=3500,
            frequency=1,
            section_start=58,
            section_end=64
        },
        {
            seq=2,
            reward_item=_itemlist.i_31398_1_1,
            original_price=3800,
            frequency=5,
            section_start=58,
            section_end=64
        },
        {
            seq=3,
            reward_item=_itemlist.i_29319_1_1,
            original_price=1200,
            frequency=50,
            section_start=58,
            section_end=64
        },
        {
            seq=4,
            reward_item=_itemlist.i_56453_1_1,
            original_price=3280,
            frequency=3,
            section_start=58,
            section_end=64
        },
        {
            seq=5,
            reward_item=_itemlist.i_56452_1_1,
            original_price=980,
            frequency=3,
            section_start=58,
            section_end=64
        },
        {
            seq=6,
            reward_item=_itemlist.i_31468_1_1,
            original_price=2010,
            frequency=3,
            section_start=58,
            section_end=64
        },
        {
            seq=7,
            reward_item=_itemlist.i_29165_1_1,
            original_price=2750,
            frequency=3,
            limit_type=1,
            section_start=58,
            section_end=64
        },
        {
            seq=8,
            reward_item=_itemlist.i_29444_1_1,
            original_price=960,
            section_start=58,
            section_end=64
        },
        {
            seq=9,
            reward_item=_itemlist.i_56540_1_1,
            original_price=500,
            frequency=30,
            section_start=58,
            section_end=64
        },
        {
            seq=10,
            reward_item=_itemlist.i_29445_1_1,
            original_price=2175,
            section_start=58,
            section_end=64
        },
        {
            seq=11,
            reward_item=_itemlist.i_31358_1_1,
            original_price=2000,
            frequency=2,
            limit_type=1,
            section_start=58,
            section_end=64
        },
        {
            seq=12,
            reward_item=_itemlist.i_29040_1_1,
            frequency=30,
            section_start=58,
            section_end=64
        },
        {
            seq=13,
            reward_item=_itemlist.i_29107_1_1,
            original_price=300,
            section_start=58,
            section_end=64
        },
        {
            seq=14,
            reward_item=_itemlist.i_56333_1_1,
            original_price=500,
            frequency=99,
            section_start=58,
            section_end=64
        },
        {
            seq=15,
            reward_item=_itemlist.i_28156_1_1,
            original_price=360,
            section_start=58,
            section_end=64
        },
        {
            seq=16,
            reward_item=_itemlist.i_28076_1_1,
            original_price=450,
            section_start=58,
            section_end=64
        },
        {
            seq=17,
            reward_item=_itemlist.i_29345_1_1,
            original_price=80,
            frequency=40,
            section_start=58,
            section_end=64
        },
        {
            seq=18,
            reward_item=_itemlist.i_29152_1_1,
            frequency=2,
            section_start=58,
            section_end=64
        },
        {
            seq=19,
            reward_item=_itemlist.i_29160_1_1,
            original_price=2500,
            frequency=20,
            section_start=58,
            section_end=64
        },
        {
            seq=20,
            reward_item=_itemlist.i_56369_1_1,
            original_price=700,
            frequency=100,
            section_start=58,
            section_end=64
        },
        {
            seq=21,
            reward_item=_itemlist.i_29378_10_1,
            original_price=4000,
            frequency=99,
            section_start=58,
            section_end=64
        },
        {
            seq=22,
            reward_item=_itemlist.i_56368_1_1,
            original_price=1400,
            section_start=58,
            section_end=64
        },
        {
            seq=23,
            reward_item=_itemlist.i_28187_1_1,
            original_price=2150,
            frequency=20,
            section_start=58,
            section_end=64
        },
        {
            reward_item=_itemlist.i_25853_1_1,
            original_price=3300,
            frequency=5,
            section_start=65,
            section_end=74
        },
        {
            seq=1,
            reward_item=_itemlist.i_29155_1_1,
            original_price=3500,
            frequency=1,
            section_start=65,
            section_end=74
        },
        {
            seq=2,
            reward_item=_itemlist.i_31398_1_1,
            original_price=3800,
            frequency=5,
            section_start=65,
            section_end=74
        },
        {
            seq=3,
            reward_item=_itemlist.i_29319_1_1,
            original_price=1200,
            frequency=50,
            section_start=65,
            section_end=74
        },
        {
            seq=4,
            reward_item=_itemlist.i_56453_1_1,
            original_price=3280,
            frequency=3,
            section_start=65,
            section_end=74
        },
        {
            seq=5,
            reward_item=_itemlist.i_56452_1_1,
            original_price=980,
            frequency=3,
            section_start=65,
            section_end=74
        },
        {
            seq=6,
            reward_item=_itemlist.i_31468_1_1,
            original_price=2010,
            frequency=3,
            section_start=65,
            section_end=74
        },
        {
            seq=7,
            reward_item=_itemlist.i_29165_1_1,
            original_price=2750,
            frequency=3,
            limit_type=1,
            section_start=65,
            section_end=74
        },
        {
            seq=8,
            reward_item=_itemlist.i_29444_1_1,
            original_price=960,
            section_start=65,
            section_end=74
        },
        {
            seq=9,
            reward_item=_itemlist.i_56540_1_1,
            original_price=500,
            frequency=30,
            section_start=65,
            section_end=74
        },
        {
            seq=10,
            reward_item=_itemlist.i_29445_1_1,
            original_price=2175,
            section_start=65,
            section_end=74
        },
        {
            seq=11,
            reward_item=_itemlist.i_31359_1_1,
            original_price=3200,
            frequency=2,
            limit_type=1,
            section_start=65,
            section_end=74
        },
        {
            seq=12,
            reward_item=_itemlist.i_29040_1_1,
            frequency=30,
            section_start=65,
            section_end=74
        },
        {
            seq=13,
            reward_item=_itemlist.i_29107_1_1,
            original_price=300,
            section_start=65,
            section_end=74
        },
        {
            seq=14,
            reward_item=_itemlist.i_56333_1_1,
            original_price=500,
            frequency=99,
            section_start=65,
            section_end=74
        },
        {
            seq=15,
            reward_item=_itemlist.i_28156_1_1,
            original_price=360,
            section_start=65,
            section_end=74
        },
        {
            seq=16,
            reward_item=_itemlist.i_28076_1_1,
            original_price=450,
            section_start=65,
            section_end=74
        },
        {
            seq=17,
            reward_item=_itemlist.i_29345_1_1,
            original_price=80,
            frequency=40,
            section_start=65,
            section_end=74
        },
        {
            seq=18,
            reward_item=_itemlist.i_29152_1_1,
            frequency=2,
            section_start=65,
            section_end=74
        },
        {
            seq=19,
            reward_item=_itemlist.i_29160_1_1,
            original_price=2500,
            frequency=20,
            section_start=65,
            section_end=74
        },
        {
            seq=20,
            reward_item=_itemlist.i_56369_1_1,
            original_price=700,
            frequency=100,
            section_start=65,
            section_end=74
        },
        {
            seq=21,
            reward_item=_itemlist.i_29378_10_1,
            original_price=4000,
            frequency=99,
            section_start=65,
            section_end=74
        },
        {
            seq=22,
            reward_item=_itemlist.i_56368_1_1,
            original_price=1400,
            section_start=65,
            section_end=74
        },
        {
            seq=23,
            reward_item=_itemlist.i_28187_1_1,
            original_price=2150,
            frequency=20,
            section_start=65,
            section_end=74
        },
        {
            reward_item=_itemlist.i_25853_1_1,
            original_price=3300,
            frequency=5,
            section_start=75,
            section_end=98
        },
        {
            seq=1,
            reward_item=_itemlist.i_29155_1_1,
            original_price=3500,
            frequency=1,
            section_start=75,
            section_end=98
        },
        {
            seq=2,
            reward_item=_itemlist.i_31398_1_1,
            original_price=3800,
            frequency=5,
            section_start=75,
            section_end=98
        },
        {
            seq=3,
            reward_item=_itemlist.i_29319_1_1,
            original_price=1200,
            frequency=50,
            section_start=75,
            section_end=98
        },
        {
            seq=4,
            reward_item=_itemlist.i_56453_1_1,
            original_price=3280,
            frequency=3,
            section_start=75,
            section_end=98
        },
        {
            seq=5,
            reward_item=_itemlist.i_56452_1_1,
            original_price=980,
            frequency=3,
            section_start=75,
            section_end=98
        },
        {
            seq=6,
            reward_item=_itemlist.i_31468_1_1,
            original_price=2010,
            frequency=3,
            section_start=75,
            section_end=98
        },
        {
            seq=7,
            reward_item=_itemlist.i_29165_1_1,
            original_price=2750,
            frequency=3,
            limit_type=1,
            section_start=75,
            section_end=98
        },
        {
            seq=8,
            reward_item=_itemlist.i_29444_1_1,
            original_price=960,
            section_start=75,
            section_end=98
        },
        {
            seq=9,
            reward_item=_itemlist.i_56540_1_1,
            original_price=500,
            frequency=30,
            section_start=75,
            section_end=98
        },
        {
            seq=10,
            reward_item=_itemlist.i_29445_1_1,
            original_price=2175,
            section_start=75,
            section_end=98
        },
        {
            seq=11,
            reward_item=_itemlist.i_61506_1_1,
            original_price=1760,
            frequency=20,
            section_start=75,
            section_end=98
        },
        {
            seq=12,
            reward_item=_itemlist.i_61500_1_1,
            original_price=810,
            frequency=20,
            section_start=75,
            section_end=98
        },
        {
            seq=13,
            reward_item=_itemlist.i_29040_1_1,
            frequency=30,
            section_start=75,
            section_end=98
        },
        {
            seq=14,
            reward_item=_itemlist.i_56333_1_1,
            original_price=500,
            frequency=99,
            section_start=75,
            section_end=98
        },
        {
            seq=15,
            reward_item=_itemlist.i_28310_1_1,
            original_price=600,
            section_start=75,
            section_end=98
        },
        {
            seq=16,
            reward_item=_itemlist.i_28076_1_1,
            original_price=450,
            section_start=75,
            section_end=98
        },
        {
            seq=17,
            reward_item=_itemlist.i_29345_1_1,
            original_price=80,
            frequency=40,
            section_start=75,
            section_end=98
        },
        {
            seq=18,
            reward_item=_itemlist.i_29152_1_1,
            frequency=2,
            section_start=75,
            section_end=98
        },
        {
            seq=19,
            reward_item=_itemlist.i_29160_1_1,
            original_price=2500,
            frequency=20,
            section_start=75,
            section_end=98
        },
        {
            seq=20,
            reward_item=_itemlist.i_56369_1_1,
            original_price=700,
            frequency=100,
            section_start=75,
            section_end=98
        },
        {
            seq=21,
            reward_item=_itemlist.i_29378_10_1,
            original_price=4000,
            frequency=99,
            section_start=75,
            section_end=98
        },
        {
            seq=22,
            reward_item=_itemlist.i_56368_1_1,
            original_price=1400,
            section_start=75,
            section_end=98
        },
        {
            seq=23,
            reward_item=_itemlist.i_28187_1_1,
            original_price=2150,
            frequency=20,
            section_start=75,
            section_end=98
        },
        {
            reward_item=_itemlist.i_29152_1_1,
            frequency=2,
            section_start=99,
            section_end=0
        },
        {
            seq=1,
            reward_item=_itemlist.i_29155_1_1,
            original_price=3500,
            frequency=1,
            section_start=99,
            section_end=0
        },
        {
            seq=2,
            reward_item=_itemlist.i_31398_1_1,
            original_price=3800,
            frequency=5,
            section_start=99,
            section_end=0
        },
        {
            seq=3,
            reward_item=_itemlist.i_29319_1_1,
            original_price=1200,
            frequency=50,
            section_start=99,
            section_end=0
        },
        {
            seq=4,
            reward_item=_itemlist.i_56453_1_1,
            original_price=3280,
            frequency=3,
            section_start=99,
            section_end=0
        },
        {
            seq=5,
            reward_item=_itemlist.i_56452_1_1,
            original_price=980,
            frequency=3,
            section_start=99,
            section_end=0
        },
        {
            seq=6,
            reward_item=_itemlist.i_31468_1_1,
            original_price=2010,
            frequency=3,
            section_start=99,
            section_end=0
        },
        {
            seq=7,
            reward_item=_itemlist.i_29165_1_1,
            original_price=2750,
            frequency=3,
            limit_type=1,
            section_start=99,
            section_end=0
        },
        {
            seq=8,
            reward_item=_itemlist.i_29444_1_1,
            original_price=960,
            section_start=99,
            section_end=0
        },
        {
            seq=9,
            reward_item=_itemlist.i_56540_1_1,
            original_price=500,
            frequency=30,
            section_start=99,
            section_end=0
        },
        {
            seq=10,
            reward_item=_itemlist.i_29445_1_1,
            original_price=2175,
            section_start=99,
            section_end=0
        },
        {
            seq=11,
            reward_item=_itemlist.i_25853_1_1,
            original_price=3300,
            frequency=5,
            section_start=99,
            section_end=0
        },
        {
            seq=12,
            reward_item=_itemlist.i_61506_1_1,
            original_price=1760,
            frequency=20,
            section_start=99,
            section_end=0
        },
        {
            seq=13,
            reward_item=_itemlist.i_61500_1_1,
            original_price=810,
            frequency=20,
            section_start=99,
            section_end=0
        },
        {
            seq=14,
            reward_item=_itemlist.i_28857_1_1,
            original_price=2176,
            section_start=99,
            section_end=0
        },
        {
            seq=15,
            reward_item=_itemlist.i_29107_1_1,
            original_price=300,
            section_start=99,
            section_end=0
        },
        {
            seq=16,
            reward_item=_itemlist.i_56333_1_1,
            original_price=500,
            frequency=99,
            section_start=99,
            section_end=0
        },
        {
            seq=17,
            reward_item=_itemlist.i_28310_1_1,
            original_price=600,
            section_start=99,
            section_end=0
        },
        {
            seq=18,
            reward_item=_itemlist.i_28076_1_1,
            original_price=450,
            section_start=99,
            section_end=0
        },
        {
            seq=19,
            reward_item=_itemlist.i_29345_1_1,
            original_price=80,
            frequency=40,
            section_start=99,
            section_end=0
        },
        {
            seq=20,
            reward_item=_itemlist.i_56369_1_1,
            original_price=700,
            frequency=100,
            section_start=99,
            section_end=0
        },
        {
            seq=21,
            reward_item=_itemlist.i_29378_10_1,
            original_price=4000,
            frequency=99,
            section_start=99,
            section_end=0
        },
        {
            seq=22,
            reward_item=_itemlist.i_56368_1_1,
            original_price=1400,
            section_start=99,
            section_end=0
        },
        {
            seq=23,
            reward_item=_itemlist.i_28187_1_1,
            original_price=2150,
            frequency=20,
            section_start=99,
            section_end=0
        }
    },
    activity_interface={
        {
            interface=0
        },
        {
            interface=1,
            is_show=1
        },
        {
            interface=2
        },
        {
            interface=3
        },
        {
            interface=4
        },
        {
            interface=5
        },
        {
            interface=6
        }
    }
}
SetConfigDefaultVal(Config.lucky_discount_auto,_default_val,nil,nil,nil)