local _default_val={
    mentor_question={
        button_group=1,
        question="您目前的感情状态是……？",
        recommend_job=1
    },
    mentor_fb={
        min_level=1,
        max_level=55,
        verse_group=1,
        is_down=0,
        name="东风不与周郎便"
    },
    milepost={
        type=1,
        order=0
    },
    Passmerit_exp={
        reward_exp=53973
    }
}
local _itemlist={
    i_22005_10_1={
        item_id=22005,
        num=10,
        is_bind=1
    },
    i_31327_1_1={
        item_id=31327,
        num=1,
        is_bind=1
    },
    i_31328_1_1={
        item_id=31328,
        num=1,
        is_bind=1
    },
    i_31329_1_1={
        item_id=31329,
        num=1,
        is_bind=1
    },
    i_31300_2_1={
        item_id=31300,
        num=2,
        is_bind=1
    },
    i_31304_2_1={
        item_id=31304,
        num=2,
        is_bind=1
    },
    i_31300_3_1={
        item_id=31300,
        num=3,
        is_bind=1
    },
    i_31304_3_1={
        item_id=31304,
        num=3,
        is_bind=1
    },
    i_24518_1_1={
        item_id=24518,
        num=1,
        is_bind=1
    },
    i_31300_4_1={
        item_id=31300,
        num=4,
        is_bind=1
    },
    i_31304_4_1={
        item_id=31304,
        num=4,
        is_bind=1
    },
    i_31301_4_1={
        item_id=31301,
        num=4,
        is_bind=1
    },
    i_31311_4_1={
        item_id=31311,
        num=4,
        is_bind=1
    },
    i_31301_5_1={
        item_id=31301,
        num=5,
        is_bind=1
    },
    i_31321_1_1={
        item_id=31321,
        num=1,
        is_bind=1
    },
    i_31311_5_1={
        item_id=31311,
        num=5,
        is_bind=1
    },
    i_31301_6_1={
        item_id=31301,
        num=6,
        is_bind=1
    },
    i_31311_6_1={
        item_id=31311,
        num=6,
        is_bind=1
    },
    i_27398_1_1={
        item_id=27398,
        num=1,
        is_bind=1
    },
    i_28555_1_1={
        item_id=28555,
        num=1,
        is_bind=1
    },
    i_31302_1_1={
        item_id=31302,
        num=1,
        is_bind=1
    },
    i_27399_1_1={
        item_id=27399,
        num=1,
        is_bind=1
    },
    i_31303_1_1={
        item_id=31303,
        num=1,
        is_bind=1
    }
}
Config.mentor_cfg_auto={
    mentor_reward={
        {
            seq=0,
            days=3,
            reward_item1=_itemlist.i_22005_10_1,
            reward_item2=_itemlist.i_22005_10_1
        },
        {
            seq=1,
            days=7,
            reward_item1=_itemlist.i_22005_10_1,
            reward_item2=_itemlist.i_22005_10_1
        },
        {
            seq=2,
            days=14,
            reward_item1=_itemlist.i_22005_10_1,
            reward_item2=_itemlist.i_22005_10_1
        },
        {
            seq=3,
            days=21,
            reward_item1=_itemlist.i_22005_10_1,
            reward_item2=_itemlist.i_22005_10_1
        },
        {
            seq=4,
            days=30,
            reward_item1=_itemlist.i_22005_10_1,
            reward_item2=_itemlist.i_22005_10_1
        }
    },
    other={
        {
            graduate_level=60,
            graduate_days=30,
            npc_seq=115,
            mentor_fb_scene=1600,
            min_team_num=2,
            mentor_fb_time=900,
            verse_group_num=12,
            master_reward="65850:65851",
            apprentice_reward="65850:65851",
            reward_show="65850:65851",
            reward_show2="65850:65851",
            milepost_limit=3,
            passmerit_scene=324,
            passmerit_coordinate_x=48,
            passmerit_coordinate_y=50,
            passmerit_ready=6,
            passmerit_game_time=63,
            passmerit_exp_frequency=1,
            delay_time=15,
            not_online_time=259200,
            consume_amount=300,
            chill_time=43200,
            apply_show="若您的师傅或徒弟超过<color=#FF3E3E>3</color>天未上线，可申请解除师徒关系。申请后立即进入师徒关系冷静期。<color=#2789AA>(12小时内可取消解除）</color>",
            force_show="师傅或徒弟可通过消耗<color=#FF3E3E>300</color>元宝，强制解除师徒关系。强制解除后立即进入师徒关系冷静期。<color=#2789AA>(12小时内可取消解除）</color>"
        }
    },
    mentor_question={
        [1]={
            button_id=1,
            option="静待缘分"
        },
        [2]={
            button_id=2,
            option="甜蜜美满",
            recommend_job=3
        },
        [3]={
            button_id=3,
            option="佳人暗许",
            recommend_job=2
        },
        [4]={
            button_id=4,
            option="心灰意冷",
            recommend_job=5
        },
        [5]={
            button_id=5,
            button_group=2,
            question="你希望你的师傅/徒弟……",
            option="风华绝代"
        },
        [6]={
            button_id=6,
            button_group=2,
            question="你希望你的师傅/徒弟……",
            option="娇俏可爱",
            recommend_job=2
        },
        [7]={
            button_id=7,
            button_group=2,
            question="你希望你的师傅/徒弟……",
            option="高贵清冷",
            recommend_job=6
        },
        [8]={
            button_id=8,
            button_group=2,
            question="你希望你的师傅/徒弟……",
            option="威武霸气",
            recommend_job=4
        },
        [9]={
            button_id=9,
            button_group=3,
            question="你希望你的师傅/徒弟性格是……？",
            option="坚定果断",
            recommend_job=3
        },
        [10]={
            button_id=10,
            button_group=3,
            question="你希望你的师傅/徒弟性格是……？",
            option="小心谨慎",
            recommend_job=6
        },
        [11]={
            button_id=11,
            button_group=3,
            question="你希望你的师傅/徒弟性格是……？",
            option="圆滑老练",
            recommend_job=5
        },
        [12]={
            button_id=12,
            button_group=3,
            question="你希望你的师傅/徒弟性格是……？",
            option="豪放不羁",
            recommend_job=4
        }
    },
    mentor_fb={
        {
            index=1,
            npc_id=67000
        },
        {
            index=2,
            is_down=1,
            name="铜雀春深锁二乔",
            npc_id=67001
        },
        {
            index=3,
            verse_group=2,
            name="春宵苦短日高起",
            npc_id=67002
        },
        {
            index=4,
            verse_group=2,
            is_down=1,
            name="从此君王不早朝",
            npc_id=67003
        },
        {
            index=5,
            verse_group=3,
            name="得成比目何辞死",
            npc_id=67004
        },
        {
            index=6,
            verse_group=3,
            is_down=1,
            name="愿作鸳鸯不羡仙",
            npc_id=67005
        },
        {
            index=7,
            verse_group=4,
            name="情人眼里出西施",
            npc_id=67006
        },
        {
            index=8,
            verse_group=4,
            is_down=1,
            name="色不迷人人自迷",
            npc_id=67007
        },
        {
            index=9,
            verse_group=5,
            name="洛阳亲友如相问",
            npc_id=67008
        },
        {
            index=10,
            verse_group=5,
            is_down=1,
            name="一片冰心在玉壶",
            npc_id=67009
        },
        {
            index=11,
            verse_group=6,
            name="花谢花飞飞满天",
            npc_id=67010
        },
        {
            index=12,
            verse_group=6,
            is_down=1,
            name="红消香断有谁怜",
            npc_id=67011
        },
        {
            index=13,
            verse_group=7,
            name="天生我材必有用",
            npc_id=67012
        },
        {
            index=14,
            verse_group=7,
            is_down=1,
            name="千金散尽还复来",
            npc_id=67013
        },
        {
            index=15,
            verse_group=8,
            name="在天愿做比翼鸟",
            npc_id=67014
        },
        {
            index=16,
            verse_group=8,
            is_down=1,
            name="在地愿为连理枝",
            npc_id=67015
        },
        {
            index=17,
            verse_group=9,
            name="衣带渐宽终不悔",
            npc_id=67016
        },
        {
            index=18,
            verse_group=9,
            is_down=1,
            name="为伊消得人憔悴",
            npc_id=67017
        },
        {
            index=19,
            verse_group=10,
            name="东边日出西边雨",
            npc_id=67018
        },
        {
            index=20,
            verse_group=10,
            is_down=1,
            name="道是无晴却有晴",
            npc_id=67019
        },
        {
            index=21,
            verse_group=11,
            name="枝上柳绵吹又少",
            npc_id=67020
        },
        {
            index=22,
            verse_group=11,
            is_down=1,
            name="天涯何处无芳草",
            npc_id=67021
        },
        {
            index=23,
            verse_group=12,
            name="人生得意须进欢",
            npc_id=67022
        },
        {
            index=24,
            verse_group=12,
            is_down=1,
            name="莫使金樽空对月",
            npc_id=67023
        },
        {
            index=25,
            verse_group=13,
            name="今宵酒醒何处",
            npc_id=67024
        },
        {
            index=26,
            verse_group=13,
            is_down=1,
            name="杨柳岸晓风残月",
            npc_id=67025
        },
        {
            index=27,
            verse_group=14,
            name="葡萄美酒夜光杯",
            npc_id=67026
        },
        {
            index=28,
            verse_group=14,
            is_down=1,
            name="欲饮琵琶马上催",
            npc_id=67027
        },
        {
            index=29,
            verse_group=15,
            name="所谓伊人",
            npc_id=67028
        },
        {
            index=30,
            verse_group=15,
            is_down=1,
            name="在水一方",
            npc_id=67029
        },
        {
            index=31,
            verse_group=16,
            name="结发为夫妻",
            npc_id=67030
        },
        {
            index=32,
            verse_group=16,
            is_down=1,
            name="恩爱两不疑",
            npc_id=67031
        },
        {
            index=33,
            verse_group=17,
            name="羌笛何须怨杨柳",
            npc_id=67032
        },
        {
            index=34,
            verse_group=17,
            is_down=1,
            name="春风不度玉门关",
            npc_id=67033
        },
        {
            index=35,
            verse_group=18,
            name="天涯地角有穷时",
            npc_id=67034
        },
        {
            index=36,
            verse_group=18,
            is_down=1,
            name="只有相思无尽处",
            npc_id=67035
        },
        {
            index=37,
            verse_group=19,
            name="红豆生南国",
            npc_id=67036
        },
        {
            index=38,
            verse_group=19,
            is_down=1,
            name="春来发几枝",
            npc_id=67037
        },
        {
            index=39,
            verse_group=20,
            name="愿君多采颉",
            npc_id=67038
        },
        {
            index=40,
            verse_group=20,
            is_down=1,
            name="此物最相思",
            npc_id=67039
        },
        {
            index=41,
            verse_group=21,
            name="举杯邀明月",
            npc_id=67040
        },
        {
            index=42,
            verse_group=21,
            is_down=1,
            name="对影成三人",
            npc_id=67041
        },
        {
            index=43,
            verse_group=22,
            name="问世间情为何物",
            npc_id=67042
        },
        {
            index=44,
            verse_group=22,
            is_down=1,
            name="直叫人生死相许",
            npc_id=67043
        },
        {
            index=45,
            verse_group=23,
            name="满园春色关不住",
            npc_id=67044
        },
        {
            index=46,
            verse_group=23,
            is_down=1,
            name="一支红杏出墙来",
            npc_id=67045
        },
        {
            index=47,
            verse_group=24,
            name="同是天涯沦落人",
            npc_id=67046
        },
        {
            index=48,
            verse_group=24,
            is_down=1,
            name="相逢何必曾相识",
            npc_id=67047
        },
        {
            index=49,
            verse_group=25,
            name="千呼万唤始出来",
            npc_id=67048
        },
        {
            index=50,
            verse_group=25,
            is_down=1,
            name="犹抱琵琶半遮面",
            npc_id=67049
        },
        {
            index=51,
            verse_group=26,
            name="窈窕淑女",
            npc_id=67050
        },
        {
            index=52,
            verse_group=26,
            is_down=1,
            name="君子好逑",
            npc_id=67051
        },
        {
            index=53,
            verse_group=27,
            name="云想衣裳花想容",
            npc_id=67052
        },
        {
            index=54,
            verse_group=27,
            is_down=1,
            name="春风拂槛露华浓",
            npc_id=67053
        },
        {
            index=55,
            verse_group=28,
            name="但愿人长久",
            npc_id=67054
        },
        {
            index=56,
            verse_group=28,
            is_down=1,
            name="千里共婵娟",
            npc_id=67055
        },
        {
            index=57,
            verse_group=29,
            name="春蚕到死丝方尽",
            npc_id=67056
        },
        {
            index=58,
            verse_group=29,
            is_down=1,
            name="蜡炬成灰泪始干",
            npc_id=67057
        },
        {
            index=59,
            verse_group=30,
            name="身无彩凤双飞翼",
            npc_id=67058
        },
        {
            index=60,
            verse_group=30,
            is_down=1,
            name="心有灵犀一点通",
            npc_id=67059
        },
        {
            index=61,
            verse_group=31,
            name="天阶夜色凉如水",
            npc_id=67060
        },
        {
            index=62,
            verse_group=31,
            is_down=1,
            name="坐看牵牛织女星",
            npc_id=67061
        },
        {
            index=63,
            verse_group=32,
            name="愿得一心人",
            npc_id=67062
        },
        {
            index=64,
            verse_group=32,
            is_down=1,
            name="白头不相离",
            npc_id=67063
        },
        {
            index=65,
            verse_group=33,
            name="去年今日此门中",
            npc_id=67064
        },
        {
            index=66,
            verse_group=33,
            is_down=1,
            name="人面桃花相映红",
            npc_id=67065
        },
        {
            index=67,
            verse_group=34,
            name="月上柳梢头",
            npc_id=67066
        },
        {
            index=68,
            verse_group=34,
            is_down=1,
            name="人约黄昏后",
            npc_id=67067
        },
        {
            index=69,
            verse_group=35,
            name="锦瑟无端五十弦",
            npc_id=67068
        },
        {
            index=70,
            verse_group=35,
            is_down=1,
            name="一弦一柱思华年",
            npc_id=67069
        },
        {
            index=71,
            verse_group=36,
            name="停车坐爱枫林晚",
            npc_id=67070
        },
        {
            index=72,
            verse_group=36,
            is_down=1,
            name="霜叶红于二月花",
            npc_id=67071
        },
        {
            index=73,
            verse_group=37,
            name="相见时难别亦难",
            npc_id=67072
        },
        {
            index=74,
            verse_group=37,
            is_down=1,
            name="东风无力百花残",
            npc_id=67073
        },
        {
            index=75,
            verse_group=38,
            name="昨夜雨疏风骤",
            npc_id=67074
        },
        {
            index=76,
            verse_group=38,
            is_down=1,
            name="浓睡不消残酒",
            npc_id=67075
        },
        {
            index=77,
            verse_group=39,
            name="蓦然回首",
            npc_id=67076
        },
        {
            index=78,
            verse_group=39,
            is_down=1,
            name="那人却在灯火阑珊处",
            npc_id=67077
        },
        {
            index=79,
            verse_group=40,
            name="两情若是长久时",
            npc_id=67078
        },
        {
            index=80,
            verse_group=40,
            is_down=1,
            name="又岂在朝朝暮暮",
            npc_id=67079
        },
        {
            index=81,
            verse_group=41,
            name="无言独上西楼",
            npc_id=67080
        },
        {
            index=82,
            verse_group=41,
            is_down=1,
            name="月如钩",
            npc_id=67081
        },
        {
            index=83,
            verse_group=42,
            name="落花人独立",
            npc_id=67082
        },
        {
            index=84,
            verse_group=42,
            is_down=1,
            name="微雨燕双飞",
            npc_id=67083
        },
        {
            index=85,
            verse_group=43,
            name="还君明珠双泪垂",
            npc_id=67084
        },
        {
            index=86,
            verse_group=43,
            is_down=1,
            name="恨不相逢未嫁时",
            npc_id=67085
        },
        {
            index=87,
            verse_group=44,
            name="海上生明月",
            npc_id=67086
        },
        {
            index=88,
            verse_group=44,
            is_down=1,
            name="天涯共此时",
            npc_id=67087
        },
        {
            index=89,
            verse_group=45,
            name="海内存知己",
            npc_id=67088
        },
        {
            index=90,
            verse_group=45,
            is_down=1,
            name="天涯若比邻",
            npc_id=67089
        },
        {
            index=91,
            verse_group=46,
            name="回眸一笑百媚生",
            npc_id=67090
        },
        {
            index=92,
            verse_group=46,
            is_down=1,
            name="六宫粉黛无颜色",
            npc_id=67091
        },
        {
            index=93,
            verse_group=47,
            name="金风玉露一相逢",
            npc_id=67092
        },
        {
            index=94,
            verse_group=47,
            is_down=1,
            name="便胜却人间无数",
            npc_id=67093
        },
        {
            index=95,
            verse_group=48,
            name="夕阳无限好",
            npc_id=67094
        },
        {
            index=96,
            verse_group=48,
            is_down=1,
            name="只是近黄昏",
            npc_id=67095
        },
        {
            index=97,
            verse_group=49,
            name="二十四桥明月夜",
            npc_id=67096
        },
        {
            index=98,
            verse_group=49,
            is_down=1,
            name="玉人何处教吹萧",
            npc_id=67097
        },
        {
            index=99,
            verse_group=50,
            name="曾经沧海难为水",
            npc_id=67098
        },
        {
            index=100,
            verse_group=50,
            is_down=1,
            name="除却巫山不是云",
            npc_id=67099
        },
        {
            index=101,
            min_level=56,
            max_level=75,
            verse_group=51,
            npc_id=67100
        },
        {
            index=102,
            min_level=56,
            max_level=75,
            verse_group=51,
            is_down=1,
            name="铜雀春深锁二乔",
            npc_id=67101
        },
        {
            index=103,
            min_level=56,
            max_level=75,
            verse_group=52,
            name="春宵苦短日高起",
            npc_id=67102
        },
        {
            index=104,
            min_level=56,
            max_level=75,
            verse_group=52,
            is_down=1,
            name="从此君王不早朝",
            npc_id=67103
        },
        {
            index=105,
            min_level=56,
            max_level=75,
            verse_group=53,
            name="得成比目何辞死",
            npc_id=67104
        },
        {
            index=106,
            min_level=56,
            max_level=75,
            verse_group=53,
            is_down=1,
            name="愿作鸳鸯不羡仙",
            npc_id=67105
        },
        {
            index=107,
            min_level=56,
            max_level=75,
            verse_group=54,
            name="情人眼里出西施",
            npc_id=67106
        },
        {
            index=108,
            min_level=56,
            max_level=75,
            verse_group=54,
            is_down=1,
            name="色不迷人人自迷",
            npc_id=67107
        },
        {
            index=109,
            min_level=56,
            max_level=75,
            verse_group=55,
            name="洛阳亲友如相问",
            npc_id=67108
        },
        {
            index=110,
            min_level=56,
            max_level=75,
            verse_group=55,
            is_down=1,
            name="一片冰心在玉壶",
            npc_id=67109
        },
        {
            index=111,
            min_level=56,
            max_level=75,
            verse_group=56,
            name="花谢花飞飞满天",
            npc_id=67110
        },
        {
            index=112,
            min_level=56,
            max_level=75,
            verse_group=56,
            is_down=1,
            name="红消香断有谁怜",
            npc_id=67111
        },
        {
            index=113,
            min_level=56,
            max_level=75,
            verse_group=57,
            name="天生我材必有用",
            npc_id=67112
        },
        {
            index=114,
            min_level=56,
            max_level=75,
            verse_group=57,
            is_down=1,
            name="千金散尽还复来",
            npc_id=67113
        },
        {
            index=115,
            min_level=56,
            max_level=75,
            verse_group=58,
            name="在天愿做比翼鸟",
            npc_id=67114
        },
        {
            index=116,
            min_level=56,
            max_level=75,
            verse_group=58,
            is_down=1,
            name="在地愿为连理枝",
            npc_id=67115
        },
        {
            index=117,
            min_level=56,
            max_level=75,
            verse_group=59,
            name="衣带渐宽终不悔",
            npc_id=67116
        },
        {
            index=118,
            min_level=56,
            max_level=75,
            verse_group=59,
            is_down=1,
            name="为伊消得人憔悴",
            npc_id=67117
        },
        {
            index=119,
            min_level=56,
            max_level=75,
            verse_group=60,
            name="东边日出西边雨",
            npc_id=67118
        },
        {
            index=120,
            min_level=56,
            max_level=75,
            verse_group=60,
            is_down=1,
            name="道是无晴却有晴",
            npc_id=67119
        },
        {
            index=121,
            min_level=56,
            max_level=75,
            verse_group=61,
            name="枝上柳绵吹又少",
            npc_id=67120
        },
        {
            index=122,
            min_level=56,
            max_level=75,
            verse_group=61,
            is_down=1,
            name="天涯何处无芳草",
            npc_id=67121
        },
        {
            index=123,
            min_level=56,
            max_level=75,
            verse_group=62,
            name="人生得意须进欢",
            npc_id=67122
        },
        {
            index=124,
            min_level=56,
            max_level=75,
            verse_group=62,
            is_down=1,
            name="莫使金樽空对月",
            npc_id=67123
        },
        {
            index=125,
            min_level=56,
            max_level=75,
            verse_group=63,
            name="今宵酒醒何处",
            npc_id=67124
        },
        {
            index=126,
            min_level=56,
            max_level=75,
            verse_group=63,
            is_down=1,
            name="杨柳岸晓风残月",
            npc_id=67125
        },
        {
            index=127,
            min_level=56,
            max_level=75,
            verse_group=64,
            name="葡萄美酒夜光杯",
            npc_id=67126
        },
        {
            index=128,
            min_level=56,
            max_level=75,
            verse_group=64,
            is_down=1,
            name="欲饮琵琶马上催",
            npc_id=67127
        },
        {
            index=129,
            min_level=56,
            max_level=75,
            verse_group=65,
            name="所谓伊人",
            npc_id=67128
        },
        {
            index=130,
            min_level=56,
            max_level=75,
            verse_group=65,
            is_down=1,
            name="在水一方",
            npc_id=67129
        },
        {
            index=131,
            min_level=56,
            max_level=75,
            verse_group=66,
            name="结发为夫妻",
            npc_id=67130
        },
        {
            index=132,
            min_level=56,
            max_level=75,
            verse_group=66,
            is_down=1,
            name="恩爱两不疑",
            npc_id=67131
        },
        {
            index=133,
            min_level=56,
            max_level=75,
            verse_group=67,
            name="羌笛何须怨杨柳",
            npc_id=67132
        },
        {
            index=134,
            min_level=56,
            max_level=75,
            verse_group=67,
            is_down=1,
            name="春风不度玉门关",
            npc_id=67133
        },
        {
            index=135,
            min_level=56,
            max_level=75,
            verse_group=68,
            name="天涯地角有穷时",
            npc_id=67134
        },
        {
            index=136,
            min_level=56,
            max_level=75,
            verse_group=68,
            is_down=1,
            name="只有相思无尽处",
            npc_id=67135
        },
        {
            index=137,
            min_level=56,
            max_level=75,
            verse_group=69,
            name="红豆生南国",
            npc_id=67136
        },
        {
            index=138,
            min_level=56,
            max_level=75,
            verse_group=69,
            is_down=1,
            name="春来发几枝",
            npc_id=67137
        },
        {
            index=139,
            min_level=56,
            max_level=75,
            verse_group=70,
            name="愿君多采颉",
            npc_id=67138
        },
        {
            index=140,
            min_level=56,
            max_level=75,
            verse_group=70,
            is_down=1,
            name="此物最相思",
            npc_id=67139
        },
        {
            index=141,
            min_level=56,
            max_level=75,
            verse_group=71,
            name="举杯邀明月",
            npc_id=67140
        },
        {
            index=142,
            min_level=56,
            max_level=75,
            verse_group=71,
            is_down=1,
            name="对影成三人",
            npc_id=67141
        },
        {
            index=143,
            min_level=56,
            max_level=75,
            verse_group=72,
            name="问世间情为何物",
            npc_id=67142
        },
        {
            index=144,
            min_level=56,
            max_level=75,
            verse_group=72,
            is_down=1,
            name="直叫人生死相许",
            npc_id=67143
        },
        {
            index=145,
            min_level=56,
            max_level=75,
            verse_group=73,
            name="满园春色关不住",
            npc_id=67144
        },
        {
            index=146,
            min_level=56,
            max_level=75,
            verse_group=73,
            is_down=1,
            name="一支红杏出墙来",
            npc_id=67145
        },
        {
            index=147,
            min_level=56,
            max_level=75,
            verse_group=74,
            name="同是天涯沦落人",
            npc_id=67146
        },
        {
            index=148,
            min_level=56,
            max_level=75,
            verse_group=74,
            is_down=1,
            name="相逢何必曾相识",
            npc_id=67147
        },
        {
            index=149,
            min_level=56,
            max_level=75,
            verse_group=75,
            name="千呼万唤始出来",
            npc_id=67148
        },
        {
            index=150,
            min_level=56,
            max_level=75,
            verse_group=75,
            is_down=1,
            name="犹抱琵琶半遮面",
            npc_id=67149
        },
        {
            index=151,
            min_level=56,
            max_level=75,
            verse_group=76,
            name="窈窕淑女",
            npc_id=67150
        },
        {
            index=152,
            min_level=56,
            max_level=75,
            verse_group=76,
            is_down=1,
            name="君子好逑",
            npc_id=67151
        },
        {
            index=153,
            min_level=56,
            max_level=75,
            verse_group=77,
            name="云想衣裳花想容",
            npc_id=67152
        },
        {
            index=154,
            min_level=56,
            max_level=75,
            verse_group=77,
            is_down=1,
            name="春风拂槛露华浓",
            npc_id=67153
        },
        {
            index=155,
            min_level=56,
            max_level=75,
            verse_group=78,
            name="但愿人长久",
            npc_id=67154
        },
        {
            index=156,
            min_level=56,
            max_level=75,
            verse_group=78,
            is_down=1,
            name="千里共婵娟",
            npc_id=67155
        },
        {
            index=157,
            min_level=56,
            max_level=75,
            verse_group=79,
            name="春蚕到死丝方尽",
            npc_id=67156
        },
        {
            index=158,
            min_level=56,
            max_level=75,
            verse_group=79,
            is_down=1,
            name="蜡炬成灰泪始干",
            npc_id=67157
        },
        {
            index=159,
            min_level=56,
            max_level=75,
            verse_group=80,
            name="身无彩凤双飞翼",
            npc_id=67158
        },
        {
            index=160,
            min_level=56,
            max_level=75,
            verse_group=80,
            is_down=1,
            name="心有灵犀一点通",
            npc_id=67159
        },
        {
            index=161,
            min_level=56,
            max_level=75,
            verse_group=81,
            name="天阶夜色凉如水",
            npc_id=67160
        },
        {
            index=162,
            min_level=56,
            max_level=75,
            verse_group=81,
            is_down=1,
            name="坐看牵牛织女星",
            npc_id=67161
        },
        {
            index=163,
            min_level=56,
            max_level=75,
            verse_group=82,
            name="愿得一心人",
            npc_id=67162
        },
        {
            index=164,
            min_level=56,
            max_level=75,
            verse_group=82,
            is_down=1,
            name="白头不相离",
            npc_id=67163
        },
        {
            index=165,
            min_level=56,
            max_level=75,
            verse_group=83,
            name="去年今日此门中",
            npc_id=67164
        },
        {
            index=166,
            min_level=56,
            max_level=75,
            verse_group=83,
            is_down=1,
            name="人面桃花相映红",
            npc_id=67165
        },
        {
            index=167,
            min_level=56,
            max_level=75,
            verse_group=84,
            name="月上柳梢头",
            npc_id=67166
        },
        {
            index=168,
            min_level=56,
            max_level=75,
            verse_group=84,
            is_down=1,
            name="人约黄昏后",
            npc_id=67167
        },
        {
            index=169,
            min_level=56,
            max_level=75,
            verse_group=85,
            name="锦瑟无端五十弦",
            npc_id=67168
        },
        {
            index=170,
            min_level=56,
            max_level=75,
            verse_group=85,
            is_down=1,
            name="一弦一柱思华年",
            npc_id=67169
        },
        {
            index=171,
            min_level=56,
            max_level=75,
            verse_group=86,
            name="停车坐爱枫林晚",
            npc_id=67170
        },
        {
            index=172,
            min_level=56,
            max_level=75,
            verse_group=86,
            is_down=1,
            name="霜叶红于二月花",
            npc_id=67171
        },
        {
            index=173,
            min_level=56,
            max_level=75,
            verse_group=87,
            name="相见时难别亦难",
            npc_id=67172
        },
        {
            index=174,
            min_level=56,
            max_level=75,
            verse_group=87,
            is_down=1,
            name="东风无力百花残",
            npc_id=67173
        },
        {
            index=175,
            min_level=56,
            max_level=75,
            verse_group=88,
            name="昨夜雨疏风骤",
            npc_id=67174
        },
        {
            index=176,
            min_level=56,
            max_level=75,
            verse_group=88,
            is_down=1,
            name="浓睡不消残酒",
            npc_id=67175
        },
        {
            index=177,
            min_level=56,
            max_level=75,
            verse_group=89,
            name="蓦然回首",
            npc_id=67176
        },
        {
            index=178,
            min_level=56,
            max_level=75,
            verse_group=89,
            is_down=1,
            name="那人却在灯火阑珊处",
            npc_id=67177
        },
        {
            index=179,
            min_level=56,
            max_level=75,
            verse_group=90,
            name="两情若是长久时",
            npc_id=67178
        },
        {
            index=180,
            min_level=56,
            max_level=75,
            verse_group=90,
            is_down=1,
            name="又岂在朝朝暮暮",
            npc_id=67179
        },
        {
            index=181,
            min_level=56,
            max_level=75,
            verse_group=91,
            name="无言独上西楼",
            npc_id=67180
        },
        {
            index=182,
            min_level=56,
            max_level=75,
            verse_group=91,
            is_down=1,
            name="月如钩",
            npc_id=67181
        },
        {
            index=183,
            min_level=56,
            max_level=75,
            verse_group=92,
            name="落花人独立",
            npc_id=67182
        },
        {
            index=184,
            min_level=56,
            max_level=75,
            verse_group=92,
            is_down=1,
            name="微雨燕双飞",
            npc_id=67183
        },
        {
            index=185,
            min_level=56,
            max_level=75,
            verse_group=93,
            name="还君明珠双泪垂",
            npc_id=67184
        },
        {
            index=186,
            min_level=56,
            max_level=75,
            verse_group=93,
            is_down=1,
            name="恨不相逢未嫁时",
            npc_id=67185
        },
        {
            index=187,
            min_level=56,
            max_level=75,
            verse_group=94,
            name="海上生明月",
            npc_id=67186
        },
        {
            index=188,
            min_level=56,
            max_level=75,
            verse_group=94,
            is_down=1,
            name="天涯共此时",
            npc_id=67187
        },
        {
            index=189,
            min_level=56,
            max_level=75,
            verse_group=95,
            name="海内存知己",
            npc_id=67188
        },
        {
            index=190,
            min_level=56,
            max_level=75,
            verse_group=95,
            is_down=1,
            name="天涯若比邻",
            npc_id=67189
        },
        {
            index=191,
            min_level=56,
            max_level=75,
            verse_group=96,
            name="回眸一笑百媚生",
            npc_id=67190
        },
        {
            index=192,
            min_level=56,
            max_level=75,
            verse_group=96,
            is_down=1,
            name="六宫粉黛无颜色",
            npc_id=67191
        },
        {
            index=193,
            min_level=56,
            max_level=75,
            verse_group=97,
            name="金风玉露一相逢",
            npc_id=67192
        },
        {
            index=194,
            min_level=56,
            max_level=75,
            verse_group=97,
            is_down=1,
            name="便胜却人间无数",
            npc_id=67193
        },
        {
            index=195,
            min_level=56,
            max_level=75,
            verse_group=98,
            name="夕阳无限好",
            npc_id=67194
        },
        {
            index=196,
            min_level=56,
            max_level=75,
            verse_group=98,
            is_down=1,
            name="只是近黄昏",
            npc_id=67195
        },
        {
            index=197,
            min_level=56,
            max_level=75,
            verse_group=99,
            name="二十四桥明月夜",
            npc_id=67196
        },
        {
            index=198,
            min_level=56,
            max_level=75,
            verse_group=99,
            is_down=1,
            name="玉人何处教吹萧",
            npc_id=67197
        },
        {
            index=199,
            min_level=56,
            max_level=75,
            verse_group=100,
            name="曾经沧海难为水",
            npc_id=67198
        },
        {
            index=200,
            min_level=56,
            max_level=75,
            verse_group=100,
            is_down=1,
            name="除却巫山不是云",
            npc_id=67199
        },
        {
            index=201,
            min_level=76,
            max_level=90,
            verse_group=101,
            npc_id=67200
        },
        {
            index=202,
            min_level=76,
            max_level=90,
            verse_group=101,
            is_down=1,
            name="铜雀春深锁二乔",
            npc_id=67201
        },
        {
            index=203,
            min_level=76,
            max_level=90,
            verse_group=102,
            name="春宵苦短日高起",
            npc_id=67202
        },
        {
            index=204,
            min_level=76,
            max_level=90,
            verse_group=102,
            is_down=1,
            name="从此君王不早朝",
            npc_id=67203
        },
        {
            index=205,
            min_level=76,
            max_level=90,
            verse_group=103,
            name="得成比目何辞死",
            npc_id=67204
        },
        {
            index=206,
            min_level=76,
            max_level=90,
            verse_group=103,
            is_down=1,
            name="愿作鸳鸯不羡仙",
            npc_id=67205
        },
        {
            index=207,
            min_level=76,
            max_level=90,
            verse_group=104,
            name="情人眼里出西施",
            npc_id=67206
        },
        {
            index=208,
            min_level=76,
            max_level=90,
            verse_group=104,
            is_down=1,
            name="色不迷人人自迷",
            npc_id=67207
        },
        {
            index=209,
            min_level=76,
            max_level=90,
            verse_group=105,
            name="洛阳亲友如相问",
            npc_id=67208
        },
        {
            index=210,
            min_level=76,
            max_level=90,
            verse_group=105,
            is_down=1,
            name="一片冰心在玉壶",
            npc_id=67209
        },
        {
            index=211,
            min_level=76,
            max_level=90,
            verse_group=106,
            name="花谢花飞飞满天",
            npc_id=67210
        },
        {
            index=212,
            min_level=76,
            max_level=90,
            verse_group=106,
            is_down=1,
            name="红消香断有谁怜",
            npc_id=67211
        },
        {
            index=213,
            min_level=76,
            max_level=90,
            verse_group=107,
            name="天生我材必有用",
            npc_id=67212
        },
        {
            index=214,
            min_level=76,
            max_level=90,
            verse_group=107,
            is_down=1,
            name="千金散尽还复来",
            npc_id=67213
        },
        {
            index=215,
            min_level=76,
            max_level=90,
            verse_group=108,
            name="在天愿做比翼鸟",
            npc_id=67214
        },
        {
            index=216,
            min_level=76,
            max_level=90,
            verse_group=108,
            is_down=1,
            name="在地愿为连理枝",
            npc_id=67215
        },
        {
            index=217,
            min_level=76,
            max_level=90,
            verse_group=109,
            name="衣带渐宽终不悔",
            npc_id=67216
        },
        {
            index=218,
            min_level=76,
            max_level=90,
            verse_group=109,
            is_down=1,
            name="为伊消得人憔悴",
            npc_id=67217
        },
        {
            index=219,
            min_level=76,
            max_level=90,
            verse_group=110,
            name="东边日出西边雨",
            npc_id=67218
        },
        {
            index=220,
            min_level=76,
            max_level=90,
            verse_group=110,
            is_down=1,
            name="道是无晴却有晴",
            npc_id=67219
        },
        {
            index=221,
            min_level=76,
            max_level=90,
            verse_group=111,
            name="枝上柳绵吹又少",
            npc_id=67220
        },
        {
            index=222,
            min_level=76,
            max_level=90,
            verse_group=111,
            is_down=1,
            name="天涯何处无芳草",
            npc_id=67221
        },
        {
            index=223,
            min_level=76,
            max_level=90,
            verse_group=112,
            name="人生得意须进欢",
            npc_id=67222
        },
        {
            index=224,
            min_level=76,
            max_level=90,
            verse_group=112,
            is_down=1,
            name="莫使金樽空对月",
            npc_id=67223
        },
        {
            index=225,
            min_level=76,
            max_level=90,
            verse_group=113,
            name="今宵酒醒何处",
            npc_id=67224
        },
        {
            index=226,
            min_level=76,
            max_level=90,
            verse_group=113,
            is_down=1,
            name="杨柳岸晓风残月",
            npc_id=67225
        },
        {
            index=227,
            min_level=76,
            max_level=90,
            verse_group=114,
            name="葡萄美酒夜光杯",
            npc_id=67226
        },
        {
            index=228,
            min_level=76,
            max_level=90,
            verse_group=114,
            is_down=1,
            name="欲饮琵琶马上催",
            npc_id=67227
        },
        {
            index=229,
            min_level=76,
            max_level=90,
            verse_group=115,
            name="所谓伊人",
            npc_id=67228
        },
        {
            index=230,
            min_level=76,
            max_level=90,
            verse_group=115,
            is_down=1,
            name="在水一方",
            npc_id=67229
        },
        {
            index=231,
            min_level=76,
            max_level=90,
            verse_group=116,
            name="结发为夫妻",
            npc_id=67230
        },
        {
            index=232,
            min_level=76,
            max_level=90,
            verse_group=116,
            is_down=1,
            name="恩爱两不疑",
            npc_id=67231
        },
        {
            index=233,
            min_level=76,
            max_level=90,
            verse_group=117,
            name="羌笛何须怨杨柳",
            npc_id=67232
        },
        {
            index=234,
            min_level=76,
            max_level=90,
            verse_group=117,
            is_down=1,
            name="春风不度玉门关",
            npc_id=67233
        },
        {
            index=235,
            min_level=76,
            max_level=90,
            verse_group=118,
            name="天涯地角有穷时",
            npc_id=67234
        },
        {
            index=236,
            min_level=76,
            max_level=90,
            verse_group=118,
            is_down=1,
            name="只有相思无尽处",
            npc_id=67235
        },
        {
            index=237,
            min_level=76,
            max_level=90,
            verse_group=119,
            name="红豆生南国",
            npc_id=67236
        },
        {
            index=238,
            min_level=76,
            max_level=90,
            verse_group=119,
            is_down=1,
            name="春来发几枝",
            npc_id=67237
        },
        {
            index=239,
            min_level=76,
            max_level=90,
            verse_group=120,
            name="愿君多采颉",
            npc_id=67238
        },
        {
            index=240,
            min_level=76,
            max_level=90,
            verse_group=120,
            is_down=1,
            name="此物最相思",
            npc_id=67239
        },
        {
            index=241,
            min_level=76,
            max_level=90,
            verse_group=121,
            name="举杯邀明月",
            npc_id=67240
        },
        {
            index=242,
            min_level=76,
            max_level=90,
            verse_group=121,
            is_down=1,
            name="对影成三人",
            npc_id=67241
        },
        {
            index=243,
            min_level=76,
            max_level=90,
            verse_group=122,
            name="问世间情为何物",
            npc_id=67242
        },
        {
            index=244,
            min_level=76,
            max_level=90,
            verse_group=122,
            is_down=1,
            name="直叫人生死相许",
            npc_id=67243
        },
        {
            index=245,
            min_level=76,
            max_level=90,
            verse_group=123,
            name="满园春色关不住",
            npc_id=67244
        },
        {
            index=246,
            min_level=76,
            max_level=90,
            verse_group=123,
            is_down=1,
            name="一支红杏出墙来",
            npc_id=67245
        },
        {
            index=247,
            min_level=76,
            max_level=90,
            verse_group=124,
            name="同是天涯沦落人",
            npc_id=67246
        },
        {
            index=248,
            min_level=76,
            max_level=90,
            verse_group=124,
            is_down=1,
            name="相逢何必曾相识",
            npc_id=67247
        },
        {
            index=249,
            min_level=76,
            max_level=90,
            verse_group=125,
            name="千呼万唤始出来",
            npc_id=67248
        },
        {
            index=250,
            min_level=76,
            max_level=90,
            verse_group=125,
            is_down=1,
            name="犹抱琵琶半遮面",
            npc_id=67249
        },
        {
            index=251,
            min_level=76,
            max_level=90,
            verse_group=126,
            name="窈窕淑女",
            npc_id=67250
        },
        {
            index=252,
            min_level=76,
            max_level=90,
            verse_group=126,
            is_down=1,
            name="君子好逑",
            npc_id=67251
        },
        {
            index=253,
            min_level=76,
            max_level=90,
            verse_group=127,
            name="云想衣裳花想容",
            npc_id=67252
        },
        {
            index=254,
            min_level=76,
            max_level=90,
            verse_group=127,
            is_down=1,
            name="春风拂槛露华浓",
            npc_id=67253
        },
        {
            index=255,
            min_level=76,
            max_level=90,
            verse_group=128,
            name="但愿人长久",
            npc_id=67254
        },
        {
            index=256,
            min_level=76,
            max_level=90,
            verse_group=128,
            is_down=1,
            name="千里共婵娟",
            npc_id=67255
        },
        {
            index=257,
            min_level=76,
            max_level=90,
            verse_group=129,
            name="春蚕到死丝方尽",
            npc_id=67256
        },
        {
            index=258,
            min_level=76,
            max_level=90,
            verse_group=129,
            is_down=1,
            name="蜡炬成灰泪始干",
            npc_id=67257
        },
        {
            index=259,
            min_level=76,
            max_level=90,
            verse_group=130,
            name="身无彩凤双飞翼",
            npc_id=67258
        },
        {
            index=260,
            min_level=76,
            max_level=90,
            verse_group=130,
            is_down=1,
            name="心有灵犀一点通",
            npc_id=67259
        },
        {
            index=261,
            min_level=76,
            max_level=90,
            verse_group=131,
            name="天阶夜色凉如水",
            npc_id=67260
        },
        {
            index=262,
            min_level=76,
            max_level=90,
            verse_group=131,
            is_down=1,
            name="坐看牵牛织女星",
            npc_id=67261
        },
        {
            index=263,
            min_level=76,
            max_level=90,
            verse_group=132,
            name="愿得一心人",
            npc_id=67262
        },
        {
            index=264,
            min_level=76,
            max_level=90,
            verse_group=132,
            is_down=1,
            name="白头不相离",
            npc_id=67263
        },
        {
            index=265,
            min_level=76,
            max_level=90,
            verse_group=133,
            name="去年今日此门中",
            npc_id=67264
        },
        {
            index=266,
            min_level=76,
            max_level=90,
            verse_group=133,
            is_down=1,
            name="人面桃花相映红",
            npc_id=67265
        },
        {
            index=267,
            min_level=76,
            max_level=90,
            verse_group=134,
            name="月上柳梢头",
            npc_id=67266
        },
        {
            index=268,
            min_level=76,
            max_level=90,
            verse_group=134,
            is_down=1,
            name="人约黄昏后",
            npc_id=67267
        },
        {
            index=269,
            min_level=76,
            max_level=90,
            verse_group=135,
            name="锦瑟无端五十弦",
            npc_id=67268
        },
        {
            index=270,
            min_level=76,
            max_level=90,
            verse_group=135,
            is_down=1,
            name="一弦一柱思华年",
            npc_id=67269
        },
        {
            index=271,
            min_level=76,
            max_level=90,
            verse_group=136,
            name="停车坐爱枫林晚",
            npc_id=67270
        },
        {
            index=272,
            min_level=76,
            max_level=90,
            verse_group=136,
            is_down=1,
            name="霜叶红于二月花",
            npc_id=67271
        },
        {
            index=273,
            min_level=76,
            max_level=90,
            verse_group=137,
            name="相见时难别亦难",
            npc_id=67272
        },
        {
            index=274,
            min_level=76,
            max_level=90,
            verse_group=137,
            is_down=1,
            name="东风无力百花残",
            npc_id=67273
        },
        {
            index=275,
            min_level=76,
            max_level=90,
            verse_group=138,
            name="昨夜雨疏风骤",
            npc_id=67274
        },
        {
            index=276,
            min_level=76,
            max_level=90,
            verse_group=138,
            is_down=1,
            name="浓睡不消残酒",
            npc_id=67275
        },
        {
            index=277,
            min_level=76,
            max_level=90,
            verse_group=139,
            name="蓦然回首",
            npc_id=67276
        },
        {
            index=278,
            min_level=76,
            max_level=90,
            verse_group=139,
            is_down=1,
            name="那人却在灯火阑珊处",
            npc_id=67277
        },
        {
            index=279,
            min_level=76,
            max_level=90,
            verse_group=140,
            name="两情若是长久时",
            npc_id=67278
        },
        {
            index=280,
            min_level=76,
            max_level=90,
            verse_group=140,
            is_down=1,
            name="又岂在朝朝暮暮",
            npc_id=67279
        },
        {
            index=281,
            min_level=76,
            max_level=90,
            verse_group=141,
            name="无言独上西楼",
            npc_id=67280
        },
        {
            index=282,
            min_level=76,
            max_level=90,
            verse_group=141,
            is_down=1,
            name="月如钩",
            npc_id=67281
        },
        {
            index=283,
            min_level=76,
            max_level=90,
            verse_group=142,
            name="落花人独立",
            npc_id=67282
        },
        {
            index=284,
            min_level=76,
            max_level=90,
            verse_group=142,
            is_down=1,
            name="微雨燕双飞",
            npc_id=67283
        },
        {
            index=285,
            min_level=76,
            max_level=90,
            verse_group=143,
            name="还君明珠双泪垂",
            npc_id=67284
        },
        {
            index=286,
            min_level=76,
            max_level=90,
            verse_group=143,
            is_down=1,
            name="恨不相逢未嫁时",
            npc_id=67285
        },
        {
            index=287,
            min_level=76,
            max_level=90,
            verse_group=144,
            name="海上生明月",
            npc_id=67286
        },
        {
            index=288,
            min_level=76,
            max_level=90,
            verse_group=144,
            is_down=1,
            name="天涯共此时",
            npc_id=67287
        },
        {
            index=289,
            min_level=76,
            max_level=90,
            verse_group=145,
            name="海内存知己",
            npc_id=67288
        },
        {
            index=290,
            min_level=76,
            max_level=90,
            verse_group=145,
            is_down=1,
            name="天涯若比邻",
            npc_id=67289
        },
        {
            index=291,
            min_level=76,
            max_level=90,
            verse_group=146,
            name="回眸一笑百媚生",
            npc_id=67290
        },
        {
            index=292,
            min_level=76,
            max_level=90,
            verse_group=146,
            is_down=1,
            name="六宫粉黛无颜色",
            npc_id=67291
        },
        {
            index=293,
            min_level=76,
            max_level=90,
            verse_group=147,
            name="金风玉露一相逢",
            npc_id=67292
        },
        {
            index=294,
            min_level=76,
            max_level=90,
            verse_group=147,
            is_down=1,
            name="便胜却人间无数",
            npc_id=67293
        },
        {
            index=295,
            min_level=76,
            max_level=90,
            verse_group=148,
            name="夕阳无限好",
            npc_id=67294
        },
        {
            index=296,
            min_level=76,
            max_level=90,
            verse_group=148,
            is_down=1,
            name="只是近黄昏",
            npc_id=67295
        },
        {
            index=297,
            min_level=76,
            max_level=90,
            verse_group=149,
            name="二十四桥明月夜",
            npc_id=67296
        },
        {
            index=298,
            min_level=76,
            max_level=90,
            verse_group=149,
            is_down=1,
            name="玉人何处教吹萧",
            npc_id=67297
        },
        {
            index=299,
            min_level=76,
            max_level=90,
            verse_group=150,
            name="曾经沧海难为水",
            npc_id=67298
        },
        {
            index=300,
            min_level=76,
            max_level=90,
            verse_group=150,
            is_down=1,
            name="除却巫山不是云",
            npc_id=67299
        },
        {
            index=301,
            min_level=91,
            max_level=120,
            verse_group=151,
            npc_id=67300
        },
        {
            index=302,
            min_level=91,
            max_level=120,
            verse_group=151,
            is_down=1,
            name="铜雀春深锁二乔",
            npc_id=67301
        },
        {
            index=303,
            min_level=91,
            max_level=120,
            verse_group=152,
            name="春宵苦短日高起",
            npc_id=67302
        },
        {
            index=304,
            min_level=91,
            max_level=120,
            verse_group=152,
            is_down=1,
            name="从此君王不早朝",
            npc_id=67303
        },
        {
            index=305,
            min_level=91,
            max_level=120,
            verse_group=153,
            name="得成比目何辞死",
            npc_id=67304
        },
        {
            index=306,
            min_level=91,
            max_level=120,
            verse_group=153,
            is_down=1,
            name="愿作鸳鸯不羡仙",
            npc_id=67305
        },
        {
            index=307,
            min_level=91,
            max_level=120,
            verse_group=154,
            name="情人眼里出西施",
            npc_id=67306
        },
        {
            index=308,
            min_level=91,
            max_level=120,
            verse_group=154,
            is_down=1,
            name="色不迷人人自迷",
            npc_id=67307
        },
        {
            index=309,
            min_level=91,
            max_level=120,
            verse_group=155,
            name="洛阳亲友如相问",
            npc_id=67308
        },
        {
            index=310,
            min_level=91,
            max_level=120,
            verse_group=155,
            is_down=1,
            name="一片冰心在玉壶",
            npc_id=67309
        },
        {
            index=311,
            min_level=91,
            max_level=120,
            verse_group=156,
            name="花谢花飞飞满天",
            npc_id=67310
        },
        {
            index=312,
            min_level=91,
            max_level=120,
            verse_group=156,
            is_down=1,
            name="红消香断有谁怜",
            npc_id=67311
        },
        {
            index=313,
            min_level=91,
            max_level=120,
            verse_group=157,
            name="天生我材必有用",
            npc_id=67312
        },
        {
            index=314,
            min_level=91,
            max_level=120,
            verse_group=157,
            is_down=1,
            name="千金散尽还复来",
            npc_id=67313
        },
        {
            index=315,
            min_level=91,
            max_level=120,
            verse_group=158,
            name="在天愿做比翼鸟",
            npc_id=67314
        },
        {
            index=316,
            min_level=91,
            max_level=120,
            verse_group=158,
            is_down=1,
            name="在地愿为连理枝",
            npc_id=67315
        },
        {
            index=317,
            min_level=91,
            max_level=120,
            verse_group=159,
            name="衣带渐宽终不悔",
            npc_id=67316
        },
        {
            index=318,
            min_level=91,
            max_level=120,
            verse_group=159,
            is_down=1,
            name="为伊消得人憔悴",
            npc_id=67317
        },
        {
            index=319,
            min_level=91,
            max_level=120,
            verse_group=160,
            name="东边日出西边雨",
            npc_id=67318
        },
        {
            index=320,
            min_level=91,
            max_level=120,
            verse_group=160,
            is_down=1,
            name="道是无晴却有晴",
            npc_id=67319
        },
        {
            index=321,
            min_level=91,
            max_level=120,
            verse_group=161,
            name="枝上柳绵吹又少",
            npc_id=67320
        },
        {
            index=322,
            min_level=91,
            max_level=120,
            verse_group=161,
            is_down=1,
            name="天涯何处无芳草",
            npc_id=67321
        },
        {
            index=323,
            min_level=91,
            max_level=120,
            verse_group=162,
            name="人生得意须进欢",
            npc_id=67322
        },
        {
            index=324,
            min_level=91,
            max_level=120,
            verse_group=162,
            is_down=1,
            name="莫使金樽空对月",
            npc_id=67323
        },
        {
            index=325,
            min_level=91,
            max_level=120,
            verse_group=163,
            name="今宵酒醒何处",
            npc_id=67324
        },
        {
            index=326,
            min_level=91,
            max_level=120,
            verse_group=163,
            is_down=1,
            name="杨柳岸晓风残月",
            npc_id=67325
        },
        {
            index=327,
            min_level=91,
            max_level=120,
            verse_group=164,
            name="葡萄美酒夜光杯",
            npc_id=67326
        },
        {
            index=328,
            min_level=91,
            max_level=120,
            verse_group=164,
            is_down=1,
            name="欲饮琵琶马上催",
            npc_id=67327
        },
        {
            index=329,
            min_level=91,
            max_level=120,
            verse_group=165,
            name="所谓伊人",
            npc_id=67328
        },
        {
            index=330,
            min_level=91,
            max_level=120,
            verse_group=165,
            is_down=1,
            name="在水一方",
            npc_id=67329
        },
        {
            index=331,
            min_level=91,
            max_level=120,
            verse_group=166,
            name="结发为夫妻",
            npc_id=67330
        },
        {
            index=332,
            min_level=91,
            max_level=120,
            verse_group=166,
            is_down=1,
            name="恩爱两不疑",
            npc_id=67331
        },
        {
            index=333,
            min_level=91,
            max_level=120,
            verse_group=167,
            name="羌笛何须怨杨柳",
            npc_id=67332
        },
        {
            index=334,
            min_level=91,
            max_level=120,
            verse_group=167,
            is_down=1,
            name="春风不度玉门关",
            npc_id=67333
        },
        {
            index=335,
            min_level=91,
            max_level=120,
            verse_group=168,
            name="天涯地角有穷时",
            npc_id=67334
        },
        {
            index=336,
            min_level=91,
            max_level=120,
            verse_group=168,
            is_down=1,
            name="只有相思无尽处",
            npc_id=67335
        },
        {
            index=337,
            min_level=91,
            max_level=120,
            verse_group=169,
            name="红豆生南国",
            npc_id=67336
        },
        {
            index=338,
            min_level=91,
            max_level=120,
            verse_group=169,
            is_down=1,
            name="春来发几枝",
            npc_id=67337
        },
        {
            index=339,
            min_level=91,
            max_level=120,
            verse_group=170,
            name="愿君多采颉",
            npc_id=67338
        },
        {
            index=340,
            min_level=91,
            max_level=120,
            verse_group=170,
            is_down=1,
            name="此物最相思",
            npc_id=67339
        },
        {
            index=341,
            min_level=91,
            max_level=120,
            verse_group=171,
            name="举杯邀明月",
            npc_id=67340
        },
        {
            index=342,
            min_level=91,
            max_level=120,
            verse_group=171,
            is_down=1,
            name="对影成三人",
            npc_id=67341
        },
        {
            index=343,
            min_level=91,
            max_level=120,
            verse_group=172,
            name="问世间情为何物",
            npc_id=67342
        },
        {
            index=344,
            min_level=91,
            max_level=120,
            verse_group=172,
            is_down=1,
            name="直叫人生死相许",
            npc_id=67343
        },
        {
            index=345,
            min_level=91,
            max_level=120,
            verse_group=173,
            name="满园春色关不住",
            npc_id=67344
        },
        {
            index=346,
            min_level=91,
            max_level=120,
            verse_group=173,
            is_down=1,
            name="一支红杏出墙来",
            npc_id=67345
        },
        {
            index=347,
            min_level=91,
            max_level=120,
            verse_group=174,
            name="同是天涯沦落人",
            npc_id=67346
        },
        {
            index=348,
            min_level=91,
            max_level=120,
            verse_group=174,
            is_down=1,
            name="相逢何必曾相识",
            npc_id=67347
        },
        {
            index=349,
            min_level=91,
            max_level=120,
            verse_group=175,
            name="千呼万唤始出来",
            npc_id=67348
        },
        {
            index=350,
            min_level=91,
            max_level=120,
            verse_group=175,
            is_down=1,
            name="犹抱琵琶半遮面",
            npc_id=67349
        },
        {
            index=351,
            min_level=91,
            max_level=120,
            verse_group=176,
            name="窈窕淑女",
            npc_id=67350
        },
        {
            index=352,
            min_level=91,
            max_level=120,
            verse_group=176,
            is_down=1,
            name="君子好逑",
            npc_id=67351
        },
        {
            index=353,
            min_level=91,
            max_level=120,
            verse_group=177,
            name="云想衣裳花想容",
            npc_id=67352
        },
        {
            index=354,
            min_level=91,
            max_level=120,
            verse_group=177,
            is_down=1,
            name="春风拂槛露华浓",
            npc_id=67353
        },
        {
            index=355,
            min_level=91,
            max_level=120,
            verse_group=178,
            name="但愿人长久",
            npc_id=67354
        },
        {
            index=356,
            min_level=91,
            max_level=120,
            verse_group=178,
            is_down=1,
            name="千里共婵娟",
            npc_id=67355
        },
        {
            index=357,
            min_level=91,
            max_level=120,
            verse_group=179,
            name="春蚕到死丝方尽",
            npc_id=67356
        },
        {
            index=358,
            min_level=91,
            max_level=120,
            verse_group=179,
            is_down=1,
            name="蜡炬成灰泪始干",
            npc_id=67357
        },
        {
            index=359,
            min_level=91,
            max_level=120,
            verse_group=180,
            name="身无彩凤双飞翼",
            npc_id=67358
        },
        {
            index=360,
            min_level=91,
            max_level=120,
            verse_group=180,
            is_down=1,
            name="心有灵犀一点通",
            npc_id=67359
        },
        {
            index=361,
            min_level=91,
            max_level=120,
            verse_group=181,
            name="天阶夜色凉如水",
            npc_id=67360
        },
        {
            index=362,
            min_level=91,
            max_level=120,
            verse_group=181,
            is_down=1,
            name="坐看牵牛织女星",
            npc_id=67361
        },
        {
            index=363,
            min_level=91,
            max_level=120,
            verse_group=182,
            name="愿得一心人",
            npc_id=67362
        },
        {
            index=364,
            min_level=91,
            max_level=120,
            verse_group=182,
            is_down=1,
            name="白头不相离",
            npc_id=67363
        },
        {
            index=365,
            min_level=91,
            max_level=120,
            verse_group=183,
            name="去年今日此门中",
            npc_id=67364
        },
        {
            index=366,
            min_level=91,
            max_level=120,
            verse_group=183,
            is_down=1,
            name="人面桃花相映红",
            npc_id=67365
        },
        {
            index=367,
            min_level=91,
            max_level=120,
            verse_group=184,
            name="月上柳梢头",
            npc_id=67366
        },
        {
            index=368,
            min_level=91,
            max_level=120,
            verse_group=184,
            is_down=1,
            name="人约黄昏后",
            npc_id=67367
        },
        {
            index=369,
            min_level=91,
            max_level=120,
            verse_group=185,
            name="锦瑟无端五十弦",
            npc_id=67368
        },
        {
            index=370,
            min_level=91,
            max_level=120,
            verse_group=185,
            is_down=1,
            name="一弦一柱思华年",
            npc_id=67369
        },
        {
            index=371,
            min_level=91,
            max_level=120,
            verse_group=186,
            name="停车坐爱枫林晚",
            npc_id=67370
        },
        {
            index=372,
            min_level=91,
            max_level=120,
            verse_group=186,
            is_down=1,
            name="霜叶红于二月花",
            npc_id=67371
        },
        {
            index=373,
            min_level=91,
            max_level=120,
            verse_group=187,
            name="相见时难别亦难",
            npc_id=67372
        },
        {
            index=374,
            min_level=91,
            max_level=120,
            verse_group=187,
            is_down=1,
            name="东风无力百花残",
            npc_id=67373
        },
        {
            index=375,
            min_level=91,
            max_level=120,
            verse_group=188,
            name="昨夜雨疏风骤",
            npc_id=67374
        },
        {
            index=376,
            min_level=91,
            max_level=120,
            verse_group=188,
            is_down=1,
            name="浓睡不消残酒",
            npc_id=67375
        },
        {
            index=377,
            min_level=91,
            max_level=120,
            verse_group=189,
            name="蓦然回首",
            npc_id=67376
        },
        {
            index=378,
            min_level=91,
            max_level=120,
            verse_group=189,
            is_down=1,
            name="那人却在灯火阑珊处",
            npc_id=67377
        },
        {
            index=379,
            min_level=91,
            max_level=120,
            verse_group=190,
            name="两情若是长久时",
            npc_id=67378
        },
        {
            index=380,
            min_level=91,
            max_level=120,
            verse_group=190,
            is_down=1,
            name="又岂在朝朝暮暮",
            npc_id=67379
        },
        {
            index=381,
            min_level=91,
            max_level=120,
            verse_group=191,
            name="无言独上西楼",
            npc_id=67380
        },
        {
            index=382,
            min_level=91,
            max_level=120,
            verse_group=191,
            is_down=1,
            name="月如钩",
            npc_id=67381
        },
        {
            index=383,
            min_level=91,
            max_level=120,
            verse_group=192,
            name="落花人独立",
            npc_id=67382
        },
        {
            index=384,
            min_level=91,
            max_level=120,
            verse_group=192,
            is_down=1,
            name="微雨燕双飞",
            npc_id=67383
        },
        {
            index=385,
            min_level=91,
            max_level=120,
            verse_group=193,
            name="还君明珠双泪垂",
            npc_id=67384
        },
        {
            index=386,
            min_level=91,
            max_level=120,
            verse_group=193,
            is_down=1,
            name="恨不相逢未嫁时",
            npc_id=67385
        },
        {
            index=387,
            min_level=91,
            max_level=120,
            verse_group=194,
            name="海上生明月",
            npc_id=67386
        },
        {
            index=388,
            min_level=91,
            max_level=120,
            verse_group=194,
            is_down=1,
            name="天涯共此时",
            npc_id=67387
        },
        {
            index=389,
            min_level=91,
            max_level=120,
            verse_group=195,
            name="海内存知己",
            npc_id=67388
        },
        {
            index=390,
            min_level=91,
            max_level=120,
            verse_group=195,
            is_down=1,
            name="天涯若比邻",
            npc_id=67389
        },
        {
            index=391,
            min_level=91,
            max_level=120,
            verse_group=196,
            name="回眸一笑百媚生",
            npc_id=67390
        },
        {
            index=392,
            min_level=91,
            max_level=120,
            verse_group=196,
            is_down=1,
            name="六宫粉黛无颜色",
            npc_id=67391
        },
        {
            index=393,
            min_level=91,
            max_level=120,
            verse_group=197,
            name="金风玉露一相逢",
            npc_id=67392
        },
        {
            index=394,
            min_level=91,
            max_level=120,
            verse_group=197,
            is_down=1,
            name="便胜却人间无数",
            npc_id=67393
        },
        {
            index=395,
            min_level=91,
            max_level=120,
            verse_group=198,
            name="夕阳无限好",
            npc_id=67394
        },
        {
            index=396,
            min_level=91,
            max_level=120,
            verse_group=198,
            is_down=1,
            name="只是近黄昏",
            npc_id=67395
        },
        {
            index=397,
            min_level=91,
            max_level=120,
            verse_group=199,
            name="二十四桥明月夜",
            npc_id=67396
        },
        {
            index=398,
            min_level=91,
            max_level=120,
            verse_group=199,
            is_down=1,
            name="玉人何处教吹萧",
            npc_id=67397
        },
        {
            index=399,
            min_level=91,
            max_level=120,
            verse_group=200,
            name="曾经沧海难为水",
            npc_id=67398
        },
        {
            index=400,
            min_level=91,
            max_level=120,
            verse_group=200,
            is_down=1,
            name="除却巫山不是云",
            npc_id=67399
        }
    },
    mentor_fb_reward={
        {
            stage=0,
            master_coin=0,
            master_chivalrous=0,
            apprentice_coin=0
        },
        {
            stage=1,
            master_reward={
                [0]=_itemlist.i_31327_1_1
            },
            master_coin=5000,
            master_chivalrous=30,
            apprentice_reward={
                [0]=_itemlist.i_31327_1_1
            },
            apprentice_coin=5000
        },
        {
            stage=2,
            master_reward={
                [0]=_itemlist.i_31327_1_1
            },
            master_coin=8000,
            master_chivalrous=60,
            apprentice_reward={
                [0]=_itemlist.i_31327_1_1
            },
            apprentice_coin=6000
        },
        {
            stage=3,
            master_reward={
                [0]=_itemlist.i_31327_1_1
            },
            master_coin=10000,
            master_chivalrous=90,
            apprentice_reward={
                [0]=_itemlist.i_31327_1_1
            },
            apprentice_coin=7000
        },
        {
            stage=4,
            master_reward={
                [0]=_itemlist.i_31327_1_1
            },
            master_coin=11000,
            master_chivalrous=120,
            apprentice_reward={
                [0]=_itemlist.i_31327_1_1
            },
            apprentice_coin=8000
        },
        {
            stage=5,
            master_reward={
                [0]=_itemlist.i_31327_1_1
            },
            master_coin=12000,
            master_chivalrous=150,
            apprentice_reward={
                [0]=_itemlist.i_31327_1_1
            },
            apprentice_coin=9000
        },
        {
            stage=6,
            master_reward={
                [0]=_itemlist.i_31328_1_1
            },
            master_coin=13000,
            master_chivalrous=180,
            apprentice_reward={
                [0]=_itemlist.i_31328_1_1
            },
            apprentice_coin=10000
        },
        {
            stage=7,
            master_reward={
                [0]=_itemlist.i_31328_1_1
            },
            master_coin=14000,
            master_chivalrous=210,
            apprentice_reward={
                [0]=_itemlist.i_31328_1_1
            },
            apprentice_coin=11000
        },
        {
            stage=8,
            master_reward={
                [0]=_itemlist.i_31328_1_1
            },
            master_coin=15000,
            master_chivalrous=240,
            apprentice_reward={
                [0]=_itemlist.i_31328_1_1
            },
            apprentice_coin=12000
        },
        {
            stage=9,
            master_reward={
                [0]=_itemlist.i_31328_1_1
            },
            master_coin=16000,
            master_chivalrous=270,
            apprentice_reward={
                [0]=_itemlist.i_31328_1_1
            },
            apprentice_coin=13000
        },
        {
            stage=10,
            master_reward={
                [0]=_itemlist.i_31329_1_1
            },
            master_coin=17000,
            master_chivalrous=300,
            apprentice_reward={
                [0]=_itemlist.i_31329_1_1
            },
            apprentice_coin=14000
        },
        {
            stage=11,
            master_reward={
                [0]=_itemlist.i_31329_1_1
            },
            master_coin=18000,
            master_chivalrous=330,
            apprentice_reward={
                [0]=_itemlist.i_31329_1_1
            },
            apprentice_coin=15000
        },
        {
            stage=12,
            master_reward={
                [0]=_itemlist.i_31329_1_1
            },
            master_coin=20000,
            master_chivalrous=360,
            apprentice_reward={
                [0]=_itemlist.i_31329_1_1
            },
            apprentice_coin=16000
        }
    },
    milepost={
        {
            seq=0,
            param=2500,
            name="沉淀·壹",
            master_reward={
                [0]=_itemlist.i_31300_2_1
            },
            apprentice_reward={
                [0]=_itemlist.i_31304_2_1
            }
        },
        {
            seq=1,
            param=3000,
            order=1,
            name="沉淀·贰",
            master_reward={
                [0]=_itemlist.i_31300_3_1
            },
            apprentice_reward={
                [0]=_itemlist.i_31304_3_1
            }
        },
        {
            seq=2,
            param=4000,
            order=2,
            name="沉淀·叁",
            master_reward={
                [0]=_itemlist.i_31300_3_1,
                [1]=_itemlist.i_24518_1_1
            },
            apprentice_reward={
                [0]=_itemlist.i_31304_3_1,
                [1]=_itemlist.i_24518_1_1
            }
        },
        {
            seq=3,
            param=5000,
            order=3,
            name="沉淀·肆",
            master_reward={
                [0]=_itemlist.i_31300_4_1,
                [1]=_itemlist.i_24518_1_1
            },
            apprentice_reward={
                [0]=_itemlist.i_31304_4_1,
                [1]=_itemlist.i_24518_1_1
            }
        },
        {
            seq=4,
            param=6000,
            order=4,
            name="沉淀·伍",
            master_reward={
                [0]=_itemlist.i_31301_4_1,
                [1]=_itemlist.i_24518_1_1
            },
            apprentice_reward={
                [0]=_itemlist.i_31311_4_1,
                [1]=_itemlist.i_24518_1_1
            }
        },
        {
            seq=5,
            param=7500,
            order=5,
            name="沉淀·陆",
            master_reward={
                [0]=_itemlist.i_31301_5_1,
                [1]=_itemlist.i_31321_1_1
            },
            apprentice_reward={
                [0]=_itemlist.i_31311_5_1,
                [1]=_itemlist.i_31321_1_1
            }
        },
        {
            seq=6,
            type=2,
            param=3,
            name="羁绊·壹",
            master_reward={
                [0]=_itemlist.i_31300_2_1
            },
            apprentice_reward={
                [0]=_itemlist.i_31304_2_1
            }
        },
        {
            seq=7,
            type=2,
            param=5,
            order=1,
            name="羁绊·贰",
            master_reward={
                [0]=_itemlist.i_31300_3_1
            },
            apprentice_reward={
                [0]=_itemlist.i_31304_3_1
            }
        },
        {
            seq=8,
            type=2,
            param=7,
            order=2,
            name="羁绊·叁",
            master_reward={
                [0]=_itemlist.i_31300_3_1,
                [1]=_itemlist.i_24518_1_1
            },
            apprentice_reward={
                [0]=_itemlist.i_31304_3_1,
                [1]=_itemlist.i_24518_1_1
            }
        },
        {
            seq=9,
            type=2,
            param=10,
            order=3,
            name="羁绊·肆",
            master_reward={
                [0]=_itemlist.i_31300_4_1,
                [1]=_itemlist.i_24518_1_1
            },
            apprentice_reward={
                [0]=_itemlist.i_31304_4_1,
                [1]=_itemlist.i_24518_1_1
            }
        },
        {
            seq=10,
            type=2,
            param=15,
            order=4,
            name="羁绊·伍",
            master_reward={
                [0]=_itemlist.i_31301_4_1,
                [1]=_itemlist.i_24518_1_1
            },
            apprentice_reward={
                [0]=_itemlist.i_31311_4_1,
                [1]=_itemlist.i_24518_1_1
            }
        },
        {
            seq=11,
            type=2,
            param=20,
            order=5,
            name="羁绊·陆",
            master_reward={
                [0]=_itemlist.i_31301_5_1,
                [1]=_itemlist.i_31321_1_1
            },
            apprentice_reward={
                [0]=_itemlist.i_31311_5_1,
                [1]=_itemlist.i_31321_1_1
            }
        },
        {
            seq=12,
            param=8500,
            order=6,
            name="沉淀·柒",
            master_reward={
                [0]=_itemlist.i_31301_6_1,
                [1]=_itemlist.i_31321_1_1
            },
            apprentice_reward={
                [0]=_itemlist.i_31311_6_1,
                [1]=_itemlist.i_31321_1_1
            }
        },
        {
            seq=13,
            param=10000,
            order=7,
            name="沉淀·捌",
            master_reward={
                [0]=_itemlist.i_31301_6_1,
                [1]=_itemlist.i_31321_1_1
            },
            apprentice_reward={
                [0]=_itemlist.i_31311_6_1,
                [1]=_itemlist.i_31321_1_1
            }
        },
        {
            seq=14,
            type=2,
            param=25,
            order=6,
            name="羁绊·柒",
            master_reward={
                [0]=_itemlist.i_31301_6_1,
                [1]=_itemlist.i_31321_1_1
            },
            apprentice_reward={
                [0]=_itemlist.i_31311_6_1,
                [1]=_itemlist.i_31321_1_1
            }
        },
        {
            seq=15,
            type=2,
            param=30,
            order=7,
            name="羁绊·捌",
            master_reward={
                [0]=_itemlist.i_31301_6_1,
                [1]=_itemlist.i_31321_1_1
            },
            apprentice_reward={
                [0]=_itemlist.i_31311_6_1,
                [1]=_itemlist.i_31321_1_1
            }
        }
    },
    Passmerit_exp={
        {
            level=1,
            reward_exp=0
        },
        {
            level=2,
            reward_exp=0
        },
        {
            level=3,
            reward_exp=0
        },
        {
            level=4,
            reward_exp=0
        },
        {
            level=5,
            reward_exp=0
        },
        {
            level=6,
            reward_exp=0
        },
        {
            level=7,
            reward_exp=0
        },
        {
            level=8,
            reward_exp=0
        },
        {
            level=9,
            reward_exp=0
        },
        {
            level=10,
            reward_exp=0
        },
        {
            level=11,
            reward_exp=0
        },
        {
            level=12,
            reward_exp=0
        },
        {
            level=13,
            reward_exp=0
        },
        {
            level=14,
            reward_exp=0
        },
        {
            level=15,
            reward_exp=0
        },
        {
            level=16,
            reward_exp=0
        },
        {
            level=17,
            reward_exp=0
        },
        {
            level=18,
            reward_exp=0
        },
        {
            level=19,
            reward_exp=0
        },
        {
            level=20,
            reward_exp=0
        },
        {
            level=21,
            reward_exp=0
        },
        {
            level=22,
            reward_exp=0
        },
        {
            level=23,
            reward_exp=0
        },
        {
            level=24,
            reward_exp=0
        },
        {
            level=25,
            reward_exp=0
        },
        {
            level=26,
            reward_exp=0
        },
        {
            level=27,
            reward_exp=0
        },
        {
            level=28,
            reward_exp=0
        },
        {
            level=29,
            reward_exp=0
        },
        {
            level=30
        },
        {
            level=31
        },
        {
            level=32
        },
        {
            level=33
        },
        {
            level=34
        },
        {
            level=35
        },
        {
            level=36
        },
        {
            level=37
        },
        {
            level=38
        },
        {
            level=39
        },
        {
            level=40
        },
        {
            level=41
        },
        {
            level=42
        },
        {
            level=43
        },
        {
            level=44
        },
        {
            level=45
        },
        {
            level=46
        },
        {
            level=47
        },
        {
            level=48
        },
        {
            level=49
        },
        {
            level=50
        },
        {
            level=51
        },
        {
            level=52
        },
        {
            level=53
        },
        {
            level=54
        },
        {
            level=55
        },
        {
            level=56
        },
        {
            level=57
        },
        {
            level=58
        },
        {
            level=59
        },
        {
            level=60
        },
        {
            level=61
        },
        {
            level=62
        },
        {
            level=63
        },
        {
            level=64
        },
        {
            level=65,
            reward_exp=77113
        },
        {
            level=66,
            reward_exp=77113
        },
        {
            level=67,
            reward_exp=77113
        },
        {
            level=68,
            reward_exp=77113
        },
        {
            level=69,
            reward_exp=77113
        },
        {
            level=70,
            reward_exp=77113
        },
        {
            level=71,
            reward_exp=77113
        },
        {
            level=72,
            reward_exp=100179
        },
        {
            level=73,
            reward_exp=100179
        },
        {
            level=74,
            reward_exp=100179
        },
        {
            level=75,
            reward_exp=100179
        },
        {
            level=76,
            reward_exp=100179
        },
        {
            level=77,
            reward_exp=100179
        },
        {
            level=78,
            reward_exp=174179
        },
        {
            level=79,
            reward_exp=174179
        },
        {
            level=80,
            reward_exp=174179
        },
        {
            level=81,
            reward_exp=174179
        },
        {
            level=82,
            reward_exp=207179
        },
        {
            level=83,
            reward_exp=207179
        },
        {
            level=84,
            reward_exp=207179
        },
        {
            level=85,
            reward_exp=207179
        },
        {
            level=86,
            reward_exp=259179
        },
        {
            level=87,
            reward_exp=259179
        },
        {
            level=88,
            reward_exp=259179
        },
        {
            level=89,
            reward_exp=286179
        },
        {
            level=90,
            reward_exp=286179
        },
        {
            level=91,
            reward_exp=286179
        },
        {
            level=92,
            reward_exp=325179
        },
        {
            level=93,
            reward_exp=325179
        },
        {
            level=94,
            reward_exp=325179
        },
        {
            level=95,
            reward_exp=325179
        },
        {
            level=96,
            reward_exp=391180
        },
        {
            level=97,
            reward_exp=391180
        },
        {
            level=98,
            reward_exp=409180
        },
        {
            level=99,
            reward_exp=409180
        },
        {
            level=100,
            reward_exp=409180
        },
        {
            level=101,
            reward_exp=473180
        },
        {
            level=102,
            reward_exp=473180
        },
        {
            level=103,
            reward_exp=483180
        },
        {
            level=104,
            reward_exp=483180
        },
        {
            level=105,
            reward_exp=483180
        },
        {
            level=106,
            reward_exp=533180
        },
        {
            level=107,
            reward_exp=533180
        },
        {
            level=108,
            reward_exp=563180
        },
        {
            level=109,
            reward_exp=563180
        },
        {
            level=110,
            reward_exp=588180
        },
        {
            level=111,
            reward_exp=588180
        },
        {
            level=112,
            reward_exp=593180
        },
        {
            level=113,
            reward_exp=593180
        },
        {
            level=114,
            reward_exp=608180
        },
        {
            level=115,
            reward_exp=608180
        },
        {
            level=116,
            reward_exp=668180
        },
        {
            level=117,
            reward_exp=668180
        },
        {
            level=118,
            reward_exp=688180
        },
        {
            level=119,
            reward_exp=688180
        },
        {
            level=120,
            reward_exp=708181
        }
    },
    game_reward={
        {
            grade=0,
            name="无",
            score=0
        },
        {
            grade=1,
            name="一星",
            score=3280,
            master_reward={
                [0]=_itemlist.i_27398_1_1
            },
            apprentice_reward={
                [0]=_itemlist.i_27398_1_1
            }
        },
        {
            grade=2,
            name="二星",
            score=6560,
            master_reward={
                [0]=_itemlist.i_28555_1_1
            },
            apprentice_reward={
                [0]=_itemlist.i_28555_1_1
            }
        },
        {
            grade=3,
            name="三星",
            score=9840,
            master_reward={
                [0]=_itemlist.i_31302_1_1
            },
            apprentice_reward={
                [0]=_itemlist.i_31302_1_1
            }
        },
        {
            grade=4,
            name="四星",
            score=13120,
            master_reward={
                [0]=_itemlist.i_27399_1_1
            },
            apprentice_reward={
                [0]=_itemlist.i_27399_1_1
            }
        },
        {
            grade=5,
            name="五星",
            score=16400,
            master_reward={
                [0]=_itemlist.i_31303_1_1
            },
            apprentice_reward={
                [0]=_itemlist.i_31303_1_1
            }
        }
    },
    introduce={
        {
            fun_id=0,
            fun_name="里程碑",
            desc_seq=288,
            master_reward="65850:31321",
            apprentice_reward="65850:31321"
        },
        {
            fun_id=1,
            fun_name="天书传道",
            desc_seq=289,
            master_reward="65850:24518",
            apprentice_reward="65850:24518"
        },
        {
            fun_id=2,
            fun_name="师徒传功",
            desc_seq=290,
            master_reward="65850:65851",
            apprentice_reward="65850:65851"
        }
    }
}
SetConfigDefaultVal(Config.mentor_cfg_auto,_default_val,nil,nil,nil)