Config.millennium_peach_blossom_auto={
    initial={
        {
            seq=1,
            point=1,
            initial_number=4,
            correct_number=1
        },
        {
            seq=2,
            point=2,
            initial_number=1,
            correct_number=2
        },
        {
            seq=3,
            point=3,
            initial_number=2,
            correct_number=3
        },
        {
            seq=4,
            point=4,
            initial_number=3,
            correct_number=4
        }
    },
    poetry_number={
        {
            poetry_number=1,
            poetry_word="彩袖殷勤捧玉钟"
        },
        {
            poetry_number=2,
            poetry_word="当年拚却醉颜红"
        },
        {
            poetry_number=3,
            poetry_word="舞低杨柳楼心月"
        },
        {
            poetry_number=4,
            poetry_word="歌尽桃花扇底风"
        }
    },
    other={
        {
            special_task_id=65370,
            last_task_id=65372,
            npc_id=66302,
            special_bubble=137,
            special_talk=8600,
            fail_talk=8604,
            restart_talk=8603
        }
    }
}