local _default_val={
    lattice={
        type=0,
        group=1,
        word_7="，"
    },
    word_group={
        group=1,
        seq=1,
        word="万"
    }
}
Config.pack_poetry_auto={
    lattice={
        {
            seq=1,
            word_0="黄",
            word_1="河",
            word_2="远",
            word_3="上",
            word_4=10,
            word_5=5,
            word_6="间",
            word_8="一",
            word_9="片",
            word_10=2,
            word_11=16,
            word_12="万",
            word_13="仞",
            word_14="山"
        },
        {
            seq=2,
            type=1,
            word_0="羌",
            word_1="笛",
            word_2=7,
            word_3=15,
            word_4="怨",
            word_5="杨",
            word_6="柳",
            word_8="春",
            word_9="风",
            word_10="不",
            word_11="度",
            word_12=3,
            word_13=9,
            word_14=12
        },
        {
            seq=3,
            group=2,
            word_0=4,
            word_1=15,
            word_2="宅",
            word_3="里",
            word_4="寻",
            word_5="常",
            word_6="见",
            word_8=3,
            word_9=6,
            word_10=9,
            word_11=12,
            word_12="几",
            word_13="度",
            word_14="闻"
        },
        {
            seq=4,
            type=1,
            group=2,
            word_0="正",
            word_1="是",
            word_2="江",
            word_3="南",
            word_4=1,
            word_5=16,
            word_6=18,
            word_8="落",
            word_9="花",
            word_10="时",
            word_11="节",
            word_12=17,
            word_13=10,
            word_14=7
        },
        {
            seq=5,
            group=3,
            word_0="崆",
            word_1="峒",
            word_2="访",
            word_3="道",
            word_4="至",
            word_5=9,
            word_6=4,
            word_8=13,
            word_9=7,
            word_10=16,
            word_11=6,
            word_12="看",
            word_13="转",
            word_14="愚"
        },
        {
            seq=6,
            type=1,
            group=3,
            word_0=12,
            word_1=14,
            word_2=8,
            word_3=2,
            word_4=18,
            word_5=15,
            word_6=3,
            word_8="得",
            word_9="来",
            word_10="全",
            word_11="不",
            word_12="费",
            word_13="工",
            word_14="夫"
        }
    },
    word_group={
        {
            word="思"
        },
        {
            seq=2,
            word="孤"
        },
        {
            seq=3,
            word="玉"
        },
        {
            seq=4,
            word="及"
        },
        {
            seq=5,
            word="云"
        },
        {
            seq=6,
            word="他"
        },
        {
            seq=7,
            word="何"
        },
        {
            seq=8,
            word="真"
        },
        {
            seq=9,
            word="门"
        },
        {
            seq=10,
            word="白"
        },
        {
            seq=11,
            word="之"
        },
        {
            seq=12,
            word="关"
        },
        {
            seq=13
        },
        {
            seq=14,
            word="是"
        },
        {
            seq=15,
            word="须"
        },
        {
            seq=16,
            word="城"
        },
        {
            seq=17,
            word="需"
        },
        {
            seq=18,
            word="也"
        },
        {
            group=2,
            word="好"
        },
        {
            group=2,
            seq=2,
            word="祁"
        },
        {
            group=2,
            seq=3,
            word="崔"
        },
        {
            group=2,
            seq=4,
            word="岐"
        },
        {
            group=2,
            seq=5,
            word="催"
        },
        {
            group=2,
            seq=6,
            word="九"
        },
        {
            group=2,
            seq=7,
            word="君"
        },
        {
            group=2,
            seq=8,
            word="光"
        },
        {
            group=2,
            seq=9,
            word="堂"
        },
        {
            group=2,
            seq=10,
            word="逢"
        },
        {
            group=2,
            seq=11,
            word="恰"
        },
        {
            group=2,
            seq=12,
            word="前"
        },
        {
            group=2,
            seq=13,
            word="遇"
        },
        {
            group=2,
            seq=14,
            word="再"
        },
        {
            group=2,
            seq=15,
            word="王"
        },
        {
            group=2,
            seq=16,
            word="风"
        },
        {
            group=2,
            seq=17,
            word="又"
        },
        {
            group=2,
            seq=18,
            word="景"
        },
        {
            group=3,
            word="竹"
        },
        {
            group=3,
            seq=2,
            word="鞋"
        },
        {
            group=3,
            seq=3,
            word="处"
        },
        {
            group=3,
            seq=4,
            word="湖"
        },
        {
            group=3,
            seq=5,
            word="靴"
        },
        {
            group=3,
            seq=6,
            word="书"
        },
        {
            group=3,
            seq=7,
            word="卷"
        },
        {
            group=3,
            seq=8,
            word="铁"
        },
        {
            group=3,
            seq=9,
            word="湘"
        },
        {
            group=3,
            seq=10,
            word="寻"
        },
        {
            group=3,
            seq=11,
            word="笔"
        },
        {
            group=3,
            seq=12,
            word="踏"
        },
        {
            group=3,
            seq=13
        },
        {
            group=3,
            seq=14,
            word="破"
        },
        {
            group=3,
            seq=15,
            word="觅"
        },
        {
            group=3,
            seq=16,
            word="诗"
        },
        {
            group=3,
            seq=17,
            word="画"
        },
        {
            group=3,
            seq=18,
            word="无"
        }
    },
    other={
        {
            special_task_id=65230,
            last_task_id=65232,
            subject_talk_2=72318,
            subject_talk_3=72319,
            restart_talk=72317,
            fail_talk=72321,
            npc_id=589,
            special_bubble=130,
            group=3
        }
    }
}
SetConfigDefaultVal(Config.pack_poetry_auto,_default_val,nil,nil,nil)