Config.poetry_sort_two_auto={
    initial={
        {
            seq=1,
            point=1,
            initial_number=3,
            correct_number=1
        },
        {
            seq=2,
            point=2,
            initial_number=2,
            correct_number=2
        },
        {
            seq=3,
            point=3,
            initial_number=4,
            correct_number=3
        },
        {
            seq=4,
            point=4,
            initial_number=1,
            correct_number=4
        }
    },
    poetry_number={
        {
            poetry_number=1,
            poetry_word="大漠沙如雪"
        },
        {
            poetry_number=2,
            poetry_word="燕山月似钩"
        },
        {
            poetry_number=3,
            poetry_word="何当金络脑"
        },
        {
            poetry_number=4,
            poetry_word="快走踏青秋"
        }
    },
    other={
        {
            show_time=5,
            fail_talk=72193,
            special_task_id=65450,
            last_task_id=65452,
            npc_id=59160,
            special_bubble=126,
            special_talk=72190,
            restart_talk=72194
        }
    }
}