local _default_val={
    basis_configuration={
        section_start=1,
        section_end=3,
        seq=0,
        activity_days=1,
        buy_limit=1,
        limit_times=3,
        price=6480,
        gift_name="钟情三生礼盒"
    },
    reward_group={
        seq=0,
        reward_group=1
    },
    show_reward_item={
        section_start=1,
        section_end=3,
        seq=0,
        activity_days=1,
        show_rate="55%"
    },
    phase_reward={
        section_start=1,
        section_end=0,
        total_buy_times=9
    }
}
local _itemlist={
    i_29513_1_1={
        item_id=29513,
        num=1,
        is_bind=1
    },
    i_29514_1_1={
        item_id=29514,
        num=1,
        is_bind=1
    },
    i_29508_1_1={
        item_id=29508,
        num=1,
        is_bind=1
    },
    i_29515_1_1={
        item_id=29515,
        num=1,
        is_bind=1
    },
    i_29516_1_1={
        item_id=29516,
        num=1,
        is_bind=1
    },
    i_29517_1_1={
        item_id=29517,
        num=1,
        is_bind=1
    },
    i_29518_1_1={
        item_id=29518,
        num=1,
        is_bind=1
    },
    i_29509_1_1={
        item_id=29509,
        num=1,
        is_bind=1
    },
    i_29510_1_1={
        item_id=29510,
        num=1,
        is_bind=1
    },
    i_29511_1_1={
        item_id=29511,
        num=1,
        is_bind=1
    },
    i_29512_1_1={
        item_id=29512,
        num=1,
        is_bind=1
    },
    i_64671_1_1={
        item_id=64671,
        num=1,
        is_bind=1
    },
    i_31529_1_1={
        item_id=31529,
        num=1,
        is_bind=1
    },
    i_64672_1_1={
        item_id=64672,
        num=1,
        is_bind=1
    },
    i_64670_1_1={
        item_id=64670,
        num=1,
        is_bind=1
    },
    i_64673_1_1={
        item_id=64673,
        num=1,
        is_bind=1
    }
}
Config.qiqiaotehui_auto={
    basis_configuration={
        {
            type=0,
            reward_group=1,
            desc="限时情人礼，购买必得<color=#ff3e3e>1314520灵玉</color>，额外概率获得<color=#fe35be>钟情神兽礼</color>、<color=#fe35be>钟情魂器礼</color>、<color=#fe35be>钟情偃甲礼</color>！"
        },
        {
            type=1,
            seq=1,
            activity_days=2,
            reward_group=2,
            price=3280,
            gift_name="钟情三世礼盒",
            desc="限时情人礼，购买必得<color=#ff3e3e>1314520灵玉</color>，额外概率获得<color=#fe35be>钟情灵粹礼</color>、<color=#fe35be>钟情神魂礼</color>、<color=#fe35be>钟情偃甲礼</color>！"
        },
        {
            type=2,
            seq=2,
            activity_days=3,
            reward_group=3,
            price=4880,
            gift_name="钟情桃花礼盒",
            desc="限时情人礼，购买必得<color=#ff3e3e>1314520灵玉</color>，额外概率获得<color=#fe35be>钟情护符礼</color>、<color=#fe35be>钟情灵技礼</color>、<color=#fe35be>钟情偃甲礼</color>！"
        },
        {
            type=3,
            section_start=4,
            section_end=8,
            reward_group=4,
            desc="限时情人礼，购买必得<color=#ff3e3e>1314520灵玉</color>，额外概率获得<color=#fe35be>钟情神兽礼</color>、<color=#fe35be>钟情魂器礼</color>、<color=#fe35be>钟情祥云礼</color>！"
        },
        {
            type=4,
            section_start=4,
            section_end=8,
            seq=1,
            activity_days=2,
            reward_group=5,
            price=3280,
            gift_name="钟情三世礼盒",
            desc="限时情人礼，购买必得<color=#ff3e3e>1314520灵玉</color>，额外概率获得<color=#fe35be>钟情灵粹礼</color>、<color=#fe35be>钟情神魂礼</color>、<color=#fe35be>钟情祥云礼</color>！"
        },
        {
            type=5,
            section_start=4,
            section_end=8,
            seq=2,
            activity_days=3,
            reward_group=6,
            price=4880,
            gift_name="钟情桃花礼盒",
            desc="限时情人礼，购买必得<color=#ff3e3e>1314520灵玉</color>，额外概率获得<color=#fe35be>钟情护符礼</color>、<color=#fe35be>钟情灵技礼</color>、<color=#fe35be>钟情祥云礼</color>！"
        },
        {
            type=6,
            section_start=9,
            section_end=14,
            reward_group=7,
            desc="限时情人礼，购买必得<color=#ff3e3e>1314520灵玉</color>，额外概率获得<color=#fe35be>钟情神兽礼</color>、<color=#fe35be>钟情魂器礼</color>、<color=#fe35be>钟情庚金礼</color>！"
        },
        {
            type=7,
            section_start=9,
            section_end=14,
            seq=1,
            activity_days=2,
            reward_group=8,
            price=3280,
            gift_name="钟情三世礼盒",
            desc="限时情人礼，购买必得<color=#ff3e3e>1314520灵玉</color>，额外概率获得<color=#fe35be>钟情灵粹礼</color>、<color=#fe35be>钟情神魂礼</color>、<color=#fe35be>钟情庚金礼</color>！"
        },
        {
            type=8,
            section_start=9,
            section_end=14,
            seq=2,
            activity_days=3,
            reward_group=9,
            price=4880,
            gift_name="钟情桃花礼盒",
            desc="限时情人礼，购买必得<color=#ff3e3e>1314520灵玉</color>，额外概率获得<color=#fe35be>钟情护符礼</color>、<color=#fe35be>钟情灵技礼</color>、<color=#fe35be>钟情庚金礼</color>！"
        },
        {
            type=9,
            section_start=15,
            section_end=21,
            reward_group=10,
            desc="限时情人礼，购买必得<color=#ff3e3e>1314520灵玉</color>，额外概率获得<color=#fe35be>钟情神兽礼</color>、<color=#fe35be>钟情魂器礼</color>、<color=#fe35be>钟情玄水礼</color>！"
        },
        {
            type=10,
            section_start=15,
            section_end=21,
            seq=1,
            activity_days=2,
            reward_group=11,
            price=3280,
            gift_name="钟情三世礼盒",
            desc="限时情人礼，购买必得<color=#ff3e3e>1314520灵玉</color>，额外概率获得<color=#fe35be>钟情灵粹礼</color>、<color=#fe35be>钟情神魂礼</color>、<color=#fe35be>钟情玄水礼</color>！"
        },
        {
            type=11,
            section_start=15,
            section_end=21,
            seq=2,
            activity_days=3,
            reward_group=12,
            price=4880,
            gift_name="钟情桃花礼盒",
            desc="限时情人礼，购买必得<color=#ff3e3e>1314520灵玉</color>，额外概率获得<color=#fe35be>钟情护符礼</color>、<color=#fe35be>钟情灵技礼</color>、<color=#fe35be>钟情玄水礼</color>！"
        },
        {
            type=12,
            section_start=22,
            section_end=0,
            reward_group=13,
            desc="限时情人礼，购买必得<color=#ff3e3e>1314520灵玉</color>，额外概率获得<color=#fe35be>钟情神兽礼</color>、<color=#fe35be>钟情魂器礼</color>、<color=#fe35be>钟情麒麟礼</color>！"
        },
        {
            type=13,
            section_start=22,
            section_end=0,
            seq=1,
            activity_days=2,
            reward_group=14,
            price=3280,
            gift_name="钟情三世礼盒",
            desc="限时情人礼，购买必得<color=#ff3e3e>1314520灵玉</color>，额外概率获得<color=#fe35be>钟情灵粹礼</color>、<color=#fe35be>钟情神魂礼</color>、<color=#fe35be>钟情麒麟礼</color>！"
        },
        {
            type=14,
            section_start=22,
            section_end=0,
            seq=2,
            activity_days=3,
            reward_group=15,
            price=4880,
            gift_name="钟情桃花礼盒",
            desc="限时情人礼，购买必得<color=#ff3e3e>1314520灵玉</color>，额外概率获得<color=#fe35be>钟情护符礼</color>、<color=#fe35be>钟情灵技礼</color>、<color=#fe35be>钟情麒麟礼</color>！"
        }
    },
    reward_group={
        {
            reward_item={
                [0]=_itemlist.i_29513_1_1
            }
        },
        {
            seq=1,
            reward_item={
                [0]=_itemlist.i_29514_1_1
            }
        },
        {
            seq=2,
            reward_item={
                [0]=_itemlist.i_29508_1_1
            }
        },
        {
            reward_group=2,
            reward_item={
                [0]=_itemlist.i_29515_1_1
            }
        },
        {
            seq=1,
            reward_group=2,
            reward_item={
                [0]=_itemlist.i_29516_1_1
            }
        },
        {
            seq=2,
            reward_group=2,
            reward_item={
                [0]=_itemlist.i_29508_1_1
            }
        },
        {
            reward_group=3,
            reward_item={
                [0]=_itemlist.i_29517_1_1
            }
        },
        {
            seq=1,
            reward_group=3,
            reward_item={
                [0]=_itemlist.i_29518_1_1
            }
        },
        {
            seq=2,
            reward_group=3,
            reward_item={
                [0]=_itemlist.i_29508_1_1
            }
        },
        {
            reward_group=4,
            reward_item={
                [0]=_itemlist.i_29513_1_1
            }
        },
        {
            seq=1,
            reward_group=4,
            reward_item={
                [0]=_itemlist.i_29514_1_1
            }
        },
        {
            seq=2,
            reward_group=4,
            reward_item={
                [0]=_itemlist.i_29509_1_1
            }
        },
        {
            reward_group=5,
            reward_item={
                [0]=_itemlist.i_29515_1_1
            }
        },
        {
            seq=1,
            reward_group=5,
            reward_item={
                [0]=_itemlist.i_29516_1_1
            }
        },
        {
            seq=2,
            reward_group=5,
            reward_item={
                [0]=_itemlist.i_29509_1_1
            }
        },
        {
            reward_group=6,
            reward_item={
                [0]=_itemlist.i_29517_1_1
            }
        },
        {
            seq=1,
            reward_group=6,
            reward_item={
                [0]=_itemlist.i_29518_1_1
            }
        },
        {
            seq=2,
            reward_group=6,
            reward_item={
                [0]=_itemlist.i_29509_1_1
            }
        },
        {
            reward_group=7,
            reward_item={
                [0]=_itemlist.i_29513_1_1
            }
        },
        {
            seq=1,
            reward_group=7,
            reward_item={
                [0]=_itemlist.i_29514_1_1
            }
        },
        {
            seq=2,
            reward_group=7,
            reward_item={
                [0]=_itemlist.i_29510_1_1
            }
        },
        {
            reward_group=8,
            reward_item={
                [0]=_itemlist.i_29515_1_1
            }
        },
        {
            seq=1,
            reward_group=8,
            reward_item={
                [0]=_itemlist.i_29516_1_1
            }
        },
        {
            seq=2,
            reward_group=8,
            reward_item={
                [0]=_itemlist.i_29510_1_1
            }
        },
        {
            reward_group=9,
            reward_item={
                [0]=_itemlist.i_29517_1_1
            }
        },
        {
            seq=1,
            reward_group=9,
            reward_item={
                [0]=_itemlist.i_29518_1_1
            }
        },
        {
            seq=2,
            reward_group=9,
            reward_item={
                [0]=_itemlist.i_29510_1_1
            }
        },
        {
            reward_group=10,
            reward_item={
                [0]=_itemlist.i_29513_1_1
            }
        },
        {
            seq=1,
            reward_group=10,
            reward_item={
                [0]=_itemlist.i_29514_1_1
            }
        },
        {
            seq=2,
            reward_group=10,
            reward_item={
                [0]=_itemlist.i_29511_1_1
            }
        },
        {
            reward_group=11,
            reward_item={
                [0]=_itemlist.i_29515_1_1
            }
        },
        {
            seq=1,
            reward_group=11,
            reward_item={
                [0]=_itemlist.i_29516_1_1
            }
        },
        {
            seq=2,
            reward_group=11,
            reward_item={
                [0]=_itemlist.i_29511_1_1
            }
        },
        {
            reward_group=12,
            reward_item={
                [0]=_itemlist.i_29517_1_1
            }
        },
        {
            seq=1,
            reward_group=12,
            reward_item={
                [0]=_itemlist.i_29518_1_1
            }
        },
        {
            seq=2,
            reward_group=12,
            reward_item={
                [0]=_itemlist.i_29511_1_1
            }
        },
        {
            reward_group=13,
            reward_item={
                [0]=_itemlist.i_29513_1_1
            }
        },
        {
            seq=1,
            reward_group=13,
            reward_item={
                [0]=_itemlist.i_29514_1_1
            }
        },
        {
            seq=2,
            reward_group=13,
            reward_item={
                [0]=_itemlist.i_29512_1_1
            }
        },
        {
            reward_group=14,
            reward_item={
                [0]=_itemlist.i_29515_1_1
            }
        },
        {
            seq=1,
            reward_group=14,
            reward_item={
                [0]=_itemlist.i_29516_1_1
            }
        },
        {
            seq=2,
            reward_group=14,
            reward_item={
                [0]=_itemlist.i_29512_1_1
            }
        },
        {
            reward_group=15,
            reward_item={
                [0]=_itemlist.i_29517_1_1
            }
        },
        {
            seq=1,
            reward_group=15,
            reward_item={
                [0]=_itemlist.i_29518_1_1
            }
        },
        {
            seq=2,
            reward_group=15,
            reward_item={
                [0]=_itemlist.i_29512_1_1
            }
        }
    },
    show_reward_item={
        {
            type=0,
            show_item=_itemlist.i_29513_1_1
        },
        {
            type=1,
            seq=1,
            show_item=_itemlist.i_29514_1_1,
            show_rate="40%"
        },
        {
            type=2,
            seq=2,
            show_item=_itemlist.i_29508_1_1,
            show_rate="5%"
        },
        {
            type=3,
            activity_days=2,
            show_item=_itemlist.i_29515_1_1
        },
        {
            type=4,
            seq=1,
            activity_days=2,
            show_item=_itemlist.i_29516_1_1,
            show_rate="40%"
        },
        {
            type=5,
            seq=2,
            activity_days=2,
            show_item=_itemlist.i_29508_1_1,
            show_rate="5%"
        },
        {
            type=6,
            activity_days=3,
            show_item=_itemlist.i_29517_1_1
        },
        {
            type=7,
            seq=1,
            activity_days=3,
            show_item=_itemlist.i_29518_1_1,
            show_rate="40%"
        },
        {
            type=8,
            seq=2,
            activity_days=3,
            show_item=_itemlist.i_29508_1_1,
            show_rate="5%"
        },
        {
            type=9,
            section_start=4,
            section_end=8,
            show_item=_itemlist.i_29513_1_1
        },
        {
            type=10,
            section_start=4,
            section_end=8,
            seq=1,
            show_item=_itemlist.i_29514_1_1,
            show_rate="40%"
        },
        {
            type=11,
            section_start=4,
            section_end=8,
            seq=2,
            show_item=_itemlist.i_29509_1_1,
            show_rate="5%"
        },
        {
            type=12,
            section_start=4,
            section_end=8,
            activity_days=2,
            show_item=_itemlist.i_29515_1_1
        },
        {
            type=13,
            section_start=4,
            section_end=8,
            seq=1,
            activity_days=2,
            show_item=_itemlist.i_29516_1_1,
            show_rate="40%"
        },
        {
            type=14,
            section_start=4,
            section_end=8,
            seq=2,
            activity_days=2,
            show_item=_itemlist.i_29509_1_1,
            show_rate="5%"
        },
        {
            type=15,
            section_start=4,
            section_end=8,
            activity_days=3,
            show_item=_itemlist.i_29517_1_1
        },
        {
            type=16,
            section_start=4,
            section_end=8,
            seq=1,
            activity_days=3,
            show_item=_itemlist.i_29518_1_1,
            show_rate="40%"
        },
        {
            type=17,
            section_start=4,
            section_end=8,
            seq=2,
            activity_days=3,
            show_item=_itemlist.i_29509_1_1,
            show_rate="5%"
        },
        {
            type=18,
            section_start=9,
            section_end=14,
            show_item=_itemlist.i_29513_1_1
        },
        {
            type=19,
            section_start=9,
            section_end=14,
            seq=1,
            show_item=_itemlist.i_29514_1_1,
            show_rate="40%"
        },
        {
            type=20,
            section_start=9,
            section_end=14,
            seq=2,
            show_item=_itemlist.i_29510_1_1,
            show_rate="5%"
        },
        {
            type=21,
            section_start=9,
            section_end=14,
            activity_days=2,
            show_item=_itemlist.i_29515_1_1
        },
        {
            type=22,
            section_start=9,
            section_end=14,
            seq=1,
            activity_days=2,
            show_item=_itemlist.i_29516_1_1,
            show_rate="40%"
        },
        {
            type=23,
            section_start=9,
            section_end=14,
            seq=2,
            activity_days=2,
            show_item=_itemlist.i_29510_1_1,
            show_rate="5%"
        },
        {
            type=24,
            section_start=9,
            section_end=14,
            activity_days=3,
            show_item=_itemlist.i_29517_1_1
        },
        {
            type=25,
            section_start=9,
            section_end=14,
            seq=1,
            activity_days=3,
            show_item=_itemlist.i_29518_1_1,
            show_rate="40%"
        },
        {
            type=26,
            section_start=9,
            section_end=14,
            seq=2,
            activity_days=3,
            show_item=_itemlist.i_29510_1_1,
            show_rate="5%"
        },
        {
            type=27,
            section_start=15,
            section_end=21,
            show_item=_itemlist.i_29513_1_1
        },
        {
            type=28,
            section_start=15,
            section_end=21,
            seq=1,
            show_item=_itemlist.i_29514_1_1,
            show_rate="40%"
        },
        {
            type=29,
            section_start=15,
            section_end=21,
            seq=2,
            show_item=_itemlist.i_29511_1_1,
            show_rate="5%"
        },
        {
            type=30,
            section_start=15,
            section_end=21,
            activity_days=2,
            show_item=_itemlist.i_29515_1_1
        },
        {
            type=31,
            section_start=15,
            section_end=21,
            seq=1,
            activity_days=2,
            show_item=_itemlist.i_29516_1_1,
            show_rate="40%"
        },
        {
            type=32,
            section_start=15,
            section_end=21,
            seq=2,
            activity_days=2,
            show_item=_itemlist.i_29511_1_1,
            show_rate="5%"
        },
        {
            type=33,
            section_start=15,
            section_end=21,
            activity_days=3,
            show_item=_itemlist.i_29517_1_1
        },
        {
            type=34,
            section_start=15,
            section_end=21,
            seq=1,
            activity_days=3,
            show_item=_itemlist.i_29518_1_1,
            show_rate="40%"
        },
        {
            type=35,
            section_start=15,
            section_end=21,
            seq=2,
            activity_days=3,
            show_item=_itemlist.i_29511_1_1,
            show_rate="5%"
        },
        {
            type=36,
            section_start=22,
            section_end=0,
            show_item=_itemlist.i_29513_1_1
        },
        {
            type=37,
            section_start=22,
            section_end=0,
            seq=1,
            show_item=_itemlist.i_29514_1_1,
            show_rate="40%"
        },
        {
            type=38,
            section_start=22,
            section_end=0,
            seq=2,
            show_item=_itemlist.i_29512_1_1,
            show_rate="5%"
        },
        {
            type=39,
            section_start=22,
            section_end=0,
            activity_days=2,
            show_item=_itemlist.i_29515_1_1
        },
        {
            type=40,
            section_start=22,
            section_end=0,
            seq=1,
            activity_days=2,
            show_item=_itemlist.i_29516_1_1,
            show_rate="40%"
        },
        {
            type=41,
            section_start=22,
            section_end=0,
            seq=2,
            activity_days=2,
            show_item=_itemlist.i_29512_1_1,
            show_rate="5%"
        },
        {
            type=42,
            section_start=22,
            section_end=0,
            activity_days=3,
            show_item=_itemlist.i_29517_1_1
        },
        {
            type=43,
            section_start=22,
            section_end=0,
            seq=1,
            activity_days=3,
            show_item=_itemlist.i_29518_1_1,
            show_rate="40%"
        },
        {
            type=44,
            section_start=22,
            section_end=0,
            seq=2,
            activity_days=3,
            show_item=_itemlist.i_29512_1_1,
            show_rate="5%"
        }
    },
    phase_reward={
        {
            type=0,
            seq=0,
            buy_times=1,
            reward_item=_itemlist.i_64671_1_1
        },
        {
            type=1,
            seq=1,
            buy_times=3,
            reward_item=_itemlist.i_31529_1_1
        },
        {
            type=2,
            seq=2,
            buy_times=5,
            reward_item=_itemlist.i_64672_1_1
        },
        {
            type=3,
            seq=3,
            buy_times=7,
            reward_item=_itemlist.i_64670_1_1
        },
        {
            type=4,
            seq=4,
            buy_times=9,
            reward_item=_itemlist.i_64673_1_1
        }
    },
    other={
        {
            cfg_ver=4
        }
    }
}
SetConfigDefaultVal(Config.qiqiaotehui_auto,_default_val,nil,nil,nil)