local _default_val={
    shilian_attributes={
        seq=2,
        stuff_id=27853,
        stuff_num=1,
        type_jobs=1,
        sub_type=1,
        attr_min=1,
        attr_max=1,
        attr_type=6,
        attr_val=1
    },
    feisheng_attributes={
        hp_buff=0
    },
    skill_up={
        role_level=90,
        consume=1,
        item_id=27870
    },
    feisheng_task={
        stag=1,
        is_shilian=1,
        rate=166
    },
    task_reward={
        feisheng_stage=1,
        is_shilian=1,
        task_num=1,
        reward_group=3
    },
    reward_group={
        rate=10000
    },
    last_reward={
        feisheng_stage=1,
        is_shilian=1
    },
    anger_soul={
        type=0,
        level=0,
        item_id=56629,
        num=1,
        att_type_1=6,
        attr_value_1=0,
        att_type_2=2,
        attr_value_2=0,
        sp_id=0
    }
}
local _itemlist={
    i_27852_3_1={
        item_id=27852,
        num=3,
        is_bind=1
    },
    i_27852_4_1={
        item_id=27852,
        num=4,
        is_bind=1
    },
    i_27870_2_1={
        item_id=27870,
        num=2,
        is_bind=1
    },
    i_27850_1_1={
        item_id=27850,
        num=1,
        is_bind=1
    },
    i_27853_6_1={
        item_id=27853,
        num=6,
        is_bind=1
    },
    i_27853_8_1={
        item_id=27853,
        num=8,
        is_bind=1
    },
    i_22014_2_1={
        item_id=22014,
        num=2,
        is_bind=1
    },
    i_27852_6_1={
        item_id=27852,
        num=6,
        is_bind=1
    },
    i_27852_40_1={
        item_id=27852,
        num=40,
        is_bind=1
    },
    i_27870_4_1={
        item_id=27870,
        num=4,
        is_bind=1
    },
    i_27870_20_1={
        item_id=27870,
        num=20,
        is_bind=1
    },
    i_27850_3_1={
        item_id=27850,
        num=3,
        is_bind=1
    },
    i_27853_10_1={
        item_id=27853,
        num=10,
        is_bind=1
    },
    i_27853_84_1={
        item_id=27853,
        num=84,
        is_bind=1
    },
    i_27870_6_1={
        item_id=27870,
        num=6,
        is_bind=1
    },
    i_27850_4_1={
        item_id=27850,
        num=4,
        is_bind=1
    }
}
Config.role_feisheng_auto={
    other={
        {
            level_limit1=90,
            level_limit2=110,
            score_limit1=30000,
            score_limit2=42000,
            use_limit_up=5,
            feishengtasklist_id=60420,
            feishengtasklist_id2=60425,
            check_feishengtask=60421,
            feisheng_title1=163,
            feisheng_title2=164,
            max_exp1=30,
            max_exp2=50,
            jineng_cost=27870,
            add_exp=50,
            shilian_cost1=27852,
            cost1=1,
            shilian_cost2=27853,
            cost2=1,
            sunring_npc=73326
        }
    },
    shilian_attributes={
        {
            seq=1,
            stuff_id=27852,
            attr_val=33
        },
        {
            seq=1,
            stuff_id=27852,
            sub_type=2,
            attr_type=2
        },
        {
            seq=1,
            stuff_id=27852,
            sub_type=3,
            attr_type=1,
            attr_val=3
        },
        {
            seq=1,
            stuff_id=27852,
            sub_type=4,
            attr_type=0,
            attr_val=3
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=2,
            attr_val=33
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=2,
            sub_type=2,
            attr_type=2
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=2,
            sub_type=3,
            attr_type=1,
            attr_val=3
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=2,
            sub_type=4,
            attr_type=0,
            attr_val=3
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=3,
            attr_val=33
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=3,
            sub_type=2,
            attr_type=2
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=3,
            sub_type=3,
            attr_type=1,
            attr_val=3
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=3,
            sub_type=4,
            attr_type=0,
            attr_val=3
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=4,
            attr_val=33
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=4,
            sub_type=2,
            attr_type=2
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=4,
            sub_type=3,
            attr_type=1,
            attr_val=3
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=4,
            sub_type=4,
            attr_type=0,
            attr_val=3
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=5,
            attr_val=33
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=5,
            sub_type=2,
            attr_type=2
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=5,
            sub_type=3,
            attr_type=1,
            attr_val=3
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=5,
            sub_type=4,
            attr_type=0,
            attr_val=3
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=6,
            attr_val=33
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=6,
            sub_type=2,
            attr_type=2
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=6,
            sub_type=3,
            attr_type=1,
            attr_val=3
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=6,
            sub_type=4,
            attr_type=4,
            attr_val=2
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=7,
            attr_val=33
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=7,
            sub_type=2,
            attr_type=2
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=7,
            sub_type=3,
            attr_type=1,
            attr_val=3
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=7,
            sub_type=4,
            attr_type=3
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=8,
            attr_val=33
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=8,
            sub_type=2,
            attr_type=2
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=8,
            sub_type=3,
            attr_type=1,
            attr_val=3
        },
        {
            seq=1,
            stuff_id=27852,
            type_jobs=8,
            sub_type=4,
            attr_type=3
        },
        {
            attr_type=45,
            attr_val=2
        },
        {
            sub_type=2,
            attr_type=48,
            attr_val=2
        },
        {
            sub_type=3,
            attr_type=46,
            attr_val=3
        },
        {
            sub_type=4,
            attr_type=47
        },
        {
            sub_type=5,
            attr_type=49
        },
        {
            type_jobs=2,
            attr_type=45,
            attr_val=2
        },
        {
            type_jobs=2,
            sub_type=2,
            attr_type=48,
            attr_val=2
        },
        {
            type_jobs=2,
            sub_type=3,
            attr_type=46,
            attr_val=3
        },
        {
            type_jobs=2,
            sub_type=4,
            attr_type=47
        },
        {
            type_jobs=2,
            sub_type=5,
            attr_type=49
        },
        {
            type_jobs=3,
            attr_type=45,
            attr_val=2
        },
        {
            type_jobs=3,
            sub_type=2,
            attr_type=48,
            attr_val=2
        },
        {
            type_jobs=3,
            sub_type=3,
            attr_type=46,
            attr_val=3
        },
        {
            type_jobs=3,
            sub_type=4,
            attr_type=47
        },
        {
            type_jobs=3,
            sub_type=5,
            attr_type=49
        },
        {
            type_jobs=4,
            attr_type=45,
            attr_val=2
        },
        {
            type_jobs=4,
            sub_type=2,
            attr_type=48
        },
        {
            type_jobs=4,
            sub_type=3,
            attr_type=46,
            attr_val=2
        },
        {
            type_jobs=4,
            sub_type=4,
            attr_type=47,
            attr_val=3
        },
        {
            type_jobs=4,
            sub_type=5,
            attr_type=49
        },
        {
            type_jobs=5,
            attr_type=45,
            attr_val=2
        },
        {
            type_jobs=5,
            sub_type=2,
            attr_type=48,
            attr_val=2
        },
        {
            type_jobs=5,
            sub_type=3,
            attr_type=46,
            attr_val=3
        },
        {
            type_jobs=5,
            sub_type=4,
            attr_type=47
        },
        {
            type_jobs=5,
            sub_type=5,
            attr_type=49
        },
        {
            type_jobs=6,
            attr_type=45
        },
        {
            type_jobs=6,
            sub_type=2,
            attr_type=48,
            attr_val=2
        },
        {
            type_jobs=6,
            sub_type=3,
            attr_type=46
        },
        {
            type_jobs=6,
            sub_type=4,
            attr_type=47,
            attr_val=2
        },
        {
            type_jobs=6,
            sub_type=5,
            attr_type=49,
            attr_val=3
        },
        {
            type_jobs=7,
            attr_type=45,
            attr_val=3
        },
        {
            type_jobs=7,
            sub_type=2,
            attr_type=48,
            attr_val=2
        },
        {
            type_jobs=7,
            sub_type=3,
            attr_type=46
        },
        {
            type_jobs=7,
            sub_type=4,
            attr_type=47
        },
        {
            type_jobs=7,
            sub_type=5,
            attr_type=49,
            attr_val=2
        },
        {
            type_jobs=8,
            attr_type=45,
            attr_val=3
        },
        {
            type_jobs=8,
            sub_type=2,
            attr_type=48,
            attr_val=2
        },
        {
            type_jobs=8,
            sub_type=3,
            attr_type=46
        },
        {
            type_jobs=8,
            sub_type=4,
            attr_type=47
        },
        {
            type_jobs=8,
            sub_type=5,
            attr_type=49,
            attr_val=2
        }
    },
    feisheng_attributes={
        {
            shilian_type=1,
            maxhp=200,
            maxmp=17,
            gongji=20,
            fangyu=20,
            minjie=5,
            jingshen=10,
            huifu=8
        },
        {
            shilian_type=2,
            maxhp=500,
            maxmp=43,
            gongji=50,
            fangyu=50,
            minjie=13,
            jingshen=25,
            huifu=20
        }
    },
    skill_lock={
        {
            type_jobs=1,
            ascension_skills=3030
        },
        {
            type_jobs=2,
            ascension_skills=584
        },
        {
            type_jobs=3,
            ascension_skills=585
        },
        {
            type_jobs=4,
            ascension_skills=3031
        },
        {
            type_jobs=5,
            ascension_skills=1508
        },
        {
            type_jobs=6,
            ascension_skills=3032
        },
        {
            type_jobs=7,
            ascension_skills=3033
        },
        {
            type_jobs=8,
            ascension_skills=3034
        }
    },
    skill_up={
        {
            skill_level=1,
            need_exp=0
        },
        {
            skill_level=2,
            need_exp=4000
        },
        {
            skill_level=3,
            role_level=94,
            need_exp=10000
        },
        {
            skill_level=4,
            role_level=98,
            need_exp=12000
        },
        {
            skill_level=5,
            role_level=102,
            need_exp=16000
        },
        {
            skill_level=6,
            role_level=106,
            need_exp=20000
        },
        {
            skill_level=7,
            role_level=110,
            need_exp=24000
        },
        {
            skill_level=8,
            role_level=114,
            need_exp=32000
        },
        {
            skill_level=9,
            role_level=117,
            need_exp=40000
        },
        {
            skill_level=10,
            role_level=120,
            need_exp=50000
        }
    },
    feisheng_task={
        {
            stag=0,
            task_id=45000
        },
        {
            stag=0,
            task_id=45001
        },
        {
            stag=0,
            task_id=45002
        },
        {
            stag=0,
            task_id=45003
        },
        {
            stag=0,
            task_id=45004
        },
        {
            stag=0,
            task_id=45005
        },
        {
            stag=0,
            task_id=45006
        },
        {
            stag=0,
            task_id=45007
        },
        {
            stag=0,
            task_id=45008
        },
        {
            stag=0,
            task_id=45009
        },
        {
            stag=0,
            task_id=45010
        },
        {
            stag=0,
            task_id=45011
        },
        {
            stag=0,
            task_id=45012
        },
        {
            stag=0,
            task_id=45013
        },
        {
            stag=0,
            task_id=45014
        },
        {
            stag=0,
            task_id=45015
        },
        {
            stag=0,
            task_id=45016
        },
        {
            stag=0,
            task_id=45017
        },
        {
            stag=0,
            task_id=45018
        },
        {
            stag=0,
            task_id=45019
        },
        {
            stag=0,
            task_id=45020
        },
        {
            stag=0,
            task_id=45021
        },
        {
            stag=0,
            task_id=45022
        },
        {
            stag=0,
            task_id=45023
        },
        {
            stag=0,
            task_id=45024
        },
        {
            stag=0,
            task_id=45025
        },
        {
            stag=0,
            task_id=45026
        },
        {
            stag=0,
            task_id=45027
        },
        {
            stag=0,
            task_id=45028
        },
        {
            stag=0,
            task_id=45029
        },
        {
            stag=0,
            task_id=45030
        },
        {
            stag=0,
            task_id=45031
        },
        {
            stag=0,
            task_id=45032
        },
        {
            stag=0,
            task_id=45033
        },
        {
            stag=0,
            task_id=45034
        },
        {
            stag=0,
            task_id=45035
        },
        {
            stag=0,
            task_id=45036
        },
        {
            stag=0,
            task_id=45037
        },
        {
            stag=0,
            task_id=45038
        },
        {
            stag=0,
            task_id=45039
        },
        {
            stag=0,
            task_id=45040
        },
        {
            stag=0,
            task_id=45041
        },
        {
            stag=0,
            task_id=45042
        },
        {
            stag=0,
            task_id=45043
        },
        {
            stag=0,
            task_id=45044
        },
        {
            stag=0,
            task_id=45045
        },
        {
            stag=0,
            task_id=45046
        },
        {
            stag=0,
            task_id=45047
        },
        {
            stag=0,
            task_id=45048
        },
        {
            stag=0,
            task_id=45049
        },
        {
            stag=0,
            task_id=45050
        },
        {
            stag=0,
            task_id=45051
        },
        {
            stag=0,
            task_id=45052
        },
        {
            stag=0,
            task_id=45053
        },
        {
            stag=0,
            task_id=45054
        },
        {
            stag=0,
            task_id=45055
        },
        {
            stag=0,
            task_id=45056
        },
        {
            stag=0,
            task_id=45057
        },
        {
            stag=0,
            task_id=45058
        },
        {
            stag=0,
            task_id=45059,
            rate=206
        },
        {
            is_shilian=0,
            task_id=45060
        },
        {
            is_shilian=0,
            task_id=45061
        },
        {
            is_shilian=0,
            task_id=45062
        },
        {
            is_shilian=0,
            task_id=45063
        },
        {
            is_shilian=0,
            task_id=45064
        },
        {
            is_shilian=0,
            task_id=45065
        },
        {
            is_shilian=0,
            task_id=45066
        },
        {
            is_shilian=0,
            task_id=45067
        },
        {
            is_shilian=0,
            task_id=45068
        },
        {
            is_shilian=0,
            task_id=45069
        },
        {
            is_shilian=0,
            task_id=45070
        },
        {
            is_shilian=0,
            task_id=45071
        },
        {
            is_shilian=0,
            task_id=45072
        },
        {
            is_shilian=0,
            task_id=45073
        },
        {
            is_shilian=0,
            task_id=45074
        },
        {
            is_shilian=0,
            task_id=45075
        },
        {
            is_shilian=0,
            task_id=45076
        },
        {
            is_shilian=0,
            task_id=45077
        },
        {
            is_shilian=0,
            task_id=45078
        },
        {
            is_shilian=0,
            task_id=45079
        },
        {
            is_shilian=0,
            task_id=45080
        },
        {
            is_shilian=0,
            task_id=45081
        },
        {
            is_shilian=0,
            task_id=45082
        },
        {
            is_shilian=0,
            task_id=45083
        },
        {
            is_shilian=0,
            task_id=45084
        },
        {
            is_shilian=0,
            task_id=45085
        },
        {
            is_shilian=0,
            task_id=45086
        },
        {
            is_shilian=0,
            task_id=45087
        },
        {
            is_shilian=0,
            task_id=45088
        },
        {
            is_shilian=0,
            task_id=45089
        },
        {
            is_shilian=0,
            task_id=45090
        },
        {
            is_shilian=0,
            task_id=45091
        },
        {
            is_shilian=0,
            task_id=45092
        },
        {
            is_shilian=0,
            task_id=45093
        },
        {
            is_shilian=0,
            task_id=45094
        },
        {
            is_shilian=0,
            task_id=45095
        },
        {
            is_shilian=0,
            task_id=45096
        },
        {
            is_shilian=0,
            task_id=45097
        },
        {
            is_shilian=0,
            task_id=45098
        },
        {
            is_shilian=0,
            task_id=45099
        },
        {
            is_shilian=0,
            task_id=45100
        },
        {
            is_shilian=0,
            task_id=45101
        },
        {
            is_shilian=0,
            task_id=45102
        },
        {
            is_shilian=0,
            task_id=45103
        },
        {
            is_shilian=0,
            task_id=45104
        },
        {
            is_shilian=0,
            task_id=45105
        },
        {
            is_shilian=0,
            task_id=45106
        },
        {
            is_shilian=0,
            task_id=45107
        },
        {
            is_shilian=0,
            task_id=45108
        },
        {
            is_shilian=0,
            task_id=45109
        },
        {
            is_shilian=0,
            task_id=45110
        },
        {
            is_shilian=0,
            task_id=45111
        },
        {
            is_shilian=0,
            task_id=45112
        },
        {
            is_shilian=0,
            task_id=45113
        },
        {
            is_shilian=0,
            task_id=45114
        },
        {
            is_shilian=0,
            task_id=45115
        },
        {
            is_shilian=0,
            task_id=45116
        },
        {
            is_shilian=0,
            task_id=45117
        },
        {
            is_shilian=0,
            task_id=45118
        },
        {
            is_shilian=0,
            task_id=45119,
            rate=206
        },
        {
            task_id=45120
        },
        {
            task_id=45121
        },
        {
            task_id=45122
        },
        {
            task_id=45123
        },
        {
            task_id=45124
        },
        {
            task_id=45125
        },
        {
            task_id=45126
        },
        {
            task_id=45127
        },
        {
            task_id=45128
        },
        {
            task_id=45129
        },
        {
            task_id=45130
        },
        {
            task_id=45131
        },
        {
            task_id=45132
        },
        {
            task_id=45133
        },
        {
            task_id=45134
        },
        {
            task_id=45135
        },
        {
            task_id=45136
        },
        {
            task_id=45137
        },
        {
            task_id=45138
        },
        {
            task_id=45139
        },
        {
            task_id=45140
        },
        {
            task_id=45141
        },
        {
            task_id=45142
        },
        {
            task_id=45143
        },
        {
            task_id=45144
        },
        {
            task_id=45145
        },
        {
            task_id=45146
        },
        {
            task_id=45147
        },
        {
            task_id=45148
        },
        {
            task_id=45149
        },
        {
            task_id=45150
        },
        {
            task_id=45151
        },
        {
            task_id=45152
        },
        {
            task_id=45153
        },
        {
            task_id=45154
        },
        {
            task_id=45155
        },
        {
            task_id=45156
        },
        {
            task_id=45157
        },
        {
            task_id=45158
        },
        {
            task_id=45159
        },
        {
            task_id=45160
        },
        {
            task_id=45161
        },
        {
            task_id=45162
        },
        {
            task_id=45163
        },
        {
            task_id=45164
        },
        {
            task_id=45165
        },
        {
            task_id=45166
        },
        {
            task_id=45167
        },
        {
            task_id=45168
        },
        {
            task_id=45169
        },
        {
            task_id=45170
        },
        {
            task_id=45171
        },
        {
            task_id=45172
        },
        {
            task_id=45173
        },
        {
            task_id=45174
        },
        {
            task_id=45175
        },
        {
            task_id=45176
        },
        {
            task_id=45177
        },
        {
            task_id=45178
        },
        {
            task_id=45179,
            rate=206
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45180
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45181
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45182
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45183
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45184
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45185
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45186
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45187
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45188
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45189
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45190
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45191
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45192
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45193
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45194
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45195
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45196
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45197
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45198
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45199
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45200
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45201
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45202
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45203
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45204
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45205
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45206
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45207
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45208
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45209
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45210
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45211
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45212
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45213
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45214
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45215
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45216
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45217
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45218
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45219
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45220
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45221
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45222
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45223
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45224
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45225
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45226
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45227
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45228
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45229
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45230
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45231
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45232
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45233
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45234
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45235
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45236
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45237
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45238
        },
        {
            stag=2,
            is_shilian=0,
            task_id=45239,
            rate=206
        }
    },
    task_reward={
        {
            feisheng_stage=0,
            reward_group=1
        },
        {
            feisheng_stage=0,
            task_num=2,
            reward_group=1
        },
        {
            feisheng_stage=0,
            task_num=3,
            reward_group=1
        },
        {
            feisheng_stage=0,
            task_num=4,
            reward_group=1
        },
        {
            feisheng_stage=0,
            task_num=5,
            reward_group=1
        },
        {
            feisheng_stage=0,
            task_num=6,
            reward_group=1
        },
        {
            feisheng_stage=0,
            task_num=7,
            reward_group=2
        },
        {
            feisheng_stage=0,
            task_num=8,
            reward_group=2
        },
        {
            feisheng_stage=0,
            task_num=9,
            reward_group=2
        },
        {
            feisheng_stage=0,
            task_num=10,
            reward_group=2
        },
        {
            is_shilian=0
        },
        {
            is_shilian=0,
            task_num=2
        },
        {
            is_shilian=0,
            task_num=3
        },
        {
            is_shilian=0,
            task_num=4
        },
        {
            is_shilian=0,
            task_num=5
        },
        {
            is_shilian=0,
            task_num=6
        },
        {
            is_shilian=0,
            task_num=7
        },
        {
            is_shilian=0,
            task_num=8
        },
        {
            is_shilian=0,
            task_num=9,
            reward_group=4
        },
        {
            is_shilian=0,
            task_num=10,
            reward_group=4
        },
        {
            reward_group=5
        },
        {
            task_num=2,
            reward_group=5
        },
        {
            task_num=3,
            reward_group=5
        },
        {
            task_num=4,
            reward_group=6
        },
        {
            task_num=5,
            reward_group=6
        },
        {
            task_num=6,
            reward_group=6
        },
        {
            task_num=7,
            reward_group=6
        },
        {
            task_num=8,
            reward_group=6
        },
        {
            task_num=9,
            reward_group=6
        },
        {
            task_num=10,
            reward_group=6
        },
        {
            feisheng_stage=2,
            is_shilian=0,
            reward_group=7
        },
        {
            feisheng_stage=2,
            is_shilian=0,
            task_num=2,
            reward_group=7
        },
        {
            feisheng_stage=2,
            is_shilian=0,
            task_num=3,
            reward_group=7
        },
        {
            feisheng_stage=2,
            is_shilian=0,
            task_num=4,
            reward_group=7
        },
        {
            feisheng_stage=2,
            is_shilian=0,
            task_num=5,
            reward_group=7
        },
        {
            feisheng_stage=2,
            is_shilian=0,
            task_num=6,
            reward_group=7
        },
        {
            feisheng_stage=2,
            is_shilian=0,
            task_num=7,
            reward_group=7
        },
        {
            feisheng_stage=2,
            is_shilian=0,
            task_num=8,
            reward_group=8
        },
        {
            feisheng_stage=2,
            is_shilian=0,
            task_num=9,
            reward_group=8
        },
        {
            feisheng_stage=2,
            is_shilian=0,
            task_num=10,
            reward_group=8
        }
    },
    reward_group={
        {
            reward_id=1,
            reward_item=_itemlist.i_27852_3_1
        },
        {
            reward_id=2,
            reward_item=_itemlist.i_27852_4_1
        },
        {
            reward_id=3,
            reward_item=_itemlist.i_27870_2_1
        },
        {
            reward_id=4,
            reward_item=_itemlist.i_27850_1_1
        },
        {
            reward_id=5,
            reward_item=_itemlist.i_27853_6_1
        },
        {
            reward_id=6,
            reward_item=_itemlist.i_27853_8_1
        },
        {
            reward_id=7,
            reward_item=_itemlist.i_27870_2_1
        },
        {
            reward_id=8,
            reward_item=_itemlist.i_27850_1_1
        }
    },
    last_reward={
        {
            feisheng_stage=0,
            reward_item={
                [0]=_itemlist.i_22014_2_1,
                [1]=_itemlist.i_27852_6_1
            },
            show_reward_item={
                [0]=_itemlist.i_22014_2_1,
                [1]=_itemlist.i_27852_40_1
            }
        },
        {
            is_shilian=0,
            reward_item={
                [0]=_itemlist.i_22014_2_1,
                [1]=_itemlist.i_27870_4_1,
                [2]=_itemlist.i_27850_1_1
            },
            show_reward_item={
                [0]=_itemlist.i_22014_2_1,
                [1]=_itemlist.i_27870_20_1,
                [2]=_itemlist.i_27850_3_1
            }
        },
        {
            reward_item={
                [0]=_itemlist.i_22014_2_1,
                [1]=_itemlist.i_27853_10_1
            },
            show_reward_item={
                [0]=_itemlist.i_22014_2_1,
                [1]=_itemlist.i_27853_84_1
            }
        },
        {
            feisheng_stage=2,
            is_shilian=0,
            reward_item={
                [0]=_itemlist.i_22014_2_1,
                [1]=_itemlist.i_27870_6_1,
                [2]=_itemlist.i_27850_1_1
            },
            show_reward_item={
                [0]=_itemlist.i_22014_2_1,
                [1]=_itemlist.i_27870_20_1,
                [2]=_itemlist.i_27850_4_1
            }
        }
    },
    anger_soul={
        {
            att_type_1=0,
            att_type_2=0
        },
        {
            level=1,
            att_type_1=1,
            attr_value_1=100,
            att_type_2=20,
            attr_value_2=25,
            sp_id=14001
        },
        {
            level=2,
            att_type_1=1,
            attr_value_1=200,
            att_type_2=20,
            attr_value_2=50,
            sp_id=14002
        },
        {
            level=3,
            att_type_1=1,
            attr_value_1=300,
            att_type_2=20,
            attr_value_2=75,
            sp_id=14003
        },
        {
            level=4,
            att_type_1=1,
            attr_value_1=400,
            att_type_2=20,
            attr_value_2=100,
            sp_id=14004
        },
        {
            level=5,
            att_type_1=1,
            attr_value_1=500,
            att_type_2=20,
            attr_value_2=125,
            sp_id=14005
        },
        {
            level=6,
            att_type_1=1,
            attr_value_1=600,
            att_type_2=20,
            attr_value_2=150,
            sp_id=14006
        },
        {
            level=7,
            att_type_1=1,
            attr_value_1=700,
            att_type_2=20,
            attr_value_2=175,
            sp_id=14007
        },
        {
            level=8,
            att_type_1=1,
            attr_value_1=800,
            att_type_2=20,
            attr_value_2=200,
            sp_id=14008
        },
        {
            level=9,
            att_type_1=1,
            attr_value_1=900,
            att_type_2=20,
            attr_value_2=225,
            sp_id=14009
        },
        {
            level=10,
            att_type_1=1,
            attr_value_1=1000,
            att_type_2=20,
            attr_value_2=250,
            sp_id=14010
        },
        {
            level=11,
            att_type_1=1,
            attr_value_1=1100,
            att_type_2=20,
            attr_value_2=275,
            sp_id=14011
        },
        {
            level=12,
            att_type_1=1,
            attr_value_1=1200,
            att_type_2=20,
            attr_value_2=300,
            sp_id=14012
        },
        {
            level=13,
            att_type_1=1,
            attr_value_1=1300,
            att_type_2=20,
            attr_value_2=325,
            sp_id=14013
        },
        {
            level=14,
            att_type_1=1,
            attr_value_1=1400,
            att_type_2=20,
            attr_value_2=350,
            sp_id=14014
        },
        {
            level=15,
            att_type_1=1,
            attr_value_1=1500,
            att_type_2=20,
            attr_value_2=375,
            sp_id=14015
        },
        {
            level=16,
            att_type_1=1,
            attr_value_1=1600,
            att_type_2=20,
            attr_value_2=400,
            sp_id=14016
        },
        {
            level=17,
            att_type_1=1,
            attr_value_1=1700,
            att_type_2=20,
            attr_value_2=425,
            sp_id=14017
        },
        {
            level=18,
            att_type_1=1,
            attr_value_1=1800,
            att_type_2=20,
            attr_value_2=450,
            sp_id=14018
        },
        {
            level=19,
            att_type_1=1,
            attr_value_1=1900,
            att_type_2=20,
            attr_value_2=475,
            sp_id=14019
        },
        {
            level=20,
            item_id=0,
            num=0,
            att_type_1=1,
            attr_value_1=2000,
            att_type_2=20,
            attr_value_2=500,
            sp_id=14020
        },
        {
            type=1,
            item_id=56630,
            att_type_1=0,
            att_type_2=0
        },
        {
            type=1,
            level=1,
            item_id=56630,
            attr_value_1=1000,
            attr_value_2=15,
            sp_id=14021
        },
        {
            type=1,
            level=2,
            item_id=56630,
            attr_value_1=2000,
            attr_value_2=30,
            sp_id=14022
        },
        {
            type=1,
            level=3,
            item_id=56630,
            attr_value_1=3000,
            attr_value_2=45,
            sp_id=14023
        },
        {
            type=1,
            level=4,
            item_id=56630,
            attr_value_1=4000,
            attr_value_2=60,
            sp_id=14024
        },
        {
            type=1,
            level=5,
            item_id=56630,
            attr_value_1=5000,
            attr_value_2=75,
            sp_id=14025
        },
        {
            type=1,
            level=6,
            item_id=56630,
            attr_value_1=6000,
            attr_value_2=90,
            sp_id=14026
        },
        {
            type=1,
            level=7,
            item_id=56630,
            attr_value_1=7000,
            attr_value_2=105,
            sp_id=14027
        },
        {
            type=1,
            level=8,
            item_id=56630,
            attr_value_1=8000,
            attr_value_2=120,
            sp_id=14028
        },
        {
            type=1,
            level=9,
            item_id=56630,
            attr_value_1=9000,
            attr_value_2=135,
            sp_id=14029
        },
        {
            type=1,
            level=10,
            item_id=56630,
            attr_value_1=10000,
            attr_value_2=150,
            sp_id=14030
        },
        {
            type=1,
            level=11,
            item_id=56630,
            attr_value_1=11000,
            attr_value_2=165,
            sp_id=14031
        },
        {
            type=1,
            level=12,
            item_id=56630,
            attr_value_1=12000,
            attr_value_2=180,
            sp_id=14032
        },
        {
            type=1,
            level=13,
            item_id=56630,
            attr_value_1=13000,
            attr_value_2=195,
            sp_id=14033
        },
        {
            type=1,
            level=14,
            item_id=56630,
            attr_value_1=14000,
            attr_value_2=210,
            sp_id=14034
        },
        {
            type=1,
            level=15,
            item_id=56630,
            attr_value_1=15000,
            attr_value_2=225,
            sp_id=14035
        },
        {
            type=1,
            level=16,
            item_id=56630,
            attr_value_1=16000,
            attr_value_2=240,
            sp_id=14036
        },
        {
            type=1,
            level=17,
            item_id=56630,
            attr_value_1=17000,
            attr_value_2=255,
            sp_id=14037
        },
        {
            type=1,
            level=18,
            item_id=56630,
            attr_value_1=18000,
            attr_value_2=270,
            sp_id=14038
        },
        {
            type=1,
            level=19,
            item_id=56630,
            attr_value_1=19000,
            attr_value_2=285,
            sp_id=14039
        },
        {
            type=1,
            level=20,
            item_id=0,
            num=0,
            attr_value_1=20000,
            attr_value_2=300,
            sp_id=14040
        },
        {
            type=2,
            item_id=56631,
            att_type_1=0,
            att_type_2=0
        },
        {
            type=2,
            level=1,
            item_id=56631,
            attr_value_1=1000,
            attr_value_2=15,
            sp_id=14041
        },
        {
            type=2,
            level=2,
            item_id=56631,
            attr_value_1=2000,
            attr_value_2=30,
            sp_id=14042
        },
        {
            type=2,
            level=3,
            item_id=56631,
            attr_value_1=3000,
            attr_value_2=45,
            sp_id=14043
        },
        {
            type=2,
            level=4,
            item_id=56631,
            attr_value_1=4000,
            attr_value_2=60,
            sp_id=14044
        },
        {
            type=2,
            level=5,
            item_id=56631,
            attr_value_1=5000,
            attr_value_2=75,
            sp_id=14045
        },
        {
            type=2,
            level=6,
            item_id=56631,
            attr_value_1=6000,
            attr_value_2=90,
            sp_id=14046
        },
        {
            type=2,
            level=7,
            item_id=56631,
            attr_value_1=7000,
            attr_value_2=105,
            sp_id=14047
        },
        {
            type=2,
            level=8,
            item_id=56631,
            attr_value_1=8000,
            attr_value_2=120,
            sp_id=14048
        },
        {
            type=2,
            level=9,
            item_id=56631,
            attr_value_1=9000,
            attr_value_2=135,
            sp_id=14049
        },
        {
            type=2,
            level=10,
            item_id=56631,
            attr_value_1=10000,
            attr_value_2=150,
            sp_id=14050
        },
        {
            type=2,
            level=11,
            item_id=56631,
            attr_value_1=11000,
            attr_value_2=165,
            sp_id=14051
        },
        {
            type=2,
            level=12,
            item_id=56631,
            attr_value_1=12000,
            attr_value_2=180,
            sp_id=14052
        },
        {
            type=2,
            level=13,
            item_id=56631,
            attr_value_1=13000,
            attr_value_2=195,
            sp_id=14053
        },
        {
            type=2,
            level=14,
            item_id=56631,
            attr_value_1=14000,
            attr_value_2=210,
            sp_id=14054
        },
        {
            type=2,
            level=15,
            item_id=56631,
            attr_value_1=15000,
            attr_value_2=225,
            sp_id=14055
        },
        {
            type=2,
            level=16,
            item_id=56631,
            attr_value_1=16000,
            attr_value_2=240,
            sp_id=14056
        },
        {
            type=2,
            level=17,
            item_id=56631,
            attr_value_1=17000,
            attr_value_2=255,
            sp_id=14057
        },
        {
            type=2,
            level=18,
            item_id=56631,
            attr_value_1=18000,
            attr_value_2=270,
            sp_id=14058
        },
        {
            type=2,
            level=19,
            item_id=56631,
            attr_value_1=19000,
            attr_value_2=285,
            sp_id=14059
        },
        {
            type=2,
            level=20,
            item_id=0,
            num=0,
            attr_value_1=20000,
            attr_value_2=300,
            sp_id=14060
        }
    }
}
SetConfigDefaultVal(Config.role_feisheng_auto,_default_val,nil,nil,nil)