local _default_val={
    level={
        grade=3,
        unit_num=5,
        rabbit_num=1,
        change_unit_num=2,
        change_time=5,
        change_group=6,
        start_talk="1|2|3|4|5|6",
        succ_talk="7|8|9|10",
        fail_talk="11|12|13|14",
        reward_show="",
        item_id=""
    },
    change={
        change_group=5,
        change_unit=24
    }
}
local _itemlist={
    i_31323_1_1={
        item_id=31323,
        num=1,
        is_bind=1
    },
    i_26232_40_1={
        item_id=26232,
        num=40,
        is_bind=1
    },
    i_31324_1_1={
        item_id=31324,
        num=1,
        is_bind=1
    },
    i_31325_1_1={
        item_id=31325,
        num=1,
        is_bind=1
    }
}
Config.sanxian_game_auto={
    level={
        {
            level=1,
            grade=1,
            unit_num=3,
            change_unit_num=1,
            change_time=3,
            change_group=1,
            start_talk="1|2|3|4|6"
        },
        {
            level=2,
            grade=1,
            unit_num=3,
            change_unit_num=1,
            change_time=3,
            change_group=1,
            start_talk="1|2|3|4|6"
        },
        {
            level=3,
            grade=1,
            unit_num=3,
            change_unit_num=1,
            change_time=4,
            change_group=1,
            start_talk="1|2|3|4|6",
            final_reward={
                [0]=_itemlist.i_31323_1_1,
                [1]=_itemlist.i_26232_40_1
            },
            reward_show="五宝莲台灯",
            item_id=31323
        },
        {
            level=4,
            grade=2,
            unit_num=4,
            change_unit_num=1,
            change_time=4,
            change_group=2,
            final_reward={
                [0]=_itemlist.i_31323_1_1,
                [1]=_itemlist.i_26232_40_1
            }
        },
        {
            level=5,
            grade=2,
            unit_num=4,
            change_group=3,
            final_reward={
                [0]=_itemlist.i_31323_1_1,
                [1]=_itemlist.i_26232_40_1
            }
        },
        {
            level=6,
            grade=2,
            unit_num=4,
            rabbit_num=2,
            change_time=6,
            change_group=3,
            final_reward={
                [0]=_itemlist.i_31324_1_1,
                [1]=_itemlist.i_26232_40_1
            },
            reward_show="七星水晶灯",
            item_id=31324
        },
        {
            level=7,
            change_group=4,
            final_reward={
                [0]=_itemlist.i_31324_1_1,
                [1]=_itemlist.i_26232_40_1
            }
        },
        {
            level=8,
            rabbit_num=2,
            change_group=5,
            final_reward={
                [0]=_itemlist.i_31324_1_1,
                [1]=_itemlist.i_26232_40_1
            }
        },
        {
            level=9,
            rabbit_num=2,
            change_time=6,
            final_reward={
                [0]=_itemlist.i_31325_1_1,
                [1]=_itemlist.i_26232_40_1
            },
            reward_show="九转琉璃灯",
            item_id=31325
        },
        {
            level=10,
            rabbit_num=2,
            change_time=7,
            final_reward={
                [0]=_itemlist.i_31325_1_1,
                [1]=_itemlist.i_26232_40_1
            }
        },
        {
            level=11,
            rabbit_num=2,
            change_time=8,
            final_reward={
                [0]=_itemlist.i_31325_1_1,
                [1]=_itemlist.i_26232_40_1
            }
        },
        {
            level=12,
            rabbit_num=2,
            change_time=9,
            final_reward={
                [0]=_itemlist.i_31325_1_1,
                [1]=_itemlist.i_26232_40_1
            }
        }
    },
    change={
        {
            change_group=1,
            change_unit=12
        },
        {
            change_group=1,
            change_unit=13
        },
        {
            change_group=1,
            change_unit=23
        },
        {
            change_group=2,
            change_unit=12
        },
        {
            change_group=2,
            change_unit=13
        },
        {
            change_group=2,
            change_unit=14
        },
        {
            change_group=2,
            change_unit=23
        },
        {
            change_group=2
        },
        {
            change_group=2,
            change_unit=34
        },
        {
            change_group=3,
            change_unit=12
        },
        {
            change_group=3,
            change_unit=13
        },
        {
            change_group=3,
            change_unit=14
        },
        {
            change_group=3,
            change_unit=23
        },
        {
            change_group=3
        },
        {
            change_group=3,
            change_unit=34
        },
        {
            change_group=3,
            change_unit=1423
        },
        {
            change_group=3,
            change_unit=1234
        },
        {
            change_group=3,
            change_unit=1324
        },
        {
            change_group=4,
            change_unit=12
        },
        {
            change_group=4,
            change_unit=13
        },
        {
            change_group=4,
            change_unit=14
        },
        {
            change_group=4,
            change_unit=15
        },
        {
            change_group=4,
            change_unit=23
        },
        {
            change_group=4
        },
        {
            change_group=4,
            change_unit=25
        },
        {
            change_group=4
        },
        {
            change_group=4,
            change_unit=34
        },
        {
            change_group=4,
            change_unit=45
        },
        {
            change_unit=12
        },
        {
            change_unit=13
        },
        {
            change_unit=14
        },
        {
            change_unit=15
        },
        {
            change_unit=23
        },
        {},
        {
            change_unit=25
        },
        {},
        {
            change_unit=34
        },
        {
            change_unit=45
        },
        {
            change_unit=1234
        },
        {
            change_unit=1245
        },
        {
            change_unit=1523
        },
        {
            change_unit=1534
        },
        {
            change_unit=2345
        },
        {
            change_unit=2435
        },
        {
            change_unit=1324
        },
        {
            change_unit=1325
        },
        {
            change_unit=1425
        },
        {
            change_unit=1435
        },
        {
            change_group=6,
            change_unit=1234
        },
        {
            change_group=6,
            change_unit=1245
        },
        {
            change_group=6,
            change_unit=1523
        },
        {
            change_group=6,
            change_unit=1534
        },
        {
            change_group=6,
            change_unit=2345
        },
        {
            change_group=6,
            change_unit=2435
        },
        {
            change_group=6,
            change_unit=1324
        },
        {
            change_group=6,
            change_unit=1325
        },
        {
            change_group=6,
            change_unit=1425
        },
        {
            change_group=6,
            change_unit=1435
        }
    },
    word={
        {
            id=1,
            word="看好了！"
        },
        {
            id=2,
            word="我要开始变身了~"
        },
        {
            id=3,
            word="左三圈，右三圈"
        },
        {
            id=4,
            word="超级变变变"
        },
        {
            id=5,
            word="我要发挥真正的实力了！"
        },
        {
            id=6,
            word="感受疾风吧！"
        },
        {
            id=7,
            word="你赢啦"
        },
        {
            id=8,
            word="太棒了！"
        },
        {
            id=9,
            word="你真厉害！"
        },
        {
            id=10,
            word="不愧是你！"
        },
        {
            id=11,
            word="啦啦啦啦"
        },
        {
            id=12,
            word="抓不到我吧"
        },
        {
            id=13,
            word="嘿嘿~"
        },
        {
            id=14,
            word="略略略~"
        }
    },
    other={
        {
            start_time=3,
            chose_time=10,
            reward_time=2,
            reward_show="31325:26323",
            desc1=301,
            desc2=302,
            npc_id=73701,
            scene_id=327,
            max_level=12,
            title_item_id=28927,
            title_id=189,
            title_level=12
        }
    }
}
SetConfigDefaultVal(Config.sanxian_game_auto,_default_val,nil,nil,nil)