local _default_val={
    condition={
        condition_type=12,
        param_1=2,
        param_2=1,
        param_3=0
    }
}
Config.score_condition_auto={
    condition={
        [0]={
            condition_id=0,
            condition_type=0,
            param_1=0,
            param_2=0,
            desc="成功通关"
        },
        [1]={
            condition_id=1,
            condition_type=1,
            param_1=5,
            param_2=0,
            desc="5回合内结束战斗"
        },
        [2]={
            condition_id=2,
            condition_type=1,
            param_1=6,
            param_2=0,
            desc="6回合内结束战斗"
        },
        [3]={
            condition_id=3,
            condition_type=1,
            param_1=7,
            param_2=0,
            desc="7回合内结束战斗"
        },
        [4]={
            condition_id=4,
            condition_type=1,
            param_1=8,
            param_2=0,
            desc="8回合内结束战斗"
        },
        [5]={
            condition_id=5,
            condition_type=1,
            param_1=9,
            param_2=0,
            desc="9回合内结束战斗"
        },
        [6]={
            condition_id=6,
            condition_type=1,
            param_1=10,
            param_2=0,
            desc="10回合内结束战斗"
        },
        [7]={
            condition_id=7,
            condition_type=1,
            param_1=12,
            param_2=0,
            desc="12回合内结束战斗"
        },
        [8]={
            condition_id=8,
            condition_type=2,
            param_1=1,
            param_2=0,
            desc="战斗结束时无角色阵亡"
        },
        [9]={
            condition_id=9,
            condition_type=2,
            param_1=1,
            param_2=2,
            desc="战斗结束时阵亡角色不多于2名"
        },
        [10]={
            condition_id=10,
            condition_type=2,
            param_1=1,
            param_2=3,
            desc="战斗结束时阵亡角色不多于3名"
        },
        [11]={
            condition_id=11,
            condition_type=2,
            param_1=1,
            param_2=4,
            desc="战斗结束时阵亡角色不多于4名"
        },
        [12]={
            condition_id=12,
            condition_type=3,
            param_1=1,
            param_2=30,
            desc="战斗结束时主角生命大于30%"
        },
        [13]={
            condition_id=13,
            condition_type=3,
            param_1=1,
            param_2=40,
            desc="战斗结束时主角生命大于40%"
        },
        [14]={
            condition_id=14,
            condition_type=3,
            param_1=1,
            param_2=50,
            desc="战斗结束时主角生命大于50%"
        },
        [15]={
            condition_id=15,
            condition_type=3,
            param_1=1,
            param_2=60,
            desc="战斗结束时主角生命大于60%"
        },
        [16]={
            condition_id=16,
            condition_type=3,
            param_1=1,
            param_2=80,
            desc="战斗结束时主角生命大于80%"
        },
        [17]={
            condition_id=17,
            condition_type=4,
            param_1=5,
            param_2=2,
            param_3=700,
            desc="5回合内击败首领"
        },
        [18]={
            condition_id=18,
            condition_type=5,
            param_1=1,
            param_2=0,
            desc="携带伙伴：沫璃通关"
        },
        [19]={
            condition_id=19,
            condition_type=5,
            param_2=0,
            desc="携带伙伴：罗刹通关"
        },
        [20]={
            condition_id=20,
            condition_type=5,
            param_1=4,
            param_2=0,
            desc="携带伙伴：鹿尧通关"
        },
        [21]={
            condition_id=21,
            condition_type=5,
            param_1=6,
            param_2=0,
            desc="携带伙伴：凰通关"
        },
        [22]={
            condition_id=22,
            condition_type=5,
            param_1=8,
            param_2=0,
            desc="携带伙伴：秦龙通关"
        },
        [23]={
            condition_id=23,
            condition_type=5,
            param_1=3,
            param_2=0,
            desc="携带伙伴：烛照通关"
        },
        [24]={
            condition_id=24,
            condition_type=5,
            param_1=5,
            param_2=0,
            desc="携带伙伴：医仙儿通关"
        },
        [25]={
            condition_id=25,
            condition_type=5,
            param_1=7,
            param_2=0,
            desc="携带伙伴：夸父通关"
        },
        [26]={
            condition_id=26,
            condition_type=5,
            param_1=9,
            param_2=0,
            desc="携带伙伴：水月通关"
        },
        [27]={
            condition_id=27,
            condition_type=5,
            param_1=10,
            param_2=0,
            desc="携带伙伴：方天君通关"
        },
        [28]={
            condition_id=28,
            condition_type=5,
            param_1=11,
            param_2=0,
            desc="携带伙伴：小菀通关"
        },
        [29]={
            condition_id=29,
            condition_type=5,
            param_1=12,
            param_2=0,
            desc="携带伙伴：莫邪通关"
        },
        [30]={
            condition_id=30,
            condition_type=5,
            param_1=13,
            param_2=0,
            desc="携带伙伴：萧镇通关"
        },
        [31]={
            condition_id=31,
            condition_type=5,
            param_1=15,
            param_2=0,
            desc="携带伙伴：后羿通关"
        },
        [32]={
            condition_id=32,
            condition_type=5,
            param_1=17,
            param_2=0,
            desc="携带伙伴：南宫雪通关"
        },
        [33]={
            condition_id=33,
            condition_type=5,
            param_1=20,
            param_2=0,
            desc="携带伙伴：狱神通关"
        },
        [34]={
            condition_id=34,
            condition_type=5,
            param_1=21,
            param_2=0,
            desc="携带伙伴：姜子牙通关"
        },
        [35]={
            condition_id=35,
            condition_type=5,
            param_1=14,
            param_2=0,
            desc="携带伙伴：灵儿通关"
        },
        [36]={
            condition_id=36,
            condition_type=5,
            param_1=16,
            param_2=0,
            desc="携带伙伴：魏驰通关"
        },
        [37]={
            condition_id=37,
            condition_type=5,
            param_1=18,
            param_2=0,
            desc="携带伙伴：格乐通关"
        },
        [38]={
            condition_id=38,
            condition_type=5,
            param_1=19,
            param_2=0,
            desc="携带伙伴：大司命通关"
        },
        [39]={
            condition_id=39,
            condition_type=8,
            desc="携带至少两个气功师伙伴通关"
        },
        [40]={
            condition_id=40,
            condition_type=8,
            param_2=2,
            desc="携带至少两个剑客伙伴通关"
        },
        [41]={
            condition_id=41,
            condition_type=8,
            param_2=3,
            desc="携带至少两个狂战士伙伴通关"
        },
        [42]={
            condition_id=42,
            condition_type=8,
            param_2=4,
            desc="携带至少两个铁卫伙伴通关"
        },
        [43]={
            condition_id=43,
            condition_type=8,
            param_2=5,
            desc="携带至少两个神射手伙伴通关"
        },
        [44]={
            condition_id=44,
            condition_type=8,
            param_2=6,
            desc="携带至少两个星术师伙伴通关"
        },
        [45]={
            condition_id=45,
            condition_type=8,
            param_2=7,
            desc="携带至少两个医师伙伴通关"
        },
        [46]={
            condition_id=46,
            condition_type=8,
            param_2=8,
            desc="携带至少两个巫师伙伴通关"
        },
        [47]={
            condition_id=47,
            condition_type=10,
            param_1=1,
            param_2=5,
            desc="携带至少一个无双品质伙伴通关"
        },
        [48]={
            condition_id=48,
            condition_type=10,
            param_2=5,
            desc="携带至少两个无双品质伙伴通关"
        },
        [49]={
            condition_id=49,
            condition_type=10,
            param_1=3,
            param_2=5,
            desc="携带至少三个无双品质伙伴通关"
        },
        [50]={
            condition_id=50,
            condition_type=10,
            param_1=4,
            param_2=5,
            desc="携带至少四个无双品质伙伴通关"
        },
        [51]={
            condition_id=51,
            condition_type=10,
            param_1=1,
            param_2=6,
            desc="携带至少一个神威品质伙伴通关"
        },
        [52]={
            condition_id=52,
            condition_type=10,
            param_2=6,
            desc="携带至少二个神威品质伙伴通关"
        },
        [53]={
            condition_id=53,
            condition_type=10,
            param_1=3,
            param_2=6,
            desc="携带至少三个神威品质伙伴通关"
        },
        [54]={
            condition_id=54,
            condition_type=10,
            param_1=4,
            param_2=6,
            desc="携带至少四个神威品质伙伴通关"
        },
        [55]={
            condition_id=55,
            condition_type=11,
            param_2=0,
            desc="携带至少两个女性伙伴通关"
        },
        [56]={
            condition_id=56,
            condition_type=11,
            param_2=0,
            desc="携带至少三个女性伙伴通关"
        },
        [57]={
            condition_id=57,
            condition_type=11,
            param_2=0,
            desc="携带至少四个女性伙伴通关"
        },
        [58]={
            condition_id=58,
            condition_type=11,
            desc="携带至少两个男性伙伴通关"
        },
        [59]={
            condition_id=59,
            condition_type=11,
            desc="携带至少三个男性伙伴通关"
        },
        [60]={
            condition_id=60,
            condition_type=11,
            desc="携带至少四个男性伙伴通关"
        },
        [61]={
            condition_id=61,
            param_1=50098,
            desc="携带强化+1或以上的水灵鸢通关"
        },
        [62]={
            condition_id=62,
            param_1=50053,
            desc="携带强化+1或以上的半人仙灵通关"
        },
        [63]={
            condition_id=63,
            param_1=50183,
            desc="携带强化+1或以上的海棠花妖通关"
        },
        [64]={
            condition_id=64,
            param_1=50084,
            desc="携带强化+1或以上的大地苍龙通关"
        },
        [65]={
            condition_id=65,
            param_1=50057,
            desc="携带强化+1或以上的覆海蛟龙通关"
        },
        [66]={
            condition_id=66,
            param_1=50045,
            desc="携带强化+1或以上的魔巨人通关"
        },
        [67]={
            condition_id=67,
            param_1=50028,
            desc="携带强化+1或以上的焱角兽通关"
        },
        [68]={
            condition_id=68,
            param_1=50008,
            desc="携带强化+1或以上的太古仙灵通关"
        },
        [69]={
            condition_id=69,
            param_1=50098,
            param_2=2,
            desc="携带强化+2或以上的水灵鸢通关"
        },
        [70]={
            condition_id=70,
            param_1=50053,
            param_2=2,
            desc="携带强化+2或以上的半人仙灵通关"
        },
        [71]={
            condition_id=71,
            param_1=50183,
            param_2=2,
            desc="携带强化+2或以上的海棠花妖通关"
        },
        [72]={
            condition_id=72,
            param_1=50084,
            param_2=2,
            desc="携带强化+2或以上的大地苍龙通关"
        },
        [73]={
            condition_id=73,
            param_1=50057,
            param_2=2,
            desc="携带强化+2或以上的覆海蛟龙通关"
        },
        [74]={
            condition_id=74,
            param_1=50045,
            param_2=2,
            desc="携带强化+2或以上的魔巨人通关"
        },
        [75]={
            condition_id=75,
            param_1=50028,
            param_2=2,
            desc="携带强化+2或以上的焱角兽通关"
        },
        [76]={
            condition_id=76,
            param_1=50008,
            param_2=2,
            desc="携带强化+2或以上的太古仙灵通关"
        },
        [77]={
            condition_id=77,
            param_1=50098,
            param_2=3,
            desc="携带强化+3或以上的水灵鸢通关"
        },
        [78]={
            condition_id=78,
            param_1=50053,
            param_2=3,
            desc="携带强化+3或以上的半人仙灵通关"
        },
        [79]={
            condition_id=79,
            param_1=50183,
            param_2=3,
            desc="携带强化+3或以上的海棠花妖通关"
        },
        [80]={
            condition_id=80,
            param_1=50084,
            param_2=3,
            desc="携带强化+3或以上的大地苍龙通关"
        },
        [81]={
            condition_id=81,
            param_1=50057,
            param_2=3,
            desc="携带强化+3或以上的覆海蛟龙通关"
        },
        [82]={
            condition_id=82,
            param_1=50045,
            param_2=3,
            desc="携带强化+3或以上的魔巨人通关"
        },
        [83]={
            condition_id=83,
            param_1=50028,
            param_2=3,
            desc="携带强化+3或以上的焱角兽通关"
        },
        [84]={
            condition_id=84,
            param_1=50008,
            param_2=3,
            desc="携带强化+3或以上的太古仙灵通关"
        },
        [85]={
            condition_id=85,
            param_1=50098,
            param_2=4,
            desc="携带强化+4或以上的水灵鸢通关"
        },
        [86]={
            condition_id=86,
            param_1=50053,
            param_2=4,
            desc="携带强化+4或以上的半人仙灵通关"
        },
        [87]={
            condition_id=87,
            param_1=50183,
            param_2=4,
            desc="携带强化+4或以上的海棠花妖通关"
        },
        [88]={
            condition_id=88,
            param_1=50084,
            param_2=4,
            desc="携带强化+4或以上的大地苍龙通关"
        },
        [89]={
            condition_id=89,
            param_1=50057,
            param_2=4,
            desc="携带强化+4或以上的覆海蛟龙通关"
        },
        [90]={
            condition_id=90,
            param_1=50045,
            param_2=4,
            desc="携带强化+4或以上的魔巨人通关"
        },
        [91]={
            condition_id=91,
            param_1=50028,
            param_2=4,
            desc="携带强化+4或以上的焱角兽通关"
        },
        [92]={
            condition_id=92,
            param_1=50008,
            param_2=4,
            desc="携带强化+4或以上的太古仙灵通关"
        },
        [93]={
            condition_id=93,
            param_1=50098,
            param_2=5,
            desc="携带强化+5或以上的水灵鸢通关"
        },
        [94]={
            condition_id=94,
            param_1=50053,
            param_2=5,
            desc="携带强化+5或以上的半人仙灵通关"
        },
        [95]={
            condition_id=95,
            param_1=50183,
            param_2=5,
            desc="携带强化+5或以上的海棠花妖通关"
        },
        [96]={
            condition_id=96,
            param_1=50084,
            param_2=5,
            desc="携带强化+5或以上的大地苍龙通关"
        },
        [97]={
            condition_id=97,
            param_1=50057,
            param_2=5,
            desc="携带强化+5或以上的覆海蛟龙通关"
        },
        [98]={
            condition_id=98,
            param_1=50045,
            param_2=5,
            desc="携带强化+5或以上的魔巨人通关"
        },
        [99]={
            condition_id=99,
            param_1=50028,
            param_2=5,
            desc="携带强化+5或以上的焱角兽通关"
        },
        [100]={
            condition_id=100,
            param_1=50008,
            param_2=5,
            desc="携带强化+5或以上的太古仙灵通关"
        },
        [101]={
            condition_id=101,
            param_1=50098,
            param_2=6,
            desc="携带强化+6或以上的水灵鸢通关"
        },
        [102]={
            condition_id=102,
            param_1=50053,
            param_2=6,
            desc="携带强化+6或以上的半人仙灵通关"
        },
        [103]={
            condition_id=103,
            param_1=50183,
            param_2=6,
            desc="携带强化+6或以上的海棠花妖通关"
        },
        [104]={
            condition_id=104,
            param_1=50084,
            param_2=6,
            desc="携带强化+6或以上的大地苍龙通关"
        },
        [105]={
            condition_id=105,
            param_1=50057,
            param_2=6,
            desc="携带强化+6或以上的覆海蛟龙通关"
        },
        [106]={
            condition_id=106,
            param_1=50045,
            param_2=6,
            desc="携带强化+6或以上的魔巨人通关"
        },
        [107]={
            condition_id=107,
            param_1=50028,
            param_2=6,
            desc="携带强化+6或以上的焱角兽通关"
        },
        [108]={
            condition_id=108,
            param_1=50008,
            param_2=6,
            desc="携带强化+6或以上的太古仙灵通关"
        },
        [109]={
            condition_id=109,
            param_1=50166,
            desc="携带强化+1以上的魔鲼通关"
        },
        [110]={
            condition_id=110,
            param_1=50181,
            desc="携带强化+1以上的黄金貔貅通关"
        },
        [111]={
            condition_id=111,
            param_1=50032,
            desc="携带强化+1以上的骸骨强盗通关"
        },
        [112]={
            condition_id=112,
            param_1=50152,
            desc="携带强化+1以上的山野蛙怪通关"
        },
        [113]={
            condition_id=113,
            param_1=50179,
            desc="携带强化+1以上的顽皮瑞兽通关"
        },
        [114]={
            condition_id=114,
            param_1=50170,
            desc="携带强化+1以上的麒麟战士通关"
        },
        [115]={
            condition_id=115,
            param_1=50033,
            desc="携带强化+1以上的玉面妖狐通关"
        },
        [116]={
            condition_id=116,
            param_1=50088,
            desc="携带强化+1以上的魍魉魔盒通关"
        },
        [117]={
            condition_id=117,
            param_1=50185,
            desc="携带强化+1以上的牛运宝宝通关"
        },
        [118]={
            condition_id=118,
            param_1=50166,
            param_2=2,
            desc="携带强化+2以上的魔鲼通关"
        },
        [119]={
            condition_id=119,
            param_1=50181,
            param_2=2,
            desc="携带强化+2以上的黄金貔貅通关"
        },
        [120]={
            condition_id=120,
            param_1=50032,
            param_2=2,
            desc="携带强化+2以上的骸骨强盗通关"
        },
        [121]={
            condition_id=121,
            param_1=50152,
            param_2=2,
            desc="携带强化+2以上的山野蛙怪通关"
        },
        [122]={
            condition_id=122,
            param_1=50179,
            param_2=2,
            desc="携带强化+2以上的顽皮瑞兽通关"
        },
        [123]={
            condition_id=123,
            param_1=50170,
            param_2=2,
            desc="携带强化+2以上的麒麟战士通关"
        },
        [124]={
            condition_id=124,
            param_1=50033,
            param_2=2,
            desc="携带强化+2以上的玉面妖狐通关"
        },
        [125]={
            condition_id=125,
            param_1=50088,
            param_2=2,
            desc="携带强化+2以上的魍魉魔盒通关"
        },
        [126]={
            condition_id=126,
            param_1=50185,
            param_2=2,
            desc="携带强化+2以上的牛运宝宝通关"
        },
        [127]={
            condition_id=127,
            param_1=50166,
            param_2=3,
            desc="携带强化+3以上的魔鲼通关"
        },
        [128]={
            condition_id=128,
            param_1=50181,
            param_2=3,
            desc="携带强化+3以上的黄金貔貅通关"
        },
        [129]={
            condition_id=129,
            param_1=50032,
            param_2=3,
            desc="携带强化+3以上的骸骨强盗通关"
        },
        [130]={
            condition_id=130,
            param_1=50152,
            param_2=3,
            desc="携带强化+3以上的山野蛙怪通关"
        },
        [131]={
            condition_id=131,
            param_1=50179,
            param_2=3,
            desc="携带强化+3以上的顽皮瑞兽通关"
        },
        [132]={
            condition_id=132,
            param_1=50170,
            param_2=3,
            desc="携带强化+3以上的麒麟战士通关"
        },
        [133]={
            condition_id=133,
            param_1=50033,
            param_2=3,
            desc="携带强化+3以上的玉面妖狐通关"
        },
        [134]={
            condition_id=134,
            param_1=50088,
            param_2=3,
            desc="携带强化+3以上的魍魉魔盒通关"
        },
        [135]={
            condition_id=135,
            param_1=50185,
            param_2=3,
            desc="携带强化+3以上的牛运宝宝通关"
        },
        [136]={
            condition_id=136,
            param_1=50166,
            param_2=4,
            desc="携带强化+4以上的魔鲼通关"
        },
        [137]={
            condition_id=137,
            param_1=50181,
            param_2=4,
            desc="携带强化+4以上的黄金貔貅通关"
        },
        [138]={
            condition_id=138,
            param_1=50032,
            param_2=4,
            desc="携带强化+4以上的骸骨强盗通关"
        },
        [139]={
            condition_id=139,
            param_1=50152,
            param_2=4,
            desc="携带强化+4以上的山野蛙怪通关"
        },
        [140]={
            condition_id=140,
            param_1=50179,
            param_2=4,
            desc="携带强化+4以上的顽皮瑞兽通关"
        },
        [141]={
            condition_id=141,
            param_1=50170,
            param_2=4,
            desc="携带强化+4以上的麒麟战士通关"
        },
        [142]={
            condition_id=142,
            param_1=50033,
            param_2=4,
            desc="携带强化+4以上的玉面妖狐通关"
        },
        [143]={
            condition_id=143,
            param_1=50088,
            param_2=4,
            desc="携带强化+4以上的魍魉魔盒通关"
        },
        [144]={
            condition_id=144,
            param_1=50185,
            param_2=4,
            desc="携带强化+4以上的牛运宝宝通关"
        },
        [145]={
            condition_id=145,
            param_1=50166,
            param_2=5,
            desc="携带强化+5以上的魔鲼通关"
        },
        [146]={
            condition_id=146,
            param_1=50181,
            param_2=5,
            desc="携带强化+5以上的黄金貔貅通关"
        },
        [147]={
            condition_id=147,
            param_1=50032,
            param_2=5,
            desc="携带强化+5以上的骸骨强盗通关"
        },
        [148]={
            condition_id=148,
            param_1=50152,
            param_2=5,
            desc="携带强化+5以上的山野蛙怪通关"
        },
        [149]={
            condition_id=149,
            param_1=50179,
            param_2=5,
            desc="携带强化+5以上的顽皮瑞兽通关"
        },
        [150]={
            condition_id=150,
            param_1=50170,
            param_2=5,
            desc="携带强化+5以上的麒麟战士通关"
        },
        [151]={
            condition_id=151,
            param_1=50033,
            param_2=5,
            desc="携带强化+5以上的玉面妖狐通关"
        },
        [152]={
            condition_id=152,
            param_1=50088,
            param_2=5,
            desc="携带强化+5以上的魍魉魔盒通关"
        },
        [153]={
            condition_id=153,
            param_1=50185,
            param_2=5,
            desc="携带强化+5以上的牛运宝宝通关"
        },
        [154]={
            condition_id=154,
            param_1=50166,
            param_2=6,
            desc="携带强化+6以上的魔鲼通关"
        },
        [155]={
            condition_id=155,
            param_1=50181,
            param_2=6,
            desc="携带强化+6以上的黄金貔貅通关"
        },
        [156]={
            condition_id=156,
            param_1=50032,
            param_2=6,
            desc="携带强化+6以上的骸骨强盗通关"
        },
        [157]={
            condition_id=157,
            param_1=50152,
            param_2=6,
            desc="携带强化+6以上的山野蛙怪通关"
        },
        [158]={
            condition_id=158,
            param_1=50179,
            param_2=6,
            desc="携带强化+6以上的顽皮瑞兽通关"
        },
        [159]={
            condition_id=159,
            param_1=50170,
            param_2=6,
            desc="携带强化+6以上的麒麟战士通关"
        },
        [160]={
            condition_id=160,
            param_1=50033,
            param_2=6,
            desc="携带强化+6以上的玉面妖狐通关"
        },
        [161]={
            condition_id=161,
            param_1=50088,
            param_2=6,
            desc="携带强化+6以上的魍魉魔盒通关"
        },
        [162]={
            condition_id=162,
            param_1=50185,
            param_2=6,
            desc="携带强化+6以上的牛运宝宝通关"
        },
        [163]={
            condition_id=163,
            condition_type=13,
            param_1=1,
            param_2=3,
            param_3=3,
            desc="携带一个强化+3以上的金卡宠物通关"
        },
        [164]={
            condition_id=164,
            condition_type=13,
            param_2=3,
            param_3=3,
            desc="携带两个强化+3以上的金卡宠物通关"
        },
        [165]={
            condition_id=165,
            condition_type=13,
            param_1=3,
            param_2=3,
            param_3=3,
            desc="携带三个强化+3以上的金卡宠物通关"
        },
        [166]={
            condition_id=166,
            condition_type=13,
            param_1=4,
            param_2=3,
            param_3=3,
            desc="携带四个强化+3以上的金卡宠物通关"
        },
        [167]={
            condition_id=167,
            condition_type=13,
            param_1=1,
            param_2=4,
            param_3=3,
            desc="携带一个强化+4以上的金卡宠物通关"
        },
        [168]={
            condition_id=168,
            condition_type=13,
            param_2=4,
            param_3=3,
            desc="携带两个强化+4以上的金卡宠物通关"
        },
        [169]={
            condition_id=169,
            condition_type=13,
            param_1=3,
            param_2=4,
            param_3=3,
            desc="携带三个强化+4以上的金卡宠物通关"
        },
        [170]={
            condition_id=170,
            condition_type=13,
            param_1=4,
            param_2=4,
            param_3=3,
            desc="携带四个强化+4以上的金卡宠物通关"
        },
        [171]={
            condition_id=171,
            condition_type=13,
            param_1=1,
            param_2=5,
            param_3=3,
            desc="携带一个强化+5以上的金卡宠物通关"
        },
        [172]={
            condition_id=172,
            condition_type=13,
            param_2=5,
            param_3=3,
            desc="携带两个强化+5以上的金卡宠物通关"
        },
        [173]={
            condition_id=173,
            condition_type=13,
            param_1=3,
            param_2=5,
            param_3=3,
            desc="携带三个强化+5以上的金卡宠物通关"
        },
        [174]={
            condition_id=174,
            condition_type=13,
            param_1=4,
            param_2=5,
            param_3=3,
            desc="携带四个强化+5以上的金卡宠物通关"
        },
        [175]={
            condition_id=175,
            condition_type=13,
            param_1=1,
            param_3=4,
            desc="携带一个强化+1以上的稀有宠物通关"
        },
        [176]={
            condition_id=176,
            condition_type=13,
            param_3=4,
            desc="携带两个强化+1以上的稀有宠物通关"
        },
        [177]={
            condition_id=177,
            condition_type=13,
            param_1=3,
            param_3=4,
            desc="携带三个强化+1以上的稀有宠物通关"
        },
        [178]={
            condition_id=178,
            condition_type=13,
            param_1=4,
            param_3=4,
            desc="携带四个强化+1以上的稀有宠物通关"
        },
        [179]={
            condition_id=179,
            condition_type=13,
            param_1=1,
            param_3=4,
            desc="携带一个强化+2以上的稀有宠物通关"
        },
        [180]={
            condition_id=180,
            condition_type=13,
            param_3=4,
            desc="携带两个强化+2以上的稀有宠物通关"
        },
        [181]={
            condition_id=181,
            condition_type=13,
            param_1=3,
            param_3=4,
            desc="携带三个强化+2以上的稀有宠物通关"
        },
        [182]={
            condition_id=182,
            condition_type=13,
            param_1=4,
            param_3=4,
            desc="携带四个强化+2以上的稀有宠物通关"
        },
        [183]={
            condition_id=183,
            condition_type=13,
            param_1=1,
            param_3=4,
            desc="携带一个强化+3以上的稀有宠物通关"
        },
        [184]={
            condition_id=184,
            condition_type=13,
            param_3=4,
            desc="携带两个强化+3以上的稀有宠物通关"
        },
        [185]={
            condition_id=185,
            condition_type=13,
            param_1=3,
            param_3=4,
            desc="携带三个强化+3以上的稀有宠物通关"
        },
        [186]={
            condition_id=186,
            condition_type=13,
            param_1=4,
            param_3=4,
            desc="携带四个强化+3以上的稀有宠物通关"
        },
        [187]={
            condition_id=187,
            condition_type=13,
            param_1=1,
            param_3=4,
            desc="携带一个强化+4以上的稀有宠物通关"
        },
        [188]={
            condition_id=188,
            condition_type=13,
            param_3=4,
            desc="携带两个强化+4以上的稀有宠物通关"
        },
        [189]={
            condition_id=189,
            condition_type=13,
            param_1=3,
            param_3=4,
            desc="携带三个强化+4以上的稀有宠物通关"
        },
        [190]={
            condition_id=190,
            condition_type=13,
            param_1=4,
            param_3=4,
            desc="携带四个强化+4以上的稀有宠物通关"
        },
        [191]={
            condition_id=191,
            condition_type=13,
            param_1=1,
            param_3=4,
            desc="携带一个强化+5以上的稀有宠物通关"
        },
        [192]={
            condition_id=192,
            condition_type=13,
            param_3=4,
            desc="携带两个强化+5以上的稀有宠物通关"
        },
        [193]={
            condition_id=193,
            condition_type=13,
            param_1=3,
            param_3=4,
            desc="携带三个强化+5以上的稀有宠物通关"
        },
        [194]={
            condition_id=194,
            condition_type=13,
            param_1=4,
            param_3=4,
            desc="携带四个强化+5以上的稀有宠物通关"
        }
    }
}
SetConfigDefaultVal(Config.score_condition_auto,_default_val,nil,nil,nil)