local _default_val={
    probability_promote={
        section_start=1,
        section_end=5,
        seq1=0,
        rate_common=100,
        rate_silver=50,
        rate_gold=20
    }
}
Config.seal_promote_auto={
    probability_promote={
        {
            seq=0,
            pets_id=50129
        },
        {
            seq=1,
            seq1=1,
            pets_id=50146
        },
        {
            seq=2,
            seq1=2,
            pets_id=50119
        },
        {
            seq=3,
            section_start=5,
            section_end=10,
            pets_id=50048
        },
        {
            seq=4,
            section_start=5,
            section_end=10,
            seq1=1,
            pets_id=50105
        },
        {
            seq=5,
            section_start=5,
            section_end=10,
            seq1=2,
            pets_id=50156
        },
        {
            seq=6,
            section_start=10,
            section_end=0,
            pets_id=50124
        },
        {
            seq=7,
            section_start=10,
            section_end=0,
            seq1=1,
            pets_id=50081
        },
        {
            seq=8,
            section_start=10,
            section_end=0,
            seq1=2,
            pets_id=50131
        }
    }
}
SetConfigDefaultVal(Config.seal_promote_auto,_default_val,nil,nil,nil)