local _default_val={
    basis_configuration={
        section_start=1,
        section_end=5,
        seq=0,
        activity_days=1,
        task_group=1
    },
    task_list={
        task_id=1,
        task_type=1,
        param_1=5,
        param_2=0
    }
}
local _itemlist={
    i_26349_5_1={
        item_id=26349,
        num=5,
        is_bind=1
    },
    i_26813_1_1={
        item_id=26813,
        num=1,
        is_bind=1
    },
    i_26349_4_1={
        item_id=26349,
        num=4,
        is_bind=1
    },
    i_26812_4_1={
        item_id=26812,
        num=4,
        is_bind=1
    },
    i_26349_1_1={
        item_id=26349,
        num=1,
        is_bind=1
    },
    i_26813_2_1={
        item_id=26813,
        num=2,
        is_bind=1
    },
    i_26812_7_1={
        item_id=26812,
        num=7,
        is_bind=1
    },
    i_27541_1_1={
        item_id=27541,
        num=1,
        is_bind=1
    },
    i_27540_4_1={
        item_id=27540,
        num=4,
        is_bind=1
    },
    i_27187_3_1={
        item_id=27187,
        num=3,
        is_bind=1
    },
    i_26416_3_1={
        item_id=26416,
        num=3,
        is_bind=1
    }
}
Config.shanhaichuyu_auto={
    basis_configuration={
        {
            type=0,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_26813_1_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_26812_4_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            type=1,
            seq=1,
            activity_days=2,
            task_group=2,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_26813_2_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_26812_7_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            type=2,
            seq=2,
            activity_days=3,
            task_group=3,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_26813_1_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_26812_4_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            type=3,
            seq=3,
            activity_days=4,
            task_group=4,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_26813_1_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_26812_4_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            type=4,
            seq=4,
            activity_days=5,
            task_group=5,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_26813_2_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_26812_7_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            type=5,
            seq=5,
            activity_days=6,
            task_group=6,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_26813_1_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_26812_4_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            type=6,
            section_start=6,
            section_end=14,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_27541_1_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_27540_4_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            type=7,
            section_start=6,
            section_end=14,
            seq=1,
            activity_days=2,
            task_group=2,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_27541_1_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_27540_4_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            type=8,
            section_start=6,
            section_end=14,
            seq=2,
            activity_days=3,
            task_group=3,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_27541_1_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_27540_4_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            type=9,
            section_start=6,
            section_end=14,
            seq=3,
            activity_days=4,
            task_group=4,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_27541_1_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_27540_4_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            type=10,
            section_start=6,
            section_end=14,
            seq=4,
            activity_days=5,
            task_group=5,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_27541_1_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_27540_4_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            type=11,
            section_start=6,
            section_end=14,
            seq=5,
            activity_days=6,
            task_group=6,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_27541_1_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_27540_4_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            type=12,
            section_start=15,
            section_end=42,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_27187_3_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_27187_3_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            type=13,
            section_start=15,
            section_end=42,
            seq=1,
            activity_days=2,
            task_group=2,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_27187_3_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_27187_3_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            type=14,
            section_start=15,
            section_end=42,
            seq=2,
            activity_days=3,
            task_group=3,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_27187_3_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_27187_3_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            type=15,
            section_start=15,
            section_end=42,
            seq=3,
            activity_days=4,
            task_group=4,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_27187_3_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_27187_3_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            type=16,
            section_start=15,
            section_end=42,
            seq=4,
            activity_days=5,
            task_group=5,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_27187_3_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_27187_3_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            type=17,
            section_start=15,
            section_end=42,
            seq=5,
            activity_days=6,
            task_group=6,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_27187_3_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_27187_3_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            type=18,
            section_start=43,
            section_end=0,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_26416_3_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_26416_3_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            type=19,
            section_start=43,
            section_end=0,
            seq=1,
            activity_days=2,
            task_group=2,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_26416_3_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_26416_3_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            type=20,
            section_start=43,
            section_end=0,
            seq=2,
            activity_days=3,
            task_group=3,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_26416_3_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_26416_3_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            type=21,
            section_start=43,
            section_end=0,
            seq=3,
            activity_days=4,
            task_group=4,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_26416_3_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_26416_3_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            type=22,
            section_start=43,
            section_end=0,
            seq=4,
            activity_days=5,
            task_group=5,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_26416_3_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_26416_3_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            type=23,
            section_start=43,
            section_end=0,
            seq=5,
            activity_days=6,
            task_group=6,
            reward_item={
                [0]=_itemlist.i_26349_5_1,
                [1]=_itemlist.i_26416_3_1
            },
            unfinish_reward_item={
                [0]=_itemlist.i_26349_4_1,
                [1]=_itemlist.i_26416_3_1
            },
            double_reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        }
    },
    activity_configuration={
        {
            type=0,
            activity_type=2155,
            activity_mod_key=118004
        },
        {
            type=1,
            activity_type=2160,
            activity_mod_key=118005
        },
        {
            type=2,
            activity_type=2134,
            activity_mod_key=56046
        },
        {
            type=3,
            activity_type=2142,
            activity_mod_key=118002
        },
        {
            type=4,
            activity_type=2140,
            activity_mod_key=118003
        },
        {
            type=5,
            activity_type=2156,
            activity_mod_key=118006
        }
    },
    task_list={
        {
            type=0,
            task_group=1,
            task_type=2,
            param_1=2,
            task_desc="参与连连乐翻天2次"
        },
        {
            type=1,
            task_group=2,
            task_type=2,
            task_desc="参与连连乐翻天5次"
        },
        {
            type=2,
            task_group=3,
            task_type=3,
            task_desc="参与山海问答5次"
        },
        {
            type=3,
            task_group=4,
            param_1=2,
            task_desc="参与山海花灯2次"
        },
        {
            type=4,
            task_group=5,
            task_desc="参与山海花灯5次"
        },
        {
            type=5,
            task_group=6,
            param_1=8,
            task_desc="参与山海花灯8次"
        }
    },
    other={
        {
            buy_money=300,
            cfg_ver=4
        }
    }
}
SetConfigDefaultVal(Config.shanhaichuyu_auto,_default_val,nil,nil,nil)