local _default_val={
    gift_configure={
        section_start=1,
        section_end=7,
        start_time=1,
        end_time=3,
        seq=0,
        ring_down=1,
        ring_up=1,
        group_id=0,
        exp=0,
        coin=0,
        is_open=1
    },
    task_list={
        task_type=2,
        param_1=0,
        param_2=1,
        accept_npc=562,
        commit_npc=590,
        task_name="寻物",
        obj_desc="消灭<color=#91db64>妖兽</color>",
        get_way=""
    },
    task_prefix={
        type=6,
        section_start=1,
        section_end=7,
        start_time=1,
        end_time=3,
        task_prefix_1="山海缘起·壹",
        task_prefix_2="缘起·壹",
        story_title="故事·壹",
        desc="　　玄都吕斌少时游走于山海间，看遍名山大川，其后怀着满腔热血，守卫都城安宁。现各方势力暗潮汹涌，都想扩张属地，扩大管辖范围，风起云涌下是百姓们即将被颠覆的生活。\n　　为了百姓们安宁而又平稳的生活，玄都内部各势力也在极力周旋，以维持各地势力的平衡。然而，平衡终将被打破，到时候百姓们又该何去何从？\n　　各位少侠们，此次你们可愿伸出援手，守护这方百姓？"
    }
}
local _itemlist={
    i_27575_1_1={
        item_id=27575,
        num=1,
        is_bind=1
    },
    i_26393_10_1={
        item_id=26393,
        num=10,
        is_bind=1
    },
    i_22007_20_1={
        item_id=22007,
        num=20,
        is_bind=1
    },
    i_26349_1_1={
        item_id=26349,
        num=1,
        is_bind=1
    },
    i_26394_10_1={
        item_id=26394,
        num=10,
        is_bind=1
    },
    i_22007_30_1={
        item_id=22007,
        num=30,
        is_bind=1
    },
    i_26394_15_1={
        item_id=26394,
        num=15,
        is_bind=1
    },
    i_26394_20_1={
        item_id=26394,
        num=20,
        is_bind=1
    },
    i_29088_10_1={
        item_id=29088,
        num=10,
        is_bind=1
    },
    i_29088_15_1={
        item_id=29088,
        num=15,
        is_bind=1
    },
    i_22007_1_1={
        item_id=22007,
        num=1,
        is_bind=1
    },
    i_65535_1_1={
        item_id=65535,
        num=1,
        is_bind=1
    },
    i_29088_1_1={
        item_id=29088,
        num=1,
        is_bind=1
    },
    i_26393_1_1={
        item_id=26393,
        num=1,
        is_bind=1
    },
    i_26394_1_1={
        item_id=26394,
        num=1,
        is_bind=1
    },
    i_26813_1_1={
        item_id=26813,
        num=1,
        is_bind=1
    },
    i_29038_2_1={
        item_id=29038,
        num=2,
        is_bind=1
    },
    i_26073_1_1={
        item_id=26073,
        num=1,
        is_bind=1
    }
}
Config.shanhai_origin_auto={
    gift_configure={
        {
            type=0,
            group_id=1
        },
        {
            type=1,
            seq=1,
            ring_down=2,
            ring_up=2,
            group_id=2
        },
        {
            type=2,
            seq=2,
            ring_down=3,
            ring_up=3,
            exp=300
        },
        {
            type=3,
            seq=3,
            ring_down=4,
            ring_up=4,
            group_id=3
        },
        {
            type=4,
            seq=4,
            ring_down=5,
            ring_up=5,
            group_id=4
        },
        {
            type=5,
            seq=5,
            ring_down=6,
            ring_up=6,
            group_id=5
        },
        {
            type=6,
            seq=6,
            ring_down=7,
            ring_up=7,
            exp=300
        },
        {
            type=7,
            seq=7,
            ring_down=8,
            ring_up=8,
            group_id=6
        },
        {
            type=8,
            seq=8,
            ring_down=9,
            ring_up=9,
            group_id=7
        },
        {
            type=9,
            seq=9,
            ring_down=10,
            ring_up=10,
            group_id=8
        },
        {
            type=10,
            start_time=7,
            end_time=9,
            group_id=41
        },
        {
            type=11,
            start_time=7,
            end_time=9,
            seq=1,
            ring_down=2,
            ring_up=2,
            group_id=42
        },
        {
            type=12,
            start_time=7,
            end_time=9,
            seq=2,
            ring_down=3,
            ring_up=3,
            exp=300
        },
        {
            type=13,
            start_time=7,
            end_time=9,
            seq=3,
            ring_down=4,
            ring_up=4,
            group_id=43
        },
        {
            type=14,
            start_time=7,
            end_time=9,
            seq=4,
            ring_down=5,
            ring_up=5,
            group_id=44
        },
        {
            type=15,
            start_time=7,
            end_time=9,
            seq=5,
            ring_down=6,
            ring_up=6,
            group_id=45
        },
        {
            type=16,
            start_time=7,
            end_time=9,
            seq=6,
            ring_down=7,
            ring_up=7,
            exp=300
        },
        {
            type=17,
            start_time=7,
            end_time=9,
            seq=7,
            ring_down=8,
            ring_up=8,
            group_id=46
        },
        {
            type=18,
            start_time=7,
            end_time=9,
            seq=8,
            ring_down=9,
            ring_up=9,
            group_id=47
        },
        {
            type=19,
            start_time=7,
            end_time=9,
            seq=9,
            ring_down=10,
            ring_up=10,
            group_id=48
        },
        {
            type=20,
            section_start=8,
            section_end=21,
            seq=10,
            group_id=9
        },
        {
            type=21,
            section_start=8,
            section_end=21,
            seq=11,
            ring_down=2,
            ring_up=2,
            group_id=10
        },
        {
            type=22,
            section_start=8,
            section_end=21,
            seq=12,
            ring_down=3,
            ring_up=3,
            exp=300
        },
        {
            type=23,
            section_start=8,
            section_end=21,
            seq=13,
            ring_down=4,
            ring_up=4,
            group_id=11
        },
        {
            type=24,
            section_start=8,
            section_end=21,
            seq=14,
            ring_down=5,
            ring_up=5,
            group_id=12
        },
        {
            type=25,
            section_start=8,
            section_end=21,
            seq=15,
            ring_down=6,
            ring_up=6,
            group_id=13
        },
        {
            type=26,
            section_start=8,
            section_end=21,
            seq=16,
            ring_down=7,
            ring_up=7,
            exp=300
        },
        {
            type=27,
            section_start=8,
            section_end=21,
            seq=17,
            ring_down=8,
            ring_up=8,
            group_id=14
        },
        {
            type=28,
            section_start=8,
            section_end=21,
            seq=18,
            ring_down=9,
            ring_up=9,
            group_id=15
        },
        {
            type=29,
            section_start=8,
            section_end=21,
            seq=19,
            ring_down=10,
            ring_up=10,
            group_id=16
        },
        {
            type=30,
            section_start=8,
            section_end=21,
            start_time=7,
            end_time=9,
            seq=10,
            group_id=49
        },
        {
            type=31,
            section_start=8,
            section_end=21,
            start_time=7,
            end_time=9,
            seq=11,
            ring_down=2,
            ring_up=2,
            group_id=50
        },
        {
            type=32,
            section_start=8,
            section_end=21,
            start_time=7,
            end_time=9,
            seq=12,
            ring_down=3,
            ring_up=3,
            exp=300
        },
        {
            type=33,
            section_start=8,
            section_end=21,
            start_time=7,
            end_time=9,
            seq=13,
            ring_down=4,
            ring_up=4,
            group_id=51
        },
        {
            type=34,
            section_start=8,
            section_end=21,
            start_time=7,
            end_time=9,
            seq=14,
            ring_down=5,
            ring_up=5,
            group_id=52
        },
        {
            type=35,
            section_start=8,
            section_end=21,
            start_time=7,
            end_time=9,
            seq=15,
            ring_down=6,
            ring_up=6,
            group_id=53
        },
        {
            type=36,
            section_start=8,
            section_end=21,
            start_time=7,
            end_time=9,
            seq=16,
            ring_down=7,
            ring_up=7,
            exp=300
        },
        {
            type=37,
            section_start=8,
            section_end=21,
            start_time=7,
            end_time=9,
            seq=17,
            ring_down=8,
            ring_up=8,
            group_id=54
        },
        {
            type=38,
            section_start=8,
            section_end=21,
            start_time=7,
            end_time=9,
            seq=18,
            ring_down=9,
            ring_up=9,
            group_id=55
        },
        {
            type=39,
            section_start=8,
            section_end=21,
            start_time=7,
            end_time=9,
            seq=19,
            ring_down=10,
            ring_up=10,
            group_id=56
        },
        {
            type=40,
            section_start=22,
            section_end=36,
            seq=20,
            group_id=17
        },
        {
            type=41,
            section_start=22,
            section_end=36,
            seq=21,
            ring_down=2,
            ring_up=2,
            group_id=18
        },
        {
            type=42,
            section_start=22,
            section_end=36,
            seq=22,
            ring_down=3,
            ring_up=3,
            exp=200
        },
        {
            type=43,
            section_start=22,
            section_end=36,
            seq=23,
            ring_down=4,
            ring_up=4,
            group_id=19
        },
        {
            type=44,
            section_start=22,
            section_end=36,
            seq=24,
            ring_down=5,
            ring_up=5,
            group_id=20
        },
        {
            type=45,
            section_start=22,
            section_end=36,
            seq=25,
            ring_down=6,
            ring_up=6,
            group_id=21
        },
        {
            type=46,
            section_start=22,
            section_end=36,
            seq=26,
            ring_down=7,
            ring_up=7,
            exp=200
        },
        {
            type=47,
            section_start=22,
            section_end=36,
            seq=27,
            ring_down=8,
            ring_up=8,
            group_id=22
        },
        {
            type=48,
            section_start=22,
            section_end=36,
            seq=28,
            ring_down=9,
            ring_up=9,
            group_id=23
        },
        {
            type=49,
            section_start=22,
            section_end=36,
            seq=29,
            ring_down=10,
            ring_up=10,
            group_id=24
        },
        {
            type=50,
            section_start=22,
            section_end=36,
            start_time=7,
            end_time=9,
            seq=20,
            group_id=57
        },
        {
            type=51,
            section_start=22,
            section_end=36,
            start_time=7,
            end_time=9,
            seq=21,
            ring_down=2,
            ring_up=2,
            group_id=58
        },
        {
            type=52,
            section_start=22,
            section_end=36,
            start_time=7,
            end_time=9,
            seq=22,
            ring_down=3,
            ring_up=3,
            exp=200
        },
        {
            type=53,
            section_start=22,
            section_end=36,
            start_time=7,
            end_time=9,
            seq=23,
            ring_down=4,
            ring_up=4,
            group_id=59
        },
        {
            type=54,
            section_start=22,
            section_end=36,
            start_time=7,
            end_time=9,
            seq=24,
            ring_down=5,
            ring_up=5,
            group_id=60
        },
        {
            type=55,
            section_start=22,
            section_end=36,
            start_time=7,
            end_time=9,
            seq=25,
            ring_down=6,
            ring_up=6,
            group_id=61
        },
        {
            type=56,
            section_start=22,
            section_end=36,
            start_time=7,
            end_time=9,
            seq=26,
            ring_down=7,
            ring_up=7,
            exp=200
        },
        {
            type=57,
            section_start=22,
            section_end=36,
            start_time=7,
            end_time=9,
            seq=27,
            ring_down=8,
            ring_up=8,
            group_id=62
        },
        {
            type=58,
            section_start=22,
            section_end=36,
            start_time=7,
            end_time=9,
            seq=28,
            ring_down=9,
            ring_up=9,
            group_id=63
        },
        {
            type=59,
            section_start=22,
            section_end=36,
            start_time=7,
            end_time=9,
            seq=29,
            ring_down=10,
            ring_up=10,
            group_id=64
        },
        {
            type=60,
            section_start=37,
            section_end=52,
            seq=30,
            group_id=25
        },
        {
            type=61,
            section_start=37,
            section_end=52,
            seq=31,
            ring_down=2,
            ring_up=2,
            group_id=26
        },
        {
            type=62,
            section_start=37,
            section_end=52,
            seq=32,
            ring_down=3,
            ring_up=3,
            exp=200
        },
        {
            type=63,
            section_start=37,
            section_end=52,
            seq=33,
            ring_down=4,
            ring_up=4,
            group_id=27
        },
        {
            type=64,
            section_start=37,
            section_end=52,
            seq=34,
            ring_down=5,
            ring_up=5,
            group_id=28
        },
        {
            type=65,
            section_start=37,
            section_end=52,
            seq=35,
            ring_down=6,
            ring_up=6,
            group_id=29
        },
        {
            type=66,
            section_start=37,
            section_end=52,
            seq=36,
            ring_down=7,
            ring_up=7,
            exp=200
        },
        {
            type=67,
            section_start=37,
            section_end=52,
            seq=37,
            ring_down=8,
            ring_up=8,
            group_id=30
        },
        {
            type=68,
            section_start=37,
            section_end=52,
            seq=38,
            ring_down=9,
            ring_up=9,
            group_id=31
        },
        {
            type=69,
            section_start=37,
            section_end=52,
            seq=39,
            ring_down=10,
            ring_up=10,
            group_id=32
        },
        {
            type=70,
            section_start=37,
            section_end=52,
            start_time=7,
            end_time=9,
            seq=30,
            group_id=65
        },
        {
            type=71,
            section_start=37,
            section_end=52,
            start_time=7,
            end_time=9,
            seq=31,
            ring_down=2,
            ring_up=2,
            group_id=66
        },
        {
            type=72,
            section_start=37,
            section_end=52,
            start_time=7,
            end_time=9,
            seq=32,
            ring_down=3,
            ring_up=3,
            exp=200
        },
        {
            type=73,
            section_start=37,
            section_end=52,
            start_time=7,
            end_time=9,
            seq=33,
            ring_down=4,
            ring_up=4,
            group_id=67
        },
        {
            type=74,
            section_start=37,
            section_end=52,
            start_time=7,
            end_time=9,
            seq=34,
            ring_down=5,
            ring_up=5,
            group_id=68
        },
        {
            type=75,
            section_start=37,
            section_end=52,
            start_time=7,
            end_time=9,
            seq=35,
            ring_down=6,
            ring_up=6,
            group_id=69
        },
        {
            type=76,
            section_start=37,
            section_end=52,
            start_time=7,
            end_time=9,
            seq=36,
            ring_down=7,
            ring_up=7,
            exp=200
        },
        {
            type=77,
            section_start=37,
            section_end=52,
            start_time=7,
            end_time=9,
            seq=37,
            ring_down=8,
            ring_up=8,
            group_id=70
        },
        {
            type=78,
            section_start=37,
            section_end=52,
            start_time=7,
            end_time=9,
            seq=38,
            ring_down=9,
            ring_up=9,
            group_id=71
        },
        {
            type=79,
            section_start=37,
            section_end=52,
            start_time=7,
            end_time=9,
            seq=39,
            ring_down=10,
            ring_up=10,
            group_id=72
        },
        {
            type=80,
            section_start=53,
            section_end=0,
            seq=40,
            group_id=33
        },
        {
            type=81,
            section_start=53,
            section_end=0,
            seq=41,
            ring_down=2,
            ring_up=2,
            group_id=34
        },
        {
            type=82,
            section_start=53,
            section_end=0,
            seq=42,
            ring_down=3,
            ring_up=3,
            exp=200
        },
        {
            type=83,
            section_start=53,
            section_end=0,
            seq=43,
            ring_down=4,
            ring_up=4,
            group_id=35
        },
        {
            type=84,
            section_start=53,
            section_end=0,
            seq=44,
            ring_down=5,
            ring_up=5,
            group_id=36
        },
        {
            type=85,
            section_start=53,
            section_end=0,
            seq=45,
            ring_down=6,
            ring_up=6,
            group_id=37
        },
        {
            type=86,
            section_start=53,
            section_end=0,
            seq=46,
            ring_down=7,
            ring_up=7,
            exp=200
        },
        {
            type=87,
            section_start=53,
            section_end=0,
            seq=47,
            ring_down=8,
            ring_up=8,
            group_id=38
        },
        {
            type=88,
            section_start=53,
            section_end=0,
            seq=48,
            ring_down=9,
            ring_up=9,
            group_id=39
        },
        {
            type=89,
            section_start=53,
            section_end=0,
            seq=49,
            ring_down=10,
            ring_up=10,
            group_id=40
        },
        {
            type=90,
            section_start=53,
            section_end=0,
            start_time=7,
            end_time=9,
            seq=40,
            group_id=73
        },
        {
            type=91,
            section_start=53,
            section_end=0,
            start_time=7,
            end_time=9,
            seq=41,
            ring_down=2,
            ring_up=2,
            group_id=74
        },
        {
            type=92,
            section_start=53,
            section_end=0,
            start_time=7,
            end_time=9,
            seq=42,
            ring_down=3,
            ring_up=3,
            exp=200
        },
        {
            type=93,
            section_start=53,
            section_end=0,
            start_time=7,
            end_time=9,
            seq=43,
            ring_down=4,
            ring_up=4,
            group_id=75
        },
        {
            type=94,
            section_start=53,
            section_end=0,
            start_time=7,
            end_time=9,
            seq=44,
            ring_down=5,
            ring_up=5,
            group_id=76
        },
        {
            type=95,
            section_start=53,
            section_end=0,
            start_time=7,
            end_time=9,
            seq=45,
            ring_down=6,
            ring_up=6,
            group_id=77
        },
        {
            type=96,
            section_start=53,
            section_end=0,
            start_time=7,
            end_time=9,
            seq=46,
            ring_down=7,
            ring_up=7,
            exp=200
        },
        {
            type=97,
            section_start=53,
            section_end=0,
            start_time=7,
            end_time=9,
            seq=47,
            ring_down=8,
            ring_up=8,
            group_id=78
        },
        {
            type=98,
            section_start=53,
            section_end=0,
            start_time=7,
            end_time=9,
            seq=48,
            ring_down=9,
            ring_up=9,
            group_id=79
        },
        {
            type=99,
            section_start=53,
            section_end=0,
            start_time=7,
            end_time=9,
            seq=49,
            ring_down=10,
            ring_up=10,
            group_id=80
        }
    },
    reward_group={
        {
            group_id=1,
            reward_item={
                [0]=_itemlist.i_27575_1_1
            }
        },
        {
            group_id=2,
            reward_item={
                [0]=_itemlist.i_26393_10_1
            }
        },
        {
            group_id=3,
            reward_item={
                [0]=_itemlist.i_22007_20_1
            }
        },
        {
            group_id=4,
            reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            group_id=5,
            reward_item={
                [0]=_itemlist.i_26393_10_1
            }
        },
        {
            group_id=6,
            reward_item={
                [0]=_itemlist.i_22007_20_1
            }
        },
        {
            group_id=7,
            reward_item={
                [0]=_itemlist.i_27575_1_1
            }
        },
        {
            group_id=8,
            reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            group_id=9,
            reward_item={
                [0]=_itemlist.i_27575_1_1
            }
        },
        {
            group_id=10,
            reward_item={
                [0]=_itemlist.i_26394_10_1
            }
        },
        {
            group_id=11,
            reward_item={
                [0]=_itemlist.i_22007_30_1
            }
        },
        {
            group_id=12,
            reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            group_id=13,
            reward_item={
                [0]=_itemlist.i_26394_10_1
            }
        },
        {
            group_id=14,
            reward_item={
                [0]=_itemlist.i_22007_30_1
            }
        },
        {
            group_id=15,
            reward_item={
                [0]=_itemlist.i_27575_1_1
            }
        },
        {
            group_id=16,
            reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            group_id=17,
            reward_item={
                [0]=_itemlist.i_27575_1_1
            }
        },
        {
            group_id=18,
            reward_item={
                [0]=_itemlist.i_26394_15_1
            }
        },
        {
            group_id=19,
            reward_item={
                [0]=_itemlist.i_22007_30_1
            }
        },
        {
            group_id=20,
            reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            group_id=21,
            reward_item={
                [0]=_itemlist.i_26394_15_1
            }
        },
        {
            group_id=22,
            reward_item={
                [0]=_itemlist.i_22007_30_1
            }
        },
        {
            group_id=23,
            reward_item={
                [0]=_itemlist.i_27575_1_1
            }
        },
        {
            group_id=24,
            reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            group_id=25,
            reward_item={
                [0]=_itemlist.i_27575_1_1
            }
        },
        {
            group_id=26,
            reward_item={
                [0]=_itemlist.i_26394_20_1
            }
        },
        {
            group_id=27,
            reward_item={
                [0]=_itemlist.i_22007_30_1
            }
        },
        {
            group_id=28,
            reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            group_id=29,
            reward_item={
                [0]=_itemlist.i_26394_20_1
            }
        },
        {
            group_id=30,
            reward_item={
                [0]=_itemlist.i_22007_30_1
            }
        },
        {
            group_id=31,
            reward_item={
                [0]=_itemlist.i_27575_1_1
            }
        },
        {
            group_id=32,
            reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            group_id=33,
            reward_item={
                [0]=_itemlist.i_27575_1_1
            }
        },
        {
            group_id=34,
            reward_item={
                [0]=_itemlist.i_26394_20_1
            }
        },
        {
            group_id=35,
            reward_item={
                [0]=_itemlist.i_22007_30_1
            }
        },
        {
            group_id=36,
            reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            group_id=37,
            reward_item={
                [0]=_itemlist.i_26394_20_1
            }
        },
        {
            group_id=38,
            reward_item={
                [0]=_itemlist.i_22007_30_1
            }
        },
        {
            group_id=39,
            reward_item={
                [0]=_itemlist.i_27575_1_1
            }
        },
        {
            group_id=40,
            reward_item={
                [0]=_itemlist.i_26349_1_1
            }
        },
        {
            group_id=41,
            reward_item={
                [0]=_itemlist.i_29088_10_1
            }
        },
        {
            group_id=42,
            reward_item={
                [0]=_itemlist.i_26393_10_1
            }
        },
        {
            group_id=43,
            reward_item={
                [0]=_itemlist.i_22007_20_1
            }
        },
        {
            group_id=44,
            reward_item={
                [0]=_itemlist.i_29088_10_1
            }
        },
        {
            group_id=45,
            reward_item={
                [0]=_itemlist.i_26393_10_1
            }
        },
        {
            group_id=46,
            reward_item={
                [0]=_itemlist.i_22007_20_1
            }
        },
        {
            group_id=47,
            reward_item={
                [0]=_itemlist.i_27575_1_1
            }
        },
        {
            group_id=48,
            reward_item={
                [0]=_itemlist.i_29088_15_1
            }
        },
        {
            group_id=49,
            reward_item={
                [0]=_itemlist.i_29088_10_1
            }
        },
        {
            group_id=50,
            reward_item={
                [0]=_itemlist.i_26394_10_1
            }
        },
        {
            group_id=51,
            reward_item={
                [0]=_itemlist.i_22007_30_1
            }
        },
        {
            group_id=52,
            reward_item={
                [0]=_itemlist.i_29088_10_1
            }
        },
        {
            group_id=53,
            reward_item={
                [0]=_itemlist.i_26394_10_1
            }
        },
        {
            group_id=54,
            reward_item={
                [0]=_itemlist.i_22007_30_1
            }
        },
        {
            group_id=55,
            reward_item={
                [0]=_itemlist.i_27575_1_1
            }
        },
        {
            group_id=56,
            reward_item={
                [0]=_itemlist.i_29088_15_1
            }
        },
        {
            group_id=57,
            reward_item={
                [0]=_itemlist.i_29088_10_1
            }
        },
        {
            group_id=58,
            reward_item={
                [0]=_itemlist.i_26394_15_1
            }
        },
        {
            group_id=59,
            reward_item={
                [0]=_itemlist.i_22007_30_1
            }
        },
        {
            group_id=60,
            reward_item={
                [0]=_itemlist.i_29088_10_1
            }
        },
        {
            group_id=61,
            reward_item={
                [0]=_itemlist.i_26394_15_1
            }
        },
        {
            group_id=62,
            reward_item={
                [0]=_itemlist.i_22007_30_1
            }
        },
        {
            group_id=63,
            reward_item={
                [0]=_itemlist.i_27575_1_1
            }
        },
        {
            group_id=64,
            reward_item={
                [0]=_itemlist.i_29088_15_1
            }
        },
        {
            group_id=65,
            reward_item={
                [0]=_itemlist.i_29088_10_1
            }
        },
        {
            group_id=66,
            reward_item={
                [0]=_itemlist.i_26394_20_1
            }
        },
        {
            group_id=67,
            reward_item={
                [0]=_itemlist.i_22007_30_1
            }
        },
        {
            group_id=68,
            reward_item={
                [0]=_itemlist.i_29088_10_1
            }
        },
        {
            group_id=69,
            reward_item={
                [0]=_itemlist.i_26394_20_1
            }
        },
        {
            group_id=70,
            reward_item={
                [0]=_itemlist.i_22007_30_1
            }
        },
        {
            group_id=71,
            reward_item={
                [0]=_itemlist.i_27575_1_1
            }
        },
        {
            group_id=72,
            reward_item={
                [0]=_itemlist.i_29088_15_1
            }
        },
        {
            group_id=73,
            reward_item={
                [0]=_itemlist.i_29088_10_1
            }
        },
        {
            group_id=74,
            reward_item={
                [0]=_itemlist.i_26394_20_1
            }
        },
        {
            group_id=75,
            reward_item={
                [0]=_itemlist.i_22007_30_1
            }
        },
        {
            group_id=76,
            reward_item={
                [0]=_itemlist.i_29088_10_1
            }
        },
        {
            group_id=77,
            reward_item={
                [0]=_itemlist.i_26394_20_1
            }
        },
        {
            group_id=78,
            reward_item={
                [0]=_itemlist.i_22007_30_1
            }
        },
        {
            group_id=79,
            reward_item={
                [0]=_itemlist.i_27575_1_1
            }
        },
        {
            group_id=80,
            reward_item={
                [0]=_itemlist.i_29088_15_1
            }
        }
    },
    task_list={
        {
            task_id=1,
            task_type=0,
            param_2=0,
            accept_npc=0,
            commit_npc=549,
            accept_talk_id=0,
            commit_talk_id=0,
            task_name="山海缘起",
            progress_desc="前往玄都吴盛处接取[山海缘起]任务",
            obj_desc="前往玄都<color=#91db64>吴盛</color>处接取任务"
        },
        {
            task_id=2,
            task_type=1,
            param_2=0,
            accept_npc=549,
            accept_talk_id=90000,
            commit_talk_id=90001,
            task_name="交谈",
            progress_desc="吴盛似乎有事想请你帮忙，你去问问他吧",
            obj_desc="与<color=#91db64>吴伯</color>交谈"
        },
        {
            task_id=3,
            param_1=27981,
            accept_npc=590,
            accept_talk_id=90002,
            commit_talk_id=90003,
            progress_desc="吴伯需要一些凤尾草，你去问问是否需要帮忙吧",
            obj_desc="向<color=#91db64>吴伯</color>上交<color=#91db64>1棵凤尾草</color>"
        },
        {
            task_id=4,
            task_type=3,
            param_2=10,
            accept_npc=591,
            commit_npc=591,
            accept_talk_id=90004,
            commit_talk_id=90005,
            task_name="除妖",
            progress_desc="李娟似乎需要帮忙，你去李娟那儿问下吧"
        },
        {
            task_id=5,
            task_type=5,
            param_1=27095,
            accept_npc=89,
            commit_npc=516,
            accept_talk_id=90006,
            commit_talk_id=90007,
            task_name="代送",
            progress_desc="韩天需要你的帮忙，你快去找他吧",
            obj_desc="将<color=#91db68>弓</color>交给<color=#91db68>俞棣</color>"
        },
        {
            task_id=6,
            task_type=1,
            param_2=0,
            accept_npc=516,
            commit_npc=594,
            accept_talk_id=90008,
            commit_talk_id=90009,
            task_name="交谈",
            progress_desc="俞棣想让你去问问村里发生了什么事",
            obj_desc="与<color=#91db64>许隶</color>交谈"
        },
        {
            task_id=7,
            param_1=27859,
            accept_npc=594,
            commit_npc=695,
            accept_talk_id=90010,
            commit_talk_id=90011,
            progress_desc="许隶似乎有事情需要你帮忙，你去找找他",
            obj_desc="向<color=#91db64>渔夫</color>上交一条<color=#23cdf1>大头鱼</color>"
        },
        {
            task_id=8,
            param_1=27977,
            accept_npc=700,
            commit_npc=700,
            accept_talk_id=90012,
            commit_talk_id=90013,
            progress_desc="宛村村长夫人家好像缺一些冬笋，你去问问她",
            obj_desc="向<color=#91db64>宛村村长夫人</color>上交<color=#91db64>1份冬笋</color>"
        },
        {
            task_id=9,
            task_type=3,
            param_2=15,
            accept_npc=526,
            commit_npc=526,
            accept_talk_id=90014,
            commit_talk_id=90015,
            task_name="除妖",
            progress_desc="江燕正在找人消灭妖兽，你去找找她吧"
        },
        {
            task_id=10,
            task_type=5,
            param_1=26943,
            accept_npc=526,
            commit_npc=551,
            accept_talk_id=90016,
            commit_talk_id=90017,
            task_name="代送",
            progress_desc="江燕有封信不知道找谁送，你有空去看看吧",
            obj_desc="将<color=#91db68>信</color>交给<color=#91db68>欧阳飞羽</color>"
        },
        {
            task_id=11,
            param_1=27980,
            accept_npc=547,
            commit_npc=547,
            accept_talk_id=90018,
            commit_talk_id=90019,
            progress_desc="孔华在找一个材料，你去找他问问",
            obj_desc="向<color=#91db64>孔华</color>上交<color=#91db64>1份紫苏</color>"
        },
        {
            task_id=12,
            task_type=3,
            param_2=15,
            commit_npc=562,
            accept_talk_id=90020,
            commit_talk_id=90021,
            task_name="除妖",
            progress_desc="菲菲想请你帮个忙，你有空就去找菲菲吧"
        },
        {
            task_id=13,
            task_type=5,
            param_1=27982,
            commit_npc=524,
            accept_talk_id=90022,
            commit_talk_id=90023,
            task_name="代送",
            progress_desc="菲菲想送个极阳草给二娃，你去问问是否需要帮忙",
            obj_desc="向<color=#91db64>二娃</color>上交一颗<color=#23cdf1>极阳草</color>"
        },
        {
            task_id=14,
            task_type=5,
            param_1=27557,
            accept_npc=570,
            commit_npc=562,
            accept_talk_id=90024,
            commit_talk_id=90025,
            task_name="代送",
            progress_desc="孙尚似乎遇到了什么难题，你有空去找找他",
            obj_desc="将<color=#91db68>荷包</color>交给<color=#91db68>菲菲</color>"
        },
        {
            task_id=15,
            task_type=1,
            param_2=0,
            commit_npc=523,
            accept_talk_id=90026,
            commit_talk_id=90027,
            task_name="交谈",
            progress_desc="菲菲有事想托你帮忙，你去看看吧",
            obj_desc="与<color=#91db64>苏尚</color>交谈"
        },
        {
            task_id=16,
            param_1=26239,
            accept_npc=548,
            commit_npc=548,
            accept_talk_id=90028,
            commit_talk_id=90029,
            progress_desc="吕斌想找一个宝石，你遇到他就去问问吧",
            obj_desc="向<color=#91db64>吕斌</color>上交<color=#91db64>1颗1级赤玉</color>"
        },
        {
            task_id=17,
            task_type=3,
            param_2=15,
            accept_npc=581,
            commit_npc=581,
            accept_talk_id=90030,
            commit_talk_id=90031,
            task_name="除妖",
            progress_desc="孙老最近有点困扰，你去帮帮孙老吧"
        },
        {
            task_id=18,
            param_1=27985,
            accept_npc=88,
            commit_npc=88,
            accept_talk_id=90032,
            commit_talk_id=90033,
            progress_desc="韩羽有事想请你帮忙",
            obj_desc="向<color=#91db64>韩羽</color>上交一颗<color=#23cdf1>四象草</color>"
        },
        {
            task_id=19,
            task_type=5,
            param_1=27524,
            accept_npc=516,
            commit_npc=127,
            accept_talk_id=90034,
            commit_talk_id=90035,
            task_name="代送",
            progress_desc="俞棣想让你帮他送批货",
            obj_desc="将<color=#91db68>货物</color>交给<color=#91db68>柳芳</color>"
        },
        {
            task_id=20,
            task_type=1,
            param_2=0,
            accept_npc=127,
            commit_npc=618,
            accept_talk_id=90036,
            commit_talk_id=90037,
            task_name="交谈",
            progress_desc="柳芳有事想麻烦你",
            obj_desc="与<color=#91db64>秦林</color>交谈"
        },
        {
            task_id=21,
            param_1=26061,
            accept_npc=618,
            commit_npc=620,
            accept_talk_id=90038,
            commit_talk_id=90039,
            progress_desc="秦林似乎有事找你",
            obj_desc="向<color=#91db64>魏泓</color>上交<color=#91db64>1枚小钥匙</color>",
            get_way=315
        },
        {
            task_id=22,
            task_type=3,
            param_2=10,
            accept_npc=620,
            commit_npc=620,
            accept_talk_id=90040,
            commit_talk_id=90041,
            task_name="除妖",
            progress_desc="魏泓有事相托",
            obj_desc="教训<color=#91db64>妖兽</color>"
        },
        {
            task_id=23,
            param_1=27976,
            accept_npc=617,
            commit_npc=617,
            accept_talk_id=90042,
            commit_talk_id=90043,
            progress_desc="姚生想麻烦你一件事，你去找他问问吧",
            obj_desc="向<color=#91db64>姚生</color>上交一份<color=#23cdf1>豆荚</color>"
        },
        {
            task_id=24,
            task_type=5,
            param_1=27521,
            accept_npc=15027,
            commit_npc=524,
            accept_talk_id=90044,
            commit_talk_id=90045,
            task_name="代送",
            progress_desc="月娘想让你帮忙送点东西",
            obj_desc="将<color=#91db68>笔墨纸砚</color>交给<color=#91db68>二娃</color>"
        },
        {
            task_id=25,
            task_type=1,
            param_2=0,
            accept_npc=592,
            commit_npc=593,
            accept_talk_id=90046,
            commit_talk_id=90047,
            task_name="交谈",
            progress_desc="渔夫找你有点事儿",
            obj_desc="与<color=#91db64>船夫</color>交谈"
        },
        {
            task_id=26,
            param_1=27979,
            accept_npc=582,
            commit_npc=582,
            accept_talk_id=90048,
            commit_talk_id=90049,
            progress_desc="云子媛最近好像遇到了点难事，你去看看吧",
            obj_desc="向<color=#91db64>云子媛</color>上交<color=#91db64>1份龙井茶</color>"
        },
        {
            task_id=27,
            task_type=3,
            param_2=15,
            accept_npc=584,
            commit_npc=584,
            accept_talk_id=90050,
            commit_talk_id=90051,
            task_name="除妖",
            progress_desc="周羽想拜托你一点事儿",
            obj_desc="教训<color=#91db64>妖兽</color>"
        },
        {
            task_id=28,
            task_type=5,
            param_1=27978,
            accept_npc=526,
            commit_npc=527,
            accept_talk_id=90052,
            commit_talk_id=90053,
            task_name="代送",
            progress_desc="江燕似乎想找你帮个忙",
            obj_desc="向<color=#91db64>娜娜</color>上交一份<color=#23cdf1>辣椒</color>"
        },
        {
            task_id=29,
            task_type=5,
            param_1=27532,
            accept_npc=601,
            commit_npc=599,
            accept_talk_id=90054,
            commit_talk_id=90055,
            task_name="代送",
            progress_desc="夏小柔想请你帮个忙",
            obj_desc="将<color=#91db68>玉瓶</color>交给<color=#91db68>陆天熊</color>"
        },
        {
            task_id=30,
            param_1=27983,
            accept_npc=602,
            commit_npc=602,
            accept_talk_id=90056,
            commit_talk_id=90057,
            progress_desc="宁月有事儿找你",
            obj_desc="向<color=#91db64>宁月</color>上交<color=#91db64>1颗金虹草</color>"
        },
        {
            task_id=31,
            task_type=3,
            param_2=10,
            accept_npc=602,
            commit_npc=602,
            accept_talk_id=90058,
            commit_talk_id=90059,
            task_name="除妖",
            progress_desc="宁月想拜托你一点事儿",
            obj_desc="教训<color=#91db64>妖兽</color>"
        },
        {
            task_id=32,
            task_type=5,
            param_1=27534,
            accept_npc=586,
            commit_npc=15027,
            accept_talk_id=90060,
            commit_talk_id=90061,
            task_name="代送",
            progress_desc="王一想让你帮他送个东西，你有空去找他吧",
            obj_desc="将<color=#91db68>鲜茶</color>交给<color=#91db68>月娘</color>"
        }
    },
    task_prefix={
        {
            type=0,
            show_item={
                [0]=_itemlist.i_27575_1_1,
                [1]=_itemlist.i_26349_1_1,
                [2]=_itemlist.i_22007_1_1,
                [3]=_itemlist.i_65535_1_1
            }
        },
        {
            type=1,
            start_time=4,
            end_time=6,
            task_prefix_1="",
            task_prefix_2="",
            story_title=0,
            desc=0
        },
        {
            type=2,
            start_time=7,
            end_time=9,
            task_prefix_1="山海缘起·贰",
            task_prefix_2="缘起·贰",
            story_title="故事·贰",
            show_item={
                [0]=_itemlist.i_29088_1_1,
                [1]=_itemlist.i_26393_1_1,
                [2]=_itemlist.i_22007_1_1,
                [3]=_itemlist.i_65535_1_1
            }
        },
        {
            type=3,
            section_start=8,
            section_end=21,
            show_item={
                [0]=_itemlist.i_27575_1_1,
                [1]=_itemlist.i_26349_1_1,
                [2]=_itemlist.i_22007_1_1,
                [3]=_itemlist.i_65535_1_1
            }
        },
        {
            type=4,
            section_start=8,
            section_end=21,
            start_time=4,
            end_time=6,
            task_prefix_1="",
            task_prefix_2="",
            story_title=0,
            desc=0
        },
        {
            type=5,
            section_start=8,
            section_end=21,
            start_time=7,
            end_time=9,
            task_prefix_1="山海缘起·贰",
            task_prefix_2="缘起·贰",
            story_title="故事·贰",
            show_item={
                [0]=_itemlist.i_29088_1_1,
                [1]=_itemlist.i_26394_1_1,
                [2]=_itemlist.i_22007_1_1,
                [3]=_itemlist.i_65535_1_1
            }
        },
        {
            section_start=22,
            section_end=36,
            show_item={
                [0]=_itemlist.i_27575_1_1,
                [1]=_itemlist.i_26349_1_1,
                [2]=_itemlist.i_22007_1_1,
                [3]=_itemlist.i_65535_1_1
            }
        },
        {
            type=7,
            section_start=22,
            section_end=36,
            start_time=4,
            end_time=6,
            task_prefix_1="",
            task_prefix_2="",
            story_title=0,
            desc=0
        },
        {
            type=8,
            section_start=22,
            section_end=36,
            start_time=7,
            end_time=9,
            task_prefix_1="山海缘起·贰",
            task_prefix_2="缘起·贰",
            story_title="故事·贰",
            show_item={
                [0]=_itemlist.i_29088_1_1,
                [1]=_itemlist.i_26394_1_1,
                [2]=_itemlist.i_22007_1_1,
                [3]=_itemlist.i_65535_1_1
            }
        },
        {
            section_start=37,
            section_end=52,
            show_item={
                [0]=_itemlist.i_27575_1_1,
                [1]=_itemlist.i_26349_1_1,
                [2]=_itemlist.i_22007_1_1,
                [3]=_itemlist.i_65535_1_1
            }
        },
        {
            type=7,
            section_start=37,
            section_end=52,
            start_time=4,
            end_time=6,
            task_prefix_1="",
            task_prefix_2="",
            story_title=0,
            desc=0
        },
        {
            type=8,
            section_start=37,
            section_end=52,
            start_time=7,
            end_time=9,
            task_prefix_1="山海缘起·贰",
            task_prefix_2="缘起·贰",
            story_title="故事·贰",
            show_item={
                [0]=_itemlist.i_29088_1_1,
                [1]=_itemlist.i_26394_1_1,
                [2]=_itemlist.i_22007_1_1,
                [3]=_itemlist.i_65535_1_1
            }
        },
        {
            section_start=53,
            section_end=0,
            show_item={
                [0]=_itemlist.i_27575_1_1,
                [1]=_itemlist.i_26349_1_1,
                [2]=_itemlist.i_22007_1_1,
                [3]=_itemlist.i_65535_1_1
            }
        },
        {
            type=7,
            section_start=53,
            section_end=0,
            start_time=4,
            end_time=6,
            task_prefix_1="",
            task_prefix_2="",
            story_title=0,
            desc=0
        },
        {
            type=8,
            section_start=53,
            section_end=0,
            start_time=7,
            end_time=9,
            task_prefix_1="山海缘起·贰",
            task_prefix_2="缘起·贰",
            story_title="故事·贰",
            show_item={
                [0]=_itemlist.i_29088_1_1,
                [1]=_itemlist.i_26394_1_1,
                [2]=_itemlist.i_22007_1_1,
                [3]=_itemlist.i_65535_1_1
            }
        }
    },
    other={
        {
            ring_up=10,
            space_times=4,
            show_item={
                [0]=_itemlist.i_26813_1_1,
                [1]=_itemlist.i_29038_2_1,
                [2]=_itemlist.i_26073_1_1
            },
            level_open=32
        }
    }
}
SetConfigDefaultVal(Config.shanhai_origin_auto,_default_val,nil,nil,nil)