local _default_val={
    basis_configuration={
        section_start=1,
        section_end=0,
        task_type=2,
        task_param=3,
        param_2=0
    },
    lantern_configuration={
        score=0,
        speed_multiple=0,
        speed_time=0,
        scope_expand=0,
        scope_expand_time=0,
        rate=200
    }
}
local _itemlist={
    i_27402_1_1={
        item_id=27402,
        num=1,
        is_bind=1
    },
    i_26349_1_1={
        item_id=26349,
        num=1,
        is_bind=1
    },
    i_26349_2_1={
        item_id=26349,
        num=2,
        is_bind=1
    }
}
Config.shanhaihuadeng_auto={
    basis_configuration={
        {
            type=0,
            task_id=1,
            task_type=1,
            task_param=1,
            param_1=50,
            task_desc="单次获得50分",
            reward_item=_itemlist.i_27402_1_1
        },
        {
            type=1,
            task_id=2,
            task_type=1,
            task_param=1,
            param_1=70,
            task_desc="单次获得70分",
            reward_item=_itemlist.i_26349_1_1
        },
        {
            type=2,
            task_id=3,
            task_type=1,
            param_1=2,
            task_desc="参与2次多彩花灯",
            reward_item=_itemlist.i_26349_1_1
        },
        {
            type=3,
            task_id=4,
            task_param=2,
            param_1=300,
            task_desc="累计获得300分",
            reward_item=_itemlist.i_26349_1_1
        },
        {
            type=4,
            task_id=5,
            task_param=2,
            param_1=600,
            task_desc="累计获得600分",
            reward_item=_itemlist.i_26349_2_1
        },
        {
            type=5,
            task_id=6,
            param_1=5,
            task_desc="累计参与5次多彩花灯",
            reward_item=_itemlist.i_26349_1_1
        },
        {
            type=6,
            task_id=7,
            param_1=8,
            task_desc="累计参与8次多彩花灯",
            reward_item=_itemlist.i_26349_2_1
        }
    },
    lantern_configuration={
        {
            type=0,
            score=1
        },
        {
            type=1,
            score=2
        },
        {
            type=2,
            score=3
        },
        {
            type=3,
            score=5
        },
        {
            type=4,
            speed_multiple=2,
            speed_time=5,
            rate=100
        },
        {
            type=5,
            scope_expand=1.5,
            scope_expand_time=6,
            rate=100
        }
    },
    other={
        {
            refresh_time=3,
            refresh_num_down=2,
            refresh_num_up=4,
            game_time=60,
            day_times=3
        }
    }
}
SetConfigDefaultVal(Config.shanhaihuadeng_auto,_default_val,nil,nil,nil)