local _default_val={
    box_configure={
        section_start=2,
        section_end=3,
        seq=0,
        item_id=115,
        reward_num=3,
        limit_type=2,
        buy_times=0,
        today_times=3,
        buy_money=1980,
        gift_des="魂器绘卷宝箱",
        gift_icon=1,
        gift_name="返利\n199%"
    },
    reward_pool={
        type=0,
        item_id=1
    }
}
local _itemlist={
    i_9000_1_1={
        item_id=9000,
        num=1,
        is_bind=1
    },
    i_27399_5_1={
        item_id=27399,
        num=5,
        is_bind=1
    },
    i_24557_1_1={
        item_id=24557,
        num=1,
        is_bind=1
    },
    i_26813_1_1={
        item_id=26813,
        num=1,
        is_bind=1
    },
    i_26813_3_1={
        item_id=26813,
        num=3,
        is_bind=1
    },
    i_27399_6_1={
        item_id=27399,
        num=6,
        is_bind=1
    },
    i_27403_1_1={
        item_id=27403,
        num=1,
        is_bind=1
    },
    i_26812_3_1={
        item_id=26812,
        num=3,
        is_bind=1
    },
    i_29091_50_1={
        item_id=29091,
        num=50,
        is_bind=1
    },
    i_27403_2_1={
        item_id=27403,
        num=2,
        is_bind=1
    },
    i_27402_3_1={
        item_id=27402,
        num=3,
        is_bind=1
    },
    i_27575_5_1={
        item_id=27575,
        num=5,
        is_bind=1
    },
    i_9012_1_1={
        item_id=9012,
        num=1,
        is_bind=1
    },
    i_26443_5_1={
        item_id=26443,
        num=5,
        is_bind=1
    },
    i_27399_9_1={
        item_id=27399,
        num=9,
        is_bind=1
    },
    i_25520_3_1={
        item_id=25520,
        num=3,
        is_bind=1
    },
    i_24557_5_1={
        item_id=24557,
        num=5,
        is_bind=1
    },
    i_27399_12_1={
        item_id=27399,
        num=12,
        is_bind=1
    },
    i_27494_15_1={
        item_id=27494,
        num=15,
        is_bind=1
    },
    i_29040_2_1={
        item_id=29040,
        num=2,
        is_bind=1
    },
    i_26224_5_1={
        item_id=26224,
        num=5,
        is_bind=1
    },
    i_22099_1_1={
        item_id=22099,
        num=1,
        is_bind=1
    },
    i_24557_2_1={
        item_id=24557,
        num=2,
        is_bind=1
    },
    i_25566_1_1={
        item_id=25566,
        num=1,
        is_bind=1
    },
    i_27399_21_1={
        item_id=27399,
        num=21,
        is_bind=1
    },
    i_25520_1_1={
        item_id=25520,
        num=1,
        is_bind=1
    },
    i_25607_1_1={
        item_id=25607,
        num=1,
        is_bind=1
    },
    i_28097_1_1={
        item_id=28097,
        num=1,
        is_bind=1
    },
    i_27187_45_1={
        item_id=27187,
        num=45,
        is_bind=1
    },
    i_27479_50_1={
        item_id=27479,
        num=50,
        is_bind=1
    },
    i_9003_1_1={
        item_id=9003,
        num=1,
        is_bind=1
    },
    i_27399_3_1={
        item_id=27399,
        num=3,
        is_bind=1
    },
    i_26813_4_1={
        item_id=26813,
        num=4,
        is_bind=1
    },
    i_28771_1_1={
        item_id=28771,
        num=1,
        is_bind=1
    },
    i_27403_5_1={
        item_id=27403,
        num=5,
        is_bind=1
    },
    i_27541_6_1={
        item_id=27541,
        num=6,
        is_bind=1
    },
    i_29021_10_1={
        item_id=29021,
        num=10,
        is_bind=1
    },
    i_27540_2_1={
        item_id=27540,
        num=2,
        is_bind=1
    },
    i_25657_1_1={
        item_id=25657,
        num=1,
        is_bind=1
    },
    i_27478_500_1={
        item_id=27478,
        num=500,
        is_bind=1
    },
    i_25506_1_1={
        item_id=25506,
        num=1,
        is_bind=1
    },
    i_22014_15_1={
        item_id=22014,
        num=15,
        is_bind=1
    },
    i_28311_1_1={
        item_id=28311,
        num=1,
        is_bind=1
    },
    i_26444_2_1={
        item_id=26444,
        num=2,
        is_bind=1
    },
    i_9001_1_1={
        item_id=9001,
        num=1,
        is_bind=1
    },
    i_27479_10_1={
        item_id=27479,
        num=10,
        is_bind=1
    },
    i_27723_2_1={
        item_id=27723,
        num=2,
        is_bind=1
    },
    i_27656_1_1={
        item_id=27656,
        num=1,
        is_bind=1
    },
    i_27655_2_1={
        item_id=27655,
        num=2,
        is_bind=1
    },
    i_27664_2_1={
        item_id=27664,
        num=2,
        is_bind=1
    },
    i_29021_15_1={
        item_id=29021,
        num=15,
        is_bind=1
    },
    i_27541_1_1={
        item_id=27541,
        num=1,
        is_bind=1
    },
    i_27665_6_1={
        item_id=27665,
        num=6,
        is_bind=1
    },
    i_27664_3_1={
        item_id=27664,
        num=3,
        is_bind=1
    },
    i_27655_3_1={
        item_id=27655,
        num=3,
        is_bind=1
    },
    i_28762_2_1={
        item_id=28762,
        num=2,
        is_bind=1
    },
    i_28722_3_1={
        item_id=28722,
        num=3,
        is_bind=1
    },
    i_29120_5_1={
        item_id=29120,
        num=5,
        is_bind=1
    },
    i_27403_3_1={
        item_id=27403,
        num=3,
        is_bind=1
    },
    i_27723_18_1={
        item_id=27723,
        num=18,
        is_bind=1
    },
    i_27657_3_1={
        item_id=27657,
        num=3,
        is_bind=1
    },
    i_27656_5_1={
        item_id=27656,
        num=5,
        is_bind=1
    },
    i_27665_3_1={
        item_id=27665,
        num=3,
        is_bind=1
    },
    i_27187_50_1={
        item_id=27187,
        num=50,
        is_bind=1
    },
    i_27479_40_1={
        item_id=27479,
        num=40,
        is_bind=1
    },
    i_9002_1_1={
        item_id=9002,
        num=1,
        is_bind=1
    },
    i_26813_2_1={
        item_id=26813,
        num=2,
        is_bind=1
    },
    i_27541_4_1={
        item_id=27541,
        num=4,
        is_bind=1
    },
    i_29021_5_1={
        item_id=29021,
        num=5,
        is_bind=1
    },
    i_27665_5_1={
        item_id=27665,
        num=5,
        is_bind=1
    },
    i_27479_30_1={
        item_id=27479,
        num=30,
        is_bind=1
    },
    i_27723_12_1={
        item_id=27723,
        num=12,
        is_bind=1
    },
    i_27656_2_1={
        item_id=27656,
        num=2,
        is_bind=1
    },
    i_27655_5_1={
        item_id=27655,
        num=5,
        is_bind=1
    },
    i_27665_1_1={
        item_id=27665,
        num=1,
        is_bind=1
    },
    i_27187_35_1={
        item_id=27187,
        num=35,
        is_bind=1
    },
    i_25689_1_1={
        item_id=25689,
        num=1,
        is_bind=1
    },
    i_28658_1_1={
        item_id=28658,
        num=1,
        is_bind=1
    },
    i_28773_1_1={
        item_id=28773,
        num=1,
        is_bind=1
    },
    i_25688_1_1={
        item_id=25688,
        num=1,
        is_bind=1
    },
    i_27671_2_1={
        item_id=27671,
        num=2,
        is_bind=1
    },
    i_27672_1_1={
        item_id=27672,
        num=1,
        is_bind=1
    },
    i_22014_20_1={
        item_id=22014,
        num=20,
        is_bind=1
    },
    i_27479_35_1={
        item_id=27479,
        num=35,
        is_bind=1
    },
    i_27187_38_1={
        item_id=27187,
        num=38,
        is_bind=1
    },
    i_28772_1_1={
        item_id=28772,
        num=1,
        is_bind=1
    },
    i_27671_3_1={
        item_id=27671,
        num=3,
        is_bind=1
    },
    i_27541_5_1={
        item_id=27541,
        num=5,
        is_bind=1
    },
    i_27723_7_1={
        item_id=27723,
        num=7,
        is_bind=1
    },
    i_27187_25_1={
        item_id=27187,
        num=25,
        is_bind=1
    },
    i_26416_32_1={
        item_id=26416,
        num=32,
        is_bind=1
    },
    i_27665_7_1={
        item_id=27665,
        num=7,
        is_bind=1
    },
    i_27723_8_1={
        item_id=27723,
        num=8,
        is_bind=1
    },
    i_27187_28_1={
        item_id=27187,
        num=28,
        is_bind=1
    },
    i_26416_33_1={
        item_id=26416,
        num=33,
        is_bind=1
    },
    i_25688_2_1={
        item_id=25688,
        num=2,
        is_bind=1
    },
    i_27671_5_1={
        item_id=27671,
        num=5,
        is_bind=1
    },
    i_27672_2_1={
        item_id=27672,
        num=2,
        is_bind=1
    },
    i_22014_30_1={
        item_id=22014,
        num=30,
        is_bind=1
    },
    i_27723_9_1={
        item_id=27723,
        num=9,
        is_bind=1
    },
    i_27187_32_1={
        item_id=27187,
        num=32,
        is_bind=1
    },
    i_29106_2_1={
        item_id=29106,
        num=2,
        is_bind=1
    },
    i_29121_3_1={
        item_id=29121,
        num=3,
        is_bind=1
    },
    i_28721_5_1={
        item_id=28721,
        num=5,
        is_bind=1
    },
    i_29120_4_1={
        item_id=29120,
        num=4,
        is_bind=1
    },
    i_26416_35_1={
        item_id=26416,
        num=35,
        is_bind=1
    },
    i_27723_15_1={
        item_id=27723,
        num=15,
        is_bind=1
    },
    i_26416_22_1={
        item_id=26416,
        num=22,
        is_bind=1
    },
    i_26688_50_1={
        item_id=26688,
        num=50,
        is_bind=1
    },
    i_26687_10_1={
        item_id=26687,
        num=10,
        is_bind=1
    },
    i_26773_10_1={
        item_id=26773,
        num=10,
        is_bind=1
    },
    i_26689_30_1={
        item_id=26689,
        num=30,
        is_bind=1
    },
    i_26416_25_1={
        item_id=26416,
        num=25,
        is_bind=1
    },
    i_29021_12_1={
        item_id=29021,
        num=12,
        is_bind=1
    },
    i_26416_27_1={
        item_id=26416,
        num=27,
        is_bind=1
    },
    i_27187_30_1={
        item_id=27187,
        num=30,
        is_bind=1
    },
    i_26416_30_1={
        item_id=26416,
        num=30,
        is_bind=1
    },
    i_27666_500_1={
        item_id=27666,
        num=500,
        is_bind=1
    },
    i_27672_3_1={
        item_id=27672,
        num=3,
        is_bind=1
    },
    i_28947_1_1={
        item_id=28947,
        num=1,
        is_bind=1
    },
    i_22007_300_1={
        item_id=22007,
        num=300,
        is_bind=1
    },
    i_28926_1_1={
        item_id=28926,
        num=1,
        is_bind=1
    },
    i_28909_1_1={
        item_id=28909,
        num=1,
        is_bind=1
    },
    i_28903_1_1={
        item_id=28903,
        num=1,
        is_bind=1
    },
    i_31407_1_1={
        item_id=31407,
        num=1,
        is_bind=1
    },
    i_22006_1_1={
        item_id=22006,
        num=1,
        is_bind=1
    }
}
Config.sijibaoxiang_auto={
    box_configure={
        {
            type=0,
            section_start=1,
            section_end=1,
            item_id=1,
            today_times=2,
            buy_money=60,
            gift_des="福利宝箱",
            gift_icon=2
        },
        {
            type=1,
            section_start=1,
            section_end=1,
            seq=1,
            item_id=2,
            buy_money=300,
            gift_des="唤灵秘钥宝箱",
            gift_icon=2,
            gift_name="返利\n218%"
        },
        {
            type=2,
            section_start=1,
            section_end=1,
            seq=2,
            item_id=3,
            buy_money=500,
            gift_des="紫品伙伴宝箱",
            gift_icon=2,
            gift_name="返利\n336%"
        },
        {
            type=3,
            section_start=1,
            section_end=1,
            seq=3,
            item_id=4,
            buy_money=980,
            gift_des="紫玉徽章宝箱",
            gift_icon=3,
            gift_name="返利\n268%"
        },
        {
            type=4,
            section_start=1,
            section_end=1,
            seq=4,
            item_id=5,
            buy_money=1280,
            gift_des="高阶技能书宝箱",
            gift_icon=3,
            gift_name="返利\n319%"
        },
        {
            type=5,
            section_start=1,
            section_end=1,
            seq=5,
            item_id=6,
            today_times=5,
            gift_des="神装材料宝箱",
            gift_icon=3,
            gift_name="返利\n288%"
        },
        {
            type=6,
            section_start=1,
            section_end=1,
            seq=6,
            item_id=7,
            buy_money=3280,
            gift_des="高阶技能书宝箱",
            gift_name="返利\n398%"
        },
        {
            type=7,
            section_start=1,
            section_end=1,
            seq=7,
            item_id=8,
            buy_money=4880,
            gift_des="稀有宠宝箱",
            gift_name="返利\n379%"
        },
        {
            type=8,
            section_start=1,
            section_end=1,
            seq=8,
            item_id=9,
            buy_money=6480,
            gift_des="神兽之魂宝箱",
            gift_name="返利\n468%"
        },
        {
            type=9,
            item_id=10,
            today_times=2,
            buy_money=60,
            gift_des="福利宝箱",
            gift_icon=2
        },
        {
            type=10,
            seq=1,
            item_id=11,
            buy_money=300,
            gift_des="唤灵秘钥宝箱",
            gift_icon=2,
            gift_name="返利\n218%"
        },
        {
            type=11,
            seq=2,
            item_id=12,
            buy_money=500,
            gift_des="伙伴元神宝箱",
            gift_icon=2,
            gift_name="返利\n336%"
        },
        {
            type=12,
            seq=3,
            item_id=13,
            buy_money=980,
            gift_des="缚宠金绳宝箱",
            gift_icon=3,
            gift_name="返利\n268%"
        },
        {
            type=13,
            seq=4,
            item_id=14,
            buy_money=1280,
            gift_des="令牌(+10-15)宝箱",
            gift_icon=3,
            gift_name="返利\n319%"
        },
        {
            type=14,
            seq=5,
            item_id=113,
            limit_type=1,
            buy_times=1,
            today_times=0,
            gift_des="伙伴皮肤宝箱",
            gift_icon=3
        },
        {
            type=15,
            seq=6,
            item_id=15,
            today_times=5,
            gift_des="神装材料宝箱",
            gift_name="返利\n288%"
        },
        {
            type=16,
            seq=7,
            item_id=16,
            buy_money=3280,
            gift_des="稀有宠宝箱",
            gift_name="返利\n398%"
        },
        {
            type=17,
            seq=8,
            item_id=17,
            buy_money=4880,
            gift_des="橙玉徽章宝箱",
            gift_name="返利\n379%"
        },
        {
            type=18,
            seq=9,
            item_id=18,
            buy_money=6480,
            gift_des="神兽之魂宝箱",
            gift_name="返利\n468%"
        },
        {
            type=19,
            section_start=4,
            section_end=8,
            item_id=19,
            today_times=2,
            buy_money=60,
            gift_des="福利宝箱",
            gift_icon=2
        },
        {
            type=20,
            section_start=4,
            section_end=8,
            seq=1,
            item_id=20,
            buy_money=300,
            gift_icon=2,
            gift_name="返利\n218%"
        },
        {
            type=21,
            section_start=4,
            section_end=8,
            seq=2,
            item_id=21,
            buy_money=500,
            gift_des="稀有宠宝箱",
            gift_icon=2,
            gift_name="返利\n336%"
        },
        {
            type=22,
            section_start=4,
            section_end=8,
            seq=3,
            item_id=22,
            buy_money=980,
            gift_des="缚宠金绳宝箱",
            gift_icon=3,
            gift_name="返利\n268%"
        },
        {
            type=23,
            section_start=4,
            section_end=8,
            seq=4,
            item_id=114,
            limit_type=1,
            buy_times=1,
            today_times=0,
            gift_des="伙伴皮肤宝箱",
            gift_icon=3
        },
        {
            type=24,
            section_start=4,
            section_end=8,
            seq=5,
            item_id=23,
            buy_money=1280,
            gift_des="寻器符咒宝箱",
            gift_icon=3,
            gift_name="返利\n319%"
        },
        {
            type=25,
            section_start=4,
            section_end=8,
            seq=6,
            item_id=24,
            gift_des="伙伴元神宝箱",
            gift_name="返利\n288%"
        },
        {
            type=26,
            section_start=4,
            section_end=8,
            seq=7,
            item_id=25,
            buy_money=3280,
            gift_name="返利\n398%"
        },
        {
            type=27,
            section_start=4,
            section_end=8,
            seq=8,
            item_id=26,
            buy_money=6480,
            gift_des="神兽之魂宝箱",
            gift_name="返利\n468%"
        },
        {
            type=28,
            section_start=9,
            section_end=13,
            item_id=27,
            today_times=2,
            buy_money=60,
            gift_des="福利宝箱",
            gift_icon=2
        },
        {
            type=29,
            section_start=9,
            section_end=13,
            seq=1,
            item_id=28,
            buy_money=300,
            gift_icon=2,
            gift_name="返利\n218%"
        },
        {
            type=30,
            section_start=9,
            section_end=13,
            seq=2,
            item_id=29,
            buy_money=500,
            gift_des="缚宠金绳宝箱",
            gift_icon=2,
            gift_name="返利\n336%"
        },
        {
            type=31,
            section_start=9,
            section_end=13,
            seq=3,
            item_id=30,
            buy_money=980,
            gift_des="寻器符咒宝箱",
            gift_icon=3,
            gift_name="返利\n268%"
        },
        {
            type=32,
            section_start=9,
            section_end=13,
            seq=4,
            item_id=31,
            buy_money=1280,
            gift_des="宠物护符宝箱",
            gift_icon=3,
            gift_name="返利\n319%"
        },
        {
            type=33,
            section_start=9,
            section_end=13,
            seq=5,
            limit_type=1,
            buy_times=1,
            today_times=0,
            gift_des="伙伴皮肤宝箱",
            gift_icon=3
        },
        {
            type=34,
            section_start=9,
            section_end=13,
            seq=6,
            item_id=32,
            gift_name="返利\n288%"
        },
        {
            type=35,
            section_start=9,
            section_end=13,
            seq=7,
            item_id=33,
            buy_money=3280,
            gift_des="神兽之魂宝箱",
            gift_name="返利\n398%"
        },
        {
            type=36,
            section_start=9,
            section_end=13,
            seq=8,
            item_id=34,
            buy_money=6480,
            gift_des="橙红魂器宝箱",
            gift_name="返利\n468%"
        },
        {
            type=37,
            section_start=14,
            section_end=20,
            item_id=35,
            today_times=2,
            buy_money=60,
            gift_des="福利宝箱",
            gift_icon=2
        },
        {
            type=38,
            section_start=14,
            section_end=20,
            seq=1,
            item_id=36,
            buy_money=300,
            gift_des="橙品神印宝箱",
            gift_icon=2,
            gift_name="返利\n218%"
        },
        {
            type=39,
            section_start=14,
            section_end=20,
            seq=2,
            item_id=37,
            buy_money=500,
            gift_des="缚宠金绳宝箱",
            gift_icon=2,
            gift_name="返利\n336%"
        },
        {
            type=40,
            section_start=14,
            section_end=20,
            seq=3,
            item_id=38,
            buy_money=980,
            gift_des="寻器符咒宝箱",
            gift_icon=3,
            gift_name="返利\n268%"
        },
        {
            type=41,
            section_start=14,
            section_end=20,
            seq=4,
            item_id=39,
            buy_money=1280,
            gift_des="宠物护符宝箱",
            gift_icon=3,
            gift_name="返利\n319%"
        },
        {
            type=42,
            section_start=14,
            section_end=20,
            seq=5,
            item_id=116,
            limit_type=1,
            buy_times=1,
            today_times=0,
            gift_des="伙伴皮肤宝箱",
            gift_icon=3
        },
        {
            type=43,
            section_start=14,
            section_end=20,
            seq=6,
            item_id=40,
            gift_name="返利\n288%"
        },
        {
            type=44,
            section_start=14,
            section_end=20,
            seq=7,
            item_id=41,
            buy_money=3280,
            gift_des="神兽之魂宝箱",
            gift_name="返利\n398%"
        },
        {
            type=45,
            section_start=14,
            section_end=20,
            seq=8,
            item_id=42,
            buy_money=6480,
            gift_des="橙红魂器宝箱",
            gift_name="返利\n468%"
        },
        {
            type=46,
            section_start=21,
            section_end=27,
            item_id=43,
            today_times=2,
            buy_money=60,
            gift_des="福利宝箱",
            gift_icon=2
        },
        {
            type=47,
            section_start=21,
            section_end=27,
            seq=1,
            item_id=44,
            buy_money=300,
            gift_des="橙品神印宝箱",
            gift_icon=2,
            gift_name="返利\n218%"
        },
        {
            type=48,
            section_start=21,
            section_end=27,
            seq=2,
            item_id=45,
            buy_money=500,
            gift_des="缚宠金绳宝箱",
            gift_icon=2,
            gift_name="返利\n336%"
        },
        {
            type=49,
            section_start=21,
            section_end=27,
            seq=3,
            item_id=46,
            buy_money=980,
            gift_des="寻器符咒宝箱",
            gift_icon=3,
            gift_name="返利\n268%"
        },
        {
            type=50,
            section_start=21,
            section_end=27,
            seq=4,
            item_id=47,
            buy_money=1280,
            gift_icon=3,
            gift_name="返利\n319%"
        },
        {
            type=51,
            section_start=21,
            section_end=27,
            seq=5,
            item_id=117,
            limit_type=1,
            buy_times=1,
            today_times=0,
            gift_des="伙伴皮肤宝箱",
            gift_icon=3
        },
        {
            type=52,
            section_start=21,
            section_end=27,
            seq=6,
            item_id=48,
            gift_des="神兽之魂宝箱",
            gift_name="返利\n288%"
        },
        {
            type=53,
            section_start=21,
            section_end=27,
            seq=7,
            item_id=49,
            buy_money=3280,
            gift_des="神秘魂灵宝箱",
            gift_name="返利\n398%"
        },
        {
            type=54,
            section_start=21,
            section_end=27,
            seq=8,
            item_id=50,
            buy_money=6480,
            gift_des="橙红魂器宝箱",
            gift_name="返利\n468%"
        },
        {
            type=55,
            section_start=28,
            section_end=35,
            item_id=51,
            today_times=2,
            buy_money=60,
            gift_des="福利宝箱",
            gift_icon=2
        },
        {
            type=56,
            section_start=28,
            section_end=35,
            seq=1,
            item_id=52,
            buy_money=300,
            gift_icon=2,
            gift_name="返利\n218%"
        },
        {
            type=57,
            section_start=28,
            section_end=35,
            seq=2,
            item_id=53,
            buy_money=500,
            gift_des="缚宠金绳宝箱",
            gift_icon=2,
            gift_name="返利\n336%"
        },
        {
            type=58,
            section_start=28,
            section_end=35,
            seq=3,
            item_id=54,
            buy_money=980,
            gift_des="寻器符咒宝箱",
            gift_icon=3,
            gift_name="返利\n268%"
        },
        {
            type=59,
            section_start=28,
            section_end=35,
            seq=4,
            item_id=55,
            buy_money=1280,
            gift_icon=3,
            gift_name="返利\n319%"
        },
        {
            type=60,
            section_start=28,
            section_end=35,
            seq=5,
            item_id=113,
            limit_type=1,
            buy_times=1,
            today_times=0,
            gift_des="伙伴皮肤宝箱",
            gift_icon=3
        },
        {
            type=61,
            section_start=28,
            section_end=35,
            seq=6,
            item_id=56,
            gift_des="神兽之魂宝箱",
            gift_name="返利\n288%"
        },
        {
            type=62,
            section_start=28,
            section_end=35,
            seq=7,
            item_id=57,
            buy_money=3280,
            gift_des="神秘魂灵宝箱",
            gift_name="返利\n398%"
        },
        {
            type=63,
            section_start=28,
            section_end=35,
            seq=8,
            item_id=58,
            buy_money=6480,
            gift_des="橙红魂器宝箱",
            gift_name="返利\n468%"
        },
        {
            type=64,
            section_start=36,
            section_end=42,
            item_id=59,
            today_times=2,
            buy_money=60,
            gift_des="福利宝箱",
            gift_icon=2
        },
        {
            type=65,
            section_start=36,
            section_end=42,
            seq=1,
            item_id=60,
            buy_money=300,
            gift_des="橙品神印宝箱",
            gift_icon=2,
            gift_name="返利\n218%"
        },
        {
            type=66,
            section_start=36,
            section_end=42,
            seq=2,
            item_id=61,
            buy_money=500,
            gift_des="缚宠金绳宝箱",
            gift_icon=2,
            gift_name="返利\n336%"
        },
        {
            type=67,
            section_start=36,
            section_end=42,
            seq=3,
            item_id=62,
            buy_money=980,
            gift_des="寻器符咒宝箱",
            gift_icon=3,
            gift_name="返利\n268%"
        },
        {
            type=68,
            section_start=36,
            section_end=42,
            seq=4,
            item_id=63,
            buy_money=1280,
            gift_icon=3,
            gift_name="返利\n319%"
        },
        {
            type=69,
            section_start=36,
            section_end=42,
            seq=5,
            item_id=114,
            limit_type=1,
            buy_times=1,
            today_times=0,
            gift_des="伙伴皮肤宝箱",
            gift_icon=3
        },
        {
            type=70,
            section_start=36,
            section_end=42,
            seq=6,
            item_id=64,
            gift_des="神兽之魂宝箱",
            gift_name="返利\n288%"
        },
        {
            type=71,
            section_start=36,
            section_end=42,
            seq=7,
            item_id=65,
            buy_money=3280,
            gift_des="伙伴元神宝箱",
            gift_name="返利\n398%"
        },
        {
            type=72,
            section_start=36,
            section_end=42,
            seq=8,
            item_id=66,
            buy_money=3280,
            gift_des="神秘魂灵宝箱",
            gift_name="返利\n418%"
        },
        {
            type=73,
            section_start=36,
            section_end=42,
            seq=9,
            item_id=67,
            buy_money=6480,
            gift_des="橙红魂器宝箱",
            gift_name="返利\n468%"
        },
        {
            type=74,
            section_start=43,
            section_end=48,
            item_id=68,
            today_times=2,
            buy_money=60,
            gift_des="福利宝箱",
            gift_icon=2
        },
        {
            type=75,
            section_start=43,
            section_end=48,
            seq=1,
            item_id=69,
            buy_money=300,
            gift_icon=2,
            gift_name="返利\n218%"
        },
        {
            type=76,
            section_start=43,
            section_end=48,
            seq=2,
            item_id=70,
            buy_money=500,
            gift_des="缚宠金绳宝箱",
            gift_icon=2,
            gift_name="返利\n336%"
        },
        {
            type=77,
            section_start=43,
            section_end=48,
            seq=3,
            item_id=71,
            buy_money=980,
            gift_des="寻器符咒宝箱",
            gift_icon=3,
            gift_name="返利\n268%"
        },
        {
            type=78,
            section_start=43,
            section_end=48,
            seq=4,
            item_id=72,
            buy_money=1280,
            gift_des="神兽之魂宝箱",
            gift_icon=3,
            gift_name="返利\n319%"
        },
        {
            type=79,
            section_start=43,
            section_end=48,
            seq=5,
            limit_type=1,
            buy_times=1,
            today_times=0,
            gift_des="伙伴皮肤宝箱",
            gift_icon=3
        },
        {
            type=80,
            section_start=43,
            section_end=48,
            seq=6,
            item_id=73,
            gift_name="返利\n288%"
        },
        {
            type=81,
            section_start=43,
            section_end=48,
            seq=7,
            item_id=74,
            gift_des="神秘魂灵宝箱",
            gift_name="返利\n388%"
        },
        {
            type=82,
            section_start=43,
            section_end=48,
            seq=8,
            item_id=75,
            buy_money=3280,
            gift_des="造化装备宝箱",
            gift_name="返利\n398%"
        },
        {
            type=83,
            section_start=43,
            section_end=48,
            seq=9,
            item_id=76,
            buy_money=6480,
            gift_des="橙红魂器宝箱",
            gift_name="返利\n468%"
        },
        {
            type=84,
            section_start=49,
            section_end=56,
            item_id=77,
            today_times=2,
            buy_money=60,
            gift_des="福利宝箱",
            gift_icon=2
        },
        {
            type=85,
            section_start=49,
            section_end=56,
            seq=1,
            item_id=78,
            buy_money=300,
            gift_des="橙品神印宝箱",
            gift_icon=2,
            gift_name="返利\n218%"
        },
        {
            type=86,
            section_start=49,
            section_end=56,
            seq=2,
            item_id=79,
            buy_money=500,
            gift_des="缚宠金绳宝箱",
            gift_icon=2,
            gift_name="返利\n336%"
        },
        {
            type=87,
            section_start=49,
            section_end=56,
            seq=3,
            item_id=80,
            buy_money=980,
            gift_des="寻器符咒宝箱",
            gift_icon=3,
            gift_name="返利\n268%"
        },
        {
            type=88,
            section_start=49,
            section_end=56,
            seq=4,
            item_id=81,
            buy_money=1280,
            gift_des="神兽之魂宝箱",
            gift_icon=3,
            gift_name="返利\n319%"
        },
        {
            type=89,
            section_start=49,
            section_end=56,
            seq=5,
            item_id=116,
            limit_type=1,
            buy_times=1,
            today_times=0,
            gift_des="伙伴皮肤宝箱",
            gift_icon=3
        },
        {
            type=90,
            section_start=49,
            section_end=56,
            seq=6,
            item_id=82,
            gift_name="返利\n288%"
        },
        {
            type=91,
            section_start=49,
            section_end=56,
            seq=7,
            item_id=83,
            gift_des="神秘魂灵宝箱",
            gift_name="返利\n388%"
        },
        {
            type=92,
            section_start=49,
            section_end=56,
            seq=8,
            item_id=84,
            buy_money=3280,
            gift_des="造化装备宝箱",
            gift_name="返利\n398%"
        },
        {
            type=93,
            section_start=49,
            section_end=56,
            seq=9,
            item_id=85,
            buy_money=6480,
            gift_des="橙红魂器宝箱",
            gift_name="返利\n468%"
        },
        {
            type=94,
            section_start=57,
            section_end=63,
            item_id=86,
            today_times=2,
            buy_money=60,
            gift_des="福利宝箱",
            gift_icon=2
        },
        {
            type=95,
            section_start=57,
            section_end=63,
            seq=1,
            item_id=87,
            buy_money=300,
            gift_icon=2,
            gift_name="返利\n218%"
        },
        {
            type=96,
            section_start=57,
            section_end=63,
            seq=2,
            item_id=88,
            buy_money=500,
            gift_des="缚宠金绳宝箱",
            gift_icon=2,
            gift_name="返利\n336%"
        },
        {
            type=97,
            section_start=57,
            section_end=63,
            seq=3,
            item_id=89,
            buy_money=980,
            gift_des="寻器符咒宝箱",
            gift_icon=3,
            gift_name="返利\n268%"
        },
        {
            type=98,
            section_start=57,
            section_end=63,
            seq=4,
            item_id=90,
            buy_money=1280,
            gift_des="神兽之魂宝箱",
            gift_icon=3,
            gift_name="返利\n319%"
        },
        {
            type=99,
            section_start=57,
            section_end=63,
            seq=5,
            item_id=117,
            limit_type=1,
            buy_times=1,
            today_times=0,
            gift_des="伙伴皮肤宝箱",
            gift_icon=3
        },
        {
            type=100,
            section_start=57,
            section_end=63,
            seq=6,
            item_id=91,
            gift_name="返利\n288%"
        },
        {
            type=101,
            section_start=57,
            section_end=63,
            seq=7,
            item_id=92,
            gift_des="神秘魂灵宝箱",
            gift_name="返利\n388%"
        },
        {
            type=102,
            section_start=57,
            section_end=63,
            seq=8,
            item_id=93,
            buy_money=3280,
            gift_des="造化装备宝箱",
            gift_name="返利\n398%"
        },
        {
            type=103,
            section_start=57,
            section_end=63,
            seq=9,
            item_id=94,
            buy_money=6480,
            gift_des="橙红魂器宝箱",
            gift_name="返利\n468%"
        },
        {
            type=104,
            section_start=64,
            section_end=71,
            item_id=95,
            today_times=2,
            buy_money=60,
            gift_des="福利宝箱",
            gift_icon=2
        },
        {
            type=105,
            section_start=64,
            section_end=71,
            seq=1,
            item_id=96,
            buy_money=300,
            gift_des="橙品神印宝箱",
            gift_icon=2,
            gift_name="返利\n218%"
        },
        {
            type=106,
            section_start=64,
            section_end=71,
            seq=2,
            item_id=97,
            buy_money=500,
            gift_des="缚宠金绳宝箱",
            gift_icon=2,
            gift_name="返利\n336%"
        },
        {
            type=107,
            section_start=64,
            section_end=71,
            seq=3,
            item_id=98,
            buy_money=980,
            gift_des="寻器符咒宝箱",
            gift_icon=3,
            gift_name="返利\n268%"
        },
        {
            type=108,
            section_start=64,
            section_end=71,
            seq=4,
            item_id=99,
            buy_money=1280,
            gift_des="神兽之魂宝箱",
            gift_icon=3,
            gift_name="返利\n319%"
        },
        {
            type=109,
            section_start=64,
            section_end=71,
            seq=5,
            limit_type=1,
            buy_times=1,
            today_times=0,
            gift_des="伙伴皮肤宝箱",
            gift_icon=3
        },
        {
            type=110,
            section_start=64,
            section_end=71,
            seq=6,
            item_id=100,
            gift_name="返利\n288%"
        },
        {
            type=111,
            section_start=64,
            section_end=71,
            seq=7,
            item_id=101,
            gift_des="神秘魂灵宝箱",
            gift_name="返利\n388%"
        },
        {
            type=112,
            section_start=64,
            section_end=71,
            seq=8,
            item_id=102,
            buy_money=3280,
            gift_des="造化装备宝箱",
            gift_name="返利\n398%"
        },
        {
            type=113,
            section_start=64,
            section_end=71,
            seq=9,
            item_id=103,
            buy_money=6480,
            gift_des="橙红魂器宝箱",
            gift_name="返利\n468%"
        },
        {
            type=114,
            section_start=72,
            section_end=0,
            item_id=104,
            today_times=2,
            buy_money=60,
            gift_des="福利宝箱",
            gift_icon=2
        },
        {
            type=115,
            section_start=72,
            section_end=0,
            seq=1,
            item_id=105,
            buy_money=300,
            gift_des="橙品神印宝箱",
            gift_icon=2,
            gift_name="返利\n218%"
        },
        {
            type=116,
            section_start=72,
            section_end=0,
            seq=2,
            item_id=106,
            buy_money=500,
            gift_des="缚宠金绳宝箱",
            gift_icon=2,
            gift_name="返利\n336%"
        },
        {
            type=117,
            section_start=72,
            section_end=0,
            seq=3,
            item_id=107,
            buy_money=980,
            gift_des="寻器符咒宝箱",
            gift_icon=3,
            gift_name="返利\n268%"
        },
        {
            type=118,
            section_start=72,
            section_end=0,
            seq=4,
            item_id=108,
            buy_money=1280,
            gift_des="神兽之魂宝箱",
            gift_icon=3,
            gift_name="返利\n319%"
        },
        {
            type=119,
            section_start=72,
            section_end=0,
            seq=5,
            item_id=117,
            limit_type=1,
            buy_times=1,
            today_times=0,
            gift_des="伙伴皮肤宝箱",
            gift_icon=3
        },
        {
            type=120,
            section_start=72,
            section_end=0,
            seq=6,
            item_id=109,
            gift_name="返利\n288%"
        },
        {
            type=121,
            section_start=72,
            section_end=0,
            seq=7,
            item_id=110,
            gift_des="神秘魂灵宝箱",
            gift_name="返利\n388%"
        },
        {
            type=122,
            section_start=72,
            section_end=0,
            seq=8,
            item_id=111,
            buy_money=3280,
            gift_des="造化装备宝箱",
            gift_name="返利\n398%"
        },
        {
            type=123,
            section_start=72,
            section_end=0,
            seq=9,
            item_id=112,
            buy_money=6480,
            gift_des="橙红魂器宝箱",
            gift_name="返利\n468%"
        }
    },
    reward_pool={
        {
            reward_item=_itemlist.i_9000_1_1
        },
        {
            type=1,
            reward_item=_itemlist.i_27399_5_1
        },
        {
            type=2,
            reward_item=_itemlist.i_24557_1_1
        },
        {
            type=3,
            reward_item=_itemlist.i_26813_1_1
        },
        {
            item_id=2,
            reward_item=_itemlist.i_26813_3_1
        },
        {
            type=1,
            item_id=2,
            reward_item=_itemlist.i_27399_6_1
        },
        {
            type=2,
            item_id=2,
            reward_item=_itemlist.i_27403_1_1
        },
        {
            type=3,
            item_id=2,
            reward_item=_itemlist.i_26812_3_1
        },
        {
            item_id=3,
            reward_item=_itemlist.i_29091_50_1
        },
        {
            type=1,
            item_id=3,
            reward_item=_itemlist.i_27403_2_1
        },
        {
            type=2,
            item_id=3,
            reward_item=_itemlist.i_27402_3_1
        },
        {
            type=3,
            item_id=3,
            reward_item=_itemlist.i_27575_5_1
        },
        {
            item_id=4,
            reward_item=_itemlist.i_9012_1_1
        },
        {
            type=1,
            item_id=4,
            reward_item=_itemlist.i_26443_5_1
        },
        {
            type=2,
            item_id=4,
            reward_item=_itemlist.i_27403_1_1
        },
        {
            type=3,
            item_id=4,
            reward_item=_itemlist.i_27399_9_1
        },
        {
            item_id=5,
            reward_item=_itemlist.i_25520_3_1
        },
        {
            type=1,
            item_id=5,
            reward_item=_itemlist.i_24557_5_1
        },
        {
            type=2,
            item_id=5,
            reward_item=_itemlist.i_27399_12_1
        },
        {
            type=3,
            item_id=5,
            reward_item=_itemlist.i_27494_15_1
        },
        {
            item_id=6,
            reward_item=_itemlist.i_29040_2_1
        },
        {
            type=1,
            item_id=6,
            reward_item=_itemlist.i_26224_5_1
        },
        {
            type=2,
            item_id=6,
            reward_item=_itemlist.i_22099_1_1
        },
        {
            type=3,
            item_id=6,
            reward_item=_itemlist.i_24557_2_1
        },
        {
            item_id=7,
            reward_item=_itemlist.i_25566_1_1
        },
        {
            type=1,
            item_id=7,
            reward_item=_itemlist.i_27399_21_1
        },
        {
            type=2,
            item_id=7,
            reward_item=_itemlist.i_22099_1_1
        },
        {
            type=3,
            item_id=7,
            reward_item=_itemlist.i_25520_1_1
        },
        {
            item_id=8,
            reward_item=_itemlist.i_25607_1_1
        },
        {
            type=1,
            item_id=8,
            reward_item=_itemlist.i_28097_1_1
        },
        {
            type=2,
            item_id=8,
            reward_item=_itemlist.i_27399_21_1
        },
        {
            type=3,
            item_id=8,
            reward_item=_itemlist.i_25520_3_1
        },
        {
            item_id=9,
            reward_item=_itemlist.i_27187_45_1
        },
        {
            type=1,
            item_id=9,
            reward_item=_itemlist.i_27479_50_1
        },
        {
            type=2,
            item_id=9,
            reward_item=_itemlist.i_22099_1_1
        },
        {
            type=3,
            item_id=9,
            reward_item=_itemlist.i_9003_1_1
        },
        {
            item_id=10,
            reward_item=_itemlist.i_9000_1_1
        },
        {
            type=1,
            item_id=10,
            reward_item=_itemlist.i_27399_3_1
        },
        {
            type=2,
            item_id=10,
            reward_item=_itemlist.i_24557_1_1
        },
        {
            type=3,
            item_id=10,
            reward_item=_itemlist.i_26813_1_1
        },
        {
            item_id=11,
            reward_item=_itemlist.i_26813_4_1
        },
        {
            type=1,
            item_id=11,
            reward_item=_itemlist.i_27399_6_1
        },
        {
            type=2,
            item_id=11,
            reward_item=_itemlist.i_27403_1_1
        },
        {
            type=3,
            item_id=11,
            reward_item=_itemlist.i_26812_3_1
        },
        {
            item_id=12,
            reward_item=_itemlist.i_28771_1_1
        },
        {
            type=1,
            item_id=12,
            reward_item=_itemlist.i_27403_5_1
        },
        {
            type=2,
            item_id=12,
            reward_item=_itemlist.i_27402_3_1
        },
        {
            type=3,
            item_id=12,
            reward_item=_itemlist.i_26813_1_1
        },
        {
            item_id=13,
            reward_item=_itemlist.i_27541_6_1
        },
        {
            type=1,
            item_id=13,
            reward_item=_itemlist.i_29021_10_1
        },
        {
            type=2,
            item_id=13,
            reward_item=_itemlist.i_27540_2_1
        },
        {
            type=3,
            item_id=13,
            reward_item=_itemlist.i_27399_9_1
        },
        {
            item_id=14,
            reward_item=_itemlist.i_25657_1_1
        },
        {
            type=1,
            item_id=14,
            reward_item=_itemlist.i_27478_500_1
        },
        {
            type=2,
            item_id=14,
            reward_item=_itemlist.i_25506_1_1
        },
        {
            type=3,
            item_id=14,
            reward_item=_itemlist.i_22014_15_1
        },
        {
            item_id=15,
            reward_item=_itemlist.i_29040_2_1
        },
        {
            type=1,
            item_id=15,
            reward_item=_itemlist.i_26224_5_1
        },
        {
            type=2,
            item_id=15,
            reward_item=_itemlist.i_22099_1_1
        },
        {
            type=3,
            item_id=15,
            reward_item=_itemlist.i_24557_2_1
        },
        {
            item_id=16,
            reward_item=_itemlist.i_25607_1_1
        },
        {
            type=1,
            item_id=16,
            reward_item=_itemlist.i_27399_21_1
        },
        {
            type=2,
            item_id=16,
            reward_item=_itemlist.i_22099_1_1
        },
        {
            type=3,
            item_id=16,
            reward_item=_itemlist.i_25520_1_1
        },
        {
            item_id=17,
            reward_item=_itemlist.i_28311_1_1
        },
        {
            type=1,
            item_id=17,
            reward_item=_itemlist.i_26444_2_1
        },
        {
            type=2,
            item_id=17,
            reward_item=_itemlist.i_9012_1_1
        },
        {
            type=3,
            item_id=17,
            reward_item=_itemlist.i_25520_1_1
        },
        {
            item_id=18,
            reward_item=_itemlist.i_27187_45_1
        },
        {
            type=1,
            item_id=18,
            reward_item=_itemlist.i_27479_50_1
        },
        {
            type=2,
            item_id=18,
            reward_item=_itemlist.i_22099_1_1
        },
        {
            type=3,
            item_id=18,
            reward_item=_itemlist.i_9003_1_1
        },
        {
            item_id=19,
            reward_item=_itemlist.i_9001_1_1
        },
        {
            type=1,
            item_id=19,
            reward_item=_itemlist.i_27479_10_1
        },
        {
            type=2,
            item_id=19,
            reward_item=_itemlist.i_24557_1_1
        },
        {
            type=3,
            item_id=19,
            reward_item=_itemlist.i_26813_1_1
        },
        {
            item_id=20,
            reward_item=_itemlist.i_27723_2_1
        },
        {
            type=1,
            item_id=20,
            reward_item=_itemlist.i_27656_1_1
        },
        {
            type=2,
            item_id=20,
            reward_item=_itemlist.i_27655_2_1
        },
        {
            type=3,
            item_id=20,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            item_id=21,
            reward_item=_itemlist.i_29021_15_1
        },
        {
            type=1,
            item_id=21,
            reward_item=_itemlist.i_27399_6_1
        },
        {
            type=2,
            item_id=21,
            reward_item=_itemlist.i_24557_1_1
        },
        {
            type=3,
            item_id=21,
            reward_item=_itemlist.i_27541_1_1
        },
        {
            item_id=22,
            reward_item=_itemlist.i_27541_6_1
        },
        {
            type=1,
            item_id=22,
            reward_item=_itemlist.i_29021_10_1
        },
        {
            type=2,
            item_id=22,
            reward_item=_itemlist.i_27540_2_1
        },
        {
            type=3,
            item_id=22,
            reward_item=_itemlist.i_27399_9_1
        },
        {
            item_id=23,
            reward_item=_itemlist.i_27665_6_1
        },
        {
            type=1,
            item_id=23,
            reward_item=_itemlist.i_27664_3_1
        },
        {
            type=2,
            item_id=23,
            reward_item=_itemlist.i_27656_1_1
        },
        {
            type=3,
            item_id=23,
            reward_item=_itemlist.i_27655_3_1
        },
        {
            item_id=24,
            reward_item=_itemlist.i_28762_2_1
        },
        {
            type=1,
            item_id=24,
            reward_item=_itemlist.i_28722_3_1
        },
        {
            type=2,
            item_id=24,
            reward_item=_itemlist.i_29120_5_1
        },
        {
            type=3,
            item_id=24,
            reward_item=_itemlist.i_27403_3_1
        },
        {
            item_id=25,
            reward_item=_itemlist.i_27723_18_1
        },
        {
            type=1,
            item_id=25,
            reward_item=_itemlist.i_27657_3_1
        },
        {
            type=2,
            item_id=25,
            reward_item=_itemlist.i_27656_5_1
        },
        {
            type=3,
            item_id=25,
            reward_item=_itemlist.i_27665_3_1
        },
        {
            item_id=26,
            reward_item=_itemlist.i_27187_50_1
        },
        {
            type=1,
            item_id=26,
            reward_item=_itemlist.i_27479_40_1
        },
        {
            type=2,
            item_id=26,
            reward_item=_itemlist.i_22099_1_1
        },
        {
            type=3,
            item_id=26,
            reward_item=_itemlist.i_9003_1_1
        },
        {
            item_id=27,
            reward_item=_itemlist.i_9002_1_1
        },
        {
            type=1,
            item_id=27,
            reward_item=_itemlist.i_27479_10_1
        },
        {
            type=2,
            item_id=27,
            reward_item=_itemlist.i_24557_1_1
        },
        {
            type=3,
            item_id=27,
            reward_item=_itemlist.i_26813_2_1
        },
        {
            item_id=28,
            reward_item=_itemlist.i_27723_2_1
        },
        {
            type=1,
            item_id=28,
            reward_item=_itemlist.i_27656_1_1
        },
        {
            type=2,
            item_id=28,
            reward_item=_itemlist.i_27655_2_1
        },
        {
            type=3,
            item_id=28,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            item_id=29,
            reward_item=_itemlist.i_27541_4_1
        },
        {
            type=1,
            item_id=29,
            reward_item=_itemlist.i_29021_5_1
        },
        {
            type=2,
            item_id=29,
            reward_item=_itemlist.i_27399_9_1
        },
        {
            type=3,
            item_id=29,
            reward_item=_itemlist.i_27540_2_1
        },
        {
            item_id=30,
            reward_item=_itemlist.i_27665_5_1
        },
        {
            type=1,
            item_id=30,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            type=2,
            item_id=30,
            reward_item=_itemlist.i_27656_1_1
        },
        {
            type=3,
            item_id=30,
            reward_item=_itemlist.i_27655_3_1
        },
        {
            item_id=31,
            reward_item=_itemlist.i_9003_1_1
        },
        {
            type=1,
            item_id=31,
            reward_item=_itemlist.i_27479_30_1
        },
        {
            type=2,
            item_id=31,
            reward_item=_itemlist.i_24557_1_1
        },
        {
            type=3,
            item_id=31,
            reward_item=_itemlist.i_27399_5_1
        },
        {
            item_id=32,
            reward_item=_itemlist.i_27723_12_1
        },
        {
            type=1,
            item_id=32,
            reward_item=_itemlist.i_27656_2_1
        },
        {
            type=2,
            item_id=32,
            reward_item=_itemlist.i_27655_5_1
        },
        {
            type=3,
            item_id=32,
            reward_item=_itemlist.i_27665_1_1
        },
        {
            item_id=33,
            reward_item=_itemlist.i_27187_35_1
        },
        {
            type=1,
            item_id=33,
            reward_item=_itemlist.i_25689_1_1
        },
        {
            type=2,
            item_id=33,
            reward_item=_itemlist.i_22099_1_1
        },
        {
            type=3,
            item_id=33,
            reward_item=_itemlist.i_24557_2_1
        },
        {
            item_id=34,
            reward_item=_itemlist.i_28658_1_1
        },
        {
            type=1,
            item_id=34,
            reward_item=_itemlist.i_27657_3_1
        },
        {
            type=2,
            item_id=34,
            reward_item=_itemlist.i_27656_5_1
        },
        {
            type=3,
            item_id=34,
            reward_item=_itemlist.i_27665_5_1
        },
        {
            item_id=35,
            reward_item=_itemlist.i_28773_1_1
        },
        {
            type=1,
            item_id=35,
            reward_item=_itemlist.i_27479_10_1
        },
        {
            type=2,
            item_id=35,
            reward_item=_itemlist.i_24557_1_1
        },
        {
            type=3,
            item_id=35,
            reward_item=_itemlist.i_26813_2_1
        },
        {
            item_id=36,
            reward_item=_itemlist.i_25688_1_1
        },
        {
            type=1,
            item_id=36,
            reward_item=_itemlist.i_27671_2_1
        },
        {
            type=2,
            item_id=36,
            reward_item=_itemlist.i_27672_1_1
        },
        {
            type=3,
            item_id=36,
            reward_item=_itemlist.i_22014_20_1
        },
        {
            item_id=37,
            reward_item=_itemlist.i_27541_4_1
        },
        {
            type=1,
            item_id=37,
            reward_item=_itemlist.i_29021_10_1
        },
        {
            type=2,
            item_id=37,
            reward_item=_itemlist.i_27399_9_1
        },
        {
            type=3,
            item_id=37,
            reward_item=_itemlist.i_27540_2_1
        },
        {
            item_id=38,
            reward_item=_itemlist.i_27665_5_1
        },
        {
            type=1,
            item_id=38,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            type=2,
            item_id=38,
            reward_item=_itemlist.i_27656_1_1
        },
        {
            type=3,
            item_id=38,
            reward_item=_itemlist.i_27655_3_1
        },
        {
            item_id=39,
            reward_item=_itemlist.i_9003_1_1
        },
        {
            type=1,
            item_id=39,
            reward_item=_itemlist.i_27479_35_1
        },
        {
            type=2,
            item_id=39,
            reward_item=_itemlist.i_24557_1_1
        },
        {
            type=3,
            item_id=39,
            reward_item=_itemlist.i_27399_5_1
        },
        {
            item_id=40,
            reward_item=_itemlist.i_27723_12_1
        },
        {
            type=1,
            item_id=40,
            reward_item=_itemlist.i_27656_2_1
        },
        {
            type=2,
            item_id=40,
            reward_item=_itemlist.i_27655_5_1
        },
        {
            type=3,
            item_id=40,
            reward_item=_itemlist.i_27665_1_1
        },
        {
            item_id=41,
            reward_item=_itemlist.i_27187_38_1
        },
        {
            type=1,
            item_id=41,
            reward_item=_itemlist.i_25689_1_1
        },
        {
            type=2,
            item_id=41,
            reward_item=_itemlist.i_22099_1_1
        },
        {
            type=3,
            item_id=41,
            reward_item=_itemlist.i_24557_2_1
        },
        {
            item_id=42,
            reward_item=_itemlist.i_28658_1_1
        },
        {
            type=1,
            item_id=42,
            reward_item=_itemlist.i_27657_3_1
        },
        {
            type=2,
            item_id=42,
            reward_item=_itemlist.i_27656_5_1
        },
        {
            type=3,
            item_id=42,
            reward_item=_itemlist.i_27665_5_1
        },
        {
            item_id=43,
            reward_item=_itemlist.i_28773_1_1
        },
        {
            type=1,
            item_id=43,
            reward_item=_itemlist.i_27479_10_1
        },
        {
            type=2,
            item_id=43,
            reward_item=_itemlist.i_24557_1_1
        },
        {
            type=3,
            item_id=43,
            reward_item=_itemlist.i_28772_1_1
        },
        {
            item_id=44,
            reward_item=_itemlist.i_25688_1_1
        },
        {
            type=1,
            item_id=44,
            reward_item=_itemlist.i_27671_3_1
        },
        {
            type=2,
            item_id=44,
            reward_item=_itemlist.i_27672_1_1
        },
        {
            type=3,
            item_id=44,
            reward_item=_itemlist.i_22014_20_1
        },
        {
            item_id=45,
            reward_item=_itemlist.i_27541_5_1
        },
        {
            type=1,
            item_id=45,
            reward_item=_itemlist.i_29021_5_1
        },
        {
            type=2,
            item_id=45,
            reward_item=_itemlist.i_27399_9_1
        },
        {
            type=3,
            item_id=45,
            reward_item=_itemlist.i_27540_2_1
        },
        {
            item_id=46,
            reward_item=_itemlist.i_27665_6_1
        },
        {
            type=1,
            item_id=46,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            type=2,
            item_id=46,
            reward_item=_itemlist.i_27656_1_1
        },
        {
            type=3,
            item_id=46,
            reward_item=_itemlist.i_27655_3_1
        },
        {
            item_id=47,
            reward_item=_itemlist.i_27723_7_1
        },
        {
            type=1,
            item_id=47,
            reward_item=_itemlist.i_27656_1_1
        },
        {
            type=2,
            item_id=47,
            reward_item=_itemlist.i_27655_3_1
        },
        {
            type=3,
            item_id=47,
            reward_item=_itemlist.i_27665_1_1
        },
        {
            item_id=48,
            reward_item=_itemlist.i_27187_25_1
        },
        {
            type=1,
            item_id=48,
            reward_item=_itemlist.i_25520_1_1
        },
        {
            type=2,
            item_id=48,
            reward_item=_itemlist.i_22099_1_1
        },
        {
            type=3,
            item_id=48,
            reward_item=_itemlist.i_24557_2_1
        },
        {
            item_id=49,
            reward_item=_itemlist.i_26416_32_1
        },
        {
            type=1,
            item_id=49,
            reward_item=_itemlist.i_25689_1_1
        },
        {
            type=2,
            item_id=49,
            reward_item=_itemlist.i_22099_1_1
        },
        {
            type=3,
            item_id=49,
            reward_item=_itemlist.i_24557_2_1
        },
        {
            item_id=50,
            reward_item=_itemlist.i_28658_1_1
        },
        {
            type=1,
            item_id=50,
            reward_item=_itemlist.i_27657_3_1
        },
        {
            type=2,
            item_id=50,
            reward_item=_itemlist.i_27656_5_1
        },
        {
            type=3,
            item_id=50,
            reward_item=_itemlist.i_27665_5_1
        },
        {
            item_id=51,
            reward_item=_itemlist.i_28773_1_1
        },
        {
            type=1,
            item_id=51,
            reward_item=_itemlist.i_27479_10_1
        },
        {
            type=2,
            item_id=51,
            reward_item=_itemlist.i_24557_1_1
        },
        {
            type=3,
            item_id=51,
            reward_item=_itemlist.i_28772_1_1
        },
        {
            item_id=52,
            reward_item=_itemlist.i_27723_2_1
        },
        {
            type=1,
            item_id=52,
            reward_item=_itemlist.i_27656_1_1
        },
        {
            type=2,
            item_id=52,
            reward_item=_itemlist.i_27655_2_1
        },
        {
            type=3,
            item_id=52,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            item_id=53,
            reward_item=_itemlist.i_27541_5_1
        },
        {
            type=1,
            item_id=53,
            reward_item=_itemlist.i_29021_10_1
        },
        {
            type=2,
            item_id=53,
            reward_item=_itemlist.i_27399_9_1
        },
        {
            type=3,
            item_id=53,
            reward_item=_itemlist.i_27540_2_1
        },
        {
            item_id=54,
            reward_item=_itemlist.i_27665_7_1
        },
        {
            type=1,
            item_id=54,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            type=2,
            item_id=54,
            reward_item=_itemlist.i_27656_1_1
        },
        {
            type=3,
            item_id=54,
            reward_item=_itemlist.i_27655_3_1
        },
        {
            item_id=55,
            reward_item=_itemlist.i_27723_8_1
        },
        {
            type=1,
            item_id=55,
            reward_item=_itemlist.i_27656_2_1
        },
        {
            type=2,
            item_id=55,
            reward_item=_itemlist.i_27655_5_1
        },
        {
            type=3,
            item_id=55,
            reward_item=_itemlist.i_27665_1_1
        },
        {
            item_id=56,
            reward_item=_itemlist.i_27187_28_1
        },
        {
            type=1,
            item_id=56,
            reward_item=_itemlist.i_25520_1_1
        },
        {
            type=2,
            item_id=56,
            reward_item=_itemlist.i_22099_1_1
        },
        {
            type=3,
            item_id=56,
            reward_item=_itemlist.i_24557_2_1
        },
        {
            item_id=57,
            reward_item=_itemlist.i_26416_33_1
        },
        {
            type=1,
            item_id=57,
            reward_item=_itemlist.i_25689_1_1
        },
        {
            type=2,
            item_id=57,
            reward_item=_itemlist.i_22099_1_1
        },
        {
            type=3,
            item_id=57,
            reward_item=_itemlist.i_24557_2_1
        },
        {
            item_id=58,
            reward_item=_itemlist.i_28658_1_1
        },
        {
            type=1,
            item_id=58,
            reward_item=_itemlist.i_27657_3_1
        },
        {
            type=2,
            item_id=58,
            reward_item=_itemlist.i_27656_5_1
        },
        {
            type=3,
            item_id=58,
            reward_item=_itemlist.i_27665_5_1
        },
        {
            item_id=59,
            reward_item=_itemlist.i_28773_1_1
        },
        {
            type=1,
            item_id=59,
            reward_item=_itemlist.i_27479_10_1
        },
        {
            type=2,
            item_id=59,
            reward_item=_itemlist.i_24557_1_1
        },
        {
            type=3,
            item_id=59,
            reward_item=_itemlist.i_28772_1_1
        },
        {
            item_id=60,
            reward_item=_itemlist.i_25688_2_1
        },
        {
            type=1,
            item_id=60,
            reward_item=_itemlist.i_27671_5_1
        },
        {
            type=2,
            item_id=60,
            reward_item=_itemlist.i_27672_2_1
        },
        {
            type=3,
            item_id=60,
            reward_item=_itemlist.i_22014_30_1
        },
        {
            item_id=61,
            reward_item=_itemlist.i_27541_5_1
        },
        {
            type=1,
            item_id=61,
            reward_item=_itemlist.i_29021_10_1
        },
        {
            type=2,
            item_id=61,
            reward_item=_itemlist.i_27399_6_1
        },
        {
            type=3,
            item_id=61,
            reward_item=_itemlist.i_27540_2_1
        },
        {
            item_id=62,
            reward_item=_itemlist.i_27665_7_1
        },
        {
            type=1,
            item_id=62,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            type=2,
            item_id=62,
            reward_item=_itemlist.i_27656_1_1
        },
        {
            type=3,
            item_id=62,
            reward_item=_itemlist.i_27655_3_1
        },
        {
            item_id=63,
            reward_item=_itemlist.i_27723_9_1
        },
        {
            type=1,
            item_id=63,
            reward_item=_itemlist.i_27656_2_1
        },
        {
            type=2,
            item_id=63,
            reward_item=_itemlist.i_27655_5_1
        },
        {
            type=3,
            item_id=63,
            reward_item=_itemlist.i_27665_1_1
        },
        {
            item_id=64,
            reward_item=_itemlist.i_27187_32_1
        },
        {
            type=1,
            item_id=64,
            reward_item=_itemlist.i_25520_1_1
        },
        {
            type=2,
            item_id=64,
            reward_item=_itemlist.i_22099_1_1
        },
        {
            type=3,
            item_id=64,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            item_id=65,
            reward_item=_itemlist.i_29106_2_1
        },
        {
            type=1,
            item_id=65,
            reward_item=_itemlist.i_29121_3_1
        },
        {
            type=2,
            item_id=65,
            reward_item=_itemlist.i_28721_5_1
        },
        {
            type=3,
            item_id=65,
            reward_item=_itemlist.i_29120_4_1
        },
        {
            item_id=66,
            reward_item=_itemlist.i_26416_35_1
        },
        {
            type=1,
            item_id=66,
            reward_item=_itemlist.i_25689_1_1
        },
        {
            type=2,
            item_id=66,
            reward_item=_itemlist.i_22099_1_1
        },
        {
            type=3,
            item_id=66,
            reward_item=_itemlist.i_24557_2_1
        },
        {
            item_id=67,
            reward_item=_itemlist.i_28658_1_1
        },
        {
            type=1,
            item_id=67,
            reward_item=_itemlist.i_27657_3_1
        },
        {
            type=2,
            item_id=67,
            reward_item=_itemlist.i_27656_5_1
        },
        {
            type=3,
            item_id=67,
            reward_item=_itemlist.i_27665_5_1
        },
        {
            item_id=68,
            reward_item=_itemlist.i_28773_1_1
        },
        {
            type=1,
            item_id=68,
            reward_item=_itemlist.i_27479_10_1
        },
        {
            type=2,
            item_id=68,
            reward_item=_itemlist.i_24557_1_1
        },
        {
            type=3,
            item_id=68,
            reward_item=_itemlist.i_28772_1_1
        },
        {
            item_id=69,
            reward_item=_itemlist.i_27723_2_1
        },
        {
            type=1,
            item_id=69,
            reward_item=_itemlist.i_27656_1_1
        },
        {
            type=2,
            item_id=69,
            reward_item=_itemlist.i_27655_2_1
        },
        {
            type=3,
            item_id=69,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            item_id=70,
            reward_item=_itemlist.i_27541_5_1
        },
        {
            type=1,
            item_id=70,
            reward_item=_itemlist.i_29021_15_1
        },
        {
            type=2,
            item_id=70,
            reward_item=_itemlist.i_27399_6_1
        },
        {
            type=3,
            item_id=70,
            reward_item=_itemlist.i_27540_2_1
        },
        {
            item_id=71,
            reward_item=_itemlist.i_27665_7_1
        },
        {
            type=1,
            item_id=71,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            type=2,
            item_id=71,
            reward_item=_itemlist.i_27656_1_1
        },
        {
            type=3,
            item_id=71,
            reward_item=_itemlist.i_27655_3_1
        },
        {
            item_id=72,
            reward_item=_itemlist.i_27187_25_1
        },
        {
            type=1,
            item_id=72,
            reward_item=_itemlist.i_25520_1_1
        },
        {
            type=2,
            item_id=72,
            reward_item=_itemlist.i_24557_2_1
        },
        {
            type=3,
            item_id=72,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            item_id=73,
            reward_item=_itemlist.i_27723_15_1
        },
        {
            type=1,
            item_id=73,
            reward_item=_itemlist.i_27656_2_1
        },
        {
            type=2,
            item_id=73,
            reward_item=_itemlist.i_27655_5_1
        },
        {
            type=3,
            item_id=73,
            reward_item=_itemlist.i_27665_1_1
        },
        {
            item_id=74,
            reward_item=_itemlist.i_26416_22_1
        },
        {
            type=1,
            item_id=74,
            reward_item=_itemlist.i_25689_1_1
        },
        {
            type=2,
            item_id=74,
            reward_item=_itemlist.i_24557_2_1
        },
        {
            type=3,
            item_id=74,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            item_id=75,
            reward_item=_itemlist.i_26688_50_1
        },
        {
            type=1,
            item_id=75,
            reward_item=_itemlist.i_26687_10_1
        },
        {
            type=2,
            item_id=75,
            reward_item=_itemlist.i_26773_10_1
        },
        {
            type=3,
            item_id=75,
            reward_item=_itemlist.i_26689_30_1
        },
        {
            item_id=76,
            reward_item=_itemlist.i_28658_1_1
        },
        {
            type=1,
            item_id=76,
            reward_item=_itemlist.i_27657_3_1
        },
        {
            type=2,
            item_id=76,
            reward_item=_itemlist.i_27656_5_1
        },
        {
            type=3,
            item_id=76,
            reward_item=_itemlist.i_27665_5_1
        },
        {
            item_id=77,
            reward_item=_itemlist.i_28773_1_1
        },
        {
            type=1,
            item_id=77,
            reward_item=_itemlist.i_27479_10_1
        },
        {
            type=2,
            item_id=77,
            reward_item=_itemlist.i_24557_1_1
        },
        {
            type=3,
            item_id=77,
            reward_item=_itemlist.i_28772_1_1
        },
        {
            item_id=78,
            reward_item=_itemlist.i_25688_2_1
        },
        {
            type=1,
            item_id=78,
            reward_item=_itemlist.i_27671_5_1
        },
        {
            type=2,
            item_id=78,
            reward_item=_itemlist.i_27672_2_1
        },
        {
            type=3,
            item_id=78,
            reward_item=_itemlist.i_22014_30_1
        },
        {
            item_id=79,
            reward_item=_itemlist.i_27541_6_1
        },
        {
            type=1,
            item_id=79,
            reward_item=_itemlist.i_29021_10_1
        },
        {
            type=2,
            item_id=79,
            reward_item=_itemlist.i_27399_6_1
        },
        {
            type=3,
            item_id=79,
            reward_item=_itemlist.i_27540_2_1
        },
        {
            item_id=80,
            reward_item=_itemlist.i_27665_7_1
        },
        {
            type=1,
            item_id=80,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            type=2,
            item_id=80,
            reward_item=_itemlist.i_27656_1_1
        },
        {
            type=3,
            item_id=80,
            reward_item=_itemlist.i_27655_3_1
        },
        {
            item_id=81,
            reward_item=_itemlist.i_27187_28_1
        },
        {
            type=1,
            item_id=81,
            reward_item=_itemlist.i_25520_1_1
        },
        {
            type=2,
            item_id=81,
            reward_item=_itemlist.i_24557_2_1
        },
        {
            type=3,
            item_id=81,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            item_id=82,
            reward_item=_itemlist.i_27723_15_1
        },
        {
            type=1,
            item_id=82,
            reward_item=_itemlist.i_27656_2_1
        },
        {
            type=2,
            item_id=82,
            reward_item=_itemlist.i_27655_5_1
        },
        {
            type=3,
            item_id=82,
            reward_item=_itemlist.i_27665_1_1
        },
        {
            item_id=83,
            reward_item=_itemlist.i_26416_25_1
        },
        {
            type=1,
            item_id=83,
            reward_item=_itemlist.i_25520_1_1
        },
        {
            type=2,
            item_id=83,
            reward_item=_itemlist.i_24557_2_1
        },
        {
            type=3,
            item_id=83,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            item_id=84,
            reward_item=_itemlist.i_26688_50_1
        },
        {
            type=1,
            item_id=84,
            reward_item=_itemlist.i_26687_10_1
        },
        {
            type=2,
            item_id=84,
            reward_item=_itemlist.i_26773_10_1
        },
        {
            type=3,
            item_id=84,
            reward_item=_itemlist.i_26689_30_1
        },
        {
            item_id=85,
            reward_item=_itemlist.i_28658_1_1
        },
        {
            type=1,
            item_id=85,
            reward_item=_itemlist.i_27657_3_1
        },
        {
            type=2,
            item_id=85,
            reward_item=_itemlist.i_27656_5_1
        },
        {
            type=3,
            item_id=85,
            reward_item=_itemlist.i_27665_5_1
        },
        {
            item_id=86,
            reward_item=_itemlist.i_28773_1_1
        },
        {
            type=1,
            item_id=86,
            reward_item=_itemlist.i_27479_10_1
        },
        {
            type=2,
            item_id=86,
            reward_item=_itemlist.i_24557_1_1
        },
        {
            type=3,
            item_id=86,
            reward_item=_itemlist.i_28772_1_1
        },
        {
            item_id=87,
            reward_item=_itemlist.i_27723_2_1
        },
        {
            type=1,
            item_id=87,
            reward_item=_itemlist.i_27656_1_1
        },
        {
            type=2,
            item_id=87,
            reward_item=_itemlist.i_27655_2_1
        },
        {
            type=3,
            item_id=87,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            item_id=88,
            reward_item=_itemlist.i_27541_6_1
        },
        {
            type=1,
            item_id=88,
            reward_item=_itemlist.i_29021_12_1
        },
        {
            type=2,
            item_id=88,
            reward_item=_itemlist.i_27399_6_1
        },
        {
            type=3,
            item_id=88,
            reward_item=_itemlist.i_27540_2_1
        },
        {
            item_id=89,
            reward_item=_itemlist.i_27665_7_1
        },
        {
            type=1,
            item_id=89,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            type=2,
            item_id=89,
            reward_item=_itemlist.i_27656_1_1
        },
        {
            type=3,
            item_id=89,
            reward_item=_itemlist.i_27655_3_1
        },
        {
            item_id=90,
            reward_item=_itemlist.i_27187_28_1
        },
        {
            type=1,
            item_id=90,
            reward_item=_itemlist.i_25520_1_1
        },
        {
            type=2,
            item_id=90,
            reward_item=_itemlist.i_24557_2_1
        },
        {
            type=3,
            item_id=90,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            item_id=91,
            reward_item=_itemlist.i_27723_15_1
        },
        {
            type=1,
            item_id=91,
            reward_item=_itemlist.i_27656_2_1
        },
        {
            type=2,
            item_id=91,
            reward_item=_itemlist.i_27655_5_1
        },
        {
            type=3,
            item_id=91,
            reward_item=_itemlist.i_27665_1_1
        },
        {
            item_id=92,
            reward_item=_itemlist.i_26416_27_1
        },
        {
            type=1,
            item_id=92,
            reward_item=_itemlist.i_25520_1_1
        },
        {
            type=2,
            item_id=92,
            reward_item=_itemlist.i_24557_2_1
        },
        {
            type=3,
            item_id=92,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            item_id=93,
            reward_item=_itemlist.i_26688_50_1
        },
        {
            type=1,
            item_id=93,
            reward_item=_itemlist.i_26687_10_1
        },
        {
            type=2,
            item_id=93,
            reward_item=_itemlist.i_26773_10_1
        },
        {
            type=3,
            item_id=93,
            reward_item=_itemlist.i_26689_30_1
        },
        {
            item_id=94,
            reward_item=_itemlist.i_28658_1_1
        },
        {
            type=1,
            item_id=94,
            reward_item=_itemlist.i_27657_3_1
        },
        {
            type=2,
            item_id=94,
            reward_item=_itemlist.i_27656_5_1
        },
        {
            type=3,
            item_id=94,
            reward_item=_itemlist.i_27665_5_1
        },
        {
            item_id=95,
            reward_item=_itemlist.i_28773_1_1
        },
        {
            type=1,
            item_id=95,
            reward_item=_itemlist.i_27479_10_1
        },
        {
            type=2,
            item_id=95,
            reward_item=_itemlist.i_24557_1_1
        },
        {
            type=3,
            item_id=95,
            reward_item=_itemlist.i_28772_1_1
        },
        {
            item_id=96,
            reward_item=_itemlist.i_25688_2_1
        },
        {
            type=1,
            item_id=96,
            reward_item=_itemlist.i_27671_5_1
        },
        {
            type=2,
            item_id=96,
            reward_item=_itemlist.i_27672_2_1
        },
        {
            type=3,
            item_id=96,
            reward_item=_itemlist.i_22014_30_1
        },
        {
            item_id=97,
            reward_item=_itemlist.i_27541_6_1
        },
        {
            type=1,
            item_id=97,
            reward_item=_itemlist.i_29021_15_1
        },
        {
            type=2,
            item_id=97,
            reward_item=_itemlist.i_27399_6_1
        },
        {
            type=3,
            item_id=97,
            reward_item=_itemlist.i_27540_2_1
        },
        {
            item_id=98,
            reward_item=_itemlist.i_27665_7_1
        },
        {
            type=1,
            item_id=98,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            type=2,
            item_id=98,
            reward_item=_itemlist.i_27656_1_1
        },
        {
            type=3,
            item_id=98,
            reward_item=_itemlist.i_27655_3_1
        },
        {
            item_id=99,
            reward_item=_itemlist.i_27187_30_1
        },
        {
            type=1,
            item_id=99,
            reward_item=_itemlist.i_25520_1_1
        },
        {
            type=2,
            item_id=99,
            reward_item=_itemlist.i_24557_2_1
        },
        {
            type=3,
            item_id=99,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            item_id=100,
            reward_item=_itemlist.i_27723_15_1
        },
        {
            type=1,
            item_id=100,
            reward_item=_itemlist.i_27656_2_1
        },
        {
            type=2,
            item_id=100,
            reward_item=_itemlist.i_27655_5_1
        },
        {
            type=3,
            item_id=100,
            reward_item=_itemlist.i_27665_1_1
        },
        {
            item_id=101,
            reward_item=_itemlist.i_26416_30_1
        },
        {
            type=1,
            item_id=101,
            reward_item=_itemlist.i_25520_1_1
        },
        {
            type=2,
            item_id=101,
            reward_item=_itemlist.i_24557_2_1
        },
        {
            type=3,
            item_id=101,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            item_id=102,
            reward_item=_itemlist.i_26688_50_1
        },
        {
            type=1,
            item_id=102,
            reward_item=_itemlist.i_26687_10_1
        },
        {
            type=2,
            item_id=102,
            reward_item=_itemlist.i_26773_10_1
        },
        {
            type=3,
            item_id=102,
            reward_item=_itemlist.i_26689_30_1
        },
        {
            item_id=103,
            reward_item=_itemlist.i_28658_1_1
        },
        {
            type=1,
            item_id=103,
            reward_item=_itemlist.i_27657_3_1
        },
        {
            type=2,
            item_id=103,
            reward_item=_itemlist.i_27656_5_1
        },
        {
            type=3,
            item_id=103,
            reward_item=_itemlist.i_27665_5_1
        },
        {
            item_id=104,
            reward_item=_itemlist.i_28773_1_1
        },
        {
            type=1,
            item_id=104,
            reward_item=_itemlist.i_27479_10_1
        },
        {
            type=2,
            item_id=104,
            reward_item=_itemlist.i_24557_1_1
        },
        {
            type=3,
            item_id=104,
            reward_item=_itemlist.i_28772_1_1
        },
        {
            item_id=105,
            reward_item=_itemlist.i_25688_1_1
        },
        {
            type=1,
            item_id=105,
            reward_item=_itemlist.i_27666_500_1
        },
        {
            type=2,
            item_id=105,
            reward_item=_itemlist.i_27672_3_1
        },
        {
            type=3,
            item_id=105,
            reward_item=_itemlist.i_22014_20_1
        },
        {
            item_id=106,
            reward_item=_itemlist.i_27541_6_1
        },
        {
            type=1,
            item_id=106,
            reward_item=_itemlist.i_29021_15_1
        },
        {
            type=2,
            item_id=106,
            reward_item=_itemlist.i_27399_6_1
        },
        {
            type=3,
            item_id=106,
            reward_item=_itemlist.i_27540_2_1
        },
        {
            item_id=107,
            reward_item=_itemlist.i_27665_7_1
        },
        {
            type=1,
            item_id=107,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            type=2,
            item_id=107,
            reward_item=_itemlist.i_27656_1_1
        },
        {
            type=3,
            item_id=107,
            reward_item=_itemlist.i_27655_3_1
        },
        {
            item_id=108,
            reward_item=_itemlist.i_27187_30_1
        },
        {
            type=1,
            item_id=108,
            reward_item=_itemlist.i_25520_1_1
        },
        {
            type=2,
            item_id=108,
            reward_item=_itemlist.i_24557_2_1
        },
        {
            type=3,
            item_id=108,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            item_id=109,
            reward_item=_itemlist.i_27723_15_1
        },
        {
            type=1,
            item_id=109,
            reward_item=_itemlist.i_27656_2_1
        },
        {
            type=2,
            item_id=109,
            reward_item=_itemlist.i_27655_5_1
        },
        {
            type=3,
            item_id=109,
            reward_item=_itemlist.i_27665_1_1
        },
        {
            item_id=110,
            reward_item=_itemlist.i_26416_30_1
        },
        {
            type=1,
            item_id=110,
            reward_item=_itemlist.i_25520_1_1
        },
        {
            type=2,
            item_id=110,
            reward_item=_itemlist.i_24557_2_1
        },
        {
            type=3,
            item_id=110,
            reward_item=_itemlist.i_27664_2_1
        },
        {
            item_id=111,
            reward_item=_itemlist.i_26688_50_1
        },
        {
            type=1,
            item_id=111,
            reward_item=_itemlist.i_26687_10_1
        },
        {
            type=2,
            item_id=111,
            reward_item=_itemlist.i_26773_10_1
        },
        {
            type=3,
            item_id=111,
            reward_item=_itemlist.i_26689_30_1
        },
        {
            item_id=112,
            reward_item=_itemlist.i_28658_1_1
        },
        {
            type=1,
            item_id=112,
            reward_item=_itemlist.i_27657_3_1
        },
        {
            type=2,
            item_id=112,
            reward_item=_itemlist.i_27656_5_1
        },
        {
            type=3,
            item_id=112,
            reward_item=_itemlist.i_27665_5_1
        },
        {
            item_id=113,
            reward_item=_itemlist.i_28947_1_1
        },
        {
            type=1,
            item_id=113,
            reward_item=_itemlist.i_22007_300_1
        },
        {
            type=2,
            item_id=113,
            reward_item=_itemlist.i_27403_1_1
        },
        {
            type=3,
            item_id=113,
            reward_item=_itemlist.i_24557_1_1
        },
        {
            item_id=114,
            reward_item=_itemlist.i_28926_1_1
        },
        {
            type=1,
            item_id=114,
            reward_item=_itemlist.i_22007_300_1
        },
        {
            type=2,
            item_id=114,
            reward_item=_itemlist.i_27403_1_1
        },
        {
            type=3,
            item_id=114,
            reward_item=_itemlist.i_24557_1_1
        },
        {
            item_id=115,
            reward_item=_itemlist.i_28909_1_1
        },
        {
            type=1,
            item_id=115,
            reward_item=_itemlist.i_22007_300_1
        },
        {
            type=2,
            item_id=115,
            reward_item=_itemlist.i_27403_1_1
        },
        {
            type=3,
            item_id=115,
            reward_item=_itemlist.i_24557_1_1
        },
        {
            item_id=116,
            reward_item=_itemlist.i_28903_1_1
        },
        {
            type=1,
            item_id=116,
            reward_item=_itemlist.i_22007_300_1
        },
        {
            type=2,
            item_id=116,
            reward_item=_itemlist.i_27403_1_1
        },
        {
            type=3,
            item_id=116,
            reward_item=_itemlist.i_24557_1_1
        },
        {
            item_id=117,
            reward_item=_itemlist.i_31407_1_1
        },
        {
            type=1,
            item_id=117,
            reward_item=_itemlist.i_22007_300_1
        },
        {
            type=2,
            item_id=117,
            reward_item=_itemlist.i_27403_1_1
        },
        {
            type=3,
            item_id=117,
            reward_item=_itemlist.i_24557_1_1
        }
    },
    other={
        {
            cfg_ver=2,
            free_reward_item={
                [0]=_itemlist.i_22006_1_1
            }
        }
    }
}
SetConfigDefaultVal(Config.sijibaoxiang_auto,_default_val,nil,nil,nil)