local _default_val={
    story_list={
        type=1,
        res_name="story_harmony_heaven_3",
        can_skip=0,
        black_frame=0,
        param1=0
    },
    option_button={
        button_group=1,
        type=1,
        type_param1=0,
        show_color="f7cf6f"
    },
    scene_patrol={
        name="玄都守军",
        res_id=302,
        scene_id=108,
        xyz2=0,
        xyz3=0,
        xyz4=0,
        xyz5=0,
        xyz6=0,
        xyz7=0,
        xyz8=0,
        xyz9=0,
        xyz10=0,
        dir_y=-90,
        move_speed=2.5
    },
    recommend_job={
        button1=0,
        button2=0,
        button3=0
    },
    animation_story={
        name="刑天之死",
        type=100,
        res_name="RoleCreateStory",
        can_skip=1,
        param1=0,
        param2=0,
        param3=0,
        bullet_screen_group=0,
        mask=0
    },
    bullet_screen={
        bullet_screen_group=1,
        seq=1,
        bullet_screen=""
    }
}
Config.story_auto={
    story_list={
        {
            id=101,
            name="牛头变身",
            res_name="story_trans_1002"
        },
        {
            id=102,
            name="牛头skill_1_相机",
            res_name="story_skill_1002_1"
        },
        {
            id=103,
            name="牛头skill_2_相机",
            res_name="story_skill_1002_2"
        },
        {
            id=4,
            name="皇城展示",
            type=2,
            res_name="story_hc_show",
            param1=340
        },
        {
            id=104,
            name="牛妖王展示",
            res_name="story_showboss"
        },
        {
            id=201,
            name="游历诗人结束展示",
            type=3,
            res_name="story_poetry"
        },
        {
            id=105,
            name="刑天展示",
            res_name="story_xingtian_chuchang",
            param1=1014
        },
        {
            id=106,
            name="开幕式-战斗",
            res_name="story_origin_battle_start",
            param1=1001
        },
        {
            id=107,
            name="开幕式-战斗技能",
            res_name="story_origin_battle_skill",
            param1=1001
        },
        {
            id=108,
            name="心魔的打坐",
            type=2,
            res_name="story_xinmo_pre",
            can_skip=1,
            black_frame=1,
            param1=61
        },
        {
            id=109,
            name="结婚拜堂",
            res_name="story_wedding"
        },
        {
            id=110,
            name="师徒传功",
            res_name="story_shitu_chuangong"
        },
        {
            id=121,
            name="鸿蒙天界一",
            param1=1717
        },
        {
            id=122,
            name="鸿蒙天界二",
            res_name="story_harmony_heaven_5",
            param1=1711
        },
        {
            id=123,
            name="鸿蒙天界三",
            res_name="story_harmony_heaven_2",
            param1=1708
        },
        {
            id=124,
            name="鸿蒙天界四",
            res_name="story_harmony_heaven_6",
            param1=1702
        },
        {
            id=125,
            name="鸿蒙天界五",
            res_name="story_harmony_heaven_1",
            param1=1705
        },
        {
            id=126,
            name="鸿蒙天界一（英雄）",
            param1=1746
        },
        {
            id=127,
            name="鸿蒙天界二（英雄）",
            res_name="story_harmony_heaven_5",
            param1=1740
        },
        {
            id=128,
            name="鸿蒙天界三（英雄）",
            res_name="story_harmony_heaven_2",
            param1=1737
        },
        {
            id=129,
            name="鸿蒙天界四（英雄）",
            res_name="story_harmony_heaven_6",
            param1=1731
        },
        {
            id=130,
            name="鸿蒙天界五（英雄）",
            res_name="story_harmony_heaven_1",
            param1=1734
        },
        {
            id=131,
            name="鸿蒙天界六",
            res_name="story_harmony_heaven_7",
            param1=1714
        },
        {
            id=132,
            name="鸿蒙天界七",
            res_name="story_harmony_heaven_8",
            param1=1720
        },
        {
            id=133,
            name="鸿蒙天界八",
            res_name="story_harmony_heaven_9",
            param1=1723
        },
        {
            id=134,
            name="鸿蒙天界九",
            res_name="story_harmony_heaven_4",
            param1=1726
        },
        {
            id=135,
            name="鸿蒙天界六（英雄）",
            res_name="story_harmony_heaven_7",
            param1=1743
        },
        {
            id=136,
            name="鸿蒙天界七（英雄）",
            res_name="story_harmony_heaven_8",
            param1=1749
        },
        {
            id=137,
            name="鸿蒙天界八（英雄）",
            res_name="story_harmony_heaven_9",
            param1=1752
        },
        {
            id=138,
            name="鸿蒙天界九（英雄）",
            res_name="story_harmony_heaven_4",
            param1=1755
        },
        {
            id=141,
            name="鸿蒙登场一",
            type=101,
            res_name="story_hh_show_3",
            param1=334
        },
        {
            id=142,
            name="鸿蒙登场二",
            type=101,
            res_name="story_hh_show_5",
            param1=331
        },
        {
            id=143,
            name="鸿蒙登场三",
            type=101,
            res_name="story_hh_show_2",
            param1=332
        },
        {
            id=144,
            name="鸿蒙登场四",
            type=101,
            res_name="story_hh_show_6",
            param1=335
        },
        {
            id=145,
            name="鸿蒙登场五",
            type=101,
            res_name="story_hh_show_1",
            param1=330
        },
        {
            id=146,
            name="鸿蒙登场六",
            type=101,
            res_name="story_hh_show_7",
            param1=333
        },
        {
            id=147,
            name="鸿蒙登场七",
            type=101,
            res_name="story_hh_show_8",
            param1=336
        },
        {
            id=148,
            name="鸿蒙登场八",
            type=101,
            res_name="story_hh_show_9",
            param1=337
        },
        {
            id=149,
            name="鸿蒙登场九",
            type=101,
            res_name="story_hh_show_4",
            param1=338
        }
    },
    option={
        [1]={
            id=1,
            type=0,
            param1=10,
            show_text="<tab>上古时期，云泽大陆万族林立，各大种族表面上一片祥和，暗地里，以东皇太一为首，成立<color=#02cf7a>血盟</color>，自创邪恶永生功法，以吸取他人元气而延长寿命，被称为永生之祸，随着渴望永生的人越来越多，永生之祸开始波及万族，最终在伏羲，黄帝，共工等真神的带领下，万族联合击败了<color=#02cf7a>血盟</color>，重创了东皇太一。\n<tab>随着时间的推移，万族生活逐渐归于平静，但永生的诱惑，却始终萦绕，在平静之下，经过多年休养生息的血盟，又渐渐伸出了他们的魔爪，最近的一起修士失踪案件，就发生在玄都附近，一切的线索，仿佛都指向东皇太一的手下大将“<color=#02cf7a>刑天</color>”，在听到这个消息之后，我主动请缨，前往玄都调查此事。",
            button_group=1
        }
    },
    option_button={
        [1]={
            button_id=1,
            button_behavior="强横的力量",
            show_word="强横的力量，击破所有的防御，痛击敌人。"
        },
        [2]={
            button_id=2,
            button_behavior="多变的法术",
            show_word="多变的法术，操纵不同的元素，克制敌人。"
        },
        [3]={
            button_id=3,
            button_behavior="绝对的掌控",
            show_word="绝对的掌控，控制对方的行动，限制敌人。"
        }
    },
    scene_patrol={
        [1]={
            npc_index=1,
            res_id=303,
            birth_xyz="222|176",
            xyz1="222|204",
            destination_xyz="200|204",
            dir_y=180,
            bubble_id=1
        },
        [2]={
            npc_index=2,
            res_id=303,
            birth_xyz="191|227",
            xyz1="191|157",
            xyz2="148|157",
            destination_xyz="148|190",
            dir_y=180,
            bubble_id=2
        },
        [3]={
            npc_index=3,
            birth_xyz="232|158",
            xyz1=0,
            destination_xyz="132|158",
            bubble_id=3
        },
        [4]={
            npc_index=4,
            birth_xyz="222|144",
            xyz1="222|118",
            xyz2="191|118",
            destination_xyz="191|146",
            bubble_id=4
        },
        [5]={
            npc_index=5,
            birth_xyz="136|156",
            xyz1="151|156",
            xyz2="151|117",
            xyz3="191|117",
            destination_xyz="191|131",
            bubble_id=5
        }
    },
    recommend_job={
        [1]={
            seq=1,
            recommend_job="2|3|5"
        },
        [2]={
            seq=2,
            recommend_job="6|7"
        },
        [3]={
            seq=3,
            recommend_job="1|4|8"
        }
    },
    animation_story={
        {
            id=1,
            type=1,
            res_name="XingTianZhiSi",
            param1=1370,
            bullet_screen_group=2
        },
        {
            id=2,
            name="幽冥炼狱",
            res_name="YouMingLianYu"
        },
        {
            id=3,
            name="世界背景",
            type=1,
            res_name="XingTianZhanDou",
            param1=120,
            bullet_screen_group=1,
            mask=1
        },
        {
            id=4,
            name="开幕视频"
        },
        {
            id=5,
            name="世界背景11",
            res_name="OpenCG",
            param1=120,
            mask=1
        },
        {
            id=6,
            name="轮回忘川",
            res_name="WuJinZhiTa"
        },
        {
            id=7,
            name="初始防闪",
            can_skip=0
        },
        {
            id=8,
            name="角色飞升",
            res_name="RoleFeisheng"
        },
        {
            id=9,
            type=1,
            res_name="XingTianZhiSi",
            param1=716,
            bullet_screen_group=2
        }
    },
    bullet_screen={
        {
            bullet_screen="前排"
        },
        {
            seq=2,
            bullet_screen="前排"
        },
        {
            seq=3,
            bullet_screen="卧槽牛脾"
        },
        {
            seq=4,
            bullet_screen="怎么组队"
        },
        {
            seq=5,
            bullet_screen="有一起玩的吗"
        },
        {
            seq=6,
            bullet_screen="*******"
        },
        {
            seq=7
        },
        {
            seq=8
        },
        {
            seq=9
        },
        {
            seq=10,
            bullet_screen="有一起玩的吗"
        },
        {
            seq=11
        },
        {
            seq=12
        },
        {
            seq=13
        },
        {
            seq=14,
            bullet_screen="前排"
        },
        {
            seq=15,
            bullet_screen="有活人吗"
        },
        {
            seq=16,
            bullet_screen="小姐姐"
        },
        {
            seq=17,
            bullet_screen="我*"
        },
        {
            seq=18,
            bullet_screen="小姐姐声音好好听"
        },
        {
            seq=19,
            bullet_screen="您正在使用移动4G网络"
        },
        {
            seq=20,
            bullet_screen="声音好听"
        },
        {
            seq=21
        },
        {
            seq=22
        },
        {
            seq=23,
            bullet_screen="策划给老子滚出来"
        },
        {
            seq=24
        },
        {
            seq=25
        },
        {
            seq=26
        },
        {
            seq=27
        },
        {
            seq=28,
            bullet_screen="小姐姐"
        },
        {
            seq=29,
            bullet_screen="策划给老子滚出来"
        },
        {
            seq=30,
            bullet_screen="堪比迪士尼"
        },
        {
            seq=31,
            bullet_screen="我*"
        },
        {
            seq=32,
            bullet_screen="*****"
        },
        {
            seq=33,
            bullet_screen=66666
        },
        {
            seq=34,
            bullet_screen="*****"
        },
        {
            seq=35,
            bullet_screen="点赞"
        },
        {
            seq=36
        },
        {
            seq=37
        },
        {
            seq=38
        },
        {
            seq=39,
            bullet_screen="点赞"
        },
        {
            seq=40
        },
        {
            seq=41
        },
        {
            seq=42
        },
        {
            seq=43,
            bullet_screen="加我看片"
        },
        {
            seq=44,
            bullet_screen="点赞"
        },
        {
            seq=45,
            bullet_screen="yyds"
        },
        {
            seq=46,
            bullet_screen="？？？？？？？？"
        },
        {
            seq=47,
            bullet_screen="怎么暂停"
        },
        {
            seq=48,
            bullet_screen="我是会员"
        },
        {
            seq=49,
            bullet_screen="您正在使用移动4G网络"
        },
        {
            seq=50
        },
        {
            seq=51
        },
        {
            seq=52
        },
        {
            seq=53,
            bullet_screen="什么职业厉害"
        },
        {
            seq=54
        },
        {
            seq=55
        },
        {
            seq=56
        },
        {
            seq=57
        },
        {
            seq=58,
            bullet_screen="WIFI连接已断开"
        },
        {
            seq=59,
            bullet_screen="您正在使用运营商网络"
        },
        {
            seq=60,
            bullet_screen="****"
        },
        {
            seq=61,
            bullet_screen="四大元素"
        },
        {
            seq=62,
            bullet_screen="您正在使用移动4G网络"
        },
        {
            seq=63
        },
        {
            seq=64
        },
        {
            seq=65
        },
        {
            seq=66
        },
        {
            seq=67
        },
        {
            seq=68
        },
        {
            seq=69
        },
        {
            seq=70,
            bullet_screen="东皇太一牛脾"
        },
        {
            seq=71,
            bullet_screen="策划给老子滚出来"
        },
        {
            seq=72,
            bullet_screen="有一起玩的吗"
        },
        {
            seq=73,
            bullet_screen="什么职业厉害"
        },
        {
            seq=74,
            bullet_screen="东皇太医干嘛的"
        },
        {
            seq=75,
            bullet_screen="WIFI连接已断开"
        },
        {
            seq=76
        },
        {
            seq=77
        },
        {
            seq=78
        },
        {
            seq=79,
            bullet_screen="四大魔神使都是谁哦"
        },
        {
            seq=80
        },
        {
            seq=81
        },
        {
            seq=82
        },
        {
            seq=83,
            bullet_screen="女娲？"
        },
        {
            seq=84,
            bullet_screen="听君一席话胜似一席话"
        },
        {
            seq=85,
            bullet_screen="说一个神话，话说那么一家"
        },
        {
            seq=86,
            bullet_screen="？？？"
        },
        {
            seq=87,
            bullet_screen="怎么看战力"
        },
        {
            seq=88,
            bullet_screen="祝融yyds"
        },
        {
            seq=89,
            bullet_screen="东皇太一开大了"
        },
        {
            seq=90,
            bullet_screen="四大魔神使都是谁哦"
        },
        {
            seq=91
        },
        {
            seq=92
        },
        {
            seq=93
        },
        {
            seq=94,
            bullet_screen="听君一席话胜似一席话"
        },
        {
            seq=95
        },
        {
            seq=96
        },
        {
            seq=97
        },
        {
            seq=98,
            bullet_screen="东皇太医干嘛的"
        },
        {
            seq=99,
            bullet_screen="WIFI连接已断开"
        },
        {
            seq=100,
            bullet_screen="女娲？"
        },
        {
            seq=101,
            bullet_screen="听君一席话胜似一席话"
        },
        {
            seq=102,
            bullet_screen="说一个神话，话说那么一家"
        },
        {
            seq=103,
            bullet_screen="我反手一巴掌"
        },
        {
            seq=104,
            bullet_screen="为什么"
        },
        {
            seq=105
        },
        {
            seq=106
        },
        {
            seq=107
        },
        {
            seq=108,
            bullet_screen="堪比迪士尼"
        },
        {
            seq=109
        },
        {
            seq=110
        },
        {
            seq=111
        },
        {
            seq=112,
            bullet_screen="魔神使都是谁"
        },
        {
            seq=113,
            bullet_screen="共工打得过东皇？"
        },
        {
            seq=114,
            bullet_screen="怎么组队"
        },
        {
            seq=115,
            bullet_screen="有一起玩的吗"
        },
        {
            seq=116,
            bullet_screen="什么职业厉害"
        },
        {
            seq=117,
            bullet_screen="听君一席话胜似一席话"
        },
        {
            seq=118,
            bullet_screen="章鱼哥"
        },
        {
            seq=119
        },
        {
            seq=120
        },
        {
            seq=121
        },
        {
            seq=122,
            bullet_screen="不听老人言，等于没听见"
        },
        {
            seq=123
        },
        {
            seq=124
        },
        {
            seq=125
        },
        {
            seq=126,
            bullet_screen="有一起玩的吗"
        },
        {
            seq=127,
            bullet_screen="为什么"
        },
        {
            seq=128,
            bullet_screen="章鱼哥"
        },
        {
            seq=129,
            bullet_screen="大战旷日持久"
        },
        {
            seq=130,
            bullet_screen="都是我的小号"
        },
        {
            seq=131,
            bullet_screen="堪比迪士尼"
        },
        {
            seq=132,
            bullet_screen="我*"
        },
        {
            seq=133
        },
        {
            seq=134
        },
        {
            seq=135
        },
        {
            seq=136
        },
        {
            seq=137
        },
        {
            seq=138
        },
        {
            seq=139
        },
        {
            seq=140,
            bullet_screen="*****"
        },
        {
            seq=141,
            bullet_screen="章鱼哥"
        },
        {
            seq=142,
            bullet_screen="听君一席话胜似一席话"
        },
        {
            seq=143,
            bullet_screen="不听老人言，等于没听见"
        },
        {
            seq=144,
            bullet_screen="方晨在吗"
        },
        {
            seq=145,
            bullet_screen="听君一席话胜似一席话"
        },
        {
            seq=146,
            bullet_screen="我透"
        },
        {
            seq=147,
            bullet_screen="有一起玩的吗"
        },
        {
            seq=148
        },
        {
            seq=149
        },
        {
            seq=150
        },
        {
            seq=151,
            bullet_screen="*****"
        },
        {
            seq=152
        },
        {
            seq=153
        },
        {
            seq=154
        },
        {
            seq=155,
            bullet_screen="钲洋我爱你"
        },
        {
            seq=156,
            bullet_screen="我不知道"
        },
        {
            seq=157,
            bullet_screen=66666
        },
        {
            seq=158,
            bullet_screen="*****"
        },
        {
            seq=159,
            bullet_screen="好莱坞大片"
        },
        {
            seq=160,
            bullet_screen="我透"
        },
        {
            seq=161
        },
        {
            seq=162
        },
        {
            seq=163
        },
        {
            seq=164,
            bullet_screen="血盟是干嘛的"
        },
        {
            seq=165
        },
        {
            seq=166
        },
        {
            seq=167
        },
        {
            seq=168,
            bullet_screen="大会赞之后"
        },
        {
            seq=169,
            bullet_screen="额威威企鹅"
        },
        {
            seq=170,
            bullet_screen="饿热特热微软"
        },
        {
            seq=171,
            bullet_screen="的撒大大"
        },
        {
            seq=172,
            bullet_screen="堕神契约堕神契约堕神契约堕神契约堕神契约"
        },
        {
            seq=173,
            bullet_screen="血盟是干嘛的"
        },
        {
            seq=174,
            bullet_screen="有一起玩的吗"
        },
        {
            seq=175,
            bullet_screen="复仇者联盟"
        },
        {
            seq=176,
            bullet_screen="莫璃我老婆"
        },
        {
            seq=177
        },
        {
            seq=178
        },
        {
            seq=179
        },
        {
            seq=180,
            bullet_screen="大师傅但是"
        },
        {
            seq=181
        },
        {
            seq=182
        },
        {
            seq=183
        },
        {
            seq=184,
            bullet_screen="分为氛围"
        },
        {
            seq=185,
            bullet_screen="声音好听"
        },
        {
            seq=186,
            bullet_screen="小姐姐"
        },
        {
            seq=187,
            bullet_screen="策划给老子滚出来"
        },
        {
            seq=188,
            bullet_screen="时尚大方"
        },
        {
            seq=189,
            bullet_screen="我*"
        },
        {
            seq=190
        },
        {
            seq=191
        },
        {
            seq=192
        },
        {
            seq=193,
            bullet_screen="血盟是干嘛的"
        },
        {
            seq=194
        },
        {
            seq=195
        },
        {
            seq=196
        },
        {
            seq=197,
            bullet_screen="分为氛围"
        },
        {
            seq=198,
            bullet_screen="血盟是干嘛的"
        },
        {
            seq=199,
            bullet_screen="卧槽牛脾"
        },
        {
            seq=200,
            bullet_screen="听君一席话胜似一席话"
        },
        {
            bullet_screen_group=2,
            bullet_screen="抢个沙发"
        },
        {
            bullet_screen_group=2,
            seq=2,
            bullet_screen="赞"
        },
        {
            bullet_screen_group=2,
            seq=3,
            bullet_screen="好评"
        },
        {
            bullet_screen_group=2,
            seq=4,
            bullet_screen="我又来了"
        },
        {
            bullet_screen_group=2,
            seq=5
        },
        {
            bullet_screen_group=2,
            seq=6,
            bullet_screen="刑天点起烟说起从前"
        },
        {
            bullet_screen_group=2,
            seq=7,
            bullet_screen="大制作啊"
        },
        {
            bullet_screen_group=2,
            seq=8
        },
        {
            bullet_screen_group=2,
            seq=9,
            bullet_screen="有小姐姐吗"
        },
        {
            bullet_screen_group=2,
            seq=10
        },
        {
            bullet_screen_group=2,
            seq=11
        },
        {
            bullet_screen_group=2,
            seq=12,
            bullet_screen="这游戏氪吗"
        },
        {
            bullet_screen_group=2,
            seq=13,
            bullet_screen="做啥游戏啊，做动漫去啊"
        },
        {
            bullet_screen_group=2,
            seq=14,
            bullet_screen="不错的游戏"
        },
        {
            bullet_screen_group=2,
            seq=15,
            bullet_screen="刑天YYDS"
        },
        {
            bullet_screen_group=2,
            seq=16,
            bullet_screen="有小姐姐吗"
        },
        {
            bullet_screen_group=2,
            seq=17,
            bullet_screen="我*"
        },
        {
            bullet_screen_group=2,
            seq=18,
            bullet_screen="mua~"
        },
        {
            bullet_screen_group=2,
            seq=19,
            bullet_screen="很少有游戏在剧情上下这么大功夫的"
        },
        {
            bullet_screen_group=2,
            seq=20
        },
        {
            bullet_screen_group=2,
            seq=21
        },
        {
            bullet_screen_group=2,
            seq=22
        },
        {
            bullet_screen_group=2,
            seq=23,
            bullet_screen="？？？？？？？？"
        },
        {
            bullet_screen_group=2,
            seq=24
        },
        {
            bullet_screen_group=2,
            seq=25
        },
        {
            bullet_screen_group=2,
            seq=26
        },
        {
            bullet_screen_group=2,
            seq=27,
            bullet_screen="我，刑天，打钱"
        },
        {
            bullet_screen_group=2,
            seq=28,
            bullet_screen="加我看片"
        },
        {
            bullet_screen_group=2,
            seq=29,
            bullet_screen="？？？？？？？？"
        },
        {
            bullet_screen_group=2,
            seq=30,
            bullet_screen="刑天不是伙伴吗"
        },
        {
            bullet_screen_group=2,
            seq=31,
            bullet_screen="我*"
        },
        {
            bullet_screen_group=2,
            seq=32,
            bullet_screen="刑天点起烟说起从前"
        },
        {
            bullet_screen_group=2,
            seq=33,
            bullet_screen=66666
        },
        {
            bullet_screen_group=2,
            seq=34,
            bullet_screen="剧情党的福音"
        },
        {
            bullet_screen_group=2,
            seq=35
        },
        {
            bullet_screen_group=2,
            seq=36,
            bullet_screen="玩玩看看"
        },
        {
            bullet_screen_group=2,
            seq=37
        },
        {
            bullet_screen_group=2,
            seq=38
        },
        {
            bullet_screen_group=2,
            seq=39,
            bullet_screen="净整花里胡哨的"
        },
        {
            bullet_screen_group=2,
            seq=40
        },
        {
            bullet_screen_group=2,
            seq=41,
            bullet_screen="*****"
        },
        {
            bullet_screen_group=2,
            seq=42,
            bullet_screen="好莱坞大片"
        },
        {
            bullet_screen_group=2,
            seq=43,
            bullet_screen="加我看片"
        },
        {
            bullet_screen_group=2,
            seq=44,
            bullet_screen="点赞"
        },
        {
            bullet_screen_group=2,
            seq=45,
            bullet_screen="yyds"
        },
        {
            bullet_screen_group=2,
            seq=46,
            bullet_screen="？？？？？？？？"
        },
        {
            bullet_screen_group=2,
            seq=47,
            bullet_screen="刑天：我直接一个断头台"
        },
        {
            bullet_screen_group=2,
            seq=48,
            bullet_screen="有端游吗"
        },
        {
            bullet_screen_group=2,
            seq=49
        },
        {
            bullet_screen_group=2,
            seq=50
        },
        {
            bullet_screen_group=2,
            seq=51,
            bullet_screen="刑天点起烟说起从前"
        },
        {
            bullet_screen_group=2,
            seq=52
        },
        {
            bullet_screen_group=2,
            seq=53
        },
        {
            bullet_screen_group=2,
            seq=54
        },
        {
            bullet_screen_group=2,
            seq=55,
            bullet_screen="刑天：我抬手外圈刮"
        },
        {
            bullet_screen_group=2,
            seq=56,
            bullet_screen="是新服吗是新服吗"
        },
        {
            bullet_screen_group=2,
            seq=57,
            bullet_screen="画面还行"
        },
        {
            bullet_screen_group=2,
            seq=58,
            bullet_screen="好安逸哦"
        },
        {
            bullet_screen_group=2,
            seq=59,
            bullet_screen="****"
        },
        {
            bullet_screen_group=2,
            seq=60,
            bullet_screen="为啥"
        },
        {
            bullet_screen_group=2,
            seq=61,
            bullet_screen="不错的游戏"
        },
        {
            bullet_screen_group=2,
            seq=62,
            bullet_screen="刑天点起烟说起从前"
        },
        {
            bullet_screen_group=2,
            seq=63,
            bullet_screen="剧情牛逼"
        },
        {
            bullet_screen_group=2,
            seq=64
        },
        {
            bullet_screen_group=2,
            seq=65
        },
        {
            bullet_screen_group=2,
            seq=66,
            bullet_screen="能下载码"
        },
        {
            bullet_screen_group=2,
            seq=67
        },
        {
            bullet_screen_group=2,
            seq=68
        },
        {
            bullet_screen_group=2,
            seq=69
        },
        {
            bullet_screen_group=2,
            seq=70,
            bullet_screen="策划给老子滚出来"
        },
        {
            bullet_screen_group=2,
            seq=71,
            bullet_screen="这个剧情加分了"
        },
        {
            bullet_screen_group=2,
            seq=72,
            bullet_screen="配音还可以"
        },
        {
            bullet_screen_group=2,
            seq=73,
            bullet_screen="刑天干嘛的"
        },
        {
            bullet_screen_group=2,
            seq=74,
            bullet_screen="来了来了"
        },
        {
            bullet_screen_group=2,
            seq=75,
            bullet_screen="皇帝呢？"
        },
        {
            bullet_screen_group=2,
            seq=76,
            bullet_screen="听君一席话胜似一席话"
        },
        {
            bullet_screen_group=2,
            seq=77
        },
        {
            bullet_screen_group=2,
            seq=78
        },
        {
            bullet_screen_group=2,
            seq=79
        },
        {
            bullet_screen_group=2,
            seq=80,
            bullet_screen="大师傅士大夫"
        },
        {
            bullet_screen_group=2,
            seq=81
        },
        {
            bullet_screen_group=2,
            seq=82
        },
        {
            bullet_screen_group=2,
            seq=83
        },
        {
            bullet_screen_group=2,
            seq=84,
            bullet_screen="卧槽泪目"
        },
        {
            bullet_screen_group=2,
            seq=85,
            bullet_screen="？？？"
        },
        {
            bullet_screen_group=2,
            seq=86,
            bullet_screen="怎么看战力"
        },
        {
            bullet_screen_group=2,
            seq=87,
            bullet_screen="刑天yyds"
        },
        {
            bullet_screen_group=2,
            seq=88,
            bullet_screen="刑天开大了"
        },
        {
            bullet_screen_group=2,
            seq=89,
            bullet_screen="四大魔神使都是谁哦"
        },
        {
            bullet_screen_group=2,
            seq=90,
            bullet_screen="不作就不会死"
        },
        {
            bullet_screen_group=2,
            seq=91
        },
        {
            bullet_screen_group=2,
            seq=92
        },
        {
            bullet_screen_group=2,
            seq=93
        },
        {
            bullet_screen_group=2,
            seq=94,
            bullet_screen="为什么"
        },
        {
            bullet_screen_group=2,
            seq=95
        },
        {
            bullet_screen_group=2,
            seq=96
        },
        {
            bullet_screen_group=2,
            seq=97
        },
        {
            bullet_screen_group=2,
            seq=98,
            bullet_screen="是新游戏嘛"
        },
        {
            bullet_screen_group=2,
            seq=99,
            bullet_screen="打架啊"
        },
        {
            bullet_screen_group=2,
            seq=100,
            bullet_screen="听君一席话胜似一席话"
        },
        {
            bullet_screen_group=2,
            seq=101,
            bullet_screen="有知道结局的吗"
        },
        {
            bullet_screen_group=2,
            seq=102,
            bullet_screen="我反手一巴掌"
        },
        {
            bullet_screen_group=2,
            seq=103,
            bullet_screen="为什么"
        },
        {
            bullet_screen_group=2,
            seq=104,
            bullet_screen="刑天是魔神使吗"
        },
        {
            bullet_screen_group=2,
            seq=105
        },
        {
            bullet_screen_group=2,
            seq=106
        },
        {
            bullet_screen_group=2,
            seq=107,
            bullet_screen="有一起玩的吗"
        },
        {
            bullet_screen_group=2,
            seq=108
        },
        {
            bullet_screen_group=2,
            seq=109
        },
        {
            bullet_screen_group=2,
            seq=110
        },
        {
            bullet_screen_group=2,
            seq=111
        },
        {
            bullet_screen_group=2,
            seq=112,
            bullet_screen="刑天的头怎么掉的"
        },
        {
            bullet_screen_group=2,
            seq=113,
            bullet_screen="怎么组队"
        },
        {
            bullet_screen_group=2,
            seq=114,
            bullet_screen="有一起玩的吗"
        },
        {
            bullet_screen_group=2,
            seq=115,
            bullet_screen="什么职业厉害"
        },
        {
            bullet_screen_group=2,
            seq=116,
            bullet_screen="皇帝砍的"
        },
        {
            bullet_screen_group=2,
            seq=117,
            bullet_screen="章鱼哥"
        },
        {
            bullet_screen_group=2,
            seq=118,
            bullet_screen="哈哈哈哈哈哈哈哈哈哈哈哈"
        },
        {
            bullet_screen_group=2,
            seq=119
        },
        {
            bullet_screen_group=2,
            seq=120,
            bullet_screen="那**是黄帝"
        },
        {
            bullet_screen_group=2,
            seq=121
        },
        {
            bullet_screen_group=2,
            seq=122
        },
        {
            bullet_screen_group=2,
            seq=123,
            bullet_screen="我透"
        },
        {
            bullet_screen_group=2,
            seq=124
        },
        {
            bullet_screen_group=2,
            seq=125
        },
        {
            bullet_screen_group=2,
            seq=126
        },
        {
            bullet_screen_group=2,
            seq=127,
            bullet_screen="感觉还行"
        },
        {
            bullet_screen_group=2,
            seq=128,
            bullet_screen="脾气暴躁"
        },
        {
            bullet_screen_group=2,
            seq=129,
            bullet_screen="都是我的小号"
        },
        {
            bullet_screen_group=2,
            seq=130,
            bullet_screen="突然觉得好虐啊"
        },
        {
            bullet_screen_group=2,
            seq=131,
            bullet_screen="我*"
        },
        {
            bullet_screen_group=2,
            seq=132,
            bullet_screen="*****"
        },
        {
            bullet_screen_group=2,
            seq=133,
            bullet_screen="期待后续的剧情"
        },
        {
            bullet_screen_group=2,
            seq=134
        },
        {
            bullet_screen_group=2,
            seq=135
        },
        {
            bullet_screen_group=2,
            seq=136
        },
        {
            bullet_screen_group=2,
            seq=137
        },
        {
            bullet_screen_group=2,
            seq=138
        },
        {
            bullet_screen_group=2,
            seq=139
        },
        {
            bullet_screen_group=2,
            seq=140
        },
        {
            bullet_screen_group=2,
            seq=141,
            bullet_screen="剧情和画质可以的"
        },
        {
            bullet_screen_group=2,
            seq=142,
            bullet_screen="不听老人言，等于没听见"
        },
        {
            bullet_screen_group=2,
            seq=143,
            bullet_screen="方晨在吗"
        },
        {
            bullet_screen_group=2,
            seq=144,
            bullet_screen="胡冰心看到了吗"
        },
        {
            bullet_screen_group=2,
            seq=145,
            bullet_screen="我透，穿越了"
        },
        {
            bullet_screen_group=2,
            seq=146,
            bullet_screen="有一起玩的吗"
        },
        {
            bullet_screen_group=2,
            seq=147,
            bullet_screen="刑天无了？"
        },
        {
            bullet_screen_group=2,
            seq=148
        },
        {
            bullet_screen_group=2,
            seq=149
        },
        {
            bullet_screen_group=2,
            seq=150
        },
        {
            bullet_screen_group=2,
            seq=151,
            bullet_screen="我透"
        },
        {
            bullet_screen_group=2,
            seq=152
        },
        {
            bullet_screen_group=2,
            seq=153
        },
        {
            bullet_screen_group=2,
            seq=154
        },
        {
            bullet_screen_group=2,
            seq=155,
            bullet_screen="求无删减版的"
        },
        {
            bullet_screen_group=2,
            seq=156,
            bullet_screen=66666
        },
        {
            bullet_screen_group=2,
            seq=157,
            bullet_screen="*****"
        },
        {
            bullet_screen_group=2,
            seq=158,
            bullet_screen="好莱坞大片"
        },
        {
            bullet_screen_group=2,
            seq=159,
            bullet_screen="净整花里胡哨的"
        },
        {
            bullet_screen_group=2,
            seq=160,
            bullet_screen="大会赞之后"
        },
        {
            bullet_screen_group=2,
            seq=161,
            bullet_screen="有好兄弟跟我说说，这游戏混服么?"
        },
        {
            bullet_screen_group=2,
            seq=162
        },
        {
            bullet_screen_group=2,
            seq=163
        },
        {
            bullet_screen_group=2,
            seq=164
        },
        {
            bullet_screen_group=2,
            seq=165,
            bullet_screen="有一起玩的吗"
        },
        {
            bullet_screen_group=2,
            seq=166
        },
        {
            bullet_screen_group=2,
            seq=167
        },
        {
            bullet_screen_group=2,
            seq=168
        },
        {
            bullet_screen_group=2,
            seq=169,
            bullet_screen="饿热特热微软"
        },
        {
            bullet_screen_group=2,
            seq=170,
            bullet_screen="的撒大大"
        },
        {
            bullet_screen_group=2,
            seq=171,
            bullet_screen="刑天无了？"
        },
        {
            bullet_screen_group=2,
            seq=172
        },
        {
            bullet_screen_group=2,
            seq=173,
            bullet_screen="有一起玩的吗"
        },
        {
            bullet_screen_group=2,
            seq=174,
            bullet_screen="刑天无了？"
        },
        {
            bullet_screen_group=2,
            seq=175
        },
        {
            bullet_screen_group=2,
            seq=176
        },
        {
            bullet_screen_group=2,
            seq=177
        },
        {
            bullet_screen_group=2,
            seq=178,
            bullet_screen="复仇者联盟"
        },
        {
            bullet_screen_group=2,
            seq=179
        },
        {
            bullet_screen_group=2,
            seq=180
        },
        {
            bullet_screen_group=2,
            seq=181
        },
        {
            bullet_screen_group=2,
            seq=182,
            bullet_screen="莫璃我老婆"
        },
        {
            bullet_screen_group=2,
            seq=183,
            bullet_screen="分为氛围"
        },
        {
            bullet_screen_group=2,
            seq=184,
            bullet_screen=66666
        },
        {
            bullet_screen_group=2,
            seq=185,
            bullet_screen="刑天为什么加入血盟？"
        },
        {
            bullet_screen_group=2,
            seq=186,
            bullet_screen="策划给老子滚出来"
        },
        {
            bullet_screen_group=2,
            seq=187,
            bullet_screen="时尚大方"
        },
        {
            bullet_screen_group=2,
            seq=188
        },
        {
            bullet_screen_group=2,
            seq=189
        },
        {
            bullet_screen_group=2,
            seq=190
        },
        {
            bullet_screen_group=2,
            seq=191
        },
        {
            bullet_screen_group=2,
            seq=192
        },
        {
            bullet_screen_group=2,
            seq=193
        },
        {
            bullet_screen_group=2,
            seq=194
        },
        {
            bullet_screen_group=2,
            seq=195,
            bullet_screen="我*"
        },
        {
            bullet_screen_group=2,
            seq=196,
            bullet_screen="怎么样怎么样怎么样怎么样怎么样"
        },
        {
            bullet_screen_group=2,
            seq=197,
            bullet_screen="刑天为什么加入血盟"
        },
        {
            bullet_screen_group=2,
            seq=198,
            bullet_screen="卧槽牛脾"
        },
        {
            bullet_screen_group=2,
            seq=199,
            bullet_screen="听君一席话胜似一席话"
        }
    }
}
SetConfigDefaultVal(Config.story_auto,_default_val,nil,nil,nil)