local _default_val={
    reward={
        level_min=1,
        level_max=9,
        min_rank=1,
        max_rank=3,
        exp=0,
        bind_coin=50000,
        title=-1
    },
    box_reward={
        type=0,
        min_level=1,
        max_level=34,
        exp=0,
        coin=25000,
        rate=10000,
        box_name="首胜宝箱"
    },
    participation_reward={
        exp=0,
        coin=0
    },
    reward_find={
        find_type=0,
        coin=0,
        family_gongxian=0,
        group_id=-1
    },
    reward_find_group={
        rate=10000
    }
}
local _itemlist={
    i_24518_2_1={
        item_id=24518,
        num=2,
        is_bind=1
    },
    i_24557_2_1={
        item_id=24557,
        num=2,
        is_bind=1
    },
    i_24557_1_1={
        item_id=24557,
        num=1,
        is_bind=1
    },
    i_28516_2_1={
        item_id=28516,
        num=2,
        is_bind=1
    },
    i_28516_1_1={
        item_id=28516,
        num=1,
        is_bind=1
    },
    i_24518_3_1={
        item_id=24518,
        num=3,
        is_bind=1
    },
    i_24518_1_1={
        item_id=24518,
        num=1,
        is_bind=1
    },
    i_28516_4_1={
        item_id=28516,
        num=4,
        is_bind=1
    },
    i_29033_1_1={
        item_id=29033,
        num=1,
        is_bind=1
    },
    i_29033_2_1={
        item_id=29033,
        num=2,
        is_bind=1
    },
    i_29033_3_1={
        item_id=29033,
        num=3,
        is_bind=1
    },
    i_29033_4_1={
        item_id=29033,
        num=4,
        is_bind=1
    },
    i_29033_5_1={
        item_id=29033,
        num=5,
        is_bind=1
    },
    i_28516_3_1={
        item_id=28516,
        num=3,
        is_bind=1
    },
    i_28516_5_1={
        item_id=28516,
        num=5,
        is_bind=1
    },
    i_26393_20_1={
        item_id=26393,
        num=20,
        is_bind=1
    },
    i_26393_35_1={
        item_id=26393,
        num=35,
        is_bind=1
    },
    i_26393_50_1={
        item_id=26393,
        num=50,
        is_bind=1
    },
    i_26394_30_1={
        item_id=26394,
        num=30,
        is_bind=1
    },
    i_26394_40_1={
        item_id=26394,
        num=40,
        is_bind=1
    },
    i_26394_50_1={
        item_id=26394,
        num=50,
        is_bind=1
    },
    i_26394_55_1={
        item_id=26394,
        num=55,
        is_bind=1
    },
    i_26394_60_1={
        item_id=26394,
        num=60,
        is_bind=1
    },
    i_26239_1_1={
        item_id=26239,
        num=1,
        is_bind=1
    }
}
Config.team_fight_cfg_auto={
    reward={
        {
            seq=0,
            reward={
                [0]=_itemlist.i_24518_2_1
            }
        },
        {
            seq=1,
            min_rank=4,
            max_rank=10,
            reward={
                [0]=_itemlist.i_24557_2_1
            },
            bind_coin=40000
        },
        {
            seq=2,
            min_rank=11,
            max_rank=20,
            reward={
                [0]=_itemlist.i_24557_1_1
            },
            bind_coin=30000
        },
        {
            seq=3,
            min_rank=21,
            max_rank=50,
            reward={
                [0]=_itemlist.i_28516_2_1
            },
            bind_coin=20000
        },
        {
            seq=4,
            min_rank=51,
            max_rank=100,
            reward={
                [0]=_itemlist.i_28516_1_1
            },
            bind_coin=10000
        },
        {
            seq=5,
            min_rank=101,
            max_rank=200,
            reward={
                [0]=_itemlist.i_28516_1_1
            },
            bind_coin=10000
        },
        {
            seq=6,
            level_min=10,
            level_max=19,
            reward={
                [0]=_itemlist.i_24518_2_1
            }
        },
        {
            seq=7,
            level_min=10,
            level_max=19,
            min_rank=4,
            max_rank=10,
            reward={
                [0]=_itemlist.i_24557_2_1
            },
            bind_coin=40000
        },
        {
            seq=8,
            level_min=10,
            level_max=19,
            min_rank=11,
            max_rank=20,
            reward={
                [0]=_itemlist.i_24557_1_1
            },
            bind_coin=30000
        },
        {
            seq=9,
            level_min=10,
            level_max=19,
            min_rank=21,
            max_rank=50,
            reward={
                [0]=_itemlist.i_28516_2_1
            },
            bind_coin=20000
        },
        {
            seq=10,
            level_min=10,
            level_max=19,
            min_rank=51,
            max_rank=100,
            reward={
                [0]=_itemlist.i_28516_1_1
            },
            bind_coin=10000
        },
        {
            seq=11,
            level_min=10,
            level_max=19,
            min_rank=101,
            max_rank=200,
            reward={
                [0]=_itemlist.i_28516_1_1
            },
            bind_coin=10000
        },
        {
            seq=12,
            level_min=20,
            level_max=29,
            reward={
                [0]=_itemlist.i_24518_2_1
            }
        },
        {
            seq=13,
            level_min=20,
            level_max=29,
            min_rank=4,
            max_rank=10,
            reward={
                [0]=_itemlist.i_24557_2_1
            },
            bind_coin=40000
        },
        {
            seq=14,
            level_min=20,
            level_max=29,
            min_rank=11,
            max_rank=20,
            reward={
                [0]=_itemlist.i_24557_1_1
            },
            bind_coin=30000
        },
        {
            seq=15,
            level_min=20,
            level_max=29,
            min_rank=21,
            max_rank=50,
            reward={
                [0]=_itemlist.i_28516_2_1
            },
            bind_coin=20000
        },
        {
            seq=16,
            level_min=20,
            level_max=29,
            min_rank=51,
            max_rank=100,
            reward={
                [0]=_itemlist.i_28516_1_1
            },
            bind_coin=10000
        },
        {
            seq=17,
            level_min=20,
            level_max=29,
            min_rank=101,
            max_rank=200,
            reward={
                [0]=_itemlist.i_28516_1_1
            },
            bind_coin=10000
        },
        {
            seq=18,
            level_min=30,
            level_max=39,
            reward={
                [0]=_itemlist.i_24518_2_1
            }
        },
        {
            seq=19,
            level_min=30,
            level_max=39,
            min_rank=4,
            max_rank=10,
            reward={
                [0]=_itemlist.i_24557_2_1
            },
            bind_coin=40000
        },
        {
            seq=20,
            level_min=30,
            level_max=39,
            min_rank=11,
            max_rank=20,
            reward={
                [0]=_itemlist.i_24557_1_1
            },
            bind_coin=30000
        },
        {
            seq=21,
            level_min=30,
            level_max=39,
            min_rank=21,
            max_rank=50,
            reward={
                [0]=_itemlist.i_28516_2_1
            },
            bind_coin=20000
        },
        {
            seq=22,
            level_min=30,
            level_max=39,
            min_rank=51,
            max_rank=100,
            reward={
                [0]=_itemlist.i_28516_1_1
            },
            bind_coin=10000
        },
        {
            seq=23,
            level_min=30,
            level_max=39,
            min_rank=101,
            max_rank=200,
            reward={
                [0]=_itemlist.i_28516_1_1
            },
            bind_coin=10000
        },
        {
            seq=24,
            level_min=40,
            level_max=49,
            reward={
                [0]=_itemlist.i_24518_2_1
            },
            bind_coin=60000
        },
        {
            seq=25,
            level_min=40,
            level_max=49,
            min_rank=4,
            max_rank=10,
            reward={
                [0]=_itemlist.i_24557_2_1
            }
        },
        {
            seq=26,
            level_min=40,
            level_max=49,
            min_rank=11,
            max_rank=20,
            reward={
                [0]=_itemlist.i_24557_1_1
            },
            bind_coin=40000
        },
        {
            seq=27,
            level_min=40,
            level_max=49,
            min_rank=21,
            max_rank=50,
            reward={
                [0]=_itemlist.i_28516_2_1
            },
            bind_coin=30000
        },
        {
            seq=28,
            level_min=40,
            level_max=49,
            min_rank=51,
            max_rank=100,
            reward={
                [0]=_itemlist.i_28516_1_1
            },
            bind_coin=20000
        },
        {
            seq=29,
            level_min=40,
            level_max=49,
            min_rank=101,
            max_rank=200,
            reward={
                [0]=_itemlist.i_28516_1_1
            },
            bind_coin=20000
        },
        {
            seq=30,
            level_min=50,
            level_max=59,
            reward={
                [0]=_itemlist.i_24518_2_1
            },
            bind_coin=60000
        },
        {
            seq=31,
            level_min=50,
            level_max=59,
            min_rank=4,
            max_rank=10,
            reward={
                [0]=_itemlist.i_24557_2_1
            }
        },
        {
            seq=32,
            level_min=50,
            level_max=59,
            min_rank=11,
            max_rank=20,
            reward={
                [0]=_itemlist.i_24557_1_1
            },
            bind_coin=40000
        },
        {
            seq=33,
            level_min=50,
            level_max=59,
            min_rank=21,
            max_rank=50,
            reward={
                [0]=_itemlist.i_28516_2_1
            },
            bind_coin=30000
        },
        {
            seq=34,
            level_min=50,
            level_max=59,
            min_rank=51,
            max_rank=100,
            reward={
                [0]=_itemlist.i_28516_1_1
            },
            bind_coin=20000
        },
        {
            seq=35,
            level_min=50,
            level_max=59,
            min_rank=101,
            max_rank=200,
            reward={
                [0]=_itemlist.i_28516_1_1
            },
            bind_coin=20000
        },
        {
            seq=36,
            level_min=60,
            level_max=69,
            reward={
                [0]=_itemlist.i_24518_3_1
            },
            bind_coin=70000
        },
        {
            seq=37,
            level_min=60,
            level_max=69,
            min_rank=4,
            max_rank=10,
            reward={
                [0]=_itemlist.i_24518_1_1
            },
            bind_coin=60000
        },
        {
            seq=38,
            level_min=60,
            level_max=69,
            min_rank=11,
            max_rank=20,
            reward={
                [0]=_itemlist.i_24557_2_1
            }
        },
        {
            seq=39,
            level_min=60,
            level_max=69,
            min_rank=21,
            max_rank=50,
            reward={
                [0]=_itemlist.i_28516_4_1
            },
            bind_coin=40000
        },
        {
            seq=40,
            level_min=60,
            level_max=69,
            min_rank=51,
            max_rank=100,
            reward={
                [0]=_itemlist.i_28516_2_1
            },
            bind_coin=30000
        },
        {
            seq=41,
            level_min=60,
            level_max=69,
            min_rank=101,
            max_rank=200,
            reward={
                [0]=_itemlist.i_28516_2_1
            },
            bind_coin=30000
        },
        {
            seq=42,
            level_min=70,
            level_max=79,
            reward={
                [0]=_itemlist.i_24518_3_1
            },
            bind_coin=70000
        },
        {
            seq=43,
            level_min=70,
            level_max=79,
            min_rank=4,
            max_rank=10,
            reward={
                [0]=_itemlist.i_24518_1_1
            },
            bind_coin=60000
        },
        {
            seq=44,
            level_min=70,
            level_max=79,
            min_rank=11,
            max_rank=20,
            reward={
                [0]=_itemlist.i_24557_2_1
            }
        },
        {
            seq=45,
            level_min=70,
            level_max=79,
            min_rank=21,
            max_rank=50,
            reward={
                [0]=_itemlist.i_28516_4_1
            },
            bind_coin=40000
        },
        {
            seq=46,
            level_min=70,
            level_max=79,
            min_rank=51,
            max_rank=100,
            reward={
                [0]=_itemlist.i_28516_2_1
            },
            bind_coin=30000
        },
        {
            seq=47,
            level_min=70,
            level_max=79,
            min_rank=101,
            max_rank=200,
            reward={
                [0]=_itemlist.i_28516_2_1
            },
            bind_coin=30000
        },
        {
            seq=48,
            level_min=80,
            level_max=89,
            reward={
                [0]=_itemlist.i_24518_3_1
            },
            bind_coin=80000
        },
        {
            seq=49,
            level_min=80,
            level_max=89,
            min_rank=4,
            max_rank=10,
            reward={
                [0]=_itemlist.i_24518_1_1
            },
            bind_coin=70000
        },
        {
            seq=50,
            level_min=80,
            level_max=89,
            min_rank=11,
            max_rank=20,
            reward={
                [0]=_itemlist.i_24557_2_1
            },
            bind_coin=60000
        },
        {
            seq=51,
            level_min=80,
            level_max=89,
            min_rank=21,
            max_rank=50,
            reward={
                [0]=_itemlist.i_28516_4_1
            }
        },
        {
            seq=52,
            level_min=80,
            level_max=89,
            min_rank=51,
            max_rank=100,
            reward={
                [0]=_itemlist.i_28516_2_1
            },
            bind_coin=40000
        },
        {
            seq=53,
            level_min=80,
            level_max=89,
            min_rank=101,
            max_rank=200,
            reward={
                [0]=_itemlist.i_28516_2_1
            },
            bind_coin=40000
        },
        {
            seq=54,
            level_min=90,
            level_max=99,
            reward={
                [0]=_itemlist.i_24518_3_1
            },
            bind_coin=80000
        },
        {
            seq=55,
            level_min=90,
            level_max=99,
            min_rank=4,
            max_rank=10,
            reward={
                [0]=_itemlist.i_24518_1_1
            },
            bind_coin=70000
        },
        {
            seq=56,
            level_min=90,
            level_max=99,
            min_rank=11,
            max_rank=20,
            reward={
                [0]=_itemlist.i_24557_2_1
            },
            bind_coin=60000
        },
        {
            seq=57,
            level_min=90,
            level_max=99,
            min_rank=21,
            max_rank=50,
            reward={
                [0]=_itemlist.i_28516_4_1
            }
        },
        {
            seq=58,
            level_min=90,
            level_max=99,
            min_rank=51,
            max_rank=100,
            reward={
                [0]=_itemlist.i_28516_2_1
            },
            bind_coin=40000
        },
        {
            seq=59,
            level_min=90,
            level_max=99,
            min_rank=101,
            max_rank=200,
            reward={
                [0]=_itemlist.i_28516_2_1
            },
            bind_coin=40000
        },
        {
            seq=60,
            level_min=100,
            level_max=109,
            reward={
                [0]=_itemlist.i_24518_3_1
            },
            bind_coin=90000
        },
        {
            seq=61,
            level_min=100,
            level_max=109,
            min_rank=4,
            max_rank=10,
            reward={
                [0]=_itemlist.i_24518_1_1
            },
            bind_coin=80000
        },
        {
            seq=62,
            level_min=100,
            level_max=109,
            min_rank=11,
            max_rank=20,
            reward={
                [0]=_itemlist.i_24557_2_1
            },
            bind_coin=70000
        },
        {
            seq=63,
            level_min=100,
            level_max=109,
            min_rank=21,
            max_rank=50,
            reward={
                [0]=_itemlist.i_28516_4_1
            },
            bind_coin=60000
        },
        {
            seq=64,
            level_min=100,
            level_max=109,
            min_rank=51,
            max_rank=100,
            reward={
                [0]=_itemlist.i_28516_2_1
            }
        },
        {
            seq=65,
            level_min=100,
            level_max=109,
            min_rank=101,
            max_rank=200,
            reward={
                [0]=_itemlist.i_28516_2_1
            }
        },
        {
            seq=66,
            level_min=110,
            level_max=120,
            reward={
                [0]=_itemlist.i_24518_3_1
            },
            bind_coin=90000
        },
        {
            seq=67,
            level_min=110,
            level_max=120,
            min_rank=4,
            max_rank=10,
            reward={
                [0]=_itemlist.i_24518_1_1
            },
            bind_coin=80000
        },
        {
            seq=68,
            level_min=110,
            level_max=120,
            min_rank=11,
            max_rank=20,
            reward={
                [0]=_itemlist.i_24557_2_1
            },
            bind_coin=70000
        },
        {
            seq=69,
            level_min=110,
            level_max=120,
            min_rank=21,
            max_rank=50,
            reward={
                [0]=_itemlist.i_28516_4_1
            },
            bind_coin=60000
        },
        {
            seq=70,
            level_min=110,
            level_max=120,
            min_rank=51,
            max_rank=100,
            reward={
                [0]=_itemlist.i_28516_2_1
            }
        },
        {
            seq=71,
            level_min=110,
            level_max=120,
            min_rank=101,
            max_rank=200,
            reward={
                [0]=_itemlist.i_28516_2_1
            }
        }
    },
    box_reward={
        {
            seq=0,
            reward=_itemlist.i_29033_1_1
        },
        {
            seq=1,
            min_level=35,
            max_level=39,
            reward=_itemlist.i_29033_1_1
        },
        {
            seq=2,
            min_level=40,
            max_level=44,
            reward=_itemlist.i_29033_1_1
        },
        {
            seq=3,
            min_level=45,
            max_level=49,
            reward=_itemlist.i_29033_1_1
        },
        {
            seq=4,
            min_level=50,
            max_level=54,
            reward=_itemlist.i_29033_2_1,
            coin=35000
        },
        {
            seq=5,
            min_level=55,
            max_level=59,
            reward=_itemlist.i_29033_2_1,
            coin=35000
        },
        {
            seq=6,
            min_level=60,
            max_level=64,
            reward=_itemlist.i_29033_2_1,
            coin=35000
        },
        {
            seq=7,
            min_level=65,
            max_level=69,
            reward=_itemlist.i_29033_2_1,
            coin=35000
        },
        {
            seq=8,
            min_level=70,
            max_level=74,
            reward=_itemlist.i_29033_3_1,
            coin=45000
        },
        {
            seq=9,
            min_level=75,
            max_level=79,
            reward=_itemlist.i_29033_3_1,
            coin=45000
        },
        {
            seq=10,
            min_level=80,
            max_level=84,
            reward=_itemlist.i_29033_3_1,
            coin=45000
        },
        {
            seq=11,
            min_level=85,
            max_level=89,
            reward=_itemlist.i_29033_3_1,
            coin=45000
        },
        {
            seq=12,
            min_level=90,
            max_level=94,
            reward=_itemlist.i_29033_4_1,
            coin=50000
        },
        {
            seq=13,
            min_level=95,
            max_level=99,
            reward=_itemlist.i_29033_4_1,
            coin=50000
        },
        {
            seq=14,
            min_level=100,
            max_level=104,
            reward=_itemlist.i_29033_4_1,
            coin=50000
        },
        {
            seq=15,
            min_level=105,
            max_level=109,
            reward=_itemlist.i_29033_4_1,
            coin=50000
        },
        {
            seq=16,
            min_level=110,
            max_level=114,
            reward=_itemlist.i_29033_5_1,
            coin=60000
        },
        {
            seq=17,
            min_level=115,
            max_level=119,
            reward=_itemlist.i_29033_5_1,
            coin=60000
        },
        {
            seq=18,
            min_level=120,
            max_level=120,
            reward=_itemlist.i_29033_5_1,
            coin=60000
        },
        {
            seq=19,
            type=1,
            reward=_itemlist.i_28516_1_1,
            box_name="三战宝箱"
        },
        {
            seq=20,
            type=1,
            min_level=35,
            max_level=39,
            reward=_itemlist.i_28516_1_1,
            box_name="三战宝箱"
        },
        {
            seq=21,
            type=1,
            min_level=40,
            max_level=44,
            reward=_itemlist.i_28516_1_1,
            box_name="三战宝箱"
        },
        {
            seq=22,
            type=1,
            min_level=45,
            max_level=49,
            reward=_itemlist.i_28516_1_1,
            box_name="三战宝箱"
        },
        {
            seq=23,
            type=1,
            min_level=50,
            max_level=54,
            reward=_itemlist.i_28516_2_1,
            coin=35000,
            box_name="三战宝箱"
        },
        {
            seq=24,
            type=1,
            min_level=55,
            max_level=59,
            reward=_itemlist.i_28516_2_1,
            coin=35000,
            box_name="三战宝箱"
        },
        {
            seq=25,
            type=1,
            min_level=60,
            max_level=64,
            reward=_itemlist.i_28516_2_1,
            coin=35000,
            box_name="三战宝箱"
        },
        {
            seq=26,
            type=1,
            min_level=65,
            max_level=69,
            reward=_itemlist.i_28516_2_1,
            coin=35000,
            box_name="三战宝箱"
        },
        {
            seq=27,
            type=1,
            min_level=70,
            max_level=74,
            reward=_itemlist.i_28516_3_1,
            coin=45000,
            box_name="三战宝箱"
        },
        {
            seq=28,
            type=1,
            min_level=75,
            max_level=79,
            reward=_itemlist.i_28516_3_1,
            coin=45000,
            box_name="三战宝箱"
        },
        {
            seq=29,
            type=1,
            min_level=80,
            max_level=84,
            reward=_itemlist.i_28516_3_1,
            coin=45000,
            box_name="三战宝箱"
        },
        {
            seq=30,
            type=1,
            min_level=85,
            max_level=89,
            reward=_itemlist.i_28516_3_1,
            coin=45000,
            box_name="三战宝箱"
        },
        {
            seq=31,
            type=1,
            min_level=90,
            max_level=94,
            reward=_itemlist.i_28516_4_1,
            coin=50000,
            box_name="三战宝箱"
        },
        {
            seq=32,
            type=1,
            min_level=95,
            max_level=99,
            reward=_itemlist.i_28516_4_1,
            coin=50000,
            box_name="三战宝箱"
        },
        {
            seq=33,
            type=1,
            min_level=100,
            max_level=104,
            reward=_itemlist.i_28516_4_1,
            coin=50000,
            box_name="三战宝箱"
        },
        {
            seq=34,
            type=1,
            min_level=105,
            max_level=109,
            reward=_itemlist.i_28516_4_1,
            coin=50000,
            box_name="三战宝箱"
        },
        {
            seq=35,
            type=1,
            min_level=110,
            max_level=114,
            reward=_itemlist.i_28516_5_1,
            coin=60000,
            box_name="三战宝箱"
        },
        {
            seq=36,
            type=1,
            min_level=115,
            max_level=119,
            reward=_itemlist.i_28516_5_1,
            coin=60000,
            box_name="三战宝箱"
        },
        {
            seq=37,
            type=1,
            min_level=120,
            max_level=120,
            reward=_itemlist.i_28516_5_1,
            coin=60000,
            box_name="三战宝箱"
        }
    },
    participation_reward={
        {
            level_min=1,
            level_max=34,
            reward={
                [0]=_itemlist.i_26393_20_1
            }
        },
        {
            level_min=35,
            level_max=39,
            reward={
                [0]=_itemlist.i_26393_20_1
            }
        },
        {
            level_min=40,
            level_max=44,
            reward={
                [0]=_itemlist.i_26393_35_1
            }
        },
        {
            level_min=45,
            level_max=49,
            reward={
                [0]=_itemlist.i_26393_35_1
            }
        },
        {
            level_min=50,
            level_max=54,
            reward={
                [0]=_itemlist.i_26393_50_1
            }
        },
        {
            level_min=55,
            level_max=59,
            reward={
                [0]=_itemlist.i_26393_50_1
            }
        },
        {
            level_min=60,
            level_max=64,
            reward={
                [0]=_itemlist.i_26394_30_1
            }
        },
        {
            level_min=65,
            level_max=69,
            reward={
                [0]=_itemlist.i_26394_30_1
            }
        },
        {
            level_min=70,
            level_max=74,
            reward={
                [0]=_itemlist.i_26394_40_1
            }
        },
        {
            level_min=75,
            level_max=79,
            reward={
                [0]=_itemlist.i_26394_40_1
            }
        },
        {
            level_min=80,
            level_max=84,
            reward={
                [0]=_itemlist.i_26394_50_1
            }
        },
        {
            level_min=85,
            level_max=89,
            reward={
                [0]=_itemlist.i_26394_50_1
            }
        },
        {
            level_min=90,
            level_max=94,
            reward={
                [0]=_itemlist.i_26394_55_1
            }
        },
        {
            level_min=95,
            level_max=99,
            reward={
                [0]=_itemlist.i_26394_55_1
            }
        },
        {
            level_min=100,
            level_max=104,
            reward={
                [0]=_itemlist.i_26394_60_1
            }
        },
        {
            level_min=105,
            level_max=109,
            reward={
                [0]=_itemlist.i_26394_60_1
            }
        },
        {
            level_min=110,
            level_max=114,
            reward={
                [0]=_itemlist.i_26394_60_1
            }
        },
        {
            level_min=115,
            level_max=119,
            reward={
                [0]=_itemlist.i_26394_60_1
            }
        },
        {
            level_min=120,
            level_max=120,
            reward={
                [0]=_itemlist.i_26394_60_1
            }
        }
    },
    other={
        {
            scene_id=119,
            open_level=30,
            x=301,
            y=152,
            battle_countdown=5,
            max_round=20,
            buff_round=8,
            battle_multiple=2
        }
    },
    teammate_match={},
    opponent_match={},
    reward_find={
        {
            seq=1,
            min_level=1,
            max_level=34,
            exp=175000
        },
        {
            seq=2,
            min_level=35,
            max_level=39,
            exp=196000
        },
        {
            seq=3,
            min_level=40,
            max_level=44,
            exp=217000
        },
        {
            seq=4,
            min_level=45,
            max_level=49,
            exp=238000
        },
        {
            seq=5,
            min_level=50,
            max_level=54,
            exp=266000
        },
        {
            seq=6,
            min_level=55,
            max_level=59,
            exp=294000
        },
        {
            seq=7,
            min_level=60,
            max_level=64,
            exp=315000
        },
        {
            seq=8,
            min_level=65,
            max_level=69,
            exp=343000
        },
        {
            seq=9,
            min_level=70,
            max_level=74,
            exp=364000
        },
        {
            seq=10,
            min_level=75,
            max_level=79,
            exp=385000
        },
        {
            seq=11,
            min_level=80,
            max_level=84,
            exp=413000
        },
        {
            seq=12,
            min_level=85,
            max_level=89,
            exp=434000
        },
        {
            seq=13,
            min_level=90,
            max_level=94,
            exp=462000
        },
        {
            seq=14,
            min_level=95,
            max_level=99,
            exp=483000
        },
        {
            seq=15,
            min_level=100,
            max_level=104,
            exp=504000
        },
        {
            seq=16,
            min_level=105,
            max_level=109,
            exp=532000
        },
        {
            seq=17,
            min_level=110,
            max_level=114,
            exp=553000
        },
        {
            seq=18,
            min_level=115,
            max_level=119,
            exp=581000
        },
        {
            seq=19,
            min_level=120,
            max_level=120,
            exp=602000
        }
    },
    reward_find_group={
        {
            group_id=1,
            reward=_itemlist.i_26239_1_1
        },
        {
            group_id=2,
            reward=_itemlist.i_26239_1_1
        },
        {
            group_id=3,
            reward=_itemlist.i_26239_1_1
        },
        {
            group_id=4,
            reward=_itemlist.i_26239_1_1
        }
    }
}
SetConfigDefaultVal(Config.team_fight_cfg_auto,_default_val,nil,nil,nil)