local _default_val={
    basis_configuration={
        section_start=1,
        section_end=21,
        question_id=1,
        suc_reward_group=1,
        fault_reward_group=3
    },
    reward_group={
        reward_group=1,
        exp=100,
        coin=0
    },
    question_bank={
        answer_id=3,
        anwser_1="孙思邈",
        anwser_3="李时珍"
    }
}
local _itemlist={
    i_29060_1_1={
        item_id=29060,
        num=1,
        is_bind=1
    },
    i_28555_1_1={
        item_id=28555,
        num=1,
        is_bind=1
    },
    i_27654_1_1={
        item_id=27654,
        num=1,
        is_bind=1
    },
    i_29077_1_1={
        item_id=29077,
        num=1,
        is_bind=1
    },
    i_28611_1_1={
        item_id=28611,
        num=1,
        is_bind=1
    },
    i_65535_1_1={
        item_id=65535,
        num=1,
        is_bind=1
    }
}
Config.time_limit_answer_auto={
    basis_configuration={
        {
            type=0
        },
        {
            type=1,
            question_id=2
        },
        {
            type=2,
            question_id=3
        },
        {
            type=3,
            question_id=4
        },
        {
            type=4,
            question_id=5
        },
        {
            type=5,
            question_id=6
        },
        {
            type=6,
            question_id=7
        },
        {
            type=7,
            question_id=8
        },
        {
            type=8,
            question_id=9
        },
        {
            type=9,
            question_id=10
        },
        {
            type=10,
            question_id=11
        },
        {
            type=11,
            question_id=12
        },
        {
            type=12,
            question_id=13
        },
        {
            type=13,
            question_id=14
        },
        {
            type=14,
            question_id=15
        },
        {
            type=15,
            question_id=16
        },
        {
            type=16,
            question_id=17
        },
        {
            type=17,
            question_id=18
        },
        {
            type=18,
            question_id=19
        },
        {
            type=19,
            question_id=20
        },
        {
            type=20,
            section_start=22,
            section_end=0,
            suc_reward_group=2
        },
        {
            type=21,
            section_start=22,
            section_end=0,
            question_id=2,
            suc_reward_group=2
        },
        {
            type=22,
            section_start=22,
            section_end=0,
            question_id=3,
            suc_reward_group=2
        },
        {
            type=23,
            section_start=22,
            section_end=0,
            question_id=4,
            suc_reward_group=2
        },
        {
            type=24,
            section_start=22,
            section_end=0,
            question_id=5,
            suc_reward_group=2
        },
        {
            type=25,
            section_start=22,
            section_end=0,
            question_id=6,
            suc_reward_group=2
        },
        {
            type=26,
            section_start=22,
            section_end=0,
            question_id=7,
            suc_reward_group=2
        },
        {
            type=27,
            section_start=22,
            section_end=0,
            question_id=8,
            suc_reward_group=2
        },
        {
            type=28,
            section_start=22,
            section_end=0,
            question_id=9,
            suc_reward_group=2
        },
        {
            type=29,
            section_start=22,
            section_end=0,
            question_id=10,
            suc_reward_group=2
        },
        {
            type=30,
            section_start=22,
            section_end=0,
            question_id=11,
            suc_reward_group=2
        },
        {
            type=31,
            section_start=22,
            section_end=0,
            question_id=12,
            suc_reward_group=2
        },
        {
            type=32,
            section_start=22,
            section_end=0,
            question_id=13,
            suc_reward_group=2
        },
        {
            type=33,
            section_start=22,
            section_end=0,
            question_id=14,
            suc_reward_group=2
        },
        {
            type=34,
            section_start=22,
            section_end=0,
            question_id=15,
            suc_reward_group=2
        },
        {
            type=35,
            section_start=22,
            section_end=0,
            question_id=16,
            suc_reward_group=2
        },
        {
            type=36,
            section_start=22,
            section_end=0,
            question_id=17,
            suc_reward_group=2
        },
        {
            type=37,
            section_start=22,
            section_end=0,
            question_id=18,
            suc_reward_group=2
        },
        {
            type=38,
            section_start=22,
            section_end=0,
            question_id=19,
            suc_reward_group=2
        },
        {
            type=39,
            section_start=22,
            section_end=0,
            question_id=20,
            suc_reward_group=2
        }
    },
    reward_group={
        {
            type=1,
            reward_item={
                [0]=_itemlist.i_29060_1_1,
                [1]=_itemlist.i_28555_1_1
            }
        },
        {
            type=2,
            reward_item={
                [0]=_itemlist.i_29060_1_1,
                [1]=_itemlist.i_27654_1_1
            }
        },
        {
            type=3,
            reward_group=2,
            reward_item={
                [0]=_itemlist.i_29060_1_1,
                [1]=_itemlist.i_29077_1_1
            }
        },
        {
            type=4,
            reward_group=2,
            reward_item={
                [0]=_itemlist.i_29060_1_1,
                [1]=_itemlist.i_28611_1_1
            }
        },
        {
            type=5,
            reward_group=3
        }
    },
    question_bank={
        {
            question_id=1,
            question="古代女子成年行什么礼？",
            answer_id=2,
            anwser_1="冠礼",
            anwser_2="笄礼",
            anwser_3="不行礼"
        },
        {
            question_id=2,
            question="声音在哪里传播更快？",
            anwser_1="空气中",
            anwser_2="一样快",
            anwser_3="水中"
        },
        {
            question_id=3,
            question="农历把每月初一叫做什么日？",
            anwser_1="望日",
            anwser_2="满日",
            anwser_3="朔日"
        },
        {
            question_id=4,
            question="以下哪些果实是核果？",
            answer_id=1,
            anwser_1="樱桃",
            anwser_2="银杏",
            anwser_3="石榴"
        },
        {
            question_id=5,
            question="热带鱼一般生活在哪里？",
            anwser_1="咸水中",
            anwser_2="甜水中",
            anwser_3="淡水中"
        },
        {
            question_id=6,
            question="《本草纲目》的作者是？",
            anwser_2="孙仲景"
        },
        {
            question_id=7,
            question="“山外青山楼外楼”在原诗《题临安邸》中的下句是？",
            anwser_1="强中自有强中手",
            anwser_2="平明送客楚山孤",
            anwser_3="西湖歌舞几时休"
        },
        {
            question_id=8,
            question="中国最热的地方在哪里？",
            answer_id=1,
            anwser_1="吐鲁番盆地",
            anwser_2="南沙群岛",
            anwser_3="海南"
        },
        {
            question_id=9,
            question="太阳系中最大的行星是？",
            answer_id=1,
            anwser_1="木星",
            anwser_2="土星",
            anwser_3="火星"
        },
        {
            question_id=10,
            question="“腊八粥”最早起源于?",
            answer_id=2,
            anwser_1="祭祀",
            anwser_2="佛教",
            anwser_3="民间庆祝丰收的风俗"
        },
        {
            question_id=11,
            question="中国古建筑学科的开拓者是?",
            answer_id=1,
            anwser_1="梁思成",
            anwser_2="杨廷玉",
            anwser_3="吴良镛"
        },
        {
            question_id=12,
            question="《春秋》是按什么记事的？",
            anwser_1="国",
            anwser_2="事件",
            anwser_3="年"
        },
        {
            question_id=13,
            question="奥运五环旗中的绿色环代表?",
            answer_id=1,
            anwser_1="澳洲",
            anwser_2="美洲",
            anwser_3="欧洲"
        },
        {
            question_id=14,
            question="“总角之交”是指?",
            answer_id=2,
            anwser_1="顽童之交",
            anwser_2="少年之交",
            anwser_3="中年之交"
        },
        {
            question_id=15,
            question="我国古代称生什么为“弄瓦”？",
            answer_id=2,
            anwser_1="男孩",
            anwser_2="女孩",
            anwser_3="第二个孩子"
        },
        {
            question_id=16,
            question="南岳衡山的最高峰是?",
            answer_id=2,
            anwser_1="天都峰",
            anwser_2="祝融峰",
            anwser_3="莲花峰"
        },
        {
            question_id=17,
            question="以下哪一位曾被称为“药王”？",
            answer_id=1,
            anwser_2="张仲景"
        },
        {
            question_id=18,
            question="我国的“诗圣”指的是?",
            answer_id=1,
            anwser_1="杜甫",
            anwser_2="李白",
            anwser_3="李贺"
        },
        {
            question_id=19,
            question="第一次鸦片战争发生的时间是?",
            anwser_1="1841年1月",
            anwser_2="1839年3月",
            anwser_3="1840年6月"
        },
        {
            question_id=20,
            question="歌剧《茶花女》谁的作品？",
            anwser_1="普契尼",
            anwser_2="瓦格纳",
            anwser_3="威尔第"
        }
    },
    reward_show={
        {
            section_start=1,
            section_end=21,
            show_item={
                [0]=_itemlist.i_29060_1_1,
                [1]=_itemlist.i_28555_1_1,
                [2]=_itemlist.i_27654_1_1,
                [3]=_itemlist.i_65535_1_1
            }
        },
        {
            section_start=22,
            section_end=0,
            show_item={
                [0]=_itemlist.i_29060_1_1,
                [1]=_itemlist.i_29077_1_1,
                [2]=_itemlist.i_28611_1_1,
                [3]=_itemlist.i_65535_1_1
            }
        }
    },
    other={
        {
            start_times=2000,
            end_times=2200,
            ans_times=5
        }
    }
}
SetConfigDefaultVal(Config.time_limit_answer_auto,_default_val,nil,nil,nil)