Config.trade_line_auto={
    trade_line_item_type={
        {
            seq=0,
            type="任务道具",
            is_show=0
        },
        {
            seq=1,
            type="装  备",
            is_show=1
        },
        {
            seq=2,
            type="防  具",
            is_show=1
        },
        {
            seq=3,
            type="普通物品",
            is_show=1
        },
        {
            seq=4,
            type="矿  石",
            is_show=1
        },
        {
            seq=5,
            type="木  材",
            is_show=1
        },
        {
            seq=6,
            type="花  草",
            is_show=1
        },
        {
            seq=7,
            type="布  料",
            is_show=1
        },
        {
            seq=8,
            type="药  品",
            is_show=1
        },
        {
            seq=9,
            type="宝石",
            is_show=0
        },
        {
            seq=10,
            type="钥匙",
            is_show=0
        },
        {
            seq=11,
            type="魔  石",
            is_show=1
        },
        {
            seq=12,
            type="元素水晶",
            is_show=1
        },
        {
            seq=13,
            type="技能草",
            is_show=0
        },
        {
            seq=14,
            type="副本水晶",
            is_show=0
        },
        {
            seq=15,
            type="元素水晶碎片",
            is_show=1
        },
        {
            seq=16,
            type="礼包",
            is_show=0
        },
        {
            seq=17,
            type="属性药",
            is_show=0
        },
        {
            seq=18,
            type="图鉴卡",
            is_show=1
        },
        {
            seq=19,
            type="宠物技能书",
            is_show=1
        },
        {
            seq=20,
            type="灵饰",
            is_show=0
        },
        {
            seq=21,
            type="幻化时装",
            is_show=0
        },
        {
            seq=22,
            type="打卡水晶",
            is_show=0
        }
    },
    exchange_constant={
        {
            tax_rate=200,
            upper_shelf_price_min=200,
            upper_shelf_price_max=100000,
            advert_price_rate=2,
            immortal_coin_advert_min=20000,
            gold_advert_min=2,
            gold_advert_max=2000
        }
    }
}