local _default_val={
    skill={
        skill_type=2,
        param1=2,
        param2="",
        param3="",
        param4="",
        param5="",
        is_item=0,
        res_id=0,
        res_dir="",
        res_range="",
        is_dec=0
    },
    res_release={
        res_chance=200
    },
    box_position={
        boss_dir=0,
        npc_id=40605
    },
    box_reward={
        param_type=0
    },
    guide={
        index=1,
        last_time=6,
        end_delay_time=1,
        is_special=0,
        pos_y=182,
        bottom_long=300,
        bottom_wide=120,
        arrow_direction=2,
        is_mirror=1,
        arrow_x=-5,
        arrow_y=-93,
        guide_x=0,
        guide_y=0,
        advance=1,
        pos_y2=-183
    }
}
local _itemlist={
    i_29033_5_1={
        item_id=29033,
        num=5,
        is_bind=1
    },
    i_24326_6_1={
        item_id=24326,
        num=6,
        is_bind=1
    },
    i_28516_3_1={
        item_id=28516,
        num=3,
        is_bind=1
    },
    i_28516_5_1={
        item_id=28516,
        num=5,
        is_bind=1
    },
    i_24326_8_1={
        item_id=24326,
        num=8,
        is_bind=1
    },
    i_24518_3_1={
        item_id=24518,
        num=3,
        is_bind=1
    },
    i_24326_10_1={
        item_id=24326,
        num=10,
        is_bind=1
    },
    i_24326_9_1={
        item_id=24326,
        num=9,
        is_bind=1
    },
    i_24518_2_1={
        item_id=24518,
        num=2,
        is_bind=1
    },
    i_24518_1_1={
        item_id=24518,
        num=1,
        is_bind=1
    },
    i_24326_7_1={
        item_id=24326,
        num=7,
        is_bind=1
    },
    i_24557_2_1={
        item_id=24557,
        num=2,
        is_bind=1
    },
    i_28516_4_1={
        item_id=28516,
        num=4,
        is_bind=1
    },
    i_24326_5_1={
        item_id=24326,
        num=5,
        is_bind=1
    },
    i_28516_2_1={
        item_id=28516,
        num=2,
        is_bind=1
    },
    i_28516_1_1={
        item_id=28516,
        num=1,
        is_bind=1
    }
}
Config.treasure_contend_auto={
    skill={
        {
            sn=1,
            param2=28,
            param3=3,
            is_item=1,
            skill_name="抓捕",
            skill_dsc="param1秒钟的技能引导时间后，对方未离开施法范围param2则成功抓捕，对方将进入禁锢状态无法移动，冷却时间param3秒。Param4抓捕范围",
            skill_dsc_show="引导2秒，若引导结束盗宝者未离开施法范围，则盗宝者将进入禁锢状态无法移动，冷却时间3秒。",
            is_dec=2
        },
        {
            sn=2,
            param2=40,
            param3=5,
            param4=30,
            is_item=1,
            skill_name="疾走",
            skill_dsc="技能引导param1秒后，移动速度增加param2%，持续param3秒，冷却时间param4秒",
            skill_dsc_show="技能引导2秒后，移动速度增加40%，持续5秒，冷却时间30秒。",
            is_dec=2
        },
        {
            sn=3,
            skill_type=1,
            param2=30,
            is_item=1,
            skill_name="传送",
            skill_dsc="施法时间param1秒，传送到场景中的一个随机位置，冷却时间param2秒",
            skill_dsc_show="施法时间2秒，传送到场景中的一个随机位置，冷却时间30秒，打断技能会进入冷却。",
            is_dec=2
        },
        {
            sn=4,
            skill_type=1,
            param1=3,
            param2=3,
            param3=15,
            is_item=2,
            skill_name="开锁",
            skill_dsc="施法时间param1秒，打开一个宝箱的封印法阵。冷却时间param2秒，当范围内无宝箱时，无法释放，施法过程中移动将打断开锁技能。Param3开宝箱范围",
            skill_dsc_show="靠近宝箱时施法3秒可打开一个宝箱的封印。冷却时间3秒，施法过程中移动将打断开锁技能。",
            is_dec=3
        },
        {
            sn=5,
            skill_type=1,
            param1=5,
            param2=3,
            param3=15,
            is_item=2,
            skill_name="救援",
            skill_dsc="施法时间param1秒，解除范围内一名友方角色的禁锢状态，冷却时间param2秒，当范围内无被禁锢队友时，无法释放，施法过程中移动将打断救援技能，技能进入冷却。Param3救援范围",
            skill_dsc_show="靠近一名被禁锢队友时施法五秒可解除禁锢状态，冷却时间3秒，施法过程中移动将打断救援技能。",
            is_dec=3
        },
        {
            sn=6,
            param2=10,
            param3=25,
            is_item=2,
            skill_name="神隐",
            skill_dsc="技能引导param1秒后，param2秒钟内为不可见状态，隐身状态释放技能将会现行，无法被抓捕。抓捕引导时间未离开抓捕范围，仍会被抓捕。冷却时间param3秒",
            skill_dsc_show="技能引导2秒后进入10秒的隐身状态。冷却时间25秒",
            is_dec=3
        },
        {
            sn=7,
            param2=80,
            param3=6,
            param4=50,
            param5=3,
            res_id=1005,
            skill_name="轻身符",
            skill_dsc="技能引导param1秒，增加自身param2%移动速度，持续param3秒，效果结束后陷入虚弱状态，移动速度降低param4%，持续param5秒",
            skill_dsc_show="引导2秒后增加80%速度，持续6秒，结束后降低50%，持续3秒",
            is_dec=1
        },
        {
            sn=8,
            skill_type=1,
            param2=30,
            param3=40614,
            res_id=1004,
            skill_name="稻草人",
            skill_dsc="施法时间param1秒，释放技能将在身前放置一个稻草人，param2秒后或再次释放技能则传送到稻草人的位置，param3稻草人NPCid",
            skill_dsc_show="施法时间2秒，释放技能将在身前放置一个稻草人，30秒后或再次释放技能则传送到稻草人的位置。"
        },
        {
            sn=9,
            skill_type=1,
            res_id=1007,
            skill_name="天行梭",
            skill_dsc="施法时间param1秒，随机传送到场上任一位置",
            skill_dsc_show="施法时间2秒，随机传送到场上任一位置，打断后道具将消失。",
            is_dec=1
        },
        {
            sn=10,
            res_id=1001,
            skill_name="传送法阵",
            skill_dsc="引导param1时间，询问队友是否立即传送到自身当前位置,引导时间内队友同意将传送到当前位置。",
            skill_dsc_show="引导时间2秒，询问队友是否立即传送到自身当前位置,引导时间内队友同意将传送到当前位置。"
        },
        {
            sn=11,
            skill_type=1,
            param1=120,
            param2=5,
            param3=10,
            param4=40615,
            res_id=1003,
            skill_name="陷阱",
            skill_dsc="在当前位置放置一个隐形陷阱，陷阱存在param1秒，从陷阱上路过将会禁锢param2秒钟，无法移动。Param3触发范围，param4陷阱NPCid",
            skill_dsc_show="在当前位置放置一个隐形陷阱，陷阱存在120秒，从陷阱上路过将会禁锢10秒钟，无法移动。"
        },
        {
            sn=12,
            param1=60,
            res_id=1008,
            skill_name="傀儡娃娃",
            skill_dsc="在原地释放一个分身巡逻迷惑敌人，巡逻方向为释放时玩家方向。分身存在param1秒后消失",
            skill_dsc_show="在原地释放一个分身巡逻迷惑敌人，巡逻方向为释放时玩家方向。分身"
        },
        {
            sn=13,
            param2=5,
            res_id=1009,
            skill_name=" 隐身衣",
            skill_dsc="技能引导param1秒后，param2秒钟内为不可见状态，隐身状态释放技能将会现行，无法被抓捕。抓捕引导时间未离开抓捕范围，仍会被抓捕",
            skill_dsc_show="引导2秒后进入隐身状态，持续5秒。",
            is_dec=1
        },
        {
            sn=14,
            param1=30,
            res_id=1006,
            skill_name="挪移尺",
            skill_dsc="释放后立即向前进方向挪移一段距离",
            skill_dsc_show="释放后立即向前进方向挪移一段距离",
            is_dec=1
        }
    },
    res_release={
        {
            sn=7,
            npc_id=40606
        },
        {
            sn=9,
            npc_id=40608
        },
        {
            sn=13,
            npc_id=40612
        },
        {
            sn=14,
            res_chance=100,
            npc_id=40613
        }
    },
    box_position={
        {
            box_sn=1,
            box_x=562,
            box_y=119,
            boss_dir=183
        },
        {
            box_sn=2,
            box_x=868,
            box_y=958,
            boss_dir=221
        },
        {
            box_sn=3,
            box_x=671,
            box_y=772,
            boss_dir=221
        },
        {
            box_sn=4,
            box_x=241,
            box_y=750,
            boss_dir=92
        },
        {
            box_sn=5,
            box_x=78,
            box_y=664,
            boss_dir=121
        },
        {
            box_sn=6,
            box_x=259,
            box_y=495
        },
        {
            box_sn=7,
            box_x=395,
            box_y=575,
            boss_dir=129
        },
        {
            box_sn=8,
            box_x=381,
            box_y=440
        },
        {
            box_sn=9,
            box_x=511,
            box_y=584
        },
        {
            box_sn=10,
            box_x=660,
            box_y=638,
            boss_dir=98
        },
        {
            box_sn=11,
            box_x=821,
            box_y=518,
            boss_dir=43
        },
        {
            box_sn=12,
            box_x=866,
            box_y=215
        },
        {
            box_sn=13,
            box_x=570,
            box_y=266,
            boss_dir=135
        },
        {
            box_sn=14,
            box_x=452,
            box_y=10,
            boss_dir=2
        },
        {
            box_sn=15,
            box_x=432,
            box_y=297,
            boss_dir=272
        },
        {
            box_sn=16,
            box_x=287,
            box_y=107,
            boss_dir=193
        },
        {
            box_sn=17,
            box_x=86,
            box_y=17,
            boss_dir=14
        },
        {
            box_sn=18,
            box_x=271,
            box_y=295,
            boss_dir=110
        }
    },
    box_reward={
        {
            sn=1,
            item_list={
                [0]=_itemlist.i_29033_5_1,
                [1]=_itemlist.i_24326_6_1
            },
            param=1,
            times=1
        },
        {
            sn=2,
            item_list={
                [0]=_itemlist.i_28516_3_1,
                [1]=_itemlist.i_24326_6_1
            },
            param=2,
            times=2
        },
        {
            sn=3,
            item_list={
                [0]=_itemlist.i_28516_5_1,
                [1]=_itemlist.i_24326_8_1
            },
            param=3,
            times=3
        }
    },
    rank_reward={
        {
            sn=1,
            rank_range_min=1,
            rank_range_max=1,
            item_list={
                [0]=_itemlist.i_24518_3_1,
                [1]=_itemlist.i_24326_10_1
            }
        },
        {
            sn=2,
            rank_range_min=2,
            rank_range_max=2,
            item_list={
                [0]=_itemlist.i_24518_3_1,
                [1]=_itemlist.i_24326_9_1
            }
        },
        {
            sn=3,
            rank_range_min=3,
            rank_range_max=3,
            item_list={
                [0]=_itemlist.i_24518_2_1,
                [1]=_itemlist.i_24326_8_1
            }
        },
        {
            sn=4,
            rank_range_min=4,
            rank_range_max=10,
            item_list={
                [0]=_itemlist.i_24518_1_1,
                [1]=_itemlist.i_24326_7_1
            }
        },
        {
            sn=5,
            rank_range_min=11,
            rank_range_max=20,
            item_list={
                [0]=_itemlist.i_24557_2_1,
                [1]=_itemlist.i_24326_6_1
            }
        },
        {
            sn=6,
            rank_range_min=21,
            rank_range_max=50,
            item_list={
                [0]=_itemlist.i_28516_4_1,
                [1]=_itemlist.i_24326_5_1
            }
        },
        {
            sn=7,
            rank_range_min=51,
            rank_range_max=100,
            item_list={
                [0]=_itemlist.i_28516_2_1,
                [1]=_itemlist.i_24326_5_1
            }
        },
        {
            sn=8,
            rank_range_min=101,
            rank_range_max=999999,
            item_list={
                [0]=_itemlist.i_28516_1_1,
                [1]=_itemlist.i_24326_5_1
            }
        }
    },
    other={
        {
            scene_id=313,
            duration=480,
            win_box_num=15,
            pick_distance=15,
            first_props=27,
            props_time=120,
            props_num=10,
            box_score=2,
            capture_score=8,
            first_score=15,
            second_score=10,
            third_score=5,
            continu_score=3,
            time_score_3=15,
            time_score_5=10,
            time_score_8=5,
            winner_score=50,
            loser_score=20,
            defender_pos_x_1=506,
            defender_pos_y_1=524,
            defender_pos_x_2=438,
            defender_pos_y_2=571,
            defender_pos_x_3=376,
            defender_pos_y_3=499,
            attacker_pos_x_1=492,
            attacker_pos_y_1=980,
            attacker_pos_x_2=435,
            attacker_pos_y_2=943,
            attacker_pos_x_3=471,
            attacker_pos_y_3=954,
            once_team_players=3,
            guidelines_time=5,
            npc_seq=242,
            behavior_id=31007,
            team_target=240
        }
    },
    guide={
        {
            step=1,
            guide_dec_shouwei="通过移动摇杆，可控制角色移动。",
            guide_dec_daobao="通过移动摇杆，可控制角色移动。",
            guide_param="JoyGuide",
            pos_x=-531,
            pos_y=0,
            bottom_wide=100,
            is_mirror=0,
            arrow_x=21,
            arrow_y=-78,
            pos_x2=-5,
            pos_y2=211
        },
        {
            step=2,
            guide_dec_shouwei="遗迹中共存在18个宝箱，盗宝者只需盗走其中15个宝箱，即可获得胜利。此处为盗宝者距离获得剩余宝箱.",
            guide_dec_daobao="遗迹中共存在18个宝箱，盗宝者只需盗走其中15个宝箱，即可获得胜利。此处为盗宝者距离获得剩余宝箱.",
            guide_param="BoxGuide",
            pos_x=-15,
            bottom_wide=170,
            arrow_direction=4,
            is_mirror=0,
            arrow_y=117,
            pos_x2=-13
        },
        {
            step=3,
            index=2,
            guide_dec_shouwei="此处是盗宝者剩余未被捕数量，当盗宝者全部被捕，则守卫获得胜利。",
            guide_dec_daobao="此处是守卫和盗宝者的数量，当盗宝者全部被捕，则守卫获得胜利。",
            guide_param="RaiderGuide",
            pos_x=159,
            bottom_wide=170,
            arrow_direction=4,
            is_mirror=0,
            arrow_y=117,
            pos_x2=-2
        },
        {
            step=4,
            index=3,
            guide_dec_shouwei="这是抓捕技能，引导结束后可将范围内的盗宝者抓捕禁锢。长按技能可查看详情。",
            guide_dec_daobao="这里是开锁技能，施法结束后可盗走宝箱。长按可查看详情。",
            guide_param="MainSkillGuide",
            pos_x=535,
            pos_y=44,
            bottom_wide=170,
            arrow_x=79,
            arrow_y=-118,
            pos_x2=-94,
            pos_y2=205
        },
        {
            step=5,
            index=4,
            guide_dec_shouwei="这是疾走技能，使用后将短暂增加自己移动速度。长按可查看详情",
            guide_dec_daobao="这里是救援技能，施法结束后可解救范围内被捕队友。长按可查看详情。",
            guide_param="Skill1Guide",
            pos_x=361,
            pos_y=-142,
            arrow_x=40,
            pos_x2=-52,
            pos_y2=168
        },
        {
            step=6,
            index=5,
            guide_dec_shouwei="这是传送技能，施法结束后将随机传送到遗迹任意位置。长按技能可查看详情。",
            guide_dec_daobao="这里是隐身技能，引导结束后可短暂增加速度。长按可查看详情。",
            guide_param="Skill2Guide",
            pos_x=423,
            pos_y=-142,
            arrow_x=91,
            pos_x2=-107,
            pos_y2=160
        },
        {
            step=7,
            index=6,
            guide_dec_shouwei="此处是道具框，遗迹中拾取的道具将会暂存在这，点击道具可使用，使用后道具消失。",
            guide_dec_daobao="此处是道具框，遗迹中拾取的道具将会暂存在这，点击道具可使用，使用后道具消失。",
            guide_param="ItemSkillGuide",
            pos_x=305,
            pos_y=-127,
            bottom_wide=170,
            arrow_x=21,
            arrow_y=-94,
            pos_x2=-37,
            pos_y2=162
        },
        {
            step=8,
            index=7,
            guide_dec_shouwei="点击此处可查看地图，地图上标记了当前宝箱拾取情况。",
            guide_dec_daobao="点击此处可查看地图，地图上标记了当前宝箱拾取情况。",
            guide_param="SmallMapGuide",
            pos_x=-204,
            pos_y=194,
            arrow_direction=1,
            is_mirror=0,
            arrow_x=-190,
            arrow_y=11,
            pos_x2=364,
            pos_y2=-30
        },
        {
            step=9,
            index=8,
            guide_dec_shouwei="黄色标记为未被开启的宝箱，灰色为已开启宝箱。",
            guide_dec_daobao="黄色标记为未被开启的宝箱，灰色为已开启宝箱。",
            guide_param="MapShowGuide",
            is_special=1,
            pos_x=330,
            pos_y=-26,
            arrow_direction=1,
            is_mirror=0,
            arrow_x=-190,
            arrow_y=11,
            advance=0,
            pos_x2=369,
            pos_y2=76
        },
        {
            step=10,
            index=9,
            guide_dec_shouwei="此处记录了当前已获得功勋点数，点击可查看当前对局积分情况。",
            guide_dec_daobao="此处记录了当前已获得功勋点数，点击可查看当前对局积分情况。",
            guide_param="PointGuide",
            is_special=1,
            pos_x=562,
            pos_y=214,
            arrow_direction=4,
            arrow_x=11,
            arrow_y=84,
            pos_x2=-18,
            pos_y2=-135
        },
        {
            step=11,
            index=10,
            guide_dec_shouwei="靠近道具时，点击该按钮可拾取道具。",
            guide_dec_daobao="靠近道具时，点击该按钮可拾取道具。",
            guide_param="PickGuide",
            is_special=1,
            pos_x=488,
            pos_y=50,
            arrow_x=-13,
            pos_x2=-3,
            pos_y2=164
        }
    }
}
SetConfigDefaultVal(Config.treasure_contend_auto,_default_val,nil,nil,nil)