local _default_val={
    treasure_reward={
        type=1,
        parameter1=0,
        parameter2=0,
        parameter3=1,
        open_panel=66001
    }
}
local _itemlist={
    i_24481_1_1={
        item_id=24481,
        num=1,
        is_bind=1
    },
    i_24482_1_1={
        item_id=24482,
        num=1,
        is_bind=1
    },
    i_24478_1_1={
        item_id=24478,
        num=1,
        is_bind=1
    },
    i_24483_1_1={
        item_id=24483,
        num=1,
        is_bind=1
    }
}
Config.tujian_treasure_auto={
    other={
        {
            open_grade=48,
            open_time=72
        }
    },
    login_reward={
        {
            seq=0,
            sign_day=1,
            item=_itemlist.i_24481_1_1
        },
        {
            seq=1,
            sign_day=2,
            item=_itemlist.i_24482_1_1
        },
        {
            seq=2,
            sign_day=3,
            item=_itemlist.i_24478_1_1
        }
    },
    treasure_reward={
        {
            seq=0,
            parameter1=53001,
            item=_itemlist.i_24482_1_1,
            describe="击败<color=#a05838>【神秘妖灵】</color>野外首领"
        },
        {
            seq=1,
            parameter1=53002,
            item=_itemlist.i_24482_1_1,
            describe="击败<color=#a05838>【湮灭之灵】</color>野外首领"
        },
        {
            seq=2,
            type=3,
            item=_itemlist.i_24482_1_1,
            describe="交易所成功出售任意<color=#a05838>【图鉴卡】</color>",
            open_panel=18001
        },
        {
            seq=3,
            type=3,
            parameter2=1,
            item=_itemlist.i_24483_1_1,
            describe="交易所成功购买任意<color=#a05838>【图鉴卡】</color>",
            open_panel=18001
        }
    }
}
SetConfigDefaultVal(Config.tujian_treasure_auto,_default_val,nil,nil,nil)