local _default_val={
    cornucopia_configure={
        section_start=1,
        section_end=0,
        limit_type=1,
        buy_times=1,
        today_times=0
    }
}
Config.wealth_cornucopia_auto={
    cornucopia_configure={
        {
            type=0,
            seq=0,
            gold_num=60,
            gold_give=15,
            buy_money=60,
            gold_icon=1
        },
        {
            type=1,
            seq=1,
            gold_num=300,
            gold_give=75,
            buy_money=300,
            gold_icon=2
        },
        {
            type=2,
            seq=2,
            gold_num=500,
            gold_give=125,
            buy_money=500,
            gold_icon=3
        },
        {
            type=3,
            seq=3,
            gold_num=980,
            gold_give=245,
            buy_money=980,
            gold_icon=4
        },
        {
            type=4,
            seq=4,
            gold_num=1280,
            gold_give=320,
            buy_money=1280,
            gold_icon=5
        },
        {
            type=5,
            seq=5,
            gold_num=1980,
            gold_give=495,
            buy_money=1980,
            gold_icon=6
        },
        {
            type=6,
            seq=6,
            gold_num=3280,
            gold_give=820,
            buy_money=3280,
            gold_icon=7
        },
        {
            type=7,
            seq=7,
            gold_num=6480,
            gold_give=1620,
            buy_money=6480,
            gold_icon=8
        }
    },
    other={
        {
            percentage=25,
            cfg_ver=3
        }
    }
}
SetConfigDefaultVal(Config.wealth_cornucopia_auto,_default_val,nil,nil,nil)