local _default_val={
    coordinate_group={
        y=120,
        scene_id=123,
        dir=0
    },
    lattice={
        type=0,
        group=1,
        word_0="人",
        word_1="花",
        word_2="桃",
        word_3="花",
        word_4=16,
        word_5=2,
        word_6="枝",
        word_7=0,
        word_8=0,
        word_9=0,
        word_10=0,
        word_11=0
    },
    word_group={
        group=1,
        seq=1,
        word="何"
    },
    time_list={
        type=3
    },
    game_list={
        talk_finish=11062,
        talk_fail=11063
    }
}
local _itemlist={
    i_31318_1_1={
        item_id=31318,
        num=1,
        is_bind=1
    },
    i_26230_1_1={
        item_id=26230,
        num=1,
        is_bind=1
    }
}
Config.where_is_the_fairy_auto={
    play_config={
        {
            npc_id=73711
        }
    },
    coordinate_group={
        {
            x=72,
            y=390
        },
        {
            x=220,
            y=162
        },
        {
            x=134,
            scene_id=163
        },
        {
            x=254,
            y=354,
            scene_id=163
        },
        {
            x=236,
            scene_id=131
        },
        {
            x=386,
            y=414,
            scene_id=131
        },
        {
            x=152,
            y=122,
            scene_id=209
        },
        {
            x=68,
            y=36,
            scene_id=113
        },
        {
            x=132,
            y=140,
            scene_id=211
        },
        {
            x=138,
            y=60,
            scene_id=206
        },
        {
            x=190,
            y=208,
            scene_id=256
        },
        {
            x=52,
            y=16,
            scene_id=139
        },
        {
            x=210,
            y=14,
            scene_id=139
        }
    },
    group_id={},
    item_show={
        {
            reward={
                [0]=_itemlist.i_31318_1_1,
                [1]=_itemlist.i_26230_1_1
            }
        }
    },
    lattice={
        {
            seq=1,
            word_0="山",
            word_1="有",
            word_2="木",
            word_3="兮",
            word_4="木",
            word_5="有",
            word="山有木兮木有枝"
        },
        {
            seq=2,
            type=1,
            word_0="心",
            word_1=6,
            word_2="君",
            word_3=12,
            word_4=14,
            word_6=4,
            word="心悦君兮君不知"
        },
        {
            seq=3,
            group=2,
            word_1="生",
            word_2="若",
            word_3="只",
            word_5=8,
            word_6=5,
            word="人生若只如初见"
        },
        {
            seq=4,
            type=1,
            group=2,
            word_0=11,
            word_1=2,
            word_2="秋",
            word_3="风",
            word_4=13,
            word_5="画",
            word_6="扇",
            word="何事秋风悲画扇"
        },
        {
            seq=5,
            group=3,
            word_0="去",
            word_1="年",
            word_2=1,
            word_3="日",
            word_4=9,
            word_5="门",
            word_6="中",
            word="去年今日此门中"
        },
        {
            seq=6,
            type=1,
            group=3,
            word_0=14,
            word_1="面",
            word_2=17,
            word_4="相",
            word_5=6,
            word_6="红",
            word="人面桃花相映红"
        },
        {
            seq=7,
            group=4,
            word_1=3,
            word_2="不",
            word_3="知",
            word_5=9,
            word_6="去",
            word="人面不知何处去"
        },
        {
            seq=8,
            type=1,
            group=4,
            word_0="桃",
            word_2=5,
            word_3=13,
            word_4="笑",
            word_5="春",
            word_6="风",
            word="桃花依旧笑春风"
        },
        {
            seq=9,
            group=5,
            word_1=9,
            word_2="四",
            word_3=1,
            word_4="芳",
            word_5="菲",
            word_6=15,
            word="人间四月芳菲尽"
        },
        {
            seq=10,
            type=1,
            group=5,
            word_0="山",
            word_1=5,
            word_4="始",
            word_5=12,
            word_6="开",
            word="山寺桃花始盛开"
        },
        {
            seq=11,
            group=6,
            word_0="竹",
            word_1=10,
            word_3=7,
            word_4="三",
            word_5="两",
            word="竹外桃花三两枝"
        },
        {
            seq=12,
            type=1,
            group=6,
            word_0="春",
            word_1=13,
            word_2=5,
            word_3="暖",
            word_4="鸭",
            word_6="知",
            word="春江水暖鸭先知"
        },
        {
            seq=13,
            group=7,
            word_0=3,
            word_2=9,
            word_3="水",
            word_4=2,
            word_5="然",
            word_6="去",
            word="桃花流水窅然去"
        },
        {
            seq=14,
            type=1,
            group=7,
            word_0="别",
            word_1="有",
            word_2=13,
            word_3=18,
            word_4="非",
            word_5="人",
            word_6="间",
            word="别有天地非人间"
        }
    },
    word_group={
        {
            word="样"
        },
        {
            seq=2,
            word="不"
        },
        {
            seq=3,
            word="玉"
        },
        {
            seq=4,
            word="知"
        },
        {
            seq=5,
            word="云"
        },
        {
            seq=6,
            word="悦"
        },
        {
            seq=7
        },
        {
            seq=8,
            word="船"
        },
        {
            seq=9,
            word="门"
        },
        {
            seq=10,
            word="白"
        },
        {
            seq=11,
            word="起"
        },
        {
            seq=12,
            word="兮"
        },
        {
            seq=13,
            word="我"
        },
        {
            seq=14,
            word="君"
        },
        {
            seq=15,
            word="须"
        },
        {
            seq=16,
            word="城"
        },
        {
            seq=17,
            word="需"
        },
        {
            seq=18,
            word="也"
        },
        {
            group=2,
            word="枝"
        },
        {
            group=2,
            seq=2,
            word="事"
        },
        {
            group=2,
            seq=3,
            word="崔"
        },
        {
            group=2,
            seq=4,
            word="岐"
        },
        {
            group=2,
            seq=5,
            word="见"
        },
        {
            group=2,
            seq=6,
            word="九"
        },
        {
            group=2,
            seq=7,
            word="翼"
        },
        {
            group=2,
            seq=8,
            word="初"
        },
        {
            group=2,
            seq=9,
            word="堂"
        },
        {
            group=2,
            seq=10,
            word="逢"
        },
        {
            group=2,
            seq=11
        },
        {
            group=2,
            seq=12,
            word="前"
        },
        {
            group=2,
            seq=13,
            word="悲"
        },
        {
            group=2,
            seq=14,
            word="宵"
        },
        {
            group=2,
            seq=15,
            word="罢"
        },
        {
            group=2,
            seq=16,
            word="如"
        },
        {
            group=2,
            seq=17,
            word="骊"
        },
        {
            group=2,
            seq=18,
            word="景"
        },
        {
            group=3,
            word="今"
        },
        {
            group=3,
            seq=2,
            word="鞋"
        },
        {
            group=3,
            seq=3,
            word="驾"
        },
        {
            group=3,
            seq=4,
            word="湖"
        },
        {
            group=3,
            seq=5,
            word="舟"
        },
        {
            group=3,
            seq=6,
            word="映"
        },
        {
            group=3,
            seq=7,
            word="卷"
        },
        {
            group=3,
            seq=8,
            word="漫"
        },
        {
            group=3,
            seq=9,
            word="此"
        },
        {
            group=3,
            seq=10,
            word="寻"
        },
        {
            group=3,
            seq=11,
            word="与"
        },
        {
            group=3,
            seq=12,
            word="踏"
        },
        {
            group=3,
            seq=13,
            word="看"
        },
        {
            group=3,
            seq=14,
            word="人"
        },
        {
            group=3,
            seq=15,
            word="够"
        },
        {
            group=3,
            seq=16,
            word="诗"
        },
        {
            group=3,
            seq=17,
            word="桃"
        },
        {
            group=3,
            seq=18,
            word="却"
        },
        {
            group=4,
            word="远"
        },
        {
            group=4,
            seq=2,
            word="随"
        },
        {
            group=4,
            seq=3,
            word="面"
        },
        {
            group=4,
            seq=4,
            word="流"
        },
        {
            group=4,
            seq=5,
            word="依"
        },
        {
            group=4,
            seq=6,
            word="山"
        },
        {
            group=4,
            seq=7,
            word="自"
        },
        {
            group=4,
            seq=8,
            word="闲"
        },
        {
            group=4,
            seq=9,
            word="处"
        },
        {
            group=4,
            seq=10,
            word="隔"
        },
        {
            group=4,
            seq=11,
            word="李"
        },
        {
            group=4,
            seq=12,
            word="花"
        },
        {
            group=4,
            seq=13,
            word="旧"
        },
        {
            group=4,
            seq=14,
            word="遥"
        },
        {
            group=4,
            seq=15,
            word="源"
        },
        {
            group=4,
            seq=16
        },
        {
            group=4,
            seq=17,
            word="栖"
        },
        {
            group=4,
            seq=18,
            word="事"
        },
        {
            group=5,
            word="月"
        },
        {
            group=5,
            seq=2,
            word="荷"
        },
        {
            group=5,
            seq=3,
            word="景"
        },
        {
            group=5,
            seq=4,
            word="黄"
        },
        {
            group=5,
            seq=5,
            word="寺"
        },
        {
            group=5,
            seq=6,
            word="浙"
        },
        {
            group=5,
            seq=7,
            word="季"
        },
        {
            group=5,
            seq=8,
            word="枯"
        },
        {
            group=5,
            seq=9,
            word="间"
        },
        {
            group=5,
            seq=10,
            word="舒"
        },
        {
            group=5,
            seq=11,
            word="橙"
        },
        {
            group=5,
            seq=12,
            word="盛"
        },
        {
            group=5,
            seq=13,
            word="展"
        },
        {
            group=5,
            seq=14,
            word="霜"
        },
        {
            group=5,
            seq=15,
            word="尽"
        },
        {
            group=5,
            seq=16,
            word="凋"
        },
        {
            group=5,
            seq=17,
            word="荐"
        },
        {
            group=5,
            seq=18,
            word="菊"
        },
        {
            group=6,
            word="绿"
        },
        {
            group=6,
            seq=2,
            word="先"
        },
        {
            group=6,
            seq=3,
            word="田"
        },
        {
            group=6,
            seq=4,
            word="裙"
        },
        {
            group=6,
            seq=5,
            word="水"
        },
        {
            group=6,
            seq=6,
            word="罗"
        },
        {
            group=6,
            seq=7,
            word="花"
        },
        {
            group=6,
            seq=8,
            word="色"
        },
        {
            group=6,
            seq=9,
            word="佛"
        },
        {
            group=6,
            seq=10,
            word="外"
        },
        {
            group=6,
            seq=11,
            word="前"
        },
        {
            group=6,
            seq=12,
            word="声"
        },
        {
            group=6,
            seq=13,
            word="江"
        },
        {
            group=6,
            seq=14,
            word="疏"
        },
        {
            group=6,
            seq=15,
            word="荷"
        },
        {
            group=6,
            seq=16,
            word="芙"
        },
        {
            group=6,
            seq=17,
            word="照"
        },
        {
            group=6,
            seq=18,
            word="歌"
        },
        {
            group=7,
            word="清"
        },
        {
            group=7,
            seq=2,
            word="窅"
        },
        {
            group=7,
            seq=3,
            word="桃"
        },
        {
            group=7,
            seq=4,
            word="蓉"
        },
        {
            group=7,
            seq=5,
            word="闻"
        },
        {
            group=7,
            seq=6,
            word="到"
        },
        {
            group=7,
            seq=7,
            word="裁"
        },
        {
            group=7,
            seq=8,
            word="泼"
        },
        {
            group=7,
            seq=9,
            word="流"
        },
        {
            group=7,
            seq=10,
            word="莲"
        },
        {
            group=7,
            seq=11,
            word="颜"
        },
        {
            group=7,
            seq=12,
            word="红"
        },
        {
            group=7,
            seq=13,
            word="天"
        },
        {
            group=7,
            seq=14,
            word="感"
        },
        {
            group=7,
            seq=15,
            word="凝"
        },
        {
            group=7,
            seq=16,
            word="叶"
        },
        {
            group=7,
            seq=17,
            word="意"
        },
        {
            group=7,
            seq=18,
            word="地"
        }
    },
    time_list={
        {
            strat_time=0,
            end_time=300,
            type=1
        },
        {
            strat_time=300,
            end_time=600
        },
        {
            strat_time=600,
            end_time=900,
            type=2
        },
        {
            strat_time=900,
            end_time=1200
        },
        {
            strat_time=1200,
            end_time=1500,
            type=1
        },
        {
            strat_time=1500,
            end_time=1800,
            type=2
        },
        {
            strat_time=1800,
            end_time=2100
        },
        {
            strat_time=2100,
            end_time=2400,
            type=2
        }
    },
    other={
        {
            group=7,
            talk_id=14029
        }
    },
    game_list={
        {
            game_type=1,
            talk_rule=14026
        },
        {
            game_type=2,
            talk_rule=14027
        },
        {
            game_type=3,
            talk_rule=14028
        }
    }
}
SetConfigDefaultVal(Config.where_is_the_fairy_auto,_default_val,nil,nil,nil)