local _default_val={
    lattice={
        type=0,
        group=1,
        word_4="，",
        word_7=0,
        word_8=0,
        word_9=0,
        word_10=0,
        word_11=0
    },
    word_group={
        group=1,
        seq=1,
        word="可"
    }
}
Config.world_couplet_auto={
    lattice={
        {
            seq=1,
            word_0="青",
            word_1="山",
            word_2="不",
            word_3="墨",
            word_4="千",
            word_5="秋",
            word_6="画"
        },
        {
            seq=2,
            type=1,
            word_0="绿",
            word_1=6,
            word_2=10,
            word_3="弦",
            word_4=2,
            word_5=13,
            word_6=16
        },
        {
            seq=3,
            group=2,
            word_0="雏",
            word_1="凤",
            word_2="学",
            word_3="飞",
            word_5="万",
            word_6="里",
            word_7="风",
            word_8="云",
            word_9="从",
            word_10="此",
            word_11="起"
        },
        {
            seq=4,
            type=1,
            group=2,
            word_0=1,
            word_1=16,
            word_2="奋",
            word_3="起",
            word_5=6,
            word_6=14,
            word_7=10,
            word_8=7,
            word_9="及",
            word_10="时",
            word_11=4
        },
        {
            seq=5,
            group=3,
            word_0="如",
            word_1="来",
            word_2="说",
            word_3="法",
            word_5="狮",
            word_6="吼",
            word_7="象",
            word_8="鸣",
            word_9="声",
            word_10="震",
            word_11="地"
        },
        {
            seq=6,
            type=1,
            group=3,
            word_0=5,
            word_1=2,
            word_2="讲",
            word_3="经",
            word_5=9,
            word_6=18,
            word_7=3,
            word_8=15,
            word_9="气",
            word_10="冲",
            word_11=12
        }
    },
    word_group={
        {
            word="思"
        },
        {
            seq=2,
            word="万"
        },
        {
            seq=3,
            word="则"
        },
        {
            seq=4,
            word="及"
        },
        {
            seq=5
        },
        {
            seq=6,
            word="水"
        },
        {
            seq=7,
            word="他"
        },
        {
            seq=8,
            word="真"
        },
        {
            seq=9,
            word="灵"
        },
        {
            seq=10,
            word="无"
        },
        {
            seq=11,
            word="之"
        },
        {
            seq=12,
            word="时"
        },
        {
            seq=13,
            word="古"
        },
        {
            seq=14,
            word="是"
        },
        {
            seq=15,
            word="即"
        },
        {
            seq=16,
            word="琴"
        },
        {
            seq=17,
            word="玉"
        },
        {
            seq=18,
            word="也"
        },
        {
            group=2,
            word="潜"
        },
        {
            group=2,
            seq=2,
            word="余"
        },
        {
            group=2,
            seq=3,
            word="华"
        },
        {
            group=2,
            seq=4,
            word="来"
        },
        {
            group=2,
            seq=5,
            word="清"
        },
        {
            group=2,
            seq=6,
            word="九"
        },
        {
            group=2,
            seq=7,
            word="雨"
        },
        {
            group=2,
            seq=8,
            word="林"
        },
        {
            group=2,
            seq=9,
            word="夏"
        },
        {
            group=2,
            seq=10,
            word="雷"
        },
        {
            group=2,
            seq=11,
            word="欣"
        },
        {
            group=2,
            seq=12,
            word="心"
        },
        {
            group=2,
            seq=13,
            word="知"
        },
        {
            group=2,
            seq=14,
            word="天"
        },
        {
            group=2,
            seq=15
        },
        {
            group=2,
            seq=16,
            word="龙"
        },
        {
            group=2,
            seq=17,
            word="发"
        },
        {
            group=2,
            seq=18,
            word="下"
        },
        {
            group=3,
            word="罗"
        },
        {
            group=3,
            seq=2,
            word="勒"
        },
        {
            group=3,
            seq=3,
            word="凤"
        },
        {
            group=3,
            seq=4,
            word="行"
        },
        {
            group=3,
            seq=5,
            word="弥"
        },
        {
            group=3,
            seq=6,
            word="归"
        },
        {
            group=3,
            seq=7,
            word="墓"
        },
        {
            group=3,
            seq=8,
            word="旭"
        },
        {
            group=3,
            seq=9,
            word="龙"
        },
        {
            group=3,
            seq=10,
            word="丹"
        },
        {
            group=3,
            seq=11,
            word="清"
        },
        {
            group=3,
            seq=12,
            word="霄"
        },
        {
            group=3,
            seq=13,
            word="河"
        },
        {
            group=3,
            seq=14,
            word="花"
        },
        {
            group=3,
            seq=15,
            word="舞"
        },
        {
            group=3,
            seq=16,
            word="思"
        },
        {
            group=3,
            seq=17,
            word="之"
        },
        {
            group=3,
            seq=18,
            word="飞"
        }
    },
    other={
        {
            special_task_id=65091,
            last_task_id=65093,
            subject_talk_2=72132,
            subject_talk_3=72133,
            restart_talk=72136,
            fail_talk=72135,
            npc_id=687,
            special_bubble=109,
            group=3
        }
    }
}
SetConfigDefaultVal(Config.world_couplet_auto,_default_val,nil,nil,nil)