local _default_val={
    server={
        platform="ml1",
        server=1,
        open_day=59,
        item_group=10
    },
    gift_configure={
        section_start=3,
        section_end=7,
        seq=0,
        item_group=2
    },
    role={
        role_id=2098200579,
        name="祖龙巧儿",
        seq=0
    }
}
local _itemlist={
    i_26813_2_1={
        item_id=26813,
        num=2,
        is_bind=1
    },
    i_24557_2_1={
        item_id=24557,
        num=2,
        is_bind=1
    },
    i_27399_6_1={
        item_id=27399,
        num=6,
        is_bind=1
    },
    i_23908_1_1={
        item_id=23908,
        num=1,
        is_bind=1
    },
    i_24557_3_1={
        item_id=24557,
        num=3,
        is_bind=1
    },
    i_27399_12_1={
        item_id=27399,
        num=12,
        is_bind=1
    },
    i_25614_1_1={
        item_id=25614,
        num=1,
        is_bind=1
    },
    i_25520_1_1={
        item_id=25520,
        num=1,
        is_bind=1
    },
    i_27399_15_1={
        item_id=27399,
        num=15,
        is_bind=1
    },
    i_25505_10_1={
        item_id=25505,
        num=10,
        is_bind=1
    },
    i_27478_200_1={
        item_id=27478,
        num=200,
        is_bind=1
    },
    i_25517_1_1={
        item_id=25517,
        num=1,
        is_bind=1
    },
    i_25505_15_1={
        item_id=25505,
        num=15,
        is_bind=1
    },
    i_27478_300_1={
        item_id=27478,
        num=300,
        is_bind=1
    },
    i_25506_3_1={
        item_id=25506,
        num=3,
        is_bind=1
    },
    i_27478_400_1={
        item_id=27478,
        num=400,
        is_bind=1
    },
    i_25517_2_1={
        item_id=25517,
        num=2,
        is_bind=1
    },
    i_25516_1_1={
        item_id=25516,
        num=1,
        is_bind=1
    },
    i_27478_500_1={
        item_id=27478,
        num=500,
        is_bind=1
    },
    i_25517_3_1={
        item_id=25517,
        num=3,
        is_bind=1
    },
    i_28721_1_1={
        item_id=28721,
        num=1,
        is_bind=1
    },
    i_27403_1_1={
        item_id=27403,
        num=1,
        is_bind=1
    },
    i_28722_1_1={
        item_id=28722,
        num=1,
        is_bind=1
    },
    i_27403_2_1={
        item_id=27403,
        num=2,
        is_bind=1
    },
    i_27403_3_1={
        item_id=27403,
        num=3,
        is_bind=1
    },
    i_28671_1_1={
        item_id=28671,
        num=1,
        is_bind=1
    },
    i_27403_4_1={
        item_id=27403,
        num=4,
        is_bind=1
    },
    i_29067_1_1={
        item_id=29067,
        num=1,
        is_bind=1
    },
    i_27575_10_1={
        item_id=27575,
        num=10,
        is_bind=1
    },
    i_29068_1_1={
        item_id=29068,
        num=1,
        is_bind=1
    },
    i_27575_20_1={
        item_id=27575,
        num=20,
        is_bind=1
    },
    i_29069_1_1={
        item_id=29069,
        num=1,
        is_bind=1
    },
    i_27575_30_1={
        item_id=27575,
        num=30,
        is_bind=1
    },
    i_28147_1_1={
        item_id=28147,
        num=1,
        is_bind=1
    },
    i_27575_40_1={
        item_id=27575,
        num=40,
        is_bind=1
    },
    i_25688_1_1={
        item_id=25688,
        num=1,
        is_bind=1
    },
    i_27671_10_1={
        item_id=27671,
        num=10,
        is_bind=1
    },
    i_25688_2_1={
        item_id=25688,
        num=2,
        is_bind=1
    },
    i_27671_20_1={
        item_id=27671,
        num=20,
        is_bind=1
    },
    i_27672_10_1={
        item_id=27672,
        num=10,
        is_bind=1
    },
    i_25688_3_1={
        item_id=25688,
        num=3,
        is_bind=1
    },
    i_27672_20_1={
        item_id=27672,
        num=20,
        is_bind=1
    },
    i_29017_20_1={
        item_id=29017,
        num=20,
        is_bind=1
    },
    i_29017_25_1={
        item_id=29017,
        num=25,
        is_bind=1
    },
    i_29017_50_1={
        item_id=29017,
        num=50,
        is_bind=1
    },
    i_25516_2_1={
        item_id=25516,
        num=2,
        is_bind=1
    },
    i_25516_3_1={
        item_id=25516,
        num=3,
        is_bind=1
    },
    i_27478_750_1={
        item_id=27478,
        num=750,
        is_bind=1
    },
    i_25516_5_1={
        item_id=25516,
        num=5,
        is_bind=1
    },
    i_25853_1_1={
        item_id=25853,
        num=1,
        is_bind=1
    },
    i_27830_10_1={
        item_id=27830,
        num=10,
        is_bind=1
    },
    i_27830_20_1={
        item_id=27830,
        num=20,
        is_bind=1
    },
    i_27830_30_1={
        item_id=27830,
        num=30,
        is_bind=1
    },
    i_25853_2_1={
        item_id=25853,
        num=2,
        is_bind=1
    },
    i_27830_40_1={
        item_id=27830,
        num=40,
        is_bind=1
    }
}
Config.xianshileichongbufa_auto={
    server={
        {
            platform="ma1"
        },
        {
            platform="ma1",
            server=2
        },
        {
            platform="ma1",
            server=3
        },
        {
            platform="ma1",
            server=4
        },
        {
            platform="ma1",
            server=5
        },
        {
            platform="ma1",
            server=6,
            open_day=58
        },
        {
            platform="ma1",
            server=7,
            open_day=58
        },
        {
            platform="ma1",
            server=8,
            open_day=58
        },
        {
            platform="ma1",
            server=9,
            open_day=57
        },
        {
            platform="ma1",
            server=10,
            open_day=56,
            item_group=9
        },
        {
            platform="ma1",
            server=11,
            open_day=55,
            item_group=9
        },
        {
            platform="ma1",
            server=12,
            open_day=54,
            item_group=9
        },
        {
            platform="ma1",
            server=13,
            open_day=53,
            item_group=9
        },
        {
            platform="ma1",
            server=14,
            open_day=52,
            item_group=9
        },
        {
            platform="ma1",
            server=15,
            open_day=51,
            item_group=9
        },
        {
            platform="ma1",
            server=16,
            open_day=50,
            item_group=9
        },
        {
            platform="ma1",
            server=17,
            open_day=49,
            item_group=9
        },
        {
            platform="ma1",
            server=18,
            open_day=48,
            item_group=8
        },
        {
            platform="ma1",
            server=19,
            open_day=47,
            item_group=8
        },
        {
            platform="ma1",
            server=20,
            open_day=46,
            item_group=8
        },
        {
            platform="ma1",
            server=21,
            open_day=45,
            item_group=8
        },
        {
            platform="ma1",
            server=22,
            open_day=44,
            item_group=8
        },
        {
            platform="ma1",
            server=23,
            open_day=43,
            item_group=8
        },
        {
            platform="ma1",
            server=24,
            open_day=42,
            item_group=7
        },
        {
            platform="ma1",
            server=25,
            open_day=41,
            item_group=7
        },
        {
            platform="ma1",
            server=26,
            open_day=40,
            item_group=7
        },
        {
            platform="ma1",
            server=27,
            open_day=39,
            item_group=7
        },
        {
            platform="ma1",
            server=28,
            open_day=38,
            item_group=7
        },
        {
            platform="ma1",
            server=29,
            open_day=37,
            item_group=7
        },
        {
            platform="ma1",
            server=30,
            open_day=36,
            item_group=7
        },
        {
            platform="ma1",
            server=31,
            open_day=35,
            item_group=6
        },
        {
            platform="ma1",
            server=32,
            open_day=34,
            item_group=6
        },
        {
            platform="ma1",
            server=33,
            open_day=33,
            item_group=6
        },
        {
            platform="ma1",
            server=34,
            open_day=32,
            item_group=6
        },
        {
            platform="ma1",
            server=35,
            open_day=31,
            item_group=6
        },
        {
            platform="ma1",
            server=36,
            open_day=30,
            item_group=6
        },
        {
            platform="ma1",
            server=37,
            open_day=29,
            item_group=6
        },
        {
            platform="ma1",
            server=38,
            open_day=28,
            item_group=5
        },
        {
            platform="ma1",
            server=39,
            open_day=27,
            item_group=5
        },
        {
            platform="ma1",
            server=40,
            open_day=26,
            item_group=5
        },
        {
            platform="ma1",
            server=41,
            open_day=25,
            item_group=5
        },
        {
            platform="ma1",
            server=42,
            open_day=24,
            item_group=5
        },
        {
            platform="ma1",
            server=43,
            open_day=23,
            item_group=5
        },
        {
            platform="ma1",
            server=44,
            open_day=22,
            item_group=5
        },
        {
            platform="ma1",
            server=45,
            open_day=21,
            item_group=4
        },
        {
            platform="ma1",
            server=46,
            open_day=20,
            item_group=4
        },
        {
            platform="ma1",
            server=47,
            open_day=19,
            item_group=4
        },
        {
            platform="ma1",
            server=48,
            open_day=17,
            item_group=4
        },
        {
            platform="ma1",
            server=49,
            open_day=15,
            item_group=4
        },
        {
            platform="ma1",
            server=50,
            open_day=13,
            item_group=3
        },
        {
            platform="ma1",
            server=51,
            open_day=11,
            item_group=3
        },
        {
            platform="ma1",
            server=52,
            open_day=9,
            item_group=3
        },
        {
            platform="ma1",
            server=53,
            open_day=7,
            item_group=2
        },
        {
            platform="ma1",
            server=54,
            open_day=5,
            item_group=2
        },
        {
            platform="ma1",
            server=55,
            open_day=3,
            item_group=2
        },
        {
            platform="ma1",
            server=56,
            open_day=1,
            item_group=1
        },
        {
            open_day=398
        },
        {
            server=2,
            open_day=397
        },
        {
            server=3,
            open_day=397
        },
        {
            server=4,
            open_day=396
        },
        {
            server=5,
            open_day=348
        },
        {
            server=6,
            open_day=347
        },
        {
            server=7,
            open_day=346
        },
        {
            server=8,
            open_day=345
        },
        {
            server=9,
            open_day=257
        },
        {
            server=10,
            open_day=256
        },
        {
            server=11,
            open_day=255
        },
        {
            server=12,
            open_day=254
        },
        {
            server=13,
            open_day=253
        },
        {
            server=14,
            open_day=256
        },
        {
            server=15,
            open_day=164
        },
        {
            server=16,
            open_day=162
        },
        {
            server=17,
            open_day=161
        },
        {
            server=18,
            open_day=160
        },
        {
            server=19,
            open_day=159
        },
        {
            server=20,
            open_day=158
        },
        {
            server=21,
            open_day=157
        },
        {
            server=22,
            open_day=156
        },
        {
            server=23,
            open_day=155
        },
        {
            server=24,
            open_day=154
        },
        {
            server=25,
            open_day=153
        },
        {
            server=26,
            open_day=152
        },
        {
            server=27,
            open_day=151
        },
        {
            server=28,
            open_day=150
        },
        {
            server=29,
            open_day=149
        },
        {
            server=30,
            open_day=148
        },
        {
            server=31,
            open_day=147
        },
        {
            server=32,
            open_day=146
        },
        {
            server=33,
            open_day=145
        },
        {
            server=34,
            open_day=144
        },
        {
            server=35,
            open_day=143
        },
        {
            server=36,
            open_day=142
        },
        {
            server=37,
            open_day=141
        },
        {
            server=38,
            open_day=140
        },
        {
            server=39,
            open_day=139
        },
        {
            server=40,
            open_day=138
        },
        {
            server=41,
            open_day=137
        },
        {
            server=42,
            open_day=136
        },
        {
            server=43,
            open_day=135
        },
        {
            server=44,
            open_day=134
        },
        {
            server=45,
            open_day=133
        },
        {
            server=46,
            open_day=132
        },
        {
            server=47,
            open_day=131
        },
        {
            server=48,
            open_day=130
        },
        {
            server=49,
            open_day=129
        },
        {
            server=50,
            open_day=128
        },
        {
            server=51,
            open_day=127
        },
        {
            server=52,
            open_day=126
        },
        {
            server=53,
            open_day=125
        },
        {
            server=54,
            open_day=124
        },
        {
            server=55,
            open_day=123
        },
        {
            server=56,
            open_day=122
        },
        {
            server=57,
            open_day=121
        },
        {
            server=58,
            open_day=120
        },
        {
            server=59,
            open_day=119
        },
        {
            server=60,
            open_day=118
        },
        {
            server=61,
            open_day=117
        },
        {
            server=62,
            open_day=116
        },
        {
            server=63,
            open_day=115
        },
        {
            server=64,
            open_day=114
        },
        {
            server=65,
            open_day=113
        },
        {
            server=66,
            open_day=112
        },
        {
            server=67,
            open_day=111
        },
        {
            server=68,
            open_day=110
        },
        {
            server=69,
            open_day=109
        },
        {
            server=70,
            open_day=108
        },
        {
            server=71,
            open_day=107
        },
        {
            server=72,
            open_day=106
        },
        {
            server=73,
            open_day=105
        },
        {
            server=74,
            open_day=105
        },
        {
            server=75,
            open_day=105
        },
        {
            server=76,
            open_day=27,
            item_group=5
        },
        {
            server=77,
            open_day=26,
            item_group=5
        },
        {
            server=78,
            open_day=25,
            item_group=5
        },
        {
            server=79,
            open_day=24,
            item_group=5
        },
        {
            server=80,
            open_day=23,
            item_group=5
        },
        {
            server=81,
            open_day=22,
            item_group=5
        },
        {
            server=82,
            open_day=21,
            item_group=4
        },
        {
            server=83,
            open_day=20,
            item_group=4
        },
        {
            server=84,
            open_day=19,
            item_group=4
        },
        {
            server=85,
            open_day=18,
            item_group=4
        },
        {
            server=86,
            open_day=17,
            item_group=4
        },
        {
            server=87,
            open_day=16,
            item_group=4
        },
        {
            server=88,
            open_day=15,
            item_group=4
        },
        {
            server=89,
            open_day=14,
            item_group=3
        },
        {
            server=90,
            open_day=13,
            item_group=3
        },
        {
            server=91,
            open_day=12,
            item_group=3
        },
        {
            server=92,
            open_day=11,
            item_group=3
        },
        {
            server=93,
            open_day=10,
            item_group=3
        },
        {
            server=94,
            open_day=10,
            item_group=3
        },
        {
            server=95,
            open_day=9,
            item_group=3
        },
        {
            server=96,
            open_day=8,
            item_group=3
        },
        {
            server=97,
            open_day=7,
            item_group=2
        },
        {
            server=98,
            open_day=6,
            item_group=2
        },
        {
            server=99,
            open_day=5,
            item_group=2
        },
        {
            server=100,
            open_day=4,
            item_group=2
        },
        {
            server=101,
            open_day=3,
            item_group=2
        },
        {
            server=102,
            open_day=2,
            item_group=1
        },
        {
            server=103,
            open_day=1,
            item_group=1
        },
        {
            server=104,
            open_day=0,
            item_group=1
        },
        {
            server=2001,
            open_day=60
        },
        {
            platform="dev",
            server=93,
            open_day=48,
            item_group=8
        },
        {
            platform="ma1",
            server=2001,
            open_day=20,
            item_group=4
        }
    },
    gift_configure={
        {
            section_start=1,
            section_end=2,
            item_group=1,
            reward_item={
                [0]=_itemlist.i_26813_2_1,
                [1]=_itemlist.i_24557_2_1,
                [2]=_itemlist.i_27399_6_1
            }
        },
        {
            section_start=1,
            section_end=2,
            seq=1,
            item_group=1,
            reward_item={
                [0]=_itemlist.i_23908_1_1,
                [1]=_itemlist.i_24557_3_1,
                [2]=_itemlist.i_27399_12_1
            }
        },
        {
            section_start=1,
            section_end=2,
            seq=2,
            item_group=1,
            reward_item={
                [0]=_itemlist.i_25614_1_1,
                [1]=_itemlist.i_25520_1_1,
                [2]=_itemlist.i_27399_15_1
            }
        },
        {
            reward_item={
                [0]=_itemlist.i_25505_10_1,
                [1]=_itemlist.i_27478_200_1,
                [2]=_itemlist.i_25517_1_1
            }
        },
        {
            seq=1,
            reward_item={
                [0]=_itemlist.i_25505_15_1,
                [1]=_itemlist.i_27478_300_1,
                [2]=_itemlist.i_25517_1_1
            }
        },
        {
            seq=2,
            reward_item={
                [0]=_itemlist.i_25506_3_1,
                [1]=_itemlist.i_27478_400_1,
                [2]=_itemlist.i_25517_2_1
            }
        },
        {
            seq=3,
            reward_item={
                [0]=_itemlist.i_25516_1_1,
                [1]=_itemlist.i_27478_500_1,
                [2]=_itemlist.i_25517_3_1
            }
        },
        {
            section_start=8,
            section_end=14,
            item_group=3,
            reward_item={
                [0]=_itemlist.i_28721_1_1,
                [1]=_itemlist.i_27403_1_1,
                [2]=_itemlist.i_25517_1_1
            }
        },
        {
            section_start=8,
            section_end=14,
            seq=1,
            item_group=3,
            reward_item={
                [0]=_itemlist.i_28722_1_1,
                [1]=_itemlist.i_27403_2_1,
                [2]=_itemlist.i_25517_1_1
            }
        },
        {
            section_start=8,
            section_end=14,
            seq=2,
            item_group=3,
            reward_item={
                [0]=_itemlist.i_28722_1_1,
                [1]=_itemlist.i_27403_3_1,
                [2]=_itemlist.i_25517_2_1
            }
        },
        {
            section_start=8,
            section_end=14,
            seq=3,
            item_group=3,
            reward_item={
                [0]=_itemlist.i_28671_1_1,
                [1]=_itemlist.i_27403_4_1,
                [2]=_itemlist.i_25517_3_1
            }
        },
        {
            section_start=15,
            section_end=21,
            item_group=4,
            reward_item={
                [0]=_itemlist.i_29067_1_1,
                [1]=_itemlist.i_27575_10_1,
                [2]=_itemlist.i_25517_1_1
            }
        },
        {
            section_start=15,
            section_end=21,
            seq=1,
            item_group=4,
            reward_item={
                [0]=_itemlist.i_29068_1_1,
                [1]=_itemlist.i_27575_20_1,
                [2]=_itemlist.i_25517_1_1
            }
        },
        {
            section_start=15,
            section_end=21,
            seq=2,
            item_group=4,
            reward_item={
                [0]=_itemlist.i_29069_1_1,
                [1]=_itemlist.i_27575_30_1,
                [2]=_itemlist.i_25517_2_1
            }
        },
        {
            section_start=15,
            section_end=21,
            seq=3,
            item_group=4,
            reward_item={
                [0]=_itemlist.i_28147_1_1,
                [1]=_itemlist.i_27575_40_1,
                [2]=_itemlist.i_25517_3_1
            }
        },
        {
            section_start=22,
            section_end=28,
            item_group=5,
            reward_item={
                [0]=_itemlist.i_25688_1_1,
                [1]=_itemlist.i_27671_10_1,
                [2]=_itemlist.i_25517_1_1
            }
        },
        {
            section_start=22,
            section_end=28,
            seq=1,
            item_group=5,
            reward_item={
                [0]=_itemlist.i_25688_2_1,
                [1]=_itemlist.i_27671_20_1,
                [2]=_itemlist.i_25517_1_1
            }
        },
        {
            section_start=22,
            section_end=28,
            seq=2,
            item_group=5,
            reward_item={
                [0]=_itemlist.i_25688_2_1,
                [1]=_itemlist.i_27672_10_1,
                [2]=_itemlist.i_25517_2_1
            }
        },
        {
            section_start=22,
            section_end=28,
            seq=3,
            item_group=5,
            reward_item={
                [0]=_itemlist.i_25688_3_1,
                [1]=_itemlist.i_27672_20_1,
                [2]=_itemlist.i_25517_3_1
            }
        },
        {
            section_start=29,
            section_end=35,
            item_group=6,
            reward_item={
                [0]=_itemlist.i_29017_20_1,
                [1]=_itemlist.i_27403_1_1,
                [2]=_itemlist.i_25517_1_1
            }
        },
        {
            section_start=29,
            section_end=35,
            seq=1,
            item_group=6,
            reward_item={
                [0]=_itemlist.i_29017_25_1,
                [1]=_itemlist.i_27403_2_1,
                [2]=_itemlist.i_25517_1_1
            }
        },
        {
            section_start=29,
            section_end=35,
            seq=2,
            item_group=6,
            reward_item={
                [0]=_itemlist.i_29017_25_1,
                [1]=_itemlist.i_27403_3_1,
                [2]=_itemlist.i_25517_2_1
            }
        },
        {
            section_start=29,
            section_end=35,
            seq=3,
            item_group=6,
            reward_item={
                [0]=_itemlist.i_29017_50_1,
                [1]=_itemlist.i_27403_4_1,
                [2]=_itemlist.i_25517_3_1
            }
        },
        {
            section_start=36,
            section_end=42,
            item_group=7,
            reward_item={
                [0]=_itemlist.i_25516_1_1,
                [1]=_itemlist.i_27478_500_1,
                [2]=_itemlist.i_25517_1_1
            }
        },
        {
            section_start=36,
            section_end=42,
            seq=1,
            item_group=7,
            reward_item={
                [0]=_itemlist.i_25516_2_1,
                [1]=_itemlist.i_27478_500_1,
                [2]=_itemlist.i_25517_1_1
            }
        },
        {
            section_start=36,
            section_end=42,
            seq=2,
            item_group=7,
            reward_item={
                [0]=_itemlist.i_25516_3_1,
                [1]=_itemlist.i_27478_750_1,
                [2]=_itemlist.i_25517_2_1
            }
        },
        {
            section_start=36,
            section_end=42,
            seq=3,
            item_group=7,
            reward_item={
                [0]=_itemlist.i_25516_5_1,
                [1]=_itemlist.i_27478_750_1,
                [2]=_itemlist.i_25517_3_1
            }
        },
        {
            section_start=43,
            section_end=48,
            item_group=8,
            reward_item={
                [0]=_itemlist.i_28721_1_1,
                [1]=_itemlist.i_27403_1_1,
                [2]=_itemlist.i_25517_1_1
            }
        },
        {
            section_start=43,
            section_end=48,
            seq=1,
            item_group=8,
            reward_item={
                [0]=_itemlist.i_28722_1_1,
                [1]=_itemlist.i_27403_2_1,
                [2]=_itemlist.i_25517_1_1
            }
        },
        {
            section_start=43,
            section_end=48,
            seq=2,
            item_group=8,
            reward_item={
                [0]=_itemlist.i_28722_1_1,
                [1]=_itemlist.i_27403_3_1,
                [2]=_itemlist.i_25517_2_1
            }
        },
        {
            section_start=43,
            section_end=48,
            seq=3,
            item_group=8,
            reward_item={
                [0]=_itemlist.i_28671_1_1,
                [1]=_itemlist.i_27403_4_1,
                [2]=_itemlist.i_28722_1_1
            }
        },
        {
            section_start=49,
            section_end=56,
            item_group=9,
            reward_item={
                [0]=_itemlist.i_25688_2_1,
                [1]=_itemlist.i_27671_10_1,
                [2]=_itemlist.i_25517_1_1
            }
        },
        {
            section_start=49,
            section_end=56,
            seq=1,
            item_group=9,
            reward_item={
                [0]=_itemlist.i_25688_2_1,
                [1]=_itemlist.i_27671_20_1,
                [2]=_itemlist.i_25517_1_1
            }
        },
        {
            section_start=49,
            section_end=56,
            seq=2,
            item_group=9,
            reward_item={
                [0]=_itemlist.i_25688_3_1,
                [1]=_itemlist.i_27672_10_1,
                [2]=_itemlist.i_25517_2_1
            }
        },
        {
            section_start=49,
            section_end=56,
            seq=3,
            item_group=9,
            reward_item={
                [0]=_itemlist.i_25688_3_1,
                [1]=_itemlist.i_27672_20_1,
                [2]=_itemlist.i_25517_3_1
            }
        },
        {
            section_start=57,
            section_end=0,
            item_group=10,
            reward_item={
                [0]=_itemlist.i_25853_1_1,
                [1]=_itemlist.i_27830_10_1,
                [2]=_itemlist.i_25517_1_1
            }
        },
        {
            section_start=57,
            section_end=0,
            seq=1,
            item_group=10,
            reward_item={
                [0]=_itemlist.i_25853_1_1,
                [1]=_itemlist.i_27830_20_1,
                [2]=_itemlist.i_25517_1_1
            }
        },
        {
            section_start=57,
            section_end=0,
            seq=2,
            item_group=10,
            reward_item={
                [0]=_itemlist.i_25853_1_1,
                [1]=_itemlist.i_27830_30_1,
                [2]=_itemlist.i_25517_2_1
            }
        },
        {
            section_start=57,
            section_end=0,
            seq=3,
            item_group=10,
            reward_item={
                [0]=_itemlist.i_25853_2_1,
                [1]=_itemlist.i_27830_40_1,
                [2]=_itemlist.i_25517_3_1
            }
        }
    },
    role={
        {
            role_id=78645735,
            name="夏侯馨柔"
        },
        {
            role_id=78646049,
            name="爱吃芒果"
        },
        {
            role_id=78646049,
            name="爱吃芒果",
            seq=1
        },
        {
            role_id=78646049,
            name="爱吃芒果",
            seq=2
        },
        {
            role_id=14681815,
            name="情深缘浅"
        },
        {
            role_id=14681815,
            name="情深缘浅",
            seq=1
        },
        {
            role_id=14681815,
            name="情深缘浅",
            seq=2
        },
        {
            role_id=14681510,
            name="玄戈"
        },
        {
            role_id=26214423,
            name="僵小鱼"
        },
        {
            role_id=25166667,
            name="诸葛清轩"
        },
        {
            role_id=25166667,
            name="诸葛清轩",
            seq=1
        },
        {
            role_id=25166667,
            name="诸葛清轩",
            seq=2
        },
        {
            role_id=23069112,
            name="心悦"
        },
        {
            role_id=27263822,
            name="朝朝亦孤独"
        },
        {
            role_id=38797507,
            name="皇甫瑶依"
        },
        {
            role_id=35651612,
            name="北唐洛尘"
        },
        {
            role_id=35651612,
            name="北唐洛尘",
            seq=1
        },
        {
            role_id=85984213,
            name="我最灬摇摆"
        },
        {
            role_id=85984213,
            name="我最灬摇摆",
            seq=1
        },
        {
            role_id=85984213,
            name="我最灬摇摆",
            seq=2
        },
        {
            role_id=85983397,
            name="拿杆破枪丶"
        },
        {
            role_id=85983397,
            name="拿杆破枪丶",
            seq=1
        },
        {
            role_id=80740988,
            name="沈七"
        },
        {
            role_id=80740988,
            name="沈七",
            seq=1
        },
        {
            role_id=80740988,
            name="沈七",
            seq=2
        },
        {
            role_id=79692931,
            name="你我倦如旅行"
        },
        {
            role_id=79692931,
            name="你我倦如旅行",
            seq=1
        },
        {
            role_id=79692931,
            name="你我倦如旅行",
            seq=2
        },
        {
            role_id=85984834,
            name="叶寒风"
        },
        {
            role_id=79694241,
            name="一杯冰美式"
        },
        {
            role_id=79694241,
            name="一杯冰美式",
            seq=1
        },
        {
            role_id=79691834,
            name="始于初心。"
        },
        {
            role_id=79691834,
            name="始于初心。",
            seq=1
        },
        {
            role_id=85983604,
            name="龍啸梵音"
        },
        {
            role_id=85983604,
            name="龍啸梵音",
            seq=1
        },
        {
            role_id=85983604,
            name="龍啸梵音",
            seq=2
        },
        {
            role_id=5242988,
            name="中华小当家",
            seq=2
        },
        {
            role_id=48234620,
            name="叶孤城"
        },
        {
            role_id=89130350,
            name="独孤暮白"
        },
        {
            role_id=88081679,
            name="今晚打老虎"
        },
        {
            role_id=88081679,
            name="今晚打老虎",
            seq=1
        },
        {
            role_id=88081679,
            name="今晚打老虎",
            seq=2
        },
        {
            role_id=90178307,
            name="椰果圣代"
        },
        {
            role_id=89130710,
            name="我要当狗托"
        },
        {
            role_id=89131374,
            name="江上雪"
        },
        {
            role_id=89131374,
            name="江上雪",
            seq=1
        },
        {
            role_id=89131374,
            name="江上雪",
            seq=2
        },
        {
            role_id=88081535,
            name="狂热"
        },
        {
            role_id=88081535,
            name="狂热",
            seq=1
        },
        {
            role_id=88081535,
            name="狂热",
            seq=2
        },
        {
            role_id=88081683,
            name="少师九歌",
            seq=1
        },
        {
            role_id=89129543,
            name="青阳官人"
        },
        {
            role_id=90179286,
            name="万物皆可绿",
            seq=1
        },
        {
            role_id=89130735,
            name="着逝者为铠"
        },
        {
            role_id=90179286,
            name="万物皆可绿",
            seq=2
        },
        {
            role_id=88082898,
            name="Candy྅"
        },
        {
            role_id=91227851,
            name="东宫翊旋"
        },
        {
            role_id=89130137,
            name="特步飞"
        },
        {
            role_id=88080499,
            name="叫我女王大人"
        },
        {
            role_id=89129869,
            name="戒丿情"
        },
        {
            role_id=90178736,
            name="左丘道人"
        },
        {
            role_id=88080499,
            name="叫我女王大人",
            seq=1
        },
        {
            role_id=90179892,
            name="清秋神"
        },
        {
            role_id=89130710,
            name="我要当狗托",
            seq=1
        },
        {
            role_id=90179892,
            name="清秋神",
            seq=1
        },
        {
            role_id=90179892,
            name="清秋神",
            seq=2
        },
        {
            role_id=88080992,
            name="年爱念汐"
        },
        {
            role_id=91226474,
            name="妹妹你别跑"
        },
        {
            role_id=91226474,
            name="妹妹你别跑",
            seq=1
        },
        {
            role_id=91226474,
            name="妹妹你别跑",
            seq=2
        },
        {
            role_id=88080957,
            name="久睡成瘾"
        },
        {
            role_id=88080957,
            name="久睡成瘾",
            seq=1
        },
        {
            role_id=88080957,
            name="久睡成瘾",
            seq=2
        },
        {
            role_id=98567097,
            name="阿布都啦啦啦"
        },
        {
            role_id=98567097,
            name="阿布都啦啦啦",
            seq=1
        },
        {
            role_id=98567443,
            name="轩辕清梦"
        },
        {
            role_id=98567443,
            name="轩辕清梦",
            seq=1
        },
        {
            role_id=98567443,
            name="轩辕清梦",
            seq=2
        },
        {
            role_id=98568775,
            name="折扇戏美人"
        },
        {
            role_id=98568775,
            name="折扇戏美人",
            seq=2
        },
        {
            role_id=98568775,
            name="折扇戏美人",
            seq=1
        },
        {
            role_id=98568848,
            name="狗拖是也"
        },
        {
            role_id=98568848,
            name="狗拖是也",
            seq=1
        },
        {
            role_id=98568848,
            name="狗拖是也",
            seq=2
        },
        {
            role_id=98566244,
            name="澡妹妹丶"
        },
        {
            role_id=98566244,
            name="澡妹妹丶",
            seq=1
        },
        {
            role_id=98567530,
            name="芒果小希"
        },
        {
            role_id=98566391,
            name="御龙恒之"
        },
        {
            role_id=98566244,
            name="澡妹妹丶",
            seq=2
        },
        {
            role_id=98567097,
            name="阿布都啦啦啦",
            seq=2
        },
        {
            role_id=98569551,
            name="弥牟昕若"
        },
        {
            role_id=98569551,
            name="弥牟昕若",
            seq=1
        },
        {
            role_id=98569551,
            name="弥牟昕若",
            seq=2
        },
        {
            role_id=98566801,
            name="大灰狼"
        },
        {
            role_id=98566801,
            name="大灰狼",
            seq=1
        },
        {
            role_id=98566801,
            name="大灰狼",
            seq=2
        },
        {
            role_id=98568683,
            name="小爺。"
        },
        {
            role_id=56623123,
            name="影杀"
        },
        {
            role_id=54526015,
            name="崆峒掌教大帝"
        },
        {
            role_id=54526015,
            name="崆峒掌教大帝",
            seq=1
        },
        {
            role_id=54526015,
            name="崆峒掌教大帝",
            seq=2
        },
        {
            role_id=54526208,
            name="万宇归初乡’"
        },
        {
            role_id=56623973,
            name="一枪穿云"
        },
        {
            role_id=56623155,
            name="岁月如歌"
        },
        {
            role_id=56623155,
            name="岁月如歌",
            seq=1
        },
        {
            role_id=56623155,
            name="岁月如歌",
            seq=2
        },
        {
            role_id=54526214,
            name="范范范♬"
        },
        {
            role_id=54526214,
            name="范范范♬",
            seq=1
        },
        {
            role_id=54526214,
            name="范范范♬",
            seq=2
        },
        {
            role_id=54525967,
            name="尛丠莵"
        },
        {
            role_id=54526806,
            name="惜缘"
        },
        {
            role_id=54526806,
            name="惜缘",
            seq=1
        },
        {
            role_id=54526806,
            name="惜缘",
            seq=2
        },
        {
            role_id=56623826,
            name="星云小陌"
        },
        {
            role_id=56623826,
            name="星云小陌",
            seq=1
        },
        {
            role_id=56623826,
            name="星云小陌",
            seq=2
        },
        {
            role_id=54527447,
            name="醉看风拂袖"
        },
        {
            role_id=56623123,
            name="影杀",
            seq=1
        },
        {
            role_id=54527556,
            name="十里红妆梦2"
        },
        {
            role_id=56623319,
            name="夹谷茹曼"
        },
        {
            role_id=56623554,
            name="小凶许"
        },
        {
            role_id=56623554,
            name="小凶许",
            seq=1
        },
        {
            role_id=56623554,
            name="小凶许",
            seq=2
        },
        {
            role_id=104858175,
            name="太香"
        },
        {
            role_id=101711889,
            name="呵呵姑娘"
        },
        {
            role_id=101712023,
            name="鲁疏疏"
        },
        {
            role_id=102760784,
            name="晴天"
        },
        {
            role_id=102760784,
            name="晴天",
            seq=1
        },
        {
            role_id=104859926,
            name="成阳元修"
        },
        {
            role_id=104859535,
            name="魔道老千"
        },
        {
            role_id=104859535,
            name="魔道老千",
            seq=1
        },
        {
            role_id=104859535,
            name="魔道老千",
            seq=2
        },
        {
            role_id=102760784,
            name="晴天",
            seq=2
        },
        {
            role_id=102762119,
            name="夜半轻轻舞"
        },
        {
            role_id=103809179,
            name="莫花钱"
        },
        {
            role_id=103809179,
            name="莫花钱",
            seq=1
        },
        {
            role_id=104858175,
            name="太香",
            seq=1
        },
        {
            role_id=104858175,
            name="太香",
            seq=2
        },
        {
            role_id=103809179,
            name="莫花钱",
            seq=2
        },
        {
            role_id=103810372,
            name="举世无双88"
        },
        {
            role_id=104857821,
            name="夜夙"
        },
        {
            role_id=104857821,
            name="夜夙",
            seq=1
        },
        {
            role_id=104857821,
            name="夜夙",
            seq=2
        },
        {
            role_id=102762569,
            name="柏侯子逸"
        },
        {
            role_id=102762569,
            name="柏侯子逸",
            seq=1
        },
        {
            role_id=102762569,
            name="柏侯子逸",
            seq=2
        },
        {
            role_id=101711889,
            name="呵呵姑娘",
            seq=1
        },
        {
            role_id=101711889,
            name="呵呵姑娘",
            seq=2
        },
        {
            role_id=101712623,
            name="一杆梅子酒"
        },
        {
            role_id=101712623,
            name="一杆梅子酒",
            seq=1
        },
        {
            role_id=101712544,
            name="那年花开"
        },
        {
            role_id=101713114,
            name="妞妞"
        },
        {
            role_id=101713114,
            name="妞妞",
            seq=1
        },
        {
            role_id=101713114,
            name="妞妞",
            seq=2
        },
        {
            role_id=103811082,
            name="-李淳风-"
        },
        {
            role_id=102762449,
            name="歆颖雅静"
        },
        {
            role_id=101712827,
            name="小哥"
        },
        {
            role_id=102761978,
            name="即墨如雪丶"
        },
        {
            role_id=102761978,
            name="即墨如雪丶",
            seq=1
        },
        {
            role_id=103809434,
            name="完美破防"
        },
        {
            role_id=102761978,
            name="即墨如雪丶",
            seq=2
        },
        {
            role_id=104859861,
            name="风信子"
        },
        {
            role_id=103811204,
            name="正经的茄子"
        },
        {
            role_id=103811204,
            name="正经的茄子",
            seq=1
        },
        {
            role_id=103811204,
            name="正经的茄子",
            seq=2
        },
        {
            role_id=104858481,
            name="轩辕惜玉"
        },
        {
            role_id=101713765,
            name="南郭惜月",
            seq=1
        },
        {
            role_id=101713765,
            name="南郭惜月",
            seq=2
        },
        {
            role_id=103809381,
            name="司徒美琳"
        },
        {
            role_id=103809581,
            name="冷月"
        },
        {
            role_id=101714081,
            name="天使的翅膀"
        },
        {
            role_id=104857937,
            name="陌。路"
        },
        {
            role_id=102761999,
            name="沙哇低卡"
        },
        {
            role_id=104858303,
            name="隔壁老王"
        },
        {
            role_id=104858303,
            name="隔壁老王",
            seq=1
        },
        {
            role_id=103810712,
            name="左～右"
        },
        {
            role_id=104858432,
            name="黑胡子"
        },
        {
            role_id=108004592,
            name="叶老二"
        },
        {
            role_id=108003460,
            name="紫"
        },
        {
            role_id=108004592,
            name="叶老二",
            seq=1
        },
        {
            role_id=108004540,
            name="诸葛紫文"
        },
        {
            role_id=108004540,
            name="诸葛紫文",
            seq=1
        },
        {
            role_id=108003460,
            name="紫",
            seq=1
        },
        {
            role_id=108004693,
            name="完美生活"
        },
        {
            role_id=108004592,
            name="叶老二",
            seq=2
        },
        {
            role_id=108003775,
            name="🐮轻歌行🐮🐮"
        },
        {
            role_id=108003776,
            name="豆浆"
        },
        {
            role_id=108003776,
            name="豆浆",
            seq=1
        },
        {
            role_id=108004926,
            name="古口清鸢"
        },
        {
            role_id=108004540,
            name="诸葛紫文",
            seq=2
        },
        {
            role_id=108004877,
            name="帅老头"
        },
        {
            role_id=108004223,
            name="寒枫丶"
        },
        {
            role_id=108003858,
            name="以后我买单"
        },
        {
            role_id=108004095,
            name="汝嫣奕风"
        },
        {
            role_id=108004095,
            name="汝嫣奕风",
            seq=1
        },
        {
            role_id=108003858,
            name="以后我买单",
            seq=1
        },
        {
            role_id=108004630,
            name="颠覆你的墨镜"
        },
        {
            role_id=108004322,
            name="少师云轩"
        },
        {
            role_id=108003858,
            name="以后我买单",
            seq=2
        },
        {
            role_id=108003969,
            name="小青蛙",
            seq=1
        },
        {
            role_id=108004861,
            name="仲孙司深"
        },
        {
            role_id=108004630,
            name="颠覆你的墨镜",
            seq=1
        },
        {
            role_id=108004221,
            name="子玉怀瑾"
        },
        {
            role_id=108004881,
            name="归海雪见"
        },
        {
            role_id=108003644,
            name="随风肆意飘",
            seq=1
        },
        {
            role_id=108003644,
            name="随风肆意飘",
            seq=2
        },
        {
            role_id=108003649,
            name="鐘绫"
        },
        {
            role_id=108003649,
            name="鐘绫",
            seq=1
        },
        {
            role_id=108003649,
            name="鐘绫",
            seq=2
        },
        {
            role_id=108003525,
            name="兮兮。"
        },
        {
            role_id=108005054,
            name="三疯"
        },
        {
            role_id=108003525,
            name="兮兮。",
            seq=1
        },
        {
            role_id=108004207,
            name="大刀"
        },
        {
            role_id=108004207,
            name="大刀",
            seq=1
        },
        {
            role_id=108004207,
            name="大刀",
            seq=2
        },
        {
            role_id=108004994,
            name="兜丷里"
        },
        {
            role_id=108005028,
            name="无与伦比",
            seq=2
        },
        {
            role_id=57671805,
            name="⒈ィ固イ人"
        },
        {
            role_id=58720284,
            name="阿大"
        },
        {
            role_id=58720284,
            name="阿大",
            seq=1
        },
        {
            role_id=58720284,
            name="阿大",
            seq=2
        },
        {
            role_id=57671805,
            name="⒈ィ固イ人",
            seq=1
        },
        {
            role_id=57671933,
            name="都是一群弟弟"
        },
        {
            role_id=57671933,
            name="都是一群弟弟",
            seq=2
        },
        {
            role_id=57671933,
            name="都是一群弟弟",
            seq=1
        },
        {
            role_id=57671770,
            name="ℳ๓₯㎕马"
        },
        {
            role_id=58720269,
            name="锁清秋",
            seq=2
        },
        {
            role_id=57671805,
            name="⒈ィ固イ人",
            seq=2
        },
        {
            role_id=57671743,
            name="丨灬犹大丶"
        },
        {
            role_id=57671743,
            name="丨灬犹大丶",
            seq=1
        },
        {
            role_id=58720560,
            name="浩星子言",
            seq=1
        },
        {
            role_id=58720698,
            name="容易",
            seq=2
        },
        {
            role_id=57672782,
            name="即墨修宇"
        },
        {
            role_id=57671694,
            name="絵飛ヾ的魚"
        },
        {
            role_id=58720648,
            name="南梵天"
        },
        {
            role_id=58720648,
            name="南梵天",
            seq=1
        },
        {
            role_id=58720854,
            name="天津人",
            seq=1
        },
        {
            role_id=58720601,
            name="浩哥哥"
        },
        {
            role_id=46138155,
            name="紫气东来"
        },
        {
            role_id=46138155,
            name="紫气东来",
            seq=1
        },
        {
            role_id=46138155,
            name="紫气东来",
            seq=2
        },
        {
            role_id=52429269,
            name="北丐"
        },
        {
            role_id=52429269,
            name="北丐",
            seq=1
        },
        {
            role_id=17826342,
            name="狂暴天郡"
        },
        {
            role_id=17826342,
            name="狂暴天郡",
            seq=1
        },
        {
            role_id=53479494,
            name="难帝"
        },
        {
            role_id=53479494,
            name="难帝",
            seq=1
        },
        {
            role_id=53479494,
            name="难帝",
            seq=2
        },
        {
            role_id=19923861,
            name="小手™冰凉"
        },
        {
            role_id=19923861,
            name="小手™冰凉",
            seq=1
        },
        {
            role_id=68157743,
            name="云深不知处"
        },
        {
            role_id=50335253,
            name="战天灬道一"
        },
        {
            role_id=50335253,
            name="战天灬道一",
            seq=1
        },
        {
            role_id=41945754,
            name="巴索罗米·熊"
        },
        {
            role_id=41945754,
            name="巴索罗米·熊",
            seq=1
        },
        {
            role_id=41945754,
            name="巴索罗米·熊",
            seq=2
        },
        {
            role_id=62914759,
            name="…三爺…"
        },
        {
            role_id=76547099,
            name="司鸿纯熙"
        },
        {
            role_id=76547099,
            name="司鸿纯熙",
            seq=1
        },
        {
            role_id=76547099,
            name="司鸿纯熙",
            seq=2
        },
        {
            role_id=72351843,
            name="跪下唱征服"
        },
        {
            role_id=72351843,
            name="跪下唱征服",
            seq=1
        },
        {
            role_id=41943344,
            name="某些人是真菜"
        },
        {
            role_id=41943344,
            name="某些人是真菜",
            seq=1
        },
        {
            role_id=36700997,
            name="等等我"
        },
        {
            role_id=39846891,
            name="唵嘛呢叭咪吽"
        },
        {
            role_id=39846891,
            name="唵嘛呢叭咪吽",
            seq=1
        },
        {
            role_id=30410284,
            name="宇文南瑾"
        },
        {
            role_id=52429224,
            name="G。M大气"
        },
        {
            role_id=52429224,
            name="G。M大气",
            seq=1
        },
        {
            role_id=52429224,
            name="G。M大气",
            seq=2
        },
        {
            role_id=30411132,
            name="公子世无双丶",
            seq=2
        },
        {
            role_id=2098200778,
            name="东厢彭泽"
        },
        {
            role_id=2098200778,
            name="东厢彭泽",
            seq=1
        },
        {
            role_id=2098200778,
            name="东厢彭泽",
            seq=2
        },
        {
            role_id=2098200977,
            name="丰将墨柒"
        },
        {
            role_id=2098200977,
            name="丰将墨柒",
            seq=1
        },
        {
            role_id=2098200977,
            name="丰将墨柒",
            seq=2
        },
        {
            role_id=2098200578,
            name="司城沐雪"
        },
        {
            role_id=2098200578,
            name="司城沐雪",
            seq=1
        },
        {
            role_id=2098200578,
            name="司城沐雪",
            seq=3
        },
        {},
        {
            seq=1
        },
        {
            seq=2
        },
        {
            seq=3
        },
        {
            role_id=2098200781,
            name="即墨雨馨"
        },
        {
            role_id=2098200781,
            name="即墨雨馨",
            seq=1
        },
        {
            role_id=2098200781,
            name="即墨雨馨",
            seq=2
        },
        {
            role_id=97546193,
            name="安阳初晴"
        },
        {
            role_id=97546193,
            name="安阳初晴",
            seq=1
        },
        {
            role_id=97546193,
            name="安阳初晴",
            seq=2
        },
        {
            role_id=97546193,
            name="安阳初晴",
            seq=3
        },
        {
            role_id=97546196,
            name="安陵南笙"
        },
        {
            role_id=97546296,
            name="安陵南笙",
            seq=1
        },
        {
            role_id=97546296,
            name="安陵南笙",
            seq=2
        },
        {
            role_id=97546296,
            name="安陵南笙",
            seq=3
        },
        {
            role_id=97546393,
            name="吾丘子墨"
        },
        {
            role_id=97546393,
            name="吾丘子墨",
            seq=1
        },
        {
            role_id=97546393,
            name="吾丘子墨",
            seq=2
        },
        {
            role_id=97546393,
            name="吾丘子墨",
            seq=3
        },
        {
            role_id=2098200586,
            name="长鱼书琳"
        },
        {
            role_id=2098200586,
            name="长鱼书琳",
            seq=1
        },
        {
            role_id=2098200586,
            name="长鱼书琳",
            seq=2
        },
        {
            role_id=2098200586,
            name="长鱼书琳",
            seq=3
        },
        {
            role_id=2098200678,
            name="都尉官人"
        },
        {
            role_id=2098200678,
            name="都尉官人",
            seq=1
        },
        {
            role_id=2098200678,
            name="都尉官人",
            seq=2
        },
        {
            role_id=2098200678,
            name="都尉官人",
            seq=3
        },
        {
            role_id=2098200677,
            name="西宫修宇"
        },
        {
            role_id=2098200677,
            name="西宫修宇",
            seq=1
        },
        {
            role_id=2098200677,
            name="西宫修宇",
            seq=2
        },
        {
            role_id=2098200677,
            name="西宫修宇",
            seq=3
        }
    },
    other={
        {
            reset_flag=1,
            no_compensation=2
        }
    }
}
SetConfigDefaultVal(Config.xianshileichongbufa_auto,_default_val,nil,nil,nil)