local _default_val={
    xiuwei_att={
        xiuwei_type=0,
        xiuwei_level=1,
        xiuwei_exp=6000,
        dam_add=0,
        xiaoguo_add=0,
        dedam_def=0,
        xiaoguo_def=0,
        hp_add=0,
        sp_id=0,
        open_level=90
    },
    xiuwei_dec={
        max_level=20
    }
}
Config.xiuwei_auto={
    other={
        {
            cost1=27870,
            cost1_exp=50,
            cost2=27871,
            cost2_exp=780,
            use_times1=200,
            use_times=20,
            need_feisheng=1,
            open_level=90
        }
    },
    xiuwei_att={
        {
            xiuwei_exp=3000,
            dam_add=10,
            xiaoguo_add=10,
            sp_id=3001
        },
        {
            xiuwei_level=2,
            dam_add=20,
            xiaoguo_add=20,
            sp_id=3002
        },
        {
            xiuwei_level=3,
            xiuwei_exp=9000,
            dam_add=30,
            xiaoguo_add=30,
            sp_id=3003,
            open_level=92
        },
        {
            xiuwei_level=4,
            xiuwei_exp=12000,
            dam_add=40,
            xiaoguo_add=40,
            sp_id=3004,
            open_level=94
        },
        {
            xiuwei_level=5,
            xiuwei_exp=15000,
            dam_add=50,
            xiaoguo_add=50,
            sp_id=3005,
            open_level=96
        },
        {
            xiuwei_level=6,
            xiuwei_exp=18000,
            dam_add=60,
            xiaoguo_add=60,
            sp_id=3006,
            open_level=98
        },
        {
            xiuwei_level=7,
            xiuwei_exp=21000,
            dam_add=70,
            xiaoguo_add=70,
            sp_id=3007,
            open_level=100
        },
        {
            xiuwei_level=8,
            xiuwei_exp=24000,
            dam_add=80,
            xiaoguo_add=80,
            sp_id=3008,
            open_level=102
        },
        {
            xiuwei_level=9,
            xiuwei_exp=27000,
            dam_add=90,
            xiaoguo_add=90,
            sp_id=3009,
            open_level=104
        },
        {
            xiuwei_level=10,
            xiuwei_exp=30000,
            dam_add=100,
            xiaoguo_add=100,
            sp_id=3010,
            open_level=106
        },
        {
            xiuwei_level=11,
            xiuwei_exp=33000,
            dam_add=110,
            xiaoguo_add=110,
            sp_id=3011,
            open_level=108
        },
        {
            xiuwei_level=12,
            xiuwei_exp=36000,
            dam_add=120,
            xiaoguo_add=120,
            sp_id=3012,
            open_level=110
        },
        {
            xiuwei_level=13,
            xiuwei_exp=39000,
            dam_add=130,
            xiaoguo_add=130,
            sp_id=3013,
            open_level=112
        },
        {
            xiuwei_level=14,
            xiuwei_exp=42000,
            dam_add=140,
            xiaoguo_add=140,
            sp_id=3014,
            open_level=114
        },
        {
            xiuwei_level=15,
            xiuwei_exp=45000,
            dam_add=150,
            xiaoguo_add=150,
            sp_id=3015,
            open_level=115
        },
        {
            xiuwei_level=16,
            xiuwei_exp=48000,
            dam_add=160,
            xiaoguo_add=160,
            sp_id=3016,
            open_level=116
        },
        {
            xiuwei_level=17,
            xiuwei_exp=51000,
            dam_add=170,
            xiaoguo_add=170,
            sp_id=3017,
            open_level=117
        },
        {
            xiuwei_level=18,
            xiuwei_exp=54000,
            dam_add=180,
            xiaoguo_add=180,
            sp_id=3018,
            open_level=118
        },
        {
            xiuwei_level=19,
            xiuwei_exp=57000,
            dam_add=190,
            xiaoguo_add=190,
            sp_id=3019,
            open_level=119
        },
        {
            xiuwei_level=20,
            xiuwei_exp=60000,
            dam_add=200,
            xiaoguo_add=200,
            sp_id=3020,
            open_level=120
        },
        {
            xiuwei_type=1,
            xiuwei_exp=2000,
            dedam_def=10,
            xiaoguo_def=10,
            hp_add=750
        },
        {
            xiuwei_type=1,
            xiuwei_level=2,
            xiuwei_exp=4000,
            dedam_def=20,
            xiaoguo_def=20,
            hp_add=1500
        },
        {
            xiuwei_type=1,
            xiuwei_level=3,
            dedam_def=30,
            xiaoguo_def=30,
            hp_add=2250,
            open_level=92
        },
        {
            xiuwei_type=1,
            xiuwei_level=4,
            xiuwei_exp=8000,
            dedam_def=40,
            xiaoguo_def=40,
            hp_add=3000,
            open_level=94
        },
        {
            xiuwei_type=1,
            xiuwei_level=5,
            xiuwei_exp=10000,
            dedam_def=50,
            xiaoguo_def=50,
            hp_add=3750,
            open_level=96
        },
        {
            xiuwei_type=1,
            xiuwei_level=6,
            xiuwei_exp=12000,
            dedam_def=60,
            xiaoguo_def=60,
            hp_add=4500,
            open_level=98
        },
        {
            xiuwei_type=1,
            xiuwei_level=7,
            xiuwei_exp=14000,
            dedam_def=70,
            xiaoguo_def=70,
            hp_add=5250,
            open_level=100
        },
        {
            xiuwei_type=1,
            xiuwei_level=8,
            xiuwei_exp=16000,
            dedam_def=80,
            xiaoguo_def=80,
            hp_add=6000,
            open_level=102
        },
        {
            xiuwei_type=1,
            xiuwei_level=9,
            xiuwei_exp=18000,
            dedam_def=90,
            xiaoguo_def=90,
            hp_add=6750,
            open_level=104
        },
        {
            xiuwei_type=1,
            xiuwei_level=10,
            xiuwei_exp=20000,
            dedam_def=100,
            xiaoguo_def=100,
            hp_add=7500,
            open_level=106
        },
        {
            xiuwei_type=1,
            xiuwei_level=11,
            xiuwei_exp=22000,
            dedam_def=110,
            xiaoguo_def=110,
            hp_add=8250,
            open_level=108
        },
        {
            xiuwei_type=1,
            xiuwei_level=12,
            xiuwei_exp=24000,
            dedam_def=120,
            xiaoguo_def=120,
            hp_add=9000,
            open_level=110
        },
        {
            xiuwei_type=1,
            xiuwei_level=13,
            xiuwei_exp=26000,
            dedam_def=130,
            xiaoguo_def=130,
            hp_add=9750,
            open_level=112
        },
        {
            xiuwei_type=1,
            xiuwei_level=14,
            xiuwei_exp=28000,
            dedam_def=140,
            xiaoguo_def=140,
            hp_add=10500,
            open_level=114
        },
        {
            xiuwei_type=1,
            xiuwei_level=15,
            xiuwei_exp=30000,
            dedam_def=150,
            xiaoguo_def=150,
            hp_add=11250,
            open_level=115
        },
        {
            xiuwei_type=1,
            xiuwei_level=16,
            xiuwei_exp=32000,
            dedam_def=160,
            xiaoguo_def=160,
            hp_add=12000,
            open_level=116
        },
        {
            xiuwei_type=1,
            xiuwei_level=17,
            xiuwei_exp=34000,
            dedam_def=170,
            xiaoguo_def=170,
            hp_add=12750,
            open_level=117
        },
        {
            xiuwei_type=1,
            xiuwei_level=18,
            xiuwei_exp=36000,
            dedam_def=180,
            xiaoguo_def=180,
            hp_add=13500,
            open_level=118
        },
        {
            xiuwei_type=1,
            xiuwei_level=19,
            xiuwei_exp=38000,
            dedam_def=190,
            xiaoguo_def=190,
            hp_add=14250,
            open_level=119
        },
        {
            xiuwei_type=1,
            xiuwei_level=20,
            xiuwei_exp=40000,
            dedam_def=200,
            xiaoguo_def=200,
            hp_add=15000,
            open_level=120
        },
        {
            xiuwei_type=2,
            xiuwei_exp=3000,
            dam_add=10,
            xiaoguo_add=10,
            sp_id=3041
        },
        {
            xiuwei_type=2,
            xiuwei_level=2,
            dam_add=20,
            xiaoguo_add=20,
            sp_id=3042
        },
        {
            xiuwei_type=2,
            xiuwei_level=3,
            xiuwei_exp=9000,
            dam_add=30,
            xiaoguo_add=30,
            sp_id=3043,
            open_level=92
        },
        {
            xiuwei_type=2,
            xiuwei_level=4,
            xiuwei_exp=12000,
            dam_add=40,
            xiaoguo_add=40,
            sp_id=3044,
            open_level=94
        },
        {
            xiuwei_type=2,
            xiuwei_level=5,
            xiuwei_exp=15000,
            dam_add=50,
            xiaoguo_add=50,
            sp_id=3045,
            open_level=96
        },
        {
            xiuwei_type=2,
            xiuwei_level=6,
            xiuwei_exp=18000,
            dam_add=60,
            xiaoguo_add=60,
            sp_id=3046,
            open_level=98
        },
        {
            xiuwei_type=2,
            xiuwei_level=7,
            xiuwei_exp=21000,
            dam_add=70,
            xiaoguo_add=70,
            sp_id=3047,
            open_level=100
        },
        {
            xiuwei_type=2,
            xiuwei_level=8,
            xiuwei_exp=24000,
            dam_add=80,
            xiaoguo_add=80,
            sp_id=3048,
            open_level=102
        },
        {
            xiuwei_type=2,
            xiuwei_level=9,
            xiuwei_exp=27000,
            dam_add=90,
            xiaoguo_add=90,
            sp_id=3049,
            open_level=104
        },
        {
            xiuwei_type=2,
            xiuwei_level=10,
            xiuwei_exp=30000,
            dam_add=100,
            xiaoguo_add=100,
            sp_id=3050,
            open_level=106
        },
        {
            xiuwei_type=2,
            xiuwei_level=11,
            xiuwei_exp=33000,
            dam_add=110,
            xiaoguo_add=110,
            sp_id=3051,
            open_level=108
        },
        {
            xiuwei_type=2,
            xiuwei_level=12,
            xiuwei_exp=36000,
            dam_add=120,
            xiaoguo_add=120,
            sp_id=3052,
            open_level=110
        },
        {
            xiuwei_type=2,
            xiuwei_level=13,
            xiuwei_exp=39000,
            dam_add=130,
            xiaoguo_add=130,
            sp_id=3053,
            open_level=112
        },
        {
            xiuwei_type=2,
            xiuwei_level=14,
            xiuwei_exp=42000,
            dam_add=140,
            xiaoguo_add=140,
            sp_id=3054,
            open_level=114
        },
        {
            xiuwei_type=2,
            xiuwei_level=15,
            xiuwei_exp=45000,
            dam_add=150,
            xiaoguo_add=150,
            sp_id=3055,
            open_level=115
        },
        {
            xiuwei_type=2,
            xiuwei_level=16,
            xiuwei_exp=48000,
            dam_add=160,
            xiaoguo_add=160,
            sp_id=3056,
            open_level=116
        },
        {
            xiuwei_type=2,
            xiuwei_level=17,
            xiuwei_exp=51000,
            dam_add=170,
            xiaoguo_add=170,
            sp_id=3057,
            open_level=117
        },
        {
            xiuwei_type=2,
            xiuwei_level=18,
            xiuwei_exp=54000,
            dam_add=180,
            xiaoguo_add=180,
            sp_id=3058,
            open_level=118
        },
        {
            xiuwei_type=2,
            xiuwei_level=19,
            xiuwei_exp=57000,
            dam_add=190,
            xiaoguo_add=190,
            sp_id=3059,
            open_level=119
        },
        {
            xiuwei_type=2,
            xiuwei_level=20,
            xiuwei_exp=60000,
            dam_add=200,
            xiaoguo_add=200,
            sp_id=3060,
            open_level=120
        },
        {
            xiuwei_type=3,
            xiuwei_exp=2000,
            dedam_def=10,
            xiaoguo_def=10,
            hp_add=750
        },
        {
            xiuwei_type=3,
            xiuwei_level=2,
            xiuwei_exp=4000,
            dedam_def=20,
            xiaoguo_def=20,
            hp_add=1500
        },
        {
            xiuwei_type=3,
            xiuwei_level=3,
            dedam_def=30,
            xiaoguo_def=30,
            hp_add=2250,
            open_level=92
        },
        {
            xiuwei_type=3,
            xiuwei_level=4,
            xiuwei_exp=8000,
            dedam_def=40,
            xiaoguo_def=40,
            hp_add=3000,
            open_level=94
        },
        {
            xiuwei_type=3,
            xiuwei_level=5,
            xiuwei_exp=10000,
            dedam_def=50,
            xiaoguo_def=50,
            hp_add=3750,
            open_level=96
        },
        {
            xiuwei_type=3,
            xiuwei_level=6,
            xiuwei_exp=12000,
            dedam_def=60,
            xiaoguo_def=60,
            hp_add=4500,
            open_level=98
        },
        {
            xiuwei_type=3,
            xiuwei_level=7,
            xiuwei_exp=14000,
            dedam_def=70,
            xiaoguo_def=70,
            hp_add=5250,
            open_level=100
        },
        {
            xiuwei_type=3,
            xiuwei_level=8,
            xiuwei_exp=16000,
            dedam_def=80,
            xiaoguo_def=80,
            hp_add=6000,
            open_level=102
        },
        {
            xiuwei_type=3,
            xiuwei_level=9,
            xiuwei_exp=18000,
            dedam_def=90,
            xiaoguo_def=90,
            hp_add=6750,
            open_level=104
        },
        {
            xiuwei_type=3,
            xiuwei_level=10,
            xiuwei_exp=20000,
            dedam_def=100,
            xiaoguo_def=100,
            hp_add=7500,
            open_level=106
        },
        {
            xiuwei_type=3,
            xiuwei_level=11,
            xiuwei_exp=22000,
            dedam_def=110,
            xiaoguo_def=110,
            hp_add=8250,
            open_level=108
        },
        {
            xiuwei_type=3,
            xiuwei_level=12,
            xiuwei_exp=24000,
            dedam_def=120,
            xiaoguo_def=120,
            hp_add=9000,
            open_level=110
        },
        {
            xiuwei_type=3,
            xiuwei_level=13,
            xiuwei_exp=26000,
            dedam_def=130,
            xiaoguo_def=130,
            hp_add=9750,
            open_level=112
        },
        {
            xiuwei_type=3,
            xiuwei_level=14,
            xiuwei_exp=28000,
            dedam_def=140,
            xiaoguo_def=140,
            hp_add=10500,
            open_level=114
        },
        {
            xiuwei_type=3,
            xiuwei_level=15,
            xiuwei_exp=30000,
            dedam_def=150,
            xiaoguo_def=150,
            hp_add=11250,
            open_level=115
        },
        {
            xiuwei_type=3,
            xiuwei_level=16,
            xiuwei_exp=32000,
            dedam_def=160,
            xiaoguo_def=160,
            hp_add=12000,
            open_level=116
        },
        {
            xiuwei_type=3,
            xiuwei_level=17,
            xiuwei_exp=34000,
            dedam_def=170,
            xiaoguo_def=170,
            hp_add=12750,
            open_level=117
        },
        {
            xiuwei_type=3,
            xiuwei_level=18,
            xiuwei_exp=36000,
            dedam_def=180,
            xiaoguo_def=180,
            hp_add=13500,
            open_level=118
        },
        {
            xiuwei_type=3,
            xiuwei_level=19,
            xiuwei_exp=38000,
            dedam_def=190,
            xiaoguo_def=190,
            hp_add=14250,
            open_level=119
        },
        {
            xiuwei_type=3,
            xiuwei_level=20,
            xiuwei_exp=40000,
            dedam_def=200,
            xiaoguo_def=200,
            hp_add=15000,
            open_level=120
        },
        {
            xiuwei_type=4,
            xiuwei_exp=3000,
            dam_add=10,
            xiaoguo_add=10,
            sp_id=3021
        },
        {
            xiuwei_type=4,
            xiuwei_level=2,
            dam_add=20,
            xiaoguo_add=20,
            sp_id=3022
        },
        {
            xiuwei_type=4,
            xiuwei_level=3,
            xiuwei_exp=9000,
            dam_add=30,
            xiaoguo_add=30,
            sp_id=3023,
            open_level=92
        },
        {
            xiuwei_type=4,
            xiuwei_level=4,
            xiuwei_exp=12000,
            dam_add=40,
            xiaoguo_add=40,
            sp_id=3024,
            open_level=94
        },
        {
            xiuwei_type=4,
            xiuwei_level=5,
            xiuwei_exp=15000,
            dam_add=50,
            xiaoguo_add=50,
            sp_id=3025,
            open_level=96
        },
        {
            xiuwei_type=4,
            xiuwei_level=6,
            xiuwei_exp=18000,
            dam_add=60,
            xiaoguo_add=60,
            sp_id=3026,
            open_level=98
        },
        {
            xiuwei_type=4,
            xiuwei_level=7,
            xiuwei_exp=21000,
            dam_add=70,
            xiaoguo_add=70,
            sp_id=3027,
            open_level=100
        },
        {
            xiuwei_type=4,
            xiuwei_level=8,
            xiuwei_exp=24000,
            dam_add=80,
            xiaoguo_add=80,
            sp_id=3028,
            open_level=102
        },
        {
            xiuwei_type=4,
            xiuwei_level=9,
            xiuwei_exp=27000,
            dam_add=90,
            xiaoguo_add=90,
            sp_id=3029,
            open_level=104
        },
        {
            xiuwei_type=4,
            xiuwei_level=10,
            xiuwei_exp=30000,
            dam_add=100,
            xiaoguo_add=100,
            sp_id=3030,
            open_level=106
        },
        {
            xiuwei_type=4,
            xiuwei_level=11,
            xiuwei_exp=33000,
            dam_add=110,
            xiaoguo_add=110,
            sp_id=3031,
            open_level=108
        },
        {
            xiuwei_type=4,
            xiuwei_level=12,
            xiuwei_exp=36000,
            dam_add=120,
            xiaoguo_add=120,
            sp_id=3032,
            open_level=110
        },
        {
            xiuwei_type=4,
            xiuwei_level=13,
            xiuwei_exp=39000,
            dam_add=130,
            xiaoguo_add=130,
            sp_id=3033,
            open_level=112
        },
        {
            xiuwei_type=4,
            xiuwei_level=14,
            xiuwei_exp=42000,
            dam_add=140,
            xiaoguo_add=140,
            sp_id=3034,
            open_level=114
        },
        {
            xiuwei_type=4,
            xiuwei_level=15,
            xiuwei_exp=45000,
            dam_add=150,
            xiaoguo_add=150,
            sp_id=3035,
            open_level=115
        },
        {
            xiuwei_type=4,
            xiuwei_level=16,
            xiuwei_exp=48000,
            dam_add=160,
            xiaoguo_add=160,
            sp_id=3036,
            open_level=116
        },
        {
            xiuwei_type=4,
            xiuwei_level=17,
            xiuwei_exp=51000,
            dam_add=170,
            xiaoguo_add=170,
            sp_id=3037,
            open_level=117
        },
        {
            xiuwei_type=4,
            xiuwei_level=18,
            xiuwei_exp=54000,
            dam_add=180,
            xiaoguo_add=180,
            sp_id=3038,
            open_level=118
        },
        {
            xiuwei_type=4,
            xiuwei_level=19,
            xiuwei_exp=57000,
            dam_add=190,
            xiaoguo_add=190,
            sp_id=3039,
            open_level=119
        },
        {
            xiuwei_type=4,
            xiuwei_level=20,
            xiuwei_exp=60000,
            dam_add=200,
            xiaoguo_add=200,
            sp_id=3040,
            open_level=120
        },
        {
            xiuwei_type=5,
            xiuwei_exp=2000,
            dedam_def=10,
            xiaoguo_def=10,
            hp_add=750
        },
        {
            xiuwei_type=5,
            xiuwei_level=2,
            xiuwei_exp=4000,
            dedam_def=20,
            xiaoguo_def=20,
            hp_add=1500
        },
        {
            xiuwei_type=5,
            xiuwei_level=3,
            dedam_def=30,
            xiaoguo_def=30,
            hp_add=2250,
            open_level=92
        },
        {
            xiuwei_type=5,
            xiuwei_level=4,
            xiuwei_exp=8000,
            dedam_def=40,
            xiaoguo_def=40,
            hp_add=3000,
            open_level=94
        },
        {
            xiuwei_type=5,
            xiuwei_level=5,
            xiuwei_exp=10000,
            dedam_def=50,
            xiaoguo_def=50,
            hp_add=3750,
            open_level=96
        },
        {
            xiuwei_type=5,
            xiuwei_level=6,
            xiuwei_exp=12000,
            dedam_def=60,
            xiaoguo_def=60,
            hp_add=4500,
            open_level=98
        },
        {
            xiuwei_type=5,
            xiuwei_level=7,
            xiuwei_exp=14000,
            dedam_def=70,
            xiaoguo_def=70,
            hp_add=5250,
            open_level=100
        },
        {
            xiuwei_type=5,
            xiuwei_level=8,
            xiuwei_exp=16000,
            dedam_def=80,
            xiaoguo_def=80,
            hp_add=6000,
            open_level=102
        },
        {
            xiuwei_type=5,
            xiuwei_level=9,
            xiuwei_exp=18000,
            dedam_def=90,
            xiaoguo_def=90,
            hp_add=6750,
            open_level=104
        },
        {
            xiuwei_type=5,
            xiuwei_level=10,
            xiuwei_exp=20000,
            dedam_def=100,
            xiaoguo_def=100,
            hp_add=7500,
            open_level=106
        },
        {
            xiuwei_type=5,
            xiuwei_level=11,
            xiuwei_exp=22000,
            dedam_def=110,
            xiaoguo_def=110,
            hp_add=8250,
            open_level=108
        },
        {
            xiuwei_type=5,
            xiuwei_level=12,
            xiuwei_exp=24000,
            dedam_def=120,
            xiaoguo_def=120,
            hp_add=9000,
            open_level=110
        },
        {
            xiuwei_type=5,
            xiuwei_level=13,
            xiuwei_exp=26000,
            dedam_def=130,
            xiaoguo_def=130,
            hp_add=9750,
            open_level=112
        },
        {
            xiuwei_type=5,
            xiuwei_level=14,
            xiuwei_exp=28000,
            dedam_def=140,
            xiaoguo_def=140,
            hp_add=10500,
            open_level=114
        },
        {
            xiuwei_type=5,
            xiuwei_level=15,
            xiuwei_exp=30000,
            dedam_def=150,
            xiaoguo_def=150,
            hp_add=11250,
            open_level=115
        },
        {
            xiuwei_type=5,
            xiuwei_level=16,
            xiuwei_exp=32000,
            dedam_def=160,
            xiaoguo_def=160,
            hp_add=12000,
            open_level=116
        },
        {
            xiuwei_type=5,
            xiuwei_level=17,
            xiuwei_exp=34000,
            dedam_def=170,
            xiaoguo_def=170,
            hp_add=12750,
            open_level=117
        },
        {
            xiuwei_type=5,
            xiuwei_level=18,
            xiuwei_exp=36000,
            dedam_def=180,
            xiaoguo_def=180,
            hp_add=13500,
            open_level=118
        },
        {
            xiuwei_type=5,
            xiuwei_level=19,
            xiuwei_exp=38000,
            dedam_def=190,
            xiaoguo_def=190,
            hp_add=14250,
            open_level=119
        },
        {
            xiuwei_type=5,
            xiuwei_level=20,
            xiuwei_exp=40000,
            dedam_def=200,
            xiaoguo_def=200,
            hp_add=15000,
            open_level=120
        }
    },
    xiuwei_dec={
        {
            xiuwei_type=0,
            xiuwei_name="人物攻修",
            xiuwei_dec="提高角色伤害、效果命中、治疗效果",
            skill_icon="s12001"
        },
        {
            xiuwei_type=1,
            xiuwei_name="人物防修",
            xiuwei_dec="提高角色伤害减免、效果抵抗、生命值",
            skill_icon="s12002"
        },
        {
            xiuwei_type=2,
            xiuwei_name="宠物攻修",
            xiuwei_dec="提高宠物伤害、效果命中、治疗效果",
            skill_icon="s12003"
        },
        {
            xiuwei_type=3,
            xiuwei_name="宠物防修",
            xiuwei_dec="提高宠物伤害减免、效果抵抗、生命值",
            skill_icon="s12004"
        },
        {
            xiuwei_type=4,
            xiuwei_name="伙伴攻修",
            xiuwei_dec="提高伙伴伤害、效果命中、治疗效果",
            skill_icon="s12005"
        },
        {
            xiuwei_type=5,
            xiuwei_name="伙伴防修",
            xiuwei_dec="提高伙伴伤害减免、效果抵抗、生命值",
            skill_icon="s12006"
        }
    }
}
SetConfigDefaultVal(Config.xiuwei_auto,_default_val,nil,nil,nil)