local _default_val={
    scene={
        scene_id=136,
        npc_id=71057,
        x=358,
        y=164
    }
}
local _itemlist={
    i_26363_1_1={
        item_id=26363,
        num=1,
        is_bind=1
    },
    i_22007_20_1={
        item_id=22007,
        num=20,
        is_bind=1
    },
    i_24514_1_1={
        item_id=24514,
        num=1,
        is_bind=1
    }
}
Config.xunmenghudie_auto={
    scene={
        {
            y=128
        },
        {
            y=134
        },
        {
            x=352,
            y=100
        },
        {
            x=326,
            y=22
        },
        {
            x=344,
            y=8
        },
        {
            y=30
        },
        {
            x=360
        },
        {
            x=350,
            y=200
        },
        {
            x=258,
            y=140
        },
        {
            x=244
        },
        {
            x=206,
            y=64
        },
        {
            x=360,
            y=340
        },
        {
            x=194,
            y=314
        },
        {
            x=332,
            y=252
        },
        {
            x=332,
            y=62
        },
        {
            x=264,
            y=240
        },
        {
            x=298,
            y=258
        },
        {
            x=274,
            y=272
        },
        {
            x=212,
            y=246
        },
        {
            x=194,
            y=166
        },
        {
            x=162,
            y=172
        },
        {
            x=112,
            y=154
        },
        {
            x=82,
            y=204
        },
        {
            x=34,
            y=204
        },
        {
            x=106,
            y=300
        }
    },
    reward={
        {
            section_start=1,
            section_end=0,
            reward_item={
                [0]=_itemlist.i_26363_1_1,
                [1]=_itemlist.i_22007_20_1,
                [2]=_itemlist.i_24514_1_1
            }
        }
    },
    other={
        {
            frequency=3,
            desc="儿时，母亲会带着我走过溪流上的木\n桥，溪水里有鱼儿，它们在芦苇下嬉\n戏。我在一旁捉着蝴蝶，一起等着外\n出的父亲归来...",
            time=3
        }
    }
}
SetConfigDefaultVal(Config.xunmenghudie_auto,_default_val,nil,nil,nil)