local _default_val={
    task={
        section=6,
        seq1=0,
        describe="活跃度达到50",
        type=2,
        parameter=1,
        combat=30,
        open_panel=21001
    },
    reward={
        section_start=1,
        section_end=7,
        seq=0,
        combat=80
    }
}
local _itemlist={
    i_28770_1_1={
        item_id=28770,
        num=1,
        is_bind=1
    },
    i_26359_3_1={
        item_id=26359,
        num=3,
        is_bind=1
    },
    i_29120_1_1={
        item_id=29120,
        num=1,
        is_bind=1
    },
    i_25506_1_1={
        item_id=25506,
        num=1,
        is_bind=1
    },
    i_29121_1_1={
        item_id=29121,
        num=1,
        is_bind=1
    },
    i_28926_1_1={
        item_id=28926,
        num=1,
        is_bind=1
    },
    i_25657_1_1={
        item_id=25657,
        num=1,
        is_bind=1
    },
    i_27723_1_1={
        item_id=27723,
        num=1,
        is_bind=1
    }
}
Config.yuanqijishibu_auto={
    task={
        {
            seq=0,
            section=1,
            describe="完成播种1次",
            type=7,
            open_panel=139006
        },
        {
            seq=1,
            section=1,
            seq1=1,
            describe="完成元气竞速1次",
            type=8,
            open_panel=139012
        },
        {
            seq=2,
            section=1,
            seq1=2,
            parameter=50
        },
        {
            seq=3,
            section=1,
            seq1=3,
            describe="每日登录",
            type=1,
            open_panel=0
        },
        {
            seq=4,
            section=2,
            describe="完成播种1次",
            type=7,
            open_panel=139006
        },
        {
            seq=5,
            section=2,
            seq1=1,
            describe="完成元气竞速1次",
            type=8,
            open_panel=139012
        },
        {
            seq=6,
            section=2,
            seq1=2,
            parameter=50
        },
        {
            seq=7,
            section=2,
            seq1=3,
            describe="每日登录",
            type=1,
            open_panel=0
        },
        {
            seq=8,
            section=3,
            describe="完成播种1次",
            type=7,
            open_panel=139006
        },
        {
            seq=9,
            section=3,
            seq1=1,
            describe="完成元气竞速1次",
            type=8,
            open_panel=139012
        },
        {
            seq=10,
            section=3,
            seq1=2,
            parameter=50
        },
        {
            seq=11,
            section=3,
            seq1=3,
            describe="每日登录",
            type=1,
            open_panel=0
        },
        {
            seq=12,
            section=4,
            describe="完成妙笔生花1次",
            type=9,
            open_panel=139007
        },
        {
            seq=13,
            section=4,
            seq1=1,
            describe="完成寻梦蝴蝶1次",
            type=10,
            open_panel=139004
        },
        {
            seq=14,
            section=4,
            seq1=2,
            parameter=50
        },
        {
            seq=15,
            section=4,
            seq1=3,
            describe="每日登录",
            type=1,
            open_panel=0
        },
        {
            seq=16,
            section=5,
            describe="完成妙笔生花1次",
            type=9,
            open_panel=139007
        },
        {
            seq=17,
            section=5,
            seq1=1,
            describe="完成寻梦蝴蝶1次",
            type=10,
            open_panel=139004
        },
        {
            seq=18,
            section=5,
            seq1=2,
            parameter=50
        },
        {
            seq=19,
            section=5,
            seq1=3,
            describe="每日登录",
            type=1,
            open_panel=0
        },
        {
            seq=20,
            describe="完成妙笔生花1次",
            type=9,
            combat=80,
            open_panel=139007
        },
        {
            seq=21,
            seq1=1,
            describe="完成寻梦蝴蝶1次",
            type=10,
            combat=80,
            open_panel=139004
        },
        {
            seq=22,
            seq1=2,
            parameter=50,
            combat=80
        },
        {
            seq=23,
            seq1=3,
            describe="活跃度达到100",
            parameter=100,
            combat=80
        },
        {
            seq=24,
            seq1=4,
            describe="活跃度达到150",
            parameter=150,
            combat=80
        },
        {
            seq=25,
            seq1=5,
            describe="每日登录",
            type=1,
            combat=80,
            open_panel=0
        }
    },
    reward={
        {
            reward1_item=_itemlist.i_28770_1_1,
            reward2_item={
                [0]=_itemlist.i_26359_3_1,
                [1]=_itemlist.i_29120_1_1
            }
        },
        {
            seq=1,
            combat=160,
            reward1_item=_itemlist.i_28770_1_1,
            reward2_item={
                [0]=_itemlist.i_26359_3_1,
                [1]=_itemlist.i_25506_1_1
            }
        },
        {
            seq=2,
            combat=240,
            reward1_item=_itemlist.i_28770_1_1,
            reward2_item={
                [0]=_itemlist.i_26359_3_1,
                [1]=_itemlist.i_29121_1_1
            }
        },
        {
            seq=3,
            combat=320,
            reward1_item=_itemlist.i_28770_1_1,
            reward2_item={
                [0]=_itemlist.i_26359_3_1,
                [1]=_itemlist.i_25506_1_1
            }
        },
        {
            seq=4,
            combat=400,
            reward1_item=_itemlist.i_28770_1_1,
            reward2_item={
                [0]=_itemlist.i_26359_3_1,
                [1]=_itemlist.i_29120_1_1
            }
        },
        {
            seq=5,
            combat=480,
            reward1_item=_itemlist.i_28770_1_1,
            reward2_item={
                [0]=_itemlist.i_26359_3_1,
                [1]=_itemlist.i_28926_1_1
            }
        },
        {
            section_start=8,
            section_end=21,
            reward1_item=_itemlist.i_28770_1_1,
            reward2_item={
                [0]=_itemlist.i_26359_3_1,
                [1]=_itemlist.i_29120_1_1
            }
        },
        {
            section_start=8,
            section_end=21,
            seq=1,
            combat=160,
            reward1_item=_itemlist.i_28770_1_1,
            reward2_item={
                [0]=_itemlist.i_26359_3_1,
                [1]=_itemlist.i_25657_1_1
            }
        },
        {
            section_start=8,
            section_end=21,
            seq=2,
            combat=240,
            reward1_item=_itemlist.i_28770_1_1,
            reward2_item={
                [0]=_itemlist.i_26359_3_1,
                [1]=_itemlist.i_29121_1_1
            }
        },
        {
            section_start=8,
            section_end=21,
            seq=3,
            combat=320,
            reward1_item=_itemlist.i_28770_1_1,
            reward2_item={
                [0]=_itemlist.i_26359_3_1,
                [1]=_itemlist.i_25657_1_1
            }
        },
        {
            section_start=8,
            section_end=21,
            seq=4,
            combat=400,
            reward1_item=_itemlist.i_28770_1_1,
            reward2_item={
                [0]=_itemlist.i_26359_3_1,
                [1]=_itemlist.i_29120_1_1
            }
        },
        {
            section_start=8,
            section_end=21,
            seq=5,
            combat=480,
            reward1_item=_itemlist.i_28770_1_1,
            reward2_item={
                [0]=_itemlist.i_26359_3_1,
                [1]=_itemlist.i_28926_1_1
            }
        },
        {
            section_start=22,
            section_end=0,
            reward1_item=_itemlist.i_28770_1_1,
            reward2_item={
                [0]=_itemlist.i_26359_3_1,
                [1]=_itemlist.i_29120_1_1
            }
        },
        {
            section_start=22,
            section_end=0,
            seq=1,
            combat=160,
            reward1_item=_itemlist.i_28770_1_1,
            reward2_item={
                [0]=_itemlist.i_26359_3_1,
                [1]=_itemlist.i_27723_1_1
            }
        },
        {
            section_start=22,
            section_end=0,
            seq=2,
            combat=240,
            reward1_item=_itemlist.i_28770_1_1,
            reward2_item={
                [0]=_itemlist.i_26359_3_1,
                [1]=_itemlist.i_29121_1_1
            }
        },
        {
            section_start=22,
            section_end=0,
            seq=3,
            combat=320,
            reward1_item=_itemlist.i_28770_1_1,
            reward2_item={
                [0]=_itemlist.i_26359_3_1,
                [1]=_itemlist.i_27723_1_1
            }
        },
        {
            section_start=22,
            section_end=0,
            seq=4,
            combat=400,
            reward1_item=_itemlist.i_28770_1_1,
            reward2_item={
                [0]=_itemlist.i_26359_3_1,
                [1]=_itemlist.i_29120_1_1
            }
        },
        {
            section_start=22,
            section_end=0,
            seq=5,
            combat=480,
            reward1_item=_itemlist.i_28770_1_1,
            reward2_item={
                [0]=_itemlist.i_26359_3_1,
                [1]=_itemlist.i_28926_1_1
            }
        }
    },
    other={
        {
            price=980,
            cfg_ver=2
        }
    }
}
SetConfigDefaultVal(Config.yuanqijishibu_auto,_default_val,nil,nil,nil)