local _default_val={
    scene={
        layer=1,
        area=0,
        name="天宫2层",
        area_type=2,
        can_goto_platform_id="3|0",
        is_battle=1,
        pos_x=860,
        pos_y=47
    },
    ranking_reward={
        rank_type=1,
        min_rank_pos=1,
        max_rank_pos=1
    },
    boss_reward={
        boss_type=0,
        min_rank_pos=1,
        max_rank_pos=1,
        reward_score=150
    },
    battle_reward={
        power=1,
        score=0
    },
    boss_to_configure={
        button_name="出手次数排行",
        desc="出手次数排行"
    },
    achievement={
        ach_group=1,
        ach_level=0,
        achieve_type=0,
        ach_param1=5
    }
}
local _itemlist={
    i_33003_1_1={
        item_id=33003,
        num=1,
        is_bind=1
    },
    i_24557_3_1={
        item_id=24557,
        num=3,
        is_bind=1
    },
    i_65907_30000_1={
        item_id=65907,
        num=30000,
        is_bind=1
    },
    i_33002_1_1={
        item_id=33002,
        num=1,
        is_bind=1
    },
    i_24557_2_1={
        item_id=24557,
        num=2,
        is_bind=1
    },
    i_65907_25000_1={
        item_id=65907,
        num=25000,
        is_bind=1
    },
    i_24557_1_1={
        item_id=24557,
        num=1,
        is_bind=1
    },
    i_33001_1_1={
        item_id=33001,
        num=1,
        is_bind=1
    },
    i_65907_20000_1={
        item_id=65907,
        num=20000,
        is_bind=1
    },
    i_33000_1_1={
        item_id=33000,
        num=1,
        is_bind=1
    },
    i_65907_15000_1={
        item_id=65907,
        num=15000,
        is_bind=1
    },
    i_33004_3_1={
        item_id=33004,
        num=3,
        is_bind=1
    },
    i_24557_6_1={
        item_id=24557,
        num=6,
        is_bind=1
    },
    i_65907_50000_1={
        item_id=65907,
        num=50000,
        is_bind=1
    },
    i_33004_2_1={
        item_id=33004,
        num=2,
        is_bind=1
    },
    i_24557_5_1={
        item_id=24557,
        num=5,
        is_bind=1
    },
    i_65907_45000_1={
        item_id=65907,
        num=45000,
        is_bind=1
    },
    i_33004_1_1={
        item_id=33004,
        num=1,
        is_bind=1
    },
    i_65907_40000_1={
        item_id=65907,
        num=40000,
        is_bind=1
    },
    i_24557_4_1={
        item_id=24557,
        num=4,
        is_bind=1
    },
    i_65907_35000_1={
        item_id=65907,
        num=35000,
        is_bind=1
    },
    i_65907_1000_1={
        item_id=65907,
        num=1000,
        is_bind=1
    },
    i_65907_3000_1={
        item_id=65907,
        num=3000,
        is_bind=1
    },
    i_65907_5000_1={
        item_id=65907,
        num=5000,
        is_bind=1
    },
    i_65907_6000_1={
        item_id=65907,
        num=6000,
        is_bind=1
    },
    i_65907_7000_1={
        item_id=65907,
        num=7000,
        is_bind=1
    },
    i_65907_2000_1={
        item_id=65907,
        num=2000,
        is_bind=1
    },
    i_65907_4000_1={
        item_id=65907,
        num=4000,
        is_bind=1
    },
    i_28828_1_1={
        item_id=28828,
        num=1,
        is_bind=1
    },
    i_31257_3_1={
        item_id=31257,
        num=3,
        is_bind=1
    }
}
Config.yunding_heavenly_palace_auto={
    scene={
        {
            platform_id=0,
            layer=0,
            name="天宫1层",
            area_type=1,
            can_goto_platform_id="1|2",
            is_battle=0,
            pos_x=39,
            pos_y=145
        },
        {
            platform_id=1,
            pos_x=240,
            pos_y=214
        },
        {
            platform_id=2,
            area=1,
            pos_x=244,
            pos_y=67
        },
        {
            platform_id=3,
            layer=2,
            name="天宫3层",
            can_goto_platform_id="1|2|4|5",
            pos_x=373,
            pos_y=143
        },
        {
            platform_id=4,
            layer=3,
            name="天宫4层",
            can_goto_platform_id="3|6",
            pos_x=534,
            pos_y=240
        },
        {
            platform_id=5,
            layer=3,
            area=1,
            name="天宫4层",
            can_goto_platform_id="3|6",
            pos_x=532
        },
        {
            platform_id=6,
            layer=4,
            name="天宫5层",
            can_goto_platform_id="4|5|7|8",
            pos_x=700,
            pos_y=139
        },
        {
            platform_id=7,
            layer=5,
            name="天宫6层",
            can_goto_platform_id="6|9",
            pos_y=239
        },
        {
            platform_id=8,
            layer=5,
            area=1,
            name="天宫6层",
            can_goto_platform_id="6|9"
        },
        {
            platform_id=9,
            layer=6,
            name="云顶天宫",
            area_type=3,
            can_goto_platform_id="7|8",
            pos_x=1068,
            pos_y=149
        }
    },
    ranking_reward={
        {
            reward_seq=0,
            rank_type=0,
            ranking_reward_show={
                [0]=_itemlist.i_33003_1_1,
                [1]=_itemlist.i_24557_3_1,
                [2]=_itemlist.i_65907_30000_1
            }
        },
        {
            reward_seq=1,
            rank_type=0,
            min_rank_pos=2,
            max_rank_pos=2,
            ranking_reward_show={
                [0]=_itemlist.i_33002_1_1,
                [1]=_itemlist.i_24557_2_1,
                [2]=_itemlist.i_65907_25000_1
            }
        },
        {
            reward_seq=2,
            rank_type=0,
            min_rank_pos=3,
            max_rank_pos=3,
            ranking_reward_show={
                [0]=_itemlist.i_24557_1_1,
                [1]=_itemlist.i_33001_1_1,
                [2]=_itemlist.i_65907_20000_1
            }
        },
        {
            reward_seq=3,
            rank_type=0,
            min_rank_pos=4,
            max_rank_pos=10,
            ranking_reward_show={
                [0]=_itemlist.i_24557_1_1,
                [1]=_itemlist.i_33000_1_1,
                [2]=_itemlist.i_65907_15000_1
            }
        },
        {
            reward_seq=9,
            ranking_reward_show={
                [0]=_itemlist.i_33004_3_1,
                [1]=_itemlist.i_24557_6_1,
                [2]=_itemlist.i_65907_50000_1
            }
        },
        {
            reward_seq=10,
            min_rank_pos=2,
            max_rank_pos=2,
            ranking_reward_show={
                [0]=_itemlist.i_33004_2_1,
                [1]=_itemlist.i_24557_5_1,
                [2]=_itemlist.i_65907_45000_1
            }
        },
        {
            reward_seq=11,
            min_rank_pos=3,
            max_rank_pos=3,
            ranking_reward_show={
                [0]=_itemlist.i_33004_1_1,
                [1]=_itemlist.i_24557_5_1,
                [2]=_itemlist.i_65907_40000_1
            }
        },
        {
            reward_seq=12,
            min_rank_pos=4,
            max_rank_pos=10,
            ranking_reward_show={
                [0]=_itemlist.i_33003_1_1,
                [1]=_itemlist.i_24557_4_1,
                [2]=_itemlist.i_65907_35000_1
            }
        },
        {
            reward_seq=13,
            min_rank_pos=11,
            max_rank_pos=20,
            ranking_reward_show={
                [0]=_itemlist.i_33002_1_1,
                [1]=_itemlist.i_24557_3_1,
                [2]=_itemlist.i_65907_30000_1
            }
        },
        {
            reward_seq=14,
            min_rank_pos=21,
            max_rank_pos=50,
            ranking_reward_show={
                [0]=_itemlist.i_33002_1_1,
                [1]=_itemlist.i_24557_3_1,
                [2]=_itemlist.i_65907_30000_1
            }
        },
        {
            reward_seq=15,
            min_rank_pos=51,
            max_rank_pos=100,
            ranking_reward_show={
                [0]=_itemlist.i_24557_2_1,
                [1]=_itemlist.i_33001_1_1,
                [2]=_itemlist.i_65907_25000_1
            }
        },
        {
            reward_seq=16,
            min_rank_pos=101,
            max_rank_pos=200,
            ranking_reward_show={
                [0]=_itemlist.i_24557_1_1,
                [1]=_itemlist.i_33000_1_1,
                [2]=_itemlist.i_65907_20000_1
            }
        }
    },
    boss_reward={
        {
            reward_seq=0,
            reward_score=500
        },
        {
            reward_seq=1,
            min_rank_pos=2,
            max_rank_pos=2,
            reward_score=350
        },
        {
            reward_seq=2,
            min_rank_pos=3,
            max_rank_pos=3,
            reward_score=250
        },
        {
            reward_seq=3,
            min_rank_pos=4,
            max_rank_pos=10
        },
        {
            reward_seq=4,
            min_rank_pos=11,
            max_rank_pos=20
        },
        {
            reward_seq=5,
            min_rank_pos=21,
            max_rank_pos=50
        },
        {
            reward_seq=6,
            min_rank_pos=51,
            max_rank_pos=100
        },
        {
            reward_seq=7,
            min_rank_pos=101,
            max_rank_pos=200
        },
        {
            reward_seq=8,
            min_rank_pos=201,
            max_rank_pos=1000
        },
        {
            reward_seq=9,
            boss_type=1,
            reward_score=500
        },
        {
            reward_seq=10,
            boss_type=1,
            min_rank_pos=2,
            max_rank_pos=2,
            reward_score=350
        },
        {
            reward_seq=11,
            boss_type=1,
            min_rank_pos=3,
            max_rank_pos=3,
            reward_score=250
        },
        {
            reward_seq=12,
            boss_type=1,
            min_rank_pos=4,
            max_rank_pos=10
        },
        {
            reward_seq=13,
            boss_type=1,
            min_rank_pos=11,
            max_rank_pos=20
        },
        {
            reward_seq=14,
            boss_type=1,
            min_rank_pos=21,
            max_rank_pos=50
        },
        {
            reward_seq=15,
            boss_type=1,
            min_rank_pos=51,
            max_rank_pos=100
        },
        {
            reward_seq=16,
            boss_type=1,
            min_rank_pos=101,
            max_rank_pos=200
        },
        {
            reward_seq=17,
            boss_type=1,
            min_rank_pos=201,
            max_rank_pos=1000
        },
        {
            reward_seq=18,
            boss_type=2,
            reward_score=500
        },
        {
            reward_seq=19,
            boss_type=2,
            min_rank_pos=2,
            max_rank_pos=2,
            reward_score=350
        },
        {
            reward_seq=20,
            boss_type=2,
            min_rank_pos=3,
            max_rank_pos=3,
            reward_score=250
        },
        {
            reward_seq=21,
            boss_type=2,
            min_rank_pos=4,
            max_rank_pos=10
        },
        {
            reward_seq=22,
            boss_type=2,
            min_rank_pos=11,
            max_rank_pos=20
        },
        {
            reward_seq=23,
            boss_type=2,
            min_rank_pos=21,
            max_rank_pos=50
        },
        {
            reward_seq=24,
            boss_type=2,
            min_rank_pos=51,
            max_rank_pos=100
        },
        {
            reward_seq=25,
            boss_type=2,
            min_rank_pos=101,
            max_rank_pos=200
        },
        {
            reward_seq=26,
            boss_type=2,
            min_rank_pos=201,
            max_rank_pos=1000
        },
        {
            reward_seq=27,
            boss_type=3,
            reward_score=500
        },
        {
            reward_seq=28,
            boss_type=3,
            min_rank_pos=2,
            max_rank_pos=2,
            reward_score=350
        },
        {
            reward_seq=29,
            boss_type=3,
            min_rank_pos=3,
            max_rank_pos=3,
            reward_score=250
        },
        {
            reward_seq=30,
            boss_type=3,
            min_rank_pos=4,
            max_rank_pos=10
        },
        {
            reward_seq=31,
            boss_type=3,
            min_rank_pos=11,
            max_rank_pos=20
        },
        {
            reward_seq=32,
            boss_type=3,
            min_rank_pos=21,
            max_rank_pos=50
        },
        {
            reward_seq=33,
            boss_type=3,
            min_rank_pos=51,
            max_rank_pos=100
        },
        {
            reward_seq=34,
            boss_type=3,
            min_rank_pos=101,
            max_rank_pos=200
        },
        {
            reward_seq=35,
            boss_type=3,
            min_rank_pos=201,
            max_rank_pos=1000
        }
    },
    battle_reward={
        {
            fail_power=0,
            score=20
        },
        {
            fail_power=1,
            power=4,
            score=5
        },
        {
            fail_power=2,
            score=10
        },
        {
            fail_power=3
        },
        {
            fail_power=4,
            power=4
        }
    },
    boss_to_configure={
        {
            boss_type=0,
            monster_group=2234,
            npc_id=74180,
            button_name="总伤害排行",
            desc="总伤害排行",
            boss_name="獓狠"
        },
        {
            boss_type=1,
            monster_group=2235,
            npc_id=74181,
            button_name="单次伤害排行",
            desc="单次伤害排行",
            boss_name="毕方"
        },
        {
            boss_type=2,
            monster_group=2236,
            npc_id=74182,
            boss_name="重明"
        },
        {
            boss_type=3,
            monster_group=2237,
            npc_id=74183,
            boss_name="孟极"
        }
    },
    achievement={
        {
            sn=1,
            ach_name="善战·壹",
            ach_dsc="云顶天宫累计获得100积分",
            ach_param1=100,
            achieve_reward={
                [0]=_itemlist.i_65907_1000_1
            }
        },
        {
            sn=2,
            ach_level=1,
            ach_name="善战·贰",
            ach_dsc="云顶天宫累计获得300积分",
            ach_param1=300,
            achieve_reward={
                [0]=_itemlist.i_65907_3000_1
            }
        },
        {
            sn=3,
            ach_level=2,
            ach_name="善战·叁",
            ach_dsc="云顶天宫累计获得600积分",
            ach_param1=600,
            achieve_reward={
                [0]=_itemlist.i_65907_5000_1
            }
        },
        {
            sn=4,
            ach_level=3,
            ach_name="善战·肆",
            ach_dsc="云顶天宫累计获得800积分",
            ach_param1=800,
            achieve_reward={
                [0]=_itemlist.i_65907_6000_1
            }
        },
        {
            sn=5,
            ach_level=4,
            ach_name="善战·伍",
            ach_dsc="云顶天宫累计获得1000积分",
            ach_param1=1000,
            achieve_reward={
                [0]=_itemlist.i_65907_7000_1
            }
        },
        {
            sn=6,
            ach_group=2,
            ach_name="战神·壹",
            ach_dsc="云顶天宫与玩家战斗胜利5次",
            achieve_type=1,
            achieve_reward={
                [0]=_itemlist.i_65907_1000_1
            }
        },
        {
            sn=7,
            ach_group=2,
            ach_level=1,
            ach_name="战神·贰",
            ach_dsc="云顶天宫与玩家战斗胜利10次",
            achieve_type=1,
            ach_param1=10,
            achieve_reward={
                [0]=_itemlist.i_65907_2000_1
            }
        },
        {
            sn=8,
            ach_group=2,
            ach_level=2,
            ach_name="战神·叁",
            ach_dsc="云顶天宫与玩家战斗胜利20次",
            achieve_type=1,
            ach_param1=20,
            achieve_reward={
                [0]=_itemlist.i_65907_3000_1
            }
        },
        {
            sn=9,
            ach_group=2,
            ach_level=3,
            ach_name="战神·肆",
            ach_dsc="云顶天宫与玩家战斗胜利30次",
            achieve_type=1,
            ach_param1=30,
            achieve_reward={
                [0]=_itemlist.i_65907_4000_1
            }
        },
        {
            sn=10,
            ach_group=2,
            ach_level=4,
            ach_name="战神·伍",
            ach_dsc="云顶天宫与玩家战斗胜利50次",
            achieve_type=1,
            ach_param1=50,
            achieve_reward={
                [0]=_itemlist.i_65907_6000_1
            }
        },
        {
            sn=11,
            ach_group=3,
            ach_name="骁勇·壹",
            ach_dsc="云顶天宫主动挑战玩家5次",
            achieve_type=2,
            achieve_reward={
                [0]=_itemlist.i_65907_2000_1
            }
        },
        {
            sn=12,
            ach_group=3,
            ach_level=1,
            ach_name="骁勇·贰",
            ach_dsc="云顶天宫主动挑战玩家10次",
            achieve_type=2,
            ach_param1=10,
            achieve_reward={
                [0]=_itemlist.i_65907_3000_1
            }
        },
        {
            sn=13,
            ach_group=3,
            ach_level=2,
            ach_name="骁勇·叁",
            ach_dsc="云顶天宫主动挑战玩家15次",
            achieve_type=2,
            ach_param1=15,
            achieve_reward={
                [0]=_itemlist.i_65907_4000_1
            }
        },
        {
            sn=14,
            ach_group=3,
            ach_level=3,
            ach_name="骁勇·肆",
            ach_dsc="云顶天宫主动挑战玩家25次",
            achieve_type=2,
            ach_param1=25,
            achieve_reward={
                [0]=_itemlist.i_65907_5000_1
            }
        },
        {
            sn=15,
            ach_group=3,
            ach_level=4,
            ach_name="骁勇·伍",
            ach_dsc="云顶天宫主动挑战玩家40次",
            achieve_type=2,
            ach_param1=40,
            achieve_reward={
                [0]=_itemlist.i_65907_6000_1
            }
        },
        {
            sn=16,
            ach_group=4,
            ach_name="征伐·壹",
            ach_dsc="云顶天宫挑战BOSS2次",
            achieve_type=3,
            ach_param1=2,
            achieve_reward={
                [0]=_itemlist.i_65907_1000_1
            }
        },
        {
            sn=17,
            ach_group=4,
            ach_level=1,
            ach_name="征伐·贰",
            ach_dsc="云顶天宫挑战BOSS5次",
            achieve_type=3,
            achieve_reward={
                [0]=_itemlist.i_65907_2000_1
            }
        },
        {
            sn=18,
            ach_group=4,
            ach_level=2,
            ach_name="征伐·叁",
            ach_dsc="云顶天宫挑战BOSS10次",
            achieve_type=3,
            ach_param1=10,
            achieve_reward={
                [0]=_itemlist.i_65907_3000_1
            }
        },
        {
            sn=19,
            ach_group=4,
            ach_level=3,
            ach_name="征伐·肆",
            ach_dsc="云顶天宫挑战BOSS15次",
            achieve_type=3,
            ach_param1=15,
            achieve_reward={
                [0]=_itemlist.i_65907_4000_1
            }
        },
        {
            sn=20,
            ach_group=4,
            ach_level=4,
            ach_name="征伐·伍",
            ach_dsc="云顶天宫挑战BOSS30次",
            achieve_type=3,
            ach_param1=30,
            achieve_reward={
                [0]=_itemlist.i_65907_6000_1
            }
        }
    },
    others={
        {
            challenge_times=5,
            max_challenge=5,
            challenge_expend=1,
            open_time=2130,
            end_time=2200,
            ready_time=300,
            over_time=30,
            start_power=10,
            battle_cd=5,
            transfer_cd=10,
            reward_show={
                [0]=_itemlist.i_33004_3_1,
                [1]=_itemlist.i_24557_3_1,
                [2]=_itemlist.i_65907_30000_1
            },
            scene_id=344,
            yunding_reward_show={
                [0]=_itemlist.i_28828_1_1,
                [1]=_itemlist.i_31257_3_1
            },
            boss_repel_cd=180,
            boss_platform_id=9,
            battle_boss_cd=15,
            challenge_buff=13554
        }
    }
}
SetConfigDefaultVal(Config.yunding_heavenly_palace_auto,_default_val,nil,nil,nil)