#include "battle_ai_def.hpp"

int STRATEGY_PRIORITY_ARRAY[BATTLE_STRATEGY_MAX] = {
	BATTLE_STRATEGY_HEAL,
	BATTLE_STRATEGY_PURIFY,
	BATTLE_STRATEGY_REALIVE,
	BATTLE_STRATEGY_CONTROL,
	BATTLE_STRATEGY_BURN_MANA,
	BATTLE_STRATEGY_FOCUS_FIRE,	
	BATTLE_STRATEGY_BREAK_DEFENCE,
	BATTLE_STRATEGY_DEFENSE,		// 防御 特殊逻辑，放最后
	BATTLE_STRATEGY_OTHER,
};
UNSTD_STATIC_CHECK(9 == BATTLE_STRATEGY_MAX);