// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: partner_battle_data.proto

#ifndef PROTOBUF_partner_5fbattle_5fdata_2eproto__INCLUDED
#define PROTOBUF_partner_5fbattle_5fdata_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "battle_character_data.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_partner_5fbattle_5fdata_2eproto();
void protobuf_AssignDesc_partner_5fbattle_5fdata_2eproto();
void protobuf_ShutdownFile_partner_5fbattle_5fdata_2eproto();

class PB_PartnerBattleData;

// ===================================================================

class PB_PartnerBattleData : public ::google::protobuf::Message {
 public:
  PB_PartnerBattleData();
  virtual ~PB_PartnerBattleData();

  PB_PartnerBattleData(const PB_PartnerBattleData& from);

  inline PB_PartnerBattleData& operator=(const PB_PartnerBattleData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PB_PartnerBattleData& default_instance();

  void Swap(PB_PartnerBattleData* other);

  // implements Message ----------------------------------------------

  PB_PartnerBattleData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PB_PartnerBattleData& from);
  void MergeFrom(const PB_PartnerBattleData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .PB_BattleCharacterData battle_data = 1;
  inline bool has_battle_data() const;
  inline void clear_battle_data();
  static const int kBattleDataFieldNumber = 1;
  inline const ::PB_BattleCharacterData& battle_data() const;
  inline ::PB_BattleCharacterData* mutable_battle_data();
  inline ::PB_BattleCharacterData* release_battle_data();
  inline void set_allocated_battle_data(::PB_BattleCharacterData* battle_data);

  // optional int32 skin_id = 2;
  inline bool has_skin_id() const;
  inline void clear_skin_id();
  static const int kSkinIdFieldNumber = 2;
  inline ::google::protobuf::int32 skin_id() const;
  inline void set_skin_id(::google::protobuf::int32 value);

  // optional int32 battle_row = 3;
  inline bool has_battle_row() const;
  inline void clear_battle_row();
  static const int kBattleRowFieldNumber = 3;
  inline ::google::protobuf::int32 battle_row() const;
  inline void set_battle_row(::google::protobuf::int32 value);

  // optional int32 battle_column = 4 [default = -1];
  inline bool has_battle_column() const;
  inline void clear_battle_column();
  static const int kBattleColumnFieldNumber = 4;
  inline ::google::protobuf::int32 battle_column() const;
  inline void set_battle_column(::google::protobuf::int32 value);

  // optional int32 other_sp_num = 5;
  inline bool has_other_sp_num() const;
  inline void clear_other_sp_num();
  static const int kOtherSpNumFieldNumber = 5;
  inline ::google::protobuf::int32 other_sp_num() const;
  inline void set_other_sp_num(::google::protobuf::int32 value);

  // repeated int32 other_sp_list = 6;
  inline int other_sp_list_size() const;
  inline void clear_other_sp_list();
  static const int kOtherSpListFieldNumber = 6;
  inline ::google::protobuf::int32 other_sp_list(int index) const;
  inline void set_other_sp_list(int index, ::google::protobuf::int32 value);
  inline void add_other_sp_list(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      other_sp_list() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_other_sp_list();

  // optional int32 str_lv = 7;
  inline bool has_str_lv() const;
  inline void clear_str_lv();
  static const int kStrLvFieldNumber = 7;
  inline ::google::protobuf::int32 str_lv() const;
  inline void set_str_lv(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PB_PartnerBattleData)
 private:
  inline void set_has_battle_data();
  inline void clear_has_battle_data();
  inline void set_has_skin_id();
  inline void clear_has_skin_id();
  inline void set_has_battle_row();
  inline void clear_has_battle_row();
  inline void set_has_battle_column();
  inline void clear_has_battle_column();
  inline void set_has_other_sp_num();
  inline void clear_has_other_sp_num();
  inline void set_has_str_lv();
  inline void clear_has_str_lv();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::PB_BattleCharacterData* battle_data_;
  ::google::protobuf::int32 skin_id_;
  ::google::protobuf::int32 battle_row_;
  ::google::protobuf::int32 battle_column_;
  ::google::protobuf::int32 other_sp_num_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > other_sp_list_;
  ::google::protobuf::int32 str_lv_;
  friend void  protobuf_AddDesc_partner_5fbattle_5fdata_2eproto();
  friend void protobuf_AssignDesc_partner_5fbattle_5fdata_2eproto();
  friend void protobuf_ShutdownFile_partner_5fbattle_5fdata_2eproto();

  void InitAsDefaultInstance();
  static PB_PartnerBattleData* default_instance_;
};
// ===================================================================


// ===================================================================

// PB_PartnerBattleData

// optional .PB_BattleCharacterData battle_data = 1;
inline bool PB_PartnerBattleData::has_battle_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PB_PartnerBattleData::set_has_battle_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PB_PartnerBattleData::clear_has_battle_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PB_PartnerBattleData::clear_battle_data() {
  if (battle_data_ != NULL) battle_data_->::PB_BattleCharacterData::Clear();
  clear_has_battle_data();
}
inline const ::PB_BattleCharacterData& PB_PartnerBattleData::battle_data() const {
  // @@protoc_insertion_point(field_get:PB_PartnerBattleData.battle_data)
  return battle_data_ != NULL ? *battle_data_ : *default_instance_->battle_data_;
}
inline ::PB_BattleCharacterData* PB_PartnerBattleData::mutable_battle_data() {
  set_has_battle_data();
  if (battle_data_ == NULL) battle_data_ = new ::PB_BattleCharacterData;
  // @@protoc_insertion_point(field_mutable:PB_PartnerBattleData.battle_data)
  return battle_data_;
}
inline ::PB_BattleCharacterData* PB_PartnerBattleData::release_battle_data() {
  clear_has_battle_data();
  ::PB_BattleCharacterData* temp = battle_data_;
  battle_data_ = NULL;
  return temp;
}
inline void PB_PartnerBattleData::set_allocated_battle_data(::PB_BattleCharacterData* battle_data) {
  delete battle_data_;
  battle_data_ = battle_data;
  if (battle_data) {
    set_has_battle_data();
  } else {
    clear_has_battle_data();
  }
  // @@protoc_insertion_point(field_set_allocated:PB_PartnerBattleData.battle_data)
}

// optional int32 skin_id = 2;
inline bool PB_PartnerBattleData::has_skin_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PB_PartnerBattleData::set_has_skin_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PB_PartnerBattleData::clear_has_skin_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PB_PartnerBattleData::clear_skin_id() {
  skin_id_ = 0;
  clear_has_skin_id();
}
inline ::google::protobuf::int32 PB_PartnerBattleData::skin_id() const {
  // @@protoc_insertion_point(field_get:PB_PartnerBattleData.skin_id)
  return skin_id_;
}
inline void PB_PartnerBattleData::set_skin_id(::google::protobuf::int32 value) {
  set_has_skin_id();
  skin_id_ = value;
  // @@protoc_insertion_point(field_set:PB_PartnerBattleData.skin_id)
}

// optional int32 battle_row = 3;
inline bool PB_PartnerBattleData::has_battle_row() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PB_PartnerBattleData::set_has_battle_row() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PB_PartnerBattleData::clear_has_battle_row() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PB_PartnerBattleData::clear_battle_row() {
  battle_row_ = 0;
  clear_has_battle_row();
}
inline ::google::protobuf::int32 PB_PartnerBattleData::battle_row() const {
  // @@protoc_insertion_point(field_get:PB_PartnerBattleData.battle_row)
  return battle_row_;
}
inline void PB_PartnerBattleData::set_battle_row(::google::protobuf::int32 value) {
  set_has_battle_row();
  battle_row_ = value;
  // @@protoc_insertion_point(field_set:PB_PartnerBattleData.battle_row)
}

// optional int32 battle_column = 4 [default = -1];
inline bool PB_PartnerBattleData::has_battle_column() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PB_PartnerBattleData::set_has_battle_column() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PB_PartnerBattleData::clear_has_battle_column() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PB_PartnerBattleData::clear_battle_column() {
  battle_column_ = -1;
  clear_has_battle_column();
}
inline ::google::protobuf::int32 PB_PartnerBattleData::battle_column() const {
  // @@protoc_insertion_point(field_get:PB_PartnerBattleData.battle_column)
  return battle_column_;
}
inline void PB_PartnerBattleData::set_battle_column(::google::protobuf::int32 value) {
  set_has_battle_column();
  battle_column_ = value;
  // @@protoc_insertion_point(field_set:PB_PartnerBattleData.battle_column)
}

// optional int32 other_sp_num = 5;
inline bool PB_PartnerBattleData::has_other_sp_num() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PB_PartnerBattleData::set_has_other_sp_num() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PB_PartnerBattleData::clear_has_other_sp_num() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PB_PartnerBattleData::clear_other_sp_num() {
  other_sp_num_ = 0;
  clear_has_other_sp_num();
}
inline ::google::protobuf::int32 PB_PartnerBattleData::other_sp_num() const {
  // @@protoc_insertion_point(field_get:PB_PartnerBattleData.other_sp_num)
  return other_sp_num_;
}
inline void PB_PartnerBattleData::set_other_sp_num(::google::protobuf::int32 value) {
  set_has_other_sp_num();
  other_sp_num_ = value;
  // @@protoc_insertion_point(field_set:PB_PartnerBattleData.other_sp_num)
}

// repeated int32 other_sp_list = 6;
inline int PB_PartnerBattleData::other_sp_list_size() const {
  return other_sp_list_.size();
}
inline void PB_PartnerBattleData::clear_other_sp_list() {
  other_sp_list_.Clear();
}
inline ::google::protobuf::int32 PB_PartnerBattleData::other_sp_list(int index) const {
  // @@protoc_insertion_point(field_get:PB_PartnerBattleData.other_sp_list)
  return other_sp_list_.Get(index);
}
inline void PB_PartnerBattleData::set_other_sp_list(int index, ::google::protobuf::int32 value) {
  other_sp_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:PB_PartnerBattleData.other_sp_list)
}
inline void PB_PartnerBattleData::add_other_sp_list(::google::protobuf::int32 value) {
  other_sp_list_.Add(value);
  // @@protoc_insertion_point(field_add:PB_PartnerBattleData.other_sp_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
PB_PartnerBattleData::other_sp_list() const {
  // @@protoc_insertion_point(field_list:PB_PartnerBattleData.other_sp_list)
  return other_sp_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
PB_PartnerBattleData::mutable_other_sp_list() {
  // @@protoc_insertion_point(field_mutable_list:PB_PartnerBattleData.other_sp_list)
  return &other_sp_list_;
}

// optional int32 str_lv = 7;
inline bool PB_PartnerBattleData::has_str_lv() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void PB_PartnerBattleData::set_has_str_lv() {
  _has_bits_[0] |= 0x00000040u;
}
inline void PB_PartnerBattleData::clear_has_str_lv() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void PB_PartnerBattleData::clear_str_lv() {
  str_lv_ = 0;
  clear_has_str_lv();
}
inline ::google::protobuf::int32 PB_PartnerBattleData::str_lv() const {
  // @@protoc_insertion_point(field_get:PB_PartnerBattleData.str_lv)
  return str_lv_;
}
inline void PB_PartnerBattleData::set_str_lv(::google::protobuf::int32 value) {
  set_has_str_lv();
  str_lv_ = value;
  // @@protoc_insertion_point(field_set:PB_PartnerBattleData.str_lv)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_partner_5fbattle_5fdata_2eproto__INCLUDED
