// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pet_battle_data.proto

#ifndef PROTOBUF_pet_5fbattle_5fdata_2eproto__INCLUDED
#define PROTOBUF_pet_5fbattle_5fdata_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "battle_character_data.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_pet_5fbattle_5fdata_2eproto();
void protobuf_AssignDesc_pet_5fbattle_5fdata_2eproto();
void protobuf_ShutdownFile_pet_5fbattle_5fdata_2eproto();

class PB_PetBattleData;

// ===================================================================

class PB_PetBattleData : public ::google::protobuf::Message {
 public:
  PB_PetBattleData();
  virtual ~PB_PetBattleData();

  PB_PetBattleData(const PB_PetBattleData& from);

  inline PB_PetBattleData& operator=(const PB_PetBattleData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PB_PetBattleData& default_instance();

  void Swap(PB_PetBattleData* other);

  // implements Message ----------------------------------------------

  PB_PetBattleData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PB_PetBattleData& from);
  void MergeFrom(const PB_PetBattleData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .PB_BattleCharacterData battle_data = 1;
  inline bool has_battle_data() const;
  inline void clear_battle_data();
  static const int kBattleDataFieldNumber = 1;
  inline const ::PB_BattleCharacterData& battle_data() const;
  inline ::PB_BattleCharacterData* mutable_battle_data();
  inline ::PB_BattleCharacterData* release_battle_data();
  inline void set_allocated_battle_data(::PB_BattleCharacterData* battle_data);

  // repeated int32 passive_list = 2;
  inline int passive_list_size() const;
  inline void clear_passive_list();
  static const int kPassiveListFieldNumber = 2;
  inline ::google::protobuf::int32 passive_list(int index) const;
  inline void set_passive_list(int index, ::google::protobuf::int32 value);
  inline void add_passive_list(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      passive_list() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_passive_list();

  // optional int32 auto_move_type = 3;
  inline bool has_auto_move_type() const;
  inline void clear_auto_move_type();
  static const int kAutoMoveTypeFieldNumber = 3;
  inline ::google::protobuf::int32 auto_move_type() const;
  inline void set_auto_move_type(::google::protobuf::int32 value);

  // optional int32 auto_skill_id = 4;
  inline bool has_auto_skill_id() const;
  inline void clear_auto_skill_id();
  static const int kAutoSkillIdFieldNumber = 4;
  inline ::google::protobuf::int32 auto_skill_id() const;
  inline void set_auto_skill_id(::google::protobuf::int32 value);

  // optional int32 auto_skill_level = 5;
  inline bool has_auto_skill_level() const;
  inline void clear_auto_skill_level();
  static const int kAutoSkillLevelFieldNumber = 5;
  inline ::google::protobuf::int32 auto_skill_level() const;
  inline void set_auto_skill_level(::google::protobuf::int32 value);

  // optional int32 exclusive_passive_skill_OBSOLETE = 6;
  inline bool has_exclusive_passive_skill_obsolete() const;
  inline void clear_exclusive_passive_skill_obsolete();
  static const int kExclusivePassiveSkillOBSOLETEFieldNumber = 6;
  inline ::google::protobuf::int32 exclusive_passive_skill_obsolete() const;
  inline void set_exclusive_passive_skill_obsolete(::google::protobuf::int32 value);

  // optional int32 skin_id = 7;
  inline bool has_skin_id() const;
  inline void clear_skin_id();
  static const int kSkinIdFieldNumber = 7;
  inline ::google::protobuf::int32 skin_id() const;
  inline void set_skin_id(::google::protobuf::int32 value);

  // repeated int32 other_sp_list = 8;
  inline int other_sp_list_size() const;
  inline void clear_other_sp_list();
  static const int kOtherSpListFieldNumber = 8;
  inline ::google::protobuf::int32 other_sp_list(int index) const;
  inline void set_other_sp_list(int index, ::google::protobuf::int32 value);
  inline void add_other_sp_list(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      other_sp_list() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_other_sp_list();

  // optional int64 unique_id = 9;
  inline bool has_unique_id() const;
  inline void clear_unique_id();
  static const int kUniqueIdFieldNumber = 9;
  inline ::google::protobuf::int64 unique_id() const;
  inline void set_unique_id(::google::protobuf::int64 value);

  // repeated int32 passive_level_list = 10;
  inline int passive_level_list_size() const;
  inline void clear_passive_level_list();
  static const int kPassiveLevelListFieldNumber = 10;
  inline ::google::protobuf::int32 passive_level_list(int index) const;
  inline void set_passive_level_list(int index, ::google::protobuf::int32 value);
  inline void add_passive_level_list(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      passive_level_list() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_passive_level_list();

  // optional int32 lianyao_pet_id = 11;
  inline bool has_lianyao_pet_id() const;
  inline void clear_lianyao_pet_id();
  static const int kLianyaoPetIdFieldNumber = 11;
  inline ::google::protobuf::int32 lianyao_pet_id() const;
  inline void set_lianyao_pet_id(::google::protobuf::int32 value);

  // optional int32 lianyao_pet_str_lv = 12;
  inline bool has_lianyao_pet_str_lv() const;
  inline void clear_lianyao_pet_str_lv();
  static const int kLianyaoPetStrLvFieldNumber = 12;
  inline ::google::protobuf::int32 lianyao_pet_str_lv() const;
  inline void set_lianyao_pet_str_lv(::google::protobuf::int32 value);

  // optional int32 pet_exclusive_skill_disable_flag = 13;
  inline bool has_pet_exclusive_skill_disable_flag() const;
  inline void clear_pet_exclusive_skill_disable_flag();
  static const int kPetExclusiveSkillDisableFlagFieldNumber = 13;
  inline ::google::protobuf::int32 pet_exclusive_skill_disable_flag() const;
  inline void set_pet_exclusive_skill_disable_flag(::google::protobuf::int32 value);

  // optional int32 lian_yao_exclusive_skill_disable_flag = 14;
  inline bool has_lian_yao_exclusive_skill_disable_flag() const;
  inline void clear_lian_yao_exclusive_skill_disable_flag();
  static const int kLianYaoExclusiveSkillDisableFlagFieldNumber = 14;
  inline ::google::protobuf::int32 lian_yao_exclusive_skill_disable_flag() const;
  inline void set_lian_yao_exclusive_skill_disable_flag(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PB_PetBattleData)
 private:
  inline void set_has_battle_data();
  inline void clear_has_battle_data();
  inline void set_has_auto_move_type();
  inline void clear_has_auto_move_type();
  inline void set_has_auto_skill_id();
  inline void clear_has_auto_skill_id();
  inline void set_has_auto_skill_level();
  inline void clear_has_auto_skill_level();
  inline void set_has_exclusive_passive_skill_obsolete();
  inline void clear_has_exclusive_passive_skill_obsolete();
  inline void set_has_skin_id();
  inline void clear_has_skin_id();
  inline void set_has_unique_id();
  inline void clear_has_unique_id();
  inline void set_has_lianyao_pet_id();
  inline void clear_has_lianyao_pet_id();
  inline void set_has_lianyao_pet_str_lv();
  inline void clear_has_lianyao_pet_str_lv();
  inline void set_has_pet_exclusive_skill_disable_flag();
  inline void clear_has_pet_exclusive_skill_disable_flag();
  inline void set_has_lian_yao_exclusive_skill_disable_flag();
  inline void clear_has_lian_yao_exclusive_skill_disable_flag();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::PB_BattleCharacterData* battle_data_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > passive_list_;
  ::google::protobuf::int32 auto_move_type_;
  ::google::protobuf::int32 auto_skill_id_;
  ::google::protobuf::int32 auto_skill_level_;
  ::google::protobuf::int32 exclusive_passive_skill_obsolete_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > other_sp_list_;
  ::google::protobuf::int64 unique_id_;
  ::google::protobuf::int32 skin_id_;
  ::google::protobuf::int32 lianyao_pet_id_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > passive_level_list_;
  ::google::protobuf::int32 lianyao_pet_str_lv_;
  ::google::protobuf::int32 pet_exclusive_skill_disable_flag_;
  ::google::protobuf::int32 lian_yao_exclusive_skill_disable_flag_;
  friend void  protobuf_AddDesc_pet_5fbattle_5fdata_2eproto();
  friend void protobuf_AssignDesc_pet_5fbattle_5fdata_2eproto();
  friend void protobuf_ShutdownFile_pet_5fbattle_5fdata_2eproto();

  void InitAsDefaultInstance();
  static PB_PetBattleData* default_instance_;
};
// ===================================================================


// ===================================================================

// PB_PetBattleData

// optional .PB_BattleCharacterData battle_data = 1;
inline bool PB_PetBattleData::has_battle_data() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PB_PetBattleData::set_has_battle_data() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PB_PetBattleData::clear_has_battle_data() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PB_PetBattleData::clear_battle_data() {
  if (battle_data_ != NULL) battle_data_->::PB_BattleCharacterData::Clear();
  clear_has_battle_data();
}
inline const ::PB_BattleCharacterData& PB_PetBattleData::battle_data() const {
  // @@protoc_insertion_point(field_get:PB_PetBattleData.battle_data)
  return battle_data_ != NULL ? *battle_data_ : *default_instance_->battle_data_;
}
inline ::PB_BattleCharacterData* PB_PetBattleData::mutable_battle_data() {
  set_has_battle_data();
  if (battle_data_ == NULL) battle_data_ = new ::PB_BattleCharacterData;
  // @@protoc_insertion_point(field_mutable:PB_PetBattleData.battle_data)
  return battle_data_;
}
inline ::PB_BattleCharacterData* PB_PetBattleData::release_battle_data() {
  clear_has_battle_data();
  ::PB_BattleCharacterData* temp = battle_data_;
  battle_data_ = NULL;
  return temp;
}
inline void PB_PetBattleData::set_allocated_battle_data(::PB_BattleCharacterData* battle_data) {
  delete battle_data_;
  battle_data_ = battle_data;
  if (battle_data) {
    set_has_battle_data();
  } else {
    clear_has_battle_data();
  }
  // @@protoc_insertion_point(field_set_allocated:PB_PetBattleData.battle_data)
}

// repeated int32 passive_list = 2;
inline int PB_PetBattleData::passive_list_size() const {
  return passive_list_.size();
}
inline void PB_PetBattleData::clear_passive_list() {
  passive_list_.Clear();
}
inline ::google::protobuf::int32 PB_PetBattleData::passive_list(int index) const {
  // @@protoc_insertion_point(field_get:PB_PetBattleData.passive_list)
  return passive_list_.Get(index);
}
inline void PB_PetBattleData::set_passive_list(int index, ::google::protobuf::int32 value) {
  passive_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:PB_PetBattleData.passive_list)
}
inline void PB_PetBattleData::add_passive_list(::google::protobuf::int32 value) {
  passive_list_.Add(value);
  // @@protoc_insertion_point(field_add:PB_PetBattleData.passive_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
PB_PetBattleData::passive_list() const {
  // @@protoc_insertion_point(field_list:PB_PetBattleData.passive_list)
  return passive_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
PB_PetBattleData::mutable_passive_list() {
  // @@protoc_insertion_point(field_mutable_list:PB_PetBattleData.passive_list)
  return &passive_list_;
}

// optional int32 auto_move_type = 3;
inline bool PB_PetBattleData::has_auto_move_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PB_PetBattleData::set_has_auto_move_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PB_PetBattleData::clear_has_auto_move_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PB_PetBattleData::clear_auto_move_type() {
  auto_move_type_ = 0;
  clear_has_auto_move_type();
}
inline ::google::protobuf::int32 PB_PetBattleData::auto_move_type() const {
  // @@protoc_insertion_point(field_get:PB_PetBattleData.auto_move_type)
  return auto_move_type_;
}
inline void PB_PetBattleData::set_auto_move_type(::google::protobuf::int32 value) {
  set_has_auto_move_type();
  auto_move_type_ = value;
  // @@protoc_insertion_point(field_set:PB_PetBattleData.auto_move_type)
}

// optional int32 auto_skill_id = 4;
inline bool PB_PetBattleData::has_auto_skill_id() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PB_PetBattleData::set_has_auto_skill_id() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PB_PetBattleData::clear_has_auto_skill_id() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PB_PetBattleData::clear_auto_skill_id() {
  auto_skill_id_ = 0;
  clear_has_auto_skill_id();
}
inline ::google::protobuf::int32 PB_PetBattleData::auto_skill_id() const {
  // @@protoc_insertion_point(field_get:PB_PetBattleData.auto_skill_id)
  return auto_skill_id_;
}
inline void PB_PetBattleData::set_auto_skill_id(::google::protobuf::int32 value) {
  set_has_auto_skill_id();
  auto_skill_id_ = value;
  // @@protoc_insertion_point(field_set:PB_PetBattleData.auto_skill_id)
}

// optional int32 auto_skill_level = 5;
inline bool PB_PetBattleData::has_auto_skill_level() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PB_PetBattleData::set_has_auto_skill_level() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PB_PetBattleData::clear_has_auto_skill_level() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PB_PetBattleData::clear_auto_skill_level() {
  auto_skill_level_ = 0;
  clear_has_auto_skill_level();
}
inline ::google::protobuf::int32 PB_PetBattleData::auto_skill_level() const {
  // @@protoc_insertion_point(field_get:PB_PetBattleData.auto_skill_level)
  return auto_skill_level_;
}
inline void PB_PetBattleData::set_auto_skill_level(::google::protobuf::int32 value) {
  set_has_auto_skill_level();
  auto_skill_level_ = value;
  // @@protoc_insertion_point(field_set:PB_PetBattleData.auto_skill_level)
}

// optional int32 exclusive_passive_skill_OBSOLETE = 6;
inline bool PB_PetBattleData::has_exclusive_passive_skill_obsolete() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void PB_PetBattleData::set_has_exclusive_passive_skill_obsolete() {
  _has_bits_[0] |= 0x00000020u;
}
inline void PB_PetBattleData::clear_has_exclusive_passive_skill_obsolete() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void PB_PetBattleData::clear_exclusive_passive_skill_obsolete() {
  exclusive_passive_skill_obsolete_ = 0;
  clear_has_exclusive_passive_skill_obsolete();
}
inline ::google::protobuf::int32 PB_PetBattleData::exclusive_passive_skill_obsolete() const {
  // @@protoc_insertion_point(field_get:PB_PetBattleData.exclusive_passive_skill_OBSOLETE)
  return exclusive_passive_skill_obsolete_;
}
inline void PB_PetBattleData::set_exclusive_passive_skill_obsolete(::google::protobuf::int32 value) {
  set_has_exclusive_passive_skill_obsolete();
  exclusive_passive_skill_obsolete_ = value;
  // @@protoc_insertion_point(field_set:PB_PetBattleData.exclusive_passive_skill_OBSOLETE)
}

// optional int32 skin_id = 7;
inline bool PB_PetBattleData::has_skin_id() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void PB_PetBattleData::set_has_skin_id() {
  _has_bits_[0] |= 0x00000040u;
}
inline void PB_PetBattleData::clear_has_skin_id() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void PB_PetBattleData::clear_skin_id() {
  skin_id_ = 0;
  clear_has_skin_id();
}
inline ::google::protobuf::int32 PB_PetBattleData::skin_id() const {
  // @@protoc_insertion_point(field_get:PB_PetBattleData.skin_id)
  return skin_id_;
}
inline void PB_PetBattleData::set_skin_id(::google::protobuf::int32 value) {
  set_has_skin_id();
  skin_id_ = value;
  // @@protoc_insertion_point(field_set:PB_PetBattleData.skin_id)
}

// repeated int32 other_sp_list = 8;
inline int PB_PetBattleData::other_sp_list_size() const {
  return other_sp_list_.size();
}
inline void PB_PetBattleData::clear_other_sp_list() {
  other_sp_list_.Clear();
}
inline ::google::protobuf::int32 PB_PetBattleData::other_sp_list(int index) const {
  // @@protoc_insertion_point(field_get:PB_PetBattleData.other_sp_list)
  return other_sp_list_.Get(index);
}
inline void PB_PetBattleData::set_other_sp_list(int index, ::google::protobuf::int32 value) {
  other_sp_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:PB_PetBattleData.other_sp_list)
}
inline void PB_PetBattleData::add_other_sp_list(::google::protobuf::int32 value) {
  other_sp_list_.Add(value);
  // @@protoc_insertion_point(field_add:PB_PetBattleData.other_sp_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
PB_PetBattleData::other_sp_list() const {
  // @@protoc_insertion_point(field_list:PB_PetBattleData.other_sp_list)
  return other_sp_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
PB_PetBattleData::mutable_other_sp_list() {
  // @@protoc_insertion_point(field_mutable_list:PB_PetBattleData.other_sp_list)
  return &other_sp_list_;
}

// optional int64 unique_id = 9;
inline bool PB_PetBattleData::has_unique_id() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void PB_PetBattleData::set_has_unique_id() {
  _has_bits_[0] |= 0x00000100u;
}
inline void PB_PetBattleData::clear_has_unique_id() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void PB_PetBattleData::clear_unique_id() {
  unique_id_ = GOOGLE_LONGLONG(0);
  clear_has_unique_id();
}
inline ::google::protobuf::int64 PB_PetBattleData::unique_id() const {
  // @@protoc_insertion_point(field_get:PB_PetBattleData.unique_id)
  return unique_id_;
}
inline void PB_PetBattleData::set_unique_id(::google::protobuf::int64 value) {
  set_has_unique_id();
  unique_id_ = value;
  // @@protoc_insertion_point(field_set:PB_PetBattleData.unique_id)
}

// repeated int32 passive_level_list = 10;
inline int PB_PetBattleData::passive_level_list_size() const {
  return passive_level_list_.size();
}
inline void PB_PetBattleData::clear_passive_level_list() {
  passive_level_list_.Clear();
}
inline ::google::protobuf::int32 PB_PetBattleData::passive_level_list(int index) const {
  // @@protoc_insertion_point(field_get:PB_PetBattleData.passive_level_list)
  return passive_level_list_.Get(index);
}
inline void PB_PetBattleData::set_passive_level_list(int index, ::google::protobuf::int32 value) {
  passive_level_list_.Set(index, value);
  // @@protoc_insertion_point(field_set:PB_PetBattleData.passive_level_list)
}
inline void PB_PetBattleData::add_passive_level_list(::google::protobuf::int32 value) {
  passive_level_list_.Add(value);
  // @@protoc_insertion_point(field_add:PB_PetBattleData.passive_level_list)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
PB_PetBattleData::passive_level_list() const {
  // @@protoc_insertion_point(field_list:PB_PetBattleData.passive_level_list)
  return passive_level_list_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
PB_PetBattleData::mutable_passive_level_list() {
  // @@protoc_insertion_point(field_mutable_list:PB_PetBattleData.passive_level_list)
  return &passive_level_list_;
}

// optional int32 lianyao_pet_id = 11;
inline bool PB_PetBattleData::has_lianyao_pet_id() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void PB_PetBattleData::set_has_lianyao_pet_id() {
  _has_bits_[0] |= 0x00000400u;
}
inline void PB_PetBattleData::clear_has_lianyao_pet_id() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void PB_PetBattleData::clear_lianyao_pet_id() {
  lianyao_pet_id_ = 0;
  clear_has_lianyao_pet_id();
}
inline ::google::protobuf::int32 PB_PetBattleData::lianyao_pet_id() const {
  // @@protoc_insertion_point(field_get:PB_PetBattleData.lianyao_pet_id)
  return lianyao_pet_id_;
}
inline void PB_PetBattleData::set_lianyao_pet_id(::google::protobuf::int32 value) {
  set_has_lianyao_pet_id();
  lianyao_pet_id_ = value;
  // @@protoc_insertion_point(field_set:PB_PetBattleData.lianyao_pet_id)
}

// optional int32 lianyao_pet_str_lv = 12;
inline bool PB_PetBattleData::has_lianyao_pet_str_lv() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void PB_PetBattleData::set_has_lianyao_pet_str_lv() {
  _has_bits_[0] |= 0x00000800u;
}
inline void PB_PetBattleData::clear_has_lianyao_pet_str_lv() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void PB_PetBattleData::clear_lianyao_pet_str_lv() {
  lianyao_pet_str_lv_ = 0;
  clear_has_lianyao_pet_str_lv();
}
inline ::google::protobuf::int32 PB_PetBattleData::lianyao_pet_str_lv() const {
  // @@protoc_insertion_point(field_get:PB_PetBattleData.lianyao_pet_str_lv)
  return lianyao_pet_str_lv_;
}
inline void PB_PetBattleData::set_lianyao_pet_str_lv(::google::protobuf::int32 value) {
  set_has_lianyao_pet_str_lv();
  lianyao_pet_str_lv_ = value;
  // @@protoc_insertion_point(field_set:PB_PetBattleData.lianyao_pet_str_lv)
}

// optional int32 pet_exclusive_skill_disable_flag = 13;
inline bool PB_PetBattleData::has_pet_exclusive_skill_disable_flag() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void PB_PetBattleData::set_has_pet_exclusive_skill_disable_flag() {
  _has_bits_[0] |= 0x00001000u;
}
inline void PB_PetBattleData::clear_has_pet_exclusive_skill_disable_flag() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void PB_PetBattleData::clear_pet_exclusive_skill_disable_flag() {
  pet_exclusive_skill_disable_flag_ = 0;
  clear_has_pet_exclusive_skill_disable_flag();
}
inline ::google::protobuf::int32 PB_PetBattleData::pet_exclusive_skill_disable_flag() const {
  // @@protoc_insertion_point(field_get:PB_PetBattleData.pet_exclusive_skill_disable_flag)
  return pet_exclusive_skill_disable_flag_;
}
inline void PB_PetBattleData::set_pet_exclusive_skill_disable_flag(::google::protobuf::int32 value) {
  set_has_pet_exclusive_skill_disable_flag();
  pet_exclusive_skill_disable_flag_ = value;
  // @@protoc_insertion_point(field_set:PB_PetBattleData.pet_exclusive_skill_disable_flag)
}

// optional int32 lian_yao_exclusive_skill_disable_flag = 14;
inline bool PB_PetBattleData::has_lian_yao_exclusive_skill_disable_flag() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void PB_PetBattleData::set_has_lian_yao_exclusive_skill_disable_flag() {
  _has_bits_[0] |= 0x00002000u;
}
inline void PB_PetBattleData::clear_has_lian_yao_exclusive_skill_disable_flag() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void PB_PetBattleData::clear_lian_yao_exclusive_skill_disable_flag() {
  lian_yao_exclusive_skill_disable_flag_ = 0;
  clear_has_lian_yao_exclusive_skill_disable_flag();
}
inline ::google::protobuf::int32 PB_PetBattleData::lian_yao_exclusive_skill_disable_flag() const {
  // @@protoc_insertion_point(field_get:PB_PetBattleData.lian_yao_exclusive_skill_disable_flag)
  return lian_yao_exclusive_skill_disable_flag_;
}
inline void PB_PetBattleData::set_lian_yao_exclusive_skill_disable_flag(::google::protobuf::int32 value) {
  set_has_lian_yao_exclusive_skill_disable_flag();
  lian_yao_exclusive_skill_disable_flag_ = value;
  // @@protoc_insertion_point(field_set:PB_PetBattleData.lian_yao_exclusive_skill_disable_flag)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pet_5fbattle_5fdata_2eproto__INCLUDED
