// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: platform_battle_partner.proto

#ifndef PROTOBUF_platform_5fbattle_5fpartner_2eproto__INCLUDED
#define PROTOBUF_platform_5fbattle_5fpartner_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "partner_battle_data.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_platform_5fbattle_5fpartner_2eproto();
void protobuf_AssignDesc_platform_5fbattle_5fpartner_2eproto();
void protobuf_ShutdownFile_platform_5fbattle_5fpartner_2eproto();

class PB_PlatformBattlePartner;

// ===================================================================

class PB_PlatformBattlePartner : public ::google::protobuf::Message {
 public:
  PB_PlatformBattlePartner();
  virtual ~PB_PlatformBattlePartner();

  PB_PlatformBattlePartner(const PB_PlatformBattlePartner& from);

  inline PB_PlatformBattlePartner& operator=(const PB_PlatformBattlePartner& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PB_PlatformBattlePartner& default_instance();

  void Swap(PB_PlatformBattlePartner* other);

  // implements Message ----------------------------------------------

  PB_PlatformBattlePartner* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PB_PlatformBattlePartner& from);
  void MergeFrom(const PB_PlatformBattlePartner& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 pos = 1;
  inline bool has_pos() const;
  inline void clear_pos();
  static const int kPosFieldNumber = 1;
  inline ::google::protobuf::int32 pos() const;
  inline void set_pos(::google::protobuf::int32 value);

  // optional int32 level = 2;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 2;
  inline ::google::protobuf::int32 level() const;
  inline void set_level(::google::protobuf::int32 value);

  // optional int32 partner_id = 3;
  inline bool has_partner_id() const;
  inline void clear_partner_id();
  static const int kPartnerIdFieldNumber = 3;
  inline ::google::protobuf::int32 partner_id() const;
  inline void set_partner_id(::google::protobuf::int32 value);

  // optional int32 capability = 4;
  inline bool has_capability() const;
  inline void clear_capability();
  static const int kCapabilityFieldNumber = 4;
  inline ::google::protobuf::int32 capability() const;
  inline void set_capability(::google::protobuf::int32 value);

  // optional .PB_PartnerBattleData partner_battle_data = 5;
  inline bool has_partner_battle_data() const;
  inline void clear_partner_battle_data();
  static const int kPartnerBattleDataFieldNumber = 5;
  inline const ::PB_PartnerBattleData& partner_battle_data() const;
  inline ::PB_PartnerBattleData* mutable_partner_battle_data();
  inline ::PB_PartnerBattleData* release_partner_battle_data();
  inline void set_allocated_partner_battle_data(::PB_PartnerBattleData* partner_battle_data);

  // @@protoc_insertion_point(class_scope:PB_PlatformBattlePartner)
 private:
  inline void set_has_pos();
  inline void clear_has_pos();
  inline void set_has_level();
  inline void clear_has_level();
  inline void set_has_partner_id();
  inline void clear_has_partner_id();
  inline void set_has_capability();
  inline void clear_has_capability();
  inline void set_has_partner_battle_data();
  inline void clear_has_partner_battle_data();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 pos_;
  ::google::protobuf::int32 level_;
  ::google::protobuf::int32 partner_id_;
  ::google::protobuf::int32 capability_;
  ::PB_PartnerBattleData* partner_battle_data_;
  friend void  protobuf_AddDesc_platform_5fbattle_5fpartner_2eproto();
  friend void protobuf_AssignDesc_platform_5fbattle_5fpartner_2eproto();
  friend void protobuf_ShutdownFile_platform_5fbattle_5fpartner_2eproto();

  void InitAsDefaultInstance();
  static PB_PlatformBattlePartner* default_instance_;
};
// ===================================================================


// ===================================================================

// PB_PlatformBattlePartner

// optional int32 pos = 1;
inline bool PB_PlatformBattlePartner::has_pos() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PB_PlatformBattlePartner::set_has_pos() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PB_PlatformBattlePartner::clear_has_pos() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PB_PlatformBattlePartner::clear_pos() {
  pos_ = 0;
  clear_has_pos();
}
inline ::google::protobuf::int32 PB_PlatformBattlePartner::pos() const {
  // @@protoc_insertion_point(field_get:PB_PlatformBattlePartner.pos)
  return pos_;
}
inline void PB_PlatformBattlePartner::set_pos(::google::protobuf::int32 value) {
  set_has_pos();
  pos_ = value;
  // @@protoc_insertion_point(field_set:PB_PlatformBattlePartner.pos)
}

// optional int32 level = 2;
inline bool PB_PlatformBattlePartner::has_level() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PB_PlatformBattlePartner::set_has_level() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PB_PlatformBattlePartner::clear_has_level() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PB_PlatformBattlePartner::clear_level() {
  level_ = 0;
  clear_has_level();
}
inline ::google::protobuf::int32 PB_PlatformBattlePartner::level() const {
  // @@protoc_insertion_point(field_get:PB_PlatformBattlePartner.level)
  return level_;
}
inline void PB_PlatformBattlePartner::set_level(::google::protobuf::int32 value) {
  set_has_level();
  level_ = value;
  // @@protoc_insertion_point(field_set:PB_PlatformBattlePartner.level)
}

// optional int32 partner_id = 3;
inline bool PB_PlatformBattlePartner::has_partner_id() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PB_PlatformBattlePartner::set_has_partner_id() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PB_PlatformBattlePartner::clear_has_partner_id() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PB_PlatformBattlePartner::clear_partner_id() {
  partner_id_ = 0;
  clear_has_partner_id();
}
inline ::google::protobuf::int32 PB_PlatformBattlePartner::partner_id() const {
  // @@protoc_insertion_point(field_get:PB_PlatformBattlePartner.partner_id)
  return partner_id_;
}
inline void PB_PlatformBattlePartner::set_partner_id(::google::protobuf::int32 value) {
  set_has_partner_id();
  partner_id_ = value;
  // @@protoc_insertion_point(field_set:PB_PlatformBattlePartner.partner_id)
}

// optional int32 capability = 4;
inline bool PB_PlatformBattlePartner::has_capability() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PB_PlatformBattlePartner::set_has_capability() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PB_PlatformBattlePartner::clear_has_capability() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PB_PlatformBattlePartner::clear_capability() {
  capability_ = 0;
  clear_has_capability();
}
inline ::google::protobuf::int32 PB_PlatformBattlePartner::capability() const {
  // @@protoc_insertion_point(field_get:PB_PlatformBattlePartner.capability)
  return capability_;
}
inline void PB_PlatformBattlePartner::set_capability(::google::protobuf::int32 value) {
  set_has_capability();
  capability_ = value;
  // @@protoc_insertion_point(field_set:PB_PlatformBattlePartner.capability)
}

// optional .PB_PartnerBattleData partner_battle_data = 5;
inline bool PB_PlatformBattlePartner::has_partner_battle_data() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PB_PlatformBattlePartner::set_has_partner_battle_data() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PB_PlatformBattlePartner::clear_has_partner_battle_data() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PB_PlatformBattlePartner::clear_partner_battle_data() {
  if (partner_battle_data_ != NULL) partner_battle_data_->::PB_PartnerBattleData::Clear();
  clear_has_partner_battle_data();
}
inline const ::PB_PartnerBattleData& PB_PlatformBattlePartner::partner_battle_data() const {
  // @@protoc_insertion_point(field_get:PB_PlatformBattlePartner.partner_battle_data)
  return partner_battle_data_ != NULL ? *partner_battle_data_ : *default_instance_->partner_battle_data_;
}
inline ::PB_PartnerBattleData* PB_PlatformBattlePartner::mutable_partner_battle_data() {
  set_has_partner_battle_data();
  if (partner_battle_data_ == NULL) partner_battle_data_ = new ::PB_PartnerBattleData;
  // @@protoc_insertion_point(field_mutable:PB_PlatformBattlePartner.partner_battle_data)
  return partner_battle_data_;
}
inline ::PB_PartnerBattleData* PB_PlatformBattlePartner::release_partner_battle_data() {
  clear_has_partner_battle_data();
  ::PB_PartnerBattleData* temp = partner_battle_data_;
  partner_battle_data_ = NULL;
  return temp;
}
inline void PB_PlatformBattlePartner::set_allocated_partner_battle_data(::PB_PartnerBattleData* partner_battle_data) {
  delete partner_battle_data_;
  partner_battle_data_ = partner_battle_data;
  if (partner_battle_data) {
    set_has_partner_battle_data();
  } else {
    clear_has_partner_battle_data();
  }
  // @@protoc_insertion_point(field_set_allocated:PB_PlatformBattlePartner.partner_battle_data)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_platform_5fbattle_5fpartner_2eproto__INCLUDED
