// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: role_mirageterritory_data.proto

#ifndef PROTOBUF_role_5fmirageterritory_5fdata_2eproto__INCLUDED
#define PROTOBUF_role_5fmirageterritory_5fdata_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_role_5fmirageterritory_5fdata_2eproto();
void protobuf_AssignDesc_role_5fmirageterritory_5fdata_2eproto();
void protobuf_ShutdownFile_role_5fmirageterritory_5fdata_2eproto();

class PB_RoleMirageTerritoryInfoData;
class PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo;
class PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo;

// ===================================================================

class PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo : public ::google::protobuf::Message {
 public:
  PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo();
  virtual ~PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo();

  PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo(const PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo& from);

  inline PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo& operator=(const PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo& default_instance();

  void Swap(PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo* other);

  // implements Message ----------------------------------------------

  PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo& from);
  void MergeFrom(const PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 top_seq = 1;
  inline bool has_top_seq() const;
  inline void clear_top_seq();
  static const int kTopSeqFieldNumber = 1;
  inline ::google::protobuf::int32 top_seq() const;
  inline void set_top_seq(::google::protobuf::int32 value);

  // optional int32 now_seq = 2;
  inline bool has_now_seq() const;
  inline void clear_now_seq();
  static const int kNowSeqFieldNumber = 2;
  inline ::google::protobuf::int32 now_seq() const;
  inline void set_now_seq(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:PB_RoleMirageTerritoryInfoData.MirageTerritoryInfo)
 private:
  inline void set_has_top_seq();
  inline void clear_has_top_seq();
  inline void set_has_now_seq();
  inline void clear_has_now_seq();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 top_seq_;
  ::google::protobuf::int32 now_seq_;
  friend void  protobuf_AddDesc_role_5fmirageterritory_5fdata_2eproto();
  friend void protobuf_AssignDesc_role_5fmirageterritory_5fdata_2eproto();
  friend void protobuf_ShutdownFile_role_5fmirageterritory_5fdata_2eproto();

  void InitAsDefaultInstance();
  static PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo* default_instance_;
};
// -------------------------------------------------------------------

class PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo : public ::google::protobuf::Message {
 public:
  PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo();
  virtual ~PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo();

  PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo(const PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo& from);

  inline PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo& operator=(const PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo& default_instance();

  void Swap(PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo* other);

  // implements Message ----------------------------------------------

  PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo& from);
  void MergeFrom(const PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 today_pass_times = 1;
  inline bool has_today_pass_times() const;
  inline void clear_today_pass_times();
  static const int kTodayPassTimesFieldNumber = 1;
  inline ::google::protobuf::int32 today_pass_times() const;
  inline void set_today_pass_times(::google::protobuf::int32 value);

  // optional int32 pass_area = 2;
  inline bool has_pass_area() const;
  inline void clear_pass_area();
  static const int kPassAreaFieldNumber = 2;
  inline ::google::protobuf::int32 pass_area() const;
  inline void set_pass_area(::google::protobuf::int32 value);

  // optional int32 pass_seq = 3;
  inline bool has_pass_seq() const;
  inline void clear_pass_seq();
  static const int kPassSeqFieldNumber = 3;
  inline ::google::protobuf::int32 pass_seq() const;
  inline void set_pass_seq(::google::protobuf::int32 value);

  // repeated .PB_RoleMirageTerritoryInfoData.MirageTerritoryInfo partner_list = 4;
  inline int partner_list_size() const;
  inline void clear_partner_list();
  static const int kPartnerListFieldNumber = 4;
  inline const ::PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo& partner_list(int index) const;
  inline ::PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo* mutable_partner_list(int index);
  inline ::PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo* add_partner_list();
  inline const ::google::protobuf::RepeatedPtrField< ::PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo >&
      partner_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo >*
      mutable_partner_list();

  // @@protoc_insertion_point(class_scope:PB_RoleMirageTerritoryInfoData.MirageTerritoryAllInfo)
 private:
  inline void set_has_today_pass_times();
  inline void clear_has_today_pass_times();
  inline void set_has_pass_area();
  inline void clear_has_pass_area();
  inline void set_has_pass_seq();
  inline void clear_has_pass_seq();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int32 today_pass_times_;
  ::google::protobuf::int32 pass_area_;
  ::google::protobuf::RepeatedPtrField< ::PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo > partner_list_;
  ::google::protobuf::int32 pass_seq_;
  friend void  protobuf_AddDesc_role_5fmirageterritory_5fdata_2eproto();
  friend void protobuf_AssignDesc_role_5fmirageterritory_5fdata_2eproto();
  friend void protobuf_ShutdownFile_role_5fmirageterritory_5fdata_2eproto();

  void InitAsDefaultInstance();
  static PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo* default_instance_;
};
// -------------------------------------------------------------------

class PB_RoleMirageTerritoryInfoData : public ::google::protobuf::Message {
 public:
  PB_RoleMirageTerritoryInfoData();
  virtual ~PB_RoleMirageTerritoryInfoData();

  PB_RoleMirageTerritoryInfoData(const PB_RoleMirageTerritoryInfoData& from);

  inline PB_RoleMirageTerritoryInfoData& operator=(const PB_RoleMirageTerritoryInfoData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PB_RoleMirageTerritoryInfoData& default_instance();

  void Swap(PB_RoleMirageTerritoryInfoData* other);

  // implements Message ----------------------------------------------

  PB_RoleMirageTerritoryInfoData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PB_RoleMirageTerritoryInfoData& from);
  void MergeFrom(const PB_RoleMirageTerritoryInfoData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo MirageTerritoryInfo;
  typedef PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo MirageTerritoryAllInfo;

  // accessors -------------------------------------------------------

  // repeated .PB_RoleMirageTerritoryInfoData.MirageTerritoryAllInfo pertner_data_list = 1;
  inline int pertner_data_list_size() const;
  inline void clear_pertner_data_list();
  static const int kPertnerDataListFieldNumber = 1;
  inline const ::PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo& pertner_data_list(int index) const;
  inline ::PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo* mutable_pertner_data_list(int index);
  inline ::PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo* add_pertner_data_list();
  inline const ::google::protobuf::RepeatedPtrField< ::PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo >&
      pertner_data_list() const;
  inline ::google::protobuf::RepeatedPtrField< ::PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo >*
      mutable_pertner_data_list();

  // @@protoc_insertion_point(class_scope:PB_RoleMirageTerritoryInfoData)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo > pertner_data_list_;
  friend void  protobuf_AddDesc_role_5fmirageterritory_5fdata_2eproto();
  friend void protobuf_AssignDesc_role_5fmirageterritory_5fdata_2eproto();
  friend void protobuf_ShutdownFile_role_5fmirageterritory_5fdata_2eproto();

  void InitAsDefaultInstance();
  static PB_RoleMirageTerritoryInfoData* default_instance_;
};
// ===================================================================


// ===================================================================

// PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo

// optional int32 top_seq = 1;
inline bool PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo::has_top_seq() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo::set_has_top_seq() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo::clear_has_top_seq() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo::clear_top_seq() {
  top_seq_ = 0;
  clear_has_top_seq();
}
inline ::google::protobuf::int32 PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo::top_seq() const {
  // @@protoc_insertion_point(field_get:PB_RoleMirageTerritoryInfoData.MirageTerritoryInfo.top_seq)
  return top_seq_;
}
inline void PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo::set_top_seq(::google::protobuf::int32 value) {
  set_has_top_seq();
  top_seq_ = value;
  // @@protoc_insertion_point(field_set:PB_RoleMirageTerritoryInfoData.MirageTerritoryInfo.top_seq)
}

// optional int32 now_seq = 2;
inline bool PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo::has_now_seq() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo::set_has_now_seq() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo::clear_has_now_seq() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo::clear_now_seq() {
  now_seq_ = 0;
  clear_has_now_seq();
}
inline ::google::protobuf::int32 PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo::now_seq() const {
  // @@protoc_insertion_point(field_get:PB_RoleMirageTerritoryInfoData.MirageTerritoryInfo.now_seq)
  return now_seq_;
}
inline void PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo::set_now_seq(::google::protobuf::int32 value) {
  set_has_now_seq();
  now_seq_ = value;
  // @@protoc_insertion_point(field_set:PB_RoleMirageTerritoryInfoData.MirageTerritoryInfo.now_seq)
}

// -------------------------------------------------------------------

// PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo

// optional int32 today_pass_times = 1;
inline bool PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::has_today_pass_times() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::set_has_today_pass_times() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::clear_has_today_pass_times() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::clear_today_pass_times() {
  today_pass_times_ = 0;
  clear_has_today_pass_times();
}
inline ::google::protobuf::int32 PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::today_pass_times() const {
  // @@protoc_insertion_point(field_get:PB_RoleMirageTerritoryInfoData.MirageTerritoryAllInfo.today_pass_times)
  return today_pass_times_;
}
inline void PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::set_today_pass_times(::google::protobuf::int32 value) {
  set_has_today_pass_times();
  today_pass_times_ = value;
  // @@protoc_insertion_point(field_set:PB_RoleMirageTerritoryInfoData.MirageTerritoryAllInfo.today_pass_times)
}

// optional int32 pass_area = 2;
inline bool PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::has_pass_area() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::set_has_pass_area() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::clear_has_pass_area() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::clear_pass_area() {
  pass_area_ = 0;
  clear_has_pass_area();
}
inline ::google::protobuf::int32 PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::pass_area() const {
  // @@protoc_insertion_point(field_get:PB_RoleMirageTerritoryInfoData.MirageTerritoryAllInfo.pass_area)
  return pass_area_;
}
inline void PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::set_pass_area(::google::protobuf::int32 value) {
  set_has_pass_area();
  pass_area_ = value;
  // @@protoc_insertion_point(field_set:PB_RoleMirageTerritoryInfoData.MirageTerritoryAllInfo.pass_area)
}

// optional int32 pass_seq = 3;
inline bool PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::has_pass_seq() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::set_has_pass_seq() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::clear_has_pass_seq() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::clear_pass_seq() {
  pass_seq_ = 0;
  clear_has_pass_seq();
}
inline ::google::protobuf::int32 PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::pass_seq() const {
  // @@protoc_insertion_point(field_get:PB_RoleMirageTerritoryInfoData.MirageTerritoryAllInfo.pass_seq)
  return pass_seq_;
}
inline void PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::set_pass_seq(::google::protobuf::int32 value) {
  set_has_pass_seq();
  pass_seq_ = value;
  // @@protoc_insertion_point(field_set:PB_RoleMirageTerritoryInfoData.MirageTerritoryAllInfo.pass_seq)
}

// repeated .PB_RoleMirageTerritoryInfoData.MirageTerritoryInfo partner_list = 4;
inline int PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::partner_list_size() const {
  return partner_list_.size();
}
inline void PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::clear_partner_list() {
  partner_list_.Clear();
}
inline const ::PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo& PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::partner_list(int index) const {
  // @@protoc_insertion_point(field_get:PB_RoleMirageTerritoryInfoData.MirageTerritoryAllInfo.partner_list)
  return partner_list_.Get(index);
}
inline ::PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo* PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::mutable_partner_list(int index) {
  // @@protoc_insertion_point(field_mutable:PB_RoleMirageTerritoryInfoData.MirageTerritoryAllInfo.partner_list)
  return partner_list_.Mutable(index);
}
inline ::PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo* PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::add_partner_list() {
  // @@protoc_insertion_point(field_add:PB_RoleMirageTerritoryInfoData.MirageTerritoryAllInfo.partner_list)
  return partner_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo >&
PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::partner_list() const {
  // @@protoc_insertion_point(field_list:PB_RoleMirageTerritoryInfoData.MirageTerritoryAllInfo.partner_list)
  return partner_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::PB_RoleMirageTerritoryInfoData_MirageTerritoryInfo >*
PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo::mutable_partner_list() {
  // @@protoc_insertion_point(field_mutable_list:PB_RoleMirageTerritoryInfoData.MirageTerritoryAllInfo.partner_list)
  return &partner_list_;
}

// -------------------------------------------------------------------

// PB_RoleMirageTerritoryInfoData

// repeated .PB_RoleMirageTerritoryInfoData.MirageTerritoryAllInfo pertner_data_list = 1;
inline int PB_RoleMirageTerritoryInfoData::pertner_data_list_size() const {
  return pertner_data_list_.size();
}
inline void PB_RoleMirageTerritoryInfoData::clear_pertner_data_list() {
  pertner_data_list_.Clear();
}
inline const ::PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo& PB_RoleMirageTerritoryInfoData::pertner_data_list(int index) const {
  // @@protoc_insertion_point(field_get:PB_RoleMirageTerritoryInfoData.pertner_data_list)
  return pertner_data_list_.Get(index);
}
inline ::PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo* PB_RoleMirageTerritoryInfoData::mutable_pertner_data_list(int index) {
  // @@protoc_insertion_point(field_mutable:PB_RoleMirageTerritoryInfoData.pertner_data_list)
  return pertner_data_list_.Mutable(index);
}
inline ::PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo* PB_RoleMirageTerritoryInfoData::add_pertner_data_list() {
  // @@protoc_insertion_point(field_add:PB_RoleMirageTerritoryInfoData.pertner_data_list)
  return pertner_data_list_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo >&
PB_RoleMirageTerritoryInfoData::pertner_data_list() const {
  // @@protoc_insertion_point(field_list:PB_RoleMirageTerritoryInfoData.pertner_data_list)
  return pertner_data_list_;
}
inline ::google::protobuf::RepeatedPtrField< ::PB_RoleMirageTerritoryInfoData_MirageTerritoryAllInfo >*
PB_RoleMirageTerritoryInfoData::mutable_pertner_data_list() {
  // @@protoc_insertion_point(field_mutable_list:PB_RoleMirageTerritoryInfoData.pertner_data_list)
  return &pertner_data_list_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_role_5fmirageterritory_5fdata_2eproto__INCLUDED
